[[_rgfis_persistence-layer_PersistenceSessionServiceInternal]]
= `PersistenceSessionServiceInternal`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


The (internal) `PersistenceSessionServiceInternal` domain service acts as a facade to the underlying JDO persistence session / database connection.  As such it provides methods for querying and for persisting objects.

[NOTE]
====
The default implementation of this service is not request-scoped, however all of the methods delegate
to the `PersistenceSession` of the current `IsisSession` - obtained from the thread-local of `IsisSessionFactory` singleton service.
So, in effect the service does act as if it is request scoped.
====



== SPI

The SPI of the service is a hierarchy of types.  First is `AdapterManagerBase`:

[source,java]
----
public interface AdapterManagerBase {
    ObjectAdapter getAdapterFor(Object pojo);           // <1>
    ObjectAdapter adapterFor(Object domainObject);      // <2>
----
<1> Gets the `ObjectAdapter` for the specified domain object if it exists in the identity map, else returns `null`.
<2> Looks up or creates a standalone (value) or root adapter.

The `AdapterManager` is the immediate subtype:

[source,java]
----
public interface AdapterManager extends AdapterManagerBase {
    ObjectAdapter getAdapterFor(Object pojo);                       // <1>
    ObjectAdapter adapterFor(                                       // <2>
        Object pojo, ObjectAdapter parentAdapter,
        OneToManyAssociation collection);
    ObjectAdapter mapRecreatedPojo(Oid oid, Object recreatedPojo);  // <3>
    void removeAdapter(ObjectAdapter adapter);                      // <4>
}
----
<1> Gets the `ObjectAdapter` for the `Oid` if it exists in the identity map.
<2> Looks up or creates a collection adapter.
<3> Enable RecreatableObjectFacet to 'temporarily' map an existing pojo to an oid.
<4> Enable RecreatableObjectFacet to remove a 'temporarily' mapped an adapter for a pojo.


Finally, `PersistenceSessionServiceInternal` is a subtype of `AdapterManager`:

[source,java]
----
public interface PersistenceSessionServiceInternal extends AdapterManager {

    // instantiate
    ObjectAdapter createTransientInstance(
                    ObjectSpecification spec);
    ObjectAdapter createViewModelInstance(
                    ObjectSpecification spec, String memento);

    // retrieve
    void resolve(Object parent);
    @Deprecated
    void resolve(Object parent, Object field);
    Object lookup(Bookmark bookmark, final BookmarkService.FieldResetPolicy fieldResetPolicy);
    Bookmark bookmarkFor(Object domainObject);
    Bookmark bookmarkFor(Class<?> cls, String identifier);

    // beginTran, flush, commit, currentTransaction
    void beginTran();
    boolean flush();
    void commit();
    Transaction currentTransaction();
    void executeWithinTransaction(TransactionalClosure transactionalClosure);

    // makePersistent, remove
    void makePersistent(ObjectAdapter adapter);
    void remove(ObjectAdapter adapter);
    // allMatchingQuery, firstMatchingQuery
    <T> List<ObjectAdapter> allMatchingQuery(Query<T> query);
    <T> ObjectAdapter firstMatchingQuery(Query<T> query);
}
----


== Runtime vs Noop implementation

The framework provides two implementations:

* `PersistenceSessionServiceInternalDefault` is provided by `isis-core-runtime`, and is used during normal use and integration tests

* `PersistenceSessionServiceInternalNoop` is provided as a fallback by `isis-core-metamodel`, and is provided to allow the xref:rg:mvn:rgmvn.adoc#[maven plugin] to be bootstrapped without any "backend" database.

The `...Default` implementation takes priority over the `...Noop` implementation.
