[[_rgant-DomainObjectLayout_iconUiEvent]]
= iconUiEvent()
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/


Whenever a domain object is to be rendered, the framework fires off an icon UI event to obtain an icon (name) for the object (if possible).
This is as an alternative to implementing xref:../rgcms/rgcms.adoc#_rgcms_methods_reserved_iconName[`iconName()`] reserved method.
(If `iconName()` is present, then it will take precedence).

Subscribers subscribe through the xref:../rgsvc/rgsvc.adoc#_rgsvc_core-domain-api_EventBusService[`EventBusService`] and can use obtain a reference to the domain object from the event.
From this they can, if they wish, specify an icon name for the domain object using the event's API.


[NOTE]
====
The feature was originally introduced so that xref:../rgant/rgant.adoc#_rgant-XmlRootElement[`@XmlRootElement`]-annotated xref:../ugfun/ugfun.adoc#_ugfun_building-blocks_types-of-domain-objects_view-models[view model]s could be kept as minimal as possible, just defining the data.
UI events allow subscribers to provide UI hints, while xref:../ugfun/ugfun.adoc#_ugfun_building-blocks_types-of-domain-objects_mixins[mixin]s can be used to provide the behaviour.
====

By default the event raised is `IconUiEvent.Default`.
For example:

[source,java]
----
@DomainObjectLayout
public class ToDoItemDto {
    ...
}
----

The purpose of the `iconUiEvent()` attribute is to allows a custom subclass to be emitted instead.
A similar attribute is available for titles and CSS classes.

For example:

[source,java]
----
@DomainObjectLayout(
    iconUiEvent=ToDoItemDto.IconUiEvent.class
)
public class ToDoItemDto {
    public static class IconUiEvent
        extends org.apache.isis.applib.services.eventbus.IconUiEvent<ToDoItemDto> { }
    ...
}
----

The benefit is that subscribers can be more targeted as to the events that they subscribe to.




== Subscribers

Subscribers (which must be domain services) subscribe using either the link:https://github.com/google/guava[Guava] API or (if the xref:../rgsvc/rgsvc.adoc#_rgsvc_core-domain-api_EventBusService[`EventBusService`] has been appropriately configured) using the link:http://www.axonframework.org/[Axon Framework] API.
The examples below are compatible with both.

Subscribers can be either coarse-grained (if they subscribe to the top-level event type):

[source,java]
----
@DomainService(nature=NatureOfService.DOMAIN)
public class SomeSubscriber extends AbstractSubscriber {
    @org.axonframework.eventhandling.annotation.EventHandler // if using axon
    @com.google.common.eventbus.Subscribe                    // if using guava
    public void on(IconUiEvent ev) {
        if(ev.getSource() instanceof ToDoItemDto) { ... }
    }
}
----

or can be fine-grained (by subscribing to specific event subtypes):

[source,java]
----
@DomainService(nature=NatureOfService.DOMAIN)
public class SomeSubscriber extends AbstractSubscriber {
    @org.axonframework.eventhandling.annotation.EventHandler // if using axon
    @com.google.common.eventbus.Subscribe                    // if using guava
    public void on(ToDoItemDto.IconUiEvent ev) {
        ...
    }
}
----

The subscriber should then use `IconUiEvent#setIconName(...)` to actually specify the icon name to be used.




== Default, Doop and Noop events

If the `iconUiEvent` attribute is not explicitly specified (is left as its default value, `IconUiEvent.Default`), then the framework will, by default, post an event.

If this is not required, then the `isis.reflector.facet.domainObjectLayoutAnnotation.iconUiEvent.postForDefault` configuration property can be set to "false"; this will disable posting.

On the other hand, if the `iconUiEvent` has been explicitly specified to some subclass, then an event will be posted.
The framework provides `IconUiEvent.Doop` as such a subclass, so setting the `iconUiEvent` attribute to this class
will ensure that the event to be posted, irrespective of the configuration property setting.

And, conversely, the framework also provides `IconUiEvent.Noop`; if `iconUiEvent` attribute is set to this class,
then no event will be posted.



== Raising events programmatically

Normally events are only raised for interactions through the UI.
However, events can be raised programmatically either by calling the xref:../rgsvc/rgsvc.adoc#_rgsvc_core-domain-api_EventBusService[`EventBusService`] API directly, or as a result of calling the xref:../rgsvc/rgsvc.adoc#_rgsvc_core-domain-api_DomainObjectContainer[`DomainObjectContainer`]'s `iconNameOf(...)` method.


