[[_rgant-Property_publishing]]
= `publishing()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/




The `publishing()` attribute determines whether and how a property edit is published via the registered implementation of a xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublishingService[`PublishingService`]) or xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublisherService[`PublisherService`].
This attribute is also supported for xref:../rgant/rgant.adoc#_rgant-DomainObject_publishing[domain objects], where it controls whether changed objects are published as events, and for xref:../rgant/rgant.adoc#_rgant-Property_publishing[`@Property#publishing()`], where it controls whether property edits are published as events.

A common use case is to notify external "downstream" systems of changes in the state of the Apache Isis application.
The default value for the attribute is `AS_CONFIGURED`, meaning that the
xref:../rgcfg/rgcfg.adoc#_rgcfg_configuring-core[configuration property] `isis.services.publish.properties` is used to
determine the whether the property is published:

* `all`
+
all property edits are published

* `none`
+
no property edits are published

If there is no configuration property in `isis.properties` then publishing is automatically enabled.

This default can be overridden on an property-by-property basis; if `publishing()` is set to `ENABLED` then the
property edit is published irrespective of the configured value; if set to `DISABLED` then the property edit is
_not_ published, again irrespective of the configured value.

For example:

[source,java]
----
public class Order {
    @Property(publishing=Publishing.ENABLED)        // <1>
    public int getQuantity() { ... }
    public void setQuantity(int quantity) { ... }
}
----
<1> because set to enabled, will be published irrespective of the configured value.

