[[_rgant-ParameterLayout_named]]
= `named()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/



The `named()` attribute explicitly specifies the action parameter's name.

Unlike most other aspects of the Apache Isis metamodel, the name of method parameters cannot (prior to Java 8, at least) be inferred from the Java source code.
Without other information, Apache Isis uses the object's type (`int`, `String` etc) as the name instead.
This can be sufficient for application-specific reference types (eg `ToDoItem`) but is generally not sufficient for primitives and other value types.
The `named()` attribute is therefore often required to specify the parameter name.

As of Java 8, the Java reflection API has been extended.
The (non-ASF) link:http://platform.incode.org[Incode Platform^]'s paraname8 metamodel extension provides support for this.
Note that your application must (obviously) be running on Java 8, and be compiled with the `-parameters` compile flag for javac.



By default the name is HTML escaped.
To allow HTML markup, set the related `namedEscaped()` attribute to `false`.

For example:

[source,java]
----
public class Customer {
    public Order placeOrder(
            final Product product
           ,@ParameterLayout(named="Quantity")
            final int quantity) {
        Order order = newTransientInstance(Order.class);
        order.modifyCustomer(this);
        order.modifyProduct(product);
        order.setQuantity(quantity);
        return order;
    }
    ...
}
----


[TIP]
====
The framework also provides a separate, powerful mechanism for xref:../ugbtb/ugbtb.adoc#_ugbtb_i18n[internationalization].
====

== See also

This attribute can also be specified for:

* xref:../rgant/rgant.adoc#_rgant-ActionLayout_named[actions]
* xref:../rgant/rgant.adoc#_rgant-CollectionLayout_named[collections]
* xref:../rgant/rgant.adoc#_rgant-PropertyLayout_named[properties]
* xref:../rgant/rgant.adoc#_rgant-DomainObjectLayout_named[domain objects]
* xref:../rgant/rgant.adoc#_rgant-ViewModelLayout_named[view models]
* xref:../rgant/rgant.adoc#_rgant-DomainServiceLayout_named[domain services].

