End users interact with link:https://isis.apache.org/userguide/${ISIS_VERSION}/fun/overview.html#view-models[view models] in the same as a domain entity.

However, whereas domain entities are mapped to a datastore, view models are not.
Instead they are recreated dynamically by serializing their state, typically into the URL itself.

The framework provides a number of ways to serialize this state, but the most flexible and standard is to use JAXB annotations:

[source,java]
----
@XmlRootElement(name = "demoapp.DemoStatefulViewModel")     // <.>
@XmlType                                                    // <.>
@XmlAccessorType(XmlAccessType.FIELD)                       // <.>
@DomainObject(
        nature=Nature.VIEW_MODEL
        , objectType = "demoapp.DemoStatefulViewModel"
)
public class StatefulViewModelUsingJaxb implements HasAsciiDocDescription {

    // ...

    @Property(editing = Editing.ENABLED)
    @Getter @Setter
    private String message;                                 // <.>
}
----

<.> mandatory, specifies this is a JAXB element
<.> mandatory boilerplate
<.> serializes the state by reading the field
<.> no further JAXB annotations required for the property.

Notice how the 'message' property can be modified and survives a refresh of the page.

Behind the scenes, the object is converted into an XML serialization, and that is URL encoded.

As you can see this can result in long URLs.
If the URL is too long, or needs to be encrypted, then the link:https://isis.apache.org/refguide/${ISIS_VERSION}/applib-svc/UrlEncodingService.html[`UrlEncodingService`] SPI can provide for different serializations.

