{
  rich {
    university_dept_Departments {
      findDepartmentByName {
        invoke(name: "Physics") {
          results {
            instrumentedStaffMembers {
              window(offset: 4, size: 2) {
                returnedCount
                rows {
                  name { get }
                }
              }
            }
          }
        }
      }
    }
  }
}
