{
  rich {
    university_dept_Departments {
      findDepartmentByName {
        invoke(name: "Classics") {
          results {
            changeDeptHead {
              params {
                newDeptHead {
                  datatype
                  autoComplete(search: "Ho") {
                    name {
                      get
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
