{
  rich {
    university_dept_Departments {
      findDepartmentByName {
        invoke(name: "Classics") {
          results {
            name {
              get
            }
            staffMembers {
              datatype
              get {
                name {
                  get
                }
              }
            }
          }
        }
      }
    }
  }
}
