[[_ugvw_customisation_custom-javascript]]
= Custom Javascript
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The Wicket viewer ships with embedded JQuery, so this can be leveraged, for example to perform arbitrary transformations of the rendered page on page load.

[WARNING]
====
Just because something is possible, it doesn't necessarily mean we encourage it.
Please be aware that there is no formal API for any custom javascript that you might implement to target; future versions of Apache Isis might break your code.

If possible, consider using the `ComponentFactory` API described in the xref:ug:vw:ugvw.adoc#_ugvw_extending[Extending] chapter.
====

To register your Javascript code, then just specify the appropriate configuration property:


[source,java]
----
isis.viewer.wicket.application.js=stylesheets/myapp.js
----

This file is resolved relative to `src/main/webapp`.

Currently only one such `.js` file can be registered.




