
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



== Implementation

This is an SPI, and the framework provides several implementations.

NOTE: The framework allows multiple implementations of this service to be registered; all will be called.

=== Applib (Log4j2)

The applib provides a simple implementation, xref:refguide:applib:index/services/publishing/log/ExecutionLogger.adoc[], that just logs events as they are received.

It can be configured using:

[source,xml]
.log4j2-spring.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
  <Properties> ... </Properties>
  <Appenders> ... </Appenders>
  <Loggers>
    ...
    <logger
      name="org.apache.causeway.applib.services.publishing.log.ExecutionLogger"
      level="debug"/>
    ...
  </Loggers>
</Configuration>
----

See the `log4j2-spring.xml` file in xref:docs:starters:simpleapp.adoc[simpleapp] for the omitted detail.

=== Execution Log

The xref:userguide:executionlog:about.adoc[] module also provides an implementation, xref:refguide:extensions:index/executionlog/applib/spiimpl/ExecutionSubscriberForExecutionLog.adoc[].
This implementation persists an instance of the xref:refguide:extensions:index/executionlog/applib/dom/ExecutionLogEntry.adoc[] entity for each event.

=== Execution Outbox

The xref:userguide:executionoutbox:about.adoc[] module also provides an implementation, xref:refguide:extensions:index/executionoutbox/applib/spiimpl/ExecutionSubscriberForExecutionOutbox.adoc[].
This implementation persists an instance of the xref:refguide:extensions:index/executionoutbox/applib/dom/ExecutionOutboxEntry.adoc[] entity for each event.
