= Side effects
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


Often when the state of an object is modified there is a business rule for some sort of side-effect.
For example, suppose that a `Person` has a persisted derived property:

[source,java]
----
public class Person {

    @Getter @Setter                     // <1>
    private LocalDate dateOfBirth;

    @Getter @Setter
    private int age;                    // <2>
----
<1> using Lombok to remove boilerplate.
<2> persisted derived property based on `dateOfBirth`.

One design would be to only allow the two properties to be modified through an action:

[source,java]
----
public Person updateDateOfBirth(LocalDate dateOfBirth) {
    setDateOfBirth(dateOfBirth);
    setAge(Years.between(clockService.now(), dateOfBirth));
    return this;
}
----

Alternatively we could allow the property to be edited, and then compute the side-effect.

[source,java]
----
public void setDateOfBirth(LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    setAge(Years.between(clockService.now(), dateOfBirth));
    return this;
}
----

Datanucleus does _not_ call the setter when reloading the object from the database, so there is no issue in having the side-effect code (calling `setAge(...)`).

[NOTE]
====
The framework also allows side-effect code to be placed in separate xref:refguide:applib-cm:methods.adoc#modify[`modify...()`], xref:refguide:applib-cm:methods.adoc#clear[`clear...()`] supporting methods; if present then these will be called by the framework rather than the setter.
However, because of DataNucleus' smart handling of setters, these supporting methods are in essence redundant, and so should be considered deprecated.
====
