<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements. See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to you under the Apache License, Version 2.0.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.apache.causeway.regressiontests</groupId>
        <artifactId>causeway-regressiontests-referenceapp</artifactId>
        <version>4.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>causeway-regressiontests-referenceapp-domain</artifactId>
    <name>Apache Causeway Regression Tests - Reference Application Domain</name>

    <properties>
        <maven.jar.phase>package</maven.jar.phase>
        <jar-plugin.automaticModuleName>org.apache.causeway.regressiontests.referenceapp.domain</jar-plugin.automaticModuleName>
        <git-plugin.propertiesDir>org/apache/causeway/regressiontests/referenceapp/domain</git-plugin.propertiesDir>
    </properties>

    <build>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
                <includes>
                    <include>application.yml</include>
                </includes>
            </resource>
            <resource>
                <filtering>false</filtering>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <filtering>false</filtering>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.rat</groupId>
                <artifactId>apache-rat-plugin</artifactId>
                <configuration>
                    <excludes combine.children="append">
                        <exclude>src/main/java/demoapp/dom/**/*_*.java</exclude>
                        <exclude>src/main/java/demoapp/dom/**/package-info.java</exclude>
                        <exclude>src/main/java/demoapp/dom/_infra/docgen/SuppressDocumentation.java</exclude>
                        <exclude>src/main/java/demoapp/dom/_infra/samples/**</exclude>
                        <exclude>src/main/java/demoapp/dom/domain/properties/ValueSemantics/percentage/**</exclude>
                        <exclude>src/main/java/demoapp/dom/types/causeway/clobs/samples/**</exclude>
                        <exclude>src/main/java/demoapp/dom/types/javamath/bigdecimals/meta/Money.java</exclude>
                        <exclude>src/main/resources/banner.txt</exclude>
                        <exclude>src/main/resources/static/**</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-pdfjs-applib</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-secman-integration</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-secman-encryption-spring</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.testing</groupId>
            <artifactId>causeway-testing-h2console-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-sse-applib</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.valuetypes</groupId>
            <artifactId>causeway-valuetypes-asciidoc-metamodel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.valuetypes</groupId>
            <artifactId>causeway-valuetypes-markdown-metamodel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.valuetypes</groupId>
            <artifactId>causeway-valuetypes-vega-metamodel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-docgen-help</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-fullcalendar-applib</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-secman-persistence-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-commandlog-persistence-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-sessionlog-persistence-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-executionlog-persistence-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-executionoutbox-persistence-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.extensions</groupId>
            <artifactId>causeway-extensions-audittrail-persistence-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.valuetypes</groupId>
            <artifactId>causeway-valuetypes-asciidoc-persistence-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.valuetypes</groupId>
            <artifactId>causeway-valuetypes-markdown-persistence-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.causeway.valuetypes</groupId>
            <artifactId>causeway-valuetypes-vega-persistence-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-opentelemetry</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-otlp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
