= Actions
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:

The business rules described above (xref:business-rules/visibility.adoc[visibility], xref:business-rules/usability.adoc[usability], xref:business-rules/validity.adoc[validity]) are business rules that enforce preconditions

The actual business logic is implemented in the form of actions: methods that are invokable by the user to allow them to accomplish some sort of goal.
Rather than have the end-user have to edit individual properties of numerous objects, an action can encode these rules and allow only safe transformations of the application from one consistent state to the next.

Examples could be: "place order", "award compensation", "approve an invoice", "check installation" and so on.



