= Prerequisites
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:partial-page:


Apache Isis is a Java based framework, so in terms of prerequisites, you'll need to install:

* Java 7 or 8 JDK
* link:http://maven.apache.org[Apache Maven] 3.x

You'll probably also want to use an IDE; the Apache Isis committers use either IntelliJ or Eclipse; in the xref:support:dg:ide.adoc[Developers' Guide] we have detailed setup instructions for using these two IDEs.
If you're a NetBeans user you should have no problems as it too has strong support for Maven.

When building and running within an IDE, you'll also need to configure the Datanucleus enhancer.
This is implemented as a Maven plugin, so in the case of IntelliJ, it's easy enough to run the enhancer as required.
It should be just as straightforward for NetBeans too.

For Eclipse the maven integration story is a little less refined.
All is not lost, however; DataNucleus also has an implementation of the enhancer as an Eclipse plugin, which usually works well enough.

