:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

(since 2.0.0-M2)

When running this demo using one of the JEE enabled images (eg.
`payara`), this simple singleton bean is managed by the EJB container
via `CDI`:

[source,java]
----
import javax.ejb.Singleton;

@Singleton
public class JeeDemoService {

    public String getMessage() {
        return "Hello World from JEE";
    }

}
----

Now we can verify that domain object service injection also works with
CDI managed beans:

[source,java]
----
@DomainObject
public class JeeDemo {

    @Inject private JeeDemoService jeeDemoService;

    @Action
    public String getJeeMessage(){
        return jeeDemoService.getMessage();
    }

    ...

}
----

See the sources for this demo here:
link:${SOURCES_DEMO}/demoapp/dom/jee[sources].

== Container Managed Connection Pool (advanced JEE usage):

You need to setup your JEE container's built-in connection pool inside
the container first. This is vendor specific. You than can use this
connection pool via `JNDI` lookup.

=== Setup JDO

....
isis.persistence.jdo-datanucleus.impl.datanucleus.ConnectionFactoryName=jdbc/demo-domain
isis.persistence.jdo-datanucleus.impl.datanucleus.ConnectionFactory2Name=jdbc/demo-domain-nontx
isis.persistence.jdo-datanucleus.impl.javax.jdo.option.TransactionType=JTA
....

=== Setup JNDI resource provider

Add a singleton bean to your application, that provides the lookup
resources.

[source,java]
----
import javax.ejb.*;

@Singleton
@Startup
public class ConnectionResources {

    @Resource(lookup="jdbc/demo-domain")
    private javax.sql.DataSource domainDS;

    @Resource(lookup="jdbc/demo-domain-nontx")
    private javax.sql.DataSource domainDS_nontx;

}
----
