= From v1.15.x to 1.16.0
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]




== `AppManifest2` and `Module`

While not required, it is recommended to rework modules to subclass from `ModuleAbstract`, and to bootstrap the application using `AppManifestAbstract2`.


== `IntegrationTestAbstract3`

While not required, it is recommended that integration tests are updated to subclass from `IntegrationTestAbstract3`.
These require a `Module` to bootstrap from (see above).


== Explicitly-defined actions

By default actions are implicitly recognised as any remaining `public` methods once properties/collections and supporting methods are discounted.
Any methods that are _not_ intended to be actions have previously required to be annotated with `@Programmatic`.

Setting:

[source,ini]
----
isis.reflector.explicitAnnotations.action=true
----

reverses this policy: left-over `public` methods will not be treated as actions unless they also have an `@Action` annotation.



== `isis-mavendeps-intellij` Aggregator POM

The contents of the `org.apache.isis.mavendeps:isis-mavendeps-intellij` aggregator has been moved to `org.apache.isis.mavendeps:isis-mavendeps-webapp`.

Since these are commonly found together in the webapp module, the `isis-mavendeps-intellij` reference can therefore simply be removed.

Note that `isis-mavendeps-webapp` has been updated with support for running within Eclipse IDE.



== (non-ASF) Incode Platform

The generic subdomain modules of the (non-ASF) link:http://platform.incode.org["Incode Platform"] have been demoted to instead act as examples.

Rather than consume as binaries, the recommendation is to copy in the source code into your application and adapt as required.

For the time being, the binaries will continue to be released, but to avoid confusions the `groupId:artifactId` and the packages have been changed.

For example, the _alias_ generic subdomain has moved:

* from: `org.incode.module.alias:incode-module-alias-dom`
* to:  `org.incode.example.alias:incode-example-alias-dom`

The package has similarly changed:

* from: `org.incode.module.alias`
* to: `org.incode.example.alias`

The full list of generic subdomains that have been renamed to examples is: _alias, classification, commchannel, communications, country, docfragment, document, note, settings_ and _tags_.

