[[_migration-notes_1.10.0-to-1.11.0]]
= From v1.10.0 to 1.11.0
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


Existing projects written against v1.10.0 should run against v1.11.0 with few if any changes.
If you *do* encounter any difficulties then let us know via the link:https://isis.apache.org/versions/1.11.0/support.html[users mailing list], so we can support you and document issues here.



== Swagger UI

The new link:https://isis.apache.org/versions/1.11.0/guides/rgsvc/rgsvc.html#_rgsvc_metadata-api_SwaggerService[`SwaggerService`] allows link:http://swagger.io[Swagger] spec files to be generated from the Apache Isis metamodel.
These can be downloaded directly through the `SwaggerResource` (mapped to `/restful/swagger/public` and `/restful/swagger/private`) as well as from the Wicket UI through the `SwaggerServiceMenu`.

In addition, the link:https://isis.apache.org/versions/1.11.0/guides/ugfun/ugfun.html#_ugfun_getting-started_simpleapp-archetype[SimpleApp archetype] now bundles link:https://github.com/swagger-api/swagger-ui[Swagger UI], which documents the main features of the REST API and allows it to be explored.

To enable this in your application, first update the `web.xml`:

[source,xml]
----
<servlet>
    <servlet-name>WebjarsServlet</servlet-name>                         <!--1-->
    <servlet-class>org.webjars.servlet.WebjarsServlet</servlet-class>
    <init-param>
        <param-name>disableCache</param-name>
        <param-value>false</param-value>
    </init-param>
    <load-on-startup>2</load-on-startup>
</servlet>
<servlet-mapping>
    <servlet-name>WebjarsServlet</servlet-name>
    <url-pattern>/webjars/*</url-pattern>
</servlet-mapping>
...
<filter>
    <filter-name>IsisSessionFilterForRestfulObjects</filter-name>
    ...
    <init-param>
        <param-name>whenNoSession</param-name>
        <param-value>auto</param-value>                                 <!--2-->
    </init-param>
    <init-param>
        <param-name>passThru</param-name>                               <!--3-->
        <param-value>/restful/swagger</param-value>
    </init-param>
</filter>
----
<1> provides access to the Swagger UI (packaged as a webjar)
<2> issues a 401 status, but with the `WWW-Authenticate` challenge suppressed if requested from the Swagger UI
<3> provides access to the RESTful resource that generates the Swagger spec.

There is also an HTML page to load the Swagger UI itself; this resides in `src/main/webapp/swagger-ui/index.html`.
Copy the link:https://github.com/apache/isis/blob/master/example/application/simpleapp/webapp/src/main/webapp/swagger-ui/index.html[file from Apache Isis' repo], or from the app generated by the link:https://isis.apache.org/versions/1.11.0/guides/ugfun/ugfun.html#_ugfun_getting-started_simpleapp-archetype[SimpleApp archetype].

The text of the simple app's `about/index.html` has also changed (the `<li`> for the `/restful` URL has been replaced with a `/swagger-ui` URL).
If you use link:https://github.com/apache/isis/blob/master/example/application/simpleapp/webapp/src/main/webapp/about/index.html[this file], then update it.

If your application is bootstrapped using an `AppManifest` (recommended; link:https://isis.apache.org/versions/1.11.0/guides/rgcms/rgcms.html#_rgcms_classes_AppManifest-bootstrapping[here]) then the default implementation of the `SwaggerService` will automatically be discovered and registered.
However, if you are still using the older `isis.properties` configuration file to explicitly register services then you will need to add in this service.



== `RoutingService`

The new link:https://isis.apache.org/versions/1.11.0/guides/rgsvc/rgsvc.html#_rgsvc_presentation-layer-spi_RoutingService[`RoutingService`] SPI service provides a plugin point to the link:https://isis.apache.org/versions/1.11.0/guides/ugvw/ugvw.html[Wicket viewer] so that a different object than that returned from an action invocation can be rendered.

The framework provides a default implementation of this service that will - instead of a void or a `null` result - render the home page (as per the link:https://isis.apache.org/versions/1.11.0/guides/rgant/rgant.html#_rgant-HomePage[`@HomePage`] annotation) if there is one.
This is therefore a subtle change in the UI.
If you wish to retain the original behaviour (to return the "no results" page instead), then you should implement your own no-op implementation of this service:

[source,java]
----
@DomainService
@DomainServiceLayout(menuOrder="1")
public class IdentityRoutingService implements RoutingService {
    public boolean canRoute(Object original) { return true; }
    public Object route(Object original) { return original; }
}
----


== Wicket Viewer i18n

The link:https://isis.apache.org/versions/1.11.0/guides/ugvw/html.adoc#[Wicket viewer] (its labels, buttons, messages etc) can now be internationalized using the link:https://isis.apache.org/versions/1.11.0/guides/rgsvc/rgsvc.html#_rgsvc_presentation-layer-spi_TranslationService[`TranslationService`].

To enable this, new ``msgId``s and corresponding translations must be added to the `translations.po` file.
Full details of these ``msgId``s can be found in link:https://isis.apache.org/versions/1.11.0/guides/ugbtb/ugbtb.html#__ugbtb_i18n_wicket-viewer[i18n] section of the "beyond the basics" guide.

If no translations are available, then the fallback is to use the previous mechanism, ie Wicket's original resource bundles.
This feature can therefore be considered as optional.
