[[_migration-notes_1.13.0-to-1.14.0]]
= From v1.13.x to 1.14.0
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



== New metamodel validations

This release defines a number of metamodel validations.
These can be enabled or disabled using configuration properties:

* `isis.reflector.validator.explicitObjectType` +
+
Whether to check that the class has an object type explicitly specified somehow.
This is strongly recommended, but is disabled by default to prevent migration issues.

* `isis.reflector.validator.jdoqlFromClause` +
+
Whether to check that the class name in JDOQL `FROM` clause matches or is a supertype of the class on which it is annotated.
This is enabled by default.

* `isis.reflector.validator.jdoqlVariablesClause` +
+
Whether to check that the class name in JDOQL `VARIABLES` clause is a recognized class.
This is enabled by default.

* `isis.reflector.validator.mixinsOnly` +
+
This is disabled by default; if enabled, this configuration property will treat any contributed service as invalid; instead use mixins (as a simpler/less confusing programming model).

* `isis.reflector.validator.noParamsOnly` +
+
When searching for  link:https://isis.apache.org/versions/1.14.0/guides/rgcms/rgcms.html#_rgcms_methods_prefixes_disable[`disableXxx()`] or link:https://isis.apache.org/versions/1.14.0/guides/rgcms/rgcms.html#_rgcms_methods_prefixes_hide[`hideXxx()`] supporting methods, whether to search only for the no-param version (or also for supporting methods that match the parameter types of the action). +
+
This is disabled by default; if enabled then this makes for a simpler programming model.

* `isis.reflector.validator.serviceActionsOnly` +
+
Domain services are stateless (at least conceptually) and so should not have any properties or collections; any that are defined will not be rendered by the viewers. +
+
This is disabled by default; if enabled, then this ensure that domain services only declare actions and so makes for a simpler programming model.

