[[HomePageProviderService]]
= `HomePageProviderService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:



This service simply provides access to the home page object (if any) that is returned from the domain service action annotated with xref:refguide:applib-ant:HomePage.adoc[`@HomePage`].

It was originally introduced to support the default implementation of xref:refguide:applib-svc:presentation-layer-spi/RoutingService.adoc[`RoutingService`], but was factored out to support alternative implementations of that service (and may be useful for other use cases).


== SPI & Implementation

The SPI defined by `HomePageProviderService` is:

[source,java]
----
public interface HomePageProviderService {
    @Programmatic
    Object homePage();
}
----

The default implementation is provided by `o.a.i.core.runtime.services.homepage.HomePageProviderServiceDefault`.

Any custom implementations should be annotated using `@DomainService(nature = NatureOfService.DOMAIN)`.



