= Demo

The Demo provides an introduction to the features and components available in Apache Isis.

It allows you to learn the very basics and also to discover some of the more advanced features, the framework has to offer. See the Docker section below on how to get started.

== Getting Started (Docker)

== Docker

NOTE: Further on *<tag>* is used as a placeholder for the docker image tag of your choice. When omitted the latest version is used. Actual tag names might be changed without notice. Currently we have tag *nightly*. See https://hub.docker.com/r/apacheisis/demo-springboot/tags/[apacheisis/demo-springboot] (Docker-Hub)

=== Prereqs

Install https://www.docker.com/community-edition[Docker] on your computer.

=== Pulling the Docker Image

Pull the demo image using:

[source]
----
docker pull apacheisis/demo-springboot:<tag>
----

=== Running the Docker Image

Run the demo image using:

[source]
----
docker run --name demo --detach -p8080:8080 apacheisis/demo-springboot:<tag>
----

This will start a new Docker container named 'demo'.

The demo-app can then be accessed at http://localhost:8080/wicket/[].
Login with `sven:pass`.

To stop and remove the container named 'demo' use:

[source]
----
docker stop demo && docker rm demo
----

=== Customization - ContextPath

To run the _Demo_ using a _context-path_, add an environment variable eg. `ContextPath=/demo`.

[source]
----
docker run --name demo --detach -p8080:8080 -eContextPath=/demo apacheisis/demo-springboot:<tag>
----

=== Customization - Prototyping

To run the _Demo_ in _prototyping_ mode, add an environment variable `PROTOTYPING=true`.

[source]
----
docker run --name demo --detach -p8080:8080 -ePROTOTYPING=true apacheisis/demo-springboot:<tag>
----

=== Customization - Attached Console

To run the container with your console attached, replace the '--detach' argument with '-it'. (Use CTRL-C to stop and detach.)

[source]
----
docker run --name demo -it -p8080:8080 apacheisis/demo-springboot:<tag>
----

== Contributing

If you like to get involved quickly, please feel free to open new pull requests (at github) or just join the discussion and provide feedback.

If you are interested in contributing to Apache Isis, see the https://isis.apache.org/guides/dg/dg.html[Developers' Guide] for details. 


== Credits

This Demo App uses icons made by link:http://www.freepik.com[Freepik] and
link:https://www.flaticon.com/authors/smashicons[Smashicons].
These are licensed by link:http://creativecommons.org/licenses/by/3.0/[Creative Commons BY 3.0^]
