= CommandReplayOnPrimaryService
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.CommandReplayOnPrimaryService.java
----
class CommandReplayOnPrimaryService {
  @Inject
final CommandJdoRepository commandServiceRepository;
  @Inject
final JaxbService jaxbService;
  @Inject
final MessageService messageService;
  @Inject
final ContentMappingServiceForCommandsDto contentMappingServiceForCommandsDto;
  @Inject
final CommandRetrievalService commandRetrievalService;
  List<CommandJdo> findCommands(final UUID uniqueId, final Integer batchSize)     // <.>
  Integer default1FindCommandsOnPrimaryFrom()
  Clob downloadCommands(final UUID uniqueId, final Integer batchSize, final String filenamePrefix)     // <.>
  Integer default1DownloadCommands()
  String default2DownloadCommands()
  Clob downloadCommandById(final UUID uniqueId, final String filenamePrefix)     // <.>
  String default1DownloadCommandById()
}
----

<.> xref:#findCommands__UUID_Integer[findCommands(UUID, Integer)]
+
--
These actions should be called with HTTP Accept Header set to: `application/xml;profile="urn:org.restfulobjects:repr-types/action-result";x-ro-domain-type="org.apache.isis.schema.cmd.v1.CommandsDto"` 
--
<.> xref:#downloadCommands__UUID_Integer_String[downloadCommands(UUID, Integer, String)]
+
--
These actions should be called with HTTP Accept Header set to: `application/xml;profile="urn:org.restfulobjects:repr-types/action-result";x-ro-domain-type="org.apache.isis.schema.cmd.v1.CommandsDto"` 
--
<.> xref:#downloadCommandById__UUID_String[downloadCommandById(UUID, String)]
+
--
This action should be called with HTTP Accept Header set to: `application/xml;profile="urn:org.restfulobjects:repr-types/action-result";x-ro-domain-type="org.apache.isis.schema.cmd.v1.CommandDto"` 
--

== Members

[#findCommands__UUID_Integer]
=== findCommands(UUID, Integer)

These actions should be called with HTTP Accept Header set to: `application/xml;profile="urn:org.restfulobjects:repr-types/action-result";x-ro-domain-type="org.apache.isis.schema.cmd.v1.CommandsDto"` 

[#downloadCommands__UUID_Integer_String]
=== downloadCommands(UUID, Integer, String)

These actions should be called with HTTP Accept Header set to: `application/xml;profile="urn:org.restfulobjects:repr-types/action-result";x-ro-domain-type="org.apache.isis.schema.cmd.v1.CommandsDto"` 

[#downloadCommandById__UUID_String]
=== downloadCommandById(UUID, String)

This action should be called with HTTP Accept Header set to: `application/xml;profile="urn:org.restfulobjects:repr-types/action-result";x-ro-domain-type="org.apache.isis.schema.cmd.v1.CommandDto"` 
