= loadedLifecycleEvent()
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


Whenever a persistent domain object is loaded from the database, a "loaded" lifecycle event is fired.

Subscribers subscribe through the xref:rg:svc:core-domain-api/EventBusService.adoc[`EventBusService`] and can use the event to obtain a reference to the domain object just loaded.
The subscriber could then, for example, update or default values on the object (eg to support on-the-fly migration scenarios).

By default the event raised is `ObjectLoadedEvent.Default`. For example:

[source,java]
----
@DomainObject
public class ToDoItemDto {
    ...
}
----

The purpose of the `loadedLifecycleEvent()` attribute is to allows a custom subclass to be emitted instead.
A similar attribute is available for other lifecycle events.

For example:

[source,java]
----
@DomainObjectLayout(
    loadedLifecycleEvent=ToDoItem.LoadedEvent.class
)
public class ToDoItem {
    public static class LoadedEvent
        extends org.apache.isis.applib.events.lifecycle.ObjectLoadedEvent<ToDoItem> { }
    ...
}
----

The benefit is that subscribers can be more targeted as to the events that they subscribe to.




== Subscribers

Subscribers (which must be domain services) subscribe using either the link:https://github.com/google/guava[Guava] API or (if the xref:rg:svc:core-domain-api/EventBusService.adoc[`EventBusService`] has been appropriately configured) using the link:http://www.axonframework.org/[Axon Framework] API.
The examples below support both.

Subscribers can be either coarse-grained (if they subscribe to the top-level event type):

[source,java]
----
@DomainService(nature=NatureOfService.DOMAIN)
public class SomeSubscriber extends AbstractSubscriber {
    @org.axonframework.eventhandling.EventHandler       // if using axon
    @com.google.common.eventbus.Subscribe               // if using guava
    public void on(ObjectLoadedEvent ev) {
        if(ev.getSource() instanceof ToDoItem) { ... }
    }
}
----

or can be fine-grained (by subscribing to specific event subtypes):

[source,java]
----
@DomainService(nature=NatureOfService.DOMAIN)
public class SomeSubscriber extends AbstractSubscriber {
    @org.axonframework.eventhandling.EventHandler       // if using axon
    @com.google.common.eventbus.Subscribe               // if using guava
    public void on(ToDoItem.ObjectLoadedEvent ev) {
        ...
    }
}
----






== Default, Doop and Noop events

If the `loadedLifecycleEvent` attribute is not explicitly specified (is left as its default value, `ObjectLoadedEvent.Default`), then the framework will, by default, post an event.

If this is not required, then the `isis.reflector.facet.domainObjectAnnotation.loadedLifecycleEvent.postForDefault` configuration property can be set to "false"; this will disable posting.

On the other hand, if the `loadedLifecycleEvent` has been explicitly specified to some subclass, then an event will be posted.
The framework provides `ObjectLoadedEvent.Doop` as such a subclass, so setting the `loadedLifecycleEvent` attribute to this class will ensure that the event to be posted, irrespective of the configuration property setting.

And, conversely, the framework also provides `ObjectLoadedEvent.Noop`; if `loadedLifecycleEvent` attribute is set to this class, then no event will be posted.




