[#mementoSerialization]
= `mementoSerialization()`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:



The `mementoSerialization` attribute indicates that the collection should be included or excluded from any snapshots generated by the xref:refguide:applib-svc:XmlSnapshotService.adoc[`XmlSnapshotService`].

For example:

[source,java]
----
import lombok.Getter;
import lombok.Setter;

public class Customer {

    @Collection(mementoSerialization=EXCLUDED)
    @Getter @Setter
    private SortedSet<Order> previousOrders = ...

}
----


Alternatively, if the collection is derived, then providing only a "getter" will also work:

[source,java]
----
public class Customer {

    public SortedSet<Order> getPreviousOrders() {...}
    ...
}
----

== See also

This attribute is also supported for xref:refguide:applib-ant:Property.adoc#mementoSerialization[properties].

