{
  university_dept_Departments {
    findByName {
      invoke(name: "Classics") {
        removeStaffMember {
          params {
            staffMember {
              choices {
                name {
                  get
                }
              }
            }
          }
        }
      }
    }
  }
}
