{
  university_dept_DeptHeadMenu {
    findDeptHeadByName {
      invoke(name: "foo") {
        _gql_mutations {
          changeName {
            invoke(newName: "bar") {
              name
              department {
                name
              }
            }
          }
        }
      }
    }
  }
}
