{
  university_dept_Departments {
    createDepartment {
      params {
        name {
          disabled(name: "")
        }
      }
      invokeNonIdempotent(name: "newbie") {
        name {
          get
        }
      }
    }
  }
}
