{
  university_dept_DeptHeads {
    findHeadByName {
      invoke(name: "foo") {
        changeName {
          invokeIdempotent(newName: "bar") {
            name {
              get
            }
          }
        }
      }
    }
  }
}
