{
  university_dept_DepartmentMenu {
    _gql_mutations {
      createDepartment {
        hidden
        disabled
        invoke(name: "newbie") {
          name {
            get
          }
        }
      }
    }
  }
}
