{
    gql_test_domain_TopLevelMenu {
        findDeptHeadByName(name: "foo") {
            _gql_mutations {
                changeName(newName: "bar") {
                    name
                    department {
                        name
                    }
                }
            }
        }
    }
}
