{
  university_dept_DepartmentMenu {
    findAllDepartments {
      invoke {
        name {
          get
        }
        _gql_meta {
          id
          logicalTypeName
          version
        }
      }
    }
  }
}
