{
  university_dept_Departments {
    findAllDepartments {
      invoke {
        name {
          get
        }
        _gql_meta {
          logicalTypeName
          version
        }
      }
    }
  }
}
