[[_rgsvc_presentation-api_BookmarkUiService]]
= `BookmarkUiService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `BookmarkUiService` provides the ability to programmatically interact with bookmarked pages and breadcrumbs, as rendered by the Wicket viewer.

One possible use case is programmatically to support multiple "contexts" and allow the end-user to switch from one context to another.



== API & Implementation

The API defined by `BookmarkUiService` is:

[source,java]
----
public interface BookmarkUiService {
    void clear();   // <1>
}
----
<1> Simply clears the current list of breadcrumbs and bookmarks.

The xref:../ugvw/ugvw.adoc#[Wicket viewer] provides an implementation of this service, `o.a.i.viewer.wicket.viewer.services.BookmarkUiServiceWicket`.





