= `ApplicationFeatureRepository`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `ApplicationFeatureRepository` provides the access to string representations of the packages, classes and
class members (collectively: "application features") of the domain classes within the Apache Isis' internal metamodel.

[TIP]
====
This functionality was originally implemented as part of (non-ASF) link:http://platform.incode.org[Incode Platform^] security module, where the string representations of the various features are used to represent permissions.
====


== API

The API defined by the service is:

[source,java]
----
public interface ApplicationFeatureRepository {
    List<String> packageNames();
    List<String> packageNamesContainingClasses(ApplicationMemberType memberType);
    List<String> classNamesContainedIn(String packageFqn, ApplicationMemberType memberType);
    List<String> classNamesRecursivelyContainedIn(String packageFqn);
    List<String> memberNamesOf(String packageFqn, String className, ApplicationMemberType memberType);
}
----

where `ApplicationMemberType` in turn is:

[source,java]
----
public enum ApplicationMemberType {
    PROPERTY,
    COLLECTION,
    ACTION;
}
----

These methods are designed primarily to return lists of strings for use in drop-downs.


== Implementation

The default implementation of this service is `ApplicationFeatureRepositoryDefault`.


=== Configuration Properties

The default implementation of this domain service supports the following configuration properties:

[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(default value)
|Description

|`isis.services.` +
`applicationFeatures.` +
`init`
| `lazy`, `eager` +
(`lazy`)
|Whether the application features repository (which surfaces the framework's metamodel) should be
initialized lazily or eagerly.  +

Lazy initialization can speed up bootstrapping, useful while developing and running tests.

|===


=== Related Services

The default implementation of this service uses the `ApplicationFeatureFactory` service to instantiate `ApplicationFeature` instances.


