:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Mixins are a mechanism for decoupling behaviour from state, so that the behaviour of the mixin seemingly belongs to an underlying domain object, but in fact is implemented in a different class.
This is a particularly powerful capability for large "modular monoliths", because the mixin can reside in one module and the mixee (or contributee) can reside in another.
This is made even more powerful by the fact that the contributee can be an interface type rather than a concrete class.

The idiomatic way of writing mixins is as class that is annotated with link:https://causeway.apache.org/refguide/2.0.0-SNAPSHOT/applib/index/annotation/Property.html[@Property], link:https://causeway.apache.org/refguide/2.0.0-SNAPSHOT/applib/index/annotation/Collection.html[@Collection] or link:https://causeway.apache.org/refguide/2.0.0-SNAPSHOT/applib/index/annotation/Action.html[@Action].
These require that the mixin class has a single primary method representing the domain member being contributed.
By default the name of this method is "prop" for properties, "coll" for collections, and "act" for actions.
This default is defined through the link:https://causeway.apache.org/refguide/2.0.0-SNAPSHOT/applib/index/annotation/DomainObject.html#mixinmethod[@DomainObject#mixinmethod]; if you look into their definition you will see that the `@Property,` `@Collection` and `@Action` are all meta-annotated with `@DomainObject#mixinMethod`.

In most circumstances there will be little need to use `@DomainObject#mixinMethod` directly.
However, if you prefer some other method names other than the defaults then you can annotate your mixins with this annotation; or define your own annotation (eg `@MyAction`) and meta-annotate it with both `@Action` and `@DomainObject#mixinMethod` as appropriate.


=== How this demo works

The collection on the left is a mixin to this view model, but (for demonstration purposes) uses `@DomainObject#mixinMethod` to change the default method name from "coll" to "collection":

[source,java,indent=0]
.DomainObjectMixinMethodVm_objects.java
----
include::DomainObjectMixinMethodVm_objects.java[tags=class]
----
<.> overrides the default mixin method
<.> method representing the contributed domain collection, using the overridden method name

Similarly, the "updateName" action shown on the collection panel is also a mixin, allowing the name of any object to be updated.
This also overrrides the default name:

[source,java,indent=0]
.DomainObjectMixinMethodVm_updateName.java
----
include::DomainObjectMixinMethodVm_updateName.java[tags=class]
----
<.> overrides the default mixin method
<.> method representing the contributed domain collection, using the overridden method name

The 'initialCharacter' column in the table is also a mixin, this time of the domain class in the collection.
Navigate through to the entity to inspect that mixin's source code.
