[[hidden]]
= `hidden()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:




Actions can be hidden at the domain-level, indicating that they are not visible to the end-user.

[TIP]
====
It is also possible to use xref:refguide:applib-ant:ActionLayout.adoc#hidden[`@ActionLayout#hidden()`] or xref:vw:ROOT:layout.adoc#file-based[file-based layouts] such that the action can be hidden at the view layer.
Both options are provided with a view that in the future the view-layer semantics may be under the control of (expert) users, whereas domain-layer semantics should never be overridden or modified by the user.
====

For example:

[source,java]
----
public class Customer {
    @Action(hidden=Where.EVERYWHERE)
    public void updateStatus() { /* ... */ }
    ...
}
----

The acceptable values for the `where` parameter are:

* `Where.EVERYWHERE` or `Where.ANYWHERE` +
+
The action should be hidden at all times.

* `Where.NOWHERE` +
+
The action should not be hidden.


The other values of the `Where` enum have no meaning for a collection.



[NOTE]
====
For actions of domain services the visibility is dependent upon its xref:refguide:applib-ant:DomainService.adoc#nature[`@DomainService#nature()`] and also on whether it is contributed (as per  xref:refguide:applib-ant:ActionLayout.adoc#contributedAs[`@ActionLayout#contributedAs()`]).
====



== See also

This attribute can also be applied to:

* xref:refguide:applib-ant:Property.adoc#hidden[properties]
* xref:refguide:applib-ant:Collection.adoc#hidden[collections].

