[#Blob]
= `Blob`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


`Blob` (in the `org.apache.isis.applib.value` package) is a value type defined by the Apache Isis framework to represent a binary large object.
Conceptually you can consider it as a set of bytes (a picture, a video etc), though in fact it wraps three pieces of information:

* the set of bytes
* a name
* a mime type.

This is reflected in the class' constructors and properties:

// TODO: v2: use include::[]

[source,java]
----
import lombok.Getter;

public final class Blob ... {

    public Blob(
            String name,
            String primaryType, String subtype,
            byte[] bytes) {
        // ...
    }
    public Blob(
            String name,
            String mimeTypeBase,
            byte[] bytes) {
        // ...
    }
    public Blob(
            String name,
            MimeType mimeType,
            byte[] bytes) {
        // ...
    }

    @Getter
    private String name;
    @Getter
    private MimeType mimeType;
    @Getter
    private byte[] bytes;

    // ...
}
----

Mandatory properties of this type can be mapped with xref:pjdo:ROOT:about.adoc[JDO/DataNucleus] using:

[source,java]
----
import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.Column;

@Persistent(defaultFetchGroup="false", columns = {
    @Column(name = "someImage_name"
            , allowsNull = "false"),
    @Column(name = "someImage_mimetype"
            , allowsNull = "false"),
    @Column(name = "someImage_bytes"
            , allowsNull = "false")
})
private Blob someImage;
----

while optional properties can be mapped the same, but using `allowsNull = "true` for each of the ``@Column``s.

