@startuml
set separator none
title Payment Terminal - System Context

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<FraudDetector>> {
  BackgroundColor #dddddd
  FontColor #fffffe
  BorderColor #9a9a9a
  shadowing false
}
skinparam person<<Merchant>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
  shadowing false
}
skinparam rectangle<<PaymentTerminal>> {
  BackgroundColor #dddddd
  FontColor #fffffe
  BorderColor #9a9a9a
  shadowing false
}

person "==Merchant\n<size:10>[Person]</size>\n\nMerchant" <<Merchant>> as Merchant
rectangle "==Payment Terminal\n<size:10>[Software System]</size>\n\nPayment Terminal" <<PaymentTerminal>> as PaymentTerminal
rectangle "==Fraud Detector\n<size:10>[Software System]</size>\n\nFraud Detector" <<FraudDetector>> as FraudDetector

Merchant .[#707070,thickness=2].> PaymentTerminal : "<color:#707070>Makes payment"
PaymentTerminal .[#707070,thickness=2].> FraudDetector : "<color:#707070>Obtains fraud score"
@enduml