= Menu
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


Menu services provide actions to be rendered on the menu.

For the Wicket viewer, each service's actions appear as a collection of menu items of a named menu, and this menu is on one of the three menu bars provided by the Wicket viewer.  It is possible for more than one menu service's actions to appear on the same menu; a separator is shown between each.

For the Restful Objects viewer, all menu services are shown in the services representation.

We suggest naming such classes `XxxMenu`, eg:


[source,java]
----
@DomainService(                                                 // <1>
    nature = NatureOfService.VIEW_MENU_ONLY
)
@DomainServiceLayout(                                           // <2>
        named = "Customers",
        menuBar = DomainServiceLayout.MenuBar.PRIMARY,
        menuOrder = "10"
)
public class CustomerMenu {

    @Action(
            semantics = SemanticsOf.SAFE
    )
    @ActionLayout(bookmarking = BookmarkPolicy.AS_ROOT)
    @MemberOrder( sequence = "1" )
    public List<Customer> findByName(                           // <3>
            @ParameterLayout(named="Name")                      // <4>
            final String name
    ) {
        return customerRepository.findByName(name);             // <5>
    }

    @Action(
            semantics = SemanticsOf.NON_IDEMPOTENT
    )
    @MemberOrder( sequence = "3" )
    public Customer newCustomer(...) {
        return customerRepository.newCustomer(...);
    }

    @Action(
            semantics = SemanticsOf.SAFE,
            restrictTo = RestrictTo.PROTOTYPING                 // <6>
    )
    @MemberOrder( sequence = "99" )
    public List<Customer> listAll() {
        return customerRepository.listAll();
    }

    @Inject
    protected CustomerRepository customerRepository;            // <4>
}
----
<1> The (Apache Isis) xref:rg:ant:DomainService.adoc[`@DomainService`] annotation is used to identify the class as a domain service.
Apache Isis scans the classpath looking for classes with this annotation, so there very little configuration other than to tell the framework which packages to scan underneath.
The `VIEW_MENU_ONLY` nature indicates that this service's actions should be exposed as menu items.
<2> The xref:rg:ant:DomainServiceLayout.adoc[`@DomainServiceLayout`] annotation provides UI hints.
The menu is named "Customers" (otherwise it would have defaulted to "Customer Menu", based on the class name, while the xref:rg:ant:DomainServiceLayout/menuOrder.adoc[`menuOrder`] attribute determines the order of the menu with respect to other menu services.
<3> The `findByName` method is annotated with various Apache Isis annotations (xref:rg:ant:Action.adoc[`@Action`], xref:rg:ant:ActionLayout.adoc[`@ActionLayout`] and xref:rg:ant:MemberOrder.adoc[`@MemberOrder`] and is itself rendered in the UI as a "Find By Name" menu item underneath the "Simple Objects" menu.
<4> The xref:rg:ant:ParameterLayout.adoc[`@ParameterLayout`] provides metadata for the parameter itself, in this case its name.
<5> the action implementation delegates to an injected repository.
The framework can inject into not just other domain services but will also automatically into domain entities and view models.
There is further discussion of service injection xref:ug:fun:ugfun.adoc#_ugfun_programming-model_inject-services[below].
<6> xref:rg:ant:Action/restrictTo.adoc[Prototype] actions are rendered only in prototyping mode.
A "list all" action such as this can be useful when exploring the domain with a small dataset.

[TIP]
====
Annotating action parameters with xref:rg:ant:ParameterLayout/named.adoc[`@ParameterLayout#named()`] can become somewhat tiresome.
You can avoid doing this by configuring the (non-ASF) link:http://platform.incode.org[Incode Platform^]'s paraname8 metamodel extension.
====


Not every action on the repository need to be delegated to of course (the above example does but only because it is very simple).

[TIP]
====
While there's nothing to stop `VIEW_MENU` domain services being injected into other domain objects and interacted with programmatically, we recommend against it.
Instead, inject the underlying repository.
If there is additional business logic, then consider introducing a further `DOMAIN`-scoped service and call that instead.
====


