= i18n Concerns

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


The GraphQL Specification (link:https://spec.graphql.org/October2021/#sec-Names[]) requires that names of fields and types use only a subset of ASCII characters.
On the other hand the GraphQL viewer will infer these fields from the Java domain objects, which permits a wider range of characters.

To ensure that only permitted characters are used in the GraphQL model, provide an implementation of the xref:refguide:applib:index/services/ascii/AsciiIdentifierService.adoc[AsciiIdentifierService].

For example, suppose this class is part of the domain:

[source,java]
.I18nCalculator
----
@Named("university.calc.I18nCalculator")
@DomainService
@Priority(PriorityPrecedence.EARLY)
@RequiredArgsConstructor(onConstructor_ = {@Inject})
public class I18nCalculator {

    @Action(semantics = SemanticsOf.SAFE)
    public String concät(
            String ä1,
            String ä2) {
        return ä1 + ä2;
    }
}
----

As this service uses a non-ASCII character, `ä`, we need to provide a service to convert it:

[source,java]
.AsciiIdentifierServiceSupportingGraphqlViewer
----
@Service
public class AsciiIdentifierServiceSupportingGraphqlViewer
    implements AsciiIdentifierService {

    public String asciiIdFor(String featureId) {
        return featureId.replace("ä", "a");
    }
}
----

This implementation could be fairly easily be extended for other Latin languages, but non-Latin languages such as Kanji would obviously need a more sophisticated implementation.
