= AbstractInterval
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.AbstractInterval.java
----
class AbstractInterval<T> {
  AbstractInterval()
  AbstractInterval(Interval interval)
  AbstractInterval(LocalDate startDate, LocalDate endDate)
  AbstractInterval(LocalDate startDate, LocalDate endDate, IntervalEnding ending)
  Interval asInterval()
  boolean contains(LocalDate date)     // <.>
  boolean contains(T localDateInterval)     // <.>
  int days()     // <.>
  LocalDate endDate()
  LocalDate endDate(IntervalEnding ending)
  LocalDate endDateExcluding()
  LocalDate endDateFromStartDate()
  boolean isValid()
  T overlap(T otherInterval)     // <.>
  boolean overlaps(T interval)     // <.>
  LocalDate startDate()
  boolean within(T interval)     // <.>
  boolean isInfinite()
  boolean isOpenEnded()
}
----

<.> xref:#contains__LocalDate[contains(LocalDate)]
+
--
Does this date contain the specified time interval.
--
<.> xref:#contains__T[contains(T)]
+
--
Does this time interval contain the specified time interval.
--
<.> xref:#days__[days()]
+
--
The duration in days
--
<.> xref:#overlap__T[overlap(T)]
+
--
Gets the overlap between this interval and another interval.
--
<.> xref:#overlaps__T[overlaps(T)]
+
--
Does this time interval contain the specified time interval.
--
<.> xref:#within__T[within(T)]
+
--
Does this interval is within the specified interval
--

== Members

[#contains__LocalDate]
=== contains(LocalDate)

Does this date contain the specified time interval.

[#contains__T]
=== contains(T)

Does this time interval contain the specified time interval.

[#days__]
=== days()

The duration in days

[#overlap__T]
=== overlap(T)

Gets the overlap between this interval and another interval.

[#overlaps__T]
=== overlaps(T)

Does this time interval contain the specified time interval.

[#within__T]
=== within(T)

Does this interval is within the specified interval
