= BSCol
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

A column within a row which, depending on its _#getSpan()_ , could be as narrow as 1/12th of the page's width, all the way up to spanning the entire page.

Pretty much other content can be contained within a column, though most commonly it will be xref:refguide:applib:index/layout/component/FieldSet.adoc[FieldSet] s (a group of properties) or xref:refguide:applib:index/layout/component/CollectionLayoutData.adoc[CollectionLayoutData] s. However, columns can also be used to contain further xref:refguide:applib:index/layout/grid/bootstrap/BSRow.adoc[BSRow] s (creating a nested grid of rows/cols/rows/cols) and xref:refguide:applib:index/layout/grid/bootstrap/BSTabGroup.adoc[BSTabGroup] s.

It is rendered as a (eg) <div class="col-md-4 ...">

== API

[source,java]
.BSCol.java
----
class BSCol {
  String getId()     // <.>
  void setId(String id)
  int getSpan()
  void setSpan(int span)
  Boolean isUnreferencedActions()     // <.>
  void setUnreferencedActions(Boolean unreferencedActions)
  Boolean isUnreferencedCollections()     // <.>
  void setUnreferencedCollections(Boolean unreferencedCollections)
  DomainObjectLayoutData getDomainObject()     // <.>
  void setDomainObject(DomainObjectLayoutData domainObjectLayoutData)
  List<SizeSpan> getSizeSpans()
  void setSizeSpans(List<SizeSpan> sizeSpans)
  List<ActionLayoutData> getActions()
  void setActions(List<ActionLayoutData> actions)
  List<BSRow> getRows()
  void setRows(List<BSRow> rows)
  List<BSTabGroup> getTabGroups()
  void setTabGroups(List<BSTabGroup> tabGroups)
  List<FieldSet> getFieldSets()
  void setFieldSets(List<FieldSet> fieldSets)
  List<CollectionLayoutData> getCollections()
  void setCollections(List<CollectionLayoutData> collections)
  String getMetadataError()     // <.>
  void setMetadataError(String metadataError)
  String toCssClass()
  String toString()
}
----

<.> xref:#getId_[getId()]
+
--
As per <div id="...">...</div> : must be unique across entire page.
--
<.> xref:#isUnreferencedActions_[isUnreferencedActions()]
+
--
Whether this column should be used to hold any unreferenced actions (contributed or "native").
--
<.> xref:#isUnreferencedCollections_[isUnreferencedCollections()]
+
--
Whether this column should be used to hold any unreferenced collections (contributed or "native").
--
<.> xref:#getDomainObject_[getDomainObject()]
+
--
Whether to show the object's icon and title.
--
<.> xref:#getMetadataError_[getMetadataError()]
+
--
For diagnostics; populated by the framework if and only if a metadata error.
--

== Members

[#getId_]
=== getId()

As per <div id="...">...</div> : must be unique across entire page.

[#isUnreferencedActions_]
=== isUnreferencedActions()

Whether this column should be used to hold any unreferenced actions (contributed or "native").

Any layout must have precisely one column or xref:refguide:applib:index/layout/component/FieldSet.adoc[FieldSet] that has this attribute set.

[#isUnreferencedCollections_]
=== isUnreferencedCollections()

Whether this column should be used to hold any unreferenced collections (contributed or "native").

Any layout must have precisely one column or xref:refguide:applib:index/layout/grid/bootstrap/BSTabGroup.adoc[BSTabGroup] that has this attribute set.

[#getDomainObject_]
=== getDomainObject()

Whether to show the object's icon and title.

[#getMetadataError_]
=== getMetadataError()

For diagnostics; populated by the framework if and only if a metadata error.
