= BSTabGroup
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Represents a tab group containing one or more xref:refguide:applib:index/layout/grid/bootstrap/BSTab.adoc[BSTab] s.

== API

[source,java]
.BSTabGroup.java
----
class BSTabGroup {
  Boolean isUnreferencedCollections()     // <.>
  void setUnreferencedCollections(Boolean unreferencedCollections)
  Boolean isCollapseIfOne()     // <.>
  void setCollapseIfOne(Boolean collapseIfOne)
  List<BSTab> getTabs()
  void setTabs(List<BSTab> tabs)
  BSTabGroupOwner getOwner()     // <.>
  void setOwner(BSTabGroupOwner owner)
  String getMetadataError()     // <.>
  void setMetadataError(String metadataError)
  BSGrid getGrid()
}
----

<.> xref:#isUnreferencedCollections_[isUnreferencedCollections()]
+
--
Whether this tab group should be used to hold any unreferenced collections (contributed or "native").
--
<.> xref:#isCollapseIfOne_[isCollapseIfOne()]
+
--
If there is a single tab in the tabgroup, then whether to collapse and render without the outer tab.
--
<.> xref:#getOwner_[getOwner()]
+
--
Owner.
--
<.> xref:#getMetadataError_[getMetadataError()]
+
--
For diagnostics; populated by the framework if and only if a metadata error.
--

== Members

[#isUnreferencedCollections_]
=== isUnreferencedCollections()

Whether this tab group should be used to hold any unreferenced collections (contributed or "native").

Any layout must have precisely one tab group or xref:refguide:applib:index/layout/grid/bootstrap/BSCol.adoc[BSCol] that has this attribute set.

[#isCollapseIfOne_]
=== isCollapseIfOne()

If there is a single tab in the tabgroup, then whether to collapse and render without the outer tab.

[#getOwner_]
=== getOwner()

Owner.

Set programmatically by framework after reading in from XML.

[#getMetadataError_]
=== getMetadataError()

For diagnostics; populated by the framework if and only if a metadata error.
