"Marks the field, argument, input field or enum value as deprecated"
directive @deprecated(
    "The reason for the deprecation"
    reason: String = "No longer supported"
  ) on FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE | INPUT_FIELD_DEFINITION

"Directs the executor to include this field or fragment only when the `if` argument is true"
directive @include(
    "Included when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Directs the executor to skip this field or fragment when the `if` argument is true."
directive @skip(
    "Skipped when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Exposes a URL that specifies the behaviour of this scalar."
directive @specifiedBy(
    "The URL that specifies the behaviour of this scalar."
    url: String!
  ) on SCALAR

type Query {
  causeway_applib_UserMenu: causeway_applib_UserMenu
  causeway_conf_ConfigurationMenu: causeway_conf_ConfigurationMenu
  causeway_security_LogoutMenu: causeway_security_LogoutMenu
  numServices: Int
  university_dept_DepartmentMenu: university_dept_DepartmentMenu
  university_dept_DeptHeadMenu: university_dept_DeptHeadMenu
}

type causeway_applib_DomainObjectList {
  _gql_meta: causeway_applib_DomainObjectList__gql_meta
  actionArguments: String
  actionId: String
  actionOwningFqcn: String
  elementTypeFqcn: String!
  title: String!
}

type causeway_applib_DomainObjectList__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_FacetGroupNode {
  _gql_meta: causeway_applib_FacetGroupNode__gql_meta
  facets: String!
}

type causeway_applib_FacetGroupNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_ParameterNode {
  _gql_meta: causeway_applib_ParameterNode__gql_meta
  parameter: String!
  parentNode: causeway_applib_node_ActionNode!
}

type causeway_applib_ParameterNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_PropertyNode {
  _gql_meta: causeway_applib_PropertyNode__gql_meta
  _gql_mutations: causeway_applib_PropertyNode__gql_mutations
  mixedIn: String!
  parentNode: causeway_applib_TypeNode!
  property: String!
}

type causeway_applib_PropertyNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_PropertyNode__gql_mutations {
  streamChildNodes: causeway_applib_PropertyNode__streamChildNodes
}

type causeway_applib_PropertyNode__streamChildNodes {
  disabled: String
  hidden: Boolean
  invoke: java_util_stream_Stream
}

type causeway_applib_RoleMemento {
  _gql_meta: causeway_applib_RoleMemento__gql_meta
  description: String!
  name: String!
}

type causeway_applib_RoleMemento__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_TypeNode {
  _gql_meta: causeway_applib_TypeNode__gql_meta
  domainClassDto: causeway_schema_metamodel_v2_DomainClassDto!
}

type causeway_applib_TypeNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_UserMemento {
  _gql_meta: causeway_applib_UserMemento__gql_meta
  authenticationCode: String!
  authenticationSource: String!
  avatarUrl: String
  impersonating: String!
  languageLocale: String
  multiTenancyToken: String
  name: String!
  numberFormatLocale: String
  realName: String
  roles: [causeway_applib_RoleMemento]
  timeFormatLocale: String
}

type causeway_applib_UserMemento__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_UserMenu {
  me: causeway_applib_UserMenu__me
}

type causeway_applib_UserMenu__me {
  disabled: String
  hidden: Boolean
  invoke: causeway_applib_UserMemento
}

type causeway_applib_node_ActionNode {
  _gql_meta: causeway_applib_node_ActionNode__gql_meta
  _gql_mutations: causeway_applib_node_ActionNode__gql_mutations
  action: String!
  mixedIn: String!
  parentNode: causeway_applib_TypeNode!
}

type causeway_applib_node_ActionNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_node_ActionNode__gql_mutations {
  streamChildNodes: causeway_applib_node_ActionNode__streamChildNodes
}

type causeway_applib_node_ActionNode__streamChildNodes {
  disabled: String
  hidden: Boolean
  invoke: java_util_stream_Stream
}

type causeway_applib_node_CollectionNode {
  _gql_meta: causeway_applib_node_CollectionNode__gql_meta
  _gql_mutations: causeway_applib_node_CollectionNode__gql_mutations
  collection: String!
  mixedIn: String!
  parentNode: causeway_applib_TypeNode!
}

type causeway_applib_node_CollectionNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_node_CollectionNode__gql_mutations {
  streamChildNodes: causeway_applib_node_CollectionNode__streamChildNodes
}

type causeway_applib_node_CollectionNode__streamChildNodes {
  disabled: String
  hidden: Boolean
  invoke: java_util_stream_Stream
}

type causeway_applib_node_FacetAttrNode {
  _gql_meta: causeway_applib_node_FacetAttrNode__gql_meta
  facetAttr: String!
  parentNode: causeway_applib_node_FacetNode!
}

type causeway_applib_node_FacetAttrNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_node_FacetNode {
  _gql_meta: causeway_applib_node_FacetNode__gql_meta
  facet: String!
  shadowed: String!
}

type causeway_applib_node_FacetNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_conf_ConfigurationMenu {
  configuration: causeway_conf_ConfigurationMenu__configuration
}

type causeway_conf_ConfigurationMenu__configuration {
  disabled: String
  hidden: Boolean
  invoke: causeway_conf_ConfigurationViewmodel
}

type causeway_conf_ConfigurationProperty {
  _gql_meta: causeway_conf_ConfigurationProperty__gql_meta
  key: String!
  value: String!
}

type causeway_conf_ConfigurationProperty__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_conf_ConfigurationViewmodel {
  _gql_meta: causeway_conf_ConfigurationViewmodel__gql_meta
  environment: [causeway_conf_ConfigurationProperty]
  primary: [causeway_conf_ConfigurationProperty]
  secondary: [causeway_conf_ConfigurationProperty]
}

type causeway_conf_ConfigurationViewmodel__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationFeatureViewModel {
  _gql_meta: causeway_feat_ApplicationFeatureViewModel__gql_meta
  memberName: String!
  namespaceName: String!
  typeSimpleName: String!
}

type causeway_feat_ApplicationFeatureViewModel__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationNamespace {
  _gql_meta: causeway_feat_ApplicationNamespace__gql_meta
  memberName: String!
  namespaceName: String!
  typeSimpleName: String!
}

type causeway_feat_ApplicationNamespace__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationType {
  _gql_meta: causeway_feat_ApplicationType__gql_meta
  actions: [causeway_feat_ApplicationTypeAction]
  collections: [causeway_feat_ApplicationTypeCollection]
  memberName: String!
  namespaceName: String!
  properties: [causeway_feat_ApplicationTypeProperty]
  typeSimpleName: String!
}

type causeway_feat_ApplicationTypeAction {
  _gql_meta: causeway_feat_ApplicationTypeAction__gql_meta
  actionSemantics: String!
  memberName: String!
  namespaceName: String!
  returnType: String!
  typeSimpleName: String!
}

type causeway_feat_ApplicationTypeAction__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationTypeCollection {
  _gql_meta: causeway_feat_ApplicationTypeCollection__gql_meta
  derived: String!
  elementType: String!
  memberName: String!
  namespaceName: String!
  typeSimpleName: String!
}

type causeway_feat_ApplicationTypeCollection__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationTypeMember {
  _gql_meta: causeway_feat_ApplicationTypeMember__gql_meta
  memberName: String!
  namespaceName: String!
  typeSimpleName: String!
}

type causeway_feat_ApplicationTypeMember__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationTypeProperty {
  _gql_meta: causeway_feat_ApplicationTypeProperty__gql_meta
  derived: String!
  maxLength: String
  memberName: String!
  namespaceName: String!
  returnType: String!
  typeSimpleName: String!
  typicalLength: String
}

type causeway_feat_ApplicationTypeProperty__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationType__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_schema_metamodel_v2_DomainClassDto {
  _gql_meta: causeway_schema_metamodel_v2_DomainClassDto__gql_meta
  actions: String!
  annotations: String!
  collections: String!
  facets: String!
  id: String!
  majorVersion: String
  minorVersion: String
  properties: String!
  service: String!
}

type causeway_schema_metamodel_v2_DomainClassDto__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_security_LoginRedirect {
  _gql_meta: causeway_security_LoginRedirect__gql_meta
}

type causeway_security_LoginRedirect__gql_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_security_LogoutMenu {
  logout: causeway_security_LogoutMenu__logout
}

type causeway_security_LogoutMenu__logout {
  disabled: String
  hidden: Boolean
  invoke: String
}

type causeway_testing_fixtures_FixtureResult {
  _gql_meta: causeway_testing_fixtures_FixtureResult__gql_meta
  className: String!
  fixtureScriptClassName: String
  key: String!
}

type causeway_testing_fixtures_FixtureResult__gql_meta {
  id: String!
  logicalTypeName: String!
}

type java_lang_Runnable {
  _gql_meta: java_lang_Runnable__gql_meta
}

type java_lang_Runnable__gql_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_Map {
  _gql_meta: java_util_Map__gql_meta
}

type java_util_Map__gql_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_SortedMap {
  _gql_meta: java_util_SortedMap__gql_meta
}

type java_util_SortedMap__gql_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_concurrent_Callable {
  _gql_meta: java_util_concurrent_Callable__gql_meta
}

type java_util_concurrent_Callable__gql_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_function_BiFunction {
  _gql_meta: java_util_function_BiFunction__gql_meta
}

type java_util_function_BiFunction__gql_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_function_Consumer {
  _gql_meta: java_util_function_Consumer__gql_meta
}

type java_util_function_Consumer__gql_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_function_Function {
  _gql_meta: java_util_function_Function__gql_meta
}

type java_util_function_Function__gql_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_stream_Stream {
  _gql_meta: java_util_stream_Stream__gql_meta
}

type java_util_stream_Stream__gql_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_commons_functional_Either {
  _gql_meta: org_apache_causeway_commons_functional_Either__gql_meta
  _gql_mutations: org_apache_causeway_commons_functional_Either__gql_mutations
  left: String!
  right: String!
}

type org_apache_causeway_commons_functional_Either__accept {
  disabled: String
  hidden: Boolean
  invoke(leftConsumer: java_util_function_Consumer__gql_input!, rightConsumer: java_util_function_Consumer__gql_input!): String
}

type org_apache_causeway_commons_functional_Either__gql_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_commons_functional_Either__gql_mutations {
  accept: org_apache_causeway_commons_functional_Either__accept
  left: org_apache_causeway_commons_functional_Either__left
  map: org_apache_causeway_commons_functional_Either__map
  mapLeft: org_apache_causeway_commons_functional_Either__mapLeft
  mapRight: org_apache_causeway_commons_functional_Either__mapRight
  right: org_apache_causeway_commons_functional_Either__right
}

type org_apache_causeway_commons_functional_Either__left {
  disabled: String
  hidden: Boolean
  invoke: String
}

type org_apache_causeway_commons_functional_Either__map {
  disabled: String
  hidden: Boolean
  invoke(leftMapper: java_util_function_Function__gql_input!, rightMapper: java_util_function_Function__gql_input!): org_apache_causeway_commons_functional_Either
}

type org_apache_causeway_commons_functional_Either__mapLeft {
  disabled: String
  hidden: Boolean
  invoke(leftMapper: java_util_function_Function__gql_input!): org_apache_causeway_commons_functional_Either
}

type org_apache_causeway_commons_functional_Either__mapRight {
  disabled: String
  hidden: Boolean
  invoke(rightMapper: java_util_function_Function__gql_input!): org_apache_causeway_commons_functional_Either
}

type org_apache_causeway_commons_functional_Either__right {
  disabled: String
  hidden: Boolean
  invoke: String
}

type org_apache_causeway_commons_functional_Railway {
  _gql_meta: org_apache_causeway_commons_functional_Railway__gql_meta
  _gql_mutations: org_apache_causeway_commons_functional_Railway__gql_mutations
  failure: String!
  success: String!
}

type org_apache_causeway_commons_functional_Railway__chain {
  disabled: String
  hidden: Boolean
  invoke(chainingFunction: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Railway
}

type org_apache_causeway_commons_functional_Railway__gql_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_commons_functional_Railway__gql_mutations {
  chain: org_apache_causeway_commons_functional_Railway__chain
  ifFailure: org_apache_causeway_commons_functional_Railway__ifFailure
  ifSuccess: org_apache_causeway_commons_functional_Railway__ifSuccess
  mapFailure: org_apache_causeway_commons_functional_Railway__mapFailure
  mapSuccess: org_apache_causeway_commons_functional_Railway__mapSuccess
}

type org_apache_causeway_commons_functional_Railway__ifFailure {
  disabled: String
  hidden: Boolean
  invoke(failureConsumer: org_apache_causeway_commons_functional_ThrowingConsumer__gql_input!): org_apache_causeway_commons_functional_Railway
}

type org_apache_causeway_commons_functional_Railway__ifSuccess {
  disabled: String
  hidden: Boolean
  invoke(successConsumer: org_apache_causeway_commons_functional_ThrowingConsumer__gql_input!): org_apache_causeway_commons_functional_Railway
}

type org_apache_causeway_commons_functional_Railway__mapFailure {
  disabled: String
  hidden: Boolean
  invoke(failureMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Railway
}

type org_apache_causeway_commons_functional_Railway__mapSuccess {
  disabled: String
  hidden: Boolean
  invoke(successMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Railway
}

type org_apache_causeway_commons_functional_ThrowingConsumer {
  _gql_meta: org_apache_causeway_commons_functional_ThrowingConsumer__gql_meta
  _gql_mutations: org_apache_causeway_commons_functional_ThrowingConsumer__gql_mutations
}

type org_apache_causeway_commons_functional_ThrowingConsumer__andThen {
  disabled: String
  hidden: Boolean
  invoke(arg0: java_util_function_Consumer__gql_input!): java_util_function_Consumer
}

type org_apache_causeway_commons_functional_ThrowingConsumer__gql_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_commons_functional_ThrowingConsumer__gql_mutations {
  andThen: org_apache_causeway_commons_functional_ThrowingConsumer__andThen
  throwing: org_apache_causeway_commons_functional_ThrowingConsumer__throwing
}

type org_apache_causeway_commons_functional_ThrowingConsumer__throwing {
  disabled: String
  hidden: Boolean
  invoke(exceptionWrapper: java_util_function_BiFunction__gql_input!): org_apache_causeway_commons_functional_ThrowingConsumer
}

type org_apache_causeway_commons_functional_ThrowingFunction {
  _gql_meta: org_apache_causeway_commons_functional_ThrowingFunction__gql_meta
  _gql_mutations: org_apache_causeway_commons_functional_ThrowingFunction__gql_mutations
}

type org_apache_causeway_commons_functional_ThrowingFunction__andThen {
  disabled: String
  hidden: Boolean
  invoke(arg0: java_util_function_Function__gql_input!): java_util_function_Function
}

type org_apache_causeway_commons_functional_ThrowingFunction__compose {
  disabled: String
  hidden: Boolean
  invoke(arg0: java_util_function_Function__gql_input!): java_util_function_Function
}

type org_apache_causeway_commons_functional_ThrowingFunction__gql_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_commons_functional_ThrowingFunction__gql_mutations {
  andThen: org_apache_causeway_commons_functional_ThrowingFunction__andThen
  compose: org_apache_causeway_commons_functional_ThrowingFunction__compose
  throwing: org_apache_causeway_commons_functional_ThrowingFunction__throwing
}

type org_apache_causeway_commons_functional_ThrowingFunction__throwing {
  disabled: String
  hidden: Boolean
  invoke(exceptionWrapper: java_util_function_BiFunction__gql_input!): org_apache_causeway_commons_functional_ThrowingFunction
}

type org_apache_causeway_commons_functional_ThrowingRunnable {
  _gql_meta: org_apache_causeway_commons_functional_ThrowingRunnable__gql_meta
  _gql_mutations: org_apache_causeway_commons_functional_ThrowingRunnable__gql_mutations
}

type org_apache_causeway_commons_functional_ThrowingRunnable__callUncatched {
  disabled: String
  hidden: Boolean
  invoke: String
}

type org_apache_causeway_commons_functional_ThrowingRunnable__gql_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_commons_functional_ThrowingRunnable__gql_mutations {
  callUncatched: org_apache_causeway_commons_functional_ThrowingRunnable__callUncatched
  run: org_apache_causeway_commons_functional_ThrowingRunnable__run
  runUncatched: org_apache_causeway_commons_functional_ThrowingRunnable__runUncatched
  toCallable: org_apache_causeway_commons_functional_ThrowingRunnable__toCallable
  toRunnable: org_apache_causeway_commons_functional_ThrowingRunnable__toRunnable
}

type org_apache_causeway_commons_functional_ThrowingRunnable__run {
  disabled: String
  hidden: Boolean
  invoke: String
}

type org_apache_causeway_commons_functional_ThrowingRunnable__runUncatched {
  disabled: String
  hidden: Boolean
  invoke: String
}

type org_apache_causeway_commons_functional_ThrowingRunnable__toCallable {
  disabled: String
  hidden: Boolean
  invoke: java_util_concurrent_Callable
}

type org_apache_causeway_commons_functional_ThrowingRunnable__toRunnable {
  disabled: String
  hidden: Boolean
  invoke: java_lang_Runnable
}

type org_apache_causeway_commons_functional_Try {
  _gql_meta: org_apache_causeway_commons_functional_Try__gql_meta
  _gql_mutations: org_apache_causeway_commons_functional_Try__gql_mutations
  failure: String!
  success: String!
}

type org_apache_causeway_commons_functional_Try__accept {
  disabled: String
  hidden: Boolean
  invoke(failureConsumer: org_apache_causeway_commons_functional_ThrowingConsumer__gql_input!, successConsumer: org_apache_causeway_commons_functional_ThrowingConsumer__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__flatMapSuccess {
  disabled: String
  hidden: Boolean
  invoke(successMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__flatMapSuccessAsNullable {
  disabled: String
  hidden: Boolean
  invoke(successMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__flatMapSuccessWhenPresent {
  disabled: String
  hidden: Boolean
  invoke(successMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__gql_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_commons_functional_Try__gql_mutations {
  accept: org_apache_causeway_commons_functional_Try__accept
  flatMapSuccess: org_apache_causeway_commons_functional_Try__flatMapSuccess
  flatMapSuccessAsNullable: org_apache_causeway_commons_functional_Try__flatMapSuccessAsNullable
  flatMapSuccessWhenPresent: org_apache_causeway_commons_functional_Try__flatMapSuccessWhenPresent
  ifAbsentFail: org_apache_causeway_commons_functional_Try__ifAbsentFail
  ifFailure: org_apache_causeway_commons_functional_Try__ifFailure
  ifFailureFail: org_apache_causeway_commons_functional_Try__ifFailureFail
  ifSuccess: org_apache_causeway_commons_functional_Try__ifSuccess
  ifSuccessAsNullable: org_apache_causeway_commons_functional_Try__ifSuccessAsNullable
  mapEmptyToFailure: org_apache_causeway_commons_functional_Try__mapEmptyToFailure
  mapFailure: org_apache_causeway_commons_functional_Try__mapFailure
  mapFailureToSuccess: org_apache_causeway_commons_functional_Try__mapFailureToSuccess
  mapSuccess: org_apache_causeway_commons_functional_Try__mapSuccess
  mapSuccessAsNullable: org_apache_causeway_commons_functional_Try__mapSuccessAsNullable
  mapSuccessWhenPresent: org_apache_causeway_commons_functional_Try__mapSuccessWhenPresent
  mapToEither: org_apache_causeway_commons_functional_Try__mapToEither
  orCall: org_apache_causeway_commons_functional_Try__orCall
  then: org_apache_causeway_commons_functional_Try__then
  thenCall: org_apache_causeway_commons_functional_Try__thenCall
  thenRun: org_apache_causeway_commons_functional_Try__thenRun
}

type org_apache_causeway_commons_functional_Try__ifAbsentFail {
  disabled: String
  hidden: Boolean
  invoke: org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__ifFailure {
  disabled: String
  hidden: Boolean
  invoke(exceptionConsumer: org_apache_causeway_commons_functional_ThrowingConsumer__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__ifFailureFail {
  disabled: String
  hidden: Boolean
  invoke: org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__ifSuccess {
  disabled: String
  hidden: Boolean
  invoke(valueConsumer: org_apache_causeway_commons_functional_ThrowingConsumer__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__ifSuccessAsNullable {
  disabled: String
  hidden: Boolean
  invoke(valueConsumer: org_apache_causeway_commons_functional_ThrowingConsumer__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__mapEmptyToFailure {
  disabled: String
  hidden: Boolean
  invoke: org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__mapFailure {
  disabled: String
  hidden: Boolean
  invoke(failureMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__mapFailureToSuccess {
  disabled: String
  hidden: Boolean
  invoke(recoveryMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__mapSuccess {
  disabled: String
  hidden: Boolean
  invoke(successMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__mapSuccessAsNullable {
  disabled: String
  hidden: Boolean
  invoke(successMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__mapSuccessWhenPresent {
  disabled: String
  hidden: Boolean
  invoke(successMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__mapToEither {
  disabled: String
  hidden: Boolean
  invoke(failureMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!, successMapper: org_apache_causeway_commons_functional_ThrowingFunction__gql_input!): org_apache_causeway_commons_functional_Either
}

type org_apache_causeway_commons_functional_Try__orCall {
  disabled: String
  hidden: Boolean
  invoke(fallback: java_util_concurrent_Callable__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__then {
  disabled: String
  hidden: Boolean
  invoke(next: java_util_concurrent_Callable__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__thenCall {
  disabled: String
  hidden: Boolean
  invoke(callable: java_util_concurrent_Callable__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_commons_functional_Try__thenRun {
  disabled: String
  hidden: Boolean
  invoke(runnable: org_apache_causeway_commons_functional_ThrowingRunnable__gql_input!): org_apache_causeway_commons_functional_Try
}

type org_apache_causeway_core_metamodel_inspect_model_MMNode {
  _gql_meta: org_apache_causeway_core_metamodel_inspect_model_MMNode__gql_meta
}

type org_apache_causeway_core_metamodel_inspect_model_MMNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_core_metamodel_inspect_model_MemberNode {
  _gql_meta: org_apache_causeway_core_metamodel_inspect_model_MemberNode__gql_meta
  _gql_mutations: org_apache_causeway_core_metamodel_inspect_model_MemberNode__gql_mutations
  mixedIn: String!
  parentNode: causeway_applib_TypeNode!
}

type org_apache_causeway_core_metamodel_inspect_model_MemberNode__gql_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_core_metamodel_inspect_model_MemberNode__gql_mutations {
  streamChildNodes: org_apache_causeway_core_metamodel_inspect_model_MemberNode__streamChildNodes
}

type org_apache_causeway_core_metamodel_inspect_model_MemberNode__streamChildNodes {
  disabled: String
  hidden: Boolean
  invoke: java_util_stream_Stream
}

type org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript {
  _gql_meta: org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__gql_meta
  friendlyName: String!
  qualifiedName: String!
}

type org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__gql_meta {
  id: String!
  logicalTypeName: String!
}

type university_dept_Department {
  _gql_meta: university_dept_Department__gql_meta
  deptHead: university_dept_DeptHead
  name: String!
}

type university_dept_DepartmentMenu {
  _gql_mutations: university_dept_DepartmentMenu__gql_mutations
  findAllDepartments: university_dept_DepartmentMenu__findAllDepartments
}

type university_dept_DepartmentMenu__adminAction {
  disabled: String
  hidden: Boolean
  invoke: String
}

type university_dept_DepartmentMenu__createDepartment {
  disabled: String
  hidden: Boolean
  invoke(deptHead: university_dept_DeptHead__gql_input, name: String!): university_dept_Department
}

type university_dept_DepartmentMenu__findAllDepartments {
  disabled: String
  hidden: Boolean
  invoke: [university_dept_Department]
}

type university_dept_DepartmentMenu__gql_mutations {
  adminAction: university_dept_DepartmentMenu__adminAction
  createDepartment: university_dept_DepartmentMenu__createDepartment
  otherAdminAction: university_dept_DepartmentMenu__otherAdminAction
}

type university_dept_DepartmentMenu__otherAdminAction {
  disabled: String
  hidden: Boolean
  invoke: String
}

type university_dept_Department__gql_meta {
  id: String!
  logicalTypeName: String!
  version: String
}

type university_dept_DeptHead {
  _gql_meta: university_dept_DeptHead__gql_meta
  _gql_mutations: university_dept_DeptHead__gql_mutations
  department: university_dept_Department
  name: String
}

type university_dept_DeptHeadMenu {
  findAllDeptHeads: university_dept_DeptHeadMenu__findAllDeptHeads
  findDeptHeadByName: university_dept_DeptHeadMenu__findDeptHeadByName
}

type university_dept_DeptHeadMenu__findAllDeptHeads {
  disabled: String
  hidden: Boolean
  invoke: [university_dept_DeptHead]
}

type university_dept_DeptHeadMenu__findDeptHeadByName {
  disabled: String
  hidden: Boolean
  invoke(name: String!): university_dept_DeptHead
}

type university_dept_DeptHead__changeDepartment {
  disabled: String
  hidden: Boolean
  invoke(department: university_dept_Department__gql_input!): university_dept_DeptHead
}

type university_dept_DeptHead__changeName {
  disabled: String
  hidden: Boolean
  invoke(newName: String!): university_dept_DeptHead
}

type university_dept_DeptHead__gql_meta {
  id: String!
  logicalTypeName: String!
  version: String
}

type university_dept_DeptHead__gql_mutations {
  changeDepartment: university_dept_DeptHead__changeDepartment
  changeName: university_dept_DeptHead__changeName
}

input causeway_applib_DomainObjectList__gql_input {
  id: ID!
}

input causeway_applib_FacetGroupNode__gql_input {
  id: ID!
}

input causeway_applib_ParameterNode__gql_input {
  id: ID!
}

input causeway_applib_PropertyNode__gql_input {
  id: ID!
}

input causeway_applib_RoleMemento__gql_input {
  id: ID!
}

input causeway_applib_TypeNode__gql_input {
  id: ID!
}

input causeway_applib_UserMemento__gql_input {
  id: ID!
}

input causeway_applib_node_ActionNode__gql_input {
  id: ID!
}

input causeway_applib_node_CollectionNode__gql_input {
  id: ID!
}

input causeway_applib_node_FacetAttrNode__gql_input {
  id: ID!
}

input causeway_applib_node_FacetNode__gql_input {
  id: ID!
}

input causeway_conf_ConfigurationProperty__gql_input {
  id: ID!
}

input causeway_conf_ConfigurationViewmodel__gql_input {
  id: ID!
}

input causeway_feat_ApplicationFeatureViewModel__gql_input {
  id: ID!
}

input causeway_feat_ApplicationNamespace__gql_input {
  id: ID!
}

input causeway_feat_ApplicationTypeAction__gql_input {
  id: ID!
}

input causeway_feat_ApplicationTypeCollection__gql_input {
  id: ID!
}

input causeway_feat_ApplicationTypeMember__gql_input {
  id: ID!
}

input causeway_feat_ApplicationTypeProperty__gql_input {
  id: ID!
}

input causeway_feat_ApplicationType__gql_input {
  id: ID!
}

input causeway_schema_metamodel_v2_DomainClassDto__gql_input {
  id: ID!
}

input causeway_security_LoginRedirect__gql_input {
  id: ID!
}

input causeway_testing_fixtures_FixtureResult__gql_input {
  id: ID!
}

input java_lang_Runnable__gql_input {
  id: ID!
}

input java_util_Map__gql_input {
  id: ID!
}

input java_util_SortedMap__gql_input {
  id: ID!
}

input java_util_concurrent_Callable__gql_input {
  id: ID!
}

input java_util_function_BiFunction__gql_input {
  id: ID!
}

input java_util_function_Consumer__gql_input {
  id: ID!
}

input java_util_function_Function__gql_input {
  id: ID!
}

input java_util_stream_Stream__gql_input {
  id: ID!
}

input org_apache_causeway_commons_functional_Either__gql_input {
  id: ID!
}

input org_apache_causeway_commons_functional_Railway__gql_input {
  id: ID!
}

input org_apache_causeway_commons_functional_ThrowingConsumer__gql_input {
  id: ID!
}

input org_apache_causeway_commons_functional_ThrowingFunction__gql_input {
  id: ID!
}

input org_apache_causeway_commons_functional_ThrowingRunnable__gql_input {
  id: ID!
}

input org_apache_causeway_commons_functional_Try__gql_input {
  id: ID!
}

input org_apache_causeway_core_metamodel_inspect_model_MMNode__gql_input {
  id: ID!
}

input org_apache_causeway_core_metamodel_inspect_model_MemberNode__gql_input {
  id: ID!
}

input org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__gql_input {
  id: ID!
}

input university_dept_Department__gql_input {
  id: ID!
}

input university_dept_DeptHead__gql_input {
  id: ID!
}
