site:
  title: Apache Isis
  url: https://isis.apache.org/
  start_page: toc:ROOT:about.adoc

content:
  sources:

# antora
    - url: .
      start_path: antora/components/toc # toc
      branches: HEAD

    - url: .
      start_path: antora/components/core # core
      branches: HEAD
    - url: .
      start_path: antora/components/extensions # extensions
      branches: HEAD
    - url: .
      start_path: antora/components/incubator # incubator
      branches: HEAD
    - url: .
      start_path: antora/components/legacy # legacy
      branches: HEAD
    - url: .
      start_path: antora/components/refguide # refguide
      branches: HEAD
    - url: .
      start_path: antora/components/security # security
      branches: HEAD
    - url: .
      start_path: antora/components/testing # testing
      branches: HEAD
    - url: .
      start_path: antora/components/userguide # userguide
      branches: HEAD

# core
    - url: .
      start_path: core/applib/src/main/doc # refguide
      branches: HEAD
    - url: .
      start_path: core/codegen-bytebuddy/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/commons/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/config/src/main/doc # refguide
      branches: HEAD
    - url: .
      start_path: core/detached-tests/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/metamodel/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/persistence/jdo/src/main/doc # pjdo
      branches: HEAD
    - url: .
      start_path: core/runtime/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/webboot-springboot/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/runtime-services/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/webapp/src/main/doc # core
      branches: HEAD
    - url: .
      start_path: core/schema/src/main/doc # refguide
      branches: HEAD
    - url: .
      start_path: core/security/api/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: core/security/bypass/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: core/security/shiro/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: core/security/keycloak/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: core/testsupport/unittestsupport/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: core/testsupport/integtestsupport/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: core/viewers/restfulobjects/jaxrs-resteasy-4/src/main/doc # vro
      branches: HEAD
    - url: .
      start_path: core/viewers/restfulobjects/src/main/doc # vro
      branches: HEAD
    - url: .
      start_path: core/viewers/wicket/src/main/doc # vw
      branches: HEAD

# examples
    - url: .
      start_path: examples/demo/src/main/doc # demoapp
      branches: HEAD
    - url: .
      start_path: examples/smoketests/src/main/doc # core
      branches: HEAD

# starters
    - url: .
      start_path: starters/src/main/doc # toc
      branches: HEAD

# incubator
    - url: .
      start_path: incubator/core/model/src/main/doc # incubator
      branches: HEAD
    - url: .
      start_path: incubator/core/microprofile/src/main/doc # incubator
      branches: HEAD

# legacy
    - url: .
      start_path: legacy/core/applib/src/main/doc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/core/commons/src/main/doc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/core/runtime/src/main/doc # legacy
      branches: HEAD
    - url: .
      start_path: legacy/vro/restclient/src/main/doc # legacy
      branches: HEAD

# extensions
    - url: .
      start_path: extensions/core/spring/src/main/doc # extensions
      branches: HEAD
    - url: .
      start_path: extensions/persistence/h2console/src/main/doc # extensions
      branches: HEAD
    - url: .
      start_path: extensions/persistence/hsqldbmgr/src/main/doc # extensions
      branches: HEAD

    - url: .
      start_path: extensions/security/secman/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/api/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/encryption-jbcrypt/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/model/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/pjdo/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/secman/shiro-realm/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: extensions/security/shiro-realm-ldap/src/main/doc # security
      branches: HEAD
    - url: .
      start_path: extensions/testing/fixtures/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: extensions/testing/specsupport/src/main/doc # testing
      branches: HEAD
    - url: .
      start_path: extensions/vro/restclient/src/main/doc # vro
      branches: HEAD
    - url: .
      start_path: extensions/vw/asciidoc/src/main/doc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/exceldownload/src/main/doc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/markdown/src/main/doc # vw
      branches: HEAD
    - url: .
      start_path: extensions/vw/sse/src/main/doc # vw
      branches: HEAD

# mavendeps
    - url: .
      start_path: mavendeps/src/main/doc # toc
      branches: HEAD


ui:
  bundle:
#    url: ../isis-antora/build/ui-bundle.zip
    url: https://github.com/apache/isis-antora/blob/master/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: antora/supplemental-ui

asciidoc:
  extensions:
    - asciidoctor-plantuml
    - ./antora/lib/lorem
    - ./antora/lib/jira-issue
    - ./antora/lib/powershell
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    plantuml-server-url: "http://www.plantuml.com/plantuml"
    isiscurr: "2.0.0-M2"
    isisnext: "2.0.0-M3"
    isisnextafter: "2.0.0-M4"
    :isisdevafter: "2.0.0-M4-SNAPSHOT"

output:
  dir: antora/target/site
