:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Usually a domain event is emitted by the framework to emit whenever the user interacts with a collection.
Domain service subscribers can influence these interaction by subscribing to these events, allowing them to hide the collection.
(Contrasting this with properties or actions, there are no other interactions that can be influenced because collections cannot be modified directly).

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/Collection.html#domainevent[@Collection#domainEvent] attribute specifies the class to be emitted; this must be a subclass of the abstract link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/events/domain/CollectionDomainEvent.html[CollectionDomainEvent] class.

If no `domainEvent` is specified on the property itself, then the domain event class can be specified at the class level using link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObject.html#collectiondomainevent[@DomainObject#collectionDomainEvent]..
And if not specified at the class level, then an instance of `oa.c..applib.events.domain.CollectionDomainEvent.Default` is emitted as the fallback.

== How this demo works

This page object has two collections, `children` and `moreChildren`
The first is annotated with a custom domain event, the second is not.

The annotated collection's visibility can be controlled using the "change control strategy" action.
This control does not apply to the non-annotated collection.

In terms of code:

* this page object, with its collections:
+
[source,java]
----
include::CollectionDomainEventPage.java[tags=class]
----
<.> the event class to emit; genericised by the target type and the collection type.
It's common to define these as nested classes.
<.> indicates that the framework should emit domain events of this type
<.> not annotated and so will emit the default collection domain event


* the subscriber that listens to the events:
+
[source,java]
.CollectionDomainEventControlSubscriber.java
----
include::CollectionDomainEventControlSubscriber.java[tags=class]
----
<.> currently selected strategy
<.> listens to the custom event
<.> dispatches to the currently selected control strategy (see below)

* the action that selects the strategy in effect:
+
[source,java]
.CollectionDomainEventPage_changeControlStrategy
----
include::CollectionDomainEventPage_changeControlStrategy.java[tags=class]
----
<.> Forces page to fully redraw


* the different strategies:

** do nothing
+
[source,java]
.CollectionDomainEventControlStrategy.java
----
include::CollectionDomainEventControlStrategy.java[tags=class]
----

** hide
+
[source,java,indent=0]
.CollectionDomainEventControlStrategy.java
----
include::CollectionDomainEventControlStrategy.java[tags=hide]
----
