= Rel _(enum)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.Rel.java
----
enum Rel {
  SELF
  DESCRIBEDBY
  UP
  PREVIOUS
  NEXT
  HELP
  ICON
  ACTION
  ACTION_PARAM
  ADD_TO
  ATTACHMENT
  CHOICE
  CLEAR
  COLLECTION
  DEFAULT
  DELETE
  DETAILS
  DOMAIN_TYPE
  DOMAIN_TYPES
  ELEMENT
  ELEMENT_TYPE
  INVOKE
  MODIFY
  PERSIST
  PROPERTY
  REMOVE_FROM
  RETURN_TYPE
  SERVICE
  SERVICES
  UPDATE
  USER
  VALUE
  VERSION
  CONTRIBUTED_BY
  OBJECT_LAYOUT
  OBJECT_ICON
  LAYOUT
  MENUBARS
  BRAND_LOGO_SIGNIN
  BRAND_LOGO_HEADER
  LOGOUT
  String getName()     // <.>
  String getSimpleName()     // <.>
  String andParam(String paramName, String paramValue)     // <.>
  boolean matches(Rel otherRel)
  boolean matches(String otherRelStr)
  Rel parse(String str)
}
----

<.> xref:#getName__[getName()]
+
--
full spec name with rel-def and suffix, eg. _urn:org.apache.isis.restfulobjects:rels/menuBars_
--
<.> xref:#getSimpleName__[getSimpleName()]
+
--
suffix only, eg. _menuBars_
--
<.> xref:#andParam__String_String[andParam(String, String)]
+
--
For those xref:refguide:viewer:index/restfulobjects/applib/Rel.adoc[Rel] s that also take a param
--

== Members

[#getName__]
=== getName()

full spec name with rel-def and suffix, eg. _urn:org.apache.isis.restfulobjects:rels/menuBars_

[#getSimpleName__]
=== getSimpleName()

suffix only, eg. _menuBars_

[#andParam__String_String]
=== andParam(String, String)

For those xref:refguide:viewer:index/restfulobjects/applib/Rel.adoc[Rel] s that also take a param
