/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package demoapp.dom.types.isis.markups.holder;

import javax.inject.Named;

/* This file was GENERATED by the showcase generator (tooling). Do NOT edit! */
@Named("demo.IsisMarkupHolder")
//tag::class[]
public interface IsisMarkupHolder {

    org.apache.isis.applib.value.Markup getReadOnlyProperty();
    void setReadOnlyProperty(org.apache.isis.applib.value.Markup c);

    org.apache.isis.applib.value.Markup getReadWriteProperty();
    void setReadWriteProperty(org.apache.isis.applib.value.Markup c);

    org.apache.isis.applib.value.Markup getReadOnlyOptionalProperty();
    void setReadOnlyOptionalProperty(org.apache.isis.applib.value.Markup c);

    org.apache.isis.applib.value.Markup getReadWriteOptionalProperty();
    void setReadWriteOptionalProperty(org.apache.isis.applib.value.Markup c);

}
//end::class[]
