= Bootstrapping using `AppManifest`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:



Apache Isis 1.9.0 provides a simplified programmatic way of bootstrapping the application, that also unifies bootstrapping for integration tests.

For now this new bootstrapping mechanism is optional (you don't have to change your code), but it may become mandatory in future releases.
The link:https://isis.apache.org/versions/1.9.0/arch/simpleapp/about.html[SimpleApp archetype] has been updated to use this new mechanism.

The instructions below assume that your application is structured as per the simpleapp archetype.  Adjust accordingly.



== `myapp-dom` Module

In your `myapp-dom` module (containing definitions of your persistent entities and domain services), create an empty class to represent the module.
This should be at the root package for the domain, eg:

[source,java]
----
package myapp.dom;
public final class MyAppDomainModule {
    private MyAppDomainModule(){}
}
----

Since there is no requirement to actually instantiate this class (it merely provides the location of the `myapp.dom` package), we give it a private constructor.

If you have any other modules where you have either domain services or entities, similarly create an empty "module" class.



== `myapp-fixture` Module

Similarly, in your `myapp-fixture` module (containing fixture scripts used for testing and demos), do likewise:

[source,java]
----
package myapp.fixture;
public class MyAppFixtureModule {
    private MyAppFixtureModule(){}
}
----




== `myapp-app` Maven Module

Create a new `myapp-app` Maven module:

* in its `pom.xml`, reference `myapp-fixture` +
+
[source,xml]
----
<dependency>
    <groupId>${project.groupId}</groupId>
    <artifactId>myapp-fixture</artifactId>
</dependency>
----
+
[NOTE]
====
Since `myapp-fixture` will reference `myapp-dom` there's no need for a direct reference to `myapp-dom`
====

* also add in dependencies to the core framework: +
+
[source,xml]
----
<dependency>
    <groupId>org.apache.isis.core</groupId>
    <artifactId>isis-core-wrapper</artifactId>
</dependency>
<dependency>
    <groupId>org.apache.isis.core</groupId>
    <artifactId>isis-core-runtime</artifactId>
</dependency>
----

* if your application uses any of the (non-ASF) link:http://www.isisaddons.org[Isis Addons] modules, then add dependencies to these modules in the `pom.xml`.
You should be able to copy-and-paste the dependencies from the `pom.xml` of your `myapp-webapp` module.

Create a module class for the `myapp` module also:

[source,java]
----
package myapp.app;
public final class MyAppAppModule {
    private MyAppAppModule() {}
}
----

Next, create an `AppManifest` implementation, eg: +

[source,java]
----
package myapp.app;
public class MyAppAppManifest implements AppManifest {
    @Override
    public List<Class<?>> getModules() {                             // <1>
        return Arrays.asList(
                MyAppDomainModule.class,
                MyAppFixtureModule.class,
                MyAppAppModule.class
        );
    }
    @Override
    public List<Class<?>> getAdditionalServices() { return null; }  // <2>
    @Override
    public String getAuthenticationMechanism() { return null; }
    @Override
    public String getAuthorizationMechanism() { return null; }
    @Override
    public List<Class<? extends FixtureScript>> getFixtures() { return null; }
    @Override
    public Map<String, String> getConfigurationProperties() { return null; }
}
----
<1> the module classes, whose packages specify the existence of domain services and/or persistent entities.
If your app uses (non-ASF) link:http://www.isisaddons.org[Isis Addons] modules, then include the module classes for these addons in `getModules()`.
For example, the (non-ASF) link:https://platform.incode.org[Incode Platform^]'s security module provides the `org.isisaddons.module.security.SecurityModule` class.
<2> any additional services, as per `isis.services` configuration property.


[TIP]
====
For details of the usages of the other methods in this interface, see the link:https://isis.apache.org/versions/1.9.0/guides/rgcms/rgcms.html#_rgcms_classes_AppManifest-bootstrapping[reference guide] documentation.
====


If in your `myapp-dom` module you have application-level services and view models (services that depend on persistent domain entities but not the other way around), then we recommend that you move this code to the new `myapp-app` module.
This makes the layering clearer, and avoids circular dependencies between  application-layer vs domain-layer logic.




== Update parent

in the parent `pom.xml`, declare and reference the new `myapp-app` module:

[source,xml]
----
<dependencyManagement>
    <dependencies>
        ...
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>myapp-app</artifactId>
            <version>${project.version}</version>
        </dependency>
        ...
    </dependencies>
</dependencyManagement>

<modules>
    <module>app</module>
    ...
</modules>

----



== Update `myapp-integtests`

In its `pom.xml`:

* add a dependency on `myapp-app`
* remove dependency on `myapp-fixture` (and on `myapp-dom`, if present)
* remove dependencies on `isis-core-wrapper` and `isis-core-runtime` (since now obtained transitively from `myapp-app`)

Also update (simplify) `MyAppSystemInitializer` to use the new `AppManifest`, eg:

[source,java]
----
public class MyAppSystemInitializer {
    public static void initIsft() {
        IsisSystemForTest isft = IsisSystemForTest.getElseNull();
        if(isft == null) {
            isft = new IsisSystemForTest.Builder()
                    .withLoggingAt(org.apache.log4j.Level.INFO)
                    .with(new DomainAppAppManifest())                   // <1>
                    .with(new IsisConfigurationForJdoIntegTests())      // <2>
                    .build()
                    .setUpSystem();
            IsisSystemForTest.set(isft);
        }
    }
}
----
<1> bootstrapping using the new `AppManifest` implementation
<2> if your bootstrapping previously explicitly overrode certain configuration properties, this can instead be moved to the `getConfigurationProperties()` method of your `AppManifest` implementation.




== Update `myapp-webapp`

In its `pom.xml`:

* add a dependency on `myapp-app`
* remove dependency on `myapp-fixture` (and on `myapp-dom`, if present)
* remove dependencies on `isis-core-wrapper` and `isis-core-runtime` (since now obtained transitively from `myapp-app`)

* (if you didn't previously), move any dependencies to addons or other services referenced in the `AppManifest` to the `pom.xml` of the new `myapp-app` module.


Remove configuration properties that are no longer needed:

* in `isis.properties`:

** remove `isis.services-installer`
** remove `isis.services.ServicesInstallerFromAnnotation.packagePrefix`
** remove `isis.services`

* in `persistor_datanucleus.properties`

** remove `isis.persistor.datanucleus.RegisterEntities.packagePrefix`


Finally, specify the `AppManifest` to use to bootstrap the app.  You have a choice here:

* either update `isis.properties`, using the `isis.appManifest` key to specify the `AppManifest` implementation, eg: +
+
[source,ini]
----
isis.appManifest=domainapp.app.DomainAppAppManifest
----

* alternatively, specify the `AppManifest` by overriding the `IsisWicketApplication#newWicketModule()`, eg: +
+
[source,java]
----
@Override
protected Module newIsisWicketModule() {
    final Module isisDefaults = super.newIsisWicketModule();
    ...
    final Module overrides = new AbstractModule() {
        @Override
        protected void configure() {
            ...
            bind(AppManifest.class).toInstance(new DomainAppAppManifest());
        }
    };

    return Modules.override(isisDefaults).with(overrides);
}
----

If the second (programmatic) approach is used, this overrides the first approach (using `isis.properties`).




