[[r3.0.0]]
= 3.0.0

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


After almost six years effort (!), v2.0.0 and v3.0.0 are the first official releases of Apache Causeway, now re-platformed to run on Spring Boot.
The two versions are being released at the same time.


The v3.0.0 release is broadly equivalent to the v2.0.0 release.
As such, see the xref:2024/2.0.0/relnotes.adoc[2.0.0] release notes for full details of the features available in this release.

However, 3.0.0:

* targets Spring Boot 3.x (instead of Spring Boot 2.x)
* targets Java 17 (instead of Java 11)

It also uses the `jakarta` namespace rather than `javax`.

You should generally use


There is one functional change, namely that support for xref:security:shiro:about.adoc[Shiro security] module has been dropped (for now).
See the xref:relnotes:ROOT:2024/3.0.0/mignotes.adoc#simple-security-replacement-for-shiro[migration notes] for options.



NOTE: Not yet released.

include::partial$2024/2.0.0/_relnotes.adoc[]
