:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Moving the mouse over to the top-left of the page will bring down a set of bookmarks.
This is populated simply by navigating into different domain objects,
allowing the end-user can easily navigate back to the page later on in their session.
Both entities and view models are bookmarked.

To make this set of bookmarks more useful, the set of bookmarks can be organised into a tree, meaning that "child" objects are only added to the bookmark if their parent object is.
A canonical example is order/order-item ... any items are grouped by their owning order.

Domain classes control this feature using the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObjectLayout.html#bookmarking[@DomainObjectLayout#bookmarking] attribute:

* link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/BookmarkPolicy.html#as_root[AS_ROOT] - this is the standard behaviour.
These objects are always bookmarked as they are visited.
* link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/BookmarkPolicy.html#as_child[AS_CHILD] - only bookmark the object if its parent object is also bookmarked
* https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/BookmarkPolicy.html#NEVER[NEVER] - do not bookmark.


== How this demo works

On the left hand side is a collection of objects.
These are all annotated as root bookmarks.
Navigate into any of them and a bookmark should be added to the bookmark list.

In addition, these "parent" objects have an action "addChildren".
Call this action and a set of objects will be added.
These children objects are annotated to use "child" bookmarks.
Navigate into any child object and their bookmark should be added at the correct place.

In terms of code:

* parent objects:
+
[source,java]
----
include::DomainObjectLayoutBookmarkingEntity.java[tags=class]
----
<.> uses root bookmark policy

* child objects:
+
[source,java]
----
include::DomainObjectLayoutBookmarkingChildEntity.java[tags=class]
----
<.> uses child bookmark policy
