= GridService
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Loads the layout (grid) for any domain class. Also supports various formats xref:refguide:applib:index/services/layout/LayoutExportStyle.adoc[LayoutExportStyle] for export.

Using DTOs based on

== API

[source,java]
.GridService.java
----
interface GridService {
  boolean supportsReloading()     // <.>
  void invalidate(Class<?> domainClass)     // <.>
  BSGrid load(LayoutKey layoutKey)     // <.>
  EnumSet<CommonMimeType> supportedFormats()
  Optional<GridMarshaller> marshaller(CommonMimeType format)
}
----

<.> xref:#supportsReloading_[supportsReloading()]
+
--
Whether dynamic reloading of layouts is enabled.
--
<.> xref:#invalidate_Class[invalidate(Class)]
+
--
To support metamodel invalidation/rebuilding of spec.
--
<.> xref:#load_LayoutKey[load(LayoutKey)]
+
--
Returns a xref:refguide:applib:index/layout/grid/bootstrap/BSGrid.adoc[BSGrid] for given _LayoutKey_ .
--

== Members

[#supportsReloading_]
=== supportsReloading()

Whether dynamic reloading of layouts is enabled.

The default implementation enables reloading while prototyping, disables in production.

[#invalidate_Class]
=== invalidate(Class)

To support metamodel invalidation/rebuilding of spec.

Acts as a no-op if not _#supportsReloading()_ .

[#load_LayoutKey]
=== load(LayoutKey)

Returns a xref:refguide:applib:index/layout/grid/bootstrap/BSGrid.adoc[BSGrid] for given _LayoutKey_ .

The default implementation uses the layout name to search for a differently named layout file, `[domainClass].layout.[layout].xml` .

When no specific grid layout is found returns a generic fallback.

include::hooks/GridService_010-implementation.adoc[]

include::hooks/GridService_020-examples-and-usage.adoc[]
