The framework has built-in support for representing servlets and other resources that exist alongside the Apache Isis runtime, using the `LocalResourcePath` data type .
When an action returns an instance of this type, then this is rendered as a redirect request to the browser to that resource.
In this way you could for example return a link to a PDF or image (to be rendered by the web browser itself), or provide access to dynamic content by redirecting to a servlet.

NOTE: This is an Apache Isis specific data type.

From here you can:

* navigate to an entity that uses the `LocalResourcePath` datatype
* open a view model that uses the `LocalResourcePath` datatype

Some properties on these domain objects are mandatory, some optional.

== Common interfaces

The entity and view model types both implement some common interfaces.

=== IsisLocalResourcePathHolder

The `IsisLocalResourcePathHolder` interface is used to contribute a number of mixins to both types:

[source,java]
----
include::holder/IsisLocalResourcePathHolder.java[tags=class]
----

=== IsisLocalResourcePathHolder2

The `IsisLocalResourcePathHolder2` interface is used to demonstrate support for label positions using `@PropertyLayout(labelPosition=...)`.

Further details, along with the effect of this annotation, can be seen on the entity and view model object pages.