Usually a domain event is emitted by the framework to emit whenever the user interacts with a property.
Domain service subscribers can influence this interaction, either by:

* hiding the property
* disabling the property
* validating proposed values for the property
* performing arbitrary operations before the property has been modified (including modifying the proposed value of the property)
* performing arbitrary operations after the property has been modified

The `domainEvent` semantic specifies the class to be emitted; this must be a subclass of the abstract `org.apache.isis.applib.events.domain.PropertyDomainEvent` class.

If no `domainEvent` is specified on the property itself, then the domain event class can be specified at the class level using `@DomainObject#propertyDomainEvent`.
And if not specified at the class level, then an instance of `org.apache.isis.applib.events.domain.PropertyDomainEvent.Default` is emitted as the fallback.

[TIP]
====
The fallback domain event can be suppressed using the `isis.applib.annotation.property.domain-event.post-for-default` configuration property.
====

== Annotated Property

In the demo, the `PropertyDomainEventVmMakingThisLongerAndLonger` class defines an editable property, "text", annotated with `domainEvent`:

[source,java]
----
include::PropertyDomainEventVm.java[tags=class]
----
<.> the event class to emit; genericised by the target type and the property type
<.> indicates that the framework should emit this type


== Subscriber

The `PropertyDomainEventControlService` is the subscriber:

[source,java]
----
include::subscribers/PropertyDomainEventControlService.java[tags=class]
----
<.> holds which "strategy" should be used to modify the interactions with the text field
<.> subscribes using the Spring event bus


== Influencing the Interaction

The mechanisms to influence the interactions are implemented as an enum.
The `DO_NOTHING` enum, unsurprisingly, does nothing:

[source,java]
----
include::subscribers/PropertyDomainEventControlStrategy.java[tags=class]
----

There are five further options:

* hide
+
[source,java,indent=0]
----
include::subscribers/PropertyDomainEventControlStrategy.java[tags=hide]
----

* disable
+
[source,java,indent=0]
----
include::subscribers/PropertyDomainEventControlStrategy.java[tags=disable]
----

* validate
+
[source,java,indent=0]
----
include::subscribers/PropertyDomainEventControlStrategy.java[tags=validate]
----

* executing
+
[source,java,indent=0]
----
include::subscribers/PropertyDomainEventControlStrategy.java[tags=executing]
----

* executed
+
[source,java,indent=0]
----
include::subscribers/PropertyDomainEventControlStrategy.java[tags=executed]
----

=== Selecting the Strategy

Selecting which strategy is in force is implemented using two mixins which work together:

* the `controlText` mixin property just surfaces the selected strategy as a read-only value:
+
[source,java]
----
include::subscribers/PropertyDomainEventVm_controlText.java[tags=class]
----

* while the `controlTextEditing` mixin action allows the strategy to be changed:
+
[source,java]
----
include::subscribers/PropertyDomainEventVm_controlTextEditing.java[tags=class]
----
<.> forces the page to redraw.
Necessary because the text property's state change

