= EmailServiceDefault
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Default implementation of xref:refguide:applib:index/services/email/EmailService.adoc[EmailService] , that uses Spring Boot's _JavaMailSender_ API service to send out emails.

Note that this implementation requires that an implementation of Spring's _JavaMailSender_ is configured.

== API

[source,java]
.EmailServiceDefault.java
----
class EmailServiceDefault {
  void init()     // <.>
  boolean isConfigured()
  boolean send(List<String> toList, List<String> ccList, List<String> bccList, String subject, String body, DataSource... attachments)
  String[] originalUnlessOverridden(List<String> original, String overrideIfAny)
  boolean notEmpty(String[] addresses)
}
----

<.> xref:#init_[init()]
+
--
Loads responsive email templates borrowed from http://zurb.com/ink/templates.php (Basic)
--

== Members

[#init_]
=== init()

Loads responsive email templates borrowed from http://zurb.com/ink/templates.php (Basic)
