= Injecting services
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:


Apache Isis runs on top of SpringBoot, and uses SpringBoot for dependency injection, both of the applications own domain services and als of the very many additional services defined by the framework (such as xref:refguide:applib-svc:persistence-layer-api/RepositoryService.adoc[`RepositoryService`]).

However, not only does it autowire domain services into other services, it also ensures that services are injected into any domain object (eg entity, view model, fixture script, specification etc).




== Field Injection

Field injection is generally recommended, using the `@javax.inject.Inject` annotation.
For example:

[source,java]
----
public class Customer {
    ...
    @javax.inject.Inject
    OrderRepository orderRepository;
}
----

To inject a list of services, use:

[source,java]
----
public class DocumentService {
    ...
    @javax.inject.Inject
    List<PaperclipFactory> paperclipFactories;
}
----

We recommend using default rather than `private` visibility so that the field can be mocked out within unit tests (placed in the same package as the code under test).




== Method Injection

The framework also supports two forms of method injection.
All that is required to inject a service into a entity/service is to provide an appropriate method or field.
The name of the method does not matter, only that it is prefixed either `set` or `inject`, is public, and has a single parameter of the correct type.

For example:

[source,java]
----
public class Customer {
    private OrderRepository orderRepository;
    public void setOrderRepository(OrderRepository orderRepository) {
        this.orderRepository = orderRepository;
    }
    ...
}
----

or alternatively, using 'inject' as the prefix:

[source,java]
----
public class Customer {
    private OrderRepository orderRepository;
    public void injectOrderRepository(OrderRepository orderRepository) {
        this.orderRepository = orderRepository;
    }
    ...
}
----

Lists of services can be injected in a similar manner.

Note that the method name can be anything; it doesn't need to be related to the type being injected.


== Constructor injection

TODO: v2: this is now supported, because of Spring Boot, I think.


== Multiple Implementations

Sometimes there may be multiple services that implement a single type.
This is common for example for SPI service, whereby one module defines an SPI service, and other module(s) in the application implement that service.
To support this, lists of services can be injected.

When there are multiple service implementations of a given type, annotate the different implementations using Spring's link:https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/Order.html[`@Order`] or https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Primary.html[`@Primary`].


== Scoping

TODO: v2: should describe how this works.



== Qualified Injection

TODO: v2: x-ref to Spring Boot docs.



