= UserService

The   xref:index:UserService.adoc[UserService]   allows the domain object to obtain the identity of the user 
interacting with said object.


If  _SudoService_  has been used to temporarily override the user and/or roles, 
then this service will report the overridden values instead.

.UserService
[source,java]
----
interface UserService {

  Optional<UserMemento> currentUser() // <.>

  UserMemento getUser() // <.>

  UserMemento currentUserElseFail() // <.>

  Optional<String> currentUserName() // <.>
}
----


<.> `Optional<UserMemento> currentUser()` Optionally gets the details about the current user, 
based on whether an  _ExecutionContext_  can be found with the current thread's context.

<.> `UserMemento getUser()` Gets the details about the current user.

<.> `UserMemento currentUserElseFail()` Gets the details about the current user.

<.> `Optional<String> currentUserName()` Optionally gets the the current user's name, 
based on whether an  _ExecutionContext_  can be found with the current thread's context.

