{
  rich {
    Scenario(name: "Fizz and buzz are concatenated together"){
      Name
      When {
        university_calc_Calculator {
          concat {
            invoke(prefix: "Fizz", suffix: "Buzz") {
              args {
                prefix
                suffix
              }
              results
            }
          }
        }
      }
    }
  }
}
