= PermissionsEvaluationService _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Strategy for determining which permission should apply when there are multiple that apply for a particular target feature Id, and which may conflict with each other.

All implementations of this interface must be _java.io.Serializable_ , because an instance is serialized into xref:refguide:extensions:index/secman/applib/permission/dom/ApplicationPermissionValueSet.adoc[ApplicationPermissionValueSet] .

== API

[source,java]
.PermissionsEvaluationService.java
----
interface PermissionsEvaluationService {
  ApplicationPermissionValueSet.Evaluation evaluate(ApplicationFeatureId targetMemberId, ApplicationPermissionMode mode, Collection<ApplicationPermissionValue> permissionValues)     // <.>
}
----

<.> xref:#evaluate__ApplicationFeatureId_ApplicationPermissionMode_Collection[evaluate(ApplicationFeatureId, ApplicationPermissionMode, Collection)]

== Members

[#evaluate__ApplicationFeatureId_ApplicationPermissionMode_Collection]
=== evaluate(ApplicationFeatureId, ApplicationPermissionMode, Collection)
