= Migrating from M5 to M6

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


(This page will be added to as development progresses).

== Changes to the Programming Model

=== Removed (Programming Model)

[cols="2a,3a", options="header"]

|===

| was
| now what?

| `@Action(associateWithSequence=...)` removed
| use `@ActionLayout(sequence=...)` instead

| `@MemberOrder(name=...)` removed
| instead on a _Property_ use `@PropertyLayout(fieldSetId=..., fieldSetName=...)` 
or on an _Action_ use `@Action(associateWith=...)`; 
there is no counterpart for _Collection_ 

| `@MemberOrder(sequence=...)` removed
| use `@ActionLayout/@PropertyLayout/@CollectionLayout(sequence=...)` instead

| `@Model` (from extensions) removed
| use `@MemberSupport`  (Applib) instead

|===

== Other Changes

Module `IsisModuleExtCorsImpl` was renamed to `IsisModuleExtCors`. 

Module `IsisModuleExtModelAnnotation` was removed and is no longer required.

Service `BookmarkService` has been improved, such that its methods return `Optional<?>` instead of nullable objects. 



== Extensions

=== SecMan

Following menu actions for User Management have been removed:

[source,xml]
.menubars.layout.xml
----
<!--
<mb3:serviceAction objectType="isis.ext.secman.ApplicationUserMenu" id="newLocalUser">
    <cpt:named>New Local User</cpt:named>
</mb3:serviceAction>
<mb3:serviceAction objectType="isis.ext.secman.ApplicationUserMenu" id="allUsers">
    <cpt:named>All Users</cpt:named>
</mb3:serviceAction>
<mb3:serviceAction objectType="isis.ext.secman.ApplicationUserMenu" id="newDelegateUser">
    <cpt:named>New Delegate User</cpt:named>
</mb3:serviceAction>
-->
----

Use the new User Manager View Model instead:

[source,xml]
.menubars.layout.xml
----
<mb3:serviceAction objectType="isis.ext.secman.ApplicationUserMenu" id="userManager">
    <cpt:named>User Manager</cpt:named>
</mb3:serviceAction>
----                
                