#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0.
#
spring.application.name=Apache Causeway Reference Application Viewer Regression
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
causeway.viewer.graphql.api-scope=ALL
causeway.viewer.graphql.schema-style=SIMPLE_AND_RICH
causeway.viewer.graphql.resources.structural-metadata-response-type=DIRECT
causeway.viewer.graphql.authentication.fallback.username=sven
causeway.viewer.graphql.authentication.fallback.roles=causeway-ext-secman-admin,causeway-ext-secman-user
causeway.viewer.wicket.base-path=/wicket/
causeway.viewer.webcomponents.htmx.base-path=/htmx
causeway.viewer.webcomponents.htmx.graph-ql-endpoint=/graphql
causeway.viewer.webcomponents.htmx.brand=Causeway Reference Application
causeway.viewer.webcomponents.htmx.wicket-comparison-path=/wicket/
causeway.viewer.webcomponents.htmx.application-stylesheet=/css/application.css
causeway.viewer.webcomponents.htmx.vaadin-reference-widgets=true
causeway.viewer.webcomponents.htmx.reference-minimum-search-length=2
causeway.viewer.webcomponents.htmx.reference-maximum-results=50
causeway.value-types.kroki.backend-url=
