@startuml(id=context)
title Payment Terminal - System Context
caption Payment Gateway Diagram

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<2>> {
  BackgroundColor #dddddd
  FontColor #fffffe
  BorderColor #9a9a9a
}
skinparam rectangle<<3>> {
  BackgroundColor #dddddd
  FontColor #fffffe
  BorderColor #9a9a9a
}
rectangle "==Merchant\n<size:10>[Person]</size>\n\nMerchant" <<1>> as 1
rectangle "==Fraud Detector\n<size:10>[Software System]</size>\n\nFraud Detector" <<3>> as 3
rectangle "==Payment Terminal\n<size:10>[Software System]</size>\n\nPayment Terminal" <<2>> as 2
1 .[#707070,thickness=2].> 2 : "Makes payment"
2 .[#707070,thickness=2].> 3 : "Obtains fraud score"
@enduml