The framework has built-in support for a number of temporal types, including `java.time.OffsetDateTime`.

From here you can:

* navigate to an entity that uses the `java.time.OffsetDateTime` datatype
* open a view model that uses the `java.time.OffsetDateTime` datatype

Some properties on these domain objects are mandatory, some optional.

== Common interface

These objects both implement a common interface, `JavaTimeOffsetDateTimeHolder`:

[source,java]
----
include::holder/JavaTimeOffsetDateTimeHolder.java[tags=class]
----


== Mixin actions

A number of mixin actions contribute through this interface, demonstrate the use of `java.time.OffsetDateTime` as a parameter and as a return type.
For example:

* the `updateReadOnlyProperty` action is:
+
[source,java]
----
include::holder/JavaTimeOffsetDateTimeHolder_updateReadOnlyProperty.java[tags=class]
----

* the `updateReadOnlyOptionalProperty` action is:
+
[source,java]
----
include::holder/JavaTimeOffsetDateTimeHolder_updateReadOnlyOptionalProperty.java[tags=class]
----

* the `actionReturning` action is:
+
[source,java]
----
include::holder/JavaTimeOffsetDateTimeHolder_actionReturning.java[tags=class]
----


* the `actionReturningCollection` action is:
+
[source,java]
----
include::holder/JavaTimeOffsetDateTimeHolder_actionReturningCollection.java[tags=class]
----

== Mixin properties

We also use the interface to contribute a mixin property:

* the `mixinProperty` property:
+
[source,java]
----
include::holder/JavaTimeOffsetDateTimeHolder_mixinProperty.java[tags=class]
----


== @PropertyLayout(labelPosition=...)

To demonstrate support for label positions using `@PropertyLayout(labelPosition=...)`, the entity and view model objects both implement the extended `JavaTimeOffsetDateTimeHolder2` interface:

[source,java]
----
include::holder/JavaTimeOffsetDateTimeHolder2.java[tags=class]
----

<.> The default methods have annotations that are automatically inherited.
<.> Position to the left
<.> Uses `@MemberOrder` positions the properties into the appropriate `<field-set>` within the `Xxx.layout.xml` layout file.
<.> Position label on top
<.> Position label to the right
+
CAUTION: currently not supported
<.> Hide the label compleely.


== @PropertyLayout(renderDay=...)

To demonstrate support for `@PropertyLayout(renderDay=...)` -- to simplify the modelling "[inclusive, exclusive)" date ranges -- the entity and view model objects both implement the extended `JavaTimeOffsetDateTimeHolder3` interface.
All methods have a default implementation:

[source,java]
----
include::holder/JavaTimeOffsetDateTimeHolder3.java[tags=class]
----

<.> Render the value as the day before
<.> Render the value unchanged
<.> Render the value as the day before

