[[ActionDomainEvent]]
= `ActionDomainEvent`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


Subclass of xref:applib-classes:events.adoc#AbstractDomainEvent[`AbstractDomainEvent`] for actions.

The class has a number of responsibilities (in addition to those it inherits):

* capture the target object being interacted with
* capture the arguments for each of the action's parameters
* provide selected metadata about the action parameters from the metamodel (names, types)
* link back to the xref:refguide:applib-svc:CommandContext.adoc[`CommandContext`] service's `Command` object

The class itself is instantiated automatically by the framework whenever interacting with a rendered object's action.

== API

The API of the class is:

// TODO: v2: use include::[]

[source,java]
----
public abstract class ActionDomainEvent<S> extends AbstractDomainEvent<S> {

    public static class Default extends ActionDomainEvent<Object> { }   // <.>
    public static class Noop extends ActionDomainEvent<Object> { }      // <.>
    public static class Doop extends ActionDomainEvent<Object> { }      // <.>

    @Deprecated
    public Command getCommand();                                        // <.>

    public SemanticsOf getSemantics();

    public List<String> getParameterNames();
    public List<Class<?>> getParameterTypes();

    public List<Object> getArguments();                                 // <.>
    public Object getReturnValue();                                     // <.>
    public void setReturnValue();                                       // <.>
}
----
<1> The `Default` nested static class is the default for the xref:refguide:applib-ant:Action.adoc#domainEvent[`@Action#domainEvent()`]
annotation attribute.
Whether this raises an event or not depends upon the `isis.reflector.facet.actionAnnotation.domainEvent.postForDefault` configuration property.
<2> The `Noop` class is provided as a convenience to indicate that an event should _not_ be posted (irrespective of the configuration property setting).
<3> Similarly, the `Doop` class is provided as a convenience to indicate that an event _should_ be raised (irrespective of the configuration property setting).
<4> Deprecated, use xref:refguide:applib-svc:CommandContext.adoc[`CommandContext`] or (better)  xref:refguide:applib-svc:InteractionContext.adoc[`InteractionContext`]instead.
<5> The arguments being used to invoke the action; populated during validate phase and subsequent phases.
<6> The value returned by the action; populated only in the executed phase.
<7> Allows the subscriber to effectively change the value returned by the action; may only be called in the executed phase.
