[[Timestampable]]
= `Timestampable`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The `Timestampable` role interface is a convenience that combines the xref:refguide:applib-cm:classes.adoc#HoldsUpdatedAt[`HoldsUpdatedAt`] and xref:refguide:applib-cm:classes.adoc#HoldsUpdatedBy[`HoldsUpdatedBy`] interfaces.
It is defined as:

[source,java]
----
public interface Timestampable
    extends HoldsUpdatedAt, HoldsUpdatedBy {
}
----

The interface no additional methods of its own.



== Alternatives

An alternative way to maintain a timestamp is to use JDO's `@Version` annotation.
With this approach, it is the JDO/DataNucleus that maintains the version, rather than the framework's `TimestampService`.
See xref:refguide:applib-cm:classes.adoc#HoldsUpdatedBy[`HoldsUpdatedBy`] for further details.
