
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



== Implementation

The xref:core:runtimeservices:about.adoc[Core Runtime Services] module provides a default implementation, xref:refguide:core:index/runtimeservices/email/EmailServiceDefault.adoc[].
This sends email as an HTML message, using an external SMTP provider.


=== Configuration Properties

The default implementation (xref:refguide:core:index/runtimeservices/email/EmailServiceDefault.adoc[]) defines a number of xref:refguide:config:sections/causeway.core.runtime-services.adoc[configuration properties], under the `causeway.core.runtime-services.email` key.

It also requires that an implementation of Spring's `JavaMailSender` is present on the classpath.
This requires its own configuration.

// https://issues.apache.org/jira/browse/CAUSEWAY-3757 is an intention to simplify this configuratoin.


