= Object Management (CRUD)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


This chapter shows the idioms for creating, reading, updating and deleting xref:ug:fun:building-blocks/types-of-domain-objects/domain-entities.adoc[domain entities].
The main domain services used for this are xref:rg:svc:persistence-layer-api/RepositoryService.adoc[`RepositoryService`] and xref:rg:svc:core-domain-api/FactoryService.adoc[`FactoryService`].

It also shows how to instantiate xref:ug:fun:building-blocks/types-of-domain-objects/view-models.adoc[view models] and how to programmatically instantiate xref:ug:fun:building-blocks/types-of-domain-objects/mixins.adoc[mixins] (useful primarily for xref:ug:tst:integ-test-support.adoc[integration testing]).





