= `EntityAuditDispatcher`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

WARNING: TODO: this content has not yet been reviewed/updated for v2.0

The (internal) `EntityAuditDispatcher` service acts as an internal facade to any registered xref:refguide:applib-svc:EntityAuditListener.adoc[`EntityAuditListener`] service(s).
It is responsible for obtaining the details of all changes to domain objects within an interaction, and then to call the configured ``EntityAuditListener``(s) to actually create audit entries of those changes.




== SPI and Implementation

The SPI of the service is:

[source,java]
----
public class EntityAuditDispatcher {
    public void dispatchEntityAudits(...);  // <1>
}
----
<1> uses the xref:core:runtime-services:ChangedObjectsService.adoc[`ChangedObjectsServiceInternal`] to obtain details of the changed properties, then call the configured xref:refguide:applib-svc:AuditerService.adoc[`AuditerService`](s).

== Registering the Service

Apache Isis' default implementation of `EntityAuditDispatcher` class is automatically registered (it is annotated with `@DomainService`) so no further configuration is required.


== Related Classes

In total there are 4 sorts of data the framework has dispatchers for ...
. *EntityAudit*: dispatched via `EntityAuditDispatcher` and subscribed to via `EntityAuditListener` (SPI)
. *ChangingEntities*: dispatched via `ChangingEntitiesDispatcher` and subscribed to via `ChangingEntitiesListener` (SPI)
. *Execution*: dispatched via `ExecutionDispatcher` and subscribed to via `ExecutionListener` (SPI)
. *Command*: dispatched via `CommandDispatcher` and subscribed to via `CommandListener` (SPI)
