= `EntityChangesPublisher`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

WARNING: TODO: this content has not yet been reviewed/updated for v2.0

The (internal) `EntityChangesPublisher` service acts as an internal facade to any configured xref:system:generated:index/applib/services/publishing/spi/EntityChangesSubscriber.adoc[`EntityChangesSubscriber`] domain service(s).

For changing entities, it provides an API for the framework to call at the end of the interaction; it obtains details of the changed entities (from the xref:core:runtime-services:ChangedObjectsService.adoc[`ChangedObjectsService`]) and filters them to just those objects that are to be published; these are then passed through to any configured `EntityChangesSubscriber` implementations.


== SPI and Implementation

The SPI of the service is:

[source,java]
----
public class EntityChangesPublisher {

	void publishChanging(...);   // <1>

}
----
<1> to published all changing entities that are to be published (with the xref:system:generated:index/applib/annotation/DomainObject.adoc#publishing[`@DomainObject#publishing`] annotation attribute or equivalent).

== Related Classes

In total there are 4 sorts of data the framework has publishers for ...
. *EntityPropertyChanges*: published via `EntityPropertyChangePublisher` and subscribed to via `EntityPropertyChangeSubscriber` (SPI)
. *EntityChanges*: published via `EntityChangesPublisher` and subscribed to via `EntityChangesSubscriber` (SPI)
. *Execution*: published via `ExecutionPublisher` and subscribed to via `ExecutionSubscriber` (SPI)
. *Command*: published via `CommandPublisher` and subscribed to via `CommandSubscriber` (SPI)

