= `ExecutionDispatcher`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

WARNING: TODO: this content has not yet been reviewed/updated for v2.0

The (internal) `ExecutionDispatcher` domain service acts as an internal facade to any configured xref:refguide:applib-svc:PublisherService.adoc[`PublisherService`] domain service(s).

For published action invocations/ property edits, it provides an API for those member executions to call.

For published objects, it provides an API for the framework to call at the end of the interaction; it obtains details of the changed objects (from the xref:core:runtime-services:ChangedObjectsService.adoc[`ChangedObjectsServiceInternal`]) and filters them to just those objects that are to be published; these are then passed through to any configured `PublisherService` implementations.


== SPI and Implementation

The SPI of the service is:

[source,java]
----
public class ExecutionDispatcher {

	void dispatchActionInvoking(Execution execution);   // <1>
	
    void dispatchPropertyChanging(Execution execution); // <2>
    
}
----
<1> to publish an action invocation, as represented by the specified member `Execution` parameter and with the xref:refguide:applib-ant:Action.adoc#publishing[`@Action#executionDispatch`] annotation attribute or equivalent, to any configured xref:refguide:applib-svc:PublisherService.adoc[`PublisherService`].
The `Execution` object will be an instance of `ActionInvocation` (see xref:refguide:applib-svc:InteractionContext.adoc[`InteractionContext`] for details).
<2> to publish a property edit, as as represented by the specified member `Execution` parameter and with the xref:refguide:applib-ant:Property.adoc#publishing[`@Property#executionDispatch`] annotation attribute or equivalent, to any configured xref:refguide:applib-svc:PublisherService.adoc[`PublisherService`].
The `Execution` object will be an instance of `PropertyEdit` (see xref:refguide:applib-svc:InteractionContext.adoc[`InteractionContext`] for details).

== Related Classes

In total there are 4 sorts of data the framework has dispatchers for ...
. *EntityAudit*: dispatched via `EntityAuditDispatcher` and subscribed to via `EntityAuditListener` (SPI)
. *ChangingEntities*: dispatched via `ChangingEntitiesDispatcher` and subscribed to via `ChangingEntitiesListener` (SPI)
. *Execution*: dispatched via `ExecutionDispatcher` and subscribed to via `ExecutionListener` (SPI)
. *Command*: dispatched via `CommandDispatcher` and subscribed to via `CommandListener` (SPI)