The framework has built-in support for all of the primitive data types, including `byte`.

From here you can:

* navigate to an entity that uses the `byte` datatype
* open a view model that uses the `byte` datatype

Because `byte` is a primitive value, the properties on these domain objects are mandatory.

== Common interface

These objects both implement a common interface, `PrimitiveByteHolder`:

[source,java]
----
include::holder/PrimitiveByteHolder.java[tags=class]
----

The default methods have annotations that automatically inherited.
Using `@MemberOrder` positions the properties into the appropriate `<field-set>` within the `Xxx.layout.xml` layout file.


== Mixin actions

A number of mixin actions contribute through this interface, demonstrate the use of `byte` as a parameter and as a return type.
For example:

* the `updateReadOnlyPropertyPromptStyleInline` action is:
+
[source,java]
----
include::holder/PrimitiveByteHolder_updateReadOnlyPropertyPromptStyleInline.java[tags=class]
----
+
There are a number of variants of this action, to demonstrate different prompt layouts.

* the `actionReturning` action is:
+
[source,java]
----
include::holder/PrimitiveByteHolder_actionReturning.java[tags=class]
----

== Mixin properties

We also use the interface to contribute a number of mixin properties:

* the `mixinPropertyWithCssClass` property:
+
[source,java]
----
include::holder/PrimitiveByteHolder_mixinPropertyWithCssClass.java[tags=class]
----
+
TIP: the styling is provided from the `application.css` static resource.


