= System Overview

These tables summarize all Maven artifacts available with _Apache Isis_.

== Base

[plantuml,Base,svg]
----
@startuml(id=Base)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis\n<size:10>[Container: packaging: pom]</size>" <<4>> as 4
  rectangle "==Apache Isis (Aggregator)\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
  rectangle "==Apache Isis Antora\n<size:10>[Container: packaging: pom]</size>" <<3>> as 3
  rectangle "==Apache Isis Supplemental - Legal Info\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
}
2 .[#707070].> 4 : ""
2 .[#707070].> 3 : ""
@enduml
----

.Projects/Modules (Base)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis
|isis-all
|pom
|
|Apache Isis (Aggregator)
|Convenience aggregator POM that references all modules.
        The parent POM of the core framework is isis-parent/pom.xml



|org.apache.isis
|antora
|pom
|\antora
|Apache Isis Antora
|

|org.apache.isis
|isis-parent
|pom
|\isis-parent
|Apache Isis
|Parent for the core framework + extensions, starter parent pom for starter apps.



|org.apache.isis
|supplemental-model
|jar
|\supplemental-model
|Apache Isis Supplemental - Legal Info
|For example, the templates used by many Apache distributions assemble a listing of project dependencies 
  	according to their organization name (and URL), along with the URL each project's website. When dependency 
  	POMs are missing this information, the dependency notice file that the Remote Resources Plugin renders can 
  	be invalid.
	To compensate for incomplete dependency POMs, we use the supplemental models support.


|===

== Commons

[plantuml,Commons,svg]
----
@startuml(id=Commons)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Commons\n<size:10>[Container: packaging: jar]</size>" <<2>> as 2
}
@enduml
----

.Projects/Modules (Commons)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.commons
|isis-commons
|jar
|\commons
|Apache Isis Commons
|Apache Isis Commons is a library with utilities, that are shared with the entire Apache Isis ecosystem.

_Dependencies_

* com.fasterxml.jackson.core:jackson-databind:jar:<managed>
* com.google.code.findbugs:annotations:jar:<managed>
* javax:javaee-api:jar:<managed>
* org.junit.jupiter:junit-jupiter-api:jar:<managed>
* org.junit.jupiter:junit-jupiter-engine:jar:<managed>
* org.junit.jupiter:junit-jupiter-params:jar:<managed>
* org.junit.vintage:junit-vintage-engine:jar:<managed>
* org.slf4j:slf4j-api:jar:<managed>
* org.springframework:spring-context:jar:<managed>
* org.springframework:spring-tx:jar:<managed>
* org.springframework.boot:spring-boot-starter:jar:<managed>
* org.springframework.boot:spring-boot-starter-log4j2:jar:<managed>
* org.yaml:snakeyaml:jar:<managed>


|===

== Core

[plantuml,Core,svg]
----
@startuml(id=Core)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<11>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<12>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<8>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<9>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<10>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Core\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
  rectangle "==Apache Isis Core - AppLib\n<size:10>[Container: packaging: jar]</size>" <<3>> as 3
  rectangle "==Apache Isis Core - Code Gen (ByteBuddy)\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Core - Configuration\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
  rectangle "==Apache Isis Core - MetaModel\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
  rectangle "==Apache Isis Core - Runtime\n<size:10>[Container: packaging: jar]</size>" <<8>> as 8
  rectangle "==Apache Isis Core - Runtime Services\n<size:10>[Container: packaging: jar]</size>" <<9>> as 9
  rectangle "==Apache Isis Core - Schemas\n<size:10>[Container: packaging: jar]</size>" <<12>> as 12
  rectangle "==Apache Isis Core - Security\n<size:10>[Container: packaging: jar]</size>" <<10>> as 10
  rectangle "==Apache Isis Core - Unit Test Support\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Apache Isis Core - WebApp\n<size:10>[Container: packaging: jar]</size>" <<11>> as 11
}
2 .[#707070].> 3 : ""
2 .[#707070].> 4 : ""
2 .[#707070].> 5 : ""
2 .[#707070].> 7 : ""
2 .[#707070].> 8 : ""
2 .[#707070].> 9 : ""
2 .[#707070].> 12 : ""
2 .[#707070].> 10 : ""
2 .[#707070].> 6 : ""
2 .[#707070].> 11 : ""
@enduml
----

.Projects/Modules (Core)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.core
|isis-core
|pom
|\core
|Apache Isis Core
|Core framework, providing metamodel, runtime and core APIs.

_Dependencies_

* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.core
|isis-applib
|jar
|\api\applib
|Apache Isis Core - AppLib
|Isis application library, defining annotations and utilities for the
        default (Java) programming model.

_Components_

* org.apache.isis.applib.annotation.DomainObject
* org.apache.isis.applib.annotation.DomainService
* org.apache.isis.applib.annotation.Mixin
* org.apache.isis.applib.annotation.ViewModel
* org.apache.isis.applib.services.audit.AuditerServiceLogging
* org.apache.isis.applib.services.clock.ClockService
* org.apache.isis.applib.services.command.CommandService
* org.apache.isis.applib.services.command.spi.CommandServiceListener$Null
* org.apache.isis.applib.services.commanddto.conmap.ContentMappingServiceForCommandDto
* org.apache.isis.applib.services.commanddto.conmap.ContentMappingServiceForCommandsDto
* org.apache.isis.applib.services.commanddto.processor.spi.CommandDtoProcessorServiceIdentity
* org.apache.isis.applib.services.iactn.InteractionContext
* org.apache.isis.applib.services.jaxb.JaxbServiceDefault
* org.apache.isis.applib.services.publish.PublisherServiceLogging
* org.apache.isis.applib.services.session.SessionLoggingServiceLogging

_Dependencies_

* com.google.code.findbugs:annotations:jar:<managed>
* javax:javaee-api:jar:<managed>
* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-schema:jar:<managed>
* org.assertj:assertj-core:jar:<managed>
* org.jmock:jmock:jar:<managed>



|org.apache.isis.core
|isis-core-codegen-bytebuddy
|jar
|\core\codegen-bytebuddy
|Apache Isis Core - Code Gen (ByteBuddy)
|Code generation using ByteBuddy.

_Components_

* org.apache.isis.core.codegen.bytebuddy.services.ProxyFactoryServiceByteBuddy

_Dependencies_

* net.bytebuddy:byte-buddy:jar:<managed>
* org.apache.isis.commons:isis-commons:jar:<managed>
* org.jmock:jmock-junit4:jar:<managed>
* org.objenesis:objenesis:jar:${objenesis.version}



|org.apache.isis.core
|isis-core-config
|jar
|\core\config
|Apache Isis Core - Configuration
|Isis configuration library for framework internal use.

_Components_

* org.apache.isis.core.config.beans.IsisBeanFactoryPostProcessorForSpring
* org.apache.isis.core.config.converters.PatternsConverter
* org.apache.isis.core.config.environment.IsisSystemEnvironment
* org.apache.isis.core.config.validators.PatternOptionalStringConstraintValidator
* org.apache.isis.core.config.viewer.wicket.WebAppContextPath

_Dependencies_

* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.hibernate.validator:hibernate-validator:jar:<managed>
* org.springframework.boot:spring-boot-configuration-processor:jar:<managed>



|org.apache.isis.core
|isis-core-internaltestsupport
|jar
|\core\internaltestsupport
|Apache Isis Core - Unit Test Support
|Support for writing unit tests in either JUnit 4 or JUnit 5; should be added as a dependency with scope=test only

_Dependencies_

* net.bytebuddy:byte-buddy:jar:<managed>
* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.core:isis-core-codegen-bytebuddy:jar:<managed>
* org.assertj:assertj-core:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>
* org.hamcrest:hamcrest-library:jar:<managed>
* org.jmock:jmock:jar:<managed>
* org.jmock:jmock-junit4:jar:<managed>
* org.junit.jupiter:junit-jupiter-api:jar:<managed>
* org.junit.jupiter:junit-jupiter-engine:jar:<managed>
* org.junit.vintage:junit-vintage-engine:jar:<managed>
* org.mockito:mockito-core:jar:<managed>
* org.picocontainer:picocontainer:jar:<managed>
* org.slf4j:slf4j-api:jar:${slf4j-api.version}
* org.springframework:spring-test:jar:<managed>
* org.springframework.boot:spring-boot-starter-test:jar:<managed>



|org.apache.isis.core
|isis-core-metamodel
|jar
|\core\metamodel
|Apache Isis Core - MetaModel
|_Components_

* org.apache.isis.core.metamodel.facets.schema.IsisSchemaMetaModelRefiner
* org.apache.isis.core.metamodel.facets.schema.IsisSchemaValueTypeProvider
* org.apache.isis.core.metamodel.objectmanager.ObjectManagerDefault
* org.apache.isis.core.metamodel.progmodel.ProgrammingModelInitFilterDefault
* org.apache.isis.core.metamodel.services.ServiceInjectorDefault
* org.apache.isis.core.metamodel.services.appfeat.ApplicationFeatureFactory
* org.apache.isis.core.metamodel.services.appfeat.ApplicationFeatureRepositoryDefault
* org.apache.isis.core.metamodel.services.classsubstitutor.ClassSubstitutorDefault
* org.apache.isis.core.metamodel.services.classsubstitutor.ClassSubstitutorForCollections
* org.apache.isis.core.metamodel.services.classsubstitutor.ClassSubstitutorForDomainObjects
* org.apache.isis.core.metamodel.services.classsubstitutor.ClassSubstitutorRegistry
* org.apache.isis.core.metamodel.services.events.MetamodelEventService
* org.apache.isis.core.metamodel.services.exceprecog.ExceptionRecognizerForRecoverableException
* org.apache.isis.core.metamodel.services.grid.GridLoaderServiceDefault
* org.apache.isis.core.metamodel.services.grid.GridReaderUsingJaxb
* org.apache.isis.core.metamodel.services.grid.GridServiceDefault
* org.apache.isis.core.metamodel.services.grid.bootstrap3.GridSystemServiceBS3
* org.apache.isis.core.metamodel.services.layout.LayoutServiceDefault
* org.apache.isis.core.metamodel.services.metamodel.MetaModelServiceDefault
* org.apache.isis.core.metamodel.services.registry.ServiceRegistryDefault
* org.apache.isis.core.metamodel.services.tablecol.TableColumnOrderServiceDefault
* org.apache.isis.core.metamodel.services.title.TitleServiceDefault
* org.apache.isis.core.metamodel.specloader.InjectorMethodEvaluatorDefault
* org.apache.isis.core.metamodel.specloader.ProgrammingModelServiceDefault
* org.apache.isis.core.metamodel.specloader.SpecificationLoaderDefault
* org.apache.isis.core.metamodel.valuetypes.ValueTypeProviderDefault
* org.apache.isis.core.metamodel.valuetypes.ValueTypeProviderForBuiltin
* org.apache.isis.core.metamodel.valuetypes.ValueTypeProviderForCollections
* org.apache.isis.core.metamodel.valuetypes.ValueTypeRegistry

_Dependencies_

* io.swagger:swagger-core:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-config:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-security:jar:<managed>
* org.hibernate.validator:hibernate-validator:jar:<managed>
* org.jmock:jmock:jar:<managed>



|org.apache.isis.core
|isis-core-runtime
|jar
|\core\runtime
|Apache Isis Core - Runtime
|_Components_

* org.apache.isis.core.runtime.events.RuntimeEventService
* org.apache.isis.core.runtime.events.persistence.TimestampService
* org.apache.isis.core.runtime.persistence.transaction.AuditerDispatchService
* org.apache.isis.core.runtime.persistence.transaction.ChangedObjectsService

_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-metamodel:jar:<managed>



|org.apache.isis.core
|isis-core-runtimeservices
|jar
|\core\runtimeservices
|Apache Isis Core - Runtime Services
|Introduced to keep the 'runtime' package concise. Viewers don't have dependencies on this module.

_Components_

* org.apache.isis.core.runtimeservices.bookmarks.BookmarkServiceDefault
* org.apache.isis.core.runtimeservices.command.CommandDtoServiceInternalDefault
* org.apache.isis.core.runtimeservices.command.CommandExecutorServiceDefault
* org.apache.isis.core.runtimeservices.confmenu.ConfigurationViewServiceDefault
* org.apache.isis.core.runtimeservices.email.EmailServiceDefault
* org.apache.isis.core.runtimeservices.eventbus.EventBusServiceSpring
* org.apache.isis.core.runtimeservices.exceprecog.ExceptionRecognizerServiceDefault
* org.apache.isis.core.runtimeservices.factory.FactoryServiceDefault
* org.apache.isis.core.runtimeservices.homepage.HomePageResolverServiceDefault
* org.apache.isis.core.runtimeservices.i18n.po.TranslationServicePo
* org.apache.isis.core.runtimeservices.ixn.InteractionDtoServiceInternalDefault
* org.apache.isis.core.runtimeservices.menubars.MenuBarsLoaderServiceDefault
* org.apache.isis.core.runtimeservices.menubars.bootstrap3.MenuBarsServiceBS3
* org.apache.isis.core.runtimeservices.message.MessageServiceDefault
* org.apache.isis.core.runtimeservices.publish.PublisherDispatchServiceDefault
* org.apache.isis.core.runtimeservices.queryresultscache.QueryResultsCacheDefault
* org.apache.isis.core.runtimeservices.repository.RepositoryServiceDefault
* org.apache.isis.core.runtimeservices.routing.RoutingServiceDefault
* org.apache.isis.core.runtimeservices.scratchpad.ScratchpadDefault
* org.apache.isis.core.runtimeservices.session.IsisInteractionFactoryDefault
* org.apache.isis.core.runtimeservices.sudo.SudoServiceDefault
* org.apache.isis.core.runtimeservices.urlencoding.UrlEncodingServiceWithCompression
* org.apache.isis.core.runtimeservices.user.UserServiceDefault
* org.apache.isis.core.runtimeservices.user.UserServiceDefault$SudoServiceSpi
* org.apache.isis.core.runtimeservices.userprof.UserProfileServiceDefault
* org.apache.isis.core.runtimeservices.userreg.EmailNotificationServiceDefault
* org.apache.isis.core.runtimeservices.wrapper.WrapperFactoryDefault
* org.apache.isis.core.runtimeservices.xactn.TransactionServiceSpring
* org.apache.isis.core.runtimeservices.xml.XmlServiceDefault
* org.apache.isis.core.runtimeservices.xmlsnapshot.XmlSnapshotServiceDefault

_Dependencies_

* org.apache.isis.core:isis-core-codegen-bytebuddy:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.hsqldb:hsqldb:jar:<managed>



|org.apache.isis.core
|isis-core-security
|jar
|\core\security
|Apache Isis Core - Security
|_Components_

* org.apache.isis.core.security.authentication.manager.AuthenticationManager
* org.apache.isis.core.security.authentication.standard.RandomCodeGeneratorDefault
* org.apache.isis.core.security.authorization.manager.AuthorizationManager

_Dependencies_

* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-config:jar:<managed>
* org.hamcrest:hamcrest-library:jar:<managed>
* org.jmock:jmock-junit4:jar:<managed>
* org.junit.jupiter:junit-jupiter-api:jar:<managed>
* org.junit.jupiter:junit-jupiter-engine:jar:<managed>
* org.junit.vintage:junit-vintage-engine:jar:<managed>



|org.apache.isis.core
|isis-core-webapp
|jar
|\core\webapp
|Apache Isis Core - WebApp
|Bundles all the web specific classes a srequired by viewers.
        Introduced to keep the 'runtime' package concise.

_Components_

* org.apache.isis.core.webapp.health.HealthIndicatorUsingHealthCheckService
* org.apache.isis.core.webapp.modules.logonlog.WebModuleLogOnExceptionLogger
* org.apache.isis.core.webapp.modules.templresources.WebModuleTemplateResources
* org.apache.isis.core.webapp.webappctx.IsisWebAppContextInitializer

_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.springframework:spring-web:jar:<managed>
* org.springframework.boot:spring-boot:jar:<managed>
* org.springframework.boot:spring-boot-actuator:jar:<managed>
* org.springframework.boot:spring-boot-starter-thymeleaf:jar:<managed>



|org.apache.isis.core
|isis-schema
|jar
|\api\schema
|Apache Isis Core - Schemas
|Apache Isis schemas, for conversion into canonical DTOs (for use in integration scenarios).

_Dependencies_

* joda-time:joda-time:jar:<managed>
* org.springframework:spring-context:jar:<managed>


|===

== App

[plantuml,App,svg]
----
@startuml(id=App)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Starter Parent\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
}
@enduml
----

.Projects/Modules (App)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.app
|isis-app-starter-parent
|pom
|\starters
|Apache Isis Starter Parent
|Parent pom providing dependency and plugin management for Apache Isis applications
		built with Maven.  Builds on top of spring-boot-starter-parent.


|===

== Mavendeps

[plantuml,Mavendeps,svg]
----
@startuml(id=Mavendeps)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Maven Deps\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
  rectangle "==Apache Isis Maven Deps - BDD Integ Spec\n<size:10>[Container: packaging: pom]</size>" <<3>> as 3
  rectangle "==Apache Isis Maven Deps - Integration Testing\n<size:10>[Container: packaging: pom]</size>" <<4>> as 4
  rectangle "==Apache Isis Maven Deps - JDK11\n<size:10>[Container: packaging: pom]</size>" <<5>> as 5
  rectangle "==Apache Isis Maven Deps - Testing\n<size:10>[Container: packaging: pom]</size>" <<6>> as 6
  rectangle "==Apache Isis Maven Deps - Webapp\n<size:10>[Container: packaging: pom]</size>" <<7>> as 7
}
2 .[#707070].> 3 : ""
2 .[#707070].> 4 : ""
2 .[#707070].> 5 : ""
2 .[#707070].> 6 : ""
2 .[#707070].> 7 : ""
@enduml
----

.Projects/Modules (Mavendeps)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.mavendeps
|isis-mavendeps
|pom
|\mavendeps
|Apache Isis Maven Deps
|Collection of Apache Isis Maven Dependency Bundles.



|org.apache.isis.mavendeps
|isis-mavendeps-integspecs
|pom
|\mavendeps\integspecs
|Apache Isis Maven Deps - BDD Integ Spec
|Defines a module that can be used as a single dependency for BDD (Cucumber) specs as integration tests.

_Dependencies_

* org.apache.isis.testing:isis-testing-fakedata-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-specsupport-applib:jar:<managed>



|org.apache.isis.mavendeps
|isis-mavendeps-integtests
|pom
|\mavendeps\integtests
|Apache Isis Maven Deps - Integration Testing
|Defines a module that can be used as a single dependency for integration tests.

_Dependencies_

* org.apache.isis.testing:isis-testing-fakedata-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-integtestsupport-applib:jar:<managed>



|org.apache.isis.mavendeps
|isis-mavendeps-jdk11
|pom
|\mavendeps\jdk11
|Apache Isis Maven Deps - JDK11
|Defines a module to bring in dependencies that were part of JDK 8 but
        had been removed with JDK 11+. These dependencies are activated when the 
        consuming project is built with JDK 11 or higher.



|org.apache.isis.mavendeps
|isis-mavendeps-unittests
|pom
|\mavendeps\unittests
|Apache Isis Maven Deps - Testing
|Defines a module that can be used as a single dependency for a set of common testing libraries.

_Dependencies_

* org.apache.isis.testing:isis-testing-fakedata-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-unittestsupport-applib:jar:<managed>



|org.apache.isis.mavendeps
|isis-mavendeps-webapp
|pom
|\mavendeps\webapp
|Apache Isis Maven Deps - Webapp
|Defines a module that can be used as a single dependency for running an Apache Isis webapp (Wicket, Restful Objects and Shiro security)

_Dependencies_

* commons-logging:commons-logging:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-runtimeservices:jar:<managed>
* org.apache.isis.core:isis-core-security:jar:<managed>
* org.apache.isis.core:isis-schema:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-datanucleus5:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jpa-model:jar:<managed>
* org.apache.isis.security:isis-security-bypass:jar:<managed>
* org.apache.isis.security:isis-security-keycloak:jar:<managed>
* org.apache.isis.security:isis-security-shiro:jar:<managed>
* org.apache.isis.viewer:isis-viewer-restfulobjects-jaxrsresteasy4:jar:<managed>
* org.apache.isis.viewer:isis-viewer-restfulobjects-viewer:jar:<managed>
* org.apache.isis.viewer:isis-viewer-wicket-viewer:jar:<managed>
* org.springframework.boot:spring-boot-starter-tomcat:jar:<managed>
* org.springframework.boot:spring-boot-starter-web:jar:<managed>


|===

== Mappings

[plantuml,Mappings,svg]
----
@startuml(id=Mappings)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Ext - REST Client (applib)\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
  rectangle "==Apache Isis Ext - REST Client (parent)\n<size:10>[Container: packaging: pom]</size>" <<6>> as 6
  rectangle "==Apache Isis Map - JaxRS Client (applib)\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Map - JaxRS Client (impl)\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
  rectangle "==Apache Isis Map - JaxRS Client (parent)\n<size:10>[Container: packaging: pom]</size>" <<3>> as 3
  rectangle "==Apache Isis Mappings\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
}
6 .[#707070].> 7 : ""
3 .[#707070].> 4 : ""
3 .[#707070].> 5 : ""
2 .[#707070].> 6 : ""
2 .[#707070].> 3 : ""
@enduml
----

.Projects/Modules (Mappings)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.mappings
|isis-mappings
|pom
|\mappings
|Apache Isis Mappings
|Libraries and tools to map one bounded context (usually an Apache Isis application) to some other BC (usually
		_not_ an Apache Isis application).

_Dependencies_

* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.mappings
|isis-mappings-jaxrsclient
|pom
|\mappings\jaxrsclient
|Apache Isis Map - JaxRS Client (parent)
|Integrates JaxRS Client Library



|org.apache.isis.mappings
|isis-mappings-jaxrsclient-applib
|jar
|\mappings\jaxrsclient\applib
|Apache Isis Map - JaxRS Client (applib)
|_Dependencies_

* javax:javaee-api:jar:<managed>
* org.springframework:spring-context:jar:<managed>



|org.apache.isis.mappings
|isis-mappings-jaxrsclient-impl
|jar
|\mappings\jaxrsclient\testlib
|Apache Isis Map - JaxRS Client (impl)
|_Dependencies_

* org.apache.isis.mappings:isis-mappings-jaxrsclient-applib:jar:<managed>



|org.apache.isis.mappings
|isis-mappings-restclient
|pom
|\mappings\restclient
|Apache Isis Ext - REST Client (parent)
|A client for the Restful Objects Viewer



|org.apache.isis.mappings
|isis-mappings-restclient-applib
|jar
|\mappings\restclient\applib
|Apache Isis Ext - REST Client (applib)
|A client for the Restful Objects Viewer

_Dependencies_

* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.springframework:spring-context:jar:<managed>


|===

== Persistence

[plantuml,Persistence,svg]
----
@startuml(id=Persistence)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Persistence - JDO\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
  rectangle "==Apache Isis Persistence - JDO (applib)\n<size:10>[Container: packaging: jar]</size>" <<3>> as 3
  rectangle "==Apache Isis Persistence - JDO (datanucleus 5)\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Persistence - JPA\n<size:10>[Container: packaging: pom]</size>" <<5>> as 5
  rectangle "==Apache Isis Persistence - JPA (applib)\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Apache Isis Persistence - JPA (model)\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
}
2 .[#707070].> 3 : ""
2 .[#707070].> 4 : ""
5 .[#707070].> 6 : ""
5 .[#707070].> 7 : ""
@enduml
----

.Projects/Modules (Persistence)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.persistence
|isis-persistence-jdo
|pom
|\persistence\jdo
|Apache Isis Persistence - JDO
|Supplementary applib for JDO persistence



|org.apache.isis.persistence
|isis-persistence-jdo-applib
|jar
|\persistence\jdo\applib
|Apache Isis Persistence - JDO (applib)
|Supplementary applib for JDO persistence

_Dependencies_

* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.datanucleus:datanucleus-rdbms:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>



|org.apache.isis.persistence
|isis-persistence-jdo-datanucleus5
|jar
|\persistence\jdo\datanucleus-5
|Apache Isis Persistence - JDO (datanucleus 5)
|JDO plugin using datanucleus.

_Components_

* org.apache.isis.persistence.jdo.datanucleus5.datanucleus.DataNucleusSettings
* org.apache.isis.persistence.jdo.datanucleus5.datanucleus.service.JdoPersistenceLifecycleService
* org.apache.isis.persistence.jdo.datanucleus5.exceprecog.ExceptionRecognizerForJDODataStoreException
* org.apache.isis.persistence.jdo.datanucleus5.exceprecog.ExceptionRecognizerForJDODataStoreExceptionIntegrityConstraintViolationForeignKeyNoActionException
* org.apache.isis.persistence.jdo.datanucleus5.exceprecog.ExceptionRecognizerForJDOObjectNotFoundException
* org.apache.isis.persistence.jdo.datanucleus5.exceprecog.ExceptionRecognizerForSQLIntegrityConstraintViolationUniqueOrIndexException
* org.apache.isis.persistence.jdo.datanucleus5.jdosupport.IsisJdoSupportDN5
* org.apache.isis.persistence.jdo.datanucleus5.metamodel.JdoProgrammingModelPlugin
* org.apache.isis.persistence.jdo.datanucleus5.metrics.MetricsServiceDefault
* org.apache.isis.persistence.jdo.datanucleus5.persistence.IsisPlatformTransactionManagerForJdo
* org.apache.isis.persistence.jdo.datanucleus5.persistence.PersistenceSessionFactory5

_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-applib:jar:<managed>
* org.datanucleus:datanucleus-api-jdo:jar:<managed>
* org.datanucleus:datanucleus-core:jar:<managed>
* org.datanucleus:datanucleus-jdo-query:jar:<managed>
* org.datanucleus:datanucleus-jodatime:jar:<managed>
* org.datanucleus:datanucleus-rdbms:jar:<managed>



|org.apache.isis.persistence
|isis-persistence-jpa
|pom
|\persistence\jpa
|Apache Isis Persistence - JPA
|Apache Isis JPA integration



|org.apache.isis.persistence
|isis-persistence-jpa-applib
|jar
|\persistence\jpa\applib
|Apache Isis Persistence - JPA (applib)
|Supplementary applib for JPA persistence

_Dependencies_

* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>



|org.apache.isis.persistence
|isis-persistence-jpa-model
|jar
|\persistence\jpa\model
|Apache Isis Persistence - JPA (model)
|JPA integration (metamodel)

_Components_

* org.apache.isis.persistence.jpa.metamodel.JpaProgrammingModelPlugin

_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jpa-applib:jar:<managed>
* org.springframework.data:spring-data-jpa:jar:<managed>


|===

== Security

[plantuml,Security,svg]
----
@startuml(id=Security)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Security - Bypass\n<size:10>[Container: packaging: jar]</size>" <<2>> as 2
  rectangle "==Apache Isis Security - Keycloak\n<size:10>[Container: packaging: jar]</size>" <<3>> as 3
  rectangle "==Apache Isis Security - Shiro\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
}
@enduml
----

.Projects/Modules (Security)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.security
|isis-security-bypass
|jar
|\security\bypass
|Apache Isis Security - Bypass
|_Components_

* org.apache.isis.security.bypass.authentication.AuthenticatorBypass
* org.apache.isis.security.bypass.authorization.AuthorizorBypass

_Dependencies_

* org.apache.isis.core:isis-core-runtimeservices:jar:<managed>



|org.apache.isis.security
|isis-security-keycloak
|jar
|\security\keycloak
|Apache Isis Security - Keycloak
|Authentication and Authorization using Keycloak

_Components_

* org.apache.isis.security.keycloak.authentication.AuthenticatorKeycloak
* org.apache.isis.security.keycloak.authorization.AuthorizorKeycloak
* org.apache.isis.security.keycloak.webmodule.WebModuleKeycloak

_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.core:isis-core-runtimeservices:jar:<managed>
* org.apache.isis.core:isis-core-webapp:jar:<managed>



|org.apache.isis.security
|isis-security-shiro
|jar
|\security\shiro
|Apache Isis Security - Shiro
|Authentication and Authorization using Apache Shiro.

_Components_

* org.apache.isis.security.shiro.authentication.AuthenticatorShiro
* org.apache.isis.security.shiro.authorization.AuthorizorShiro
* org.apache.isis.security.shiro.webmodule.WebModuleShiro

_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.core:isis-core-runtimeservices:jar:<managed>
* org.apache.isis.core:isis-core-webapp:jar:<managed>
* org.apache.shiro:shiro-core:jar:<managed>
* org.apache.shiro:shiro-web:jar:<managed>


|===

== Valuetypes

[plantuml,Valuetypes,svg]
----
@startuml(id=Valuetypes)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<22>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<11>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<12>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<13>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<14>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<15>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<16>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<17>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<18>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<19>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<8>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<9>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<20>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<21>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<10>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Val - Asciidoctor (MetaModel)\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
  rectangle "==Apache Isis Val - Asciidoctor (Persistence)\n<size:10>[Container: packaging: pom]</size>" <<6>> as 6
  rectangle "==Apache Isis Val - Asciidoctor (applib)\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Val - Asciidoctor (parent)\n<size:10>[Container: packaging: pom]</size>" <<3>> as 3
  rectangle "==Apache Isis Val - Asciidoctor (persistence jdo DN5)\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
  rectangle "==Apache Isis Val - Asciidoctor (ui vaadin)\n<size:10>[Container: packaging: jar]</size>" <<9>> as 9
  rectangle "==Apache Isis Val - Asciidoctor (ui wicket)\n<size:10>[Container: packaging: jar]</size>" <<10>> as 10
  rectangle "==Apache Isis Val - Asciidoctor (ui)\n<size:10>[Container: packaging: pom]</size>" <<8>> as 8
  rectangle "==Apache Isis Val - Markdown (MetaModel)\n<size:10>[Container: packaging: jar]</size>" <<13>> as 13
  rectangle "==Apache Isis Val - Markdown (Persistence)\n<size:10>[Container: packaging: pom]</size>" <<14>> as 14
  rectangle "==Apache Isis Val - Markdown (applib)\n<size:10>[Container: packaging: jar]</size>" <<12>> as 12
  rectangle "==Apache Isis Val - Markdown (parent)\n<size:10>[Container: packaging: pom]</size>" <<11>> as 11
  rectangle "==Apache Isis Val - Markdown (persistence jdo DN5)\n<size:10>[Container: packaging: jar]</size>" <<15>> as 15
  rectangle "==Apache Isis Val - Markdown (ui wicket)\n<size:10>[Container: packaging: jar]</size>" <<17>> as 17
  rectangle "==Apache Isis Val - Markdown (ui)\n<size:10>[Container: packaging: pom]</size>" <<16>> as 16
  rectangle "==Apache Isis Val - SSE (ui)\n<size:10>[Container: packaging: pom]</size>" <<21>> as 21
  rectangle "==Apache Isis Val - Server Sent Events\n<size:10>[Container: packaging: jar]</size>" <<19>> as 19
  rectangle "==Apache Isis Val - Server Sent Events (metamodel)\n<size:10>[Container: packaging: jar]</size>" <<20>> as 20
  rectangle "==Apache Isis Val - Server Sent Events (parent)\n<size:10>[Container: packaging: pom]</size>" <<18>> as 18
  rectangle "==Apache Isis Val - Server Sent Events (ui wicket)\n<size:10>[Container: packaging: jar]</size>" <<22>> as 22
  rectangle "==Apache Isis Value types\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
}
6 .[#707070].> 7 : ""
3 .[#707070].> 5 : ""
3 .[#707070].> 6 : ""
3 .[#707070].> 4 : ""
3 .[#707070].> 8 : ""
8 .[#707070].> 9 : ""
8 .[#707070].> 10 : ""
14 .[#707070].> 15 : ""
11 .[#707070].> 13 : ""
11 .[#707070].> 14 : ""
11 .[#707070].> 12 : ""
11 .[#707070].> 16 : ""
16 .[#707070].> 17 : ""
21 .[#707070].> 22 : ""
18 .[#707070].> 21 : ""
18 .[#707070].> 19 : ""
18 .[#707070].> 20 : ""
2 .[#707070].> 3 : ""
2 .[#707070].> 11 : ""
2 .[#707070].> 18 : ""
@enduml
----

.Projects/Modules (Valuetypes)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.valuetypes
|isis-valuetypes
|pom
|\valuetypes
|Apache Isis Value types
|Value types for use within Apache Isis applications.

_Dependencies_

* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-asciidoc
|pom
|\valuetypes\asciidoc
|Apache Isis Val - Asciidoctor (parent)
|Asciidoc value type.



|org.apache.isis.valuetypes
|isis-valuetypes-asciidoc-applib
|jar
|\valuetypes\asciidoc\applib
|Apache Isis Val - Asciidoctor (applib)
|_Dependencies_

* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.asciidoctor:asciidoctorj-api:jar:${asciidoctorj.version}



|org.apache.isis.valuetypes
|isis-valuetypes-asciidoc-metamodel
|jar
|\valuetypes\asciidoc\metamodel
|Apache Isis Val - Asciidoctor (MetaModel)
|_Components_

* org.apache.isis.valuetypes.asciidoc.metamodel.AsciiDocMetaModelRefiner
* org.apache.isis.valuetypes.asciidoc.metamodel.AsciiDocValueTypeProvider

_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-applib:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-asciidoc-persistence
|pom
|\valuetypes\asciidoc\persistence
|Apache Isis Val - Asciidoctor (Persistence)
|_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-applib:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-asciidoc-persistence-jdo-dn5
|jar
|\valuetypes\asciidoc\persistence\jdo-dn5
|Apache Isis Val - Asciidoctor (persistence jdo DN5)
|_Dependencies_

* org.datanucleus:datanucleus-core:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-asciidoc-ui
|pom
|\valuetypes\asciidoc\ui
|Apache Isis Val - Asciidoctor (ui)
|_Dependencies_

* com.github.jnr:jnr-constants:jar:0.9.11
* com.github.jnr:jnr-enxio:jar:0.20
* com.github.jnr:jnr-posix:jar:3.0.49
* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-applib:jar:<managed>
* org.asciidoctor:asciidoctorj:jar:${asciidoctorj.version}



|org.apache.isis.valuetypes
|isis-valuetypes-asciidoc-ui-vaa
|jar
|\valuetypes\asciidoc\ui\vaadin
|Apache Isis Val - Asciidoctor (ui vaadin)
|_Components_

* org.apache.isis.valuetypes.asciidoc.ui.vaa.components.AsciiDocFieldFactoryVaa

_Dependencies_

* org.apache.isis.incubator.viewer:isis-viewer-vaadin-ui:jar:${project.version}



|org.apache.isis.valuetypes
|isis-valuetypes-asciidoc-ui-wkt
|jar
|\valuetypes\asciidoc\ui\wicket
|Apache Isis Val - Asciidoctor (ui wicket)
|_Components_

* org.apache.isis.valuetypes.asciidoc.ui.wkt.components.AsciiDocPanelFactoriesWkt$Parented
* org.apache.isis.valuetypes.asciidoc.ui.wkt.components.AsciiDocPanelFactoriesWkt$Standalone
* org.apache.isis.valuetypes.asciidoc.ui.wkt.components.schema.chg.v2.ChangesDtoPanelFactoriesWkt$Parented
* org.apache.isis.valuetypes.asciidoc.ui.wkt.components.schema.chg.v2.ChangesDtoPanelFactoriesWkt$Standalone
* org.apache.isis.valuetypes.asciidoc.ui.wkt.components.schema.cmd.v2.CommandDtoPanelFactoriesWkt$Parented
* org.apache.isis.valuetypes.asciidoc.ui.wkt.components.schema.cmd.v2.CommandDtoPanelFactoriesWkt$Standalone
* org.apache.isis.valuetypes.asciidoc.ui.wkt.components.schema.ixn.v2.InteractionDtoPanelFactoriesWkt$Parented
* org.apache.isis.valuetypes.asciidoc.ui.wkt.components.schema.ixn.v2.InteractionDtoPanelFactoriesWkt$Standalone

_Dependencies_

* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-markdown
|pom
|\valuetypes\markdown
|Apache Isis Val - Markdown (parent)
|Markdown value type.



|org.apache.isis.valuetypes
|isis-valuetypes-markdown-applib
|jar
|\valuetypes\markdown\applib
|Apache Isis Val - Markdown (applib)
|_Dependencies_

* com.vladsch.flexmark:flexmark-all:jar:${flexmark.version}
* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-markdown-metamodel
|jar
|\valuetypes\markdown\metamodel
|Apache Isis Val - Markdown (MetaModel)
|_Components_

* org.apache.isis.valuetypes.markdown.metamodel.MarkdownMetaModelRefiner
* org.apache.isis.valuetypes.markdown.metamodel.MarkdownValueTypeProvider

_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-markdown-applib:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-markdown-persistence
|pom
|\valuetypes\markdown\persistence
|Apache Isis Val - Markdown (Persistence)
|_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-markdown-applib:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-markdown-persistence-jdo-dn5
|jar
|\valuetypes\markdown\persistence\jdo-dn5
|Apache Isis Val - Markdown (persistence jdo DN5)
|_Dependencies_

* org.apache.isis.valuetypes:isis-valuetypes-markdown-applib:jar:<managed>
* org.datanucleus:datanucleus-core:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-markdown-ui
|pom
|\valuetypes\markdown\ui
|Apache Isis Val - Markdown (ui)
|_Dependencies_

* com.vladsch.flexmark:flexmark-all:jar:${flexmark.version}
* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-markdown-applib:jar:<managed>
* org.jsoup:jsoup:jar:1.12.1



|org.apache.isis.valuetypes
|isis-valuetypes-markdown-ui-wkt
|jar
|\valuetypes\markdown\ui\wicket
|Apache Isis Val - Markdown (ui wicket)
|_Dependencies_

* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-sse
|pom
|\valuetypes\sse
|Apache Isis Val - Server Sent Events (parent)
|Dynamically updating HTML markup



|org.apache.isis.valuetypes
|isis-valuetypes-sse-applib
|jar
|\valuetypes\sse\applib
|Apache Isis Val - Server Sent Events
|_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.core:isis-core-webapp:jar:<managed>
* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-sse-metamodel
|jar
|\valuetypes\sse\metamodel
|Apache Isis Val - Server Sent Events (metamodel)
|_Components_

* org.apache.isis.valuetypes.sse.metamodel.facets.SseAnnotationFacetFactory$Register

_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-sse-applib:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-sse-ui
|pom
|\valuetypes\sse\ui
|Apache Isis Val - SSE (ui)
|_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-sse-applib:jar:<managed>



|org.apache.isis.valuetypes
|isis-valuetypes-sse-ui-wkt
|jar
|\valuetypes\sse\ui\wicket
|Apache Isis Val - Server Sent Events (ui wicket)
|_Components_

* org.apache.isis.valuetypes.sse.ui.wkt.markup.ListeningMarkupPanelFactoriesForWicket$Parented
* org.apache.isis.valuetypes.sse.ui.wkt.markup.ListeningMarkupPanelFactoriesForWicket$Standalone
* org.apache.isis.valuetypes.sse.ui.wkt.services.SseServiceDefault
* org.apache.isis.valuetypes.sse.ui.wkt.webmodule.WebModuleServerSentEvents

_Dependencies_

* org.apache.isis.valuetypes:isis-valuetypes-sse-metamodel:jar:<managed>
* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>


|===

== Viewer

[plantuml,Viewer,svg]
----
@startuml(id=Viewer)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<11>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<12>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<8>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<9>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<10>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Viewer - Common Model\n<size:10>[Container: packaging: jar]</size>" <<2>> as 2
  rectangle "==Apache Isis Viewer - RO\n<size:10>[Container: packaging: pom]</size>" <<3>> as 3
  rectangle "==Apache Isis Viewer - RO (AppLib)\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Viewer - RO (JAX-RS Resteasy v4)\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
  rectangle "==Apache Isis Viewer - RO (Rendering)\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Apache Isis Viewer - RO (Testing)\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
  rectangle "==Apache Isis Viewer - RO (Viewer)\n<size:10>[Container: packaging: jar]</size>" <<8>> as 8
  rectangle "==Apache Isis Viewer - Wicket\n<size:10>[Container: packaging: pom]</size>" <<9>> as 9
  rectangle "==Apache Isis Viewer - Wicket (Model)\n<size:10>[Container: packaging: jar]</size>" <<10>> as 10
  rectangle "==Apache Isis Viewer - Wicket (UI Components)\n<size:10>[Container: packaging: jar]</size>" <<11>> as 11
  rectangle "==Apache Isis Viewer - Wicket (Viewer)\n<size:10>[Container: packaging: jar]</size>" <<12>> as 12
}
3 .[#707070].> 4 : ""
3 .[#707070].> 5 : ""
3 .[#707070].> 6 : ""
3 .[#707070].> 7 : ""
3 .[#707070].> 8 : ""
9 .[#707070].> 10 : ""
9 .[#707070].> 11 : ""
9 .[#707070].> 12 : ""
@enduml
----

.Projects/Modules (Viewer)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.viewer
|isis-viewer-common
|jar
|\viewers\common
|Apache Isis Viewer - Common Model
|_Components_

* org.apache.isis.viewer.common.model.branding.BrandingUiModelProvider
* org.apache.isis.viewer.common.model.header.HeaderUiModelProvider
* org.apache.isis.viewer.common.model.menu.MenuUiModelProvider
* org.apache.isis.viewer.common.model.userprofile.UserProfileUiModelProvider

_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.webjars:font-awesome:jar:5.13.0



|org.apache.isis.viewer
|isis-viewer-restfulobjects
|pom
|\viewers\restfulobjects
|Apache Isis Viewer - RO
|

|org.apache.isis.viewer
|isis-viewer-restfulobjects-applib
|jar
|\viewers\restfulobjects\applib
|Apache Isis Viewer - RO (AppLib)
|_Dependencies_

* com.fasterxml.jackson.core:jackson-databind:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-metamodel:jar:<managed>



|org.apache.isis.viewer
|isis-viewer-restfulobjects-jaxrsresteasy4
|jar
|\viewers\restfulobjects\jaxrs-resteasy-4
|Apache Isis Viewer - RO (JAX-RS Resteasy v4)
|JAX-RS plugin using jboss resteasy.

_Components_

* org.apache.isis.viewer.restfulobjects.jaxrsresteasy4.conneg.RestfulObjectsJaxbWriterForXml
* org.apache.isis.viewer.restfulobjects.jaxrsresteasy4.webmodule.WebModuleJaxrsResteasy4

_Dependencies_

* com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:<managed>
* org.apache.isis.viewer:isis-viewer-restfulobjects-rendering:jar:<managed>
* org.apache.isis.viewer:isis-viewer-restfulobjects-testing:jar:<managed>
* org.apache.isis.viewer:isis-viewer-restfulobjects-viewer:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>
* org.jboss.resteasy:resteasy-spring-boot-starter:jar:<managed>



|org.apache.isis.viewer
|isis-viewer-restfulobjects-rendering
|jar
|\viewers\restfulobjects\rendering
|Apache Isis Viewer - RO (Rendering)
|_Components_

* org.apache.isis.viewer.restfulobjects.rendering.domainobjects.JsonValueEncoder
* org.apache.isis.viewer.restfulobjects.rendering.service.RepresentationServiceContentNegotiator
* org.apache.isis.viewer.restfulobjects.rendering.service.acceptheader.AcceptHeaderServiceForRest
* org.apache.isis.viewer.restfulobjects.rendering.service.acceptheader.AcceptHeaderServiceForRest$RequestFilter
* org.apache.isis.viewer.restfulobjects.rendering.service.acceptheader.AcceptHeaderServiceForRest$ResponseFilter
* org.apache.isis.viewer.restfulobjects.rendering.service.conneg.ContentNegotiationServiceForRestfulObjectsV1_0
* org.apache.isis.viewer.restfulobjects.rendering.service.conneg.ContentNegotiationServiceOrgApacheIsisV1
* org.apache.isis.viewer.restfulobjects.rendering.service.conneg.ContentNegotiationServiceXRoDomainType
* org.apache.isis.viewer.restfulobjects.rendering.service.swagger.SwaggerServiceDefault
* org.apache.isis.viewer.restfulobjects.rendering.service.swagger.internal.ClassExcluderDefault
* org.apache.isis.viewer.restfulobjects.rendering.service.swagger.internal.SwaggerSpecGenerator
* org.apache.isis.viewer.restfulobjects.rendering.service.swagger.internal.TaggerDefault
* org.apache.isis.viewer.restfulobjects.rendering.service.swagger.internal.ValuePropertyFactoryDefault

_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.viewer:isis-viewer-restfulobjects-applib:jar:<managed>



|org.apache.isis.viewer
|isis-viewer-restfulobjects-testing
|jar
|\viewers\restfulobjects\testing
|Apache Isis Viewer - RO (Testing)
|_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.viewer:isis-viewer-restfulobjects-viewer:jar:<managed>



|org.apache.isis.viewer
|isis-viewer-restfulobjects-viewer
|jar
|\viewers\restfulobjects\viewer
|Apache Isis Viewer - RO (Viewer)
|_Components_

* org.apache.isis.viewer.restfulobjects.viewer.mappers.ExceptionMapperForObjectNotFound
* org.apache.isis.viewer.restfulobjects.viewer.mappers.ExceptionMapperForRestfulObjectsApplication
* org.apache.isis.viewer.restfulobjects.viewer.mappers.ExceptionMapperForRuntimeException
* org.apache.isis.viewer.restfulobjects.viewer.resources.DomainObjectResourceServerside
* org.apache.isis.viewer.restfulobjects.viewer.resources.DomainServiceResourceServerside
* org.apache.isis.viewer.restfulobjects.viewer.resources.DomainTypeResourceServerside
* org.apache.isis.viewer.restfulobjects.viewer.resources.HomePageResourceServerside
* org.apache.isis.viewer.restfulobjects.viewer.resources.ImageResourceServerside
* org.apache.isis.viewer.restfulobjects.viewer.resources.MenuBarsResourceServerside
* org.apache.isis.viewer.restfulobjects.viewer.resources.SwaggerSpecResource
* org.apache.isis.viewer.restfulobjects.viewer.resources.UserResourceServerside
* org.apache.isis.viewer.restfulobjects.viewer.resources.VersionResourceServerside

_Dependencies_

* com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-webapp:jar:<managed>
* org.apache.isis.viewer:isis-viewer-common:jar:<managed>
* org.apache.isis.viewer:isis-viewer-restfulobjects-rendering:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>



|org.apache.isis.viewer
|isis-viewer-wicket
|pom
|\viewers\wicket
|Apache Isis Viewer - Wicket
|

|org.apache.isis.viewer
|isis-viewer-wicket-model
|jar
|\viewers\wicket\model
|Apache Isis Viewer - Wicket (Model)
|_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-webapp:jar:<managed>
* org.apache.isis.viewer:isis-viewer-common:jar:<managed>
* org.apache.wicket:wicket-core:jar:<managed>
* org.apache.wicket:wicket-extensions:jar:<managed>



|org.apache.isis.viewer
|isis-viewer-wicket-ui
|jar
|\viewers\wicket\ui
|Apache Isis Viewer - Wicket (UI Components)
|_Components_

* org.apache.isis.viewer.wicket.ui.app.logout.LogoutHandlerWkt
* org.apache.isis.viewer.wicket.ui.components.widgets.themepicker.IsisWicketThemeSupportDefault

_Dependencies_

* com.google.guava:guava:jar:<managed>
* de.agilecoders.wicket:wicket-bootstrap-core:jar:<managed>
* de.agilecoders.wicket:wicket-bootstrap-extensions:jar:<managed>
* de.agilecoders.wicket:wicket-bootstrap-themes:jar:<managed>
* de.agilecoders.wicket.webjars:wicket-webjars:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.viewer:isis-viewer-wicket-model:jar:<managed>
* org.apache.wicket:wicket-auth-roles:jar:<managed>
* org.apache.wicket:wicket-core:jar:<managed>
* org.apache.wicket:wicket-devutils:jar:<managed>
* org.apache.wicket:wicket-extensions:jar:<managed>
* org.apache.wicket:wicket-spring:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>
* org.slf4j:slf4j-api:jar:${slf4j-api.version}
* org.webjars:jquery-ui:jar:<managed>
* org.webjars:select2:jar:<managed>
* org.webjars.bower:summernote:jar:<managed>
* org.wicketstuff:wicketstuff-select2:jar:<managed>



|org.apache.isis.viewer
|isis-viewer-wicket-viewer
|jar
|\viewers\wicket\viewer
|Apache Isis Viewer - Wicket (Viewer)
|_Components_

* org.apache.isis.viewer.wicket.viewer.registries.components.ComponentFactoryRegistrarDefault
* org.apache.isis.viewer.wicket.viewer.registries.components.ComponentFactoryRegistryDefault
* org.apache.isis.viewer.wicket.viewer.registries.pages.PageClassListDefault
* org.apache.isis.viewer.wicket.viewer.registries.pages.PageClassRegistryDefault
* org.apache.isis.viewer.wicket.viewer.registries.pages.PageNavigationServiceDefault
* org.apache.isis.viewer.wicket.viewer.services.BookmarkUiServiceWicket
* org.apache.isis.viewer.wicket.viewer.services.DeepLinkServiceWicket
* org.apache.isis.viewer.wicket.viewer.services.HintStoreUsingWicketSession
* org.apache.isis.viewer.wicket.viewer.services.ImageResourceCacheClassPath
* org.apache.isis.viewer.wicket.viewer.services.LocaleProviderWicket
* org.apache.isis.viewer.wicket.viewer.services.TranslationsResolverWicket
* org.apache.isis.viewer.wicket.viewer.services.WicketViewerSettingsDefault
* org.apache.isis.viewer.wicket.viewer.services.mementos.ObjectMementoServiceWicket
* org.apache.isis.viewer.wicket.viewer.webmodule.WebModuleWicket

_Dependencies_

* commons-io:commons-io:jar:<managed>
* de.agilecoders.wicket:wicket-bootstrap-core:jar:<managed>
* net.ftlines.wicket-source:wicket-source:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>
* org.apache.wicket:wicket-auth-roles:jar:<managed>
* org.apache.wicket:wicket-spring:jar:<managed>
* org.jmock:jmock-junit4:jar:<managed>
* org.springframework:spring-web:jar:<managed>


|===

== Testing

[plantuml,Testing,svg]
----
@startuml(id=Testing)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<11>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<12>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<13>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<14>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<15>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<16>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<17>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<18>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<8>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<9>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<10>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Testing\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
  rectangle "==Apache Isis Tst - FakeData (applib)\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Tst - FakeData (fixtures)\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
  rectangle "==Apache Isis Tst - FakeData (integ tests)\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Apache Isis Tst - FakeData (parent)\n<size:10>[Container: packaging: pom]</size>" <<3>> as 3
  rectangle "==Apache Isis Tst - Fixtures (applib)\n<size:10>[Container: packaging: jar]</size>" <<8>> as 8
  rectangle "==Apache Isis Tst - Fixtures (parent)\n<size:10>[Container: packaging: pom]</size>" <<7>> as 7
  rectangle "==Apache Isis Tst - H2 Console (parent)\n<size:10>[Container: packaging: pom]</size>" <<9>> as 9
  rectangle "==Apache Isis Tst - H2 Console (ui)\n<size:10>[Container: packaging: jar]</size>" <<10>> as 10
  rectangle "==Apache Isis Tst - HSQLDB Manager\n<size:10>[Container: packaging: jar]</size>" <<12>> as 12
  rectangle "==Apache Isis Tst - HSQLDB Manager (parent)\n<size:10>[Container: packaging: pom]</size>" <<11>> as 11
  rectangle "==Apache Isis Tst - Integ Test Support (applib)\n<size:10>[Container: packaging: jar]</size>" <<14>> as 14
  rectangle "==Apache Isis Tst - Integ Test Support (parent)\n<size:10>[Container: packaging: pom]</size>" <<13>> as 13
  rectangle "==Apache Isis Tst - Spec/Cucumber (applib)\n<size:10>[Container: packaging: jar]</size>" <<16>> as 16
  rectangle "==Apache Isis Tst - Spec/Cucumber (parent)\n<size:10>[Container: packaging: pom]</size>" <<15>> as 15
  rectangle "==Apache Isis Tst - Unit Test Support (applib)\n<size:10>[Container: packaging: jar]</size>" <<18>> as 18
  rectangle "==Apache Isis Tst - Unit Test Support (parent)\n<size:10>[Container: packaging: pom]</size>" <<17>> as 17
}
2 .[#707070].> 3 : ""
2 .[#707070].> 7 : ""
2 .[#707070].> 9 : ""
2 .[#707070].> 11 : ""
2 .[#707070].> 13 : ""
2 .[#707070].> 15 : ""
2 .[#707070].> 17 : ""
3 .[#707070].> 4 : ""
3 .[#707070].> 5 : ""
3 .[#707070].> 6 : ""
7 .[#707070].> 8 : ""
9 .[#707070].> 10 : ""
11 .[#707070].> 12 : ""
13 .[#707070].> 14 : ""
15 .[#707070].> 16 : ""
17 .[#707070].> 18 : ""
@enduml
----

.Projects/Modules (Testing)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.testing
|isis-testing
|pom
|\testing
|Apache Isis Testing
|A library of utilities, mini-frameworks and tools for prototyping and testing Apache Isis applications.



|org.apache.isis.testing
|isis-testing-fakedata
|pom
|\testing\fakedata
|Apache Isis Tst - FakeData (parent)
|A module providing a domain service to generate fake random data
        for use in unit tests or integration tests.



|org.apache.isis.testing
|isis-testing-fakedata-applib
|jar
|\testing\fakedata\applib
|Apache Isis Tst - FakeData (applib)
|_Components_

* org.apache.isis.testing.fakedata.applib.services.FakeDataService

_Dependencies_

* com.github.javafaker:javafaker:jar:<managed>
* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-unittestsupport-applib:jar:<managed>
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.testing
|isis-testing-fakedata-fixtures
|jar
|\testing\fakedata\fixtures
|Apache Isis Tst - FakeData (fixtures)
|_Dependencies_

* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-datanucleus5:jar:<managed>
* org.apache.isis.testing:isis-testing-fakedata-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:<managed>
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.testing
|isis-testing-fakedata-integtests
|jar
|\testing\fakedata\integtests
|Apache Isis Tst - FakeData (integ tests)
|_Dependencies_

* org.apache.isis.mavendeps:isis-mavendeps-integtests:pom:<managed>
* org.apache.isis.testing:isis-testing-fakedata-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-fakedata-fixtures:jar:<managed>



|org.apache.isis.testing
|isis-testing-fixtures
|pom
|\testing\fixtures
|Apache Isis Tst - Fixtures (parent)
|Library to initialize the system under test, either for integration testing or for prototyping.



|org.apache.isis.testing
|isis-testing-fixtures-applib
|jar
|\testing\fixtures\applib
|Apache Isis Tst - Fixtures (applib)
|_Components_

* org.apache.isis.testing.fixtures.applib.fixturescripts.ExecutionParametersService
* org.apache.isis.testing.fixtures.applib.modules.ModuleWithFixturesService
* org.apache.isis.testing.fixtures.applib.queryresultscache.QueryResultsCacheControlDefault
* org.apache.isis.testing.fixtures.applib.services.FixturesLifecycleService

_Dependencies_

* joda-time:joda-time:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-applib:jar:<managed>
* org.apache.isis.subdomains:isis-subdomains-spring-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-integtestsupport-applib:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>



|org.apache.isis.testing
|isis-testing-h2console
|pom
|\testing\h2console
|Apache Isis Tst - H2 Console (parent)
|Menu and configuration to open up H2 Console



|org.apache.isis.testing
|isis-testing-h2console-ui
|jar
|\testing\h2console\ui
|Apache Isis Tst - H2 Console (ui)
|_Components_

* org.apache.isis.testing.h2console.ui.webmodule.WebModuleH2Console

_Dependencies_

* com.h2database:h2:jar:<managed>
* org.apache.isis.core:isis-core-webapp:jar:<managed>



|org.apache.isis.testing
|isis-testing-hsqldbmgr
|pom
|\testing\hsqldbmgr
|Apache Isis Tst - HSQLDB Manager (parent)
|Menu and configuration to open up HSQLDB Manager



|org.apache.isis.testing
|isis-testing-hsqldbmgr-ui
|jar
|\testing\hsqldbmgr\ui
|Apache Isis Tst - HSQLDB Manager
|_Dependencies_

* org.apache.isis.core:isis-core-webapp:jar:<managed>
* org.hsqldb:hsqldb:jar:<managed>



|org.apache.isis.testing
|isis-testing-integtestsupport
|pom
|\testing\integtestsupport
|Apache Isis Tst - Integ Test Support (parent)
|Support for writing integ tests in JUnit 5; should be added as a dependency with scope=test only



|org.apache.isis.testing
|isis-testing-integtestsupport-applib
|jar
|\testing\integtestsupport\applib
|Apache Isis Tst - Integ Test Support (applib)
|_Components_

* org.apache.isis.testing.integtestsupport.applib.IsisIntegrationTestAbstract$InteractionSupport

_Dependencies_

* com.approvaltests:approvaltests:jar:<managed>
* com.h2database:h2:jar:<managed>
* org.apache.isis.core:isis-core-runtimeservices:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-datanucleus5:jar:<managed>
* org.apache.isis.security:isis-security-bypass:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>
* org.hamcrest:hamcrest-library:jar:<managed>
* org.hsqldb:hsqldb:jar:<managed>
* org.slf4j:slf4j-api:jar:${slf4j-api.version}
* org.springframework:spring-test:jar:<managed>
* org.springframework.boot:spring-boot-starter-test:jar:<managed>



|org.apache.isis.testing
|isis-testing-specsupport
|pom
|\testing\specsupport
|Apache Isis Tst - Spec/Cucumber (parent)
|Allows Cucumber to be used to write BDD-style specifications, generally as an alternative to integration tests.



|org.apache.isis.testing
|isis-testing-specsupport-applib
|jar
|\testing\specsupport\applib
|Apache Isis Tst - Spec/Cucumber (applib)
|_Dependencies_

* io.cucumber:cucumber-java:jar:<managed>
* io.cucumber:cucumber-junit:jar:<managed>
* io.cucumber:cucumber-junit-platform-engine:jar:<managed>
* io.cucumber:cucumber-spring:jar:<managed>
* org.apache.isis.testing:isis-testing-integtestsupport-applib:jar:<managed>
* org.junit.jupiter:junit-jupiter-api:jar:<managed>
* org.junit.platform:junit-platform-console:jar:<managed>



|org.apache.isis.testing
|isis-testing-unittestsupport
|pom
|\testing\unittestsupport
|Apache Isis Tst - Unit Test Support (parent)
|A module providing test utilities for unit testing of domain modules



|org.apache.isis.testing
|isis-testing-unittestsupport-applib
|jar
|\testing\unittestsupport\applib
|Apache Isis Tst - Unit Test Support (applib)
|_Dependencies_

* com.approvaltests:approvaltests:jar:<managed>
* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-codegen-bytebuddy:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>
* org.jmock:jmock:jar:<managed>
* org.jmock:jmock-junit4:jar:<managed>
* org.picocontainer:picocontainer:jar:<managed>
* org.slf4j:slf4j-api:jar:${slf4j-api.version}
* org.springframework:spring-test:jar:<managed>
* org.springframework.boot:spring-boot-starter-test:jar:<managed>


|===

== Regression Tests

[plantuml,Regression Tests,svg]
----
@startuml(id=Regression_Tests)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis - Regression Tests\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
  rectangle "==Apache Isis - Regression Tests (stable)\n<size:10>[Container: packaging: jar]</size>" <<3>> as 3
}
2 .[#707070].> 3 : ""
@enduml
----

.Projects/Modules (Regression Tests)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.regressiontests
|isis-regressiontests
|pom
|\regressiontests
|Apache Isis - Regression Tests
|Collection of JUnit tests covering core functionalities of the framework.
        (Targeted for JVM 11+)

_Dependencies_

* org.apache.directory.server:apacheds-test-framework:jar:2.0.0.AM26
* org.apache.isis.extensions:isis-extensions-modelannotation:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-encryption-jbcrypt:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-model:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-persistence-jdo:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-shiro-realm:jar:<managed>
* org.apache.isis.extensions:isis-extensions-shiro-realm-ldap-impl:jar:<managed>
* org.apache.isis.mappings:isis-mappings-restclient-applib:jar:<managed>
* org.apache.isis.mavendeps:isis-mavendeps-integtests:pom:<managed>
* org.apache.isis.mavendeps:isis-mavendeps-jdk11:pom:<managed>
* org.apache.isis.mavendeps:isis-mavendeps-webapp:pom:<managed>
* org.apache.isis.security:isis-security-shiro:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:<managed>
* org.apache.isis.viewer:isis-viewer-common:jar:<managed>
* org.eclipse.persistence:org.eclipse.persistence.moxy:jar:2.7.5
* org.glassfish:javax.json:jar:1.1.4
* org.glassfish.jersey.ext:jersey-spring5:jar:<managed>
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.regressiontests
|isis-regressiontests-stable
|jar
|\regressiontests\stable
|Apache Isis - Regression Tests (stable)
|_Components_

* org.apache.isis.testdomain.auditing.AuditerServiceForTesting
* org.apache.isis.testdomain.conf.Configuration_headless$HeadlessCommandSupport
* org.apache.isis.testdomain.publishing.PublisherServiceForTesting
* org.apache.isis.testdomain.util.kv.KVStoreForTesting
* org.apache.isis.testdomain.util.rest.RestEndpointService

_Dependencies_

* org.glassfish.jersey.ext:jersey-spring5:jar:<managed>


|===

== Extensions

[plantuml,Extensions,svg]
----
@startuml(id=Extensions)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<22>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<23>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<24>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<25>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<26>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<27>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<28>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<29>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<30>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<31>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<10>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<11>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<12>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<13>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<14>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<15>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<16>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<17>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<18>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<19>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<8>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<9>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<20>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<21>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Ext - @Model\n<size:10>[Container: packaging: jar]</size>" <<17>> as 17
  rectangle "==Apache Isis Ext - CORS (impl)\n<size:10>[Container: packaging: jar]</size>" <<9>> as 9
  rectangle "==Apache Isis Ext - CORS (parent)\n<size:10>[Container: packaging: pom]</size>" <<8>> as 8
  rectangle "==Apache Isis Ext - Command Log\n<size:10>[Container: packaging: pom]</size>" <<3>> as 3
  rectangle "==Apache Isis Ext - Command Log Implementation (JDO)\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Ext - Command Replay\n<size:10>[Container: packaging: pom]</size>" <<5>> as 5
  rectangle "==Apache Isis Ext - Command Replay for Primary\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Apache Isis Ext - Command Replay for Secondary\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
  rectangle "==Apache Isis Ext - Flyway\n<size:10>[Container: packaging: pom]</size>" <<12>> as 12
  rectangle "==Apache Isis Ext - Flyway Impl\n<size:10>[Container: packaging: jar]</size>" <<13>> as 13
  rectangle "==Apache Isis Ext - Quartz\n<size:10>[Container: packaging: pom]</size>" <<22>> as 22
  rectangle "==Apache Isis Ext - Quartz Impl\n<size:10>[Container: packaging: jar]</size>" <<23>> as 23
  rectangle "==Apache Isis Ext - Sec Man\n<size:10>[Container: packaging: pom]</size>" <<24>> as 24
  rectangle "==Apache Isis Ext - Sec Man API\n<size:10>[Container: packaging: jar]</size>" <<25>> as 25
  rectangle "==Apache Isis Ext - Sec Man Encryption (Using jbcrypt)\n<size:10>[Container: packaging: jar]</size>" <<26>> as 26
  rectangle "==Apache Isis Ext - Sec Man Model\n<size:10>[Container: packaging: jar]</size>" <<27>> as 27
  rectangle "==Apache Isis Ext - Sec Man Persistence (Using JDO)\n<size:10>[Container: packaging: jar]</size>" <<28>> as 28
  rectangle "==Apache Isis Ext - Sec Man Realm (Using Shiro)\n<size:10>[Container: packaging: jar]</size>" <<29>> as 29
  rectangle "==Apache Isis Ext - Security - Shiro LDAP Realm (impl)\n<size:10>[Container: packaging: jar]</size>" <<31>> as 31
  rectangle "==Apache Isis Ext - Security - Shiro LDAP Realm (parent)\n<size:10>[Container: packaging: pom]</size>" <<30>> as 30
  rectangle "==Apache Isis Ext - Wicket Viewer - Excel Download (parent)\n<size:10>[Container: packaging: pom]</size>" <<10>> as 10
  rectangle "==Apache Isis Ext - Wicket Viewer - Excel Download (ui)\n<size:10>[Container: packaging: jar]</size>" <<11>> as 11
  rectangle "==Apache Isis Ext - Wicket Viewer - fullcalendar (applib)\n<size:10>[Container: packaging: jar]</size>" <<15>> as 15
  rectangle "==Apache Isis Ext - Wicket Viewer - fullcalendar (parent)\n<size:10>[Container: packaging: pom]</size>" <<14>> as 14
  rectangle "==Apache Isis Ext - Wicket Viewer - fullcalendar (ui)\n<size:10>[Container: packaging: jar]</size>" <<16>> as 16
  rectangle "==Apache Isis Ext - Wicket Viewer - pdf.js (applib)\n<size:10>[Container: packaging: jar]</size>" <<19>> as 19
  rectangle "==Apache Isis Ext - Wicket Viewer - pdf.js (metamodel)\n<size:10>[Container: packaging: jar]</size>" <<20>> as 20
  rectangle "==Apache Isis Ext - Wicket Viewer - pdf.js (parent)\n<size:10>[Container: packaging: pom]</size>" <<18>> as 18
  rectangle "==Apache Isis Ext - Wicket Viewer - pdf.js (ui)\n<size:10>[Container: packaging: jar]</size>" <<21>> as 21
  rectangle "==Apache Isis Extensions\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
}
8 .[#707070].> 9 : ""
3 .[#707070].> 4 : ""
5 .[#707070].> 6 : ""
5 .[#707070].> 7 : ""
12 .[#707070].> 13 : ""
22 .[#707070].> 23 : ""
24 .[#707070].> 25 : ""
24 .[#707070].> 26 : ""
24 .[#707070].> 27 : ""
24 .[#707070].> 28 : ""
24 .[#707070].> 29 : ""
30 .[#707070].> 31 : ""
10 .[#707070].> 11 : ""
14 .[#707070].> 15 : ""
14 .[#707070].> 16 : ""
18 .[#707070].> 19 : ""
18 .[#707070].> 20 : ""
18 .[#707070].> 21 : ""
2 .[#707070].> 17 : ""
2 .[#707070].> 8 : ""
2 .[#707070].> 3 : ""
2 .[#707070].> 5 : ""
2 .[#707070].> 12 : ""
2 .[#707070].> 22 : ""
2 .[#707070].> 24 : ""
2 .[#707070].> 30 : ""
2 .[#707070].> 10 : ""
2 .[#707070].> 14 : ""
2 .[#707070].> 18 : ""
@enduml
----

.Projects/Modules (Extensions)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.extensions
|isis-extensions
|pom
|\extensions
|Apache Isis Extensions
|Extensions to the Apache Isis framework itself.
		These are _not_ intended to be called by the domain logic of an Apache Isis application (see instead org.apache.isis.platform).

_Dependencies_

* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-command-log
|pom
|\extensions\core\command-log
|Apache Isis Ext - Command Log
|Logs commands



|org.apache.isis.extensions
|isis-extensions-command-log-jdo
|jar
|\extensions\core\command-log\impl
|Apache Isis Ext - Command Log Implementation (JDO)
|_Components_

* org.apache.isis.extensions.commandlog.impl.CommandServiceListenerForJdo
* org.apache.isis.extensions.commandlog.impl.jdo.CommandJdo$TableColumnOrderDefault
* org.apache.isis.extensions.commandlog.impl.jdo.CommandJdo$TitleProvider
* org.apache.isis.extensions.commandlog.impl.jdo.CommandJdoRepository
* org.apache.isis.extensions.commandlog.impl.ui.CommandServiceMenu

_Dependencies_

* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-config:jar:<managed>
* org.apache.isis.core:isis-core-runtimeservices:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-command-replay
|pom
|\extensions\core\command-replay
|Apache Isis Ext - Command Replay
|Replays commands to secondary system



|org.apache.isis.extensions
|isis-extensions-command-replay-primary
|jar
|\extensions\core\command-replay\primary
|Apache Isis Ext - Command Replay for Primary
|A module for obtaining commands from a primary

_Components_

* org.apache.isis.extensions.commandreplay.primary.spiimpl.CaptureResultOfCommand

_Dependencies_

* org.apache.isis.core:isis-core-config:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.core:isis-schema:jar:<managed>
* org.apache.isis.extensions:isis-extensions-command-log-jdo:jar:<managed>
* org.apache.isis.mappings:isis-mappings-jaxrsclient-applib:jar:<managed>
* org.apache.isis.mappings:isis-mappings-jaxrsclient-impl:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-command-replay-secondary
|jar
|\extensions\core\command-replay\secondary
|Apache Isis Ext - Command Replay for Secondary
|A module providing a Quartz Job to run on a secondary system,
		for obtaining commands from a primary and saving them so that they are replayed.

_Components_

* org.apache.isis.extensions.commandreplay.secondary.analyser.CommandReplayAnalyserException
* org.apache.isis.extensions.commandreplay.secondary.analyser.CommandReplayAnalyserResult
* org.apache.isis.extensions.commandreplay.secondary.analysis.CommandReplayAnalysisService
* org.apache.isis.extensions.commandreplay.secondary.clock.TickingClockService
* org.apache.isis.extensions.commandreplay.secondary.config.SecondaryConfig
* org.apache.isis.extensions.commandreplay.secondary.executor.CommandExecutorServiceWithTime
* org.apache.isis.extensions.commandreplay.secondary.fetch.CommandFetcher

_Dependencies_

* org.apache.isis.core:isis-core-config:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.core:isis-schema:jar:<managed>
* org.apache.isis.extensions:isis-extensions-quartz-impl:jar:<managed>
* org.apache.isis.mappings:isis-mappings-jaxrsclient-applib:jar:<managed>
* org.apache.isis.mappings:isis-mappings-jaxrsclient-impl:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-cors
|pom
|\extensions\vro\cors
|Apache Isis Ext - CORS (parent)
|Implementation of CORS Filter (using ebay filter)



|org.apache.isis.extensions
|isis-extensions-cors-impl
|jar
|\extensions\vro\cors\impl
|Apache Isis Ext - CORS (impl)
|_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.core:isis-core-webapp:jar:<managed>
* org.springframework:spring-web:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-exceldownload
|pom
|\extensions\vw\exceldownload
|Apache Isis Ext - Wicket Viewer - Excel Download (parent)
|A component for Apache Isis' Wicket viewer, providing an alternative representation of collections to be downloaded as an Excel spreadsheet.



|org.apache.isis.extensions
|isis-extensions-exceldownload-ui
|jar
|\extensions\vw\exceldownload\ui
|Apache Isis Ext - Wicket Viewer - Excel Download (ui)
|_Components_

* org.apache.isis.extensions.viewer.wicket.exceldownload.ui.components.CollectionContentsAsExcelFactory

_Dependencies_

* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>
* org.apache.poi:poi-ooxml:jar:<managed>
* org.apache.poi:poi-ooxml-schemas:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-flyway
|pom
|\extensions\core\flyway
|Apache Isis Ext - Flyway
|Integrates Flyway when using any (relational) persistence store



|org.apache.isis.extensions
|isis-extensions-flyway-impl
|jar
|\extensions\core\flyway\impl
|Apache Isis Ext - Flyway Impl
|_Dependencies_

* org.apache.isis.core:isis-core-config:jar:<managed>
* org.flywaydb:flyway-core:jar:<managed>
* org.springframework:spring-context:jar:<managed>
* org.springframework:spring-jdbc:jar:<managed>
* org.springframework.boot:spring-boot-autoconfigure:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-fullcalendar
|pom
|\extensions\vw\fullcalendar
|Apache Isis Ext - Wicket Viewer - fullcalendar (parent)
|A component for Apache Isis' Wicket viewer, displaying collections of objects that have a date on a fullcalendar.io (javascript widget).



|org.apache.isis.extensions
|isis-extensions-fullcalendar-applib
|jar
|\extensions\vw\fullcalendar\applib
|Apache Isis Ext - Wicket Viewer - fullcalendar (applib)
|_Dependencies_

* de.agilecoders.wicket:wicket-bootstrap-core:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-fullcalendar-ui
|jar
|\extensions\vw\fullcalendar\ui
|Apache Isis Ext - Wicket Viewer - fullcalendar (ui)
|_Dependencies_

* net.ftlines.wicket-fullcalendar:wicket-fullcalendar-core:jar:<managed>
* org.apache.isis.extensions:isis-extensions-fullcalendar-applib:jar:<managed>
* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-modelannotation
|jar
|\extensions\core\model-annotation
|Apache Isis Ext - @Model
|Allows supporting methods to be annotated as @Model, to make explicit the bounds of the metamodel.

_Components_

* org.apache.isis.extensions.modelannotation.metamodel.services.IncubatorMetaModelPlugin

_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.core:isis-core-webapp:jar:<managed>
* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-pdfjs
|pom
|\extensions\vw\pdfjs
|Apache Isis Ext - Wicket Viewer - pdf.js (parent)
|A component for Apache Isis' Wicket viewer, allowing BLOBs containing PDFs to be rendered in a panel using pdf.js.



|org.apache.isis.extensions
|isis-extensions-pdfjs-applib
|jar
|\extensions\vw\pdfjs\applib
|Apache Isis Ext - Wicket Viewer - pdf.js (applib)
|_Dependencies_

* de.agilecoders.wicket:wicket-bootstrap-core:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-pdfjs-metamodel
|jar
|\extensions\vw\pdfjs\metamodel
|Apache Isis Ext - Wicket Viewer - pdf.js (metamodel)
|_Components_

* org.apache.isis.extensions.viewer.wicket.pdfjs.metamodel.facet.PdfJsViewerFacetFromAnnotationFactory$Register

_Dependencies_

* de.agilecoders.wicket:wicket-bootstrap-core:jar:<managed>
* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.extensions:isis-extensions-pdfjs-applib:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-pdfjs-ui
|jar
|\extensions\vw\pdfjs\ui
|Apache Isis Ext - Wicket Viewer - pdf.js (ui)
|_Components_

* org.apache.isis.extensions.viewer.wicket.pdfjs.ui.components.PdfJsViewerPanelComponentFactory

_Dependencies_

* org.apache.isis.extensions:isis-extensions-pdfjs-metamodel:jar:<managed>
* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-quartz
|pom
|\extensions\core\quartz
|Apache Isis Ext - Quartz
|Integrates Quartz



|org.apache.isis.extensions
|isis-extensions-quartz-impl
|jar
|\extensions\core\quartz\impl
|Apache Isis Ext - Quartz Impl
|_Dependencies_

* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-core-config:jar:<managed>
* org.apache.isis.core:isis-core-security:jar:<managed>
* org.apache.isis.extensions:isis-extensions-command-log-jdo:jar:<managed>
* org.springframework.boot:spring-boot-starter-quartz:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-secman
|pom
|\extensions\security\secman
|Apache Isis Ext - Sec Man
|_Dependencies_

* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.core:isis-core-security:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-secman-api
|jar
|\extensions\security\secman\api
|Apache Isis Ext - Sec Man API
|

|org.apache.isis.extensions
|isis-extensions-secman-encryption-jbcrypt
|jar
|\extensions\security\secman\encryption-jbcrypt
|Apache Isis Ext - Sec Man Encryption (Using jbcrypt)
|_Components_

* org.apache.isis.extensions.secman.encryption.jbcrypt.services.PasswordEncryptionServiceUsingJBcrypt

_Dependencies_

* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-api:jar:<managed>
* org.mindrot:jbcrypt:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-secman-model
|jar
|\extensions\security\secman\model
|Apache Isis Ext - Sec Man Model
|_Components_

* org.apache.isis.extensions.secman.model.facets.TenantedAuthorizationFacetFactory$Register

_Dependencies_

* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-api:jar:2.0.0-SNAPSHOT



|org.apache.isis.extensions
|isis-extensions-secman-persistence-jdo
|jar
|\extensions\security\secman\persistence-jdo
|Apache Isis Ext - Sec Man Persistence (Using JDO)
|_Components_

* org.apache.isis.extensions.secman.jdo.dom.permission.ApplicationPermissionRepository
* org.apache.isis.extensions.secman.jdo.dom.role.ApplicationRoleRepository
* org.apache.isis.extensions.secman.jdo.dom.tenancy.ApplicationTenancyRepository
* org.apache.isis.extensions.secman.jdo.dom.user.ApplicationUserRepository
* org.apache.isis.extensions.secman.jdo.seed.SeedSecurityModuleService

_Dependencies_

* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-api:jar:2.0.0-SNAPSHOT
* org.apache.isis.extensions:isis-extensions-secman-model:jar:2.0.0-SNAPSHOT
* org.apache.isis.persistence:isis-persistence-jdo-datanucleus5:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:2.0.0-SNAPSHOT



|org.apache.isis.extensions
|isis-extensions-secman-shiro-realm
|jar
|\extensions\security\secman\shiro-realm
|Apache Isis Ext - Sec Man Realm (Using Shiro)
|_Components_

* org.apache.isis.extensions.secman.shiro.services.SecurityRealmServiceUsingShiro

_Dependencies_

* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-api:jar:2.0.0-SNAPSHOT
* org.apache.isis.security:isis-security-shiro:jar:<managed>



|org.apache.isis.extensions
|isis-extensions-shiro-realm-ldap
|pom
|\extensions\security\shiro-realm-ldap
|Apache Isis Ext - Security - Shiro LDAP Realm (parent)
|Implementation of Shiro Realm using LDAP.



|org.apache.isis.extensions
|isis-extensions-shiro-realm-ldap-impl
|jar
|\extensions\security\shiro-realm-ldap\impl
|Apache Isis Ext - Security - Shiro LDAP Realm (impl)
|_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.security:isis-security-shiro:jar:<managed>


|===

== Subdomains

[plantuml,Subdomains,svg]
----
@startuml(id=Subdomains)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<22>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<11>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<12>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<23>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<13>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<14>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<15>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<16>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<17>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<18>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<19>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<8>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<9>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<20>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<10>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<21>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Sub - Base (applib)\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Sub - Base (parent)\n<size:10>[Container: packaging: pom]</size>" <<3>> as 3
  rectangle "==Apache Isis Sub - Docx (applib)\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Apache Isis Sub - Docx (parent)\n<size:10>[Container: packaging: pom]</size>" <<5>> as 5
  rectangle "==Apache Isis Sub - Excel (Fixtures)\n<size:10>[Container: packaging: jar]</size>" <<9>> as 9
  rectangle "==Apache Isis Sub - Excel (Integ Tests)\n<size:10>[Container: packaging: jar]</size>" <<10>> as 10
  rectangle "==Apache Isis Sub - Excel (applib)\n<size:10>[Container: packaging: jar]</size>" <<8>> as 8
  rectangle "==Apache Isis Sub - Excel (parent)\n<size:10>[Container: packaging: pom]</size>" <<7>> as 7
  rectangle "==Apache Isis Sub - Excel (testing support)\n<size:10>[Container: packaging: jar]</size>" <<11>> as 11
  rectangle "==Apache Isis Sub - Freemarker (applib)\n<size:10>[Container: packaging: jar]</size>" <<13>> as 13
  rectangle "==Apache Isis Sub - Freemarker (parent)\n<size:10>[Container: packaging: pom]</size>" <<12>> as 12
  rectangle "==Apache Isis Sub - Ognl (applib)\n<size:10>[Container: packaging: jar]</size>" <<15>> as 15
  rectangle "==Apache Isis Sub - Ognl (parent)\n<size:10>[Container: packaging: pom]</size>" <<14>> as 14
  rectangle "==Apache Isis Sub - PDF Box (applib)\n<size:10>[Container: packaging: jar]</size>" <<17>> as 17
  rectangle "==Apache Isis Sub - PDF Box (parent)\n<size:10>[Container: packaging: pom]</size>" <<16>> as 16
  rectangle "==Apache Isis Sub - Spring (applib)\n<size:10>[Container: packaging: jar]</size>" <<19>> as 19
  rectangle "==Apache Isis Sub - Spring (parent)\n<size:10>[Container: packaging: pom]</size>" <<18>> as 18
  rectangle "==Apache Isis Sub - XdocReport (applib)\n<size:10>[Container: packaging: jar]</size>" <<21>> as 21
  rectangle "==Apache Isis Sub - XdocReport (parent)\n<size:10>[Container: packaging: pom]</size>" <<20>> as 20
  rectangle "==Apache Isis Sub - Zip (applib)\n<size:10>[Container: packaging: jar]</size>" <<23>> as 23
  rectangle "==Apache Isis Sub - Zip (parent)\n<size:10>[Container: packaging: pom]</size>" <<22>> as 22
  rectangle "==Apache Isis Subdomains\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
}
3 .[#707070].> 4 : ""
5 .[#707070].> 6 : ""
7 .[#707070].> 9 : ""
7 .[#707070].> 10 : ""
7 .[#707070].> 8 : ""
7 .[#707070].> 11 : ""
12 .[#707070].> 13 : ""
14 .[#707070].> 15 : ""
16 .[#707070].> 17 : ""
18 .[#707070].> 19 : ""
20 .[#707070].> 21 : ""
22 .[#707070].> 23 : ""
2 .[#707070].> 3 : ""
2 .[#707070].> 5 : ""
2 .[#707070].> 7 : ""
2 .[#707070].> 12 : ""
2 .[#707070].> 14 : ""
2 .[#707070].> 16 : ""
2 .[#707070].> 18 : ""
2 .[#707070].> 20 : ""
2 .[#707070].> 22 : ""
@enduml
----

.Projects/Modules (Subdomains)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.subdomains
|isis-subdomains
|pom
|\subdomains
|Apache Isis Subdomains
|A library of domain services and of supporting subdomains (often technical in nature), to be called from the
		core domain of an Apache Isis applications.

_Dependencies_

* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-base
|pom
|\subdomains\base
|Apache Isis Sub - Base (parent)
|A module providing Base utilities for other subdomain modules



|org.apache.isis.subdomains
|isis-subdomains-base-applib
|jar
|\subdomains\base\applib
|Apache Isis Sub - Base (applib)
|_Components_

* org.apache.isis.subdomains.base.applib.services.calendar.CalendarService

_Dependencies_

* com.google.guava:guava:jar:<managed>
* org.apache.commons:commons-lang3:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.testing:isis-testing-unittestsupport-applib:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>
* org.reflections:reflections:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-docx
|pom
|\subdomains\docx
|Apache Isis Sub - Docx (parent)
|Uses the Apache POI library for mail merge functions of .docx Word documents



|org.apache.isis.subdomains
|isis-subdomains-docx-applib
|jar
|\subdomains\docx\applib
|Apache Isis Sub - Docx (applib)
|_Dependencies_

* org.apache.isis.core:isis-applib:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-excel
|pom
|\subdomains\excel
|Apache Isis Sub - Excel (parent)
|A domain service for Apache Isis', allowing collections
        of (view model) objects to be exported/imported to/from an
        Excel spreadsheet.  Also support for excel-based fixtures.



|org.apache.isis.subdomains
|isis-subdomains-excel-applib
|jar
|\subdomains\excel\applib
|Apache Isis Sub - Excel (applib)
|_Components_

* org.apache.isis.subdomains.excel.applib.dom.ExcelService

_Dependencies_

* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:<managed>
* org.apache.poi:poi-ooxml:jar:<managed>
* org.apache.poi:poi-ooxml-schemas:jar:<managed>
* org.datanucleus:datanucleus-core:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-excel-fixtures
|jar
|\subdomains\excel\fixture
|Apache Isis Sub - Excel (Fixtures)
|_Dependencies_

* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-datanucleus5:jar:<managed>
* org.apache.isis.subdomains:isis-subdomains-excel-applib:jar:<managed>
* org.apache.isis.subdomains:isis-subdomains-excel-testing:jar:<managed>
* org.apache.isis.testing:isis-testing-fixtures-applib:jar:<managed>
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-excel-integtests
|jar
|\subdomains\excel\integtests
|Apache Isis Sub - Excel (Integ Tests)
|_Dependencies_

* org.apache.isis.mavendeps:isis-mavendeps-integtests:pom:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-datanucleus5:jar:<managed>
* org.apache.isis.subdomains:isis-subdomains-excel-fixtures:jar:<managed>
* org.apache.isis.testing:isis-testing-fakedata-applib:jar:<managed>
* org.hsqldb:hsqldb:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-excel-testing
|jar
|\subdomains\excel\testing
|Apache Isis Sub - Excel (testing support)
|_Dependencies_

* org.apache.isis.subdomains:isis-subdomains-excel-applib:jar:<managed>
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-freemarker
|pom
|\subdomains\freemarker
|Apache Isis Sub - Freemarker (parent)
|Integrates Freemarker Library



|org.apache.isis.subdomains
|isis-subdomains-freemarker-applib
|jar
|\subdomains\freemarker\applib
|Apache Isis Sub - Freemarker (applib)
|_Dependencies_

* org.apache.isis.core:isis-applib:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-ognl
|pom
|\subdomains\ognl
|Apache Isis Sub - Ognl (parent)
|Integrates Ognl Library



|org.apache.isis.subdomains
|isis-subdomains-ognl-applib
|jar
|\subdomains\ognl\applib
|Apache Isis Sub - Ognl (applib)
|_Dependencies_

* org.apache.isis.core:isis-applib:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-pdfbox
|pom
|\subdomains\pdfbox
|Apache Isis Sub - PDF Box (parent)
|Integrates PDF Box Library



|org.apache.isis.subdomains
|isis-subdomains-pdfbox-applib
|jar
|\subdomains\pdfbox\applib
|Apache Isis Sub - PDF Box (applib)
|Integrates PDF Box Library

_Dependencies_

* org.apache.isis.core:isis-applib:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-spring
|pom
|\subdomains\spring
|Apache Isis Sub - Spring (parent)
|Utility services for interacting with the Spring application context (that hosts the Apache Isis application itself)



|org.apache.isis.subdomains
|isis-subdomains-spring-applib
|jar
|\subdomains\spring\applib
|Apache Isis Sub - Spring (applib)
|_Components_

* org.apache.isis.subdomains.spring.applib.service.SpringBeansService

_Dependencies_

* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-xdocreport
|pom
|\subdomains\xdocreport
|Apache Isis Sub - XdocReport (parent)
|Integrates XDoc Report Library



|org.apache.isis.subdomains
|isis-subdomains-xdocreport-applib
|jar
|\subdomains\xdocreport\applib
|Apache Isis Sub - XdocReport (applib)
|_Components_

* org.apache.isis.subdomains.xdocreport.applib.service.XDocReportService

_Dependencies_

* com.google.guava:guava:jar:<managed>
* fr.opensagres.xdocreport:fr.opensagres.xdocreport.converter.docx.xwpf:jar:<managed>
* fr.opensagres.xdocreport:fr.opensagres.xdocreport.document.docx:jar:<managed>
* fr.opensagres.xdocreport:fr.opensagres.xdocreport.template.freemarker:jar:<managed>
* fr.opensagres.xdocreport:org.apache.poi.xwpf.converter.core:jar:<managed>
* fr.opensagres.xdocreport:org.apache.poi.xwpf.converter.pdf:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.testing:isis-testing-unittestsupport-applib:jar:<managed>
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.subdomains
|isis-subdomains-zip
|pom
|\subdomains\zip
|Apache Isis Sub - Zip (parent)
|A domain service for Apache Isis', for zipping utilities.



|org.apache.isis.subdomains
|isis-subdomains-zip-applib
|jar
|\subdomains\zip\applib
|Apache Isis Sub - Zip (applib)
|_Components_

* org.apache.isis.extensions.zip.dom.impl.ZipService

_Dependencies_

* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.projectlombok:lombok:jar:<managed>


|===

== Tooling

[plantuml,Tooling,svg]
----
@startuml(id=Tooling)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis - Tooling\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
  rectangle "==Apache Isis Tooling - C4 Modeling\n<size:10>[Container: packaging: jar]</size>" <<3>> as 3
  rectangle "==Apache Isis Tooling - CLI (Command Line Interface)\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Tooling - Java Model (Code Mining)\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
  rectangle "==Apache Isis Tooling - Model for AsciiDoc\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Apache Isis Tooling - Project Model (Code mining)\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
}
2 .[#707070].> 3 : ""
2 .[#707070].> 4 : ""
2 .[#707070].> 5 : ""
2 .[#707070].> 6 : ""
2 .[#707070].> 7 : ""
@enduml
----

.Projects/Modules (Tooling)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.tooling
|isis-tooling
|pom
|\tooling
|Apache Isis - Tooling
|Libraries and tools not depending on the _Apache Isis Core_ ecosystem, 
        eg. code mining, automated documentation.
        (Targeted for JVM 11+)

_Dependencies_

* com.google.code.findbugs:annotations:jar:3.0.1u2
* org.junit.jupiter:junit-jupiter-api:jar:<managed>
* org.junit.jupiter:junit-jupiter-engine:jar:<managed>
* org.junit.vintage:junit-vintage-engine:jar:<managed>
* org.mapstruct:mapstruct-processor:jar:1.3.1.Final
* org.projectlombok:lombok:jar:<managed>
* org.slf4j:slf4j-api:jar:<managed>
* org.springframework.boot:spring-boot-starter-log4j2:jar:<managed>



|org.apache.isis.tooling
|isis-tooling-c4modeling
|jar
|\tooling\c4modeling
|Apache Isis Tooling - C4 Modeling
|Library for programmatic C4 Model generation. 
        
        See https://c4model.com/

_Dependencies_

* com.structurizr:structurizr-core:jar:<managed>
* com.structurizr:structurizr-plantuml:jar:<managed>
* org.apache.isis.commons:isis-commons:jar:<managed>



|org.apache.isis.tooling
|isis-tooling-cli
|jar
|\tooling\cli
|Apache Isis Tooling - CLI (Command Line Interface)
|Command Line Interface for the _Apache Isis Tooling_ ecosystem.

_Dependencies_

* info.picocli:picocli:jar:<managed>
* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.tooling:isis-tooling-c4modeling:jar:<managed>
* org.apache.isis.tooling:isis-tooling-javamodel:jar:<managed>
* org.apache.isis.tooling:isis-tooling-model4adoc:jar:<managed>
* org.apache.isis.tooling:isis-tooling-projectmodel:jar:<managed>



|org.apache.isis.tooling
|isis-tooling-javamodel
|jar
|\tooling\javamodel
|Apache Isis Tooling - Java Model (Code Mining)
|Code mining library for Java bytecode introspection.

_Dependencies_

* guru.nidi:code-assert:jar:${code-assert.version}
* org.apache.isis.commons:isis-commons:jar:<managed>



|org.apache.isis.tooling
|isis-tooling-model4adoc
|jar
|\tooling\model4adoc
|Apache Isis Tooling - Model for AsciiDoc
|Library for programmatic AsciiDoc generation. 
        
        The AsciiDoc name is trademarked by the Eclipse Foundation (https://www.eclipse.org/).
		This project is *not* part of the specification effort for _AsciiDoc_ under the 
		AsciiDoc Working Group. See https://projects.eclipse.org/proposals/asciidoc-language
		and https://accounts.eclipse.org/mailing-list/asciidoc-wg. However, we are happy to 
		help with transfer of source code, if any project (under the umbrella of the 
		AsciiDoc Working Group) is willing to take over.

_Dependencies_

* org.apache.isis.commons:isis-commons:jar:<managed>
* org.asciidoctor:asciidoctorj:jar:<managed>



|org.apache.isis.tooling
|isis-tooling-projectmodel
|jar
|\tooling\projectmodel
|Apache Isis Tooling - Project Model (Code mining)
|Code mining library for Gradle/Maven project module tree introspection.

_Dependencies_

* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.maven:maven-model-builder:jar:<managed>
* org.gradle:gradle-tooling-api:jar:<managed>


|===

== Examples

[plantuml,Examples,svg]
----
@startuml(id=Examples)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Demo - Domain\n<size:10>[Container: packaging: jar]</size>" <<3>> as 3
  rectangle "==Demo - JavaFX\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Demo - Parent\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
  rectangle "==Demo - Vaadin\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
  rectangle "==Demo - Web\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Demo - Wicket\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
}
2 .[#707070].> 3 : ""
2 .[#707070].> 4 : ""
2 .[#707070].> 5 : ""
2 .[#707070].> 6 : ""
2 .[#707070].> 7 : ""
@enduml
----

.Projects/Modules (Examples)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.examples.apps
|demo-parent
|pom
|\examples\demo
|Demo - Parent
|_Dependencies_

* com.h2database:h2:jar:<managed>
* org.apache.isis.extensions:isis-extensions-exceldownload-ui:jar:<managed>
* org.apache.isis.extensions:isis-extensions-modelannotation:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-encryption-jbcrypt:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-model:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-persistence-jdo:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-shiro-realm:jar:<managed>
* org.apache.isis.mavendeps:isis-mavendeps-jdk11:pom:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-persistence-jdo-dn5:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-markdown-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-markdown-persistence-jdo-dn5:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-sse-applib:jar:<managed>
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.examples.apps
|demo-domain
|jar
|\examples\demo\domain
|Demo - Domain
|_Components_

* demoapp.dom._infra.DefaultTitleProvider
* demoapp.dom._infra.LibraryPreloadingService
* demoapp.dom._infra.fixtures.DemoFixtureScriptSpecificationProvider
* demoapp.dom._infra.resources.AsciiDocConverterService
* demoapp.dom._infra.resources.AsciiDocReaderService
* demoapp.dom._infra.resources.MarkdownReaderService
* demoapp.dom._infra.resources.MarkupReaderService
* demoapp.dom._infra.resources.MarkupVariableResolverService
* demoapp.dom._infra.resources.ResourceReaderService
* demoapp.dom._infra.samples.NameSamples
* demoapp.dom._infra.urlencoding.UrlEncodingServiceNaiveInMemory
* demoapp.dom.annotDomain.Action.command.ActionCommandJdoEntities
* demoapp.dom.annotDomain.Action.command.ActionCommandJdoSeedService
* demoapp.dom.annotDomain.Action.publishing.ActionPublishingJdoEntities
* demoapp.dom.annotDomain.Action.publishing.ActionPublishingJdoSeedService
* demoapp.dom.annotDomain.DomainObject.publishing.annotated.disabled.DomainObjectPublishingDisabledJdoEntities
* demoapp.dom.annotDomain.DomainObject.publishing.annotated.disabled.DomainObjectPublishingDisabledJdoSeedService
* demoapp.dom.annotDomain.DomainObject.publishing.annotated.enabled.DomainObjectPublishingEnabledJdoEntities
* demoapp.dom.annotDomain.DomainObject.publishing.annotated.enabled.DomainObjectPublishingEnabledJdoSeedService
* demoapp.dom.annotDomain.DomainObject.publishing.metaAnnot.enabled.DomainObjectPublishingEnabledMetaAnnotatedJdoEntities
* demoapp.dom.annotDomain.DomainObject.publishing.metaAnnot.enabled.DomainObjectPublishingEnabledMetaAnnotatedJdoSeedService
* demoapp.dom.annotDomain.DomainObject.publishing.metaAnnotOverridden.enabled.DomainObjectPublishingEnabledMetaAnnotOverriddenJdoEntities
* demoapp.dom.annotDomain.DomainObject.publishing.metaAnnotOverridden.enabled.DomainObjectPublishingEnabledMetaAnnotOverriddenJdoSeedService
* demoapp.dom.annotDomain.Property.command.PropertyCommandJdoEntities
* demoapp.dom.annotDomain.Property.command.PropertyCommandJdoSeedService
* demoapp.dom.annotDomain.Property.publishing.PropertyPublishingJdoEntities
* demoapp.dom.annotDomain.Property.publishing.PropertyPublishingJdoSeedService
* demoapp.dom.annotDomain._changes.PublisherServiceToCaptureChangesInMemory
* demoapp.dom.annotDomain._commands.ExposePersistedCommands$TableColumnOrderDefault
* demoapp.dom.annotDomain._interactions.PublisherServiceToCaptureInteractionsInMemory
* demoapp.dom.annotLayout.PropertyLayout.navigable.FileTreeNodeService
* demoapp.dom.annotLayout.PropertyLayout.repainting.PdfJsViewerAdvisorFallback
* demoapp.dom.error.service.DemoErrorReportingService
* demoapp.dom.events.DemoEventSubscriber
* demoapp.dom.events.EventLogRepository
* demoapp.dom.extensions.secman.apptenancy.ApplicationTenancyEvaluatorForDemo
* demoapp.dom.extensions.secman.apptenancy.entities.TenantedJdoEntities
* demoapp.dom.extensions.secman.apptenancy.entities.seed.TenantedJdoSeedService
* demoapp.dom.jee.DemoRequestScopedBean
* demoapp.dom.jee.JeeDemoService
* demoapp.dom.services.wrapperFactory.WrapperFactoryJdoEntities
* demoapp.dom.services.wrapperFactory.WrapperFactoryJdoSeedService
* demoapp.dom.types.isis.blobs.jdo.IsisBlobJdoEntities
* demoapp.dom.types.isis.blobs.jdo.IsisBlobJdoSeedService
* demoapp.dom.types.isis.blobs.samples.IsisBlobsSamples
* demoapp.dom.types.isis.clobs.jdo.IsisClobJdoEntities
* demoapp.dom.types.isis.clobs.jdo.IsisClobJdoSeedService
* demoapp.dom.types.isis.clobs.samples.IsisClobsSamples
* demoapp.dom.types.isis.images.jdo.IsisImageJdoEntities
* demoapp.dom.types.isis.images.jdo.IsisImageJdoSeedService
* demoapp.dom.types.isis.images.samples.IsisImagesSamples
* demoapp.dom.types.isis.localresourcepaths.jdo.IsisLocalResourcePathJdoEntities
* demoapp.dom.types.isis.localresourcepaths.jdo.IsisLocalResourcePathJdoSeedService
* demoapp.dom.types.isis.localresourcepaths.samples.IsisLocalResourcePathsSamples
* demoapp.dom.types.isis.markups.jdo.IsisMarkupJdoEntities
* demoapp.dom.types.isis.markups.jdo.IsisMarkupJdoSeedService
* demoapp.dom.types.isis.markups.samples.IsisMarkupSamples
* demoapp.dom.types.isis.passwords.jdo.IsisPasswordJdoEntities
* demoapp.dom.types.isis.passwords.jdo.IsisPasswordJdoSeedService
* demoapp.dom.types.isis.passwords.samples.IsisPasswordsSamples
* demoapp.dom.types.isisext.asciidocs.jdo.IsisAsciiDocJdoEntities
* demoapp.dom.types.isisext.asciidocs.jdo.IsisAsciiDocJdoSeedService
* demoapp.dom.types.isisext.asciidocs.samples.IsisAsciiDocSamples
* demoapp.dom.types.isisext.markdowns.jdo.IsisMarkdownJdoEntities
* demoapp.dom.types.isisext.markdowns.jdo.IsisMarkdownJdoSeedService
* demoapp.dom.types.isisext.markdowns.samples.IsisMarkdownSamples
* demoapp.dom.types.javaawt.images.jdo.JavaAwtImageJdoEntities
* demoapp.dom.types.javaawt.images.jdo.JavaAwtImageJdoSeedService
* demoapp.dom.types.javaawt.images.samples.JavaAwtImageService
* demoapp.dom.types.javaawt.images.samples.JavaAwtImagesSamples
* demoapp.dom.types.javalang.booleans.jdo.WrapperBooleanJdoEntities
* demoapp.dom.types.javalang.booleans.jdo.WrapperBooleanJdoSeedService
* demoapp.dom.types.javalang.booleans.samples.WrapperBooleanSamples
* demoapp.dom.types.javalang.bytes.jdo.WrapperByteJdoEntities
* demoapp.dom.types.javalang.bytes.jdo.WrapperByteJdoSeedService
* demoapp.dom.types.javalang.bytes.samples.WrapperByteSamples
* demoapp.dom.types.javalang.characters.jdo.WrapperCharacterJdoEntities
* demoapp.dom.types.javalang.characters.jdo.WrapperCharacterJdoSeedService
* demoapp.dom.types.javalang.characters.samples.WrapperCharacterSamples
* demoapp.dom.types.javalang.doubles.jdo.WrapperDoubleJdoEntities
* demoapp.dom.types.javalang.doubles.jdo.WrapperDoubleJdoSeedService
* demoapp.dom.types.javalang.doubles.samples.WrapperDoubleSamples
* demoapp.dom.types.javalang.floats.jdo.WrapperFloatJdoEntities
* demoapp.dom.types.javalang.floats.jdo.WrapperFloatJdoSeedService
* demoapp.dom.types.javalang.floats.samples.WrapperFloatSamples
* demoapp.dom.types.javalang.integers.jdo.WrapperIntegerJdoEntities
* demoapp.dom.types.javalang.integers.jdo.WrapperIntegerJdoSeedService
* demoapp.dom.types.javalang.integers.samples.WrapperIntegerSamples
* demoapp.dom.types.javalang.longs.jdo.WrapperLongJdoEntities
* demoapp.dom.types.javalang.longs.jdo.WrapperLongJdoSeedService
* demoapp.dom.types.javalang.longs.samples.WrapperLongSamples
* demoapp.dom.types.javalang.shorts.jdo.WrapperShortJdoEntities
* demoapp.dom.types.javalang.shorts.jdo.WrapperShortJdoSeedService
* demoapp.dom.types.javalang.shorts.samples.WrapperShortSamples
* demoapp.dom.types.javalang.strings.jdo.JavaLangStringJdoEntities
* demoapp.dom.types.javalang.strings.jdo.JavaLangStringJdoSeedService
* demoapp.dom.types.javalang.strings.samples.JavaLangStringSamples
* demoapp.dom.types.javamath.bigdecimals.jdo.JavaMathBigDecimalJdoEntities
* demoapp.dom.types.javamath.bigdecimals.jdo.JavaMathBigDecimalJdoSeedService
* demoapp.dom.types.javamath.bigdecimals.samples.JavaMathBigDecimalSamples
* demoapp.dom.types.javamath.bigintegers.jdo.JavaMathBigIntegerJdoEntities
* demoapp.dom.types.javamath.bigintegers.jdo.JavaMathBigIntegerJdoSeedService
* demoapp.dom.types.javamath.bigintegers.samples.JavaMathBigIntegerSamples
* demoapp.dom.types.javanet.urls.jdo.JavaNetUrlJdoEntities
* demoapp.dom.types.javanet.urls.jdo.JavaNetUrlJdoSeedService
* demoapp.dom.types.javanet.urls.samples.JavaNetUrlSamples
* demoapp.dom.types.javasql.javasqldate.jdo.JavaSqlDateJdoEntities
* demoapp.dom.types.javasql.javasqldate.jdo.JavaSqlDateJdoSeedService
* demoapp.dom.types.javasql.javasqldate.samples.JavaSqlDateSamples
* demoapp.dom.types.javasql.javasqltimestamp.jdo.JavaSqlTimestampJdoEntities
* demoapp.dom.types.javasql.javasqltimestamp.jdo.JavaSqlTimestampJdoSeedService
* demoapp.dom.types.javasql.javasqltimestamp.samples.JavaSqlTimestampSamples
* demoapp.dom.types.javatime.javatimelocaldate.jdo.JavaTimeLocalDateJdoEntities
* demoapp.dom.types.javatime.javatimelocaldate.jdo.JavaTimeLocalDateJdoSeedService
* demoapp.dom.types.javatime.javatimelocaldate.samples.JavaTimeLocalDateSamples
* demoapp.dom.types.javatime.javatimelocaldatetime.jdo.JavaTimeLocalDateTimeJdoEntities
* demoapp.dom.types.javatime.javatimelocaldatetime.jdo.JavaTimeLocalDateTimeJdoSeedService
* demoapp.dom.types.javatime.javatimelocaldatetime.samples.JavaTimeLocalDateTimeSamples
* demoapp.dom.types.javatime.javatimeoffsetdatetime.jdo.JavaTimeOffsetDateTimeJdoEntities
* demoapp.dom.types.javatime.javatimeoffsetdatetime.jdo.JavaTimeOffsetDateTimeJdoSeedService
* demoapp.dom.types.javatime.javatimeoffsetdatetime.samples.JavaTimeOffsetDateTimeSamples
* demoapp.dom.types.javatime.javatimeoffsettime.jdo.JavaTimeOffsetTimeJdoEntities
* demoapp.dom.types.javatime.javatimeoffsettime.jdo.JavaTimeOffsetTimeJdoSeedService
* demoapp.dom.types.javatime.javatimeoffsettime.samples.JavaTimeOffsetTimeSamples
* demoapp.dom.types.javatime.javatimezoneddatetime.jdo.JavaTimeZonedDateTimeJdoEntities
* demoapp.dom.types.javatime.javatimezoneddatetime.jdo.JavaTimeZonedDateTimeJdoSeedService
* demoapp.dom.types.javatime.javatimezoneddatetime.samples.JavaTimeZonedDateTimeSamples
* demoapp.dom.types.javautil.javautildate.jdo.JavaUtilDateJdoEntities
* demoapp.dom.types.javautil.javautildate.jdo.JavaUtilDateJdoSeedService
* demoapp.dom.types.javautil.javautildate.samples.JavaUtilDateSamples
* demoapp.dom.types.javautil.uuids.jdo.JavaUtilUuidJdoEntities
* demoapp.dom.types.javautil.uuids.jdo.JavaUtilUuidJdoSeedService
* demoapp.dom.types.javautil.uuids.samples.JavaUtilUuidSamples
* demoapp.dom.types.jodatime.jodadatetime.jdo.JodaDateTimeJdoEntities
* demoapp.dom.types.jodatime.jodadatetime.jdo.JodaDateTimeJdoSeedService
* demoapp.dom.types.jodatime.jodadatetime.samples.JodaDateTimeSamples
* demoapp.dom.types.jodatime.jodalocaldate.jdo.JodaLocalDateJdoEntities
* demoapp.dom.types.jodatime.jodalocaldate.jdo.JodaLocalDateJdoSeedService
* demoapp.dom.types.jodatime.jodalocaldate.samples.JodaLocalDateSamples
* demoapp.dom.types.jodatime.jodalocaldatetime.jdo.JodaLocalDateTimeJdoEntities
* demoapp.dom.types.jodatime.jodalocaldatetime.jdo.JodaLocalDateTimeJdoSeedService
* demoapp.dom.types.jodatime.jodalocaldatetime.samples.JodaLocalDateTimeSamples
* demoapp.dom.types.primitive.booleans.jdo.PrimitiveBooleanJdoEntities
* demoapp.dom.types.primitive.booleans.jdo.PrimitiveBooleanJdoSeedService
* demoapp.dom.types.primitive.bytes.jdo.PrimitiveByteJdoEntities
* demoapp.dom.types.primitive.bytes.jdo.PrimitiveByteJdoSeedService
* demoapp.dom.types.primitive.chars.jdo.PrimitiveCharJdoEntities
* demoapp.dom.types.primitive.chars.jdo.PrimitiveCharJdoSeedService
* demoapp.dom.types.primitive.doubles.jdo.PrimitiveDoubleJdoEntities
* demoapp.dom.types.primitive.doubles.jdo.PrimitiveDoubleJdoSeedService
* demoapp.dom.types.primitive.floats.jdo.PrimitiveFloatJdoEntities
* demoapp.dom.types.primitive.floats.jdo.PrimitiveFloatJdoSeedService
* demoapp.dom.types.primitive.ints.jdo.PrimitiveIntJdoEntities
* demoapp.dom.types.primitive.ints.jdo.PrimitiveIntJdoSeedService
* demoapp.dom.types.primitive.longs.jdo.PrimitiveLongJdoEntities
* demoapp.dom.types.primitive.longs.jdo.PrimitiveLongJdoSeedService
* demoapp.dom.types.primitive.shorts.jdo.PrimitiveShortJdoEntities
* demoapp.dom.types.primitive.shorts.jdo.PrimitiveShortJdoSeedService
* demoapp.dom.types.tuple.NumberConstantRepository
* demoapp.dom.viewmodels.jaxbrefentity.ChildJdoEntities
* demoapp.dom.viewmodels.jaxbrefentity.seed.ChildJdoSeedService

_Dependencies_

* com.h2database:h2:jar:<managed>
* org.apache.isis.extensions:isis-extensions-command-log-jdo:jar:<managed>
* org.apache.isis.extensions:isis-extensions-exceldownload-ui:jar:<managed>
* org.apache.isis.extensions:isis-extensions-modelannotation:jar:<managed>
* org.apache.isis.extensions:isis-extensions-pdfjs-applib:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-encryption-jbcrypt:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-model:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-persistence-jdo:jar:<managed>
* org.apache.isis.extensions:isis-extensions-secman-shiro-realm:jar:<managed>
* org.apache.isis.testing:isis-testing-h2console-ui:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-markdown-applib:jar:<managed>
* org.assertj:assertj-core:jar:3.16.1
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.examples.apps
|demo-javafx
|jar
|\examples\demo\javafx
|Demo - JavaFX
|_Dependencies_

* org.apache.isis.core:isis-core-runtimeservices:jar:<managed>
* org.apache.isis.core:isis-core-security:jar:<managed>
* org.apache.isis.examples.apps:demo-domain:jar:${project.version}
* org.apache.isis.incubator.viewer:isis-viewer-javafx-viewer:jar:${project.version}
* org.apache.isis.mavendeps:isis-mavendeps-integtests:pom:<managed>
* org.apache.isis.mavendeps:isis-mavendeps-jdk11:pom:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-datanucleus5:jar:<managed>
* org.apache.isis.security:isis-security-bypass:jar:<managed>
* org.apache.isis.security:isis-security-shiro:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-ui:pom:${project.version}
* org.apache.isis.valuetypes:isis-valuetypes-markdown-metamodel:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-markdown-ui:pom:${project.version}
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.examples.apps
|demo-vaadin
|jar
|\examples\demo\vaadin
|Demo - Vaadin
|_Dependencies_

* org.apache.isis.examples.apps:demo-web:jar:${project.version}
* org.apache.isis.incubator.viewer:isis-viewer-vaadin-viewer:jar:${project.version}
* org.apache.isis.mavendeps:isis-mavendeps-jdk11:pom:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-ui-vaa:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-ui-wkt:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-markdown-ui-wkt:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-sse-ui-wkt:jar:<managed>
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.examples.apps
|demo-web
|jar
|\examples\demo\web
|Demo - Web
|_Components_

* demoapp.web._infra.utils.ThereCanBeOnlyOne

_Dependencies_

* org.apache.isis.examples.apps:demo-domain:jar:${project.version}
* org.apache.isis.extensions:isis-extensions-command-replay-primary:jar:<managed>
* org.apache.isis.extensions:isis-extensions-command-replay-secondary:jar:<managed>
* org.apache.isis.extensions:isis-extensions-cors-impl:jar:<managed>
* org.apache.isis.mavendeps:isis-mavendeps-webapp:pom:<managed>



|org.apache.isis.examples.apps
|demo-wicket
|jar
|\examples\demo\wicket
|Demo - Wicket
|_Dependencies_

* org.apache.isis.examples.apps:demo-web:jar:${project.version}
* org.apache.isis.extensions:isis-extensions-pdfjs-ui:jar:<managed>
* org.apache.isis.mavendeps:isis-mavendeps-webapp:pom:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-asciidoc-ui-wkt:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-markdown-ui-wkt:jar:<managed>
* org.apache.isis.valuetypes:isis-valuetypes-sse-ui-wkt:jar:<managed>


|===

== Incubator

[plantuml,Incubator,svg]
----
@startuml(id=Incubator)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<11>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<8>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<9>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<10>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Inc - Client kroViz\n<size:10>[Container: packaging: jar]</size>" <<3>> as 3
  rectangle "==Apache Isis Inc - Viewer JavaFX\n<size:10>[Container: packaging: pom]</size>" <<4>> as 4
  rectangle "==Apache Isis Inc - Viewer JavaFX (Model)\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
  rectangle "==Apache Isis Inc - Viewer JavaFX (UI Components)\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Apache Isis Inc - Viewer JavaFX (Viewer)\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
  rectangle "==Apache Isis Inc - Viewer Vaadin\n<size:10>[Container: packaging: pom]</size>" <<8>> as 8
  rectangle "==Apache Isis Inc - Viewer Vaadin (Model)\n<size:10>[Container: packaging: jar]</size>" <<9>> as 9
  rectangle "==Apache Isis Inc - Viewer Vaadin (UI Components)\n<size:10>[Container: packaging: jar]</size>" <<10>> as 10
  rectangle "==Apache Isis Inc - Viewer Vaadin (Viewer)\n<size:10>[Container: packaging: jar]</size>" <<11>> as 11
  rectangle "==Apache Isis Incubator\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
}
4 .[#707070].> 5 : ""
4 .[#707070].> 6 : ""
4 .[#707070].> 7 : ""
8 .[#707070].> 9 : ""
8 .[#707070].> 10 : ""
8 .[#707070].> 11 : ""
2 .[#707070].> 4 : ""
2 .[#707070].> 8 : ""
@enduml
----

.Projects/Modules (Incubator)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.incubator
|isis-incubator
|pom
|\incubator
|Apache Isis Incubator
|Collection of Apache Isis extensions, subdomains or BC mappings, currently incubating.

_Dependencies_

* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.incubator.clients
|isis-client-kroviz
|jar
|\incubator\clients\kroviz
|Apache Isis Inc - Client kroViz
|Initial sketches



|org.apache.isis.incubator.viewer
|isis-viewer-javafx
|pom
|\incubator\viewers\javafx
|Apache Isis Inc - Viewer JavaFX
|Initial sketches



|org.apache.isis.incubator.viewer
|isis-viewer-javafx-model
|jar
|\incubator\viewers\javafx\model
|Apache Isis Inc - Viewer JavaFX (Model)
|_Dependencies_

* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.viewer:isis-viewer-common:jar:<managed>
* org.openjfx:javafx-base:jar:<managed>
* org.openjfx:javafx-controls:jar:<managed>
* org.openjfx:javafx-fxml:jar:<managed>
* org.openjfx:javafx-swing:jar:<managed>
* org.openjfx:javafx-web:jar:<managed>



|org.apache.isis.incubator.viewer
|isis-viewer-javafx-ui
|jar
|\incubator\viewers\javafx\ui
|Apache Isis Inc - Viewer JavaFX (UI Components)
|_Components_

* org.apache.isis.incubator.viewer.javafx.ui.components.UiComponentFactoryFx
* org.apache.isis.incubator.viewer.javafx.ui.components.markup.MarkupFieldFactory
* org.apache.isis.incubator.viewer.javafx.ui.components.number.NumberFieldFactory
* org.apache.isis.incubator.viewer.javafx.ui.components.objectref.ObjectReferenceFieldFactory
* org.apache.isis.incubator.viewer.javafx.ui.components.other.FallbackFieldFactory
* org.apache.isis.incubator.viewer.javafx.ui.components.temporal.TemporalFieldFactory
* org.apache.isis.incubator.viewer.javafx.ui.components.text.TextFieldFactory
* org.apache.isis.incubator.viewer.javafx.ui.decorator.disabling.DisablingDecoratorForButton
* org.apache.isis.incubator.viewer.javafx.ui.decorator.disabling.DisablingDecoratorForFormField
* org.apache.isis.incubator.viewer.javafx.ui.decorator.icon.IconDecoratorForLabeled
* org.apache.isis.incubator.viewer.javafx.ui.decorator.icon.IconDecoratorForMenuItem
* org.apache.isis.incubator.viewer.javafx.ui.decorator.icon.IconServiceDefault
* org.apache.isis.incubator.viewer.javafx.ui.decorator.prototyping.PrototypingDecoratorForButton
* org.apache.isis.incubator.viewer.javafx.ui.decorator.prototyping.PrototypingDecoratorForFormField
* org.apache.isis.incubator.viewer.javafx.ui.decorator.prototyping.PrototypingInfoPopupProvider
* org.apache.isis.incubator.viewer.javafx.ui.main.MainViewFx
* org.apache.isis.incubator.viewer.javafx.ui.main.UiActionHandlerFx
* org.apache.isis.incubator.viewer.javafx.ui.main.UiBuilderFx
* org.apache.isis.incubator.viewer.javafx.ui.main.UiContextFxDefault

_Dependencies_

* org.apache.isis.core:isis-core-runtimeservices:jar:<managed>
* org.apache.isis.incubator.viewer:isis-viewer-javafx-model:jar:<managed>



|org.apache.isis.incubator.viewer
|isis-viewer-javafx-viewer
|jar
|\incubator\viewers\javafx\viewer
|Apache Isis Inc - Viewer JavaFX (Viewer)
|_Dependencies_

* org.apache.isis.incubator.viewer:isis-viewer-javafx-ui:jar:<managed>



|org.apache.isis.incubator.viewer
|isis-viewer-vaadin
|pom
|\incubator\viewers\vaadin
|Apache Isis Inc - Viewer Vaadin
|Initial sketches



|org.apache.isis.incubator.viewer
|isis-viewer-vaadin-model
|jar
|\incubator\viewers\vaadin\model
|Apache Isis Inc - Viewer Vaadin (Model)
|_Dependencies_

* com.vaadin:vaadin:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-webapp:jar:<managed>
* org.apache.isis.viewer:isis-viewer-common:jar:<managed>



|org.apache.isis.incubator.viewer
|isis-viewer-vaadin-ui
|jar
|\incubator\viewers\vaadin\ui
|Apache Isis Inc - Viewer Vaadin (UI Components)
|_Components_

* org.apache.isis.incubator.viewer.vaadin.ui.auth.LogoutHandlerVaa
* org.apache.isis.incubator.viewer.vaadin.ui.auth.VaadinAuthenticationHandler
* org.apache.isis.incubator.viewer.vaadin.ui.components.UiComponentFactoryVaa
* org.apache.isis.incubator.viewer.vaadin.ui.components.blob.BlobFieldFactory
* org.apache.isis.incubator.viewer.vaadin.ui.components.clob.ClobFieldFactory
* org.apache.isis.incubator.viewer.vaadin.ui.components.markup.MarkupFieldFactory
* org.apache.isis.incubator.viewer.vaadin.ui.components.other.FallbackFieldFactory
* org.apache.isis.incubator.viewer.vaadin.ui.components.temporal.TemporalFieldFactory
* org.apache.isis.incubator.viewer.vaadin.ui.components.text.TextFieldFactory
* org.apache.isis.incubator.viewer.vaadin.ui.components.text.uuid.UuidFieldFactory
* org.apache.isis.incubator.viewer.vaadin.ui.pages.main.UiActionHandlerVaa
* org.apache.isis.incubator.viewer.vaadin.ui.pages.main.UiContextVaaDefault

_Dependencies_

* com.vaadin:vaadin:jar:<managed>
* com.vaadin:vaadin-spring:jar:<managed>
* commons-fileupload:commons-fileupload:jar:1.4
* org.apache.isis.core:isis-core-runtimeservices:jar:<managed>
* org.apache.isis.incubator.viewer:isis-viewer-vaadin-model:jar:<managed>



|org.apache.isis.incubator.viewer
|isis-viewer-vaadin-viewer
|jar
|\incubator\viewers\vaadin\viewer
|Apache Isis Inc - Viewer Vaadin (Viewer)
|_Dependencies_

* org.apache.isis.incubator.viewer:isis-viewer-vaadin-ui:jar:<managed>


|===

== Legacy

[plantuml,Legacy,svg]
----
@startuml(id=Legacy)
title package-ecosystem - Containers
caption Artifact Dependency Diagram (Maven)

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<2>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<5>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<6>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
skinparam rectangle<<7>> {
  BackgroundColor #438dd5
  FontColor #fffffe
  BorderColor #2E6295
}
package "package-ecosystem\n[Software System]" {
  rectangle "==Apache Isis Legacy\n<size:10>[Container: packaging: pom]</size>" <<2>> as 2
  rectangle "==Apache Isis Legacy - Applib\n<size:10>[Container: packaging: jar]</size>" <<3>> as 3
  rectangle "==Apache Isis Legacy - Commons\n<size:10>[Container: packaging: jar]</size>" <<4>> as 4
  rectangle "==Apache Isis Legacy - Metamodel\n<size:10>[Container: packaging: jar]</size>" <<5>> as 5
  rectangle "==Apache Isis Legacy - REST Client\n<size:10>[Container: packaging: jar]</size>" <<6>> as 6
  rectangle "==Apache Isis Legacy - Runtime\n<size:10>[Container: packaging: jar]</size>" <<7>> as 7
}
2 .[#707070].> 3 : ""
2 .[#707070].> 4 : ""
2 .[#707070].> 5 : ""
2 .[#707070].> 6 : ""
2 .[#707070].> 7 : ""
@enduml
----

.Projects/Modules (Legacy)
[cols="2m,2m,1m,1m,2,5a", options="header"]
|===
|Group |Artifact |Type |Folder |Name |Description 

|org.apache.isis.legacy
|isis-legacy
|pom
|\legacy
|Apache Isis Legacy
|Collection of deprecated Apache Isis functionality, for removal.

_Dependencies_

* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.legacy
|isis-legacy-applib
|jar
|\legacy\extensions\core\applib
|Apache Isis Legacy - Applib
|To ease migration from Apache Isis versions 1.16+ to 2.0.0.

_Components_

* org.apache.isis.legacy.applib.DomainObjectContainer

_Dependencies_

* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-applib:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>



|org.apache.isis.legacy
|isis-legacy-commons
|jar
|\legacy\extensions\core\commons
|Apache Isis Legacy - Commons
|To ease migration from Apache Isis versions 1.16+ to 2.0.0.

_Dependencies_

* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-applib:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>



|org.apache.isis.legacy
|isis-legacy-metamodel
|jar
|\legacy\extensions\core\metamodel
|Apache Isis Legacy - Metamodel
|To ease migration from Apache Isis versions 1.16+ to 2.0.0.

_Dependencies_

* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-metamodel:jar:<managed>
* org.apache.isis.legacy:isis-legacy-applib:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-applib:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>



|org.apache.isis.legacy
|isis-legacy-restclient
|jar
|\legacy\mappings\restclient
|Apache Isis Legacy - REST Client
|As defined in Isis v1.x RO Applib.

_Dependencies_

* org.apache.isis.commons:isis-commons:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.viewer:isis-viewer-restfulobjects-applib:jar:<managed>
* org.projectlombok:lombok:jar:<managed>



|org.apache.isis.legacy
|isis-legacy-runtime
|jar
|\legacy\extensions\core\runtime
|Apache Isis Legacy - Runtime
|To ease migration from Apache Isis versions 1.16+ to 2.0.0.

_Dependencies_

* com.google.guava:guava:jar:<managed>
* org.apache.isis.core:isis-applib:jar:<managed>
* org.apache.isis.core:isis-core-internaltestsupport:jar:<managed>
* org.apache.isis.core:isis-core-runtime:jar:<managed>
* org.apache.isis.legacy:isis-legacy-applib:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-applib:jar:<managed>
* org.apache.isis.persistence:isis-persistence-jdo-datanucleus5:jar:<managed>
* org.apache.isis.viewer:isis-viewer-wicket-ui:jar:<managed>
* org.datanucleus:javax.jdo:jar:<managed>


|===

