= `LocaleProvider`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `LocaleProvider` service is one of the services that work together to implement Apache Isis' support for i18n, being used by Isis' default implementation of xref:rg:svc:rgsvc.adoc#_rgsvc_presentation-layer-spi_TranslationService[`TranslationService`].

The role of the service itself is simply to return the `Locale` of the current user.


[NOTE]
====
For the "big picture" and further details on Apache Isis' i18n support, see xref:ug:btb:i18n.adoc[here].
====



== SPI

The SPI defined by this service is:

[source,java]
----
public interface LocaleProvider {
    @Programmatic
    Locale getLocale();
}
----

This is notionally request-scoped, returning the `Locale` of the current user; _not_ that of the server.  (Note that the implementation is not required to actually be xref:rg:ant:RequestScoped.adoc[`@RequestScoped`], however).




== Implementation

Isis' xref:ug:vw:ugvw.adoc#[Wicket viewer] provides an implementation of this service (`LocaleProviderWicket`) which leverages Apache Wicket APIs.

[NOTE]
====
Currently there is no equivalent implementation for the xref:ug:vro:about.adoc[RestfulObjects viewer].
====






== Related Services

This service works in conjunction with xref:rg:svc:rgsvc.adoc#_rgsvc_presentation-layer-spi_TranslationService[`TranslationService`] and xref:rg:svc:rgsvc.adoc#_rgsvc_presentation-layer-spi_TranslationsResolver[`TranslationsResolver`] in order to provide i18n support.




