= TransactionId
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Value type used to identify a transaction within the context of an outer _org.apache.isis.applib.services.iactn.Interaction_ .

The transaction and _org.apache.isis.applib.services.iactn.Interaction_ are associated by the _#getInteractionId() uniqueId_ .

Obtainable from _TransactionService#currentTransactionId()_ .

== API

[source,java]
.TransactionId.java
----
class TransactionId {
  TransactionId empty()     // <.>
}
----

<.> xref:#empty__[empty()]
+
--
Factory method that returns a nominally "empty" transaction identifier, used as a placeholder.
--

== Members

[#empty__]
=== empty()

Factory method that returns a nominally "empty" transaction identifier, used as a placeholder.
