= ObjectGraph
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Can be used to create diagrams (e.g. Plantuml)

== API

[source,java]
.ObjectGraph.java
----
class ObjectGraph {
  ObjectGraph create(ObjectGraph.Factory factory)
  ObjectGraph transform(ObjectGraph.Transformer transfomer)
  String render(ObjectGraph.Renderer renderer)
  Map<String, List<ObjectGraph.Object>> objectsGroupedByPackage()     // <.>
  Map<String, ObjectGraph.Object> objectById()     // <.>
}
----

<.> xref:#objectsGroupedByPackage_[objectsGroupedByPackage()]
+
--
Returns objects grouped by package (as list-multimap).
--
<.> xref:#objectById_[objectById()]
+
--
Returns a _Map_ from object.id to _Object ObjectGraph.Object_
--

== Members

[#objectsGroupedByPackage_]
=== objectsGroupedByPackage()

Returns objects grouped by package (as list-multimap).

[#objectById_]
=== objectById()

Returns a _Map_ from object.id to _Object ObjectGraph.Object_
