= View Models

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


As described in the xref:userguide:fun:building-blocks.adoc#view-models[introduction], view models are domain objects like domain entities, with behaviour and state.
However, unlike domain entities, their state is _not_ persisted to a database but is instead serialized into its identifier (in effect, its URL).

The framework provides two main ways to implement a view model:

* The more powerful/flexible approach is to use JAXB annotations; this allows the state of the object's properties and also its collections.
+
The serialized form of these view models is therefore XML, which also enables these view models to act as DTO (useful for various integration scenarios).

* The other approach is to use Apache Isis specific annotations.
+
While (arguably) these explain the intent of the view model better, they are more restrictive: only the state of the object's properties is serialized -- collections are ignored -- and not every datatype is recognized.
+
On the other hand, they are more likely to perform better.
This could be a factor for example in a dashboard/home page that references many view model instances.

In the sections below we consider JAXB view models both as "regular" view models, and also when using them to act as DTOs.



[[jaxb]]
== JAXB View Models


Here's a typical example of a JAXB view model, to allow (certain properties of) two ``Customer``s to be compared:

[source,java]
----
@XmlRootElement(name = "compareCustomers")          // <1>
@XmlType(
        propOrder = {                               // <2>
            "customer1",
            "customer2"
        }
)
@XmlAccessorType(XmlAccessType.FIELD)               // <3>
public class CompareCustomers {

    @XmlElement(required = true)                    // <4>
    @Getter @Setter
    Customer customer1;

    @XmlElement(required = true)                    // <4>
    @Getter @Setter
    Customer customer2;

    @XmlTransient                                   // <5>
    public String getCustomer1Name() {
        return getCustomer1().getName();
    }

    @XmlTransient                                   // <5>
    public String getCustomer2Name() {
        return getCustomer2().getName();
    }

    ...
}
----
<1> The JAXB `@XmlRootElement` annotation indicates this is a view model to Apache Isis, which then uses JAXB to serialize the state of the view model between interactions

<2> Optionally, the properties of the view model can be listed using the `XmlType#propOrder` attribute.
+
This is an all-or-nothing affair: either all properties must be listed, or else the annotation omitted.

<3> Specifying field accessor type allows the Lombok `@Getter` and `@Setter` annotations to be used.
<4> The `@XmlElement` indicates the property is part of the view model's state.
For collections, the `@XmlElementWrapper` would also typically be used.
<5> The `@XmlTransient` indicates that the property is derived and should be ignored by JAXB.
+
The derived properties could also have been implemented using xref:userguide:fun:building-blocks.adoc#mixins[mixins].


[IMPORTANT]
====
Be aware that all the state will become the DTO's memento, ultimately converted into a URL-safe form, by way of the xref:refguide:applib-svc:UrlEncodingService.adoc[`UrlEncodingService`].

There are limits to the lengths of URLs, however.
If the URL does exceed limits or contains invalid characters, then provide a custom implementation of xref:refguide:applib-svc:UrlEncodingService.adoc[`UrlEncodingService`] to handle the memento string in some other fashion (eg substituting it with a GUID, with the memento cached somehow on the server).
a URL.
====






=== Referencing Domain Entities


It's quite common for view models to be "backed by" (be projections of) some underlying domain entity.
For example, the `CompareCustomers` view model described xref:userguide:fun:programming-model.adoc#jaxb[above] actually references two underlying ``Customer`` entities.

It wouldn't make sense to serialize out the state of a persistent entity.
However, the identity of the underlying entity is well defined; Apache Isis defines the xref:refguide:schema:common.adoc[common schema] which defines the `<oid-dto>` element (and corresponding `OidDto` class): the object's type and its identifier.
This is basically a formal XML equivalent to the `Bookmark` object obtained from the xref:refguide:applib-svc:BookmarkService.adoc[`BookmarkService`].

There is only one requirement to make this work: every referenced domain entity must be annotated with xref:refguide:applib-ant:XmlJavaTypeAdapter.adoc[`@XmlJavaTypeAdapter`], specifying the framework-provided `PersistentEntityAdapter`.
And this class is similar to the xref:refguide:applib-svc:BookmarkService.adoc[`BookmarkService`]: it knows how to create an `OidDto` from an object reference.

Thus, in our view model we can legitimately write:

[source,java]
----
public class CompareCustomers {

    @XmlElement(required = true)
    @Getter @Setter
    Customer customer1;
    ...
}
----

All we need to do is remember to add that `@XmlJavaTypeAdapter` annotation to the referenced entity:

[source,java]
----
@XmlJavaTypeAdapter(PersistentEntityAdapter.class)
public class Customer ...  {
    ...
}
----


It's also possible for a DTO view models to hold collections of objects.
These can be of any type, either simple properties, or references to other objects.
The only bit of boilerplate that is required is the `@XmlElementWrapper` annotation.
This instructs JAXB to create an XML element (based on the field name) to contain each of the elements.
(If this is omitted then the contents of the collection are at the same level as the properties; almost certainly not what is required).

For example, we could perhaps generalize the view model to hold a set of ``Customer``s to be compared:

[source,java]
----
public class CompareCustomers {
    ...
    @XmlElementWrapper
    @XmlElement(name = "customers")
    @Getter @Setter
    protected List<Customer> customersToCompare = Lists.newArrayList();
}
----

This capability is particularly useful when the JAXB view model is being used as a xref:userguide:fun:programming-model.adoc#dto[DTO].



[[joda-datatypes]]
=== JODA Time Datatypes


If your JAXB view model contains fields using the JODA datatypes (`LocalDate` and so on), then `@XmlJavaTypeAdapter` additional annotations in order to "teach" JAXB how to serialize out the state.

The Apache Isis applib provides a number of adapters to use out-of-the-box.
For example:


[source,java]
----
@XmlRootElement(name = "categorizeIncomingInvoice")
@XmlType(
        propOrder = {
                ...
                "dateReceived",
                ...
        }
)
@XmlAccessorType(XmlAccessType.FIELD)
public class IncomingInvoiceViewModel extends IncomingOrderAndInvoiceViewModel {

    @XmlJavaTypeAdapter(JodaLocalDateStringAdapter.ForJaxb.class)
    private LocalDate dateReceived;

    ...
}
----

The full list of adapter classes are:



.JAXB adapters
[cols="1a,2a", options="header"]
|===

| JODA datatype
| Adapter

.2+| `org.joda.time.DateTime`
| `JodaDateTimeStringAdapter.ForJaxb`
| `JodaDateTimeXMLGregorianCalendarAdapter.ForJaxb`

.2+| `org.joda.time.LocalDate`
| `JodaLocalDateStringAdapter.ForJaxb`
| `JodaLocalDateXMLGregorianCalendarAdapter.ForJaxb`

.2+| `org.joda.time.LocalDateTime`
| `JodaLocalDateTimeStringAdapter.ForJaxb`
| `JodaLocalDateTimeXMLGregorianCalendarAdapter.ForJaxb`


.2+| `org.joda.time.LocalTime`
| `JodaLocalTimeStringAdapter.ForJaxb`
| `JodaLocalTimeXMLGregorianCalendarAdapter.ForJaxb`

| `java.sql.Timestamp`
| `JavaSqlTimestampXmlGregorianCalendarAdapter.ForJaxb`


|===


[TIP]
====
If you want to roll-your-own, take a look at link:http://blog.bdoughan.com/2011/05/jaxb-and-joda-time-dates-and-times.html[this blog post].
====



[[dto]]
== DTOs


JAXB view models can also be used as DTOs.
The examples in this section uses the DTO for `ToDoItem`, taken from the http://github.com/apache/isis-app-todoapp[TodoApp].

This DTO is defined as follows:

[source,java]
----
package todoapp.app.viewmodels.todoitem.v1;                         // <1>
@XmlRootElement(name = "toDoItemDto")                               // <2>
@XmlType(
        propOrder = {                                               // <3>
            "majorVersion", "minorVersion",
            "description", "category", ...
            "toDoItem", "similarItems"
        }
)
@DomainObjectLayout(
        titleUiEvent = TitleUiEvent.Doop.class                      // <4>
)
public class ToDoItemV1_1 implements Dto {                          // <5>
    @XmlElement(required = true, defaultValue = "1")                // <6>
    public final String getMajorVersion() { return "1"; }
    @XmlElement(required = true, defaultValue = "1")                // <7>
    public String getMinorVersion() { return "1"; }

    @XmlElement(required = true)                                    // <8>
    @Getter @Setter
    protected String description;
    @XmlElement(required = true)
    @Getter @Setter
    protected String category;
    ...

    @Getter @Setter                                                 // <9>
    protected ToDoItem toDoItem;
    @XmlElementWrapper                                              // <10>
    @XmlElement(name = "todoItem")
    @Getter @Setter
    protected List<ToDoItem> similarItems = Lists.newArrayList();
}
----
<1> package name encodes major version; see discussion on xref:userguide:fun:programming-model.adoc#versioning[versioning]
<2> identifies this class as a view model and defines the root element for JAXB serialization
<3> all properties in the class must be listed; (they can be ignored using `@XmlTransient`)
<4> demonstrating use of UI events for a subscriber to provide the DTO's title; see xref:refguide:applib-ant:DomainObjectLayout.adoc#titleUiEvent[`@DomainObjectLayout#titleUiEvent()`].
<5> class name encodes (major and) minor version; see discussion on xref:userguide:fun:programming-model.adoc#versioning[versioning]
<6> again, see discussion on xref:userguide:fun:programming-model.adoc#versioning[versioning]
<7> again, see discussion on xref:userguide:fun:programming-model.adoc#versioning[versioning]
<8> simple scalar properties
<9> reference to a persistent entity; discussed xref:userguide:fun:programming-model.adoc#referencing-domain-entities[here]
<10> reference to a collection of persistent entities; again discussed xref:userguide:fun:programming-model.adoc#referencing-domain-entities[here]




=== Versioning


The whole point of using DTOs (in Apache Isis, at least) is to define a formal contact between two inter-operating but independent applications.
Since the only thing we can predicate about the future with any certainty is that it one or both of these applications will change, we should version DTOs from the get-go.
This allows us to make changes going forward without unnecessarily breaking existing consumers of the data.

[NOTE]
====
There are several ways that versioning might be accomplished; we base our guidelines on this link:http://www.xfront.com/Versioning.pdf[article] taken from Roger Costello's blog, well worth a read.
====

We can distinguish two types of changes:

* backwardly compatible changes
* breaking changes.

We can immediately say that the XSD namespace should change only when there is a major/breaking change.
If following link:http://semver.org[semantic versioning] that means when we bump the major version number v1, v2, etc.

XML namespaces correspond (when using JAXB) to Java packages.
We should therefore place our DTOs in a package that contains only the major number; this package will eventually contain a range of DTOs that are intended to be backwardly compatible with one another.
The package should also have a `package-info.java`; it is this that declares the XSD namespace:

[source,java]
----
@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://viewmodels.app.todoapp/todoitem/v1/Dto.xsd",        // <1>
        xmlns = {
                @javax.xml.bind.annotation.XmlNs(
                        namespaceURI = "http://isis.apache.org/schema/common",
                        prefix = "com"
                )
        },
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package todoapp.app.viewmodels.todoitem.v1;                                     // <2>
----
<1> the namespace URI, used by the DTO residing in this package.
<2> the package in which the DTO resides.  Note that this contains only the major version.

Although there is no requirement for the namespace URI to correspond to a physical URL, it should be unique.
This usually means including a company domain name within the string.

As noted above, this package will contain multiple DTO classes all with the same namespace; these represent a set of minor versions of the DTO, each subsequent one intended to be backwardly compatible with the previous.
Since these DTO classes will all be in the same package (as per the advice above), the class should therefore include the minor version name:

[source,java]
----
package todoapp.app.viewmodels.todoitem.v1;     // <1>
...
public class ToDoItemV1_1 implements Dto {      // <2>
    ...
}
----
<1> package contains the major version only
<2> DTO class contains the (major and) minor version


We also recommend that each DTO instance should also specify the version of the XSD schema that it is logically compatible with.
Probably most consumers will not persist the DTOs; they will be processed and then discarded.
However, it would be wrong to assume that is the case in all cases; some consumers might choose to persist the DTO (eg for replay at some later state).

Thus:

[source,java]
----
public class ToDoItemV1_1 implements Dto {
    @XmlElement(required = true, defaultValue = "1")
    public final String getMajorVersion() { return "1"; }   // <1>
    @XmlElement(required = true, defaultValue = "1")
    public String getMinorVersion() { return "1"; }         // <2>
    ...
}
----
<1> returns the major version (in sync with the package)
<2> returns the minor version (in sync with the class name)

These methods always return a hard-coded literal.
Any instances serialized from these classes will implicitly "declare" the (major and) minor version of the schema with which they are compatible.
If a consumer has a minimum version that it requires, it can therefore inspect the XML instance itself to determine if it is able to consume said XML.

If a new (minor) version of a DTO is required, then we recommend copying-and-pasting the previous version, eg:

[source,java]
----
public class ToDoItemV1_2 implements Dto {
    @XmlElement(required = true, defaultValue = "1")
    public final String getMajorVersion() { return "1"; }
    @XmlElement(required = true, defaultValue = "2")
    public String getMinorVersion() { return "2"; }
    ...
}
----

Obviously, only changes made must be backward compatible, eg new members must be optional.

Alternatively, you might also consider simply editing the source file, ie renaming the class and bumping up the value returned by `getMinorVersion()`.

We also _don't_ recommend using inheritance (ie `ToDoItemV1_2` should not inherit from `ToDoItemV1_1`; this creates unnecessary complexity downstream if generating XSDs and DTOs for the downstream consumer.



[[generating-xsds]]
=== Generating XSDs and DTOs




In the section xref:userguide:fun:programming-model.adoc#referencing-domain-entities[above] it was explained how a view model DTO can transparently reference any "backing" entities; these references are converted to internal object identifiers.

However, if the consumer of the XML is another Java process (eg running within an Apache Camel route), then you might be tempted/expect to be able to use the same DTO within that Java process.
But of course you cannot; the consumer runs in a different process space, and will not have references to the entity types themselves.

For integration scenarios you'll therefore generally want to define a DTO in a technology independent fashion, for example using XSD schema.
This can be generated as a DTO for use within Apache Isis, while still allowing XML instances of the schema to be consumed by any other client.

The http://github.com/apache/isis-app-todoapp[TodoApp] demonstrates how use an XSD to generate a DTO; it's mostly just boilerplate.
In the todoapp it can be found in the `todoapp-xsd` Maven module, whose `pom.xml` is structured as two profiles:

[source,xml]
----
<project ... >
    <artifactId>todoapp-xsd</artifactId>
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>todoapp-app</artifactId>
        </dependency>
    </dependencies>
    <profiles>
        <profile>
            <id>isis-xsd</id>
            <activation>
                <property>
                    <name>!skip.isis-xsd</name>
                </property>
            </activation>
            ...
        </profile>
        <profile>
            <id>xjc</id>
            <activation>
                <property>
                    <name>!skip.xjc</name>
                </property>
            </activation>
            ...
        </profile>
    </profiles>
</project>
----

The `isis-xsd` profile generates the XSD using the xref:refguide:mvn:xsd.adoc[`xsd` goal] of Isis' maven plugin:

[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.isis.tool</groupId>
            <artifactId>isis-maven-plugin</artifactId>
            <version>${isis.version}</version>
            <configuration>
                <appManifest>todoapp.dom.TodoAppDomManifest</appManifest>
                <jaxbClasses>
                    <jaxbClass>todoapp.app.viewmodels.todoitem.v1.ToDoItemV1_1</jaxbClass>
                </jaxbClasses>
                <separate>false</separate>
                <commonSchemas>false</commonSchemas>
            </configuration>
            <dependencies>
                <dependency>
                    <groupId>${project.groupId}</groupId>
                    <artifactId>todoapp-dom</artifactId>
                    <version>${project.version}</version>
                </dependency>
                <dependency>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                    <version>16.0.1</version>
                </dependency>
            </dependencies>
            <executions>
                <execution>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>xsd</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <artifactId>maven-assembly-plugin</artifactId>
            <version>2.5.3</version>
            <configuration>
                <descriptor>src/assembly/dep.xml</descriptor>
            </configuration>
            <executions>
                <execution>
                    <id>create-archive</id>
                    <phase>package</phase>
                    <goals>
                        <goal>single</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----

The `todoapp.dom.TodoAppDomManifest` is a cut-down version of the app manifest that identifies only the `dom` domain services.

The `xjc` profile, meanwhile, uses the `maven-jaxb2-plugin` (a wrapper around the `schemagen` JDK tool) to generate a DTO from the XSD generated by the preceding profile:

[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.jvnet.jaxb2.maven2</groupId>
            <artifactId>maven-jaxb2-plugin</artifactId>
            <version>0.12.3</version>
            <executions>
                <execution>
                    <id>xjc-generate</id>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <removeOldOutput>true</removeOldOutput>
                <schemaDirectory>
                    target/generated-resources/isis-xsd/viewmodels.app.todoapp
                </schemaDirectory>
                <schemaIncludes>
                    <schemaInclude>todoitem/v1/Dto.xsd</schemaInclude>
                </schemaIncludes>
                <bindingDirectory>src/main/resources</bindingDirectory>
                <bindingIncludes>
                    <bindingInclude>binding.xml</bindingInclude>
                </bindingIncludes>
                <catalog>src/main/resources/catalog.xml</catalog>
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <version>1.9.1</version>
            <executions>
                <execution>
                    <id>add-source</id>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>add-source</goal>
                    </goals>
                    <configuration>
                    <sources>
                        <source>target/generated-sources/xjc</source>
                    </sources>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----



=== DTO Consumers



The actual consumers of DTOs will generally obtain the XML of the view models either by requesting the XML directly, eg using the xref:vro:ROOT:about.adoc[RestfulObjects viewer], or may have the XML sent to them asynchronously using an ESB such as Apache Camel.

In the former case, the consumer requests the DTO by calling the REST API with the appropriate HTTP `Accept` header.
An appropriate implementation of xref:refguide:applib-svc:ContentMappingService.adoc[`ContentMappingService`] can then be used to return the appropriate DTO (as XML).

For the latter case, one design is simply for the application to instantiate the view model, then call the xref:refguide:applib-svc:JaxbService.adoc[`JaxbService`] to obtain its corresponding XML.  This can then be published onto the ESB, for example using an http://activemq.apache.org[Apache ActiveMQ (TM)] queue.

However, rather than try to push all the data that might be needed by any of these external systems in a single XML event (which would require anticipating all the requirements, likely a hopeless task), a better design is to publish only the fact that something of note has changed - ie, that an action on a domain object has been invoked - and then let the consumers call back to obtain other information if required.
This can once again be done by calling the REST API with an appropriate HTTP `Accept` header.

[TIP]
====
This is an example of the link:https://leanpub.com/camel-design-patterns[VETRO pattern] (validate, enrich, transform, route, operate).
In our case we focus on the validation (to determine the nature of the inbound message, ie which action was invoked), and the enrich (callback to obtain a DTO with additional information required by the consumer).
====

The (non-ASF) link:https://platform.incode.org[Incode Platform^]'s publishmq module provides an out-of-the-box solution of this design.
It provides an implementation of the xref:refguide:applib-svc:PublisherService.adoc[`PublisherService`], but which simply publishes instances of xref:refguide:schema:ixn.adoc[`InteractionDto`] to an ActiveMQ queue.
Camel (or similar) can then be hooked up to consume these events from this queue, and use a processor to parse the action memento to determine what has changed on the source system.
Thereafter, a subsequent Camel processor can then call back to the source - via the xref:vro:ROOT:about.adoc[Restful Objects viewer] - to enrich the message with additional details using a DTO.





[[non-jaxb]]
== Non-JAXB View Models


Instead of using JAXB to specify a view model, it is also possible to use Apache Isis-specific annotations.

As was explained xref:userguide:fun:programming-model.adoc#view-models[earlier], the approach is described here is neither as flexible nor as powerful as using the JAXB-style of view models.
It is however likely to be faster.

WARNING: TODO: v2: I think we should only support programmatic API (ViewModel), and JAXB.
//  So let's get rid of all these other natures that, under the covers, are all our original poor-man's JAXB (ie, EXTERNAL_ENTITY, INMEMORY_ENTITY, VIEW_MODEL, and @ViewModel itself).


While the underlying technique is the same irrespective of use case, the programming model provides various ways of defining a view model so that the original intent is not lost.
They are:

.View model programming model
[cols="1a,4a,2a", options="header"]
|===

| Use case
| Code
| Description


| External entity
|[source,java]
----
@DomainObject(nature=Nature.EXTERNAL_ENTITY)
public class CustomerRecordOnSAP { /* ... */ }
----
|Annotated with xref:refguide:applib-ant:DomainObject.adoc#nature[`@DomainObject#nature`] and a nature of `EXTERNAL_ENTITY`, with memento derived automatically from the properties of the domain object.  Collections are ignored, as are any properties annotated as xref:refguide:applib-ant:Property.adoc#mementoSerialization[memento serialization].

| In-memory entity
|[source,java]
----
@DomainObject(nature=Nature.INMEMORY_ENTITY)
public class Log4JAppender { /* ... */ }
----
|As preceding, but using a nature of `INMEMORY_ENTITY`.

|Application view model
|[source,java]
----
@DomainObject(nature=Nature.VIEW_MODEL)
public class Dashboard { /* ... */ }
----
|As preceding, but using a nature of `VIEW_MODEL`.

|Application view model
|
[source,java]
----
@ViewModel
public class Dashboard { /* ... */ }
----

|Annotated with xref:refguide:applib-ant:ViewModel.adoc[`@ViewModel`] annotation (effectively just an alias)' memento is as preceding: from "persisted" properties, collections ignored

|Application view model
|
[source,java]
----
public class ExcelUploadManager implements ViewModel {
  public String viewModelMemento() { /* ... */ }
  public void viewModelInit(String memento) { /* ... */ }
}
----
|Implement xref:refguide:applib-cm:classes/super.adoc#ViewModel[`ViewModel`] interface.  The memento is as defined by the
interface's methods: the programmer has full control (but also full responsibility) for the string memento.

|===





