:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

This is the backing entity projected by the  `PropertyPublishingChildVm` view model:

[source,java,indent=0]
----
include::PropertyProjectingChildVm.java[tags=class]
----
<.> projecting property ...
<.> \... does not need to be visible in the user interface

Normally such an entity would have many different properties, with some visible (in tables) in some contexts, other properties in others.
A projecting view model acts as a projection of the entity, only surfacing the properties of the underlying entity that are most useful in the context of the use case in question.
