[[_rgfis_persistence-layer_PublishingServiceInternal]]
= `PublishingServiceInternal`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/


The (internal) `PublishingServiceInternal` domain service acts as an internal facade to any configured xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublisherService[`PublisherService`] or (deprecated) xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublishingService[`PublishingService`] domain services.

For published action invocations/ property edits, it provides an API for those member executions to call.

For published objects, it provides an API for the framework to call at the end of the interaction; it obtains details of the changed objects (from the xref:../rgfis/rgfis.adoc#_rgfis_persistence-layer_ChangedObjectsServiceInternal[`ChangedObjectsServiceInternal`]) and filters them to just those objects that are to be published; these are then passed through to any configured `PublisherService` or `PublishingService` implementations.


== SPI and Implementation

The SPI of the service is:

[source,java]
----
public class PublishingServiceInternal {
    void publishAction(
            Interaction.Execution execution,        // <1>
            ObjectAction objectAction,              // <2>
            IdentifiedHolder identifiedHolder,
            ObjectAdapter targetAdapter,
            List<ObjectAdapter> parameterAdapters,
            ObjectAdapter resultAdapter);
    void publishProperty(                           // <3>
            Interaction.Execution execution);
    void publishObjects();                          // <4>
}
----
<1> to publish an action invocation, as represented by the specified member `Execution` parameter and with the
xref:../rgant/rgant.adoc#_rgant-Action_publishing[`@Action#publishing()`] annotation attribute or equivalent, to any configured
xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublisherService[`PublisherService`].  The `Execution` object will be an instance of
`ActionInvocation` (see xref:../rgsvc/rgsvc.adoc#_rgsvc_application-layer-api_InteractionContext[`InteractionContext`] for details).
<2> the remaining parameters are to support the publishing of the action to any configured
xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublishingService[`PublishingService`] services (deprecated).
<3> to publish a property edit, as as represented by the specified member `Execution` parameter and with the
xref:../rgant/rgant.adoc#_rgant-Property_publishing[`@Property#publishing()`] annotation attribute or equivalent, to any
configured xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublisherService[`PublisherService`].  The `Execution` object will be an instance
of `PropertyEdit` (see xref:../rgsvc/rgsvc.adoc#_rgsvc_application-layer-api_InteractionContext[`InteractionContext`] for details).
<4> to publish all changed objects that are to be published (with the
xref:../rgant/rgant.adoc#_rgant-DomainObject_publishing[`@DomainObject#publishing()`] annotation attribute or equivalent).


The service implementation is `o.a.i.c.m.s.publishing.PublishingServiceInternal`.



== Registering the Service

Apache Isis' default implementation of `PublishingServiceInternal` class is automatically registered (it is annotated with `@DomainService`) so no further configuration is required.

To use an alternative implementation, use xref:../rgant/rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`] (as explained in the xref:../rgsvc/rgsvc adoc#__rgsvc_intro_overriding-the-services[introduction] to this guide).


== Related Classes

The service delegates between the (internal) xref:../rgfis/rgfis.adoc#_rgfis_persistence-layer_ChangedObjectsServiceInternal[`ChangedObjectsServiceInternal`] domain service to the configured xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublisherService[`PublisherService`] and  xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublishingService[`PublishingService`].

The (internal) xref:../rgfis/rgfis.adoc#_rgfis_persistence-layer_AuditingServiceInternal[`AuditingServiceInternal`] performs a similar function for the xref:../rgsvc/rgsvc.adoc#_rgsvc_persistence-layer-spi_PublisherService[`PublisherService`], also collating details of the changed objects from `ChangedObjectsServiceInternal`.
