:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Provides the ability to reorder (or suppress) columns in both parented- and standalone tables.

There can be multiple implementations of this service registered, ordered as per the Spring _org.springframework.core.annotation.Order_ annotation (or equivalent). The result of the first service implementation to return a non- `null` value will be used.

If all provided implementations return `null` , then the framework will fallback to a default implementation.

== API

[source,java]
.TableColumnOrderService.java
----
interface TableColumnOrderService {
  List<String> orderParented(final Object parent, final String collectionId, final Class<?> collectionType, final List<String> propertyIds)     // <.>
  List<String> orderStandalone(final Class<?> collectionType, final List<String> propertyIds)     // <.>
}
----

<.> xref:#orderParented__Object_String_Class_List[orderParented(Object, String, Class, List)]
+
--
For the parent collection owned by the specified parent and collection Id, return the set of property ids in the same or other order.
--
<.> xref:#orderStandalone__Class_List[orderStandalone(Class, List)]
+
--
For the standalone collection of the specified type, return the set of property ids in the same or other order.
--

== Members

[#orderParented__Object_String_Class_List]
=== orderParented(Object, String, Class, List)

For the parent collection owned by the specified parent and collection Id, return the set of property ids in the same or other order.

Return `null` if has no opinion/provides no reordering for this parent and collection.

[#orderStandalone__Class_List]
=== orderStandalone(Class, List)

For the standalone collection of the specified type, return the set of property ids in the same or other order.

Return `null` if has no opinion/provides no reordering for this type.

include::hooks/TableColumnOrderService_010-implementation.adoc[]

include::hooks/TableColumnOrderService_020-examples-and-usage.adoc[]
