:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

To highlight certain information on the page, it can sometimes be helpful to style individual collections.

The `cssClass` attribute indicates the CSS class that a collection should have.
This can be set using either the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/CollectionLayout.html#cssclass[@CollectionLayout#cssClass] annotation, or by using the link:https://causeway.apache.org/userguide/2.0.0-RC1/fun/ui.html#by-example[.layout.xml] layout file.

The `application.css` file is then be used to apply styling to that CSS class.

== How this demo works

This page contains two collections.
The `children` collection uses `@CollectionLayout#cssClass` to specify a custom CSS class of "red", while the `moreChildre` collection specifies a custom CSS class using the `layout.xml` file.

In terms of code:

* the `children` property is defined as:
+
[source,java,indent=0]
----
include::CollectionLayoutCssClassPage.java[tags=children]
----
<.> explicitly specifies the CSS class to apply for the children `<div>`


* the `moreChildren` collection defines a CSS class hint using the `Xxx.layout.xml` file:
+
[source,xml,indent=0,tabsize=4]
.CollectionLayoutCssClassPage.layout.xml
----
<cpt:collection id="moreChildren" cssClass="blue"/>
----

* the `application.css` contains these styles:
+
[source,css]
.application.css
----
.collections .red .card .card-header {
    background-color: red;
    color: white;
}

.collections .blue .card .card-header {
    background-color: dodgerblue;
    color: white;
}
----

One advantage of the layout file over the annotation is that the layout file is dynamic: it can be modified and the changes reloaded in a running application.

