:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


This class is a parent entity that contains an embedded type as a property:

[source,java]
.NumberConstantJdo.java
----
include::NumberConstantJdo.java[tags=class]
----
<.> JDO `@Embedded` annotation indicates that the constituent parts of the embedded type should be stored as columns of the owning entity


The `ComplexNumberJdo` is the embedded type:

[source,java]
.ComplexNumberJdo.java
----
include::ComplexNumberJdo.java[tags=class]
----
<.> JDO `@EmbeddedOnly` annotation is the companion of `@Embedded` on the owning object
<.> Indicates to the framework that this is a value rather than an entity.
Accordingly, we will also need to provide a `ValueSemanticsProvider` implementation, discussed below.
<.> provides access the fields
<.> allows the ORM to initialize the fields
<.> these fields of the embedded type are persisted as columns of the owning entity
