= Versioning

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The whole point of using DTOs (in Apache Isis, at least) is to define a formal contact between two inter-operating but independent applications.
Since the only thing we can predicate about the future with any certainty is that it one or both of these applications will change, we should version DTOs from the get-go.
This allows us to make changes going forward without unnecessarily breaking existing consumers of the data.

[NOTE]
====
There are several ways that versioning might be accomplished; we base our guidelines on this link:http://www.xfront.com/Versioning.pdf[article] taken from Roger Costello's blog, well worth a read.
====

We can distinguish two types of changes:

* backwardly compatible changes
* breaking changes.

We can immediately say that the XSD namespace should change only when there is a major/breaking change.
If following link:http://semver.org[semantic versioning] that means when we bump the major version number v1, v2, etc.

XML namespaces correspond (when using JAXB) to Java packages.
We should therefore place our DTOs in a package that contains only the major number; this package will eventually contain a range of DTOs that are intended to be backwardly compatible with one another.
The package should also have a `package-info.java`; it is this that declares the XSD namespace:

[source,java]
----
@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://viewmodels.app.todoapp/todoitem/v1/Dto.xsd",        // <1>
        xmlns = {
                @javax.xml.bind.annotation.XmlNs(
                        namespaceURI = "http://isis.apache.org/schema/common",
                        prefix = "com"
                )
        },
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package todoapp.app.viewmodels.todoitem.v1;                                     // <2>
----
<1> the namespace URI, used by the DTO residing in this package.
<2> the package in which the DTO resides.  Note that this contains only the major version.

Although there is no requirement for the namespace URI to correspond to a physical URL, it should be unique.
This usually means including a company domain name within the string.

As noted above, this package will contain multiple DTO classes all with the same namespace; these represent a set of minor versions of the DTO, each subsequent one intended to be backwardly compatible with the previous.
Since these DTO classes will all be in the same package (as per the advice above), the class should therefore include the minor version name:

[source,java]
----
package todoapp.app.viewmodels.todoitem.v1;     // <1>
...
public class ToDoItemV1_1 implements Dto {      // <2>
    ...
}
----
<1> package contains the major version only
<2> DTO class contains the (major and) minor version


We also recommend that each DTO instance should also specify the version of the XSD schema that it is logically compatible with.
Probably most consumers will not persist the DTOs; they will be processed and then discarded.
However, it would be wrong to assume that is the case in all cases; some consumers might choose to persist the DTO (eg for replay at some later state).

Thus:

[source,java]
----
public class ToDoItemV1_1 implements Dto {
    @XmlElement(required = true, defaultValue = "1")
    public final String getMajorVersion() { return "1"; }   // <1>
    @XmlElement(required = true, defaultValue = "1")
    public String getMinorVersion() { return "1"; }         // <2>
    ...
}
----
<1> returns the major version (in sync with the package)
<2> returns the minor version (in sync with the class name)

These methods always return a hard-coded literal.
Any instances serialized from these classes will implicitly "declare" the (major and) minor version of the schema with which they are compatible.
If a consumer has a minimum version that it requires, it can therefore inspect the XML instance itself to determine if it is able to consume said XML.

If a new (minor) version of a DTO is required, then we recommend copying-and-pasting the previous version, eg:

[source,java]
----
public class ToDoItemV1_2 implements Dto {
    @XmlElement(required = true, defaultValue = "1")
    public final String getMajorVersion() { return "1"; }
    @XmlElement(required = true, defaultValue = "2")
    public String getMinorVersion() { return "2"; }
    ...
}
----

Obviously, only changes made must be backward compatible, eg new members must be optional.

Alternatively, you might also consider simply editing the source file, ie renaming the class and bumping up the value returned by `getMinorVersion()`.

We also _don't_ recommend using inheritance (ie `ToDoItemV1_2` should not inherit from `ToDoItemV1_1`; this creates unnecessary complexity downstream if generating XSDs and DTOs for the downstream consumer.


