= ApplicationPermissionMode _(enum)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Named after UNIX modes ( `chmod` etc), determines that nature of access (of denial of access if vetoed) to an xref:refguide:applib:index/services/appfeat/ApplicationFeature.adoc[ApplicationFeature] .

== API

[source,java]
.ApplicationPermissionMode.java
----
enum ApplicationPermissionMode {
  VIEWING     // <.>
  CHANGING     // <.>
  String toString()
}
----

<.> xref:#VIEWING[VIEWING]
+
--
Whether the user/role can view (or is prevented from viewing) the application feature (class member).
--
<.> xref:#CHANGING[CHANGING]
+
--
Whether can user/role can change (or is prevented from changing) the state of the system using the application feature (class member).
--

== Members

[#VIEWING]
=== VIEWING

Whether the user/role can view (or is prevented from viewing) the application feature (class member).

The xref:refguide:extensions:index/secman/applib/permission/dom/ApplicationPermissionRule.adoc[ApplicationPermissionRule] of the xref:refguide:extensions:index/secman/applib/permission/dom/ApplicationPermission.adoc[ApplicationPermission] indicates whether access is being granted or denied.

[#CHANGING]
=== CHANGING

Whether can user/role can change (or is prevented from changing) the state of the system using the application feature (class member).

In other words, whether they can execute (if an action, modify/clear (if a property), [addTo/removeFrom (if a collection) ... see note below].

The xref:refguide:extensions:index/secman/applib/permission/dom/ApplicationPermissionRule.adoc[ApplicationPermissionRule] of the xref:refguide:extensions:index/secman/applib/permission/dom/ApplicationPermission.adoc[ApplicationPermission] indicates whether access is being granted or denied.

Note: as of CAUSEWAY-3084 the notion of mutable collections was removed
