= InteractionProvider
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Provides the current thread's xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] .

An xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] contains a top-level xref:refguide:applib:index/services/iactn/Execution.adoc[Execution] representing the invocation of an action or the editing of a property. If that top-level action or property uses the _org.apache.causeway.applib.services.wrapper.WrapperFactory_ domain service to invoke child actions/properties, then those sub-executions are captured as a call-graph. The xref:refguide:applib:index/services/iactn/Execution.adoc[Execution] is thus a graph structure.

== API

[source,java]
.InteractionProvider.java
----
interface InteractionProvider {
  boolean isInInteraction()     // <.>
  Optional<Interaction> currentInteraction()     // <.>
  Optional<InteractionContext> currentInteractionContext()     // <.>
  Optional<UUID> getInteractionId()     // <.>
  int getInteractionLayerCount()     // <.>
  Interaction currentInteractionElseFail()
  InteractionContext currentInteractionContextElseFail()
}
----

<.> xref:#isInInteraction_[isInInteraction()]
+
--
Whether there is a currently active xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] for the calling thread.
--
<.> xref:#currentInteraction_[currentInteraction()]
+
--
Optionally, the currently active xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] for the calling thread.
--
<.> xref:#currentInteractionContext_[currentInteractionContext()]
+
--
Optionally, the currently active xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] for the calling thread.
--
<.> xref:#getInteractionId_[getInteractionId()]
+
--
Unique id of the current request- or test-scoped xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] .
--
<.> xref:#getInteractionLayerCount_[getInteractionLayerCount()]
+
--
interaction-layer-stack size
--

== Members

[#isInInteraction_]
=== isInInteraction()

Whether there is a currently active xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] for the calling thread.

[#currentInteraction_]
=== currentInteraction()

Optionally, the currently active xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] for the calling thread.

[#currentInteractionContext_]
=== currentInteractionContext()

Optionally, the currently active xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] for the calling thread.

[#getInteractionId_]
=== getInteractionId()

Unique id of the current request- or test-scoped xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] .

[#getInteractionLayerCount_]
=== getInteractionLayerCount()

interaction-layer-stack size
