[[commandreplay]]
= Command Replay

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The intention of the `CommandReplay` module is to allow commands -- representing either action invocations or property edits -- to be taken from a primary system and replayed against a secondary system.

It does this by exposing a REST API on the primary system to return (representations of) xref:refguide:extensions:index/commandlog/applib/dom/CommandLogEntry.adoc[CommandLogEntry]s, called at regular intervals by the secondary system.
These are copied into the secondary system and then executed.

The main use case is for regression testing.

