= InteractionContext
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Provides the user and scenario specific environment for an xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] .

== API

[source,java]
.InteractionContext.java
----
class InteractionContext {
  InteractionContext ofUserWithSystemDefaults(final UserMemento user)     // <.>
  UnaryOperator<InteractionContext> switchUser(final UserMemento userMemento)     // <.>
  UnaryOperator<InteractionContext> switchClock(final VirtualClock clock)     // <.>
  UnaryOperator<InteractionContext> switchLocale(final Locale locale)     // <.>
  UnaryOperator<InteractionContext> switchTimeZone(final TimeZone timeZone)     // <.>
  UnaryOperator<T> combine(UnaryOperator<T>... mappers)     // <.>
  UnaryOperator<T> combine(Stream<UnaryOperator<T>> mappers)     // <.>
}
----

<.> xref:#ofUserWithSystemDefaults__UserMemento[ofUserWithSystemDefaults(UserMemento)]
+
--
Creates a new xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] with the specified user and system defaults for clock, locale and time-zone.
--
<.> xref:#switchUser__UserMemento[switchUser(UserMemento)]
+
--
Convenience method for use with _org.apache.isis.applib.services.sudo.SudoService_ , returning a _UnaryOperator_ that will act upon the provided xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] to return the same but with the specified xref:refguide:applib:index/services/user/UserMemento.adoc[UserMemento] .
--
<.> xref:#switchClock__VirtualClock[switchClock(VirtualClock)]
+
--
Convenience method for use with _org.apache.isis.applib.services.sudo.SudoService_ , returning a _UnaryOperator_ that will act upon the provided xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] to return the same but with the specified xref:refguide:applib:index/clock/VirtualClock.adoc[VirtualClock] .
--
<.> xref:#switchLocale__Locale[switchLocale(Locale)]
+
--
Convenience method for use with _org.apache.isis.applib.services.sudo.SudoService_ , returning a _UnaryOperator_ that will act upon the provided xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] to return the same but with the specified _Locale_ .
--
<.> xref:#switchTimeZone__TimeZone[switchTimeZone(TimeZone)]
+
--
Convenience method for use with _org.apache.isis.applib.services.sudo.SudoService_ , returning a _UnaryOperator_ that will act upon the provided xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] to return the same but with the specified _TimeZone_ .
--
<.> xref:#combine__UnaryOperator[combine(UnaryOperator)]
+
--
Convenience method to combine _UnaryOperator_ s, for example as per _#switchUser(UserMemento)_ and _#switchTimeZone(TimeZone)_ .
--
<.> xref:#combine__Stream[combine(Stream)]
+
--
Convenience method to combine _UnaryOperator_ s, for example as per _#switchUser(UserMemento)_ and _#switchTimeZone(TimeZone)_ . credit: https://stackoverflow.com/a/51065029/56880
--

== Members

[#ofUserWithSystemDefaults__UserMemento]
=== ofUserWithSystemDefaults(UserMemento)

Creates a new xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] with the specified user and system defaults for clock, locale and time-zone.

[#switchUser__UserMemento]
=== switchUser(UserMemento)

Convenience method for use with _org.apache.isis.applib.services.sudo.SudoService_ , returning a _UnaryOperator_ that will act upon the provided xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] to return the same but with the specified xref:refguide:applib:index/services/user/UserMemento.adoc[UserMemento] .

[#switchClock__VirtualClock]
=== switchClock(VirtualClock)

Convenience method for use with _org.apache.isis.applib.services.sudo.SudoService_ , returning a _UnaryOperator_ that will act upon the provided xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] to return the same but with the specified xref:refguide:applib:index/clock/VirtualClock.adoc[VirtualClock] .

[#switchLocale__Locale]
=== switchLocale(Locale)

Convenience method for use with _org.apache.isis.applib.services.sudo.SudoService_ , returning a _UnaryOperator_ that will act upon the provided xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] to return the same but with the specified _Locale_ .

[#switchTimeZone__TimeZone]
=== switchTimeZone(TimeZone)

Convenience method for use with _org.apache.isis.applib.services.sudo.SudoService_ , returning a _UnaryOperator_ that will act upon the provided xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] to return the same but with the specified _TimeZone_ .

[#combine__UnaryOperator]
=== combine(UnaryOperator)

Convenience method to combine _UnaryOperator_ s, for example as per _#switchUser(UserMemento)_ and _#switchTimeZone(TimeZone)_ .

NOTE: this implementation can result in heap pollution; better to use the _#combine(Stream) overload_ .

[#combine__Stream]
=== combine(Stream)

Convenience method to combine _UnaryOperator_ s, for example as per _#switchUser(UserMemento)_ and _#switchTimeZone(TimeZone)_ . credit: https://stackoverflow.com/a/51065029/56880
