= InteractionLayerTracker _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Provides access to the current xref:refguide:applib:index/services/iactnlayer/InteractionLayer.adoc[InteractionLayer] .

== API

[source,java]
.InteractionLayerTracker.java
----
interface InteractionLayerTracker {
  Optional<InteractionLayer> currentInteractionLayer()     // <.>
  InteractionLayer currentInteractionLayerElseFail()
  Optional<InteractionContext> currentInteractionContext()     // <.>
  Optional<Interaction> currentInteraction()     // <.>
}
----

<.> xref:#currentInteractionLayer__[currentInteractionLayer()]
<.> xref:#currentInteractionContext__[currentInteractionContext()]
+
--
Returns the xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] wrapped by the _#currentInteractionLayer()_ (if within an xref:refguide:applib:index/services/iactnlayer/InteractionLayer.adoc[InteractionLayer] ).
--
<.> xref:#currentInteraction__[currentInteraction()]
+
--
Returns the xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] wrapped by the _#currentInteractionLayer()_ (if within an xref:refguide:applib:index/services/iactnlayer/InteractionLayer.adoc[InteractionLayer] ).
--

== Members

[#currentInteractionLayer__]
=== currentInteractionLayer()

[#currentInteractionContext__]
=== currentInteractionContext()

Returns the xref:refguide:applib:index/services/iactnlayer/InteractionContext.adoc[InteractionContext] wrapped by the _#currentInteractionLayer()_ (if within an xref:refguide:applib:index/services/iactnlayer/InteractionLayer.adoc[InteractionLayer] ).

[#currentInteraction__]
=== currentInteraction()

Returns the xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] wrapped by the _#currentInteractionLayer()_ (if within an xref:refguide:applib:index/services/iactnlayer/InteractionLayer.adoc[InteractionLayer] ).
