= Enabling Logging
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]

Sometimes you just need to see what is going on.
There are various ways in which logging can be enabled, here are the ones we tend to use.

* In Apache Isis +
+
Modify `WEB-INF/logging.properties` (a log4j config file)

* In DataNucleus +
+
As per the http://www.datanucleus.org/products/accessplatform/logging.html[DN logging page]

* In the JDBC Driver +
+
Configure `log4jdbc` JDBC rather than the vanilla driver (see `WEB-INF/persistor_datanucleus.properties`) and configure log4j logging (see `WEB-INF/logging.properties`).
There are examples of both in the xref:simpleapp:ROOT:about.adoc[SimpleApp archetype].

* In the database +
+
Details below.


Database logging can be configured:

* for HSQLDB +
+
by adding`;sqllog=3` to the end of the JDBC URL.

* for PostgreSQL: +
+
Can change `postgresql\9.2\data\postgresql.conf`; see link:http://www.postgresql.org/docs/9.2/static/runtime-config-logging.html[this article] for details.

* for MS SQL Server Logging: +
+
We like to use the excellent SQL Profiler tool.

