[[how-run-fixtures-on-app-startup]]
= How run fixtures on startup?
:notice: licensed to the apache software foundation (asf) under one or more contributor license agreements. see the notice file distributed with this work for additional information regarding copyright ownership. the asf licenses this file to you under the apache license, version 2.0 (the "license"); you may not use this file except in compliance with the license. you may obtain a copy of the license at. http://www.apache.org/licenses/license-2.0 . unless required by applicable law or agreed to in writing, software distributed under the license is distributed on an "as is" basis, without warranties or  conditions of any kind, either express or implied. see the license for the specific language governing permissions and limitations under the license.
include::_attributes.adoc[]
:page-partial:


From this link:http://isis.markmail.org/thread/g6amfj2eyf2xfjbr[thread] on the Apache Isis users mailing list:

* _my fixtures have grown into a couple of files the application needs to read in when it starts the first time (and possibly later on when the files content change).
What is the right way to do this?
Hook up into the webapp start?
Use events?_


The standard approach is to use xref:ext-fixtures:ROOT:about.adoc[fixture scripts].
These can be run in on start-up typically by being specified in the xref:refguide:applib-cm:classes/AppManifest-bootstrapping.adoc[`AppManifest`], see for example the xref:simpleapp:ROOT:about.adoc[SimpleApp archetype].

Alternatively just set `isis.fixtures` and `isis.persistor.datanucleus.install-fixtures` properties.

In terms of implementations, you might also want to check out the (non-ASF) link:https://platform.incode.org[Incode Platform^]'s excel module, by using `ExcelFixture` and overriding `ExcelFixtureRowHandler`.

An example can be found in this (non ASF) link:https://github.com/incodehq/contactapp[contactapp], see link:https://github.com/incodehq/contactapp/blob/master/backend/fixture/src/main/java/org/incode/eurocommercial/contactapp/fixture/scenarios/demo/ContactImport.java[`ContactRowHandler`].

