"Marks the field, argument, input field or enum value as deprecated"
directive @deprecated(
    "The reason for the deprecation"
    reason: String = "No longer supported"
  ) on FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE | INPUT_FIELD_DEFINITION

"Directs the executor to include this field or fragment only when the `if` argument is true"
directive @include(
    "Included when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Directs the executor to skip this field or fragment when the `if`'argument is true."
directive @skip(
    "Skipped when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Exposes a URL that specifies the behaviour of this scalar."
directive @specifiedBy(
    "The URL that specifies the behaviour of this scalar."
    url: String!
  ) on SCALAR

type Mutator_Meta_Data {
  disable: String
  hide: Boolean
  params: _Params_Meta_Data
  validate: String
}

type Param_Meta_Data {
  autocomplete(we_call_search_for_now: String): Boolean
  choices: String
  default: String
  optionality: Boolean
  validate(we_call_value_for_now: String): String
}

type Query {
  _gql_Query_lookup: _gql_Query_lookup
  gqltestdomain_GQLTestDomainMenu: gqltestdomain_GQLTestDomainMenu
  isis_applib_UserMenu: isis_applib_UserMenu
  isis_conf_ConfigurationMenu: isis_conf_ConfigurationMenu
  isis_security_LogoutMenu: isis_security_LogoutMenu
  numServices: Int
}

type _Params_Meta_Data {
  object_action_name: Param_Meta_Data
}

type _gql_Query_lookup {
  gqltestdomain_E1(id: ID!): gqltestdomain_E1
  gqltestdomain_E2(id: ID!): gqltestdomain_E2
}

type _gql__DomainObject_generic_collection {
  disable: String
  hide: Boolean
}

type _gql__DomainObject_generic_property {
  disable: String
  hide: Boolean
}

type _gql__DomainObject_generic_structure {
  actions: [String]
  collections: [String]
  layoutXml: String
  properties: [String]
}

type gqltestdomain_E1 {
  _gql_generic: gqltestdomain_E1__DomainObject_generic
  e2: gqltestdomain_E2
  logicalTypeName: String
  name: String!
  objectIdentifier: String
}

type gqltestdomain_E1__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: gqltestdomain_E1__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
  version: String
}

type gqltestdomain_E1__DomainObject_generic_properties {
  e2: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  name: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type gqltestdomain_E2 {
  _gql_generic: gqltestdomain_E2__DomainObject_generic
  _gql_mutations: gqltestdomain_E2__DomainObject_mutations
  e1: gqltestdomain_E1
  logicalTypeName: String
  name: String
  objectIdentifier: String
  otherE2List: [gqltestdomain_E2]
  otherEntities(name: String): [org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity]
  stringList: [String]
  zintList: [Int]
}

type gqltestdomain_E2__DomainObject_generic {
  actions: gqltestdomain_E2__DomainObject_generic_actions
  collections: gqltestdomain_E2__DomainObject_generic_collections
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: gqltestdomain_E2__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
  version: String
}

type gqltestdomain_E2__DomainObject_generic_actions {
  changeE1: gqltestdomain_E2__DomainObject_generic_actions_changeE1
  changeName: gqltestdomain_E2__DomainObject_generic_actions_changeName
  otherEntities: gqltestdomain_E2__DomainObject_generic_actions_otherEntities
  remove: gqltestdomain_E2__DomainObject_generic_actions_remove
  removeWithReason: gqltestdomain_E2__DomainObject_generic_actions_removeWithReason
}

type gqltestdomain_E2__DomainObject_generic_actions_changeE1 {
  disable: String
  hide: Boolean
  params: gqltestdomain_E2__DomainObject_generic_actions_changeE1_params
  validate: String
}

type gqltestdomain_E2__DomainObject_generic_actions_changeE1_params {
  e1: gqltestdomain_E2__DomainObject_generic_actions_changeE1_params_e1
}

type gqltestdomain_E2__DomainObject_generic_actions_changeE1_params_e1 {
  autocomplete(we_call_search_for_now: String): Boolean
  choices: String
  default: String
  optionality: Boolean
  validate(we_call_value_for_now: String): String
}

type gqltestdomain_E2__DomainObject_generic_actions_changeName {
  disable: String
  hide: Boolean
  params: gqltestdomain_E2__DomainObject_generic_actions_changeName_params
  validate: String
}

type gqltestdomain_E2__DomainObject_generic_actions_changeName_params {
  newName: gqltestdomain_E2__DomainObject_generic_actions_changeName_params_newName
}

type gqltestdomain_E2__DomainObject_generic_actions_changeName_params_newName {
  autocomplete(we_call_search_for_now: String): Boolean
  choices: String
  default: String
  optionality: Boolean
  validate(we_call_value_for_now: String): String
}

type gqltestdomain_E2__DomainObject_generic_actions_otherEntities {
  disable: String
  hide: Boolean
  params: gqltestdomain_E2__DomainObject_generic_actions_otherEntities_params
  validate: String
}

type gqltestdomain_E2__DomainObject_generic_actions_otherEntities_params {
  name: gqltestdomain_E2__DomainObject_generic_actions_otherEntities_params_name
}

type gqltestdomain_E2__DomainObject_generic_actions_otherEntities_params_name {
  autocomplete(we_call_search_for_now: String): Boolean
  choices: String
  default: String
  optionality: Boolean
  validate(we_call_value_for_now: String): String
}

type gqltestdomain_E2__DomainObject_generic_actions_remove {
  disable: String
  hide: Boolean
  validate: String
}

type gqltestdomain_E2__DomainObject_generic_actions_removeWithReason {
  disable: String
  hide: Boolean
  params: gqltestdomain_E2__DomainObject_generic_actions_removeWithReason_params
  validate: String
}

type gqltestdomain_E2__DomainObject_generic_actions_removeWithReason_params {
  reason: gqltestdomain_E2__DomainObject_generic_actions_removeWithReason_params_reason
}

type gqltestdomain_E2__DomainObject_generic_actions_removeWithReason_params_reason {
  autocomplete(we_call_search_for_now: String): Boolean
  choices: String
  default: String
  optionality: Boolean
  validate(we_call_value_for_now: String): String
}

type gqltestdomain_E2__DomainObject_generic_collections {
  otherE2List: _gql__DomainObject_generic_collection
  stringList: _gql__DomainObject_generic_collection
  zintList: _gql__DomainObject_generic_collection
}

type gqltestdomain_E2__DomainObject_generic_properties {
  e1: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  name: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type gqltestdomain_E2__DomainObject_mutations {
  changeE1(e1: _gql_input__gqltestdomain_E1!): gqltestdomain_E2
  changeName(newName: String!): gqltestdomain_E2
  remove: String
  removeWithReason(reason: String!): String
}

type gqltestdomain_GQLTestDomainMenu {
  createE1(e2: _gql_input__gqltestdomain_E2, name: String): gqltestdomain_E1
  findAllE1: [gqltestdomain_E1]
  findAllE2: [gqltestdomain_E2]
  findAllTestEntities: [org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity]
  findE2(name: String): gqltestdomain_E2
}

type isis_applib_ActionNode {
  _gql_generic: isis_applib_ActionNode__DomainObject_generic
  _gql_mutations: isis_applib_ActionNode__DomainObject_mutations
  action: String!
  logicalTypeName: String
  objectIdentifier: String
  parentNode: isis_applib_TypeNode!
}

type isis_applib_ActionNode__DomainObject_generic {
  actions: isis_applib_ActionNode__DomainObject_generic_actions
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_ActionNode__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_ActionNode__DomainObject_generic_actions {
  createTitle: isis_applib_ActionNode__DomainObject_generic_actions_createTitle
  streamChildNodes: isis_applib_ActionNode__DomainObject_generic_actions_streamChildNodes
}

type isis_applib_ActionNode__DomainObject_generic_actions_createTitle {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_ActionNode__DomainObject_generic_actions_streamChildNodes {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_ActionNode__DomainObject_generic_properties {
  action: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  parentNode: _gql__DomainObject_generic_property
}

type isis_applib_ActionNode__DomainObject_mutations {
  createTitle: String
  streamChildNodes: java_util_stream_Stream
}

type isis_applib_CollectionNode {
  _gql_generic: isis_applib_CollectionNode__DomainObject_generic
  _gql_mutations: isis_applib_CollectionNode__DomainObject_mutations
  collection: String!
  logicalTypeName: String
  objectIdentifier: String
}

type isis_applib_CollectionNode__DomainObject_generic {
  actions: isis_applib_CollectionNode__DomainObject_generic_actions
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_CollectionNode__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_CollectionNode__DomainObject_generic_actions {
  createTitle: isis_applib_CollectionNode__DomainObject_generic_actions_createTitle
  streamChildNodes: isis_applib_CollectionNode__DomainObject_generic_actions_streamChildNodes
}

type isis_applib_CollectionNode__DomainObject_generic_actions_createTitle {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_CollectionNode__DomainObject_generic_actions_streamChildNodes {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_CollectionNode__DomainObject_generic_properties {
  collection: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type isis_applib_CollectionNode__DomainObject_mutations {
  createTitle: String
  streamChildNodes: java_util_stream_Stream
}

type isis_applib_DomainObjectList {
  _gql_generic: isis_applib_DomainObjectList__DomainObject_generic
  actionArguments: String
  actionId: String
  actionOwningFqcn: String
  elementTypeFqcn: String!
  logicalTypeName: String
  objectIdentifier: String
  title: String!
}

type isis_applib_DomainObjectList__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_DomainObjectList__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_DomainObjectList__DomainObject_generic_properties {
  actionArguments: _gql__DomainObject_generic_property
  actionId: _gql__DomainObject_generic_property
  actionOwningFqcn: _gql__DomainObject_generic_property
  elementTypeFqcn: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  title: _gql__DomainObject_generic_property
}

type isis_applib_FacetAttrNode {
  _gql_generic: isis_applib_FacetAttrNode__DomainObject_generic
  _gql_mutations: isis_applib_FacetAttrNode__DomainObject_mutations
  facetAttr: String!
  logicalTypeName: String
  objectIdentifier: String
}

type isis_applib_FacetAttrNode__DomainObject_generic {
  actions: isis_applib_FacetAttrNode__DomainObject_generic_actions
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_FacetAttrNode__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_FacetAttrNode__DomainObject_generic_actions {
  createTitle: isis_applib_FacetAttrNode__DomainObject_generic_actions_createTitle
  streamChildNodes: isis_applib_FacetAttrNode__DomainObject_generic_actions_streamChildNodes
}

type isis_applib_FacetAttrNode__DomainObject_generic_actions_createTitle {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_FacetAttrNode__DomainObject_generic_actions_streamChildNodes {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_FacetAttrNode__DomainObject_generic_properties {
  facetAttr: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type isis_applib_FacetAttrNode__DomainObject_mutations {
  createTitle: String
  streamChildNodes: java_util_stream_Stream
}

type isis_applib_FacetGroupNode {
  _gql_generic: isis_applib_FacetGroupNode__DomainObject_generic
  _gql_mutations: isis_applib_FacetGroupNode__DomainObject_mutations
  facets: String!
  logicalTypeName: String
  objectIdentifier: String
}

type isis_applib_FacetGroupNode__DomainObject_generic {
  actions: isis_applib_FacetGroupNode__DomainObject_generic_actions
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_FacetGroupNode__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_FacetGroupNode__DomainObject_generic_actions {
  createTitle: isis_applib_FacetGroupNode__DomainObject_generic_actions_createTitle
  streamChildNodes: isis_applib_FacetGroupNode__DomainObject_generic_actions_streamChildNodes
}

type isis_applib_FacetGroupNode__DomainObject_generic_actions_createTitle {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_FacetGroupNode__DomainObject_generic_actions_streamChildNodes {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_FacetGroupNode__DomainObject_generic_properties {
  facets: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type isis_applib_FacetGroupNode__DomainObject_mutations {
  createTitle: String
  streamChildNodes: java_util_stream_Stream
}

type isis_applib_FacetNode {
  _gql_generic: isis_applib_FacetNode__DomainObject_generic
  _gql_mutations: isis_applib_FacetNode__DomainObject_mutations
  facet: String!
  logicalTypeName: String
  objectIdentifier: String
}

type isis_applib_FacetNode__DomainObject_generic {
  actions: isis_applib_FacetNode__DomainObject_generic_actions
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_FacetNode__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_FacetNode__DomainObject_generic_actions {
  createTitle: isis_applib_FacetNode__DomainObject_generic_actions_createTitle
  streamChildNodes: isis_applib_FacetNode__DomainObject_generic_actions_streamChildNodes
}

type isis_applib_FacetNode__DomainObject_generic_actions_createTitle {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_FacetNode__DomainObject_generic_actions_streamChildNodes {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_FacetNode__DomainObject_generic_properties {
  facet: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type isis_applib_FacetNode__DomainObject_mutations {
  createTitle: String
  streamChildNodes: java_util_stream_Stream
}

type isis_applib_ParameterNode {
  _gql_generic: isis_applib_ParameterNode__DomainObject_generic
  _gql_mutations: isis_applib_ParameterNode__DomainObject_mutations
  logicalTypeName: String
  objectIdentifier: String
  parameter: String!
}

type isis_applib_ParameterNode__DomainObject_generic {
  actions: isis_applib_ParameterNode__DomainObject_generic_actions
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_ParameterNode__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_ParameterNode__DomainObject_generic_actions {
  createTitle: isis_applib_ParameterNode__DomainObject_generic_actions_createTitle
  streamChildNodes: isis_applib_ParameterNode__DomainObject_generic_actions_streamChildNodes
}

type isis_applib_ParameterNode__DomainObject_generic_actions_createTitle {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_ParameterNode__DomainObject_generic_actions_streamChildNodes {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_ParameterNode__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  parameter: _gql__DomainObject_generic_property
}

type isis_applib_ParameterNode__DomainObject_mutations {
  createTitle: String
  streamChildNodes: java_util_stream_Stream
}

type isis_applib_PropertyNode {
  _gql_generic: isis_applib_PropertyNode__DomainObject_generic
  _gql_mutations: isis_applib_PropertyNode__DomainObject_mutations
  logicalTypeName: String
  objectIdentifier: String
  property: String!
}

type isis_applib_PropertyNode__DomainObject_generic {
  actions: isis_applib_PropertyNode__DomainObject_generic_actions
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_PropertyNode__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_PropertyNode__DomainObject_generic_actions {
  createTitle: isis_applib_PropertyNode__DomainObject_generic_actions_createTitle
  streamChildNodes: isis_applib_PropertyNode__DomainObject_generic_actions_streamChildNodes
}

type isis_applib_PropertyNode__DomainObject_generic_actions_createTitle {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_PropertyNode__DomainObject_generic_actions_streamChildNodes {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_PropertyNode__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  property: _gql__DomainObject_generic_property
}

type isis_applib_PropertyNode__DomainObject_mutations {
  createTitle: String
  streamChildNodes: java_util_stream_Stream
}

type isis_applib_RoleMemento {
  _gql_generic: isis_applib_RoleMemento__DomainObject_generic
  description: String!
  logicalTypeName: String
  name: String!
  objectIdentifier: String
}

type isis_applib_RoleMemento__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_RoleMemento__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_RoleMemento__DomainObject_generic_properties {
  description: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  name: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type isis_applib_TypeNode {
  _gql_generic: isis_applib_TypeNode__DomainObject_generic
  _gql_mutations: isis_applib_TypeNode__DomainObject_mutations
  domainClassDto: String!
  logicalTypeName: String
  objectIdentifier: String
}

type isis_applib_TypeNode__DomainObject_generic {
  actions: isis_applib_TypeNode__DomainObject_generic_actions
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_TypeNode__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_TypeNode__DomainObject_generic_actions {
  createTitle: isis_applib_TypeNode__DomainObject_generic_actions_createTitle
  streamChildNodes: isis_applib_TypeNode__DomainObject_generic_actions_streamChildNodes
}

type isis_applib_TypeNode__DomainObject_generic_actions_createTitle {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_TypeNode__DomainObject_generic_actions_streamChildNodes {
  disable: String
  hide: Boolean
  validate: String
}

type isis_applib_TypeNode__DomainObject_generic_properties {
  domainClassDto: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type isis_applib_TypeNode__DomainObject_mutations {
  createTitle: String
  streamChildNodes: java_util_stream_Stream
}

type isis_applib_UserMemento {
  _gql_generic: isis_applib_UserMemento__DomainObject_generic
  authenticationCode: String!
  authenticationSource: String!
  avatarUrl: String
  impersonating: String!
  languageLocale: String
  logicalTypeName: String
  multiTenancyToken: String
  name: String!
  numberFormatLocale: String
  objectIdentifier: String
  realName: String
  roles: [isis_applib_RoleMemento]
  timeFormatLocale: String
}

type isis_applib_UserMemento__DomainObject_generic {
  collections: isis_applib_UserMemento__DomainObject_generic_collections
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_applib_UserMemento__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_applib_UserMemento__DomainObject_generic_collections {
  roles: _gql__DomainObject_generic_collection
}

type isis_applib_UserMemento__DomainObject_generic_properties {
  authenticationCode: _gql__DomainObject_generic_property
  authenticationSource: _gql__DomainObject_generic_property
  avatarUrl: _gql__DomainObject_generic_property
  impersonating: _gql__DomainObject_generic_property
  languageLocale: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  multiTenancyToken: _gql__DomainObject_generic_property
  name: _gql__DomainObject_generic_property
  numberFormatLocale: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  realName: _gql__DomainObject_generic_property
  timeFormatLocale: _gql__DomainObject_generic_property
}

type isis_applib_UserMenu {
  me: isis_applib_UserMemento
}

type isis_conf_ConfigurationMenu {
  configuration: isis_conf_ConfigurationViewmodel
}

type isis_conf_ConfigurationProperty {
  _gql_generic: isis_conf_ConfigurationProperty__DomainObject_generic
  key: String!
  logicalTypeName: String
  objectIdentifier: String
  value: String!
}

type isis_conf_ConfigurationProperty__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_conf_ConfigurationProperty__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_conf_ConfigurationProperty__DomainObject_generic_properties {
  key: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  value: _gql__DomainObject_generic_property
}

type isis_conf_ConfigurationViewmodel {
  _gql_generic: isis_conf_ConfigurationViewmodel__DomainObject_generic
  configuration: [isis_conf_ConfigurationProperty]
  environment: [isis_conf_ConfigurationProperty]
  logicalTypeName: String
  objectIdentifier: String
}

type isis_conf_ConfigurationViewmodel__DomainObject_generic {
  collections: isis_conf_ConfigurationViewmodel__DomainObject_generic_collections
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_conf_ConfigurationViewmodel__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_conf_ConfigurationViewmodel__DomainObject_generic_collections {
  configuration: _gql__DomainObject_generic_collection
  environment: _gql__DomainObject_generic_collection
}

type isis_conf_ConfigurationViewmodel__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type isis_feat_ApplicationFeatureViewModel {
  _gql_generic: isis_feat_ApplicationFeatureViewModel__DomainObject_generic
  logicalTypeName: String
  memberName: String!
  namespaceName: String!
  objectIdentifier: String
  typeSimpleName: String!
}

type isis_feat_ApplicationFeatureViewModel__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_feat_ApplicationFeatureViewModel__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_feat_ApplicationFeatureViewModel__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  memberName: _gql__DomainObject_generic_property
  namespaceName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  typeSimpleName: _gql__DomainObject_generic_property
}

type isis_feat_ApplicationNamespace {
  _gql_generic: isis_feat_ApplicationNamespace__DomainObject_generic
  logicalTypeName: String
  memberName: String!
  namespaceName: String!
  objectIdentifier: String
  typeSimpleName: String!
}

type isis_feat_ApplicationNamespace__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_feat_ApplicationNamespace__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_feat_ApplicationNamespace__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  memberName: _gql__DomainObject_generic_property
  namespaceName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  typeSimpleName: _gql__DomainObject_generic_property
}

type isis_feat_ApplicationType {
  _gql_generic: isis_feat_ApplicationType__DomainObject_generic
  actions: [isis_feat_ApplicationTypeAction]
  collections: [isis_feat_ApplicationTypeCollection]
  logicalTypeName: String
  memberName: String!
  namespaceName: String!
  objectIdentifier: String
  properties: [isis_feat_ApplicationTypeProperty]
  typeSimpleName: String!
}

type isis_feat_ApplicationTypeAction {
  _gql_generic: isis_feat_ApplicationTypeAction__DomainObject_generic
  actionSemantics: String!
  logicalTypeName: String
  memberName: String!
  namespaceName: String!
  objectIdentifier: String
  returnType: String!
  typeSimpleName: String!
}

type isis_feat_ApplicationTypeAction__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_feat_ApplicationTypeAction__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_feat_ApplicationTypeAction__DomainObject_generic_properties {
  actionSemantics: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  memberName: _gql__DomainObject_generic_property
  namespaceName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  returnType: _gql__DomainObject_generic_property
  typeSimpleName: _gql__DomainObject_generic_property
}

type isis_feat_ApplicationTypeCollection {
  _gql_generic: isis_feat_ApplicationTypeCollection__DomainObject_generic
  derived: String!
  elementType: String!
  logicalTypeName: String
  memberName: String!
  namespaceName: String!
  objectIdentifier: String
  typeSimpleName: String!
}

type isis_feat_ApplicationTypeCollection__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_feat_ApplicationTypeCollection__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_feat_ApplicationTypeCollection__DomainObject_generic_properties {
  derived: _gql__DomainObject_generic_property
  elementType: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  memberName: _gql__DomainObject_generic_property
  namespaceName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  typeSimpleName: _gql__DomainObject_generic_property
}

type isis_feat_ApplicationTypeMember {
  _gql_generic: isis_feat_ApplicationTypeMember__DomainObject_generic
  logicalTypeName: String
  memberName: String!
  namespaceName: String!
  objectIdentifier: String
  typeSimpleName: String!
}

type isis_feat_ApplicationTypeMember__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_feat_ApplicationTypeMember__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_feat_ApplicationTypeMember__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  memberName: _gql__DomainObject_generic_property
  namespaceName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  typeSimpleName: _gql__DomainObject_generic_property
}

type isis_feat_ApplicationTypeProperty {
  _gql_generic: isis_feat_ApplicationTypeProperty__DomainObject_generic
  derived: String!
  logicalTypeName: String
  maxLength: String
  memberName: String!
  namespaceName: String!
  objectIdentifier: String
  returnType: String!
  typeSimpleName: String!
  typicalLength: String
}

type isis_feat_ApplicationTypeProperty__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_feat_ApplicationTypeProperty__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_feat_ApplicationTypeProperty__DomainObject_generic_properties {
  derived: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  maxLength: _gql__DomainObject_generic_property
  memberName: _gql__DomainObject_generic_property
  namespaceName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  returnType: _gql__DomainObject_generic_property
  typeSimpleName: _gql__DomainObject_generic_property
  typicalLength: _gql__DomainObject_generic_property
}

type isis_feat_ApplicationType__DomainObject_generic {
  collections: isis_feat_ApplicationType__DomainObject_generic_collections
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_feat_ApplicationType__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_feat_ApplicationType__DomainObject_generic_collections {
  actions: _gql__DomainObject_generic_collection
  collections: _gql__DomainObject_generic_collection
  properties: _gql__DomainObject_generic_collection
}

type isis_feat_ApplicationType__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  memberName: _gql__DomainObject_generic_property
  namespaceName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  typeSimpleName: _gql__DomainObject_generic_property
}

type isis_security_LoginRedirect {
  _gql_generic: isis_security_LoginRedirect__DomainObject_generic
  logicalTypeName: String
  objectIdentifier: String
}

type isis_security_LoginRedirect__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_security_LoginRedirect__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_security_LoginRedirect__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type isis_security_LogoutMenu {
  logout: String
}

type isis_testing_fixtures_FixtureResult {
  _gql_generic: isis_testing_fixtures_FixtureResult__DomainObject_generic
  className: String!
  fixtureScriptClassName: String
  key: String!
  logicalTypeName: String
  objectIdentifier: String
}

type isis_testing_fixtures_FixtureResult__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: isis_testing_fixtures_FixtureResult__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type isis_testing_fixtures_FixtureResult__DomainObject_generic_properties {
  className: _gql__DomainObject_generic_property
  fixtureScriptClassName: _gql__DomainObject_generic_property
  key: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type java_util_SortedMap {
  _gql_generic: java_util_SortedMap__DomainObject_generic
  logicalTypeName: String
  objectIdentifier: String
}

type java_util_SortedMap__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: java_util_SortedMap__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type java_util_SortedMap__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type java_util_stream_Stream {
  _gql_generic: java_util_stream_Stream__DomainObject_generic
  logicalTypeName: String
  objectIdentifier: String
}

type java_util_stream_Stream__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: java_util_stream_Stream__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type java_util_stream_Stream__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type org_apache_isis_core_metamodel_inspect_model_MMNode {
  _gql_generic: org_apache_isis_core_metamodel_inspect_model_MMNode__DomainObject_generic
  logicalTypeName: String
  objectIdentifier: String
}

type org_apache_isis_core_metamodel_inspect_model_MMNode__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: org_apache_isis_core_metamodel_inspect_model_MMNode__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type org_apache_isis_core_metamodel_inspect_model_MMNode__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript {
  _gql_generic: org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript__DomainObject_generic
  friendlyName: String!
  logicalTypeName: String
  objectIdentifier: String
  qualifiedName: String!
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript__DomainObject_generic_properties {
  friendlyName: _gql__DomainObject_generic_property
  logicalTypeName: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
  qualifiedName: _gql__DomainObject_generic_property
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity {
  _gql_generic: org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity__DomainObject_generic
  logicalTypeName: String
  name: String!
  objectIdentifier: String
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity__DomainObject_generic {
  iconName: String
  id: ID!
  logicalTypeName: String!
  properties: org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity__DomainObject_generic_properties
  structure: _gql__DomainObject_generic_structure!
  title: String
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity__DomainObject_generic_properties {
  logicalTypeName: _gql__DomainObject_generic_property
  name: _gql__DomainObject_generic_property
  objectIdentifier: _gql__DomainObject_generic_property
}

input _gql_input__gqltestdomain_E1 {
  id: ID!
}

input _gql_input__gqltestdomain_E2 {
  id: ID!
}

input _gql_input__isis_applib_ActionNode {
  id: ID!
}

input _gql_input__isis_applib_CollectionNode {
  id: ID!
}

input _gql_input__isis_applib_DomainObjectList {
  id: ID!
}

input _gql_input__isis_applib_FacetAttrNode {
  id: ID!
}

input _gql_input__isis_applib_FacetGroupNode {
  id: ID!
}

input _gql_input__isis_applib_FacetNode {
  id: ID!
}

input _gql_input__isis_applib_ParameterNode {
  id: ID!
}

input _gql_input__isis_applib_PropertyNode {
  id: ID!
}

input _gql_input__isis_applib_RoleMemento {
  id: ID!
}

input _gql_input__isis_applib_TypeNode {
  id: ID!
}

input _gql_input__isis_applib_UserMemento {
  id: ID!
}

input _gql_input__isis_conf_ConfigurationProperty {
  id: ID!
}

input _gql_input__isis_conf_ConfigurationViewmodel {
  id: ID!
}

input _gql_input__isis_feat_ApplicationFeatureViewModel {
  id: ID!
}

input _gql_input__isis_feat_ApplicationNamespace {
  id: ID!
}

input _gql_input__isis_feat_ApplicationType {
  id: ID!
}

input _gql_input__isis_feat_ApplicationTypeAction {
  id: ID!
}

input _gql_input__isis_feat_ApplicationTypeCollection {
  id: ID!
}

input _gql_input__isis_feat_ApplicationTypeMember {
  id: ID!
}

input _gql_input__isis_feat_ApplicationTypeProperty {
  id: ID!
}

input _gql_input__isis_security_LoginRedirect {
  id: ID!
}

input _gql_input__isis_testing_fixtures_FixtureResult {
  id: ID!
}

input _gql_input__java_util_SortedMap {
  id: ID!
}

input _gql_input__java_util_stream_Stream {
  id: ID!
}

input _gql_input__org_apache_isis_core_metamodel_inspect_model_MMNode {
  id: ID!
}

input _gql_input__org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript {
  id: ID!
}

input _gql_input__org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity {
  id: ID!
}
olean
  validate: String
}

type isis_feat_ApplicationType_objectIdentifier__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type isis_feat_ApplicationType_typeSimpleName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type isis_security_LoginRedirect {
  _gql_meta: isis_security_LoginRedirect__DomainObject_meta
  logicalTypeName: String
  objectIdentifier: String
}

type isis_security_LoginRedirect__DomainObject_fields {
  logicalTypeName: isis_security_LoginRedirect_logicalTypeName__Field_metadata
  objectIdentifier: isis_security_LoginRedirect_objectIdentifier__Field_metadata
}

type isis_security_LoginRedirect__DomainObject_meta {
  fields: isis_security_LoginRedirect__DomainObject_fields
  iconName: String
  id: ID!
  logicalTypeName: String!
  title: String
}

type isis_security_LoginRedirect__DomainObject_mutations {
  noop: Mutator_Meta_Data
}

type isis_security_LoginRedirect_logicalTypeName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type isis_security_LoginRedirect_objectIdentifier__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type isis_security_LogoutMenu {
  logout: String
}

type isis_testing_fixtures_FixtureResult {
  _gql_meta: isis_testing_fixtures_FixtureResult__DomainObject_meta
  className: String!
  fixtureScriptClassName: String
  key: String!
  logicalTypeName: String
  objectIdentifier: String
}

type isis_testing_fixtures_FixtureResult__DomainObject_fields {
  className: isis_testing_fixtures_FixtureResult_className__Field_metadata
  fixtureScriptClassName: isis_testing_fixtures_FixtureResult_fixtureScriptClassName__Field_metadata
  key: isis_testing_fixtures_FixtureResult_key__Field_metadata
  logicalTypeName: isis_testing_fixtures_FixtureResult_logicalTypeName__Field_metadata
  objectIdentifier: isis_testing_fixtures_FixtureResult_objectIdentifier__Field_metadata
}

type isis_testing_fixtures_FixtureResult__DomainObject_meta {
  fields: isis_testing_fixtures_FixtureResult__DomainObject_fields
  iconName: String
  id: ID!
  logicalTypeName: String!
  title: String
}

type isis_testing_fixtures_FixtureResult__DomainObject_mutations {
  noop: Mutator_Meta_Data
}

type isis_testing_fixtures_FixtureResult_className__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type isis_testing_fixtures_FixtureResult_fixtureScriptClassName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type isis_testing_fixtures_FixtureResult_key__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type isis_testing_fixtures_FixtureResult_logicalTypeName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type isis_testing_fixtures_FixtureResult_objectIdentifier__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type java_util_SortedMap {
  _gql_meta: java_util_SortedMap__DomainObject_meta
  logicalTypeName: String
  objectIdentifier: String
}

type java_util_SortedMap__DomainObject_fields {
  logicalTypeName: java_util_SortedMap_logicalTypeName__Field_metadata
  objectIdentifier: java_util_SortedMap_objectIdentifier__Field_metadata
}

type java_util_SortedMap__DomainObject_meta {
  fields: java_util_SortedMap__DomainObject_fields
  iconName: String
  id: ID!
  logicalTypeName: String!
  title: String
}

type java_util_SortedMap__DomainObject_mutations {
  noop: Mutator_Meta_Data
}

type java_util_SortedMap_logicalTypeName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type java_util_SortedMap_objectIdentifier__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type java_util_stream_Stream {
  _gql_meta: java_util_stream_Stream__DomainObject_meta
  logicalTypeName: String
  objectIdentifier: String
}

type java_util_stream_Stream__DomainObject_fields {
  logicalTypeName: java_util_stream_Stream_logicalTypeName__Field_metadata
  objectIdentifier: java_util_stream_Stream_objectIdentifier__Field_metadata
}

type java_util_stream_Stream__DomainObject_meta {
  fields: java_util_stream_Stream__DomainObject_fields
  iconName: String
  id: ID!
  logicalTypeName: String!
  title: String
}

type java_util_stream_Stream__DomainObject_mutations {
  noop: Mutator_Meta_Data
}

type java_util_stream_Stream_logicalTypeName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type java_util_stream_Stream_objectIdentifier__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type org_apache_isis_core_metamodel_inspect_model_MMNode {
  _gql_meta: org_apache_isis_core_metamodel_inspect_model_MMNode__DomainObject_meta
  logicalTypeName: String
  objectIdentifier: String
}

type org_apache_isis_core_metamodel_inspect_model_MMNode__DomainObject_fields {
  logicalTypeName: org_apache_isis_core_metamodel_inspect_model_MMNode_logicalTypeName__Field_metadata
  objectIdentifier: org_apache_isis_core_metamodel_inspect_model_MMNode_objectIdentifier__Field_metadata
}

type org_apache_isis_core_metamodel_inspect_model_MMNode__DomainObject_meta {
  fields: org_apache_isis_core_metamodel_inspect_model_MMNode__DomainObject_fields
  iconName: String
  id: ID!
  logicalTypeName: String!
  title: String
}

type org_apache_isis_core_metamodel_inspect_model_MMNode__DomainObject_mutations {
  noop: Mutator_Meta_Data
}

type org_apache_isis_core_metamodel_inspect_model_MMNode_logicalTypeName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type org_apache_isis_core_metamodel_inspect_model_MMNode_objectIdentifier__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript {
  _gql_meta: org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript__DomainObject_meta
  friendlyName: String!
  logicalTypeName: String
  objectIdentifier: String
  qualifiedName: String!
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript__DomainObject_fields {
  friendlyName: org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript_friendlyName__Field_metadata
  logicalTypeName: org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript_logicalTypeName__Field_metadata
  objectIdentifier: org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript_objectIdentifier__Field_metadata
  qualifiedName: org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript_qualifiedName__Field_metadata
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript__DomainObject_meta {
  fields: org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript__DomainObject_fields
  iconName: String
  id: ID!
  logicalTypeName: String!
  title: String
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript__DomainObject_mutations {
  noop: Mutator_Meta_Data
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript_friendlyName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript_logicalTypeName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript_objectIdentifier__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript_qualifiedName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity {
  _gql_meta: org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity__DomainObject_meta
  logicalTypeName: String
  name: String!
  objectIdentifier: String
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity__DomainObject_fields {
  logicalTypeName: org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity_logicalTypeName__Field_metadata
  name: org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity_name__Field_metadata
  objectIdentifier: org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity_objectIdentifier__Field_metadata
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity__DomainObject_meta {
  fields: org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity__DomainObject_fields
  iconName: String
  id: ID!
  logicalTypeName: String!
  title: String
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity__DomainObject_mutations {
  noop: Mutator_Meta_Data
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity_logicalTypeName__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity_name__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

type org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity_objectIdentifier__Field_metadata {
  disable: String
  hide: Boolean
  validate: String
}

input _gql_input__gqltestdomain_E1 {
  id: ID!
}

input _gql_input__gqltestdomain_E2 {
  id: ID!
}

input _gql_input__isis_applib_ActionNode {
  id: ID!
}

input _gql_input__isis_applib_CollectionNode {
  id: ID!
}

input _gql_input__isis_applib_DomainObjectList {
  id: ID!
}

input _gql_input__isis_applib_FacetAttrNode {
  id: ID!
}

input _gql_input__isis_applib_FacetGroupNode {
  id: ID!
}

input _gql_input__isis_applib_FacetNode {
  id: ID!
}

input _gql_input__isis_applib_ParameterNode {
  id: ID!
}

input _gql_input__isis_applib_PropertyNode {
  id: ID!
}

input _gql_input__isis_applib_RoleMemento {
  id: ID!
}

input _gql_input__isis_applib_TypeNode {
  id: ID!
}

input _gql_input__isis_applib_UserMemento {
  id: ID!
}

input _gql_input__isis_conf_ConfigurationProperty {
  id: ID!
}

input _gql_input__isis_conf_ConfigurationViewmodel {
  id: ID!
}

input _gql_input__isis_feat_ApplicationFeatureViewModel {
  id: ID!
}

input _gql_input__isis_feat_ApplicationNamespace {
  id: ID!
}

input _gql_input__isis_feat_ApplicationType {
  id: ID!
}

input _gql_input__isis_feat_ApplicationTypeAction {
  id: ID!
}

input _gql_input__isis_feat_ApplicationTypeCollection {
  id: ID!
}

input _gql_input__isis_feat_ApplicationTypeMember {
  id: ID!
}

input _gql_input__isis_feat_ApplicationTypeProperty {
  id: ID!
}

input _gql_input__isis_security_LoginRedirect {
  id: ID!
}

input _gql_input__isis_testing_fixtures_FixtureResult {
  id: ID!
}

input _gql_input__java_util_SortedMap {
  id: ID!
}

input _gql_input__java_util_stream_Stream {
  id: ID!
}

input _gql_input__org_apache_isis_core_metamodel_inspect_model_MMNode {
  id: ID!
}

input _gql_input__org_apache_isis_testing_fixtures_applib_fixturescripts_FixtureScript {
  id: ID!
}

input _gql_input__org_apache_isis_viewer_graphql_viewer_source_gqltestdomain_TestEntity {
  id: ID!
}
