[[_rgcfg_configuring-core]]
= Configuring Core
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/

This section lists the core/runtime configuration properties recognized by Apache Isis.

[NOTE]
====
Configuration properties for the JDO/DataNucleus objectstore can be found in the xref:../ugodn/ugodn.adoc#_ugodn_configuring[Configuring DataNucleus] section later in this chapter, while configuration properties for the viewers can be found in the their respective chapters, xref:../ugvw/ugvw.adoc#_ugvw_configuration-properties[here for Wicket viewer], and xref:../ugvro/ugvro.adoc#_ugvro_configuration-properties[here for the Restful Objects viewer].
====


[[__rgcfg_configuring-core_domain-events]]
== Domain Events

.Core Configuration Properties for Domain Events
[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(default value)
|Description


|`isis.reflector.facet.` +
`actionAnnotation.` +
`domainEvent.postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-Action_domainEvent[`@Action#domainEvent()`] is not specified (is set to `ActionDomainEvent.Default`).

|`isis.reflector.facet.` +
`collectionAnnotation.` +
`domainEvent.postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-Collection_domainEvent[`@Collection#domainEvent()`] is not specified (is set to `CollectionDomainEvent.Default`).

|`isis.reflector.facet.` +
`propertyAnnotation.` +
`domainEvent.postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-Property_domainEvent[`@Property#domainEvent()`] is not specified (is set to `PropertyDomainEvent.Default`).



|===


[[__rgcfg_configuring-core_lifecycle-events]]
== Lifecycle Events



.Core Configuration Properties for Lifecycle Events
[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(default value)
|Description


|`isis.reflector.facet.` +
`domainObjectAnnotation.` +
`createdLifecycleEvent.` +
`postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObject_createdLifecycleEvent[`@DomainObject#createdLifecycleEvent()`] is not specified (is set to `ObjectCreatedEvent.Default`).

|`isis.reflector.facet.` +
`domainObjectAnnotation.` +
`loadedLifecycleEvent.` +
`postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObject_loadedLifecycleEvent[`@DomainObject#loadedLifecycleEvent()`] is not specified (is set to `ObjectLoadedEvent.Default`).

|`isis.reflector.facet.` +
`domainObjectAnnotation.` +
`persistingLifecycleEvent.` +
`postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObject_persistingLifecycleEvent[`@DomainObject#persistingLifecycleEvent()`] is not specified (is set to `ObjectPersistingEvent.Default`).

|`isis.reflector.facet.` +
`domainObjectAnnotation.` +
`persistedLifecycleEvent.` +
`postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObject_persistedLifecycleEvent[`@DomainObject#persistedLifecycleEvent()`] is not specified (is set to `ObjectPersistedEvent.Default`).

|`isis.reflector.facet.` +
`domainObjectAnnotation.` +
`removingLifecycleEvent.` +
`postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObject_removingLifecycleEvent[`@DomainObject#removingLifecycleEvent()`] is not specified (is set to `ObjectRemovingEvent.Default`).

|`isis.reflector.facet.` +
`domainObjectAnnotation.` +
`updatingLifecycleEvent.` +
`postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObject_updatingLifecycleEvent[`@DomainObject#updatingLifecycleEvent()`] is not specified (is set to `ObjectUpdatingEvent.Default`).

|`isis.reflector.facet.` +
`domainObjectAnnotation.` +
`updatedLifecycleEvent.` +
`postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObject_updatedLifecycleEvent[`@DomainObject#updatedLifecycleEvent()`] is not specified (is set to `ObjectUpdatedEvent.Default`).



|===




[[__rgcfg_configuring-core_ui-events]]
== UI Events


.Core Configuration Properties for UI Events
[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(default value)
|Description


|`isis.reflector.facet.` +
`domainObjectLayoutAnnotation.` +
`cssClassUiEvent.postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObjectLayout_cssClassUiEvent[`@DomainObjectLayout#cssClassUiEvent()`] is not specified (is set to `CssClassUiEvent.Default`).

|`isis.reflector.facet.` +
`domainObjectLayoutAnnotation.` +
`iconUiEvent.postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObjectLayout_iconUiEvent[`@DomainObjectLayout#iconUiEvent()`] is not specified (is set to `IconUiEvent.Default`).

|`isis.reflector.facet.` +
`domainObjectLayoutAnnotation.` +
`titleUiEvent.postForDefault`
|`true`,`false` +
(`true`)
|Whether an event should be posted if xref:../rgant/rgant.adoc#_rgant-DomainObjectLayout_titleUiEvent[`@DomainObjectLayout#titleUiEvent()`] is not specified (is set to `TitleUiEvent.Default`).



|===




[[__rgcfg_configuring-core_services]]
== Services


.Core Configuration Properties for Services
[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(default value)
|Description


|`isis.services`
|`FQCN`,`FQCN2`,...
|Fully qualified class names of classes to be instantiated as domain services.  +

Each entry can be optionally prefixed by "n:" specifying the relative order on the menu (corresponds to xref:../rgant/rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`]).

This property is IGNORED if the xref:../rgcfg/rgcfg.adoc#_rgcfg_configuring-components[`isis.appManifest`] configuration property is specified, or if an xref:../rgcms/rgcms.adoc#_rgcms_classes_super_AppManifest[`AppManifest`] is provided programmatically.


|`isis.services.` +
`applicationFeatures.` +
`init`
| `lazy`, `eager` +
(`lazy`)
|Whether the application features repository (which surfaces the framework's metamodel) should be
initialized lazily or eagerly.  +

Lazy initialization can speed up bootstrapping, useful while developing and running tests.  The default prior to `1.13.0` was eager initialization.


|`isis.services.` +
`audit.` +
`objects`
| `all`, `none` +
(`all`)
|Whether the changed properties of objects should be automatically audited (for objects annotated with xref:../rgant/rgant.adoc#_rgant-DomainObject_auditing[`@DomainObject(auditing=Auditing.AS_CONFIGURED)`].


|`isis.services.` +
`command.` +
`actions`
| `all`, `ignoreSafe`, `none` (`all`)
|Whether action invocations should be automatically reified into commands (for actions annotated with xref:../rgant/rgant.adoc#_rgant-Action_command[`@Action(command=CommandReification.AS_CONFIGURED)`].  +

`ignoreQueryOnly` is an alias for `ignoreSafe`.

|`isis.services.` +
`command.` +
`properties`
| `all`, `none` (`all`)
|(Whether property edits should be automatically reified into commands (for properties annotated with xref:../rgant/rgant.adoc#_rgant-Property_command[`@Property(command=CommandReification.AS_CONFIGURED)`].  +


|`isis.services.` +
`container.` +
`disableAutoFlush`
|`true`,`false` +
(`false`)
|Whether the `DomainObjectContainer` should automatically flush pending changes prior to querying (via `allMatches()`, `firstMatch()` and so on).



|`isis.services.` +
`ContentNegotiation-` +
`ServiceXRoDomainType` +
.`prettyPrint`
| `true`,`false` +
(depends)
|If a domain object has been mapped to the specified JAXB `x-ro-domain-type`, then determines whether the result is pretty-printed or not. +

If no configuration property is available, then the defaults is determined by the xref:../rgcfg/rgcfg.adoc#_rgcfg_deployment-types[deployment type]: production mode disables pretty printing, while prototype mode enables it.



| `isis.service.` +
`email.` +
`override.bcc` +
| email address
|intended to simplify testing, if specified then the email's `bcc` address will be that specified (rather than the email address(es) passed in as an argument to `EmailService#send(...)`).  +

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)


| `isis.service.` +
`email.` +
`override.cc` +
| email address
|intended to simplify testing, if specified then the email's `cc` address will be that specified (rather than the email address(es) passed in as an argument to `EmailService#send(...)`).  +

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)


| `isis.service.` +
`email.` +
`override.to` +
| email address
|intended to simplify testing, if specified then the email's `to` address will be that specified (rather than the email address(es) passed in as an argument to `EmailService#send(...)`).  +

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)



| `isis.service.` +
`email.` +
`port` +
| port number (`_587_`)
|The port number for the SMTP service on the the external SMTP host (used by xref:../rgsvc/rgsvc.adoc#_rgsvc_integration-api_EmailService[`EmailService`]).  +

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)


| `isis.service.` +
`email.` +
`sender.address` +
| email address
|The email address to use for sending out email (used by xref:../rgsvc/rgsvc.adoc#_rgsvc_integration-api_EmailService[`EmailService`]).
*Mandatory*.  +

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)


| `isis.service.` +
`email.` +
`sender.hostname` +
| host (`_smtp.gmail.com_`)
|The hostname of the external SMTP provider (used by xref:../rgsvc/rgsvc.adoc#_rgsvc_integration-api_EmailService[`EmailService`]).  +

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)


| `isis.service.` +
`email.` +
`sender.password` +
| email password
|The corresponding password for the email address to use for sending out email (used by xref:../rgsvc/rgsvc.adoc#_rgsvc_integration-api_EmailService[`EmailService`]).
*Mandatory*.  +

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)


| `isis.service.` +
`email.` +
`socket` +
`ConnectionTimeout`
|milliseconds +
(2000)
|The socket connection timeout

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)


| `isis.service.` +
`email.` +
`socketTimeout`
|milliseconds +
(2000)
|The socket timeout

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)



| `isis.service.` +
`email.` +
`throwExceptionOnFail`
|`true`,`false` +
(`true`)
|Whether to throw an exception if there the email cannot be sent (probably because of some misconfiguration).

This behaviour is (now) the default; the old behaviour (of just returning `false` from the `send()` method) can be re-enabled by setting this property to `false`.

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)


| `isis.service.` +
`email.` +
`tls.enabled`
|`true`,`false` +
(`true`)
|Whether to enable TLS for the email SMTP connection (used by xref:../rgsvc/rgsvc.adoc#_rgsvc_integration-api_EmailService[`EmailService`]).  +

NB: note that the key is mis-spelt, (`isis.service.email` rather than `isis.services.email`)


| `isis.services.` +
`eventbus.` +
`implementation` +
| `guava`, `axon`, +
FQCN (`_guava_`)
|which implementation to use by the xref:../rgsvc/rgsvc.adoc#_rgsvc_core-domain-api_EventBusService[`EventBusService`] as the underlying event bus.

| `isis.services.` +
`eventbus.` +
`allowLate` +
`Registration` +
|`true`,`false` +
(`false`)
|whether a domain service can register with the xref:../rgsvc/rgsvc.adoc#_rgsvc_core-domain-api_EventBusService[`EventBusService`] after any events have posted. +

Since this almost certainly constitutes a bug in application code, by default this is disallowed.


| `isis.services.` +
`exceprecog.` +
`logRecognized` +
`Exceptions` +
|`true`,`false` +
(`false`)
|whether recognized exceptions should also be logged. +

Generally a recognized exception is one that is expected (for example a uniqueness constraint violated in the database) and which does not represent an error condition.
This property logs the exception anyway, useful for debugging.


| `isis.services.` +
`ExceptionRecognizer` +
`CompositeFor` +
`JdoObjectStore.` +
`disable` +
|`true`,`false` +
(`false`)
|whether to disable the default recognizers registered by `ExceptionRecognizerCompositeForJdoObjectStore`. +

This implementation provides a default set of recognizers to convert RDBMS constraints into user-friendly messages.
In the (probably remote) chance that this functionality isn't required, they can be disabled through this flag.


|`isis.services.` +
`injector.` +
`injectPrefix`
| `true`,`false`  +
(`false`)
|(Whether the framework should support `inject...()` as a prefix for injecting domain services into other domain objects.
+
By default this is disabled.
The default prior to `1.13.0` was enabled.
If the setting is left as disabled then this may reduce application start-up times.


|`isis.services.` +
`injector.` +
`setPrefix`
| `true`,`false`  +
(`true`)
|Whether the framework should support `set...()` as a prefix for injecting domain services into other domain objects.
+
By default this is enabled (no change in `1.13.0`).
If the setting is changed to disabled then this may reduce application start-up times.


|`isis.services.` +
`publish.` +
`objects`
| `all`, `none` +
(`all`)
|Whether changed objects should be automatically published (for objects annotated with xref:../rgant/rgant.adoc#_rgant-DomainObject_publishing[`@DomainObject(publishing=Publishing.AS_CONFIGURED)`].


|`isis.services.` +
`publish.` +
`actions`
| `all`, `ignoreSafe`, `none` (`none`)
|Whether actions should be automatically published (for actions annotated with xref:../rgant/rgant.adoc#_rgant-Action_publishing[`@Action(publishing=Publishing.AS_CONFIGURED)`]. +

|`isis.services.` +
`publish.` +
`properties`
| `all`, `none` (`none`)
|Whether properties should be automatically published (for properties annotated with xref:../rgant/rgant.adoc#_rgant-Action_publishing[`@Property(publishing=Publishing.AS_CONFIGURED)`]. +


|`isis.services.` +
`ServicesInstaller` +
`FromAnnotation.` +
`packagePrefix`
|fully qualified package names (CSV)
|to search for domain services (including all subpackages).

This property is IGNORED if the xref:../rgcfg/rgcfg.adoc#_rgcfg_configuring-components[`isis.appManifest`] configuration property is specified, or if an xref:../rgcms/rgcms.adoc#_rgcms_classes_super_AppManifest[`AppManifest`] is provided programmatically.


|`isis.services.` +
`translation.` +
`po.mode`
| `read`,`write`
|Whether to force the `TranslationService` into either read or write mode. +

See xref:../ugbtb/ugbtb.adoc#_ugbtb_i18n[i18n support] to learn more about the translation service.


|===



[[__rgcfg_configuring-core_metamodel-validation]]
== MetaModel Validation


.Metamodel Validation
[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(default value)
|Description

|`isis.reflector.validator`
|`FQCN`
|Custom implementation of `MetaModelValidator` (in the `org.apache.isis.core.metamodel.specloader.validator` package) +

See xref:../ugbtb/ugbtb.adoc#_ugbtb_programming-model_custom-validator[Custom Validator] to learn more.

|`isis.reflector.validator.` +
`actionCollection` +
`ParameterChoices`
|`true`,`false` +
(`true`)
| Whether to check that collection action parameters have a corresponding choices or autoComplete facet. +

In the current implementation such a facet is always required, so this configuration option has only been introduced as a feature flag in case it needs to be disabled for some reason.

|`isis.reflector.validator.` +
`allowDeprecated`
|`true`,`false` +
(`true`)
| Whether deprecated annotations or naming conventions are tolerated or not.
If not, then a metamodel validation error will be triggered, meaning the app won't boot (fail-fast). +

See also `isis.reflector.facets.ignoreDeprecated`.

|`isis.reflector.validator.` +
`explicitObjectType`
|`true`,`false` +
(`false`)
| Whether to check that the class has an object type explicitly specified somehow.

The object type is used by the framework as an alias for the object's concrete class; it is one part of the object's OID and can be seen in the URLs of the xref:../ugvw/ugvw.adoc#[Wicket viewer] and xref:../ugvro/ugvro.adoc#[Restful Objects viewer], and is encoded in the ``Bookmark``s returned by the xref:../rgsvc/rgsvc.adoc#_rgsvc_integration-api_BookmarkService[`BookmarkService`].
In this was it may also be persisted, for example in polymorphic associations or command or auditing tables.

If the object type is not specified explicitly, then this can cause data migration issues if the class is subsequently refactored (eg renamed, or moved to a different package).

This configuration property can be used to enforce a rule that the object type must always be specified (for persistent entities and view models).

|`isis.reflector.validator.` +
`jdoqlFromClause`
|`true`,`false` +
(`true`)
| Whether to check that the class name in JDOQL `FROM` clause matches or is a supertype of the class on which it is annotated. +

Only "SELECT" queries are validated; "UPDATE" queries etc are simply ignored.

|`isis.reflector.validator.` +
`jdoqlVariablesClause`
|`true`,`false` +
(`true`)
| Whether to check that the class name in JDOQL `VARIABLES` clause is a recognized class. +

Note that although JDOQL syntax supports multiple `VARIABLES` classes, currently the validator only checks the first class name found.

|`isis.reflector.validator.` +
`mixinsOnly`
|`true`,`false` +
(`false`)
| Mixins provide a simpler programming model to contributed domain services. +

If enabled, this configuration property will treat any contributed service as invalid.
This is by way of possibly deprecating and eventually moving contributed services from the Apache Isis programming model.


|`isis.reflector.validator.` +
`noParamsOnly`
|`true`,`false` +
(`false`)
| When searching for  xref:../rgcms/rgcms.adoc#_rgcms_methods_prefixes_disable[`disableXxx()`] or xref:../rgcms/rgcms.adoc#_rgcms_methods_prefixes_hide[`hideXxx()`] methods, whether to search only for the no-param version (or also for supporting methods that match the parameter types of the action). +

If enabled then will not search for supporting methods with the exact set of arguments as the method it was supporting (and any supporting methods that have additional parameters will be treated as invalid).
Note that this in effect means that xref:../ugfun/ugfun.adoc#_ugfun_building-blocks_types-of-domain-objects_mixins[mixins] must be used instead of xref:../ugfun/ugfun.adoc#_ugfun_programming-model_domain-services_contributions[contributed services].


|`isis.reflector.validator.` +
`serviceActionsOnly`
|`true`,`false` +
(`false`)
| Domain services are stateless (at least conceptually) and so should not have any properties or collections; any that are defined will not be rendered by the viewers. +

If enabled, this configuration property will ensure that domain services only declare actions.


|===



[[__rgcfg_configuring-core_other]]
== Other Config Properties


.Other Core Configuration Properties
[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(default value)
|Description

|`isis.objects.` +
`editing`
|`true`,`false` +
(`true`)
|Whether objects' properties and collections can be edited directly (for objects annotated with xref:../rgant/rgant.adoc#_rgant-DomainObject_editing[`@DomainObject#editing()`]); see xref:../rgcfg/rgcfg.adoc#__rgcfg_configuring-core_isis-objects-editing[below] for further discussion.


|`isis.persistor.` +
`disable` +
`ConcurrencyChecking`
|`true`,`false` +
(`false`)
| Disables concurrency checking globally.  +

Only intended for "emergency use" as a workaround while pending fix/patch to Apache Isis itself.  (Note that there is no "datanucleus" in the property).


|`isis.reflector.facet.` +
`cssClass.patterns`
|regex:css1, regex2:css2,...
|Comma separated list of key:value pairs, where the key is a regex matching action names (eg `delete.*`) and the value is a link:http://getbootstrap.com/css/[Bootstrap] CSS button class (eg `btn-warning) to be applied (as per `@CssClass()`) to all action members matching the regex. +

See xref:../ugfun/ugfun.adoc#_ugfun_ui-hints_action-icons-and-css[UI hints] for more details.

|`isis.reflector.facet.` +
`cssClassFa.patterns`
|regex:fa-icon,regex2:fa-icon2,...
|Comma separated list of key:value pairs, where the key is a regex matching action names (eg `create.*`) and the value is a link:http://fortawesome.github.io/Font-Awesome/icons/[font-awesome] icon name (eg `fa-plus`) to be applied (as per `@CssClassFa()`) to all action members matching the regex. +

See xref:../ugfun/ugfun.adoc#_ugfun_ui-hints_action-icons-and-css[UI hints] for more details.


|`isis.reflector.facet.` +
`filterVisibility`
|`true`,`false` +
(`true`)
|Whether objects should be filtered for visibility. +

See xref:../rgcfg/rgcfg.adoc#__rgcfg_configuring-core_filterVisibility[section below] for further discussion.

|`isis.reflector.facets`
|`FQCN`
|This property is now ignored.  +
+
To customize the programming model, use `facets.exclude` and `facets.include`.
See xref:../ugbtb/ugbtb.adoc#_ugbtb_programming-model_finetuning[finetuning the programming model] for more details.



|`isis.reflector.facets.` +
`exclude`
|`FQCN`,`FQCN2`,...
|Fully qualified class names of (existing, built-in) facet factory classes to be included to the programming model. +

See xref:../ugbtb/ugbtb.adoc#_ugbtb_programming-model_finetuning[finetuning the programming model] for more details.


|`isis.reflector.facets.` +
`ignoreDeprecated`
|`true`,`false` +
(`false`)
|Whether deprecated facets should be ignored or honoured.  +
+
By default all deprecated facets are honoured; they remain part of the metamodel.
If instead this property is set to `true` then the facets are simply not loaded into the metamodel and their semantics will be excluded.  +
+
In most cases this should reduce the start-up times for the application.
However, be aware that this could also substantially alter the semantics of your application.
To be safe, we recommend that you first run your application using `isis.reflector.validator.allowDeprecated` set to `false`; if any deprecated annotations etc. are in use, then the app will fail-fast and refuse to start.


|`isis.reflector.facets.` +
`include`
|`FQCN`,`FQCN2`,...
|Fully qualified class names of (new, custom) facet factory classes to be included to the programming model. +
See xref:../ugbtb/ugbtb.adoc#_ugbtb_programming-model_finetuning[finetuning the programming model] for more details.


|`isis.reflector.` +
`layoutMetadataReaders`
|`FQCN`,`FQCN2`,...
|Fully qualified class names of classes to be instantiated to read layout metadata, as used in for xref:../ugvw/ugvw.adoc#_ugvw_layout_file-based[file-based layout]s. +

See xref:../ugbtb/ugbtb.adoc#_ugbtb_programming-model_layout-metadata-reader[Layout Metadata Reader] for more information.



|`isis.viewers.` +
`paged.parented`
|positive integer (12)
|Default page size for parented collections (as owned by an object, eg `Customer#getOrders()`)


|`isis.viewers.` +
`paged.standalone`
|positive integer (25)
|Default page size for standalone collections (as returned from an action invocation)


|`isis.viewers.` +
`propertyLayout.labelPosition`
|`TOP`, `LEFT` +
(`LEFT`)
|Default for label position for all properties if not explicitly specified using xref:../rgant/rgant.adoc#_rgant-PropertyLayout_labelPosition[`@PropertyLayout#labelPosition()`]

|===



[[__rgcfg_configuring-core_filterVisibility]]
=== Filtering visibility

The framework provides the `isis.reflector.facet.filterVisibility` configuration property that influences whether a returned object is visible to the end-user:

* Action invocations: +

If an action returns a collection that includes the object, then the object will be excluded from the list when rendered.
If it returns a single object and the user does not have access to that object, then the action will seemingly return `null`

* Collections: +

If a parent object has a collection references another object to which the user does not have access, then (as for actions) the object will not be rendered in the list

* Properties: +

If an parent object has a (scalar) reference some other object to which the user does not have access, then the reference will be rendered as empty.

* Choices and autoComplete lists: +

If an object is returned in a list of choices or within an auto-complete list, and the user does not have access, then it is excluded from the rendered list.

The original motivation for this feature was to transparently support such features as multi-tenancy (as per the (non-ASF) http://github.com/isisaddons/isis-module-security[Isis addons' security] module).
That is, if an entity is logically "owned" by a user, then the multi-tenancy support can be arranged to prevent some other user from viewing that object.

By default this configuration property is enabled.  To disable the visibility filtering, set the appropriate configuration property to `false`:

[source,ini]
----
isis.reflector.facet.filterVisibility=false
----

Filtering is supported by the xref:../ugvw/ugvw.adoc#[Wicket viewer] and the xref:../ugvro/ugvro.adoc#[Restful Objects viewer], and also by the xref:../rgsvc/rgsvc.adoc#_rgsvc_application-layer-api_WrapperFactory[`WrapperFactory`] domain service (provided the wrapper's execution mode is __not__ "skip rules").

[NOTE]
====
In order for the framework to perform this filtering of collections, be aware that the framework takes a _copy_ of the original collection, filters on the collection, and returns that filtered collection rather than the original.

There are no major side-effects from this algorithm, other than the fact that the referenced objects will (most likely) need to be resolved in order to determine if they are visible.
This could conceivably have a performance impact in some cases.
====




[[__rgcfg_configuring-core_isis-objects-editing]]
=== `objects.editing`

This configuration property in effect allows editing to be disabled globally for an application:

[source,ini]
----
isis.objects.editing=false
----

We recommend enabling this feature; it will help drive out the underlying business operations (processes and procedures) that require objects to change; these can then be captured as business actions.



[[__rgcfg_configuring-core_isis-viewers-propertyLayout-labelPosition]]
=== `propertyLayout.labelPosition`

If you want a consistent look-n-feel throughout the app, eg all property labels to the top, then it'd be rather frustrating to have to annotate every property.

Instead, a default can be specified in `isis.properties`:

[source,ini]
----
isis.viewers.propertyLayout.labelPosition=TOP
----

or

[source,ini]
----
isis.viewers.propertyLayout.labelPosition=LEFT
----

If these are not present then Apache Isis will render according to internal defaults.
At the time of writing, this means labels are to the left for all datatypes except multiline strings.
