{
  rich {
    university_dept_Department(object: {id: "$departmentId"}) {
      staffMembers {
        metadata {
          friendlyName
          description
          cssClassFa
          cssClassFaPosition
          maxLength
        }
      }
      changeName {
        metadata {
          friendlyName
          description
          cssClassFa
          cssClassFaPosition
        }
        params {
          newName {
            metadata {
              friendlyName
              description
              cssClassFa
              cssClassFaPosition
              maxLength
              pattern
              patternFlags
              multiLine
              typicalLength
            }
          }
        }
      }
    }
    university_dept_Staff {
      findStaffMemberByName {
        invoke(name: "Gerry Jones") {
          results {
            name {
              metadata {
                friendlyName
                description
                cssClassFa
                cssClassFaPosition
                maxLength
                pattern
                patternFlags
                multiLine
                labelPosition
                typicalLength
              }
            }
            photo {
              get {
                fileAccept
              }
            }
            hiddenPhoto {
              hidden
              metadata {
                friendlyName
                description
              }
            }
          }
        }
      }
    }
  }
}
