[[_dg_asciidoc]]
= AsciiDoc Documentation

:notice: licensed to the apache software foundation (asf) under one or more contributor license agreements. see the notice file distributed with this work for additional information regarding copyright ownership. the asf licenses this file to you under the apache license, version 2.0 (the "license"); you may not use this file except in compliance with the license. you may obtain a copy of the license at. http://www.apache.org/licenses/license-2.0 . unless required by applicable law or agreed to in writing, software distributed under the license is distributed on an "as is" basis, without warranties or  conditions of any kind, either express or implied. see the license for the specific language governing permissions and limitations under the license.
:_basedir: ../
:_imagesdir: images/
:toc: right



Apache Isis' documentation (meaning the website and the users' guide, the reference guide and this contributors' guide) is written using link:http://www.methods.co.nz/asciidoc/[Asciidoc], specifically the link:asciidoctor.org/[Asciidoctor] implementation.

The website and guides are created by running build tools (documented below) which create the HTML version of the site and guides.  You can therefore easily check the documentation before raising a pull request (as a contributor) or publishing the site (if a committer).

Publishing is performed by copying the generated HTML to a different git repository (link:https://git-wip-us.apache.org/repos/asf?p=isis-site.git[isis-site]).  This is synced by ASF infrastructure over to link:http://isis.apache.org[isis.apache.org].

And to help write the Asciidoc text itself, we provide some xref:dg.adoc#_dg__cg_ide-templates[templates].


== Where to find the Docs

The (Asciidoc) source code can be found at `adocs/documentation` (relative to root).  Online you'll find it link:https://github.com/apache/isis/tree/master/adocs/documentation[cloned to github here].



== Naming Conventions

For documents with inclusions, use '_' to separate out the logical hierarchy:

[source]
----
xxx-xxx/xxx-xxx.adoc
        _xxx-xxx_ppp-ppp.adoc
        _xxx-xxx_qqq-qqq.adoc
        _xxx-xxx_qqq-qqq_mmm-mmm.adoc
        _xxx-xxx_qqq-qqq_nnn-nnn.adoc
----

Any referenced images should be in subdirectories of the `images` directory: 

[source]
----
xxx-xxx/images/.
              /ppp-ppp/.
              /qqq-qqq/.
                      /mmm-mmm
                      /nnn-nnn
----

And similarly any resources should be in the `resources` subdirectory:

[source]
----
xxx-xxx/resources/.
                  ppp-ppp/.
                  qqq-qqq/.
                         /mmm-mmm/
                         /nnn-nnn/
----



== Writing the docs

We highly recommend that you install the (IntelliJ) live templates for Asciidoctor, as described in xref:dg.adoc#_dg_ide_intellij_live-templates[IDE templates].  These provide a large number of helper templates.

An xref:dg.adoc#_dg_appendix_asciidoc-templates[appendix] lists all the templates available, demonstrating their intended usage and output.


== Build and Review (using Maven)

To (re)build the documentation locally prior to release, change into the `adocs/documentation` directory and use:

[source]
----
mvn clean compile
----

The site will be generated at `target/site/index.html`.

You could then use a web server such as Python's SimpleHTTPServer to preview (so that all Javascript works correctly). However, instead we recommend using instant preview, described next.


== Instant Rebuild (using Ruby)

The ruby script, `monitor.rb` emulates the `mvn compile` command, regenerating any changed Asciidoctor files to the relevant `target/site` directory.  Moreover if any included files are changed then it rebuilds the parent (per the above naming convention).

=== One-time setup

To setup:

* download and install ruby 2.0.0, from link:rubyinstaller.org/downloads[http://rubyinstaller.org/downloads/]
* download devkit for the Ruby 2.0 installation, also from link:rubyinstaller.org/downloads[http://rubyinstaller.org/downloads/]. Then follow the link:https://github.com/oneclick/rubyinstaller/wiki/Development-Kit[installation instructions] on their wiki


[NOTE]
====
We use Ruby 2.0 rather than 2.1 because the wdm gem (required to monitor the filesystem if running on Windows) is not currently compatible with Ruby 2.1.
====

To download the required Ruby dependencies, use:

[source,bash]
----
gem install bundler
bundle install
----

=== Instant Rebuild

To run, we typically just use:

[source,bash]
----
sh monitor.sh
----

This script simply runs `mvn clean compile && ruby monitor.rb -b`.  The `mvn` command performs a clean rebuild of the site, and then the ruby script monitors for any further changes under `src/main/asciidoc`.

The script also starts up a web server on port 4000 so you can review results.  If any `.adoc` changes, then the appropriate HTML will be regenerated.  And, if any new assets (CSS, images etc) are added, they will be copied across.  The `-b` flag passed through means that the script also starts a web browser pointing at the newly generated docs.

The `monitor.rb` script has a couple of other options, use `-h` flag for usage:

[source,bash]
----
ruby monitor.rb -h
----

which should print:

[source]
----
usage: monitor.rb [options]
    -p, --port       port (default: 4000)
    -b, --browser    launch browser
    -h, --help       help
----


== Publish procedure

Only Apache Isis committers can publish to link:http://isis.apache.org[isis.apache.org].  We've decided to include these procedures here here (rather than put them in the xref:cgcom.adoc#[Committers' Guide]), just to keep things together.


=== One-time setup

The generated site is published by copying into the `content/` directory of the https://git-wip-us.apache.org/repos/asf/isis-site.git[isis-site git repo]. You therefore need to check this out this repo.

The procedure assumes that two git repos (for https://git-wip-us.apache.org/repos/asf/isis.git[isis] itself and for isis-site) are checked out into the same parent directory, eg:

[source]
----
/APACHE/
    isis/                       # checkout of isis.git
        adocs/
            documentation/
                README.adoc     # this file you are reading right now
                ...
    isis-site/                  # checkout of isis-site.git
        content/                # the published website
----

If this isn't the case, then it is possible to override the relative directory by passing in a system property to the mvn goal; see below.

You also need to know that ASF's publishing script work from the 'asf-site' branch, NOT from the 'master' branch. Therefore, in the `isis.git` repo site:

[source,bash]
----
git checkout asf-site
----

=== Publishing (full build)

Back in the `adocs/documentation` directory of the main `isis-git.repo`, to copy the generated documents to the `isis-site.git` repo, run:

[source,bash]
----
mvn clean package
----

This deletes the entire content of `contents`, and replaces with the content under `target/site`.  It also fixes up line endings, standardizing on unix-style LFs.

[TIP]
====
If you have checked out the `isis-site.git` repo into some other directory (relative to `isis.site.git), then this can be overridden by specifying `-Disis-site.dir=...` when calling `mvn`.
====


To copy and to also commit the generated documents to the `isis-site.git` repo , run:

[source,bash]
----
sh publish.sh "ISIS-nnnn: a custom commit message"
----

Behind the scenes this just calls `mvn clean install -Dmessage=...`.

It's also possible to omit the message, in which case `publish.sh` will reuse the most recent commit message from the main `isis.git` repo.

Pushing the commits (in the `isis-site.git` directory, of course) will publishing the changes:

[source,bash]
----
git push
----

Double check at http://isis.apache.org[isis.apache.org].




=== Publishing (partial build)

If none of the guides have been changed, and if you have run the full rebuild recently, then you can skip the generation of PDFs using:

[source,bash]
----
mvn install -Dskip.pdf -D"ISIS-nnnn: a custom commit message"
----

The `clean` goal *must not* be included though (else all the guides will disappear from the site content).
