[[_rg_annotations_manpage-DomainServiceLayout_named]]
= `named()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `named()` attribute explicitly specifies the domain service's name, overriding the name that would normally be inferred from the Java source code.  This attribute can also be specified for xref:rg.adoc#_rg_annotations_manpage-ActionLayout_named[actions], xref:rg.adoc#_rg_annotations_manpage-CollectionLayout_named[collections], xref:rg.adoc#_rg_annotations_manpage-PropertyLayout_named[properties], xref:rg.adoc#_rg_annotations_manpage-ParameterLayout_named[parameters], xref:rg.adoc#_rg_annotations_manpage-DomainObjectLayout_named[domain objects] and xref:rg.adoc#_rg_annotations_manpage-ViewModelLayout_named[view models].


[TIP]
====
The value of this attribute also has an important role to play in the positioning of the domain service's actions relative to the actions of other domain services.  See xref:rg.adoc#_rg_annotations_manpage-DomainServiceLayout_menuOrder[`menuOrder()`] for a full discussion with examples.
====

For example:

[source,java]
----
@DomainService
@DomainServiceLayout(
    named="Customers"
)
public class CustomerRepository {
   ...
}
----


