[[_rg_schema-common]]
= Common Schema
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



The main purpose of the common schema is to define the `oidDto` complex type: the object's type and its identifier.
This is basically a formal XML equivalent to the `Bookmark` object obtained from the
xref:rgsvc.adoc#_rgsvc-api_manpage-BookmarkService[`BookmarkService`].

Although simple, this is an enormously powerful concept, in that it represents a URI to any domain object managed by
a given Apache Isis application.  With it, we have the ability to lookup any arbitrary object.  Further discussion and
examples can be found xref:ug.adoc#_ug_core-concepts_building-blocks_oid[here].


[source,xml]
----
<xs:schema targetNamespace="http://isis.apache.org/schema/common"                           <!--1-->
           elementFormDefault="qualified"
           xmlns="http://isis.apache.org/schema/common"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="oidDto">                                                          <!--2-->
        <xs:sequence>
            <xs:element name="objectType" type="xs:string"/>                                <!--3-->
            <xs:element name="objectIdentifier" type="xs:string"/>                          <!--4-->
        </xs:sequence>
        <xs:attribute name="objectState" type="bookmarkObjectState" default="persistent"/>
    </xs:complexType>

    <xs:simpleType name="bookmarkObjectState">                                              <!--5-->
        <xs:restriction base="xs:string">
            <xs:enumeration value="persistent"/>
            <xs:enumeration value="transient"/>
            <xs:enumeration value="viewModel"/>
        </xs:restriction>
    </xs:simpleType>
    ...
</xs:schema>
----
<1> the common schema has a namespace URI of "http://isis.apache.org/schema/common".  Although URIs are not the same as URLs, you will find that the schemas are also downloadable from this location.
<2> the `oidDto` complex type defines the unique identifier for any domain object: its type, and an identifier.  The `objectState` attribute is of type `bookmarkObjectState` and will typically be "transient" or "viewModel"
<3> the object type, corresponding to either the
xref:rgant.adoc#_rgant-DomainObject_objectType[`@DomainObject#objectType()`] attribute, or to the (JDO)
xref:rgant.adoc#_rgant-PersistenceCapable[`@PersistenceCapable`] annotation (`schema` and/or `table`
attributes), or to the (JDO) xref:rgant.adoc#_rgant-Discriminator[`@Discriminator`] annotation.  If none
is specified, then the fully
qualified class name will be used.
<4> the object identifier (aka primary key), converted to string form.
<5> the `bookmarkObjectState` enumerates the possible persistence states of the referenced object.  Although "transient" is shown,
in practice the only types of objects will be "persistent" (entities) or "viewModel".

The `oidDto` complex type is used in two specific places by the framework:

* first, as a means of serializing JAXB view model/DTOs (annotated with
xref:rgant.adoc#_rgant-XmlRootElement[`@XmlRootElement`]), that reference domain entities. +
+
These references are serialized instead into OIDs

* second, as references to the target of action invocations, as described by the
xref:rg.adoc#_rg_schema-aim[action invocation memento] schema. +
+
They are also used to represent references to any action arguments that take domain object entities.

The common schema also defines two further types: the `valueDto` complex type and the `valueType` simple type:

[source,xml]
----
<xs:schema targetNamespace="http://isis.apache.org/schema/common"
           elementFormDefault="qualified"
           xmlns="http://isis.apache.org/schema/common"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    ...
    <xs:complexType name="valueDto">                              <!--1-->
        <xs:choice minOccurs="0" maxOccurs="1">
            <xs:element name="string" type="xs:string"/>
            <xs:element name="byte" type="xs:byte"/>
            <xs:element name="short" type="xs:short"/>
            ...
            <xs:element name="localTime" type="xs:time"/>
            <xs:element name="reference" type="oidDto"/>
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="valueType">                              <!--2-->
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="byte"/>
            <xs:enumeration value="short"/>
            ...
            <xs:enumeration value="isisApplibClob"/>
            <xs:enumeration value="reference"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
----

These two type definitions are just building blocks, also used within the
xref:rg.adoc#_rg_schema-aim[action iInvocation memento] schema.  The first, `valueDto` is intended to hold any valid
value, eg of an argument to an action.  The second, `valueType`, enumerates the different types of vales, eg of a
formal parameter to an action.
