[[_rg_schema-common]]
= Common Schema
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



== `oidDto`

The main purpose of the common schema is to define the `oidDto` complex type: the object's type and its identifier.
This is basically a formal XML equivalent to the `Bookmark` object obtained from the
xref:rg.adoc#_rg_services-api_manpage-BookmarkService[`BookmarkService`].

Although simple, this is an enormously powerful concept, in that it represents a URI to any domain object managed by
a given Apache Isis application.  With it, we have the ability to lookup any arbitrary object.  Further discussion and
examples can be found xref:ug.adoc#_ug_core-concepts_building-blocks_oid[here].




[source,xml]
----
<xs:schema targetNamespace="http://isis.apache.org/schema/common"                           <!--1-->
           elementFormDefault="qualified"
           xmlns="http://isis.apache.org/schema/common"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="oidDto">                                                          <!--2-->
        <xs:sequence>
            <xs:element name="objectType" type="xs:string"/>
            <xs:element name="objectIdentifier" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="objectState" type="bookmarkObjectState" default="persistent"/>
    </xs:complexType>
    <xs:simpleType name="bookmarkObjectState">
        <xs:restriction base="xs:string">
            <xs:enumeration value="persistent"/>
            <xs:enumeration value="transient"/>
            <xs:enumeration value="viewModel"/>
        </xs:restriction>
    </xs:simpleType>
    ...
</xs:schema>
----

This

== `valueDto` and `valueType`

The common schema defines two further types: the `valueDto` complex type and the `valueType` simple type:

[source,xml]
----
<xs:schema targetNamespace="http://isis.apache.org/schema/common"
           elementFormDefault="qualified"
           xmlns="http://isis.apache.org/schema/common"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    ...
    <xs:complexType name="valueDto">                                    <!--1-->
        <xs:choice minOccurs="0" maxOccurs="1">
            <xs:element name="string" type="xs:string"/>
            <xs:element name="byte" type="xs:byte"/>
            <xs:element name="short" type="xs:short"/>
            <xs:element name="int" type="xs:int"/>
            <xs:element name="long" type="xs:long"/>
            <xs:element name="float" type="xs:float"/>
            <xs:element name="double" type="xs:double"/>
            <xs:element name="boolean" type="xs:boolean"/>
            <xs:element name="char" type="xs:string"/>
            <xs:element name="bigDecimal" type="xs:decimal"/>
            <xs:element name="bigInteger" type="xs:integer"/>
            <xs:element name="dateTime" type="xs:dateTime"/>
            <xs:element name="localDate" type="xs:date"/>
            <xs:element name="localDateTime" type="xs:dateTime"/>
            <xs:element name="localTime" type="xs:time"/>
            <xs:element name="reference" type="oidDto"/>
        </xs:choice>
    </xs:complexType>
    <xs:simpleType name="valueType">                                  <!--2-->
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="byte"/>
            <xs:enumeration value="short"/>
            <xs:enumeration value="int"/>
            <xs:enumeration value="long"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="char"/>
            <xs:enumeration value="bigInteger"/>
            <xs:enumeration value="bigDecimal"/>
            <xs:enumeration value="javaUtilDate"/>
            <xs:enumeration value="javaSqlDate"/>
            <xs:enumeration value="javaSqlTime"/>
            <xs:enumeration value="javaSqlTimestamp"/>
            <xs:enumeration value="jodaDateTime"/>
            <xs:enumeration value="jodaLocalDate"/>
            <xs:enumeration value="jodaLocalTime"/>
            <xs:enumeration value="jodaLocalDateTime"/>
            <xs:enumeration value="isisApplibBlob"/>
            <xs:enumeration value="isisApplibClob"/>
            <xs:enumeration value="reference"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
----

These two definitions are just building blocks, both used within the xref:rg.adoc#_rg_schema-aim[Action Invocation Memento]
schema.  The first, `valueDto` is intended to hold any valid value, eg of an argument to an action.  The second,
`valueType`, enumerates the different types of vales, eg of a formal parameter to an action.
