[[_rg_annotations_manpage-XmlRootElement]]
= `@XmlRootElement` (`jaxb`) (`1.11.0-SNAPSHOT`)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `@XmlRootElement` annotation (`1.11.0-SNAPSHOT`) provides an alternative way to define a view model, in particular
one intended to act as a DTO for use within xref:ug.adoc#_ug_restfulobjects-viewer[RestfulObjects viewer], or which
contains arbitrarily complex state.

A view model is a non-persisted domain object whose state is converted to/from a string memento.  In the case of a
JAXB-annotated object this memento is its XML representation.  JAXB generally requires that the root element of the
XML representation is annotated with `@XmlRootElement`.  Apache Isis makes this a mandatory requirement.

In comparison to using either the xref:rg.adoc#_rg_classes_super_manpage-ViewModel[`ViewModel`] interface or the
xref:rg.adoc#_rg_annotations_manpage-ViewModel[`@ViewModel`] annotation, using `@XmlRootElement` has a couple of
significant advantages:

* the view model can be used as a "canonical" DTO, for example when accessing data using the
xref:ug.adoc#_ug_restfulobjects-viewer[RestfulObjects viewer] in combination with the
xref:rg.adoc#_rg_services-spi_manpage-ContentMappingService[`ContentMappingService`]. +
+
This provides a stable and
versioned API to access data in XML format using whatever client-side technology may be appropriate.

* the XML graph can be as deep as required, in particular it can contain collections of other objects. +
+
In contrast, if the `@ViewModel` annotation is used then only the state of the properties (not collections) is captured.
If using `ViewModel` interface then arbitrary state (including that of collections), however the programmer must write
all the code by hand

The main disadvantages of using JAXB-annotated view models is that any referenced persistent entity must be annotated
with the xref:rg.adoc#_rg_annotations_manpage-XmlValueTypeAdapter[`@XmlValueTypeAdapter`], using the
framework-provided `PersistentEntityAdapter`.  This adapter converts any references to such domain entities into the
`<oid-dto>` element as defined by the Apache Isis xref:rg.adoc#_rg_schema-common[common schema].

[TIP]
====
The memento string for view models is converted into a form compatible with use within a URL.  This is performed by the
xref:rg.adoc#_rg_services-spi_manpage-UrlEncodingService[`UrlEncodingService`], the default implementation of which
simply encodes to base 64.  If the view model XML graph is too large to be serialized to a string, then an alternative
implementation (eg which maps XML strings to a GUID, say) can be configured using the technique described in
xref:rg.adoc#_ug_how-tos_replacing-default-service-implementations[here] in the user guide.
====


== Example

This example is taken from the (non-ASF) http://github.com/isisaddons/isis-app-todoapp[Isis addons' todoapp]:

[source,java]
----
@XmlAccessorType(XmlAccessType.FIELD)                               // <1>
@XmlType(
        namespace = "http://viewmodels.app.todoapp/v1/todoitem",    // <2>
        propOrder = {                                               // <3>
            "description",
            "category",
            "subcategory",
            "cost"
        }
)
@XmlRootElement(name = "toDoItemDto")                               // <4>
public class ToDoItemDto implements Dto {

    @XmlElement(required = true)                                    // <5>
    @Getter @Setter
    protected String description;

    @XmlElement(required = true)
    @Getter @Setter
    protected String category;

    @Getter @Setter
    protected String subcategory;

    @Getter @Setter
    protected BigDecimal cost;

    // getters and setters omitted
}
----
<1> optional; whether JAXB-serialization reads fields directly (as here) else uses getters/setters
<2> specify the XML schema namespace to which this element type belongs
<3> all properties in the class must be listed; (they can be ignored using `@XmlTransient`)
<4> mandatory, identifies this class as a view model and defines the root element for JAXB serialization
<5> optional; JAXB metadata can specify such attributes as required/optional
