[[_rgant-Inject]]
= `@Inject` (`javax`)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



Apache Isis automatically injects domain services into other domain services and also into domain objects and view models.  In fact, it also injects domain services into xref:ugtst.adoc#_ugtst_integ-test-support[integration tests] and xref:ugtst.adoc#_ugtst_fixture-scripts[fixture scripts].

[NOTE]
====
One omission: Apache Isis (currently) does not inject services into `o.a.i.applib.spec.Specification` instances (as used by xref:rgant.adoc#_rgant-Property_mustSatisfy[`@Property#mustSatisfy()`] and xref:rgant.adoc#_rgant-Parameter_mustSatisfy[`@Parameter#mustSatisfy()`] annotations.
====

Isis supports several syntaxes for injecting domain services.  The simplest uses the `@javax.inject.Inject` annotation on the field, as defined in link:https://jcp.org/en/jsr/detail?id=330[JSR-330].

For example:

[source,java]
----
public class Customer {
    public List<Order> findRecentOrders() {    // <1>
        return orders.recentOrdersFor(this);
    }
    @javax.inject.Inject
    OrderRepository orders;                    // <2>
}
----
<1> an alternative implementation would be to implement `findRecentOrders()` as a xref:ugfun.adoc#_ugfun_how-tos_contributed-members[contributed action].
<2> we recommend default (rather than `private`) visibility so that unit tests can easily mock out the service



== Alternative syntaxes

Isis also supports setter-based injection:

[source,java]
----
public class Customer {
    ...
    public void setOrderRepository(OrderRepository orderRepository) { ... }
}
----

and also supports an additional syntax of using `inject...` as the prefix:

[source,java]
----
public class Customer {
    ...
    public void injectOrderRepository(OrderRepository orderRepository) { ... }
}
----

Generally we recommend using `@javax.inject.Inject`; it involves less code, and is more immediately familiar to most Java developers.



== Injecting collection of services

It can sometimes be useful to have declared multiple implementations of a particular domain service.  For example,
you may have a module that defines an SPI service, where multiple other modules might provide implementations of that SPI
 (akin to the chain of responsibility pattern).  To support these scenarios, it is possible to annotate a `List` or `Collection`.

For example, suppose that we provide an SPI service to veto the placing of ``Order``s for certain ``Customer``s:

[source,java]
----
public interface CustomerOrderAdvisorService {
    @Programmatic
    String vetoPlaceOrder(Customer c);
----

We could then inject a collection of these services:

[source,java]
----
public class Customer {
    public Order placeOrder(Product p, int quantity) { ... }
    public String disablePlaceOrder(Product p, int quantity) {
        for(CustomerOrderAdvisorService advisor: advisors) {
            String reason = advisor.vetoPlaceOrder(this);
            if(reason != null) { return reason; }
        }
        return null;
    }
    @Inject
    Collection<CustomerOrderAdvisorService> advisors;       // <1>
}
----
<1> inject a collection of the services.

[NOTE]
====
An alternative and almost equivalent design would be to publish an event using the xref:rgsvc.adoc#_rgsvc_api_EventBusService[`EventBusService`] and implement the domain services as subscribers to
the event.  This alternative design is used in the (non-ASF) http://github.com/isisaddons/isis-module-poly[Isis addons' poly] module, for example.
====





== Manually injecting services

Isis performs dependency injection when domain entities are recreated.  It will also perform dependency injection if an object is created through the `DomainObjectContainer`.

For example, to create a new (transient) domain object, the idiom is:

[source,java]
----
Customer cust = container.newTransientInstance(Customer.class);  <1>
// initialize state of "cust"
container.persist(cust);
----
<1> where `container` is an instance of xref:rgsvc.adoc#_rgsvc_api_DomainObjectContainer[`DomainObjectContainer`].

View models are created similarly:

[source,java]
----
ToDoAppDashboard dashboard = container.newViewModelInstance(ToDoAppDashboard.class);
----


If you prefer, though, you can simply instantiate domain objects using "new" and then inject domain services manually:


[source,java]
----
Customer cust = new Customer();
container.injectServicesInto(cust);
// initialize state of "cust"
container.persist(cust);
----


or if you prefer:

[source,java]
----
Customer cust = container.injectServicesInto(new Customer());
// initialize state of "cust"
container.persist(cust);
----


[NOTE]
====
There is one subtle difference between using `DomainObjectContainer#newTransientInstance(...)` and `DomainObjectContainer#injectServicesInto(...)`, in that with the former Apache Isis will automatically initialize all fields to their default values.

This isn't a particular useful feature (and indeed can sometimes be rather confusing) so you may well wish to standardize on using `injectServicesInto(...)` throughout.
====
