[[_rgcms_classes_domainevent_AbstractDomainEvent]]
= `AbstractDomainEvent`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


This class is the superclass for all domain events that are raised by the framework when interacting with actions,
properties or collections.

Its immediate subclasses are:

* xref:rgcms.adoc#_rgcms_classes_domainevent_ActionDomainEvent[`ActionDomainEvent`]

* xref:rgcms.adoc#_rgcms_classes_domainevent_PropertyDomainEvent[`PropertyDomainEvent`]

* xref:rgcms.adoc#_rgcms_classes_domainevent_CollectionDomainEvent[`CollectionDomainEvent`]

The main purpose of the class is to define the protocol by which subscribers can influence an interaction (eg hide a
collection, disable a property, validate action arguments).  It class also provides a simple mechanism to allow
adhoc sharing of user data between different phases.

== API

The API of the class is:

[source,java]
----
public abstract class AbstractDomainEvent<S> extends java.util.EventObject {

    public Phase getEventPhase();                                   // <1>
    public S getSource();                                           // <2>
    public Identifier getIdentifier();                              // <3>

    public void hide();                                             // <4>
    public boolean isHidden();                                      // <5>

    public void disable(final String reason);                       // <6>
    public void disable(final TranslatableString reason);
    public String getDisabledReason();                              // <7>
    public TranslatableString getDisabledReasonTranslatable();
    public boolean isDisabled();

    public void invalidate(final String reason);                    // <8>
    public void invalidate(final TranslatableString reason);
    public String getInvalidityReason();                            // <9>
    public TranslatableString getInvalidityReasonTranslatable();
    public boolean isInvalid();

    public void veto(final String reason, final Object... args);    // <10>
    public void veto(final TranslatableString translatableReason);

    public Object get(Object key);                                  // <11>
    public void put(Object key, Object value);
}
----
<1> Whether the framework is checking visibility, enablement, validity or actually executing
(invoking action, editing property), as per the `Phase` enum (defined below).
<2> The domain object raising this event
<3> Identifier of the action, property or collection being interacted with.
<4> API for subscribers to hide the member
<5> Used by the framework to determine if the member should be hidden (not rendered)
<6> API for subscribers to disable the member, specifying the reason why (possibly translated)
<7> Used by the framework to determine whether the member should be disabled (greyed out) when rendered.
<8> API for subscribers to invalidate an interaction, eg invalid arguments to an action
<9> Used by the framework to determine whether the interaction is invalid and should be blocked (eg pressing OK shows
message)
<10> Convenience API for subscribers to veto; will automatically call either `hide()`, `disable(...)` or
`invalidate(...)` based on the phase
<11> Mechanism to allow subscribers to share arbitrary information between phases.  One event instance is used for both
the hide and disable phases, and a different event instance is shared between validate/pre-execute/post-execute.

The referenced `Phase` enum is in turn:

[source,java]
----
public enum Phase {
    HIDE,
    DISABLE,
    VALIDATE,
    EXECUTING,
    EXECUTED;
    public boolean isValidatingOrLater();    // <1>
}
----
<1> The significance being that at this point the proposed values/arguments are known, and so the event can be fully
populated.
