[[_rgsvc_spi_HintStore]]
= `HintStore`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `HintStore` service defines an SPI for the xref:ugvw.adoc#[Wicket viewer] to store UI hints on a per-object basis.
For example, the viewer remembers which tabs are selected, and for collections which view is selected (eg table or hidden),
which page of a table to render, or whether "show all" (rows) is toggled.

The default implementation of this service uses the HTTP session.  The service is an SPI because the amount of data
stored could potentially be quite large (for large numbers of users who use the app all day).  An SPI makes it easy to
plug in an alternative implementation that is more sophisticated than the default (eg implementing MRU/LRU queue, or
using a NoSQL database, or simply to disabling the functionality altogether).


== SPI

The SPI of `HintStore` is:

[source,java]
----
public interface HintStore {
    String get(final Bookmark bookmark, String hintKey);                // <1>
    void set(final Bookmark bookmark, String hintKey, String value);    // <2>
    void remove(final Bookmark bookmark, String hintKey);               // <3>
    void removeAll(Bookmark bookmark);                                  // <4>
    Set<String> findHintKeys(Bookmark bookmark);                        // <5>
}
----
<1> obtain a hint (eg which tab to open) for a particular object.  Object identity is represented by `Bookmark`, as
per the xref:rgsvc.adoc#_rgsvc_api_BookmarkService[`BookmarkService`], so that alternative implementations can easily serialize this state to a string.
<2> set the state of a hint.  (The value of) all hints are represented as strings.
<3> remove a single hint for an object;
<4> remove all hints
<5> obtain all known hints for an object



== Implementation

The core framework provides a default implementation of this service (`org.apache.isis.viewer.wicket.viewer.services.HintStoreUsingWicketSession`).




== Registering the Service

Assuming that the `configuration-and-annotation` services installer is configured (implicit if using the
`AppManifest` to xref:rgcms.adoc#_rgcms_classes_AppManifest-bootstrapping[bootstrap the app]) then Apache Isis' core
implementation of `HintStore` service is automatically registered and injected (it is annotated with
`@DomainService`) so no further configuration is required.

To use an alternative implementation, use
xref:rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`] (as explained
in the xref:rgsvc.adoc#_rgsvc_intro_overriding-the-services[introduction] to this guide).


== Related Services

The xref:ugvw.adoc[Wicket viewer] exposes the xref:rgcms.adoc#_rgcms_classes_mixins_Object_clearHints["clear hints"]
mixin action that is for use by end-users of the application to clear any UI hints that have accumulated for a
domain object.
