[[_rgsvc_api_TransactionService]]
= `TransactionService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `TransactionService` provides a small number of methods to allow domain objects to influence user transactions.

[NOTE]
====
The methods in this service replace similar methods (now deprecated) in xref:rgsvc.adoc#_rgsvc_api_DomainObjectContainer[`DomainObjectContainer`].
====


== API

The API of `TransactionService` is:

[source,java]
----
public interface TransactionService {
    Transaction currentTransaction();   // <1>
    void nextTransaction();             // <2>
    void flushTransaction();            // <3>
}
----
<1> to obtain a handle on the current `Transaction`, discussed further below
<2> The framework automatically start a transaction before each user interaction (action invocation or property edit),
and will commit that transaction after the interaction has completed.  Under certain circumstances (eg actions used to
perform data migration, say, or for large fixture scripts), it can be helpful to programmatically complete one
transaction and start another one.
<3> If the user interaction creates/persists an object or deletes an object (eg using the
xref:rgsvc.adoc#_rgsvc_api_RepositoryService[`RepositoryService`]'s `persist()` or `delete()` methods), then the
framework actually queues up the work and only performs the persistence command either at the end of the transaction
or immediately prior to the next query.  Performing a flush will cause any pending calls to be performed immediately.

The `nextTransaction()` is also used by the xref:ugvw.adoc#[Wicket viewer]'s support for bulk actions; each action
is invoked in its own transaction.

The `Transaction` object - as obtained by `currentTransaction()` method, above - is a minimal wrapper around the
underlying database transaction.  Its API is:

[source,java]
----
public interface Transaction {
    UUID getTransactionId();            // <1>
    int getSequence();                  // <2>
    void flush();                       // <3>
    void clearAbortCause();             // <4>
}
----
<1> is a unique identifier for the interaction/request, as defined by the
xref:rgcms.adoc#_rgcms_classes_mixins_HasTransactionId[`HasTransactionId`] mixin.
<2> there can actually be multiple transactions within such a request/interaction; the sequence is a (0-based) is used
to distinguish such.
<3> as per `TransactionService#flushTransaction()` described above.
<4> If the cause has been rendered higher up in the stack, then clear the cause so that it won't be picked up and
rendered elsewhere.

[TIP]
====
One place where `clearAboutCause()` may be useful is for application-level handling of SQL integrity exceptions, eg as
described in link:https://issues.apache.org/jira/browse/ISIS-1476[ISIS-1476]:

[source,java]
----
try {
    // do something...
} catch (final JDODataStoreException e) {
    if (Iterables.filter(Throwables.getCausalChain(e),
        SQLIntegrityConstraintViolationException.class) != null) {
        // ignore
        this.transactionService.currentTransaction().clearAbortCause();
    } else {
        throw e;
    }
}
----
====


== Implementation

The core framework provides a default implementation of this service (`o.a.i.core.metamodel.services.xactn.TransactionServiceInternalDefault`).


== Registering the Service

Assuming that the `configuration-and-annotation` services installer is configured (implicit if using the
`AppManifest` to xref:rgcms.adoc#_rgcms_classes_AppManifest-bootstrapping[bootstrap the app]) then Apache Isis' core
implementation of `TransactionService` service is automatically registered and injected (it is annotated with
`@DomainService`) so no further configuration is required.

To use an alternative implementation, use
xref:rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`] (as explained
in the xref:rgsvc.adoc#_rgsvc_intro_overriding-the-services[introduction] to this guide).
