[[_rgsvc_api_TransactionService]]
= `TransactionService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `TransactionService` provides a small number of methods to allow domain objects to influence user transactions.

[NOTE]
====
The methods in this service replace similar methods (now deprecated) in xref:rgsvc.adoc#_rgsvc_api_DomainObjectContainer[`DomainObjectContainer`].
====


== API

The API of `TransactionService` is:


[source,java]
----
public interface TransactionService {
    void flushTransaction();
    void nextTransaction();
}
----


Normally, the framework will automatically start a transaction before each user interaction (action invocation or
property modification), and commit that transaction after the interaction has completed.  If the interaction throws
an exception then the transaction is aborted.

If the user interaction creates and persists an object (using xref:rgsvc.adoc#_rgsvc_api_DomainObjectContainer[`DomainObjectContainer`]'s `persist()` method), then the framework actually defers the call and only performs the persistence command at the
end of the transaction, or immediately prior to the next query.

    /**
     *
     *
     * <p>
     * Occasionally useful to ensure that newly persisted domain objects
     * are flushed to the database prior to a subsequent repository query.
     */

/**
* Intended only for use by fixture scripts and integration tests; commits this transaction and starts a new one.
*/



== Implementation

The core framework provides a default implementation of this service (`o.a.i.core.metamodel.services.xactn.TransactionServiceDefault`).


== Registering the Service

Assuming that the `configuration-and-annotation` services installer is configured (implicit if using the
`AppManifest` to xref:rgcms.adoc#_rgcms_classes_AppManifest-bootstrapping[bootstrap the app]) then Apache Isis' core
implementation of `TransactionService` service is automatically registered and injected (it is annotated with
`@DomainService`) so no further configuration is required.

To use an alternative implementation, use
xref:rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`] (as explained
in the xref:rgsvc.adoc#_rgsvc_intro_overriding-the-services[introduction] to this guide).
