[[_rgsvc_spi_GridSystemService]]
= `GridSystemService` (`1.12.0-SNAPSHOT`)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



The `GridSystemService` encapsulates a single layout grid system which can be used to customize the layout
of domain objects.  In particular this means being able to return a "normalized" form (validating and associating
domain object members into the various regions of the grid) and in providing a default grid if there is no other
metadata available.

In theory there can be multiple implementations of this service, one per concrete subclass of the applib `Grid` class.  Each concrete implementation requires Wicket viewer components capable of interpreting the grid layout.

The framework provides a single such grid implementation, namely for Bootstrap3.


== SPI

The SPI defined by this service is:

[source,java]
----
public interface GridSystemService<G extends Grid> {
    Class<? extends Grid> gridImplementation();                 // <1>
    String tns();                                               // <2>
    String schemaLocation();                                    // <3>
    Grid defaultGrid(Class<?> domainClass);                     // <4>
    void normalize(G grid, Class<?> domainClass);               // <5>
    void complete(G grid, Class<?> domainClass);                // <6>
    void minimal(G grid, Class<?> domainClass);                 // <7>
}
----
<1> The concrete subclass of `Grid` supported by this implementation. As noted in the introduction, there can be multiple implementations of this service,  but there can only be one implementation per concrete subclass.  As is normal practice,
the service with the lowest xref:rgant.adoc#_rgant_DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`] takes precedence.
<2> the target namespace for this grid system.  This is used when generating the XML.  The Bootstrap3 grid system provided by the framework returns the value `http://isis.apache.org/applib/layout/grid/bootstrap3`.
<3> the schema location for the XSD.  The Bootstrap3 grid system provided by the framework returns the value `http://isis.apache.org/applib/layout/grid/bootstrap3/bootstrap3.xsd`.
<4> a default grid, eg two columns in ratio 4:8.  Used when no existing grid layout exists for a domain class.
<5> Validates and normalizes a grid, modifying the grid so that all of the domain object's members (properties, collections, actions) are bound to regions of the grid.  This is done using existing metadata, most notably that of the xref:rgant.adoc#_rgant_MemberOrder[`@MemberOrder`] annotation.  Such a grid, if persisted as the layout XML file for the domain class, allows the
 `@MemberOrder` annotation to be removed from the source code of the domain class (but other annotations must be retained).
<6> Takes a normalized grid and enriches it with additional metadata (taken from Apache Isis' internal metadata) that can be represented in the layout XML.  Such a grid, if persisted as the layout XML file for the domain class, allows all layout annotations (xref:rgant.adoc#_rgant_ActionLayout[`@ActionLayout`], xref:rgant.adoc#_rgant_PropertyLayout[`@PropertyLayout`] and xref:rgant.adoc#_rgant_CollectionLayout[`@CollectionLayout`]) to be removed from the source code of the domain class.
<7> Takes a normalized grid and strips out removes all members, leaving only the grid structure.  Such a grid, if persisted as the layout XML file for the domain class, requires that the xref:rgant.adoc#_rgant_MemberOrder[`@MemberOrder`] annotation is retained in the source code of said class in order to bind members to the regions of the grid.


== Implementation

The framework provides `GridSystemServiceBS3`, an implementation that encodes the bootstrap3 grid system.  (The framework
also provides xref:ugvw.adoc[Wicket viewer] components that are capable of interpreting and rendering this metadata).


== Registering the Services

Assuming that the `configuration-and-annotation` services installer is configured (implicit if using the
`AppManifest` to xref:rgcms.adoc#_rgcms_classes_AppManifest-bootstrapping[bootstrap the app]), then the
 Bootstrap3 implementation of `GridSystemService` is automatically registered and injected, and no further
 configuration is required.

To use an alternative implementation, use
xref:rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`] (as explained
further in this xref:ugfun.adoc#_ugfun_how-tos_replacing-default-service-implementations["how to"] tip).




== Related Services

This service is used by xref:rgsvc.adoc#_rgsvc_spi_GridService[`GridService`].
