[[_rgsvc_api_MetaModelService]]
= `MetaModelService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



The `MetaModelService` provides access (albeit currently extremely limited) to aspects of Apache Isis' internal metamodel.

Currently this is limited to looking up the object type (as specified in xref:rgant.adoc#_rgant-DomainObject_objectType[`@DomainObject#objectType()`] and equivalent mechanisms, and as used in  xref:rgsvc.adoc#_rgsvc_api_BookmarkService[`Bookmark`]s and elsewhere) from an object's class, and vice versa.  In the future we expect other aspects of the metamodel to also be formally surfaced through this API.


== API


The API defined by the service is:

[source,java]
----
public interface MetaModelService {
    Class<?> fromObjectType(final String objectType);   // <1>
    String toObjectType(final Class<?> domainType);     // <2>
    void rebuild(final Class<?> domainType);            // <3>
    List<DomainMember> export();                        // <4>
}
----
<1> reverse lookup of a domain class' object type
<2> lookup of a domain class' object type
<3> (`1.12.0-SNAPSHOT`) invalidate and rebuild the internal metadata (an `ObjectSpecification`) for the specified
    domain type.
<4> (`1.12.0-SNAPSHOT`) returns a list of representations of each of member of each domain class.


== Implementation

The framework provides a default implementation of this service (`org.apache.isis.core.metamodel.services.metamodel.MetaModelServiceDefault`).


== Registering the Service

Assuming that the `configuration-and-annotation` services installer is configured (implicit if using the
`AppManifest` to xref:rgcms.adoc#_rgcms_classes_AppManifest-bootstrapping[bootstrap the app]) then Apache Isis' core
implementation of `MetamodelService` service is automatically registered and injected (it is annotated with
`@DomainService`) so no further configuration is required.

To use an alternative implementation, use
xref:rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`] (as explained
in the xref:rgsvc.adoc#_rgsvc_intro_overriding-the-services[introduction] to this guide).


== Related Services

The `MetaModelServiceMenu` (`1.12.0-SNAPSHOT`) provides a method to download all domain members as a CSV.  Internally
this calls `MetaModelService#export()`.
