[[_rgsvc_api_DomainObjectContainer_services-api]]
= Services API
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The services API allows your domain objects to programmatically inject services into arbitrary objects, as well as to look up services by type.

The methods are:

[source,java]
----
public interface DomainObjectContainer {
    <T> T injectServicesInto(final T domainObject);     // <1>
    <T> T lookupService(Class<T> service);              // <2>
    <T> Iterable<T> lookupServices(Class<T> service);   // <3>
    ...
}
----
<1> injects services into domain object; used extensively internally by the framework (eg to inject to other services, or to entities, or integration test instances, or fixture scripts).  Service injection is done automatically if objects are created using `#newTransientInstance()`, described xref:rgsvc.adoc#_rgsvc_api_DomainObjectContainer_object-creation-api[above]
<2> returns the first registered service that implements the specified class
<3> returns an `Iterable` in order to iterate over all registered services that implement the specified class

The primary use case is to instantiate domain objects using a regular constructor ("new is the new new") rather than using the xref:rgsvc.adoc#_rgsvc_api_DomainObjectContainer_object-creation-api[`#newTransientInstance()`] API, and then using the `#injectServicesInto(...)` API to set up any dependencies.

For example:

[source,java]
----
Customer cust = container.injectServicesInto( new Customer());
cust.setFirstName("Freddie");
cust.setLastName("Mercury");
container.persist(cust);
----

