[[_rgsvc_api_ConfigurationService]]
= `ConfigurationService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `ConfigurationService` allows domain objects to read the configuration properties aggregated from the various xref:rgcfg.adoc#_rgcfg_configuration-files[configuration files].


[NOTE]
====
The methods in this service replace similar methods (now deprecated) in xref:rgsvc.adoc#_rgsvc_api_DomainObjectContainer[`DomainObjectContainer`].
====


== API and Usage

The API of `ConfigurationService` is:

[source,java]
----
public interface ConfigurationService {

    String getProperty(String name);                        // <1>
    String getProperty(String name, String defaultValue);   // <2>
    List<String> getPropertyNames();                        // <3>
    Set<ConfigurationProperty> allProperties();             // <4>

}
----
<1> Return the configuration property with the specified name; else return null.
<2> Return the configuration property with the specified name; if it doesn't exist then return the specified default value.
<3> Return the names of all the available properties.
<4> Returns all properties, each as an instance of the `ConfigurationProperty` view model.

For example, here's a fictitious service that might wrap link:http://twitter4j.org/en/configuration.html[Twitter4J]. say:

[source,java]
----
@DomainService(nature=NatureOfService.DOMAIN)
public class TweetService {
    @Programmatic
    @PostConstruct
    public void init() {
        this.oauthConsumerKey = configurationService.getProperty("tweetservice.oauth.consumerKey");
        this.oauthConsumerSecret = configurationService.getProperty("tweetservice.oauth.consumerSecret");
        this.oauthAccessToken = configurationService.getProperty("tweetservice.oauth.accessToken");
        this.oauthAccessTokenSecret = configurationService.getProperty("tweetservice.oauth.accessTokenSecret");
    }
    ...
    @Inject
    ConfigurationService configurationService;
}
----

[TIP]
====
If you _do_ have a domain service that needs to access properties, then note that an alternative is to define a xref:rgant.adoc#_rgant-PostConstruct[`@PostConstruct`] method and pass in a `Map<String,String>` of properties.  The two techniques are almost identical; it's mostly a matter of taste.
====





== Implementation

The core framework provides a default implementation of this service (`o.a.i.core.runtime.services.config.ConfigurationServiceDefault`).




== Registering the Service

Assuming that the `configuration-and-annotation` services installer is configured (implicit if using the
`AppManifest` to xref:rgcms.adoc#_rgcms_classes_AppManifest-bootstrapping[bootstrap the app]) then Apache Isis' core
implementation of `ConfigurationService` service is automatically registered and injected (it is annotated with
`@DomainService`) so no further configuration is required.

To use an alternative implementation, use
xref:rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`] (as explained
in the xref:rgsvc.adoc#_rgsvc_intro_overriding-the-services[introduction] to this guide).



== Related services

The ``ConfigurationServiceMenu`` exposes the ``allConfigurationProperties`` action in the user interface.