[[_rgsvc-spi_ContentMappingService]]
= `ContentMappingService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



The `ContentMappingService` supports the (default implementation of the) xref:rgsvc.adoc#_rgsvc-spi_ContentNegotiationService[`ContentNegotiationService`] allowing the xref:ugvro.adoc#[RestfulObjects viewer] to allow domain objects to be transformed into some other format as specified by the HTTP `Accept` header.

See xref:rgsvc.adoc#_rgsvc-spi_ContentNegotiationService[`ContentNegotiationService`] for further discussion.




== SPI

The SPI defined by this service is:

[source,java]
----
public interface ContentMappingService {
    @Programmatic
    Object map(Object object,                           // <1>
               List<MediaType> acceptableMediaTypes,    // <2>
               RepresentationType representationType);  // <3>

}

----
<1> typically the input is a domain object (whose structure might change over time), and the output is a DTO (whose structure is guaranteed to be preserved over time)
<2> as per the caller's HTTP `Accept` header
<3> the representation type required (as per the link:http://restfulobjects.org[Restful Objects spec]).


[WARNING]
====
This is an "internal" SPI, meaning that it uses types that are not part of the Isis applib.  We do not guarantee that link:http://semver.org[semantic versioning] will be honoured for these APIs.
====


== Implementations

No default implementations are provided by Apache Isis framework itself.  However, the (non-ASF) http://github.com/isisaddons/isis-app-todoapp[Isis addons' todoapp] includes a sample implementation to convert its `ToDoItem`
entity into (two different versions of) a `ToDoItemDto`  (JAXB annotated).  This uses the
link:http://orika-mapper.github.io/orika-docs/intro.html[Orika] mapping library.

The source code is:

[source,java]
----
@DomainService(nature = NatureOfService.DOMAIN)
public class CustomContentMappingService implements ContentMappingService {
    private MapperFactory mapperFactory;                                // <1>
    @Programmatic
    @PostConstruct
    public void init() {
        mapperFactory = new DefaultMapperFactory.Builder().build();
        mapperFactory.registerClassMap(
                mapperFactory.classMap(ToDoItem.class, ToDoItemDto.class)   // <2>
                        .byDefault()                                        // <3>
                        .toClassMap());
        mapperFactory.registerClassMap(
                mapperFactory.classMap(Bookmark.class, OidDto.class)        // <4>
                        .field("identifier", "objectIdentifier")            // <5>
                        .byDefault() // all other fields are compatible     // <6>
                        .toClassMap());
    }
    @Programmatic
    @Override                                                               // <7>
    public Object map(
            final Object object,
            final List<MediaType> acceptableMediaTypes,
            final RepresentationType representationType) {
        if(object instanceof ToDoItem) {
            final Bookmark bookmark = bookmarkService.bookmarkFor(object);
            final ToDoItemDto dto =
                mapperFactory.getMapperFacade().map(object, ToDoItemDto.class); // <8>
            final OidDto oidDto =
                mapperFactory.getMapperFacade().map(bookmark, OidDto.class);    // <9>
            dto.setOid(oidDto);                                                 // <10>
            return dto;
        }
        return null;
    }
    @javax.inject.Inject
    private BookmarkService bookmarkService;
}
----
<1> registry of known mappings
<2> how to map `ToDoItem` to `ToDoItemDto` ...
<3> ... all properties have same name in both source and destination types
<4> how to map `Bookmark` to `OidDto` ...
<5> ... this property has a different name
<6> ... all other properties have same name
<7> the main API to implement.  This implementation ignores the `acceptableMediaTypes` and `representationType`
<8> map the domain object to the DTO
<9> and map its oid (by way of the xref:rgsvc.adoc#_rgsvc-api_BookmarkService[`BookmarkService`]
<10> and perform some additional manual wiring (because domain objects don't _know_ their Oids).

You'll notice that the implementation doesn't actually use the `acceptableMediaTypes` and `representationType` parameters.  That's because the calling `ContentNegotiationServiceXRoDomainType` will double check that the returned object is of the correct type (as defined by the `x-ro-domain-type` parameter of the HTTP `Accept` header).  Since this (example) todoapp only offers a single mapping, there's therefore no need to for the mapping service to check further.



== Related Services

This service is a companion to the default implementation of the xref:rgsvc.adoc#_rgsvc-spi_ContentNegotiationService[`ContentNegotiationService`].