[[_rgsvc_api_DomainObjectContainer_generic-repository-api]]
= Generic Repository API
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



The repository API acts as an abstraction over the JDO/DataNucleus objectstore.  You can use it during prototyping to write naive queries (find all rows, then filter using the Guava `Predicate` API, or you can use it to call JDO link:http://www.datanucleus.org/products/accessplatform_4_0/jdo/query.html#named[named queries] using JDOQL.

As an alternative, you could also use link:http://www.datanucleus.org/products/accessplatform_4_0/jdo/jdoql_typesafe.html[JDO typesafe queries] through the xref:rgsvc.adoc#_rgsvc_api_IsisJdoSupport[`IsisJdoSupport`] service.


[source,java]
----
public interface DomainObjectContainer {
    public <T> List<T> allInstances(Class<T> ofType, long... range);                        // <1>
    <T> List<T> allMatches(Query<T> query);                                                 // <2>
    <T> List<T> allMatches(Class<T> ofType, Predicate<? super T> predicate, long... range); // <3>
    <T> List<T> allMatches(Class<T> ofType, String title, long... range);                   // <4>
    <T> List<T> allMatches(Class<T> ofType, T pattern, long... range);                      // <5>
    ...
}
----
<1> all persisted instances of specified type.  Mostly for prototyping, though can be useful to obtain all instances of domain entities if the number is known to be small.  The optional varargs parameters are for paging control; more on this below.
<2> all persistence instances matching the specified `Query`.  Query itself is an Isis abstraction on top of JDO/DataNucleus' Query API.  *This is the primary API used for querying*
<3> all persistenced instances of specified type matching `Predicate`.  Only really intended for prototyping because in effect constitutes a client-side WHERE clause
<4> all persisted instances with the specified string as their title.  Only very occasionally used
<5> all persisted instances matching object (query-by-example).  Only very occasionally used

There are various implementations of the `Query` API, but these either duplicate functionality of the other overloads of `allMatches(...)` or they are not supported by the JDO/DataNucleus object store.   The only significant implementation of `Query` to be aware of is `QueryDefault`, which identifies a named query and a set of parameter/argument tuples.

For example, in the (non-ASF) http://github.com/isisaddons/isis-app-todoapp[Isis addons' todoapp] the `ToDoItem` is annotated:

[source,java]
----
@javax.jdo.annotations.Queries( {
    @javax.jdo.annotations.Query(
            name = "findByAtPathAndComplete", language = "JDOQL",               // <1>
            value = "SELECT "
                    + "FROM todoapp.dom.module.todoitem.ToDoItem "
                    + "WHERE atPath.indexOf(:atPath) == 0 "                     // <2>
                    + "   && complete == :complete"),                           // <3>
    ...
})
public class ToDoItem ... {
    ...
}
----
<1> name of the query
<2> defines the `atPath` parameter
<3> defines the `complete` parameter

This JDO query definitions are used in the `ToDoItemRepositoryImplUsingJdoql` service:

[source,java]
----
@DomainService(nature = NatureOfService.DOMAIN)
public class ToDoItemRepositoryImplUsingJdoql implements ToDoItemRepositoryImpl {
    @Programmatic
    public List<ToDoItem> findByAtPathAndCategory(final String atPath, final Category category) {
        return container.allMatches(
                new QueryDefault<>(ToDoItem.class,
                        "findByAtPathAndCategory",                              // <1>
                        "atPath", atPath,                                       // <2>
                        "category", category));                                 // <3>
    }
    ...
    @javax.inject.Inject
    DomainObjectContainer container;
}
----
<1> corresponds to the "findByAtPathAndCategory" JDO named query
<2> provide argument for the `atPath` parameter.  The pattern is parameter, argument, parameter, argument, ... and so on.
<3> provide argument for the `category` parameter.  The pattern is parameter, argument, parameter, argument, ... and so on.

Other JDOQL named queries (not shown) follow the exact same pattern.

With respect to the other query APIs, the varargs parameters are optional, but allow for (client-side and managed) paging.  The first parameter is the `start` (0-based, the second is the `count`.

[TIP]
====
It is also possible to query using DataNucleus' type-safe query API.  For more details, see xref:rgsvc.adoc#_rgsvc_api_IsisJdoSupport[`IsisJdoSupport`].
====
