[[_rgsvc_api_SessionManagementService]]
= `SessionManagementService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `SessionManagementService` provides the ability to programmatically manage sessions.  The primary use case is
for fixture scripts or other routines that are invoked from the UI and which create or modify large amounts of data.
A classic example is migrating data from one system to another.



== API

The API of `SessionManagementService` is:


[source,java]
----
public interface SessionManagementService {
    void nextSession();
}
----


Normally, the framework will automatically start a session and then a transaction before each user interaction
(action invocation or property modification), and wil then commit that transaction and close the session after the
interaction has completed.  If the interaction throws an exception then the transaction is aborted.

The `nextSession()` method allows a domain object to commit the transaction, close the session, then open a new
session and start a new transaction.

[IMPORTANT]
====
Any domain objects that were created in the "previous" session are no longer usable, and must not be rendered in the UI.
====



== Implementation

The core framework provides a default implementation of this service (`o.a.i.core.runtime.services.xactn.SessionManagementServiceDefault`).



== Registering the Service

Assuming that the `configuration-and-annotation` services installer is configured (implicit if using the
`AppManifest` to xref:rgcms.adoc#_rgcms_classes_AppManifest-bootstrapping[bootstrap the app]) then Apache Isis' core
implementation of `SessionManagementService` service is automatically registered and injected (it is annotated with
`@DomainService`) so no further configuration is required.

To use an alternative implementation, use
xref:rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`] (as explained
in the xref:rgsvc.adoc#_rgsvc_intro_overriding-the-services[introduction] to this guide).
