[[_ug_core-concepts_building-blocks]]
= Building Blocks
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

NOTE: TODO

## A MetaModel with Explicit and Inferred Semantics

NOTE: TODO

* use of annotations
** reuse JEE annotations where possible
* layout hints are overridable, to avoid restarting the app/speed up feedback


## Domain Objects and Domain Services

NOTE: TODO

* domain model
** domain objects
*** domain entity
*** view model
** domain service
** value type

Anything else can be (should be) ignored by annotating with `@Programmatic`.



## Properties, Collections and Actions

NOTE: TODO


## Domain Entities vs View Models

NOTE: TODO

`@DomainObject(nature=...)`



## Domain Services

Domain services consist of a set of logically grouped actions, and as such follow the same conventions as for entities. However, a service cannot have (persisted) properties, nor can it have (persisted) collections.

Domain services are instantiated once and once only by the framework, and are used to centralize any domain logic that does not logically belong in a domain entity or value. Apache Isis will automatically inject services into every domain entity that requests them, and into each other.

For convenience you can inherit from AbstractService or one of its subclasses, but this is not mandatory.


### Domain Services vs View Services

NOTE: TODO

`@DomainService(nature=...)`

.Factories, Repositories and Services
****
A distinction is sometimes made between a factory (that creates object) and a repository (that is used to find existing objects).  You will find them discussed separately in Evans' link:http://books.google.com/books/about/Domain_Driven_Design.html?id=hHBf4YxMnWMC[Domain Driven Design], for example.

In Apache Isis these are all implemented as domain services.  Indeed, it is quite common to have a domain service that acts as both a factory and a repository.
****




## Value Objects (Primitives)

NOTE: TODO



## Contributions

NOTE: TODO




## Event Bus

NOTE: TODO







