[[_ug_wicket-viewer_customisation_tweaking-css-classes]]
= Tweaking CSS classes
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



The HTML generated by the Wicket viewer include plenty of CSS classes so that you can easily target the required elements as required. For example, you could use CSS to suppress the entity's icon alongside its title. This would be done using:

[source,css]
----
.entityIconAndTitlePanel a img {
    display: none;
}
----

These customizations should generally be added to xref:ug.adoc#_ug_runtime_application-specific_application-css[`application.css]`; this file is included by default in every webpage served up by the Wicket viewer.



== Targeting individual members

For example, the `ToDoItem` object of the Isis addons example https://github.com/isisaddons/isis-app-todoapp/[todoapp] (not ASF) has a `notes` property. The HTML for this will be something like:

[source,html]
----
<div>
    <div class="property ToDoItem-notes">
        <div class="multiLineStringPanel scalarNameAndValueComponentType">
            <label for="id83" title="">
                <span class="scalarName">Notes</span>
                <span class="scalarValue">
                    <textarea
                        name="middleColumn:memberGroup:1:properties:4:property:scalarIfRegular:scalarValue"
                        disabled="disabled"
                        id="id83" rows="5" maxlength="400" size="125"
                        title="">
                    </textarea>
                    <span>
                    </span>
                </span>
            </label>
       </div>
    </div>
</div>
----

The xref:ug.adoc#_ug_runtime_application-specific_application-css[`application.css`] file is the place to add application-specific styles. By way of an example, if (for some reason) we wanted to completely hide the notes value, we could do so using:

[source,css]
----
div.ToDoItem-notes span.scalarValue {
    display: none;
}
----

You can use a similar approach for collections and actions.




== Targeting members through a custom CSS style

The above technique works well if you know the class member to target, but you might instead want to apply a custom style to a set of members. For this, you can use the `@CssClass`.

For example, in the `ToDoItem` class the following annotation (indicating that this is a key, important, property) :

[source,java]
----
@PropertyLayout(cssClass="x-myapp-highlight")
public LocalDate getDueBy() {
    return dueBy;
}
----

would generate the HTML:

[source,html]
----
<div>
    <div class="property ToDoItem-dueBy x-myapp-highlight">
        ...
    </div>
</div>
----

This can then be targeted, for example using:

[source,css]
----
div.x-myapp-highlight span.scalarName {
    color: red;
}
----

Note also that instead of using `@PropertyLayout(cssClass=...)` annotation, you can also specify the CSS style using a xref:rg.adoc#_rg_object-layout_dynamic[dynamic layout] JSON file:

[source,javascript]
----
"dueBy": {
    "propertyLayout": {
        "cssClass": "x-myapp-important"
    }
},
----



