[[_ugbtb_more-advanced_view-models_use-cases]]
= Use Cases
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


When developing an Apache Isis application you will most likely start off with the persistent domain entities:
`Customer`, `Order`, `Product`, and so on.  For some applications this may well suffice.  However, if the application
needs to integrate with other systems, or if the application needs to support reasonably complex business processes, then you may need to look beyond just domain entities.  This section explores these use cases.

== Externally-managed entities

Sometimes the entities that make up your application are persisted not in the local JDO/DataNucleus database
but reside in some other system, for example accessible only through a SOAP web service.  Logically that data
might still be considered a domain entity and we might want to associate behaviour with it, however it cannot be
modelled as a domain entity if only because JDO/DataNucleus doesn't know about the entity nor how to retrieve or
update it.

There are a couple of ways around this: we could either replicate the data somehow from the external system into the
 Isis-managed database (in which case it is once again just another domain entity), or we could set up a stub/proxy for
 the externally managed entity.  This proxy would hold the reference to the externally-managed domain entity (eg an
 external id), as well as the "smarts" to know how to interact with that entity (by making SOAP web service calls etc).

The stub/proxy is a type of view model: a view - if you like - onto the domain entity managed by the external system.

[NOTE]
====
DataNucleus does in fact define its own link:http://www.datanucleus.org/documentation/extensions/store_manager.html[Store Manager] extension point, so an alternative architecture would be to implement this interface such that DataNucleus
could make the calls to the external system; these externally-persisted domain entities would therefore be modelled as regular `@PersistenceCapable` entities after all.  For entities not persisted externally the implementation would delegate down to the default RDBMS-specific `StoreManager` provided by DataNucleus itself.

An implementation that supported only reading from an external entity ought to be comparatively straight-forward, but
implementing one that also supported updating external entities would need to carefully consider error conditions if the
external system is unavailable; distributed transactions are most likely difficult/impossible to implement (and not
desirable in any case).
====


== In-memory entities

As a variation on the above, sometimes there are domain objects that are, conceptually at least entities, but whose
state is not actually persisted anywhere, merely held in-memory (eg in a hash).

A simple example might be read-only configuration data that is read from a config file (eg log4j appender
definitions) but thereafter is presented in the UI just like any other entity.


== Application-layer view models

Domain entities (whether locally persisted using JDO/DataNucleus or managed externally) are the bread-and-butter of Apache Isis applications: the focus after all, should be on the business domain concepts and ensuring that they are
solid.  Generally those domain entities will make sense to the business domain experts: they form the _ubiquitous language_ of the domain.  These domain entities are part of the domain layer.

That said, it may not always be practical to expect end-users of the application to interact solely with those domain
entities.  For example, it may be useful to show a dashboard of the most significant data in the system to a user,
often pulling in and aggregating information from multiple points of the app.  Obtaining this information by hand (by
 querying the respective services/repositories) would be tedious and slow; far better to have a dashboard do the job for
 the end user.

A dashboard object is a model of the most relevant state to the end-user, in other words it is (quite literally) a view
 model.  It is not a persisted entity, instead it belongs to the application layer.

A view model need not merely aggregate data; it could also provide actions of its own.  Most likely these actions will
be queries and will always ultimately just delegate down to the appropriate domain-layer service/repository.  But in
some cases such view model actions might also modify state of underlying domain entities.

Another common use for view models is to help co-ordinate complex business processes; for example to perform a
quarterly invoicing run, or to upload annual interest rates from an Excel spreadsheet.  In these cases the view model
might have some state of its own, but in most cases that state does not need to be persisted per se.

.Desire Lines
****
One way to think of application view models is as modelling the "desire line": the commonly-trod path
that end-users must follow to get from point A to point B as quickly as possible.

To explain: there are link:http://ask.metafilter.com/62599/Where-the-sidewalk-ends[documented]
link:https://sivers.org/walkways[examples]
link:http://www.softpanorama.org/People/Wall/larry_wall_articles_and_interviews.shtml[that] architects of university
campus will only add in paths some while after the campus buildings are complete: let the pedestrians figure out the
routes they want to take.  The name we like best for this idea is "desire lines", though it has also been called
a "desire path", "paving the path" or "paving the sidewalk".

What that means is you should add view models _after_ having built up the domain layer, rather than before.  These view
models pave that commonly-trod path, automating the steps that the end-user would otherwise have to do by hand.

It takes a little practice though, because even when building the domain layer "first", you should still bear in mind
what the use cases are that those domain entities are trying to support.  You certainly _shouldn't_ try to build out a
domain layer that could support every conceivable use case before starting to think about view models.

Instead, you should iterate.  Identify the use case/story/end-user objective that you will deliver value to the
business.  Then build out the minimum domain entities to support that use case (refining the xref:ug.adoc#_ug_core-concepts_philosophy_domain-driven-design_ubiquitous-language[ubiquitous language] as you
go).  Then, identify if there any view models that could be introduced which would simplify the end-user interactions
with the system (perhaps automating several related use cases together).
****

== DTOs (`1.11.0-SNAPSHOT`)

DTOs (data transfer objects) are simple classes that (according to link:https://en.wikipedia.org/wiki/Data_transfer_object[wikipedia]) "carries data between processes".

If those two processes are parts of the same overall application (the same team builds and deploys both server and
client) then there's generally no need to define a DTO; just access the entities using Apache Isis'
xref:ugvro.adoc#[RestfulObjects viewer].

On the other hand, if the client consuming the DTO is a different application -- by which we mean developed/deployed by
a different (possible third-party) team -- then the DTOs act as a formal contract between the provider and the consumer.
In such cases, exposing domain entities over xref:ugvro.adoc#[RestfulObjects] would be
"A Bad Thing"(TM) because the consumer would in effect have access to implementation details that could then not be
easily changed by the producer.

Instead, a view model can be defined to act as a DTO.  To put this formal contract onto a solid footing, this view
model can (as of `1.11.0-SNAPSHOT`) simply be defined as a JAXB-annotated entity; this allows the consumer to obtain
the DTO in XML format along with a corresponding XSD schema describing the structure of that XML.  These XML
representations can be surfaced by the xref:ugvro.adoc#[RestfulObjects viewer] (by implementing
the xref:rg.adoc#_rg_services-spi_manpage-ContentMappingService[`ContentMappingService`]); the XSD can be obtained
using the xref:rg.adoc#_rg_services-api_manpage-JaxbService[`JaxbService`].  Using the formalism of XML also allows
DTOs to be carefully and properly versioned using XML namespaces.

[TIP]
====
If the view model DTO implements the xref:rg.adoc#_rg_classes_mixins_Dto[`Dto`] marker interface, then the framework
will also provide the ability to download the XML or its XSD directly from the UI.
====

In case it's not clear, these DTOs are still usable as "regular" view models; they will render in the xref:ugvw.adoc#[Wicket viewer] just like any other.  Indeed (as the xref:ugbtb.adoc#_ugbtb_more-advanced_view-models_programming-model[programming model] section below makes clear), these
JAXB-annotated view models are in many regards the most powerful of all the view model alternatives.


== ESB Subscribers

One important variation of the DTO use case concerns subscribers on an enterprise event bus such as
link:http://camel.apache.org[Apache Camel(TM)] and similar.

A xref:rg.adoc#_rg_services-spi_manpage-PublishingService[`PublishingService`] implementation (eg that provided by
(non-ASF) http://github.com/isisaddons/isis-module-publishmq[Isis addons' publishmq] module) can publish XML events
onto a message queue, typically representing action invocations within the originating Isis application.  The ESB
(Apache Camel) then dispatches this event to all interested subscribers.  These subscribers represent external systems
in the enterprise, managed by other teams, and so act as the third-party consumers of the data.

Rather than try to anticipate their requirements and push the data that these subscribers might need into the original
XML event (a hopeless task), DTO objects can be defined to allow these consumers to call back to the publishing Isis
application to obtain the data they need.


