[[_ugfun_how-tos_ui-hints_eager-rendering]]
= Eager rendering
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


By default, collections all rendered lazily, in other words in a "collapsed" table view:

NOTE: TODO - screenshot here

For the more commonly used collections we want to show the table expanded:

NOTE: TODO - screenshot here

For this we annotate the collection using the `@CollectionLayout(render=RenderType.EAGERLY`; for example

[source,java]
----
@javax.jdo.annotations.Persistent(table="ToDoItemDependencies")
private Set<ToDoItem> dependencies = new TreeSet<>();
@Collection
@CollectionLayout(
    render = RenderType.EAGERLY
)
public Set<ToDoItem> getDependencies() {
    return dependencies;
}
----

Alternatively, it can be specified the `Xxx.layout.json` file:

[source,javascript]
----
"dependencies": {
    "collectionLayout": {
        "render": "EAGERLY"
    },
}
----

[WARNING]
====
It might be thought that collections that are eagerly rendered should also be eagerly loaded from the database by enabling the `defaultFetchGroup` attribute:

[source,java]
----
@javax.jdo.annotations.Persistent(table="ToDoItemDependencies", defaultFetchGroup="true")
private Set<ToDoItem> dependencies = new TreeSet<>();
...
----

While this can be done, it's likely to be a bad idea, because doing so will cause DataNucleus to query for more data than required even if the object is being rendered within some referencing object's table.

Of course, your mileage may vary, so don't think you can't experiment.
====


