[[_ugfun_faqs_i18n-label-in-wicket-viewer]]
= How i18n Labels in Wicket Viewer?
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

From the Apache Isis mailing list is:

* _I am trying to internationalize the label descriptions of form actions, eg those in `ActionParametersFormPanel`.  Referencing those via their message id inside a .po file didn't work either.  Can this be done?_

At the moment (`1.10.0`) we have a bit of a hybrid story when it comes to i18n.  Most of the i18n does indeed come from the .po files, however certain bits of the UI are "hard-coded", which is to say they rely upon link:https://ci.apache.org/projects/wicket/guide/6.x/guide/i18n.html#i18n_3[ Wicket's internationalization support], namely resource bundles.

So, you can internationalize the labels from this class using the regular resource bundle approach; this is just "vanilla" Wicket: create a directory structure inside the webapp resource folder following that pattern `org.apache.isis.viewer.wicket.ui.components.actions`.  Inside there create an equivalent `ActionParametersFormPanel_xx_XX.properties` or `ActionParametersFormPanel_xx.properties` file for the various locales that you want to support (eg `ActionParametersFormPanel_en_UK.properties`, `ActionParametersFormPanel_en_US.properties`, `ActionParametersFormPanel_de.properties` and so on).

We do have a ticket link:https://issues.apache.org/jira/browse/ISIS-1093[ISIS-1093] to simplify this so that all i18n labels are read from the .po files.

