[[_ugfun_object-layout_dynamic_xml]]
= Dynamic (XML) Layout (`1.12.0-SNAPSHOT`)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



Metadata providing UI hints can be specified either xref:ugfun.adoc#_ugfun_object-layout_static[statically], using annotations, or dynamically using an `Xxx.layout.xml` file (where `Xxx` is the entity or view model object to be rendered).

A corresponding XSD schema for the XML file makes it easy to author such layout files.  It is also possible to download an initial `.layout.xml` - capturing any existing layout metadata using the xref:rgsvc.adoc#_rgsvc_api_MetamodelService[`MetamodelService`] (exposed on the prototyping menu).

[TIP]
====
It is also possible to describe dynamic layouts using a `.layout.json` file, as discussed xref:ugfun.adoc#_ugfun_object-layout_dynamic[here].  As of `1.12.0-SNAPSHOT` the `.layout.json` file should be considered as deprecated: the ``.layout.xml`` file also allows enables much more sophisticated custom layouts than those afforded by ``.layout.json``, and the layout files are easier to write due to the presence of an XSD schema file which ensures that the file is syntactically correct.
====

== Grids vs Components

The XML file distinguishes between two types of element:

* those that define a grid structure, of: rows, columns, tabgroups and tabs. +
+
The rows and columns are closely modelled on link:getbootstrap.com[bootstrap 3] (used in the implementation of the xref:ugvw.adoc[Wicket viewer]).

* those that defines common components, of: fieldsets (previously called member groups or property groups), properties, collections, actions and also the title/icon of the domain object itself.

These two different element types have their own XSD namespaces.  In principle this allows the layout engine