[[_ugfun_how-tos_class-structure_class-definition]]
= Class Definition
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



Apache Isis supports recognises three main types of domain classes:

* domain entities - domain objects persisted to the database using JDO/DataNucleus; for example `Customer`

* domain services - generally singletons, automatically injected, and providing various functionality; for example `CustomerRepository`

* view models - domain objects that are a projection of some state held by the database, in support a particular use case; for example `CustomerDashboard` (to pull together commonly accessed information about a customer).

Domain classes are generally recognized using annotations.
Apache Isis defines its own set of annotations, while entities are annotated using JDO/DataNucleus (though XML can also be used if required).
JAXB can also be used for view models.
Apache Isis recognizes some of the JDO and JAXB annotations and infers domain semantics from these annotations.

You can generally recognize an Apache Isis domain class because it will be probably be annotated using `@DomainObject` and `@DomainService`.
The framework also defines supplementary annotations, `@DomainObjectLayout` and `@DomainServiceLayout`.
These provide hints relating to the layout of the domain object in the user interface.
(Alternatively, these UI hints can be defined in a supplementary xref:ugfun.adoc#_ugfun_object-layout[`.layout.xml`] file.

We use Maven modules as a way to group related domain objects together; we can then reason about all the classes in that module as a single unit.
By convention there will be a single top-level package corresponding to the module.

For example, the (non-ASF) link:https://github.com/incodehq/incode-module-document[Document module] (part of the link:http://catalog.incode.org[Incode Catalog]) has a top-level package of `org.incode.module.document`.
Within the module there may be various subpackages, but its the module defines the namespace.

In the same way that the Java module act as a namespace for domain objects, it's good practice to map domain entities to their own (database) schemas.


[[_ugfun_how-tos_class-structure_class-definition_entities]]
== Entities

Entities are persistent domain objects.
Their persistence is handled by JDO/DataNucleus, which means that it will generally be decorated with both DataNucleus and Apache Isis annotations.
The following is typical:

[source,java]
----
@javax.jdo.annotations.PersistenceCapable(                                      // <1>
        identityType=IdentityType.DATASTORE,                                    // <2>
        schema = "simple",                                                      // <3>
        table = "SimpleObject"
)
@javax.jdo.annotations.DatastoreIdentity(                                       // <4>
        strategy=javax.jdo.annotations.IdGeneratorStrategy.IDENTITY,
        column="id"
)
@javax.jdo.annotations.Version(                                                 // <5>
        strategy= VersionStrategy.DATE_TIME,
        column="version"
)
@javax.jdo.annotations.Queries({
        @javax.jdo.annotations.Query(                                           // <6>
                name = "findByName",
                value = "SELECT "
                        + "FROM domainapp.modules.simple.dom.impl.SimpleObject "
                        + "WHERE name.indexOf(:name) >= 0 ")
})
@javax.jdo.annotations.Unique(name="SimpleObject_name_UNQ", members = {"name"}) // <7>
@DomainObject(                                                                  // <8>
        objectType = "simple.SimpleObject"
)
public class SimpleObject
             implements Comparable<SimpleObject> {                              // <9>

    public SimpleObject(final String name) {                                    // <10>
        setName(name);
    }

    ...

    @Override
    public String toString() {
        return ObjectContracts.toString(this, "name");                          // <11>
    }
    @Override
    public int compareTo(final SimpleObject other) {
        return ObjectContracts.compare(this, other, "name");                    // <9>
    }
}
----
<1> The `@PersistenceCapable` annotation indicates that this is an entity to DataNucleus.
The DataNucleus enhancer acts on the bytecode of compiled entities, injecting lazy loading and dirty object tracking functionality.
Enhanced entities end up also implementing the `javax.jdo.spi.PersistenceCapable` interface.
<2> Indicates how identifiers for the entity are handled.
Using `DATASTORE` means that a DataNucleus is responsible for assigning the value (rather than the application).
<3> Specifies the RDBMS database schema and table name for this entity will reside.
The schema should correspond with the module in which the entity resides.
The table will default to the entity name if omitted.
<4> For entities that are using `DATASTORE` identity, indicates how the id will be assigned.
A common strategy is to allow the database to assign the id, for example using an identity column or a sequence.
<5> The `@Version` annotation is useful for optimistic locking; the strategy indicates what to store in the `version` column.
<6> The `@Query` annotation (usually several of them, nested within a `@Queries` annotation) defines queries using JDOQL.
DataNucleus provides several APIs for defining queries, including entirely programmatic and type-safe APIs; but JDOQL is very similar to SQL and so easily learnt.
<7> DataNucleus will automatically add a unique index to the primary surrogate id (discussed above), but additional alternative keys can be defined using the `@Unique` annotation.
In the example above, the "name" property is assumed to be unique.
<8> The `@DomainObject` annotation identifies the domain object to Apache Isis (not DataNucleus).
It isn't necessary to include this annotation -- at least, not for entities -- but it is nevertheless recommended.
In particular, its strongly recommended that the `objectType` (which acts like an alias to the concrete domain class) is specified; note that it corresponds to the schema/table for DataNucleus' `@PersistenceCapable` annotation.
<9> Although not required, we strongly recommend that all entities are naturally `Comparable`.
This then allows parent/child relationships to be defined using ``SortedSet``s; RDBMS after all are set-oriented.
The `ObjectContracts` utility class provided by Apache Isis makes it easy to implement the `compareTo()` method, but you can also just use an IDE to generate an implementation or roll your own.
<10> Chances are that some of the properties of the entity will be mandatory, for example any properties that represent an alternate unique key to the entity.
In regular Java programming we would represent this using a constructor that defines these mandatory properties, and in Apache Isis/DataNucleus we can likewise define such a constructor.
When DataNucleus rehydrates domain entities from the database at runtime, it actually requires a no-arg constructor (it then sets all state reflectively).
However, there is no need to provide such a no-arg constructor; it is added by the enhancer process.
<11> The `ObjectContracts` utility class also provides assistance for `toString()`, useful when debugging in an IDE.


[[_ugfun_how-tos_class-structure_class-definition_domain-services]]
== Domain Services

Domain services are generally singletons that are automatically injected into other domain services.
A very common usage is as a repository (to find/locate existing entities) or as a factory (to create new instances of entities).
But services can also be exposed in the UI as top-level menus; and services are also used as a bridge to access technical resources (eg rendering a document object as a PDF).

The Apache Isis framework itself also provides a large number of number of domain services, catalogued in the xref:rgsvc.adoc#[Domain Services Reference Guide].
Some of these are APIs (intended to be called by your application's own domain objects) and some are SPIs (implemented by your application and called by the framework, customising the way it works).

The following is a typical menu service:

[source,java]
----
@DomainService(                                                 // <1>
        nature = NatureOfService.VIEW_MENU_ONLY
)
@DomainServiceLayout(                                           // <2>
        named = "Simple Objects",
        menuOrder = "10"
)
public class SimpleObjectMenu {

    ...

    @Action(semantics = SemanticsOf.SAFE)
    @ActionLayout(bookmarking = BookmarkPolicy.AS_ROOT)
    @MemberOrder(sequence = "2")
    public List<SimpleObject> findByName(                       // <3>
            @ParameterLayout(named="Name")
            final String name
    ) {
        return simpleObjectRepository.findByName(name);
    }

    @javax.inject.Inject
    SimpleObjectRepository simpleObjectRepository;              // <4>
}
----
<1> The (Apache Isis) `@DomainService` annotation is used to identify the class as a domain service.
Apache Isis scans the classpath looking for classes with this annotation, so there very little configuration other than to tell the framework which packages to scan underneath.
The `VIEW_MENU_ONLY` nature indicates that this service's actions should be exposed as menu items.
<2> The (Apache Isis) `@DomainServiceLayout` annotation provides UI hints.
In the example above the menu is named "Simple Objects" (otherwise it would have defaulted to "Simple Object Menu", based on the class name, while the `menuOrder` attribute determines the order of the menu with respect to other menu services.
<3> The `findByName` method is annotated with various Apache Isis annotations (`@Action`, `@ActionLayout` and `@MemberOrder`) and is itself rendered in the UI as a "Find By Name" menu item underneath the "Simple Objects" menu.
The implementation delegates to an `SimpleObjectRepository` service, which is injected.
<4> The `javax.inject.Inject` annotation instructs Apache Isis framework to inject the `SimpleObjectRepository` service into this domain object.
The framework can inject into not just other domain services but will also automatically into domain entities and view models.
There is further discussion of service injection xref:ugfun.adoc#_ugfun_how-tos_class-structure_inject-services[below].


[[_ugfun_how-tos_class-structure_class-definition_view-models]]
== View Models

xref:ugbtb.adoc#_ugbtb_view-models[View model]s are similar to entities in that (unlike domain services) there can be many instances of any given type; but they differ from entities in that they are not persisted into a database.
Instead they are recreated dynamically by serializing their state, ultimately into the URL itself.

A common use case for view models is to support a business process.
For example, in an invoicing application there could be an `InvoiceRun` view model, which lists all the invoices due to be paid (each month, say) and provides actions to allow those invoices to be processed.

Another use case is for a view model to act as a proxy for an entity that is managed in an external system.
For example, a `Content` view model could represent a PDF that has been scanned and is held within a separate Content Management system.

A third use case is to define DTOs that act as a stable projection of one or more underlying entities.
Apache Isis' xref:ugvro.adoc[Restful Objects] viewer provides a REST API that then allows REST clients to query the application using these DTOs; useful for integration scenarios.

Apache Isis offers several ways to implement view models, but the most flexible/powerful is to annotate the class using JAXB annotations.
For example:

[source,java]
----
@XmlRootElement(name = "invoiceRun")    // <1>
@XmlType(
        propOrder = {                   // <2>
            ...
        }
)
public class InvoiceRun {
    ...
}
----
<1> The JAXB `@XmlRootElement` annotation indicates this is a view model to Apache Isis, which then uses JAXB to serialize the state of the view model between interactions
<2> All properties of the view model must be listed using the `XmlType#propOrder` attribute.

Use JAXB elements such as `@XmlElement` for properties and the combination of `@XmlElementWrapper` and `@XmlElement` for collections.
Properties can be ignored (for serialization) using `@XmlTransient`.
