[[i18n]]
= i18n
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:


Apache Isis' support for internationlization (i18n) allows every element of the domain model (the class names, property names, action names, parameter names and so forth) to be translated.

It also supports translations of messages raised imperatively, by which we mean as the result of a call to `title()` to obtain an object's title, or messages resulting from any business rule violations (eg xref:applib:cms:methods.adoc#disable[`disable...()`] or xref:applib:cms:methods.adoc#validate[`validate...()`], and so on.

The xref:vw:ROOT:about.adoc[Wicket viewer] (that is, its labels and messages) is also internationalized using the same mechanism.
If no translations are available, then the Wicket viewer falls back to using Wicket resource bundles.

Isis does not translate the values of your domain objects, though.
So, if you have a domain concept such as `Country` whose name is intended to be localized according to the current user, you will need to model this yourself.


== Implementation Approach

Most Java frameworks tackle i18n by using Java's own `ResourceBundle` API.
However, there are some serious drawbacks in this approach, including:

* if a string appears more than once (eg "name" or "description") then it must be translated everywhere it appears in every resource bundle file
* there is no support for plural forms (see this link:http://stackoverflow.com/questions/14326653/java-internationalization-i18n-with-proper-plurals/14327683#14327683[SO answer])
* there is no tooling support for translators

Apache Isis therefore takes a different approach, drawing inspiration from GNU's https://www.gnu.org/software/gettext/manual/index.html[gettext] API and specifically its `.pot` and `.po` files.  These are intended to be used as follows:

* the `.pot` (portable object template) file holds the message text to be translated
* this file is translated into multiple `.po` (portable object) files, one per supported locale
* these `.po` files are renamed according to their locale, and placed into the 'appropriate' location to be picked up by the runtime.
The name of each `.po` resolved in a very similar way to resource bundles.

The format of the `.pot` and `.po` files is identical; the only difference is that the `.po` file has translations for each of the message strings.
These message strings can also have singular and plural forms.


[IMPORTANT]
====
Although Apache Isis' implementation is modelled after GNU's API, it does _not_ use any GNU software.
This is for two reasons: (a) to simplify the toolchain/developer experience, and (b) because GNU software is usually GPL, which would be incompatible with the Apache license.
====

This design tackles all the issues of ``ResourceBundle``s:

* the `.po` message format is such that any given message text to translate need only be translated once, even if it appears in multiple places in the application (eg "Name")
* the `.po` message format includes translations for (optional) plural form as well as singular form
* there are lots of freely available editors https://www.google.co.uk/search?q=.po+file+editor[to be found], many summarized on this https://www.drupal.org/node/11131[Drupal.org] webpage. +
+
In fact, there are also online communities/platforms of translators to assist with translating files.
One such is https://crowdin.com/[crowdin] (nb: this link does not imply endorsement).

In Apache Isis' implementation, if the translation is missing from the `.po` file then the original message text from the `.pot` file will be returned.
In fact, it isn't even necessary for there to be any `.po` files; `.po` translations can be added piecemeal as the need arises.




== `TranslationService`

The cornerstone of Apache Isis' support for i18n is the `TranslationService` service.
This is defined in the applib with the following API:

[source,java]
----
public interface TranslationService {
    public String translate(      // <1>
            final String context,
            final String text);
    public String translate(      // <2>
            final String context,
            final String singularText,
            final String pluralText,
            final int num);
    public enum Mode {
        READ,
        WRITE;
    }
    Mode getMode();               // <3>
}
----
<1> is to translate the singular form of the text
<2> is to translate the plural form of the text
<3> indicates whether the translation service is in read or write mode.

The `translate(...)` methods are closely modelled on GNU's gettext API.
The first version is used when no translation is required, the second is when both a singular and plural form will be required, with the `num` parameter being used to select which is returned.
In both cases the `context` parameter provides some contextual information for the translator; this generally corresponds to the class member.

The mode meanwhile determines the behaviour of the service.  More on this below.



=== `TranslationServicePo`

Isis provides a default implementation of `TranslationService`, namely `TranslationServicePo`.

If the service is running in the normal read mode, then it simply provides translations for the locale of the current user.
This means locates the appropriate `.po` file (based on the requesting user's locale), finds the translation and returns it.

If however the service is configured to run in write mode, then it instead records the fact that the message was requested to be translated (a little like a spy/mock in unit testing mock), and returns the original message.
The service can then be queried to discover which messages need to be translated.
All requested translations are written into the `.pot` file.

To make the service as convenient as possible to use, the service configures itself as follows:

* if running in prototype mode xref:cfg:ROOT:deployment-types.adoc[deployment type] or during integration tests, then the service runs in *write* mode, in which case it records all translations into the `.pot` file.
The `.pot` file is written out when the system is shutdown.
* if running in server (production) mode xref:cfg:ROOT:deployment-types.adoc[deployment type], then the service runs in *read* mode.
It is also possible to set a configuration setting in `isis.properties` to force read mode even if running in prototype mode (useful to manually test/demo the translations).

When running in write mode the original text is returned to the caller untranslated.
If in read mode, then the translated `.po` files are read and translations provided as required.



== Imperative messages

The `TranslationService` is used internally by Apache Isis when building up the metamodel; the name and description of every class, property, collection, action and action parameter is automatically translated.
Thus the simple act of bootstrapping Apache Isis will cause most of the messages requiring translation (that is: those for the Apache Isis metamodel) to be captured by the `TranslationService`.

However, for an application to be fully internationalized, any validation messages (from either `disableXxx()` or `validateXxx()` supporting methods) and also possibly an object's title (from the `title()` method) will also require translation.
Moreover, these messages must be captured in the `.pot` file such that they can be translated.


=== `TranslatableString`

The first part of the puzzle is tackled by an extension to Apache Isis' programming model.
Whereas previously the `disableXxx()` / `validateXxx()` / `title()` methods could only return a `java.lang.String`, they may now optionally return a `TranslatableString` (defined in Isis applib) instead.

Here's a (silly) example from the xref:simpleapp:ROOT:about.adoc[SimpleApp archetype]:

[source,java]
----
public TranslatableString validateUpdateName(final String name) {
    return name.contains("!")? TranslatableString.tr("Exclamation mark is not allowed"): null;
}
----

This corresponds to the following entry in the `.pot` file:

[source,ini]
----
#: dom.simple.SimpleObject#updateName()
msgid "Exclamation mark is not allowed"
msgstr ""
----

The full API of `TranslatableString` is modelled on the design of GNU gettext (in particular the https://code.google.com/p/gettext-commons/wiki/Tutorial[gettext-commons] library):

[source,java]
----
public final class TranslatableString {
    public static TranslatableString tr(       // <1>
            final String pattern,
            final Object... paramArgs) { /* ... */ }
    public static TranslatableString trn(      // <2>
            final String singularPattern,
            final String pluralPattern,
            final int number,
            final Object... paramArgs) { /* ... */ }
    public String translate(                   // <3>
            final TranslationService translationService,
            final String context) { /* ... */ }
}
----
<1> returns a translatable string with a single pattern for both singular and plural forms.
<2> returns a translatable string with different patterns for singular and plural forms; the one to use is determined by the 'number' argument
<3> translates the string using the provided `TranslationService`, using the appropriate singular/regular or plural form, and interpolating any arguments.

The interpolation uses the format `\{xxx}`, where the placeholder can occur multiple times.

For example:

[source,java]
----
final TranslatableString ts = TranslatableString.tr(
    "My name is {lastName}, {firstName} {lastName}.",
    "lastName", "Bond", "firstName", "James");
----

would interpolate (for the English locale) as "My name is Bond, James Bond".

For a German user, on the other hand, if the translation in the corresponding `.po` file was:

[source,ini]
----
#: xxx.yyy.Whatever#context()
msgid "My name is {lastName}, {firstName} {lastName}."
msgstr "Ich heisse {firstName} {lastName}."
----

then the translation would be: "Ich heisse James Bond".


The same class is used in xref:applib:svc:core-domain-api/MessageService.adoc[`MessageService`] so that you can raise translatable info, warning and error messages; each of the relevant methods are overloaded.

For example:

[source,java]
----
public interface MessageService {
    void informUser(String message);
    void informUser(
        TranslatableMessage message,
        final Class<?> contextClass, final String contextMethod); // <1>
    ...
}
----
<1> are concatenated together to form the context for the `.pot` file.



=== `TranslatableException`

Another mechanism by which messages can be rendered to the user are as the result of exception messages thrown and recognized by an xref:applib:svc:presentation-layer-spi/ExceptionRecognizer.adoc[`ExceptionRecognizer`].

In this case, if the exception implements `TranslatableException`, then the message will automatically be translated before being rendered.
The `TranslatableException` itself takes the form:

[source,java]
----
public interface TranslatableException {
    TranslatableString getTranslatableMessage(); // <1>
    String getTranslationContext();              // <2>
}

----
<1> the message to translate.
If returns `null`, then the `Exception#getMessage()` is used as a fallback
<2> the context to use when translating the message




== Wicket Viewer

The xref:vw:ROOT:about.adoc[Wicket viewer] (its labels and messages) is also internationalized using
the `TranslationService`.
This is done through an Isis-specific implementation of the Wicket framework's `org.apache.wicket.Localizer` class, namely `LocalizerForIsis`.

The Wicket `Localizer` defines the following API:

[source,java]
----
public String getString(
        final String key,               // <1>
        final Component component,      // <2>
        final IModel<?> model,
        final Locale locale,
        final String style,
        final String defaultValue)
    throws MissingResourceException { /* ... */ }
----
<1> The key to obtain the resource for
<2> The component to get the resource for (if any)

For example, `key` might be a value such as "okLabel", while `component` an internal class of the Wicket viewer, such as `EntityPropertiesForm`.

The `LocalizerForIsis` implementation uses the `key` as the `msgId`, while the fully qualified class name of the `component` is used as a context.
There is one exception to this: if the component is the third-party select2
component (used for drop-downs), then that class name is used directly.

In the main, using Isis' i18n support means simply adding the appropriate translations to the `translation.po` file, for each locale that you require.
If the translations are missing then the original translations from the Wicket resource bundles will be used instead.


=== Commonly used

Most of the translation requirements can be covered by adding in the following ``msgId``s:

[source,properties]
----
#: org.apache.isis.viewer.wicket.ui.pages.entity.EntityPage
msgid "CollectionContentsAsAjaxTablePanelFactory.Table"
msgstr "Table"

#: org.apache.isis.viewer.wicket.ui.pages.entity.EntityPage
msgid "CollectionContentsAsUnresolvedPanel.Hide"
msgstr "Hide"

#: org.apache.isis.viewer.wicket.ui.pages.entity.EntityPage
msgid "aboutLabel"
msgstr "About"

#: org.apache.isis.viewer.wicket.ui.pages.entity.EntityPage
msgid "cancelLabel"
msgstr "Cancel"

#: org.apache.isis.viewer.wicket.ui.pages.entity.EntityPage
msgid "datatable.no-records-found"
msgstr "No Records Found"

#: org.apache.isis.viewer.wicket.ui.pages.entity.EntityPage
msgid "editLabel"
msgstr "Edit"

#: org.wicketstuff.select2.Select2Choice
msgid "inputTooShortPlural"
msgstr "Please enter {number} more characters"

#: org.wicketstuff.select2.Select2Choice
msgid "inputTooShortSingular"
msgstr "Please enter 1 more character"

#: org.wicketstuff.select2.Select2Choice
msgid "loadMore"
msgstr "Load more"

#: org.apache.isis.viewer.wicket.ui.pages.entity.EntityPage
msgid "logoutLabel"
msgstr "Logout"

#: org.wicketstuff.select2.Select2Choice
msgid "noMatches"
msgstr "No matches"

#: org.apache.isis.viewer.wicket.ui.pages.entity.EntityPage
msgid "okLabel"
msgstr "OK"

#: org.wicketstuff.select2.Select2Choice
msgid "searching"
msgstr "Searching..."

#: org.wicketstuff.select2.Select2Choice
msgid "selectionTooBigPlural"
msgstr "You can only select {limit} items"

#: org.wicketstuff.select2.Select2Choice
msgid "selectionTooBigSingular"
msgstr "You can only select 1 item"
----

=== Login/self-sign-up

In addition, there are a reasonably large number of messages that are used for both login and the
 xref:vw:ROOT:features/user-registration.adoc[user registration] (self sign-up) and password reset features.

These are:

[source,properties]
----
#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
msgid "AutoLabel.CSS.required"
msgstr "Required"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "confirmPasswordLabel"
msgstr "Confirm password"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
msgid "emailIsNotAvailable"
msgstr "The given email is already in use"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "emailPlaceholder"
msgstr "Enter your email"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
msgid "emailPlaceholder"
msgstr "Enter an email for the new account"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "emailLabel"
msgstr "Email"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "emailSentMessage"
msgstr "An email has been sent to '${email}' for verification."

#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
msgid "forgotPasswordLinkLabel"
msgstr "Forgot your password?"

#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
msgid "loginHeader"
msgstr "Login"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "noSuchUserByEmail"
msgstr "There is no account with this email"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "noUserForAnEmailValidToken"
msgstr "The account seems to be either already deleted or has changed its email address. Please try again."

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "passwordChangeSuccessful"
msgstr "The password has been changed successfully. You can <a class=\"alert-success\" style=\"text-decoration:underline;\" href=\"${signInUrl}\">login</a> now."

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "passwordChangeUnsuccessful"
msgstr "There was a problem while updating the password. Please try again."

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "passwordLabel"
msgstr "Password"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "passwordPlaceholder"
msgstr "Enter password"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "passwordResetExpiredOrInvalidToken"
msgstr "You are trying to reset the password for an expired or invalid token"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "passwordResetHeader"
msgstr "Forgot password"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "passwordResetSubmitLabel"
msgstr "Submit"

#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
msgid "registerButtonLabel"
msgstr "Register"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
msgid "registerHeader"
msgstr "Register"

#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
msgid "rememberMeLabel"
msgstr "Remember Me"

#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
msgid "resetButtonLabel"
msgstr "Reset"

#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
msgid "signInButtonLabel"
msgstr "Sign in"

#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
msgid "signUpButtonLabel"
msgstr "Don't have an account? Sign up now."

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "signUpButtonLabel"
msgstr "Verify email"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
msgid "signUpHeader"
msgstr "Sign Up"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "usernameIsNotAvailable"
msgstr "The provided username is already in use"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "usernameLabel"
msgstr "Username"

#: org.apache.isis.viewer.wicket.ui.pages.accmngt.signup.RegistrationFormPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.register.RegisterPage
#: org.apache.isis.viewer.wicket.ui.pages.login.WicketSignInPage
#: org.apache.isis.viewer.wicket.ui.pages.accmngt.password_reset.PasswordResetPage
msgid "usernamePlaceholder"
msgstr "Username"
----






== Integration Testing

So much for the API; but as noted, it is also necessary to ensure that the required translations are recorded (by the `TranslationService`) into the `.pot` file.

For this, we recommend that you ensure that all such methods are tested through an xref:integ-test-support:ROOT:about.adoc[integration test] (not unit test).

For example, here's the corresponding integration test for the "Exclamation mark" example from the simpleapp (above):

[source,java]
----
@Rule
public ExpectedException expectedException = ExpectedException.none();

@Inject
FixtureScripts fixtureScripts;

@Test
public void failsValidation() throws Exception {
    // given
    RecreateSimpleObjects fs = new RecreateSimpleObjects().setNumber(1);
    fixtureScripts.runFixtureScript(fs, null);
    SimpleObject simpleObjectWrapped = wrap(fs.getSimpleObjects().get(0));

    // expect
    expectedExceptions.expect(InvalidException.class);
    expectedExceptions.expectMessage("Exclamation mark is not allowed");

    // when
    simpleObjectWrapped.updateName("new name!");
}
----

Running this test will result in the framework calling the `validateUpdateName(...)` method, and thus to record that a translation is required in the `.pot` file.

When the integration tests are complete (that is, when Apache Isis is shutdown), the `TranslationServicePo` will write out all captured translations to its log (more on this below).
This will include all the translations captured from the Apache Isis metamodel, along with all translations as exercised by the integration tests.

To ensure your app is fully internationalized app, you must therefore:

* use `TranslatableString` rather than `String` for all validation/disable and title methods.
* ensure that (at a minimum) all validation messages and title methods are integration tested.

[NOTE]
====
We make no apologies for this requirement: one of the reasons that we decided to implement Apache Isis' i18n support in this way is because it encourages/requires the app to be properly tested.

Behind the scenes Apache Isis uses a JUnit rule (`ExceptionRecognizerTranslate`) to intercept any exceptions that are thrown.
These are simply passed through to the registered xref:applib:svc:presentation-layer-spi/ExceptionRecognizer.adoc[`ExceptionRecognizer`]s so that any messages are recorded as requiring translation.
====




== Escaped strings

Translated messages can be escaped if required, eg to include embedded markup.

[source,ini]
----
#: com.mycompany.myapp.OrderItem#quantity
msgid "<i>Quantity</i>"
msgstr "<i>Quantité</i>"
----

For this to work, the `namedEscaped()` attribute must be specified using either the xref:vw:ROOT:layout/file-based.adoc[layout file], or using an annotation such as xref:applib:ant:PropertyLayout.adoc[`@PropertyLayout`] or xref:applib:ant:ParameterLayout.adoc[`@ParameterLayout`].

For example:

[source,java]
----
@ParameterLayout(
    named="<i>Quantity</i>",      // <1>
    namedEscaped=false
)
public Integer getQuantity() { /* ... */ }
----
<1> required (even though it won't be used when a translation is read; otherwise the escaped flag is ignored)




== Configuration

There are several different aspects of the translation service that can be configured.

=== Logging

To configure the `TranslationServicePo` to write to out the `translations.pot` file, add the following to the _integtests_ `logging.properties` file:

[source,ini]
----
log4j.appender.translations-po=org.apache.log4j.FileAppender
log4j.appender.translations-po.File=./translations.pot
log4j.appender.translations-po.Append=false
log4j.appender.translations-po.layout=org.apache.log4j.PatternLayout
log4j.appender.translations-po.layout.ConversionPattern=%m%n

log4j.logger.org.apache.isis.core.runtime.services.i18n.po.PoWriter=INFO,translations-po
log4j.additivity.org.apache.isis.core.runtime.services.i18n.po.PotWriter=false
----

Just to repeat, this is _not_ the `WEB-INF/logging.properties` file, it should instead be added to the `integtests/logging.properties` file.

=== Location of the `.po` files

The default location of the translated `.po` files is in the `WEB-INF` directory.
These are named and searched for similarly to regular Java resource bundles.

For example, assuming these translations:

[source,ini]
----
/WEB-INF/translations-en-US.po
        /translations-en.po
        /translations-fr-FR.po
        /translations.po
----

then:

* a user with `en-US` locale will use `translations-en-US.po`
* a user with `en-GB` locale will use `translations-en.po`
* a user with `fr-FR` locale will use `translations-fr-FR.po`
* a user with `fr-CA` locale will use `translations.po`

The basename for translation files is always `translations`; this cannot be altered.


=== Externalized translation files

Normally Apache Isis configuration files are read from the `WEB-INF` file.
However, Apache Isis can be configured to read config files from an xref:ug:btb:about.adoc#externalized-configuration[external directory]; this is also supported for translations.

Thus, if in `web.xml` the external configuration directory has been set:

// TODO: v2: this almost certainly no longer works, because we now set up configuration very early on.

[source,xml]
----
<context-param>
    <param-name>isis.config.dir</param-name>
    <param-value>location of external config directory</param-value>
</context-param>
----

Then this directory will be used as the base for searching for translations (rather than the default 'WEB-INF/' directory).

=== Force read mode, or disable

As noted above, if running in prototype mode then `TranslationServicePo` will be in write mode, if in production mode then will be in read mode.
To force read mode (ie use translations) even if in prototype mode, add the following configuration property to `isis.properties`:

[source,ini]
----
isis.services.translation.po.mode=read
----

It's also possible to disable the service completely (using values 'disable' or 'disabled').
This can sometimes be useful in integration tests.

[source,ini]
----
isis.services.translation.po.mode=disable
----

== Supporting services

The `TranslationServicePo` has a number of supporting/related services.

=== `LocaleProvider`

The `LocaleProvider` API is used by the `TranslationServicePo` implementation to obtain the locale of the "current user".

A default implementation is provided by the Wicket viewer.

[NOTE]
====
Note that this default implementation does not support requests made through the Restful Objects viewer (there is no Wicket 'application' object available); the upshot is that requests through Restful Objects are never translated.
Registering a different implementation of `LocaleProvider` that taps into appropriate REST (RestEasy?) APIs would be the way to address this.
====


=== `TranslationsResolver`

The `TranslationResolver` is used by the `TranslationService` implementation to lookup translations for a specified locale.
It is this service that reads from the `WEB-INF/` (or externalized directory).


=== `TranslationServicePoMenu`

The `TranslationServicePoMenu` provides a couple of menu actions in the UI (prototype mode only) that interacts with the underlying `TranslationServicePo`:

* the `downloadTranslationsFile()` action - available only in write mode - allows the current `.pot` file to be downloaded. +
+
[NOTE]
====
While this will contain all the translations from the metamodel, it will not necessarily contain all translations for all imperative methods returning `TranslatableString` instances; which are present and which are missing will depend on which imperative methods have been called (recorded by the service) prior to downloading.
====

* the `clearTranslationsCache()` action - available only in read mode - will clear the cache so that new translations can be loaded. +
+
This allows a translator to edit the appropriate `translations-xx-XX.po` file and check the translation is correct without having to restart the app.




