= Configuration Properties
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



== Applib


[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.applib.adoc[]

|===



== Core Meta Model

General configuration:

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.core.meta-model.adoc[]

|===


The `isis.core.meta-model.filter-visibility` configuration property that influences whether a returned object is visible to the end-user:

* Action invocations:
+
If an action returns a collection that includes the object, then the object will be excluded from the list when rendered.
If it returns a single object and the user does not have access to that object, then the action will seemingly return `null`

* Collections:
+
If a parent object has a collection references another object to which the user does not have access, then (as for actions) the object will not be rendered in the list

* Properties:
+
If an parent object has a (scalar) reference some other object to which the user does not have access, then the reference will be rendered as empty.

* Choices and autoComplete lists:
+
If an object is returned in a list of choices or within an auto-complete list, and the user does not have access, then it is excluded from the rendered list.

The original motivation for this feature was to transparently support such features as multi-tenancy (as per the xref:security:ROOT:about.adoc[SecMan extension]).
That is, if an entity is logically "owned" by a user, then the multi-tenancy support can be arranged to prevent some other user from viewing that object.

By default this configuration property is enabled.  To disable the visibility filtering, set the appropriate configuration property to `false`:

[source,ini]
----
isis.core.meta-model.filter-visibility=false
----

Filtering is supported by the xref:vw:ROOT:about.adoc[Wicket viewer] and the xref:vro:ROOT:about.adoc[Restful Objects viewer], and also by the xref:refguide:applib-svc:application-layer-api/WrapperFactory.adoc[`WrapperFactory`] domain service (provided the wrapper's execution mode is __not__ "skip rules").

[NOTE]
====
In order for the framework to perform this filtering of collections, be aware that the framework takes a _copy_ of the original collection, filters on the collection, and returns that filtered collection rather than the original.

There are no major side-effects from this algorithm, other than the fact that the referenced objects will (most likely) need to be resolved in order to determine if they are visible.
This could conceivably have a performance impact in some cases.
====

=== Introspection

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.core.meta-model.introspector.adoc[]

|===


The framework performs classpath scanning to identify all domain classes (domain services, mixins, entities, view models and fixture scripts), and the class-level facets for all of these are always created during bootstrapping.

In addition, the members for all domain services and mixins are also created, because these can give rise to contributed members of the entities/view models.

Lazy introspection means that the class members (properties, collections and actions) and their respective facets are _not_ created for all of the entities/view models in the domain model.
Instead these are created only on first access.
The purpose of this is primarily to speed up bootstrapping during development.

To enable lazy introspection, either set the `isis.reflector.introspect.mode` configuration property to "lazy" or to "lazy_unless_production" (the latter only if also running with a deployment type of "production").

However, the trade-off is that metamodel validation is _not_ performed in lazy mode.

[TIP]
====
Note that integration tests are run in `production` mode, and so by default these perform full introspection.
This can be overridden when calling the superclass (`IntegrationTestAbstract3`)'s contributor with `IntrospectionMode.LAZY`.
====

=== Validator

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.core.meta-model.validator.adoc[]

|===




== Core Runtime

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.core.runtime.adoc[]

|===




== Core Runtime Services

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.core.runtime-services.adoc[]

|===





== JDO DataNucleus Persistence

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.persistence.jdo-datanucleus.adoc[]


|===



== JDO DN Pass-thru

The values of these configuration properties are passed through unchanged, with the `isis.persistence.jdo-datanucleus.impl` prefix stripped off.

[NOTE]
====
Configuration properties keys under `datanucleus` need to be specified in `camelCase`.

Configuration properties keys under `javax.jdo.option` need to be specified in `PascalCase`.
====

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.persistence.jdo-datanucleus.impl.adoc[]

|===


== Shiro Security

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description


include::refguide:config:example$generated/isis.security.shiro.adoc[]

|===



== Restful Objects Viewer

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.viewer.restfulobjects.adoc[]

|===



== Wicket Viewer

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.viewer.wicket.adoc[]

|===


== Testing

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.testing.adoc[]

|===


== Value Types

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.value-types.adoc[]

|===


ifdef::env-this-stuff-is-currently-disabled[]

== Subdomains

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.subdomains.adoc[]

|===

== Mappings

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.mappings.adoc[]

|===

endif::[]

== Extensions

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.extensions.adoc[]

|===


ifdef::env-this-stuff-is-currently-disabled[]

== Incubator

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.incubator.adoc[]

|===

endif::[]


== Legacy

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/isis.legacy.adoc[]

|===


== 3rd Party

These configuration options are defined by 3rd party libraries (dependency of the Apache Isis framework) that nevertheless significantly impact the behaviour of the framework.

=== RestEasy

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/resteasy.adoc[]

|===





== Other

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description

include::refguide:config:example$generated/Other.adoc[]

|===


