Title: Suppressing Elements of the Representations

____

Enabling these settings makes the representations non-standard with respect to the http://restfulobjects.org[Restful Object spec].
In the future the spec may be updated to allow such extensions.

____

{note
These configuration settings should be considered beta, and are likely to change in the future in response to emerging requirements
}

The representations specified by the http://restfulobjects.org[Restful Object spec] are very rich in hypermedia
controls and metadata, intended to support a wide variety of possible REST clients. However, if an application is
providing its REST API only for a small well-defined set of REST clients, then it is possible to suppress (remove)
various elements of these representations.

== Global Configuration

Suppressing of elements can be done using globally using the following properties (typically added to
`WEB-INF/viewer_restfulobjects.properties`):

[source]
----
isis.viewer.restfulobjects.suppressDescribedByLinks=true
isis.viewer.restfulobjects.suppressUpdateLink=true
isis.viewer.restfulobjects.suppressMemberId=true
isis.viewer.restfulobjects.suppressMemberLinks=true
isis.viewer.restfulobjects.suppressMemberExtensions=true
isis.viewer.restfulobjects.suppressMemberDisabledReason=true
----

where, respectively, these suppress:

* "describedby" links (on all representations)
* "update" link (on object representation)
* "id" json-prop for object members (on object representation and member detail representations)
* "links" json-prop for object members (on the object representation and member detail representations)
* "extensions" json-prop for object members (on the object representation and member detail representations)
* "disabledReason" json-prop for object members (on the object representation and member detail representations)

The defaults for all of these is false, meaning that the hypermedia/metadata is NOT suppressed.

[NOTE]
====
In the future we might extend this per-request.  Raise/vote on a JIRA ticket if you require this feature.
====

== See also

If even simpler representations (of objects) are required, see link:simplified-object-representation.html[here].

If complete control over all representations is required, see link:custom-representations.html[here].