:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The `multiLine` attribute indicates that a textbox of the specified number of lines should be used to render a property or parameter:

* for properties, the attribute can be specified using the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/PropertyLayout.html#multiline[@PropertyLayout#multiLine] attribute, or using the link:https://causeway.apache.org/userguide/2.0.0-RC1/fun/ui.html#by-example[.layout.xml] layout file.

* for parameters, the attribute can be specified using the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/PropertyLayout.html#multiline[@ParameterLayout#multiLine] annotation.

The attribute is currently supported only for properties and parameters of type ``String``s.

== How this demo works

This page declares several properties, all of which are annotated to be rendered as `multiLine`.

=== Annotated

The `multiline` attribute can be specified explicitly using an annotation:

* for properties, using `@PropertyLayout#multiLine()`:
+
[source,java,indent=0]
----
include::PropertyLayoutMultiLinePage.java[tags=annotation]
----
<.> explicitly specifies that the property should use a textbox

* for parameters, using `@ParameterLayout#multiLine()`:
+
[source,java,indent=0]
----
include::PropertyLayoutMultiLinePage_updateWithParameterLayout.java[tags=annotation]
----
<.> explicitly specifies that the parameter should use a textbox

=== Layout File

For properties (not parameters), the `multiline` attribute can be specified using the `Xxx.layout.xml` file:

* property definition:
+
[source,java,indent=0]
----
include::PropertyLayoutMultiLinePage.java[tags=layout-file]
----
<.> `multiLine` hint is _not_ present.

* layout file snippet:
+
[source,xml,indent=0,tabsize=4]
----
<cpt:property id="propertyUsingLayout" multiLine="5"/>
----

One advantage of the layout file over the annotation is that the layout file is dynamic: it can be modified and the changes reloaded in a running application.

