= RoleMemento
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Immutable serializable value held by xref:refguide:applib:index/services/user/UserMemento.adoc[UserMemento] .

== API

[source,java]
.RoleMemento.java
----
class RoleMemento {
  public static final String LOGICAL_TYPE_NAME;
  RoleMemento(String name)     // <.>
  RoleMemento(String name, String description)     // <.>
}
----

<.> xref:#RoleMemento__String[RoleMemento(String)]
+
--
Creates a new role with the specified name. Description is left blank.
--
<.> xref:#RoleMemento__String_String[RoleMemento(String, String)]
+
--
Creates a new role with the specified name and description.
--

== Members

[#RoleMemento__String]
=== RoleMemento(String)

Creates a new role with the specified name. Description is left blank.

[#RoleMemento__String_String]
=== RoleMemento(String, String)

Creates a new role with the specified name and description.
