= UserMemento
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Immutable serializable value holding details about a user and its roles.

== API

[source,java]
.UserMemento.java
----
class UserMemento {
  public static final String LOGICAL_TYPE_NAME;
  UserMemento system()     // <.>
  UserMemento ofName(String name)     // <.>
  UserMemento ofNameAndRoles(String name, RoleMemento... roles)     // <.>
  UserMemento ofNameAndRoleNames(String name, String... roleNames)     // <.>
  UserMemento ofNameAndRoleNames(String name, List<String> roleNames)     // <.>
  UserMemento ofNameAndRoleNames(String name, Stream<String> roleNames)     // <.>
  List<RoleMemento> getRoles()     // <.>
  UserMemento withRoleAdded(String role)
  boolean isCurrentUser(String userName)     // <.>
  Stream<String> streamRoleNames()
  boolean hasRoleName(String roleName)
  UserMementoBuilder asBuilder()
  UserLocale asUserLocale()
}
----

<.> xref:#system__[system()]
+
--
The framework's internal user with unrestricted privileges.
--
<.> xref:#ofName__String[ofName(String)]
+
--
Creates a new user with the specified name and no roles.
--
<.> xref:#ofNameAndRoles__String_RoleMemento[ofNameAndRoles(String, RoleMemento)]
+
--
Creates a new user with the specified name and assigned roles.
--
<.> xref:#ofNameAndRoleNames__String_String[ofNameAndRoleNames(String, String)]
+
--
Creates a new user with the specified name and assigned role names.
--
<.> xref:#ofNameAndRoleNames__String_List[ofNameAndRoleNames(String, List)]
+
--
Creates a new user with the specified name and assigned role names.
--
<.> xref:#ofNameAndRoleNames__String_Stream[ofNameAndRoleNames(String, Stream)]
+
--
Creates a new user with the specified name and assigned role names.
--
<.> xref:#getRoles__[getRoles()]
+
--
The roles associated with this user.
--
<.> xref:#isCurrentUser__String[isCurrentUser(String)]
+
--
Determine if the specified name is this user.
--

== Members

[#system__]
=== system()

The framework's internal user with unrestricted privileges.

[#ofName__String]
=== ofName(String)

Creates a new user with the specified name and no roles.

[#ofNameAndRoles__String_RoleMemento]
=== ofNameAndRoles(String, RoleMemento)

Creates a new user with the specified name and assigned roles.

[#ofNameAndRoleNames__String_String]
=== ofNameAndRoleNames(String, String)

Creates a new user with the specified name and assigned role names.

[#ofNameAndRoleNames__String_List]
=== ofNameAndRoleNames(String, List)

Creates a new user with the specified name and assigned role names.

[#ofNameAndRoleNames__String_Stream]
=== ofNameAndRoleNames(String, Stream)

Creates a new user with the specified name and assigned role names.

[#getRoles__]
=== getRoles()

The roles associated with this user.

[#isCurrentUser__String]
=== isCurrentUser(String)

Determine if the specified name is this user.

