:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObjectLayout.html#cssclass[@DomainObjectLayout#cssClass] attribute indicates a CSS class which is added to the HTML wherever an instance of that domain class (type) is rendered.

The idea is that corresponding styling is added to the `css/application.css` file that the framework's UI references in every response, so that certain domain classes -- perhaps the most important ones in the domain -- are always rendered with their own specific styling.

== How this demo works

The collection on the left shows a list of entities where the `cssClass` attribute has been set to a value of "custom".
Custom CSS in `application.css` shows that they are rendered in italics and also in red, differently to the lists you will see on other demo pages.
Navigate into one of these entities and -- again -- the custom CSS is used to change the styling of their title as using italics and coloured red.

In terms of code:

* the attribute applied to the entity:
+
[source,css]
.DomainObjectLayoutCssClass.java
----
include::DomainObjectLayoutCssClassEntity.java[tags=class]
----
<.> specifies the "custom" CSS class

* the following shows the changes that have been made to `application.css` to effect this:
+
[source,css]
.application.css
----
tr.even.custom > td,
tr.odd.custom > td,
.entityPage.custom .iconAndTitle span
{
    font-style: italic;
    color: orangered;
}
----


=== See also

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib-methods/ui-hints/cssClass.html[cssClass()] method provides an alternative mechanism for specifying a custom CSS class for an object.
The difference though is that `cssClass()` is dynamic (whereas the `@DomainObjectLayout#cssClass` attribute is static).

A common use case for `cssClass()` is to reflect the state of an object that has a lifecycle, such as an `Order` with an `orderStatus`.
The colour used for a NEW order might be different from that for an CONFIRMED order, while a DISCARDED order might be rendered using [line-through]#strikethrough#.

