= LayoutExportStyle _(enum)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Format option when generating a layout file (while prototyping).

Once a layout file is in place, its layout data takes precedence over any conflicting layout data from annotations.

== API

[source,java]
.LayoutExportStyle.java
----
enum LayoutExportStyle {
  COMPLETE     // <.>
  MINIMAL     // <.>
  LayoutExportStyle defaults()
}
----

<.> xref:#COMPLETE[COMPLETE]
+
--
Format that yields a full representation for the `layout.xml` , such that any layout metadata annotations could be removed from code, without affecting the resulting xref:refguide:applib:index/layout/grid/bootstrap/BSGrid.adoc[BSGrid] , when loaded from `layout.xml` . The resulting xref:refguide:applib:index/layout/grid/bootstrap/BSGrid.adoc[BSGrid] has all the metadata, broadly speaking corresponding to the xref:refguide:applib:index/annotation/DomainObjectLayout.adoc[DomainObjectLayout] , xref:refguide:applib:index/annotation/ActionLayout.adoc[ActionLayout] , xref:refguide:applib:index/annotation/PropertyLayout.adoc[PropertyLayout] and xref:refguide:applib:index/annotation/CollectionLayout.adoc[CollectionLayout] .
--
<.> xref:#MINIMAL[MINIMAL]
+
--
Format that yields a minimal representation for the `layout.xml` , such that layout annotations are required in code to at least 'bind' the properties/collections/actions to their regions (groups and tabs).
--

== Members

[#COMPLETE]
=== COMPLETE

Format that yields a full representation for the `layout.xml` , such that any layout metadata annotations could be removed from code, without affecting the resulting xref:refguide:applib:index/layout/grid/bootstrap/BSGrid.adoc[BSGrid] , when loaded from `layout.xml` . The resulting xref:refguide:applib:index/layout/grid/bootstrap/BSGrid.adoc[BSGrid] has all the metadata, broadly speaking corresponding to the xref:refguide:applib:index/annotation/DomainObjectLayout.adoc[DomainObjectLayout] , xref:refguide:applib:index/annotation/ActionLayout.adoc[ActionLayout] , xref:refguide:applib:index/annotation/PropertyLayout.adoc[PropertyLayout] and xref:refguide:applib:index/annotation/CollectionLayout.adoc[CollectionLayout] .

In other words: if a 'complete' grid is persisted as the `layout.xml` , then there should be no need for any of the layout annotations, to be required in the domain class itself.

[#MINIMAL]
=== MINIMAL

Format that yields a minimal representation for the `layout.xml` , such that layout annotations are required in code to at least 'bind' the properties/collections/actions to their regions (groups and tabs).

In other words: the `layout.xml` is used only to specify the positioning of the groups and tabs, but has no additional meta data. The expectation is that most of the layout annotations ( xref:refguide:applib:index/annotation/DomainObjectLayout.adoc[DomainObjectLayout] , xref:refguide:applib:index/annotation/ActionLayout.adoc[ActionLayout] , xref:refguide:applib:index/annotation/PropertyLayout.adoc[PropertyLayout] , xref:refguide:applib:index/annotation/CollectionLayout.adoc[CollectionLayout] will still be retained in the domain class code.
