= IResourceContext _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Provides access to request-specific context (eg HTTP headers), session-specific context (eg authentication) and global context (eg configuration settings).

== API

[source,java]
.IResourceContext.java
----
interface IResourceContext {
  String urlFor(final String url)     // <.>
  List<MediaType> getAcceptableMediaTypes()     // <.>
  InteractionInitiatedBy getInteractionInitiatedBy()     // <.>
  Where getWhere()
  ObjectAdapterLinkTo getObjectAdapterLinkTo()
  List<List<String>> getFollowLinks()
  boolean isValidateOnly()
  boolean honorUiHints()
  boolean objectPropertyValuesOnly()
  boolean suppressDescribedByLinks()
  boolean suppressUpdateLink()
  boolean suppressMemberId()
  boolean suppressMemberLinks()
  boolean suppressMemberExtensions()
  boolean suppressMemberDisabledReason()
  boolean canEagerlyRender(ManagedObject objectAdapter)     // <.>
  RepresentationService.Intent getIntent()     // <.>
  InteractionProvider getInteractionProvider()
  MetaModelContext getMetaModelContext()
  Optional<ManagedObject> getObjectAdapterForOidFromHref(final String oidFromHref)
}
----

<.> xref:#urlFor__String[urlFor(String)]
+
--
Prepends with the base URI
--
<.> xref:#getAcceptableMediaTypes__[getAcceptableMediaTypes()]
+
--
Returns the _HttpHeaders#getAcceptableMediaTypes() acceptable media types_ as obtained from _HttpHeaders_ .
--
<.> xref:#getInteractionInitiatedBy__[getInteractionInitiatedBy()]
+
--
Whether this interaction was initiated directly by a _InteractionInitiatedBy#USER user_ (or indirectly by the _InteractionInitiatedBy#FRAMEWORK framework_ .
--
<.> xref:#canEagerlyRender__ManagedObject[canEagerlyRender(ManagedObject)]
+
--
To avoid infinite loops when eagerly rendering graphs of objects as _DomainObjectReprRenderer#asEventSerialization() events_ .
--
<.> xref:#getIntent__[getIntent()]
+
--
Applies only when rendering a domain object.
--

== Members

[#urlFor__String]
=== urlFor(String)

Prepends with the base URI

[#getAcceptableMediaTypes__]
=== getAcceptableMediaTypes()

Returns the _HttpHeaders#getAcceptableMediaTypes() acceptable media types_ as obtained from _HttpHeaders_ .

[#getInteractionInitiatedBy__]
=== getInteractionInitiatedBy()

Whether this interaction was initiated directly by a _InteractionInitiatedBy#USER user_ (or indirectly by the _InteractionInitiatedBy#FRAMEWORK framework_ .

[#canEagerlyRender__ManagedObject]
=== canEagerlyRender(ManagedObject)

To avoid infinite loops when eagerly rendering graphs of objects as _DomainObjectReprRenderer#asEventSerialization() events_ .

[#getIntent__]
=== getIntent()

Applies only when rendering a domain object.
