[[GridSystemService]]
= `GridSystemService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:



The `GridSystemService` encapsulates a single layout grid system which can be used to customize the layout
of domain objects.  In particular this means being able to return a "normalized" form (validating and associating
domain object members into the various regions of the grid) and in providing a default grid if there is no other
metadata available.

The framework provides a single such grid implementation, namely for Bootstrap3.

[NOTE]
====
Unlike most other domain services, the framework will check _all_ available implementations of `GridSystemService` to obtain available grid systems, rather than merely the first implementation found; in other words it uses the chain-of-responsibility pattern.
Services are called in the order defined by the Spring link:https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/Order.html[`@Order`] annotation).

Note though that each concrete implementation must also provide corresponding Wicket viewer components capable of interpreting the grid layout.
====


== SPI

The SPI defined by this service is:

[source,java]
----
public interface GridSystemService<G extends Grid> {
    Class<? extends Grid> gridImplementation();                 // <1>
    String tns();                                               // <2>
    String schemaLocation();                                    // <3>
    Grid defaultGrid(Class<?> domainClass);                     // <4>
    void normalize(G grid, Class<?> domainClass);               // <5>
    void complete(G grid, Class<?> domainClass);                // <6>
    void minimal(G grid, Class<?> domainClass);                 // <7>
}
----
<1> The concrete subclass of `Grid` supported by this implementation.
As noted in the introduction, there can be multiple implementations of this service,  but there can only be one implementation per concrete subclass.
As is normal practice, these are ordered as per the Spring link:https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/Order.html[`@Order`] or equivalent annotation.
<2> the target namespace for this grid system.  This is used when generating the XML.  The Bootstrap3 grid system provided by the framework returns the value `http://isis.apache.org/applib/layout/grid/bootstrap3`.
<3> the schema location for the XSD.  The Bootstrap3 grid system provided by the framework returns the value `http://isis.apache.org/applib/layout/grid/bootstrap3/bootstrap3.xsd`.
<4> a default grid, eg two columns in ratio 4:8.  Used when no existing grid layout exists for a domain class.
<5> Validates and normalizes a grid, modifying the grid so that all of the domain object's members (properties, collections, actions) are bound to regions of the grid.  This is done using existing metadata, most notably that of the xref:refguide:applib-ant:MemberOrder.adoc[`@MemberOrder`] annotation.  Such a grid, if persisted as the layout XML file for the domain class, allows the
 `@MemberOrder` annotation to be removed from the source code of the domain class (but other annotations must be retained).
<6> Takes a normalized grid and enriches it with additional metadata (taken from Apache Isis' internal metadata) that can be represented in the layout XML.  Such a grid, if persisted as the layout XML file for the domain class, allows all layout annotations (xref:refguide:applib-ant:ActionLayout.adoc[`@ActionLayout`], xref:refguide:applib-ant:PropertyLayout.adoc[`@PropertyLayout`] and xref:refguide:applib-ant:CollectionLayout.adoc[`@CollectionLayout`]) to be removed from the source code of the domain class.
<7> Takes a normalized grid and strips out removes all members, leaving only the grid structure.  Such a grid, if persisted as the layout XML file for the domain class, requires that the xref:refguide:applib-ant:MemberOrder.adoc[`@MemberOrder`] annotation is retained in the source code of said class in order to bind members to the regions of the grid.


== Implementation

The framework provides `GridSystemServiceBS3`, an implementation that encodes the bootstrap3 grid system.
(The framework also provides xref:vw:ROOT:about.adoc[Wicket viewer] components that are capable of interpreting and rendering this metadata).



== Related Services

This service is used by xref:refguide:applib-svc:presentation-layer-spi/GridService.adoc[`GridService`].
