= ApplicationFeature _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.ApplicationFeature.java
----
interface ApplicationFeature {
  ApplicationFeatureId getFeatureId()
  String getFullyQualifiedName()
  Optional<ApplicationMemberSort> getMemberSort()     // <.>
  SortedSet<ApplicationFeatureId> getMembersOfSort(ApplicationMemberSort memberSort)
  Optional<Class<?>> getActionReturnType()     // <.>
  Optional<SemanticsOf> getActionSemantics()     // <.>
  boolean isPropertyOrCollectionDerived()     // <.>
  OptionalInt getPropertyTypicalLength()     // <.>
  OptionalInt getPropertyMaxLength()     // <.>
  SortedSet<ApplicationFeatureId> getContents()
  SortedSet<ApplicationFeatureId> getProperties()
  SortedSet<ApplicationFeatureId> getCollections()
  SortedSet<ApplicationFeatureId> getActions()
}
----

<.> xref:#getMemberSort__[getMemberSort()]
+
--
Returns optionally the member sort, based on whether this feature is of sort _ApplicationFeatureSort#MEMBER_ .
--
<.> xref:#getActionReturnType__[getActionReturnType()]
+
--
Returns optionally the action's return type, based on whether this feature is of sorts _ApplicationFeatureSort#MEMBER member_ and _ApplicationMemberSort#ACTION action_ .
--
<.> xref:#getActionSemantics__[getActionSemantics()]
+
--
Returns optionally the action's semantics, based on whether this feature is of sorts _ApplicationFeatureSort#MEMBER member_ and _ApplicationMemberSort#ACTION action_ .
--
<.> xref:#isPropertyOrCollectionDerived__[isPropertyOrCollectionDerived()]
+
--
Returns whether the property or collection feature is derived.
--
<.> xref:#getPropertyTypicalLength__[getPropertyTypicalLength()]
+
--
Returns optionally the property's semantics, based on whether this feature is of sorts _ApplicationFeatureSort#MEMBER member_ and _ApplicationMemberSort#PROPERTY property_ .
--
<.> xref:#getPropertyMaxLength__[getPropertyMaxLength()]
+
--
Returns optionally the property's max-length constraint, based on whether this feature is of sorts _ApplicationFeatureSort#MEMBER member_ and _ApplicationMemberSort#PROPERTY property_ .
--

== Members

[#getMemberSort__]
=== getMemberSort()

Returns optionally the member sort, based on whether this feature is of sort _ApplicationFeatureSort#MEMBER_ .

[#getActionReturnType__]
=== getActionReturnType()

Returns optionally the action's return type, based on whether this feature is of sorts _ApplicationFeatureSort#MEMBER member_ and _ApplicationMemberSort#ACTION action_ .

[#getActionSemantics__]
=== getActionSemantics()

Returns optionally the action's semantics, based on whether this feature is of sorts _ApplicationFeatureSort#MEMBER member_ and _ApplicationMemberSort#ACTION action_ .

[#isPropertyOrCollectionDerived__]
=== isPropertyOrCollectionDerived()

Returns whether the property or collection feature is derived.

[#getPropertyTypicalLength__]
=== getPropertyTypicalLength()

Returns optionally the property's semantics, based on whether this feature is of sorts _ApplicationFeatureSort#MEMBER member_ and _ApplicationMemberSort#PROPERTY property_ .

[#getPropertyMaxLength__]
=== getPropertyMaxLength()

Returns optionally the property's max-length constraint, based on whether this feature is of sorts _ApplicationFeatureSort#MEMBER member_ and _ApplicationMemberSort#PROPERTY property_ .
