:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



Actions parameters can be either value types or reference types (typically entities), and can be either single-valued (a scalar) or multi-valued (a list).

Actions that have one or more multi-valued parameters are sometimes called "bulk" actions because they act "in bulk", upon a number of objects.

[TIP]
====
Rather than using a supporting method, it is also possible to use link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/Action.html#choicesfrom[@Action#choicesFrom], which causes .
====

== How this demo works

On the left hand side of this page are two different implementations of a design to mark "character" objects as favourites.
If added as a favourite, the object is moved to the "favourites" collection in the middle.

The first implementation uses a supporting `choicesXNnn` method, providing a list of actions from the appropriate collection.

The second implementation uses the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/Action.html#choicesfrom[@Action#choicesFrom] annotation.
Instead of a supporting `choicesXNnn` method, checkboxes are rendered against a collection; these act as the source of candidate values for the parameter.

In terms of code:

* page object:
+
[source,java,indent=0]
.BulkActionPage.java
----
include::BulkActionPage.java[tags=class]
----

* the actions to add and remove American favorites use a `choices` method:
+
[source,java,indent=0]
.BulkActionPage_addToAmericanFavourites.java.java
----
include::BulkActionPage_addToAmericanFavourites.java[tags=class]
----
<.> explicitly provide a set of candidates to select from
+
with `removeFromAmericanFavourites` the equivalent code, but moving the objects in the other direction

* whereas the avtions to add and remove British favourites use the `@Action#choicesFrom` annotation:
+
[source,java,indent=0]
.BulkActionPage_addToBritishFavourites.java.java
----
include::BulkActionPage_addToBritishFavourites.java[tags=class]
----
<.> indicates that the choices are taken from this collection
+
where again `removeFromBritishFavourites` the equivalent code, but moving the objects in the other direction.

