[[welcome-page]]
= Welcome page
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



It's possible to customize the application name, welcome message (as displayed on the home page if not home page service is configured) and the about message can all be customized.
This is done by specifying the appropriate configuration properties:

[source,properties]
----
isis.viewer.wicket.application.name=My Wonderful App
isis.viewer.wicket.welcome.file=welcome.html                # <1>
isis.viewer.wicket.application.about=My Wonderful App v1.0
----
<1> the `welcome.html` file is resolved relative to `src/main/webapp`.

[TIP]
====
Do not confuse the welcome page file with the xref:vw:ROOT:customisation/top-level-index-page.adoc[top-level index page]; they are different things!
====


The `application.name` is used both on the sign-in page and also top-left on the header.
It's also possible to replace this text with images:


[source,properties]
----
isis.viewer.wicket.application.brandLogoSignin=/images/logo-512.png
isis.viewer.wicket.application.brandLogoHeader=/images/logo-80x32.png
----

These images are resolved relative to `src/main/webapp`.

