The framework has built-in support for all of the primitive data types, including `int`.

From here you can:

* navigate to an entity that uses the `int` datatype
* open a view model that uses the `int` datatype

Because `int` is a primitive value, the properties on these domain objects are mandatory.

== Common interface

These objects both implement a common interface, `PrimitiveIntHolder`:

[source,java]
----
include::holder/PrimitiveIntHolder.java[tags=class]
----

There is also an extension of this interface, `PrimitiveIntHolder2`, with default methods demonstrating the use of label positions:

[source,java]
----
include::holder/PrimitiveIntHolder2.java[tags=class]
----

<.> The default methods have annotations that are automatically inherited.
<.> Using `@MemberOrder` positions the properties into the appropriate `<field-set>` within the `Xxx.layout.xml` layout file.


== Mixin actions

A number of mixin actions contribute through this interface, demonstrate the use of `int` as a parameter and as a return type.
For example:

* the `updateReadOnlyProperty` action is:
+
[source,java]
----
include::holder/PrimitiveIntHolder_updateReadOnlyProperty.java[tags=class]
----

* the `actionReturning` action is:
+
[source,java]
----
include::holder/PrimitiveIntHolder_actionReturning.java[tags=class]
----

== Mixin properties

We also use the interface to contribute a mixin property:

* the `mixinProperty` property:
+
[source,java]
----
include::holder/PrimitiveIntHolder_mixinProperty.java[tags=class]
----

