= `defaultView()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


The xref:ug:vw:ugvw.adoc#[Wicket viewer] allows additional views to be configured to render collections of objects; at the time of writing thesee include the excel, fullcalendar2 and gmap3 provided by the (non-ASF) link:http://platform.incode.org[Incode Platform^].
If the objects to be rendered have the correct "shape", then the appropriate view will be made available.  For example, objects with a date can be rendered using `calendar`; objects with locations can be rendered using `map`.

The `defaultView()` attribute is used to select which of these views should be used by default for a given collection.


For example:

[source,java]
----
public class BusRoute {
    @CollectionLayout(
        defaultView="map"
    )
    public SortedSet<BusStop> getStops() { ... }
    ...
}
----


[NOTE]
====
This attribute takes precedence over any value for the xref:rg:ant:CollectionLayout/render.adoc[`@CollectionLayout#render()`] attribute.  For example, if the
`defaultView` attribute is defined to "table", then the table will be show even if `render` is set to `LAZILY`.
====


== Alternatives


As an alternative to using the annotation, the dynamic xref:ug:vw:ugvw.adoc#_ugvw_layout_file-based[file-based layout] can be used instead.

