= `Dto`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


The `Dto` role interface is intended to be implemented by JAXB-annotated view models, that is, annotated using
xref:rg:ant:XmlRootElement.adoc[`@XmlRootElement`].
It enables the ability to download the XML and XSD schema of those objects using two xref:ug:fun:building-blocks/types-of-domain-objects/mixins.adoc[mixins], `Dto_downloadXml` and `Dto_downloadXsd`.

The interface is just a marker interface (with no members), and is defined as:

[source,java]
----
public interface Dto { }
----

The `Dto_downloadXml` mixin defines the following action:

[source,java]
----
@Mixin(method="act")
public class Dto_downloadXml {
    public Dto_downloadXml(final Dto dto) { ... }     // <1>
    public Object act(final String fileName) { ... }   // <2>
    ...
}
----
<1> provided as an action to any class that (trivially) implements the `Dto` interface
<2> The action's name is derived from the class name.

This will return the XML text wrapped up in a xref:rg:cms:classes/value-types/Clob.adoc[`Clob`].

The `Dto_downloadXsd` mixin is similar:

[source,java]
----
@Mixin(method="act")
public class Dto_downloadXsd {
    public Dto_downloadXsd(final Dto dto) { ... }                                             // <1>
    public Object act(final String fileName, final IsisSchemes isisSchemas) { ... }   // <2>
}
----
<1> provided as an action to any class that (trivially) implements the `Dto` interface
<2> The action's name be derived from the class name.

If the domain object's JAXB annotations reference only a single XSD schema then this will return that XML text as a xref:rg:cms:classes/value-types/Clob.adoc[`Clob`] of that XSD.
If there are multiple XSD schemas referenced then the action will return a zip of those schemas, wrapped up in a xref:rg:cms:classes/value-types/Blob.adoc[`Blob`].
The `IsisSchemas` parameter to the action can be used to optionally ignore the common xref:rg:cms:schema.adoc[Apache Isis schemas] (useful if there is only one other XSD schema referenced by the DTO).



== Related Services

The `Dto_downloadXml` and `Dto_downloadXsd` delegate to the xref:rg:svc:integration-api/JaxbService.adoc[`JaxbService`] to actually generate the XML/XSD.