= From v1.11.0 to 1.12.0

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:



Existing projects written against v1.11.x should run against v1.12.0 with few if any changes.
If you *do* encounter any difficulties then let us know via the link:https://isis.apache.org/versions/1.12.0/support.html#[users mailing list], so we can support you and document issues here.



== Dynamic XML Layouts

The major new feature in 1.12.0 is link:https://isis.apache.org/versions/1.12.0/guides/ugvw/ugvw.html#_ugvw_layout_file-based[dynamic XML layouts], providing much enhanced support for custom layouts.

The new `Xxx.layout.xml` file is optional; without it domain objects will continue to be rendered as before, using metadata from annotations (link:https://isis.apache.org/versions/1.12.0/guides/rgant/rgant.html#_rgant-DomainObjectLayout[`@DomainObjectLayout`], link:https://isis.apache.org/versions/1.12.0/guides/rgant/rgant.html#_rgant-PropertyLayout[`@PropertyLayout`], link:https://isis.apache.org/versions/1.12.0/guides/rgant/rgant.html#_rgant-CollectionLayout[`@CollectionLayout`], link:https://isis.apache.org/versions/1.12.0/guides/rgant/rgant.html#_rgant-ActionLayout[`@ActionLayout`], link:https://isis.apache.org/versions/1.12.0/guides/rgant/rgant.html#_rgant-MemberOrder[`@MemberOrder`] and link:https://isis.apache.org/versions/1.12.0/guides/rgant/rgant.html#_rgant-MemberGroupLayout[`@MemberGroupLayout`]), and also from any link:https://isis.apache.org/versions/1.12.0/guides/ugvw/ugvw.html#_ugvw_layout_file-based[`Xxx.layout.json`] file that might already exist.
There is therefore no requirement to move to the new more flexible XML-based layout.

If you do want to start using the new format, then you will find that 1.12.0 provides a mixin action (available in prototype mode only) called "download XML layout".
This will allow you to download the current layout file for the object being rendered.
This can then be saved alongside the class' Java source file.
Once a `Xxx.layout.xml` file is present, any existing `Xxx.layout.json` file will be ignored; any annotations though will continue to be honoured.

If you wish to migrate all your domain objects to use XML layouts, this can be done using the "download layouts (XML)" (on the "Prototyping" menu), as a single zip file.
This can then be unzipped into the `src/main/java` directory.


== Mixins

(As mentioned above), 1.12.0 provides a number of new mixin actions and properties:

* link:https://isis.apache.org/versions/1.12.0/guides/rgcms/rgcms.html#__rgcms_classes_mixins_Object_clearHints[clear hints] action

* link:https://isis.apache.org/versions/1.12.0/guides/rgcms/rgcms.html#__rgcms_classes_mixins_Object_downloadLayoutXml[download Layout XML] action (prototype mode)

* link:https://isis.apache.org/versions/1.12.0/guides/rgcms/rgcms.html#__rgcms_classes_mixins_Object_rebuildMetamodel[rebuild metamodel] action (prototype mode)

* link:https://isis.apache.org/versions/1.12.0/guides/rgcms/rgcms.html#__rgcms_classes_mixins_Persistable_datanucleusXxx[id and version] properties (for domain entities only)

These are in addition to the link:https://isis.apache.org/versions/1.12.0/guides/rgcms/rgcms.html#__rgcms_classes_mixins_Persistable_downloadJdoMetadata[download JDO metadata] mixin action (prototype mode) provided in earlier versions of the framework.

The properties are grouped in a "metadata" fieldset, and the mixin actions associated with that fieldset.
If the domain object is a view model rather than an entity (that is, has no id or version) then the actions will instead be rendered as top-level actions.

Most of these mixin object members are visible only in prototype mode, though some are visible in production mode and so potentially visible to end-users.
If you wish to suppress these members from the view, you can either use link:https://isis.apache.org/versions/1.12.0/guides/ugsec/ugsec.html#[security], or alternatively you can write subscribers to veto the visibility of these members by subscribing to their respective domain events.



== JAXB view models are editable

All link:https://isis.apache.org/versions/1.12.0/guides/rgant/rgant.html#_rgant-XmlRootElement[`@XmlRootElement`] view models are now implicitly editable.
Therefore any view models that should be read-only should have editing attribute disabled using link:https://isis.apache.org/versions/1.12.0/guides/rgant/rgant.html#_rgant-DomainObject_editing[`@DomainObject#editing()`] (or use a subscriber to veto editability).


== `DomainObjectContainer` domain service

The link:https://isis.apache.org/versions/1.12.0/guides/rgsvc/rgsvc.html#_rgsvc_core-domain-api_DomainObjectContainer[`DomainObjectContainer`]domain service has been deprecated, with its methods moved to a new set of more fine-grained domain services, such as link:https://isis.apache.org/versions/1.12.0/guides/rgsvc/rgsvc.html#_rgsvc_persistence-layer-api_RepositoryService[`RepositoryService`] and
link:https://isis.apache.org/versions/1.12.0/guides/rgsvc/rgsvc.html#_rgsvc_application-layer-api_MessageService[`MessageService`].

The `DomainObjectContainer` service will continue to be supported until Apache Isis v2.0.0, but in the meantime, consider changing existing application code to use these new domain services.

Please note that when migrating from _rgsvc_core-domain-api_DomainObjectContainer_object-persistence-api.adoc#_rgsvc_core-domain-api_DomainObjectContainer_object-persistence-api[`DomainObjectContainer#persist()`] to link:https://isis.apache.org/versions/1.12.0/../guides/rgsvc/rgsvc.html#_rgsvc_persistence-layer-api_RepositoryService[`RepositoryService#persist()`], no exception will be thrown if the Domain Object is already persisted, so the behavior of link:https://isis.apache.org/versions/1.12.0/guides/rgsvc/rgsvc.html#_rgsvc_persistence-layer-api_RepositoryService[`RepositoryService#persist()`] will be the same as that of link:https://isis.apache.org/versions/1.12.0/guides/rgsvc/rgsvc.html#_rgsvc_core-domain-api_DomainObjectContainer_object-persistence-api[`DomainObjectContainer#persistIfNotAlready()`].



== Removal of the `self-host` profile

The `self-host` profile has been removed from the link:https://isis.apache.org/versions/1.12.0/arch/simpleapp/about.html[SimpleApp archetype].
Instead, run the application using either the `org.apache.isis.WebServer` main class, or `mvn jetty:run`, or build the WAR and deploy to a servlet container such as Tomcat.




== `isis.viewer.wicket.disableModalDialogs` removed

The Apache Isis Wicket viewer uses a modal dialog for action parameters.  Before this feature was implemented (prior to 1.4.0), action parameters were rendered on their own page.  This property was provided to re-enable the old behaviour.

The property has now been removed and this feature removed; actions parameters are always now always shown in a modal dialog.

