[#type-of-domain-objects]
= Type of Domain Objects

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


Apache Causeway supports recognises five main types of domain classes:

* *domain entities* - are domain objects that hold persisted state, for example `Customer` or `Order`.
They can and often do also include business logic, encapsulating the state.
An ORM (xref:pjpa::about.adoc[JPA/EclipseLink] or xref:pjdo::about.adoc[JDO/DataNucleus]) is used to persist the state to the database.

* *domain services* - are (typically) singletons that act upon entities.
Common implementations are repositories (to find domain entities) or factories (to create entities), but they might also be holders of business logic that for whatever reason you want to keep outside an entity; perhaps it easier to test that way.
An example might be `InvoiceCalculationServices`.

* *view models* - are domain objects that holds temporary state for a given user; you might consider these as part of the "application" layer.
They could be a projection of an underlying entity/ies for some particular use case (eg `DocumentAndCommunication`); they could aggregate data from multiple locations (eg a `CustomerDashboard`); they could manage a business process (eg `PaymentBatchManager`).

* *mixins* - allow functionality to be "contributed" in the UI by one module to another object, similar to traits or extension methods provided in some programming languages.
This is an important capability to help keep large applications decoupled; for example `Customer_receivePayment` could be defined in the "accounts receivable" module, contributing behaviour to the "Customer" entity.

* *value types* - domain objects and view models maintain state (properties and collections); each property's will be for a certain value type.
Normally these will be built-in, such as primitives, strings or dates.
But the framework also supports custom value types, either scalar or composite.
These could also be 3rd party, eg a library such as https://jscience.org[jscience.org].

From the end-user's perspective the UI displays a single domain object instance that has state (that is, a domain entity or a view model) per page.
The end-user can then inspect and modify its state, and navigate to related objects.

Domain classes are generally recognized using annotations.
Apache Causeway defines its own set of annotations, and
you can generally recognize an Apache Causeway domain class because it will be probably be annotated using xref:refguide:applib:index/annotation/DomainObject.adoc[@DomainObject] and xref:refguide:applib:index/annotation/DomainService.adoc[@DomainService].

The framework also recognises some annotations from the ORM layer (ie JPA/EclipseLink or JDO/DataNucleus) and infers domain semantics from these annotations.
Similarly, JAXB annotations are typically used for view models.

The framework also defines supplementary annotations, notably xref:refguide:applib:index/annotation/DomainObjectLayout.adoc[@DomainObjectLayout] and xref:refguide:applib:index/annotation/DomainServiceLayout.adoc[@DomainServiceLayout].
These provide hints relating to the layout of the domain object in the user interface.
Alternatively, these UI hints might be defined in a supplementary xref:userguide:ROOT:ui.adoc#object-layout[.layout.xml] file.




