= Authentication _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

An immutable, serializable value type, that holds details about a user's authentication.

== API

[source,java]
.Authentication.java
----
interface Authentication {
  String getUserName()     // <.>
  String getValidationCode()     // <.>
  UserMemento getUser()     // <.>
  ExecutionContext getExecutionContext()     // <.>
  Type getType()     // <.>
  Authentication withExecutionContext(ExecutionContext executionContext)     // <.>
}
----

<.> xref:#getUserName__[getUserName()]
+
--
The name of the authenticated user; for display purposes only.
--
<.> xref:#getValidationCode__[getValidationCode()]
+
--
A unique code given to this session during authentication.
--
<.> xref:#getUser__[getUser()]
+
--
The (programmatically) simulated (or actual) user, belonging to this session.
--
<.> xref:#getExecutionContext__[getExecutionContext()]
+
--
The xref:refguide:applib:index/services/iactn/ExecutionContext.adoc[ExecutionContext] (programmatically) simulated (or actual), belonging to this session.
--
<.> xref:#getType__[getType()]
+
--
To support external security mechanisms such as keycloak, where the validity of the session is defined by headers in the request.
--
<.> xref:#withExecutionContext__ExecutionContext[withExecutionContext(ExecutionContext)]
+
--
Returns a copy with given _executionContext_ .
--

== Members

[#getUserName__]
=== getUserName()

The name of the authenticated user; for display purposes only.

[#getValidationCode__]
=== getValidationCode()

A unique code given to this session during authentication.

This can be used to confirm that this session has been properly created and the user has been authenticated. It should return an empty string ( `""` ) if this is unauthenticated user

[#getUser__]
=== getUser()

The (programmatically) simulated (or actual) user, belonging to this session.

[#getExecutionContext__]
=== getExecutionContext()

The xref:refguide:applib:index/services/iactn/ExecutionContext.adoc[ExecutionContext] (programmatically) simulated (or actual), belonging to this session.

[#getType__]
=== getType()

To support external security mechanisms such as keycloak, where the validity of the session is defined by headers in the request.

[#withExecutionContext__ExecutionContext]
=== withExecutionContext(ExecutionContext)

Returns a copy with given _executionContext_ .
