[[_migration-notes_1.14.0-to-1.15.0]]
= From v1.14.x to 1.15.0
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



[NOTE]
====
Apache Isis 1.15.0-SNAPSHOT is currently still in development
====

== Overriding framework services (link:https://issues.apache.org/jira/browse/ISIS-1611[ISIS-1611])

Domain services fall into three categories:

* application services: written by the application developer and used only within the application
* SPI services: written by the application developer but called by the framework
* framework services: defined within the applib with a default implementation provided by the framework itself

As described
xref:../guides/ugbtb/ugbtb.adoc#_ugbtb_hints-and-tips_replacing-default-service-implementations[here], it is possible to override framework services so that the framework uses the replacement implementation.
Previously this required explicitly setting either xref:../guides/rgant/rgant.adoc#_rgant_DomainService_menuOrder[`@DomainService#menuOrder()`] or xref:../guides/rgant/rgant.adoc#_rgant_DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`].

In 1.15.0, the default value for `menuOrder` has been set to a value lower than that of the framework-provided implementations, and so will a custom implementation will always take precedence over the framework implementations without having to remember to also set `menuOrder`.


== Fix to config variable (link:https://issues.apache.org/jira/browse/ISIS-1595[ISIS-1595])

The configuration property xref:../guides/rgcfg/rgcfg.adoc#__rgcfg_configuring-core_metamodel-validation[] `isis.reflector.validator.jdoqlVariablesClause` was incorrectly named `variablesClause`.
This has now been corrected.

Any applications that used this configuration property should be updated.

== Rename of isis-viewer-wicket artifacts

The `<groupId>` and `<artifactId>` of the xref:../guides/ugvw/ugvw.adoc#[Wicket viewer] have been made consistent with other artifacts:

* the `<groupId>` has been changed from `org.apache.isis.viewer` to `org.apache.isis.core`
* the `<artifactId>` has been changed from `isis-viewer-wicket-???` to `isis-core-viewer-wicket-???`


For example:

[source,xml]
----
<groupId>org.apache.isis.viewer</groupId>
<artifactId>isis-viewer-wicket-applib</artifactId>
----

has been renamed to:

[source,xml]
----
<groupId>org.apache.isis.core</groupId>
<artifactId>isis-core-viewer-wicket-applib</artifactId>
----


