:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObjectLayout.html#tabledecorator[@DomainObjectLayout#tableDecorator] attribute allows to specify a custom client side table renderer to be specified for when a collection of domain objects are shown in either a parented collection (belonging to an object) or a standalone collection (returned from an action).

NOTE: for parented collections, the `tableDecorator` value can be overridden on a case-by-case basis using link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/CollectionLayout.html#tabledecorator[@CollectionLayout#tableDecorator].

There is currently just one decorator available, for link:https://datatables.net/[datatables.net].
If specified, the effect of `@DomainObjectLayout#paged` or `@CollectionLayout#paged` is ignored.

== How this demo works

The collection on the left hand side shows a set of domain objects that have been annotated with `tableDecorator` of "datatables".

The associated action "actionReturningCollection" returns these same objects as a standalone collection.
Here again the `tableDecorator` value _is_ honoured.

In terms of code:

[source,java,indent=0]
.DomainObjectLayoutTableDecorator.java
----
include::DomainObjectLayoutTableDecorator.java[tags=class]
----
<.> indicates that the "datatables" decoration is used.


== Related configuration property

To set the global default for `tableDecorator`, use this configuration property:

[source,yaml]
.application.yaml
----
causeway:
  applib:
    annotation:
      domain-object-layout:
        table-decorator: org.apache.causeway.applib.annotation.TableDecorator.DatatablesNet
----

