:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

There are four different ways to influence the presentation of a domain object: its title, its icon, an overall CSS class and its layout.
Normally the responsibility for specifying these presentation items belong with the domain object itself, but this responsibility can be moved to a subscriber which listens to an appropriate "UI event" and sets the corresponding presentation item.
These are specified using link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObjectLayout.html[@DomainObjectLayout]:

* link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObjectLayout.html#titleuievent[@DomainObjectLayout#titleUiEvent] - equivalent to link:https://causeway.apache.org/refguide/2.0.0-RC1/applib-methods/ui-hints/title.html[title()]
+
specifies the UI event class for a subscriber to listen to for changing the title

* link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObjectLayout.html#iconuievent[@DomainObjectLayout#iconUiEvent] - equivalent to link:https://causeway.apache.org/refguide/2.0.0-RC1/applib-methods/ui-hints/iconName.html[iconName()]
+
specifies the UI event class for a subscriber to listen to for changing the icon

* link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObjectLayout.html#cssclassuievent[@DomainObjectLayout#cssClassUiEvent] - equivalent to link:https://causeway.apache.org/refguide/2.0.0-RC1/applib-methods/ui-hints/cssClass.html[cssClass()]
+
specifies the UI event class for a subscriber to listen to for changing the CSS class

* link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObjectLayout.html#layoutuievent[@DomainObjectLayout#layoutUiEvent] - equivalent to link:https://causeway.apache.org/refguide/2.0.0-RC1/applib-methods/ui-hints/layout.html[layout()]
+
specifies the UI event class for a subscriber to listen to for changing the layout


== How this demo works

The collection on the left hand side shows a set of domain objects that have been annotated with a UI event class for each of the four presentational elements.
A subscriber listens to each of these events, and alters the presentation based upon whether the object's name ("Joey", "Monica", "Tom" etc) is in the first- or the second-half of the alphabet.

In terms of code:

* the domain object defines these events:
+
[source,java,indent=0]
.DomainObjectLayoutXxxUiEventEntity.java
----
include::DomainObjectLayoutXxxUiEventEntity.java[tags=class]
----
<.> custom title UI event
<.> custom icon UI event
<.> custom CSS class UI event
<.> custom layout UI event

* the subscriber is defined as:
+
[source,java,indent=0]
.DomainObjectLayoutXxxUiEventSubscriber.java
----
include::DomainObjectLayoutXxxUiEventSubscriber.java[tags=class]
----
+
with callbacks:
+
** for title UI event:
+
[source,java,indent=0]
----
include::DomainObjectLayoutXxxUiEventSubscriber.java[tags=titleUiEvent]
----
+
(Navigate into the object to see its title; or hover over its icon to see the title in the tooltip).

** for icon UI event:
+
[source,java,indent=0]
----
include::DomainObjectLayoutXxxUiEventSubscriber.java[tags=iconUiEvent]
----

** for CSS class UI event:
+
[source,java,indent=0]
----
include::DomainObjectLayoutXxxUiEventSubscriber.java[tags=cssClassUiEvent]
----
+
Entries in `application.css` style the object with different colours.

** for layout UI event:
+
[source,java,indent=0]
----
include::DomainObjectLayoutXxxUiEventSubscriber.java[tags=layoutUiEvent]
----
+
This causes either `DomainObjectLayoutXxxUiEventEntity-alternative1.layout.xml` or `DomainObjectLayoutXxxUiEventEntity-alternative2.layout.xml` to be used as the layout file.
Navigate into the objects and notice the different tab labels.

