= Security
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:

This guide describes the authentication and authorization features available to secure your Apache Isis application.






== Terminology

WARNING: TODO:v2: these words could perhaps move into the "security API" module, currently empty.

Apache Isis has built-in support for authentication and authorization:

* By "authentication" we mean logging into the application using some credentials, typically a username and password.
Authentication also means looking up the set of roles to which a user belongs.

* By "authorization" we mean permissions: granting roles to have access to features (object member) of the app.

Apache Isis has two levels of permissions.
_Read_ permission means that the user can view the object member; it will be rendered in the UI.  An action with only read permission will be shown disabled ("greyed out".
_Write_ permission means that the object member can be changed.  For actions this means that they can be invoked.

WARNING: TODO: v2: this is out of date, because there is also a keycloak integration.

The framework provides an API for both authentication and authorization, and provides an implementation that integrates with link:http://shiro.apache.org[Apache Shiro].
Shiro in turn uses the concept of a _realm_ as a source for both authentication and optionally authorization.

WARNING: TODO: v2: Spring Boot requires that shiro.ini is on classpath, not in WEB-INF.

Shiro ships with a simple text-based realm -- the `IniRealm` -- which reads users (and password), user roles and role permissions from the `WEB-INF/shiro.ini` file.
The link:https://github.com/apache/isis-app-helloworld[HelloWorld] and link:https://github.com/apache/isis-app-simpleapp[SimpleApp] starter apps are both configured to use this realm.

Shiro also ships with an implementation of an LDAP-based realm; LDAP is often used to manage user/passwords and corresponding user groups.
Apache Isis in turn extends this with its `IsisLdapRealm`, which provides more flexibility for both group/role and role/permissions management.

In addition, the xref:security:ROOT:about.adoc[SecMan extension] provides an implementation of the Shiro `Realm` API.
This extension also represents users, roles and permissions as domain objects, allowing them to be administered through Apache Isis itself.
Moreover, it can also optionally delegate password management to a subsidiary (delegate) realm (usually LDAP as discussed above).

In addition to Apache Isis' Shiro-based implementation of its authentication and authorization APIs, Isis also provides a "bypass" implementation, useful for quick-n-dirty prototyping when you want to in effect disable (bypass) security completely.

[NOTE]
.What about auditing?
====
A further aspect of security is auditing: recording what data was modified by which user.

Apache Isis provides the xref:refguide:applib-svc:application-layer-api/InteractionContext.adoc[`InteractionContext`]
can be used to track the actions being invoked, and the xref:refguide:applib-svc:persistence-layer-spi/AuditerService.adoc[`AuditerService`]
captures what data was modified as a result (auditing).
When ``Interaction``s are persisted (eg by way of (non-ASF) link:https://platform.incode.org[Incode Platform^]'s publishmq module) this provides excellent
traceability.
The (non-ASF) link:https://platform.incode.org[Incode Platform^]'s audit module provides an implementation of the `AuditerService`.

For xref:refguide:applib-svc:application-layer-spi/CommandService.adoc[`CommandService`] can be also be used to capture actions.
====

