= EncoderDecoder _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Provides a mechanism for encoding/decoding objects.

This interface is used in two complementary ways:

* As one option, it allows objects to take control of their own encoding/decoding, by implementing directly. However, the instance is used as a factory for itself. The framework will instantiate an instance, invoke the appropriate method method, and use the returned object. The instantiated instance itself will be discarded.

Whatever the class that implements this interface, it must also expose either a `public` no-arg constructor, or (for implementations that also are `Facet` s) a `public` constructor that accepts a single `FacetHolder` . This constructor allows the framework to instantiate the object reflectively.

== API

[source,java]
.EncoderDecoder.java
----
interface EncoderDecoder<T> {
  String toEncodedString(T toEncode)     // <.>
  T fromEncodedString(String encodedString)     // <.>
}
----

<.> xref:#toEncodedString__T[toEncodedString(T)]
+
--
Returns the provided object as an encoded string.
--
<.> xref:#fromEncodedString__String[fromEncodedString(String)]
+
--
Converts an encoded string to an instance of the object.
--

== Members

[#toEncodedString__T]
=== toEncodedString(T)

Returns the provided object as an encoded string.

Even if the class is self-encodeable, note that this method is always called on a new instance of the object created via the no-arg constructor. That is, the object shouldn't encode itself, it should encode the object provided to it.

[#fromEncodedString__String]
=== fromEncodedString(String)

Converts an encoded string to an instance of the object.

Note that here the implementing class is acting as a factory for itself.
