= TableColumnVisibilityService _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Provides the ability to suppress columns in tables.

Only one API is used, applying to both parented- and standalone tables.

There can be multiple implementations of this service registered, ordered as per the Spring _org.springframework.core.annotation.Order_ annotation (or equivalent). All implementations are consulted.

== API

[source,java]
.TableColumnVisibilityService.java
----
interface TableColumnVisibilityService {
  boolean hides(Class<?> collectionType, String memberId)     // <.>
}
----

<.> xref:#hides__Class_String[hides(Class, String)]
+
--
For the specified collectionType, whether the given memberId is visible
--

== Members

[#hides__Class_String]
=== hides(Class, String)

For the specified collectionType, whether the given memberId is visible
