[#jakarta-persistence-Entity]
= @Entity (jpa)

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

// TODO: 3866 - to complete

The `@jakarta.persistence.Entity` is used by JPA to indicate that a class is a domain entity to be persisted to the database.

For example:

[source,java]
.Customer.java
----
import jakarta.persistence.*;

@Entity                                                 // <.>
public class Customer {

    @Id                                                 // <.>
    @GeneratedValue(strategy = GenerationType.AUTO)     // <2>
    @Column(name = "id", nullable = false)              // <2>
    private Long id;

    // ...

}
----
<.> Indicates that this entity is a JPA entity
<.> JPA entities are required to declare an identifier.
It's very common for this to be a surrogate identifier, with the value assigned by the database when the object is persisted.

Apache Causeway currently does not infer any other semantics from this annotation.

[NOTE]
====
Causeway parses the `@Entity` annotation from the Java source code; it does not query the JPA metamodel.
This means that it the `@Entity` annotation must be used rather than the equivalent XML metadata.
====

...
