= Health Check
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The xref:rgsvc.adoc#_rgsvc_application-layer-spi_HealthCheckService[`HealthCheckService`] SPI allows applications to provide an implementation of that service which can indicate the overall health of the application.
The "health" is defined by the very simple `Health` class, where a non-null message indicates a problem, otherwise everything is ok:

[source,java]
----
public class Health {
    public static Health ok() {
        return new Health(null);
    }
    public static Health error(String message) {
        return new Health(message);
    }
    ...
    public boolean getResult() { return message == null; }
    public String getMessage() { return message; }
}
----

The Restful Objects viewer exposes this as `/health` REST endpoint:

* If `HealthCheckService` has been implemented, then this will be called to obtain the `Health`.

* If no implementation has been provided by the application, then an ok `Health` will be assumed.

Either way, the viewer will serialize a `Health` object into JSON, with the mime type indicated as `application/json;profile="urn:org.restfulobjects:repr-types/health"`.

Monitoring infrastructure or container orchestrators (such as Docker Swarm and Kubernetes) can then be configured to call this endpoint to check on the health of the application and take remedial action if not.


== Session Management

The Restful Objects viewer will execute the `HealthCheckService` using a hard-coded user and role:

* the user name is: `__health`
* the role is: `__health-role`

This design means that there is no need to configure monitoring infrastructure with credentials or other such complexity; they can simply hit the health endpoint.

Moreover (unless the `HealthCheckService` implementation uses the `WrapperFactory` to invoke actions), it shouldn't be needed to set up a security account for this user name.


== REST API Mapping

The `/restful/health` path must be specified as a "passThru" in `web.xml` so that no authentication challenge is issued.

TODO: v2: this has changed, because we now use `WebModule_Xxx` instead of `web.xml`, ie set this stuff up programmatically.

[source,xml]
.web.xml
----
<filter>
    <filter-name>IsisSessionFilterForRestfulObjects</filter-name>
    <filter-class>org.apache.isis.core.webapp.IsisSessionFilter</filter-class>
    ...
    <init-param>
        <param-name>passThru</param-name>
        <param-value>/restful/swagger,/restful/health</param-value>
    </init-param>
    ...
</filter>
----

This is a comma separated list, so there may be other values also (for example `/restful/swagger`, as shown above).
