= EmailNotificationService _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Supporting service for the user-registration functionality.

The framework provides a default implementation which in turn uses the _org.apache.isis.applib.services.email.EmailService_ , namely `EmailServiceDefault` .

== API

[source,java]
.EmailNotificationService.java
----
interface EmailNotificationService {
  boolean send(EmailRegistrationEvent ev)     // <.>
  boolean send(PasswordResetEvent ev)     // <.>
  boolean isConfigured()     // <.>
}
----

<.> xref:#send__EmailRegistrationEvent[send(EmailRegistrationEvent)]
+
--
Sends an email to verify an email address as part of the initial user registration
--
<.> xref:#send__PasswordResetEvent[send(PasswordResetEvent)]
+
--
Sends an email to reset a password for an already-registered user
--
<.> xref:#isConfigured__[isConfigured()]
+
--
Whether this service has been configured and thus available for use.
--

== Members

[#send__EmailRegistrationEvent]
=== send(EmailRegistrationEvent)

Sends an email to verify an email address as part of the initial user registration

[#send__PasswordResetEvent]
=== send(PasswordResetEvent)

Sends an email to reset a password for an already-registered user

[#isConfigured__]
=== isConfigured()

Whether this service has been configured and thus available for use.

If this returns false then it is _not_ valid to call _#send(EmailRegistrationEvent)_ (and doing so will result in an _IllegalStateException_ being thrown).

include::hooks/EmailNotificationService_010-implementation.adoc[]

include::hooks/EmailNotificationService_020-examples-and-usage.adoc[]
