= SpecificationAnd
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Adapter to make it easy to perform boolean algebra on xref:refguide:applib:index/spec/Specification.adoc[Specification] s.

Subclasses represent the intersection of multiple xref:refguide:applib:index/spec/Specification.adoc[Specification] s. An implementation should instantiate the xref:refguide:applib:index/spec/Specification.adoc[Specification] s to be satisfied in its constructor.

For example:

----

public class MilkAndSugarSpec extends SpecificationAnd {
    public MilkAndSugarSpec() {
        super(new MustBeMilkySpec(), new TwoLumpsOfSugarSpec());
    }
}
----

== API

[source,java]
.SpecificationAnd.java
----
class SpecificationAnd {
  SpecificationAnd(Specification... specifications)
  String satisfies(Object obj)
}
----

