:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Sometimes an object may have a collection of related objects, but for whatever reason this collection should not be visible to the end-user.

One option is to simply annotate the collection with `@Programmatic` (or `@Domain.Exclude`, which amounts to the same thing); this means that the collection is _not_ part of the framework metamodel and so will not be rendered.

An alternative approach is to annotate the collection as hidden, which can be done using either the  link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/CollectionLayout.html#hidden[@CollectionLayout#hidden] annotation, or a meta-annotation, or using the `Xxx.layout.xml` layout file.

== How this demo works

This page has 3 collections, but only one of them -- `children` -- should be visible.
This is because the other two collections have been hidden, one using an annotation and the other using the `.layout.xml` file.

In terms of code:

* the `children` collection is visible:
+
[source,java,indent=0]
.CollectionLayoutHiddenPage.java
----
include::CollectionLayoutHiddenPage.java[tags=children]
----
<.> explicitly specifies that the collection is _not_ hidden

* the `moreChildren` collection is not visible:
+
[source,java,indent=0]
.CollectionLayoutHiddenPage.java
----
include::CollectionLayoutHiddenPage.java[tags=more-children]
----
<.> explicitly specifies that the collection should always be hidden


* the `yetMoreChildren` collection is also not visible, but this time because it has been specified in the `.layout.xml` file:
+
[source,xml,indent=0]
.CollectionLayoutHiddenPage.layout.xml
----
<cpt:collection id="yetMoreChildren" hidden="EVERYWHERE"/>
----

Note that only `Where.EVERYWHERE` (or its alias, `Where.ANYWHERE`) and `Where.NOWHERE` are permitted for collections.
The other values are for use by properties and/or actions.

