= `multiLine()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


The `multiLine()` attribute specifies that the text field for a string property should span multiple lines.  It is ignored for other property types.  The attribute is also supported for xref:rg:ant:ParameterLayout/multiLine.adoc[parameters].

For example:

[source,java]
----
public class BugReport {
    @PropertyLayout(
        numberOfLines=10
    )
    public String getStepsToReproduce() { /* ... */ }
    public void setStepsToReproduce(String stepsToReproduce) { /* ... */ }
    ...
}
----

Here the `stepsToReproduce` will be displayed in a text area of 10 rows.


[NOTE]
====
If set > 1 (as would normally be the case), then the default xref:rg:ant:PropertyLayout/labelPosition.adoc[`labelPosition`] defaults to `TOP` (rather than `LEFT`, as would normally be the case).
====

== Alternatives

As an alternative to using the annotation, the dynamic xref:ug:vw:layout/file-based.adoc[file-based layout] can be used instead.

