= CausewayModuleExtLayoutLoadersGithub
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Adds the xref:refguide:applib:index/layout/menubars/Menu.adoc[Menu] with its auto-configured menu entries.

== API

[source,java]
.CausewayModuleExtLayoutLoadersGithub.java
----
class CausewayModuleExtLayoutLoadersGithub {
  public static final String NAMESPACE;
  RestTemplate restTemplateForGithubSearch(CausewayConfiguration causewayConfiguration)     // <.>
  RestTemplate restTemplateForGithubContent(CausewayConfiguration causewayConfiguration)     // <.>
}
----

<.> xref:#restTemplateForGithubSearch_CausewayConfiguration[restTemplateForGithubSearch(CausewayConfiguration)]
+
--
Returns a template configured to search for a file in the git repo.
--
<.> xref:#restTemplateForGithubContent_CausewayConfiguration[restTemplateForGithubContent(CausewayConfiguration)]
+
--
Returns a template configured to obtain the content of a file in a repo (from the default branch).
--

== Members

[#restTemplateForGithubSearch_CausewayConfiguration]
=== restTemplateForGithubSearch(CausewayConfiguration)

Returns a template configured to search for a file in the git repo.

Append for example:

----
/search/code?q=SimpleObject.layout.xml+in:path+repo:apache/causeway-app-simpleapp
----

Returns for example:

----
{
  "total_count": 1,
  "incomplete_results": false,
  "items": [
    {
      "name": "SimpleObject.layout.xml",
      "path": "module-simple/src/main/java/domainapp/modules/simple/dom/so/SimpleObject.layout.xml",
      ...
    },
     ...
   ]
   ...
}
----

[#restTemplateForGithubContent_CausewayConfiguration]
=== restTemplateForGithubContent(CausewayConfiguration)

Returns a template configured to obtain the content of a file in a repo (from the default branch).

Append for example:

----
/contents/module-simple/src/main/java/domainapp/modules/simple/dom/so/SimpleObject.layout.xml
----
