"Marks the field, argument, input field or enum value as deprecated"
directive @deprecated(
    "The reason for the deprecation"
    reason: String = "No longer supported"
  ) on FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE | INPUT_FIELD_DEFINITION

"Directs the executor to include this field or fragment only when the `if` argument is true"
directive @include(
    "Included when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Directs the executor to skip this field or fragment when the `if` argument is true."
directive @skip(
    "Skipped when true."
    if: Boolean!
  ) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Exposes a URL that specifies the behaviour of this scalar."
directive @specifiedBy(
    "The URL that specifies the behaviour of this scalar."
    url: String!
  ) on SCALAR

type Mutation {
  causeway_applib_PropertyNode__mixedIn(_gqlv_target: causeway_applib_PropertyNode__gqlv_input, mixedIn: Boolean!): causeway_applib_PropertyNode
  causeway_applib_node_ActionNode__mixedIn(_gqlv_target: causeway_applib_node_ActionNode__gqlv_input, mixedIn: Boolean!): causeway_applib_node_ActionNode
  causeway_applib_node_CollectionNode__mixedIn(_gqlv_target: causeway_applib_node_CollectionNode__gqlv_input, mixedIn: Boolean!): causeway_applib_node_CollectionNode
  causeway_applib_node_FacetNode__shadowed(_gqlv_target: causeway_applib_node_FacetNode__gqlv_input, shadowed: Boolean!): causeway_applib_node_FacetNode
  causeway_conf_ConfigurationProperty__key(_gqlv_target: causeway_conf_ConfigurationProperty__gqlv_input, key: String!): causeway_conf_ConfigurationProperty
  causeway_conf_ConfigurationProperty__value(_gqlv_target: causeway_conf_ConfigurationProperty__gqlv_input, value: String!): causeway_conf_ConfigurationProperty
  causeway_schema_metamodel_v2_DomainClassDto__actions(_gqlv_target: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input, actions: String!): causeway_schema_metamodel_v2_DomainClassDto
  causeway_schema_metamodel_v2_DomainClassDto__annotations(_gqlv_target: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input, annotations: String!): causeway_schema_metamodel_v2_DomainClassDto
  causeway_schema_metamodel_v2_DomainClassDto__collections(_gqlv_target: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input, collections: String!): causeway_schema_metamodel_v2_DomainClassDto
  causeway_schema_metamodel_v2_DomainClassDto__facets(_gqlv_target: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input, facets: String!): causeway_schema_metamodel_v2_DomainClassDto
  causeway_schema_metamodel_v2_DomainClassDto__id(_gqlv_target: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input, id: String!): causeway_schema_metamodel_v2_DomainClassDto
  causeway_schema_metamodel_v2_DomainClassDto__majorVersion(_gqlv_target: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input, majorVersion: String): causeway_schema_metamodel_v2_DomainClassDto
  causeway_schema_metamodel_v2_DomainClassDto__minorVersion(_gqlv_target: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input, minorVersion: String): causeway_schema_metamodel_v2_DomainClassDto
  causeway_schema_metamodel_v2_DomainClassDto__properties(_gqlv_target: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input, properties: String!): causeway_schema_metamodel_v2_DomainClassDto
  causeway_schema_metamodel_v2_DomainClassDto__service(_gqlv_target: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input, service: Boolean!): causeway_schema_metamodel_v2_DomainClassDto
  causeway_testing_fixtures_FixtureResult__fixtureScriptClassName(_gqlv_target: causeway_testing_fixtures_FixtureResult__gqlv_input, fixtureScriptClassName: String): causeway_testing_fixtures_FixtureResult
  causeway_testing_fixtures_FixtureResult__key(_gqlv_target: causeway_testing_fixtures_FixtureResult__gqlv_input, key: String!): causeway_testing_fixtures_FixtureResult
  causeway_testing_fixtures_FixtureResult__object(_gqlv_target: causeway_testing_fixtures_FixtureResult__gqlv_input, object: String!): causeway_testing_fixtures_FixtureResult
  org_apache_causeway_core_metamodel_inspect_model_MemberNode__mixedIn(_gqlv_target: org_apache_causeway_core_metamodel_inspect_model_MemberNode__gqlv_input, mixedIn: Boolean!): org_apache_causeway_core_metamodel_inspect_model_MemberNode
  org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__friendlyName(_gqlv_target: org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__gqlv_input, friendlyName: String!): org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript
  university_admin_AdminMenu__actionWithDisabledParam(firstParam: String!, secondParam: String!, thirdParameter: String!): String
  university_admin_AdminMenu__actionWithHiddenParam(firstParam: String!, secondParam: String!): String
  university_admin_AdminMenu__adminAction: String
  university_admin_AdminMenu__otherAdminAction: String
  university_dept_Department__addStaffMember(_gqlv_target: university_dept_Department__gqlv_input, staffMember: university_dept_StaffMember__gqlv_input!): university_dept_Department
  university_dept_Department__addStaffMembers(_gqlv_target: university_dept_Department__gqlv_input, staffMembers: [university_dept_StaffMember__gqlv_input]): university_dept_Department
  university_dept_Department__changeDeptHead(_gqlv_target: university_dept_Department__gqlv_input, newDeptHead: university_dept_DeptHead__gqlv_input!): university_dept_Department
  university_dept_Department__changeName(_gqlv_target: university_dept_Department__gqlv_input, newName: String!): university_dept_Department
  university_dept_Department__deptHead(_gqlv_target: university_dept_Department__gqlv_input, deptHead: university_dept_DeptHead__gqlv_input): university_dept_Department
  university_dept_Department__name(_gqlv_target: university_dept_Department__gqlv_input, name: String!): university_dept_Department
  university_dept_Department__removeStaffMember(_gqlv_target: university_dept_Department__gqlv_input, staffMember: university_dept_StaffMember__gqlv_input!): university_dept_Department
  university_dept_Departments__createDepartment(deptHead: university_dept_DeptHead__gqlv_input, name: String!): university_dept_Department
  university_dept_DeptHead__changeDepartment(_gqlv_target: university_dept_DeptHead__gqlv_input, department: university_dept_Department__gqlv_input!): university_dept_DeptHead
  university_dept_DeptHead__changeName(_gqlv_target: university_dept_DeptHead__gqlv_input, newName: String!): university_dept_DeptHead
  university_dept_DeptHead__department(_gqlv_target: university_dept_DeptHead__gqlv_input, department: university_dept_Department__gqlv_input): university_dept_DeptHead
  university_dept_DeptHead__name(_gqlv_target: university_dept_DeptHead__gqlv_input, name: String): university_dept_DeptHead
  university_dept_StaffMember__department(_gqlv_target: university_dept_StaffMember__gqlv_input, department: university_dept_Department__gqlv_input): university_dept_StaffMember
  university_dept_StaffMember__grade(_gqlv_target: university_dept_StaffMember__gqlv_input, grade: String!): university_dept_StaffMember
  university_dept_StaffMember__name(_gqlv_target: university_dept_StaffMember__gqlv_input, name: String!): university_dept_StaffMember
  university_dept_StaffMember__photo(_gqlv_target: university_dept_StaffMember__gqlv_input, photo: String): university_dept_StaffMember
  university_dept_Staff__createStaffMember(department: university_dept_Department__gqlv_input!, name: String!): university_dept_StaffMember
}

type Query {
  causeway_applib_UserMenu: causeway_applib_UserMenu
  causeway_conf_ConfigurationMenu: causeway_conf_ConfigurationMenu
  causeway_security_LogoutMenu: causeway_security_LogoutMenu
  university_calc_Calculator: university_calc_Calculator
  university_dept_Departments: university_dept_Departments
  university_dept_DeptHeads: university_dept_DeptHeads
  university_dept_Staff: university_dept_Staff
}

type causeway_applib_DomainObjectList {
  _gqlv_meta: causeway_applib_DomainObjectList__gqlv_meta
  actionArguments: causeway_applib_DomainObjectList__actionArguments__gqlv_property
  actionId: causeway_applib_DomainObjectList__actionId__gqlv_property
  actionOwningFqcn: causeway_applib_DomainObjectList__actionOwningFqcn__gqlv_property
  elementTypeFqcn: causeway_applib_DomainObjectList__elementTypeFqcn__gqlv_property
  objects: causeway_applib_DomainObjectList__objects__gqlv_collection
  title: causeway_applib_DomainObjectList__title__gqlv_property
}

type causeway_applib_DomainObjectList__actionArguments__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(actionArguments: String): String
}

type causeway_applib_DomainObjectList__actionId__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(actionId: String): String
}

type causeway_applib_DomainObjectList__actionOwningFqcn__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(actionOwningFqcn: String): String
}

type causeway_applib_DomainObjectList__elementTypeFqcn__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(elementTypeFqcn: String): String
}

type causeway_applib_DomainObjectList__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_DomainObjectList__objects__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_applib_DomainObjectList__title__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(title: String): String
}

type causeway_applib_FacetGroupNode {
  _gqlv_meta: causeway_applib_FacetGroupNode__gqlv_meta
  childNodes: causeway_applib_FacetGroupNode__childNodes__gqlv_collection
  facets: causeway_applib_FacetGroupNode__facets__gqlv_property
  parentNode: causeway_applib_FacetGroupNode__parentNode__gqlv_property
}

type causeway_applib_FacetGroupNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_applib_FacetGroupNode__facets__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(facets: String): String
}

type causeway_applib_FacetGroupNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_FacetGroupNode__parentNode__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parentNode: org_apache_causeway_core_metamodel_inspect_model_MMNode__gqlv_input): String
}

type causeway_applib_ParameterNode {
  _gqlv_meta: causeway_applib_ParameterNode__gqlv_meta
  childNodes: causeway_applib_ParameterNode__childNodes__gqlv_collection
  parameter: causeway_applib_ParameterNode__parameter__gqlv_property
  parentNode: causeway_applib_ParameterNode__parentNode__gqlv_property
}

type causeway_applib_ParameterNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_applib_ParameterNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_ParameterNode__parameter__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(parameter: String): String
}

type causeway_applib_ParameterNode__parentNode__gqlv_property {
  disabled: String
  get: causeway_applib_node_ActionNode!
  hidden: Boolean
  validate(parentNode: causeway_applib_node_ActionNode__gqlv_input): String
}

type causeway_applib_PropertyNode {
  _gqlv_meta: causeway_applib_PropertyNode__gqlv_meta
  childNodes: causeway_applib_PropertyNode__childNodes__gqlv_collection
  mixedIn: causeway_applib_PropertyNode__mixedIn__gqlv_property
  parentNode: causeway_applib_PropertyNode__parentNode__gqlv_property
  property: causeway_applib_PropertyNode__property__gqlv_property
}

type causeway_applib_PropertyNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_applib_PropertyNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_PropertyNode__mixedIn__gqlv_property {
  disabled: String
  get: Boolean!
  hidden: Boolean
  validate(mixedIn: Boolean): String
}

type causeway_applib_PropertyNode__parentNode__gqlv_property {
  disabled: String
  get: causeway_applib_TypeNode!
  hidden: Boolean
  validate(parentNode: causeway_applib_TypeNode__gqlv_input): String
}

type causeway_applib_PropertyNode__property__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(property: String): String
}

type causeway_applib_RoleMemento {
  _gqlv_meta: causeway_applib_RoleMemento__gqlv_meta
  description: causeway_applib_RoleMemento__description__gqlv_property
  name: causeway_applib_RoleMemento__name__gqlv_property
}

type causeway_applib_RoleMemento__description__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(description: String): String
}

type causeway_applib_RoleMemento__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_RoleMemento__name__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(name: String): String
}

type causeway_applib_TypeNode {
  _gqlv_meta: causeway_applib_TypeNode__gqlv_meta
  childNodes: causeway_applib_TypeNode__childNodes__gqlv_collection
  domainClassDto: causeway_applib_TypeNode__domainClassDto__gqlv_property
  parentNode: causeway_applib_TypeNode__parentNode__gqlv_property
}

type causeway_applib_TypeNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_applib_TypeNode__domainClassDto__gqlv_property {
  disabled: String
  get: causeway_schema_metamodel_v2_DomainClassDto!
  hidden: Boolean
  validate(domainClassDto: causeway_schema_metamodel_v2_DomainClassDto__gqlv_input): String
}

type causeway_applib_TypeNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_TypeNode__parentNode__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parentNode: org_apache_causeway_core_metamodel_inspect_model_MMNode__gqlv_input): String
}

type causeway_applib_UserMemento {
  _gqlv_meta: causeway_applib_UserMemento__gqlv_meta
  authenticationCode: causeway_applib_UserMemento__authenticationCode__gqlv_property
  authenticationSource: causeway_applib_UserMemento__authenticationSource__gqlv_property
  avatarUrl: causeway_applib_UserMemento__avatarUrl__gqlv_property
  impersonating: causeway_applib_UserMemento__impersonating__gqlv_property
  languageLocale: causeway_applib_UserMemento__languageLocale__gqlv_property
  multiTenancyToken: causeway_applib_UserMemento__multiTenancyToken__gqlv_property
  name: causeway_applib_UserMemento__name__gqlv_property
  numberFormatLocale: causeway_applib_UserMemento__numberFormatLocale__gqlv_property
  realName: causeway_applib_UserMemento__realName__gqlv_property
  roles: causeway_applib_UserMemento__roles__gqlv_collection
  timeFormatLocale: causeway_applib_UserMemento__timeFormatLocale__gqlv_property
}

type causeway_applib_UserMemento__authenticationCode__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(authenticationCode: String): String
}

type causeway_applib_UserMemento__authenticationSource__gqlv_property {
  choices(authenticationSource: String): [String]
  disabled: String
  get: String!
  hidden: Boolean
  validate(authenticationSource: String): String
}

type causeway_applib_UserMemento__avatarUrl__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(avatarUrl: String): String
}

type causeway_applib_UserMemento__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_UserMemento__impersonating__gqlv_property {
  disabled: String
  get: Boolean!
  hidden: Boolean
  validate(impersonating: Boolean): String
}

type causeway_applib_UserMemento__languageLocale__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(languageLocale: String): String
}

type causeway_applib_UserMemento__multiTenancyToken__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(multiTenancyToken: String): String
}

type causeway_applib_UserMemento__name__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(name: String): String
}

type causeway_applib_UserMemento__numberFormatLocale__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(numberFormatLocale: String): String
}

type causeway_applib_UserMemento__realName__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(realName: String): String
}

type causeway_applib_UserMemento__roles__gqlv_collection {
  disabled: String
  get: [causeway_applib_RoleMemento]
  hidden: Boolean
}

type causeway_applib_UserMemento__timeFormatLocale__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(timeFormatLocale: String): String
}

type causeway_applib_UserMenu {
  me: causeway_applib_UserMenu__me__gqlv_action
}

type causeway_applib_UserMenu__me__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke: causeway_applib_UserMemento
  validate: String
}

type causeway_applib_node_ActionNode {
  _gqlv_meta: causeway_applib_node_ActionNode__gqlv_meta
  action: causeway_applib_node_ActionNode__action__gqlv_property
  childNodes: causeway_applib_node_ActionNode__childNodes__gqlv_collection
  mixedIn: causeway_applib_node_ActionNode__mixedIn__gqlv_property
  parentNode: causeway_applib_node_ActionNode__parentNode__gqlv_property
}

type causeway_applib_node_ActionNode__action__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(action: String): String
}

type causeway_applib_node_ActionNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_applib_node_ActionNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_node_ActionNode__mixedIn__gqlv_property {
  disabled: String
  get: Boolean!
  hidden: Boolean
  validate(mixedIn: Boolean): String
}

type causeway_applib_node_ActionNode__parentNode__gqlv_property {
  disabled: String
  get: causeway_applib_TypeNode!
  hidden: Boolean
  validate(parentNode: causeway_applib_TypeNode__gqlv_input): String
}

type causeway_applib_node_CollectionNode {
  _gqlv_meta: causeway_applib_node_CollectionNode__gqlv_meta
  childNodes: causeway_applib_node_CollectionNode__childNodes__gqlv_collection
  collection: causeway_applib_node_CollectionNode__collection__gqlv_property
  mixedIn: causeway_applib_node_CollectionNode__mixedIn__gqlv_property
  parentNode: causeway_applib_node_CollectionNode__parentNode__gqlv_property
}

type causeway_applib_node_CollectionNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_applib_node_CollectionNode__collection__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(collection: String): String
}

type causeway_applib_node_CollectionNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_node_CollectionNode__mixedIn__gqlv_property {
  disabled: String
  get: Boolean!
  hidden: Boolean
  validate(mixedIn: Boolean): String
}

type causeway_applib_node_CollectionNode__parentNode__gqlv_property {
  disabled: String
  get: causeway_applib_TypeNode!
  hidden: Boolean
  validate(parentNode: causeway_applib_TypeNode__gqlv_input): String
}

type causeway_applib_node_FacetAttrNode {
  _gqlv_meta: causeway_applib_node_FacetAttrNode__gqlv_meta
  childNodes: causeway_applib_node_FacetAttrNode__childNodes__gqlv_collection
  facetAttr: causeway_applib_node_FacetAttrNode__facetAttr__gqlv_property
  parentNode: causeway_applib_node_FacetAttrNode__parentNode__gqlv_property
}

type causeway_applib_node_FacetAttrNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_applib_node_FacetAttrNode__facetAttr__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(facetAttr: String): String
}

type causeway_applib_node_FacetAttrNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_node_FacetAttrNode__parentNode__gqlv_property {
  disabled: String
  get: causeway_applib_node_FacetNode!
  hidden: Boolean
  validate(parentNode: causeway_applib_node_FacetNode__gqlv_input): String
}

type causeway_applib_node_FacetNode {
  _gqlv_meta: causeway_applib_node_FacetNode__gqlv_meta
  childNodes: causeway_applib_node_FacetNode__childNodes__gqlv_collection
  facet: causeway_applib_node_FacetNode__facet__gqlv_property
  parentNode: causeway_applib_node_FacetNode__parentNode__gqlv_property
  shadowed: causeway_applib_node_FacetNode__shadowed__gqlv_property
}

type causeway_applib_node_FacetNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_applib_node_FacetNode__facet__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(facet: String): String
}

type causeway_applib_node_FacetNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_applib_node_FacetNode__parentNode__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parentNode: org_apache_causeway_core_metamodel_inspect_model_MMNode__gqlv_input): String
}

type causeway_applib_node_FacetNode__shadowed__gqlv_property {
  disabled: String
  get: Boolean!
  hidden: Boolean
  validate(shadowed: Boolean): String
}

type causeway_conf_ConfigurationMenu {
  configuration: causeway_conf_ConfigurationMenu__configuration__gqlv_action
}

type causeway_conf_ConfigurationMenu__configuration__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke: causeway_conf_ConfigurationViewmodel
  validate: String
}

type causeway_conf_ConfigurationProperty {
  _gqlv_meta: causeway_conf_ConfigurationProperty__gqlv_meta
  key: causeway_conf_ConfigurationProperty__key__gqlv_property
  value: causeway_conf_ConfigurationProperty__value__gqlv_property
}

type causeway_conf_ConfigurationProperty__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_conf_ConfigurationProperty__key__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(key: String): String
}

type causeway_conf_ConfigurationProperty__value__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(value: String): String
}

type causeway_conf_ConfigurationViewmodel {
  _gqlv_meta: causeway_conf_ConfigurationViewmodel__gqlv_meta
  environment: causeway_conf_ConfigurationViewmodel__environment__gqlv_collection
  primary: causeway_conf_ConfigurationViewmodel__primary__gqlv_collection
  secondary: causeway_conf_ConfigurationViewmodel__secondary__gqlv_collection
}

type causeway_conf_ConfigurationViewmodel__environment__gqlv_collection {
  disabled: String
  get: [causeway_conf_ConfigurationProperty]
  hidden: Boolean
}

type causeway_conf_ConfigurationViewmodel__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_conf_ConfigurationViewmodel__primary__gqlv_collection {
  disabled: String
  get: [causeway_conf_ConfigurationProperty]
  hidden: Boolean
}

type causeway_conf_ConfigurationViewmodel__secondary__gqlv_collection {
  disabled: String
  get: [causeway_conf_ConfigurationProperty]
  hidden: Boolean
}

type causeway_feat_ApplicationFeatureViewModel {
  _gqlv_meta: causeway_feat_ApplicationFeatureViewModel__gqlv_meta
  memberName: causeway_feat_ApplicationFeatureViewModel__memberName__gqlv_property
  namespaceName: causeway_feat_ApplicationFeatureViewModel__namespaceName__gqlv_property
  parent: causeway_feat_ApplicationFeatureViewModel__parent__gqlv_property
  typeSimpleName: causeway_feat_ApplicationFeatureViewModel__typeSimpleName__gqlv_property
}

type causeway_feat_ApplicationFeatureViewModel__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationFeatureViewModel__memberName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(memberName: String): String
}

type causeway_feat_ApplicationFeatureViewModel__namespaceName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(namespaceName: String): String
}

type causeway_feat_ApplicationFeatureViewModel__parent__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parent: causeway_feat_ApplicationFeatureViewModel__gqlv_input): String
}

type causeway_feat_ApplicationFeatureViewModel__typeSimpleName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(typeSimpleName: String): String
}

type causeway_feat_ApplicationNamespace {
  _gqlv_meta: causeway_feat_ApplicationNamespace__gqlv_meta
  contents: causeway_feat_ApplicationNamespace__contents__gqlv_collection
  memberName: causeway_feat_ApplicationNamespace__memberName__gqlv_property
  namespaceName: causeway_feat_ApplicationNamespace__namespaceName__gqlv_property
  parent: causeway_feat_ApplicationNamespace__parent__gqlv_property
  typeSimpleName: causeway_feat_ApplicationNamespace__typeSimpleName__gqlv_property
}

type causeway_feat_ApplicationNamespace__contents__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type causeway_feat_ApplicationNamespace__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationNamespace__memberName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(memberName: String): String
}

type causeway_feat_ApplicationNamespace__namespaceName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(namespaceName: String): String
}

type causeway_feat_ApplicationNamespace__parent__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parent: causeway_feat_ApplicationFeatureViewModel__gqlv_input): String
}

type causeway_feat_ApplicationNamespace__typeSimpleName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(typeSimpleName: String): String
}

type causeway_feat_ApplicationType {
  _gqlv_meta: causeway_feat_ApplicationType__gqlv_meta
  actions: causeway_feat_ApplicationType__actions__gqlv_collection
  collections: causeway_feat_ApplicationType__collections__gqlv_collection
  memberName: causeway_feat_ApplicationType__memberName__gqlv_property
  namespaceName: causeway_feat_ApplicationType__namespaceName__gqlv_property
  parent: causeway_feat_ApplicationType__parent__gqlv_property
  properties: causeway_feat_ApplicationType__properties__gqlv_collection
  typeSimpleName: causeway_feat_ApplicationType__typeSimpleName__gqlv_property
}

type causeway_feat_ApplicationTypeAction {
  _gqlv_meta: causeway_feat_ApplicationTypeAction__gqlv_meta
  actionSemantics: causeway_feat_ApplicationTypeAction__actionSemantics__gqlv_property
  memberName: causeway_feat_ApplicationTypeAction__memberName__gqlv_property
  namespaceName: causeway_feat_ApplicationTypeAction__namespaceName__gqlv_property
  parent: causeway_feat_ApplicationTypeAction__parent__gqlv_property
  returnType: causeway_feat_ApplicationTypeAction__returnType__gqlv_property
  typeSimpleName: causeway_feat_ApplicationTypeAction__typeSimpleName__gqlv_property
}

type causeway_feat_ApplicationTypeAction__actionSemantics__gqlv_property {
  choices(actionSemantics: String): [String]
  disabled: String
  get: String!
  hidden: Boolean
  validate(actionSemantics: String): String
}

type causeway_feat_ApplicationTypeAction__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationTypeAction__memberName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(memberName: String): String
}

type causeway_feat_ApplicationTypeAction__namespaceName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(namespaceName: String): String
}

type causeway_feat_ApplicationTypeAction__parent__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parent: causeway_feat_ApplicationFeatureViewModel__gqlv_input): String
}

type causeway_feat_ApplicationTypeAction__returnType__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(returnType: String): String
}

type causeway_feat_ApplicationTypeAction__typeSimpleName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(typeSimpleName: String): String
}

type causeway_feat_ApplicationTypeCollection {
  _gqlv_meta: causeway_feat_ApplicationTypeCollection__gqlv_meta
  derived: causeway_feat_ApplicationTypeCollection__derived__gqlv_property
  elementType: causeway_feat_ApplicationTypeCollection__elementType__gqlv_property
  memberName: causeway_feat_ApplicationTypeCollection__memberName__gqlv_property
  namespaceName: causeway_feat_ApplicationTypeCollection__namespaceName__gqlv_property
  parent: causeway_feat_ApplicationTypeCollection__parent__gqlv_property
  typeSimpleName: causeway_feat_ApplicationTypeCollection__typeSimpleName__gqlv_property
}

type causeway_feat_ApplicationTypeCollection__derived__gqlv_property {
  disabled: String
  get: Boolean!
  hidden: Boolean
  validate(derived: Boolean): String
}

type causeway_feat_ApplicationTypeCollection__elementType__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(elementType: String): String
}

type causeway_feat_ApplicationTypeCollection__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationTypeCollection__memberName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(memberName: String): String
}

type causeway_feat_ApplicationTypeCollection__namespaceName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(namespaceName: String): String
}

type causeway_feat_ApplicationTypeCollection__parent__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parent: causeway_feat_ApplicationFeatureViewModel__gqlv_input): String
}

type causeway_feat_ApplicationTypeCollection__typeSimpleName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(typeSimpleName: String): String
}

type causeway_feat_ApplicationTypeMember {
  _gqlv_meta: causeway_feat_ApplicationTypeMember__gqlv_meta
  memberName: causeway_feat_ApplicationTypeMember__memberName__gqlv_property
  namespaceName: causeway_feat_ApplicationTypeMember__namespaceName__gqlv_property
  parent: causeway_feat_ApplicationTypeMember__parent__gqlv_property
  typeSimpleName: causeway_feat_ApplicationTypeMember__typeSimpleName__gqlv_property
}

type causeway_feat_ApplicationTypeMember__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationTypeMember__memberName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(memberName: String): String
}

type causeway_feat_ApplicationTypeMember__namespaceName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(namespaceName: String): String
}

type causeway_feat_ApplicationTypeMember__parent__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parent: causeway_feat_ApplicationFeatureViewModel__gqlv_input): String
}

type causeway_feat_ApplicationTypeMember__typeSimpleName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(typeSimpleName: String): String
}

type causeway_feat_ApplicationTypeProperty {
  _gqlv_meta: causeway_feat_ApplicationTypeProperty__gqlv_meta
  derived: causeway_feat_ApplicationTypeProperty__derived__gqlv_property
  maxLength: causeway_feat_ApplicationTypeProperty__maxLength__gqlv_property
  memberName: causeway_feat_ApplicationTypeProperty__memberName__gqlv_property
  namespaceName: causeway_feat_ApplicationTypeProperty__namespaceName__gqlv_property
  parent: causeway_feat_ApplicationTypeProperty__parent__gqlv_property
  returnType: causeway_feat_ApplicationTypeProperty__returnType__gqlv_property
  typeSimpleName: causeway_feat_ApplicationTypeProperty__typeSimpleName__gqlv_property
  typicalLength: causeway_feat_ApplicationTypeProperty__typicalLength__gqlv_property
}

type causeway_feat_ApplicationTypeProperty__derived__gqlv_property {
  disabled: String
  get: Boolean!
  hidden: Boolean
  validate(derived: Boolean): String
}

type causeway_feat_ApplicationTypeProperty__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationTypeProperty__maxLength__gqlv_property {
  disabled: String
  get: Int
  hidden: Boolean
  validate(maxLength: Int): String
}

type causeway_feat_ApplicationTypeProperty__memberName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(memberName: String): String
}

type causeway_feat_ApplicationTypeProperty__namespaceName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(namespaceName: String): String
}

type causeway_feat_ApplicationTypeProperty__parent__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parent: causeway_feat_ApplicationFeatureViewModel__gqlv_input): String
}

type causeway_feat_ApplicationTypeProperty__returnType__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(returnType: String): String
}

type causeway_feat_ApplicationTypeProperty__typeSimpleName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(typeSimpleName: String): String
}

type causeway_feat_ApplicationTypeProperty__typicalLength__gqlv_property {
  disabled: String
  get: Int
  hidden: Boolean
  validate(typicalLength: Int): String
}

type causeway_feat_ApplicationType__actions__gqlv_collection {
  disabled: String
  get: [causeway_feat_ApplicationTypeAction]
  hidden: Boolean
}

type causeway_feat_ApplicationType__collections__gqlv_collection {
  disabled: String
  get: [causeway_feat_ApplicationTypeCollection]
  hidden: Boolean
}

type causeway_feat_ApplicationType__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_feat_ApplicationType__memberName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(memberName: String): String
}

type causeway_feat_ApplicationType__namespaceName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(namespaceName: String): String
}

type causeway_feat_ApplicationType__parent__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parent: causeway_feat_ApplicationFeatureViewModel__gqlv_input): String
}

type causeway_feat_ApplicationType__properties__gqlv_collection {
  disabled: String
  get: [causeway_feat_ApplicationTypeProperty]
  hidden: Boolean
}

type causeway_feat_ApplicationType__typeSimpleName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(typeSimpleName: String): String
}

type causeway_schema_metamodel_v2_DomainClassDto {
  _gqlv_meta: causeway_schema_metamodel_v2_DomainClassDto__gqlv_meta
  actions: causeway_schema_metamodel_v2_DomainClassDto__actions__gqlv_property
  annotations: causeway_schema_metamodel_v2_DomainClassDto__annotations__gqlv_property
  collections: causeway_schema_metamodel_v2_DomainClassDto__collections__gqlv_property
  facets: causeway_schema_metamodel_v2_DomainClassDto__facets__gqlv_property
  id: causeway_schema_metamodel_v2_DomainClassDto__id__gqlv_property
  majorVersion: causeway_schema_metamodel_v2_DomainClassDto__majorVersion__gqlv_property
  minorVersion: causeway_schema_metamodel_v2_DomainClassDto__minorVersion__gqlv_property
  properties: causeway_schema_metamodel_v2_DomainClassDto__properties__gqlv_property
  service: causeway_schema_metamodel_v2_DomainClassDto__service__gqlv_property
}

type causeway_schema_metamodel_v2_DomainClassDto__actions__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(actions: String): String
}

type causeway_schema_metamodel_v2_DomainClassDto__annotations__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(annotations: String): String
}

type causeway_schema_metamodel_v2_DomainClassDto__collections__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(collections: String): String
}

type causeway_schema_metamodel_v2_DomainClassDto__facets__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(facets: String): String
}

type causeway_schema_metamodel_v2_DomainClassDto__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_schema_metamodel_v2_DomainClassDto__id__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(id: String): String
}

type causeway_schema_metamodel_v2_DomainClassDto__majorVersion__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(majorVersion: String): String
}

type causeway_schema_metamodel_v2_DomainClassDto__minorVersion__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(minorVersion: String): String
}

type causeway_schema_metamodel_v2_DomainClassDto__properties__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(properties: String): String
}

type causeway_schema_metamodel_v2_DomainClassDto__service__gqlv_property {
  disabled: String
  get: Boolean!
  hidden: Boolean
  validate(service: Boolean): String
}

type causeway_security_LoginRedirect {
  _gqlv_meta: causeway_security_LoginRedirect__gqlv_meta
}

type causeway_security_LoginRedirect__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_security_LogoutMenu {
  logout: causeway_security_LogoutMenu__logout__gqlv_action
}

type causeway_security_LogoutMenu__logout__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke: String
  validate: String
}

type causeway_testing_fixtures_FixtureResult {
  _gqlv_meta: causeway_testing_fixtures_FixtureResult__gqlv_meta
  className: causeway_testing_fixtures_FixtureResult__className__gqlv_property
  fixtureScriptClassName: causeway_testing_fixtures_FixtureResult__fixtureScriptClassName__gqlv_property
  key: causeway_testing_fixtures_FixtureResult__key__gqlv_property
  object: causeway_testing_fixtures_FixtureResult__object__gqlv_property
}

type causeway_testing_fixtures_FixtureResult__className__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(className: String): String
}

type causeway_testing_fixtures_FixtureResult__fixtureScriptClassName__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(fixtureScriptClassName: String): String
}

type causeway_testing_fixtures_FixtureResult__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type causeway_testing_fixtures_FixtureResult__key__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(key: String): String
}

type causeway_testing_fixtures_FixtureResult__object__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(object: String): String
}

type java_lang_Runnable {
  _gqlv_meta: java_lang_Runnable__gqlv_meta
}

type java_lang_Runnable__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_Map {
  _gqlv_meta: java_util_Map__gqlv_meta
}

type java_util_Map__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_SortedMap {
  _gqlv_meta: java_util_SortedMap__gqlv_meta
}

type java_util_SortedMap__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_concurrent_Callable {
  _gqlv_meta: java_util_concurrent_Callable__gqlv_meta
}

type java_util_concurrent_Callable__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_function_BiFunction {
  _gqlv_meta: java_util_function_BiFunction__gqlv_meta
}

type java_util_function_BiFunction__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_function_Consumer {
  _gqlv_meta: java_util_function_Consumer__gqlv_meta
}

type java_util_function_Consumer__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_function_Function {
  _gqlv_meta: java_util_function_Function__gqlv_meta
}

type java_util_function_Function__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type java_util_stream_Stream {
  _gqlv_meta: java_util_stream_Stream__gqlv_meta
}

type java_util_stream_Stream__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_core_metamodel_inspect_model_MMNode {
  _gqlv_meta: org_apache_causeway_core_metamodel_inspect_model_MMNode__gqlv_meta
  childNodes: org_apache_causeway_core_metamodel_inspect_model_MMNode__childNodes__gqlv_collection
  parentNode: org_apache_causeway_core_metamodel_inspect_model_MMNode__parentNode__gqlv_property
}

type org_apache_causeway_core_metamodel_inspect_model_MMNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type org_apache_causeway_core_metamodel_inspect_model_MMNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_core_metamodel_inspect_model_MMNode__parentNode__gqlv_property {
  disabled: String
  hidden: Boolean
  validate(parentNode: org_apache_causeway_core_metamodel_inspect_model_MMNode__gqlv_input): String
}

type org_apache_causeway_core_metamodel_inspect_model_MemberNode {
  _gqlv_meta: org_apache_causeway_core_metamodel_inspect_model_MemberNode__gqlv_meta
  childNodes: org_apache_causeway_core_metamodel_inspect_model_MemberNode__childNodes__gqlv_collection
  mixedIn: org_apache_causeway_core_metamodel_inspect_model_MemberNode__mixedIn__gqlv_property
  parentNode: org_apache_causeway_core_metamodel_inspect_model_MemberNode__parentNode__gqlv_property
}

type org_apache_causeway_core_metamodel_inspect_model_MemberNode__childNodes__gqlv_collection {
  disabled: String
  hidden: Boolean
}

type org_apache_causeway_core_metamodel_inspect_model_MemberNode__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_core_metamodel_inspect_model_MemberNode__mixedIn__gqlv_property {
  disabled: String
  get: Boolean!
  hidden: Boolean
  validate(mixedIn: Boolean): String
}

type org_apache_causeway_core_metamodel_inspect_model_MemberNode__parentNode__gqlv_property {
  disabled: String
  get: causeway_applib_TypeNode!
  hidden: Boolean
  validate(parentNode: causeway_applib_TypeNode__gqlv_input): String
}

type org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript {
  _gqlv_meta: org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__gqlv_meta
  friendlyName: org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__friendlyName__gqlv_property
  qualifiedName: org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__qualifiedName__gqlv_property
}

type org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__friendlyName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(friendlyName: String): String
}

type org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__gqlv_meta {
  id: String!
  logicalTypeName: String!
}

type org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__qualifiedName__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(qualifiedName: String): String
}

type university_calc_Calculator {
  addBigDecimals: university_calc_Calculator__addBigDecimals__gqlv_action
  addBigIntegers: university_calc_Calculator__addBigIntegers__gqlv_action
  addByteWrappers: university_calc_Calculator__addByteWrappers__gqlv_action
  addBytes: university_calc_Calculator__addBytes__gqlv_action
  addDoubleWrappers: university_calc_Calculator__addDoubleWrappers__gqlv_action
  addDoubles: university_calc_Calculator__addDoubles__gqlv_action
  addFloatWrappers: university_calc_Calculator__addFloatWrappers__gqlv_action
  addFloats: university_calc_Calculator__addFloats__gqlv_action
  addIntegerWrappers: university_calc_Calculator__addIntegerWrappers__gqlv_action
  addIntegers: university_calc_Calculator__addIntegers__gqlv_action
  addShortWrappers: university_calc_Calculator__addShortWrappers__gqlv_action
  addShorts: university_calc_Calculator__addShorts__gqlv_action
  and: university_calc_Calculator__and__gqlv_action
  concat: university_calc_Calculator__concat__gqlv_action
  nextMonth: university_calc_Calculator__nextMonth__gqlv_action
  not: university_calc_Calculator__not__gqlv_action
  or: university_calc_Calculator__or__gqlv_action
  plusDays: university_calc_Calculator__plusDays__gqlv_action
  plusJodaDays: university_calc_Calculator__plusJodaDays__gqlv_action
}

type university_calc_Calculator__addBigDecimals__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Float!, y: Float): Float
  params: university_calc_Calculator__addBigDecimals__gqlv_action_params
  validate(x: Float, y: Float): String
}

type university_calc_Calculator__addBigDecimals__gqlv_action_params {
  x: university_calc_Calculator__addBigDecimals__x__gqlv_action_parameter
  y: university_calc_Calculator__addBigDecimals__y__gqlv_action_parameter
}

type university_calc_Calculator__addBigDecimals__x__gqlv_action_parameter {
  disabled(x: Float): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addBigDecimals__y__gqlv_action_parameter {
  disabled(x: Float, y: Float): String
  hidden(x: Float): Boolean
  validity: String
}

type university_calc_Calculator__addBigIntegers__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Int!, y: Int): Int
  params: university_calc_Calculator__addBigIntegers__gqlv_action_params
  validate(x: Int, y: Int): String
}

type university_calc_Calculator__addBigIntegers__gqlv_action_params {
  x: university_calc_Calculator__addBigIntegers__x__gqlv_action_parameter
  y: university_calc_Calculator__addBigIntegers__y__gqlv_action_parameter
}

type university_calc_Calculator__addBigIntegers__x__gqlv_action_parameter {
  disabled(x: Int): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addBigIntegers__y__gqlv_action_parameter {
  disabled(x: Int, y: Int): String
  hidden(x: Int): Boolean
  validity: String
}

type university_calc_Calculator__addByteWrappers__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: String!, y: String): Int
  params: university_calc_Calculator__addByteWrappers__gqlv_action_params
  validate(x: String, y: String): String
}

type university_calc_Calculator__addByteWrappers__gqlv_action_params {
  x: university_calc_Calculator__addByteWrappers__x__gqlv_action_parameter
  y: university_calc_Calculator__addByteWrappers__y__gqlv_action_parameter
}

type university_calc_Calculator__addByteWrappers__x__gqlv_action_parameter {
  disabled(x: String): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addByteWrappers__y__gqlv_action_parameter {
  disabled(x: String, y: String): String
  hidden(x: String): Boolean
  validity: String
}

type university_calc_Calculator__addBytes__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: String!, y: String!): String
  params: university_calc_Calculator__addBytes__gqlv_action_params
  validate(x: String, y: String): String
}

type university_calc_Calculator__addBytes__gqlv_action_params {
  x: university_calc_Calculator__addBytes__x__gqlv_action_parameter
  y: university_calc_Calculator__addBytes__y__gqlv_action_parameter
}

type university_calc_Calculator__addBytes__x__gqlv_action_parameter {
  disabled(x: String): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addBytes__y__gqlv_action_parameter {
  disabled(x: String, y: String): String
  hidden(x: String): Boolean
  validity: String
}

type university_calc_Calculator__addDoubleWrappers__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Float!, y: Float): Float
  params: university_calc_Calculator__addDoubleWrappers__gqlv_action_params
  validate(x: Float, y: Float): String
}

type university_calc_Calculator__addDoubleWrappers__gqlv_action_params {
  x: university_calc_Calculator__addDoubleWrappers__x__gqlv_action_parameter
  y: university_calc_Calculator__addDoubleWrappers__y__gqlv_action_parameter
}

type university_calc_Calculator__addDoubleWrappers__x__gqlv_action_parameter {
  disabled(x: Float): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addDoubleWrappers__y__gqlv_action_parameter {
  disabled(x: Float, y: Float): String
  hidden(x: Float): Boolean
  validity: String
}

type university_calc_Calculator__addDoubles__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Float!, y: Float!): Float
  params: university_calc_Calculator__addDoubles__gqlv_action_params
  validate(x: Float, y: Float): String
}

type university_calc_Calculator__addDoubles__gqlv_action_params {
  x: university_calc_Calculator__addDoubles__x__gqlv_action_parameter
  y: university_calc_Calculator__addDoubles__y__gqlv_action_parameter
}

type university_calc_Calculator__addDoubles__x__gqlv_action_parameter {
  disabled(x: Float): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addDoubles__y__gqlv_action_parameter {
  disabled(x: Float, y: Float): String
  hidden(x: Float): Boolean
  validity: String
}

type university_calc_Calculator__addFloatWrappers__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Float!, y: Float): Float
  params: university_calc_Calculator__addFloatWrappers__gqlv_action_params
  validate(x: Float, y: Float): String
}

type university_calc_Calculator__addFloatWrappers__gqlv_action_params {
  x: university_calc_Calculator__addFloatWrappers__x__gqlv_action_parameter
  y: university_calc_Calculator__addFloatWrappers__y__gqlv_action_parameter
}

type university_calc_Calculator__addFloatWrappers__x__gqlv_action_parameter {
  disabled(x: Float): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addFloatWrappers__y__gqlv_action_parameter {
  disabled(x: Float, y: Float): String
  hidden(x: Float): Boolean
  validity: String
}

type university_calc_Calculator__addFloats__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Float!, y: Float!): Float
  params: university_calc_Calculator__addFloats__gqlv_action_params
  validate(x: Float, y: Float): String
}

type university_calc_Calculator__addFloats__gqlv_action_params {
  x: university_calc_Calculator__addFloats__x__gqlv_action_parameter
  y: university_calc_Calculator__addFloats__y__gqlv_action_parameter
}

type university_calc_Calculator__addFloats__x__gqlv_action_parameter {
  disabled(x: Float): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addFloats__y__gqlv_action_parameter {
  disabled(x: Float, y: Float): String
  hidden(x: Float): Boolean
  validity: String
}

type university_calc_Calculator__addIntegerWrappers__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Int!, y: Int): Int
  params: university_calc_Calculator__addIntegerWrappers__gqlv_action_params
  validate(x: Int, y: Int): String
}

type university_calc_Calculator__addIntegerWrappers__gqlv_action_params {
  x: university_calc_Calculator__addIntegerWrappers__x__gqlv_action_parameter
  y: university_calc_Calculator__addIntegerWrappers__y__gqlv_action_parameter
}

type university_calc_Calculator__addIntegerWrappers__x__gqlv_action_parameter {
  disabled(x: Int): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addIntegerWrappers__y__gqlv_action_parameter {
  disabled(x: Int, y: Int): String
  hidden(x: Int): Boolean
  validity: String
}

type university_calc_Calculator__addIntegers__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Int!, y: Int!): Int
  params: university_calc_Calculator__addIntegers__gqlv_action_params
  validate(x: Int, y: Int): String
}

type university_calc_Calculator__addIntegers__gqlv_action_params {
  x: university_calc_Calculator__addIntegers__x__gqlv_action_parameter
  y: university_calc_Calculator__addIntegers__y__gqlv_action_parameter
}

type university_calc_Calculator__addIntegers__x__gqlv_action_parameter {
  disabled(x: Int): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addIntegers__y__gqlv_action_parameter {
  disabled(x: Int, y: Int): String
  hidden(x: Int): Boolean
  validity: String
}

type university_calc_Calculator__addShortWrappers__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Int!, y: Int): Int
  params: university_calc_Calculator__addShortWrappers__gqlv_action_params
  validate(x: Int, y: Int): String
}

type university_calc_Calculator__addShortWrappers__gqlv_action_params {
  x: university_calc_Calculator__addShortWrappers__x__gqlv_action_parameter
  y: university_calc_Calculator__addShortWrappers__y__gqlv_action_parameter
}

type university_calc_Calculator__addShortWrappers__x__gqlv_action_parameter {
  disabled(x: Int): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addShortWrappers__y__gqlv_action_parameter {
  disabled(x: Int, y: Int): String
  hidden(x: Int): Boolean
  validity: String
}

type university_calc_Calculator__addShorts__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Int!, y: Int!): Int
  params: university_calc_Calculator__addShorts__gqlv_action_params
  validate(x: Int, y: Int): String
}

type university_calc_Calculator__addShorts__gqlv_action_params {
  x: university_calc_Calculator__addShorts__x__gqlv_action_parameter
  y: university_calc_Calculator__addShorts__y__gqlv_action_parameter
}

type university_calc_Calculator__addShorts__x__gqlv_action_parameter {
  disabled(x: Int): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__addShorts__y__gqlv_action_parameter {
  disabled(x: Int, y: Int): String
  hidden(x: Int): Boolean
  validity: String
}

type university_calc_Calculator__and__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Boolean!, y: Boolean!): Boolean
  params: university_calc_Calculator__and__gqlv_action_params
  validate(x: Boolean, y: Boolean): String
}

type university_calc_Calculator__and__gqlv_action_params {
  x: university_calc_Calculator__and__x__gqlv_action_parameter
  y: university_calc_Calculator__and__y__gqlv_action_parameter
}

type university_calc_Calculator__and__x__gqlv_action_parameter {
  disabled(x: Boolean): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__and__y__gqlv_action_parameter {
  disabled(x: Boolean, y: Boolean): String
  hidden(x: Boolean): Boolean
  validity: String
}

type university_calc_Calculator__concat__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(prefix: String!, suffix: String): String
  params: university_calc_Calculator__concat__gqlv_action_params
  validate(prefix: String, suffix: String): String
}

type university_calc_Calculator__concat__gqlv_action_params {
  prefix: university_calc_Calculator__concat__prefix__gqlv_action_parameter
  suffix: university_calc_Calculator__concat__suffix__gqlv_action_parameter
}

type university_calc_Calculator__concat__prefix__gqlv_action_parameter {
  disabled(prefix: String): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__concat__suffix__gqlv_action_parameter {
  disabled(prefix: String, suffix: String): String
  hidden(prefix: String): Boolean
  validity: String
}

type university_calc_Calculator__nextMonth__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(month: String!): String
  params: university_calc_Calculator__nextMonth__gqlv_action_params
  validate(month: String): String
}

type university_calc_Calculator__nextMonth__gqlv_action_params {
  month: university_calc_Calculator__nextMonth__month__gqlv_action_parameter
}

type university_calc_Calculator__nextMonth__month__gqlv_action_parameter {
  choices: [String]
  disabled(month: String): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__not__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Boolean!): Boolean
  params: university_calc_Calculator__not__gqlv_action_params
  validate(x: Boolean): String
}

type university_calc_Calculator__not__gqlv_action_params {
  x: university_calc_Calculator__not__x__gqlv_action_parameter
}

type university_calc_Calculator__not__x__gqlv_action_parameter {
  disabled(x: Boolean): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__or__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(x: Boolean!, y: Boolean!): Boolean
  params: university_calc_Calculator__or__gqlv_action_params
  validate(x: Boolean, y: Boolean): String
}

type university_calc_Calculator__or__gqlv_action_params {
  x: university_calc_Calculator__or__x__gqlv_action_parameter
  y: university_calc_Calculator__or__y__gqlv_action_parameter
}

type university_calc_Calculator__or__x__gqlv_action_parameter {
  disabled(x: Boolean): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__or__y__gqlv_action_parameter {
  disabled(x: Boolean, y: Boolean): String
  hidden(x: Boolean): Boolean
  validity: String
}

type university_calc_Calculator__plusDays__date__gqlv_action_parameter {
  disabled(date: String): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__plusDays__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(date: String!, numDays: Int!): String
  params: university_calc_Calculator__plusDays__gqlv_action_params
  validate(date: String, numDays: Int): String
}

type university_calc_Calculator__plusDays__gqlv_action_params {
  date: university_calc_Calculator__plusDays__date__gqlv_action_parameter
  numDays: university_calc_Calculator__plusDays__numDays__gqlv_action_parameter
}

type university_calc_Calculator__plusDays__numDays__gqlv_action_parameter {
  disabled(date: String, numDays: Int): String
  hidden(date: String): Boolean
  validity: String
}

type university_calc_Calculator__plusJodaDays__date__gqlv_action_parameter {
  disabled(date: String): String
  hidden: Boolean
  validity: String
}

type university_calc_Calculator__plusJodaDays__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(date: String!, numDays: Int!): String
  params: university_calc_Calculator__plusJodaDays__gqlv_action_params
  validate(date: String, numDays: Int): String
}

type university_calc_Calculator__plusJodaDays__gqlv_action_params {
  date: university_calc_Calculator__plusJodaDays__date__gqlv_action_parameter
  numDays: university_calc_Calculator__plusJodaDays__numDays__gqlv_action_parameter
}

type university_calc_Calculator__plusJodaDays__numDays__gqlv_action_parameter {
  disabled(date: String, numDays: Int): String
  hidden(date: String): Boolean
  validity: String
}

type university_dept_Department {
  _gqlv_meta: university_dept_Department__gqlv_meta
  deptHead: university_dept_Department__deptHead__gqlv_property
  name: university_dept_Department__name__gqlv_property
  staffMembers: university_dept_Department__staffMembers__gqlv_collection
}

type university_dept_Department__deptHead__gqlv_property {
  autoComplete(search: String!): [university_dept_DeptHead]
  disabled: String
  get: university_dept_DeptHead
  hidden: Boolean
  validate(deptHead: university_dept_DeptHead__gqlv_input): String
}

type university_dept_Department__gqlv_meta {
  id: String!
  logicalTypeName: String!
  version: String
}

type university_dept_Department__name__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(name: String): String
}

type university_dept_Department__staffMembers__gqlv_collection {
  disabled: String
  get: [university_dept_StaffMember]
  hidden: Boolean
}

type university_dept_Departments {
  findAllDepartments: university_dept_Departments__findAllDepartments__gqlv_action
  findDepartmentByName: university_dept_Departments__findDepartmentByName__gqlv_action
}

type university_dept_Departments__findAllDepartments__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke: [university_dept_Department]
  validate: String
}

type university_dept_Departments__findDepartmentByName__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(name: String!): university_dept_Department
  params: university_dept_Departments__findDepartmentByName__gqlv_action_params
  validate(name: String): String
}

type university_dept_Departments__findDepartmentByName__gqlv_action_params {
  name: university_dept_Departments__findDepartmentByName__name__gqlv_action_parameter
}

type university_dept_Departments__findDepartmentByName__name__gqlv_action_parameter {
  disabled(name: String): String
  hidden: Boolean
  validity: String
}

type university_dept_DeptHead {
  _gqlv_meta: university_dept_DeptHead__gqlv_meta
  department: university_dept_DeptHead__department__gqlv_property
  name: university_dept_DeptHead__name__gqlv_property
}

type university_dept_DeptHead__department__gqlv_property {
  choices(department: university_dept_Department__gqlv_input): [university_dept_Department]
  disabled: String
  get: university_dept_Department
  hidden: Boolean
  validate(department: university_dept_Department__gqlv_input): String
}

type university_dept_DeptHead__gqlv_meta {
  id: String!
  logicalTypeName: String!
  version: String
}

type university_dept_DeptHead__name__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(name: String): String
}

type university_dept_DeptHeads {
  findAllHeads: university_dept_DeptHeads__findAllHeads__gqlv_action
  findHeadByName: university_dept_DeptHeads__findHeadByName__gqlv_action
}

type university_dept_DeptHeads__findAllHeads__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke: [university_dept_DeptHead]
  validate: String
}

type university_dept_DeptHeads__findHeadByName__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(name: String!): university_dept_DeptHead
  params: university_dept_DeptHeads__findHeadByName__gqlv_action_params
  validate(name: String): String
}

type university_dept_DeptHeads__findHeadByName__gqlv_action_params {
  name: university_dept_DeptHeads__findHeadByName__name__gqlv_action_parameter
}

type university_dept_DeptHeads__findHeadByName__name__gqlv_action_parameter {
  disabled(name: String): String
  hidden: Boolean
  validity: String
}

type university_dept_Staff {
  findAllStaffMembers: university_dept_Staff__findAllStaffMembers__gqlv_action
  findStaffMemberByName: university_dept_Staff__findStaffMemberByName__gqlv_action
}

type university_dept_StaffMember {
  _gqlv_meta: university_dept_StaffMember__gqlv_meta
  department: university_dept_StaffMember__department__gqlv_property
  grade: university_dept_StaffMember__grade__gqlv_property
  name: university_dept_StaffMember__name__gqlv_property
  photo: university_dept_StaffMember__photo__gqlv_property
}

type university_dept_StaffMember__department__gqlv_property {
  choices(department: university_dept_Department__gqlv_input): [university_dept_Department]
  disabled: String
  get: university_dept_Department
  hidden: Boolean
  validate(department: university_dept_Department__gqlv_input): String
}

type university_dept_StaffMember__gqlv_meta {
  id: String!
  logicalTypeName: String!
  version: String
}

type university_dept_StaffMember__grade__gqlv_property {
  choices(grade: String): [String]
  disabled: String
  get: String!
  hidden: Boolean
  validate(grade: String): String
}

type university_dept_StaffMember__name__gqlv_property {
  disabled: String
  get: String!
  hidden: Boolean
  validate(name: String): String
}

type university_dept_StaffMember__photo__gqlv_property {
  disabled: String
  get: String
  hidden: Boolean
  validate(photo: String): String
}

type university_dept_Staff__findAllStaffMembers__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke: [university_dept_StaffMember]
  validate: String
}

type university_dept_Staff__findStaffMemberByName__gqlv_action {
  disabled: String
  hidden: Boolean
  invoke(name: String!): university_dept_StaffMember
  params: university_dept_Staff__findStaffMemberByName__gqlv_action_params
  validate(name: String): String
}

type university_dept_Staff__findStaffMemberByName__gqlv_action_params {
  name: university_dept_Staff__findStaffMemberByName__name__gqlv_action_parameter
}

type university_dept_Staff__findStaffMemberByName__name__gqlv_action_parameter {
  disabled(name: String): String
  hidden: Boolean
  validity: String
}

input causeway_applib_DomainObjectList__gqlv_input {
  id: ID!
}

input causeway_applib_FacetGroupNode__gqlv_input {
  id: ID!
}

input causeway_applib_ParameterNode__gqlv_input {
  id: ID!
}

input causeway_applib_PropertyNode__gqlv_input {
  id: ID!
}

input causeway_applib_RoleMemento__gqlv_input {
  id: ID!
}

input causeway_applib_TypeNode__gqlv_input {
  id: ID!
}

input causeway_applib_UserMemento__gqlv_input {
  id: ID!
}

input causeway_applib_node_ActionNode__gqlv_input {
  id: ID!
}

input causeway_applib_node_CollectionNode__gqlv_input {
  id: ID!
}

input causeway_applib_node_FacetAttrNode__gqlv_input {
  id: ID!
}

input causeway_applib_node_FacetNode__gqlv_input {
  id: ID!
}

input causeway_conf_ConfigurationProperty__gqlv_input {
  id: ID!
}

input causeway_conf_ConfigurationViewmodel__gqlv_input {
  id: ID!
}

input causeway_feat_ApplicationFeatureViewModel__gqlv_input {
  id: ID!
}

input causeway_feat_ApplicationNamespace__gqlv_input {
  id: ID!
}

input causeway_feat_ApplicationTypeAction__gqlv_input {
  id: ID!
}

input causeway_feat_ApplicationTypeCollection__gqlv_input {
  id: ID!
}

input causeway_feat_ApplicationTypeMember__gqlv_input {
  id: ID!
}

input causeway_feat_ApplicationTypeProperty__gqlv_input {
  id: ID!
}

input causeway_feat_ApplicationType__gqlv_input {
  id: ID!
}

input causeway_schema_metamodel_v2_DomainClassDto__gqlv_input {
  id: ID!
}

input causeway_security_LoginRedirect__gqlv_input {
  id: ID!
}

input causeway_testing_fixtures_FixtureResult__gqlv_input {
  id: ID!
}

input java_lang_Runnable__gqlv_input {
  id: ID!
}

input java_util_Map__gqlv_input {
  id: ID!
}

input java_util_SortedMap__gqlv_input {
  id: ID!
}

input java_util_concurrent_Callable__gqlv_input {
  id: ID!
}

input java_util_function_BiFunction__gqlv_input {
  id: ID!
}

input java_util_function_Consumer__gqlv_input {
  id: ID!
}

input java_util_function_Function__gqlv_input {
  id: ID!
}

input java_util_stream_Stream__gqlv_input {
  id: ID!
}

input org_apache_causeway_core_metamodel_inspect_model_MMNode__gqlv_input {
  id: ID!
}

input org_apache_causeway_core_metamodel_inspect_model_MemberNode__gqlv_input {
  id: ID!
}

input org_apache_causeway_testing_fixtures_applib_fixturescripts_FixtureScript__gqlv_input {
  id: ID!
}

input university_dept_Department__gqlv_input {
  id: ID!
}

input university_dept_DeptHead__gqlv_input {
  id: ID!
}

input university_dept_StaffMember__gqlv_input {
  id: ID!
}
