[[AuditerService]]
= `AuditerService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:




The `AuditerService` auditing service provides a simple mechanism to capture changes to data.
It is called for each property that has changed on any domain object, as a set of pre- and post-values.

== SPI

The SPI for the service is:

[source,java]
----
include::refguide:applib-svc:example$services/audit/AuditerService.java[tag=refguide]
----
<1> whether this implementation is enabled.
If all configured implementations are disabled, then auditing is suppressed (a minor performance optimization).
<2> together the `transactionId` (misnamed; really is the request/interaction Id) and the `sequence` uniquely identify the transaction in which the object was changed.
<3> identifies the object that has changed
<4> the property of the object that has changed.
The combination of the `transactionId`, `sequence`, `target` and `propertyName` is unique.
<5> the before and after values of the property (in string format).
If the object was created then "[NEW]" is used as the pre-value; if the object was deleted then "[DELETED]" is used as the post-value.
<6> the user that changed the object, and the date/time that this occurred.

The framework will call this for each and every domain object property that is modified within a transaction.

== Implementations

The framework allows multiple implementations of this service to be registered; all will be called.

There are two implementations provided by the framework:

* The core framework provides the `AuditerServiceLogging` (in `o.a.i.applib.services.audit` package).
This simply logs the messages to a link:https://logging.apache.org/log4j/log4j-2.2/manual/configuration.html[Log4j2] logger.
+
[source,xml]
.log4j2-spring.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
  <Properties> ... </Properties>
  <Appenders> ... </Appenders>
  <Loggers>
    ...
    <logger
      name="org.apache.isis.applib.services.audit.AuditerServiceLogging"
      level="debug"/>
    ...
  </Loggers>
</Configuration>
----
+
See the `log4j2-spring.xml` file in xref:docs:starters:simpleapp.adoc[simpleapp] for the omitted detail.

* the xref:security:audit-trail:about.adoc[Audit Trail] extension persists each audit record in a relational table.
As its name implies, it uses xref:pjdo:ROOT:about.adoc[JDO/DataNucleus] to do this.

