= `BookmarkService`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The `BookmarkService` domain service (and its various supertypes) provides the ability to obtain a serializable xref:BookmarkService.adoc#bookmark[`Bookmark`] for any (persisted) domain object, and to lookup domain objects given a xref:BookmarkService.adoc#bookmark[`Bookmark`].
This can then in turn be converted to and from a string.

For example, a `Customer` object with an xref:refguide:applib-ant:DomainObject.adoc#objectType[object type] of "custmgmt.Customer" and an id of 123
would correspond to a xref:BookmarkService.adoc#bookmark[`Bookmark`] with a string representation of "custmgmt.Customer|123".

Bookmarks are useful to store a reference to an arbitrary object, although be aware that there is no referential integrity.

Several of the extension libraries use bookmarks.
For example the xref:refguide:applib-svc:AuditerService.adoc[`AuditerService`] uses bookmarks to identify the object that is being modified.

Serialized form of bookmarks also appear within  xref:refguide:schema:about.adoc[schema] instances, for example as used by xref:refguide:applib-svc:CommandService.adoc[`CommandService`] and the xref:refguide:applib-svc:PublisherService.adoc[`PublisherService`].



== API

The API defined by `BookmarkService` is:

[source,java]
----
include::refguide:applib-svc:example$services/bookmark/BookmarkService.java[tags="refguide"]
----

=== `Bookmark`

The `Bookmark` type is:

[source,java]
----
include::refguide:applib-svc:example$services/bookmark/Bookmark.java[tags="refguide"]
----


== Implementation

The core framework (xref:core:runtime-services:about.adoc[Runtime Services] module) provides a default implementation of this API, namely `o.a.i.core.runtimeservices.bookmarks.BookmarkServiceDefault`.


== Related Mixins

The `BookmarkHolder` interface is intended to be implemented by domain objects that use a `Bookmark` to reference a (single) domain object; an example might be a class such as the audit entry, mentioned above.
The interface is simply:

[source,java]
----
include::refguide:applib-svc:example$services/bookmark/BookmarkHolder.java[tags="refguide"]
----

There are two mixins that will contribute to this interface:

* `BookmarkHolder_lookup`
+
which contributes a `lookup` action to return the referenced object

* `BookmarkHolder_object`
+
which contributes instead an `object` property, being the referenced object.

Either of these can be suppressed, if required, using a vetoing subscriber that listens to the action or property domain event in order to hide the member.


