= `ConfigurationViewService`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The `ConfigurationViewService`

WARNING: TODO: v2: to document - backing service for ConfigurationMenu;

returns `ConfigurationProperty` view model.  Only returns `isis.\*` and `resteasy.*`


== API

The API defined by this service is very simple:

[source,java]
----
include::refguide:applib-svc:example$services/confview/ConfigurationViewService.java[tags="refguide"]
----

where `ConfigurationProperty` is a view model:

[source,java]
----
include::refguide:applib-svc:example$services/confview/ConfigurationProperty.java[tags="refguide"]
----

== Implementation

The core framework (xref:core:runtime-services:about.adoc[Runtime Services] module) provides a default implementation of this API, namely `o.a.i.core.runtimeservices.confmenu.ConfigurationViewServiceDefault`.



== Related Services

* The configuration properties for Apache Isis can also be obtained from the xref:refguide:config:about.adoc#isisconfiguration-domain-service[`IsisConfiguration`] domain service.
These provide link:https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-typesafe-configuration-properties[type-safe] access to all `isis.*` configuration properties.
+
[NOTE]
====
`IsisConfiguration` is part of xref:refguide:config:about.adoc[`isis-core-config`] rather than the applib.

To use it therefore requires this dependency:
[source,xml]
.pom.xml
----
<dependency>
    <groupId>org.apache.isis.core</groupId>
    <artifactId>isis-core-config</artifactId>
</dependency>
----
====

* The xref:refguide:applib-svc:ConfigurationMenu.adoc[ `ConfigurationMenu`] provides a UI to access this service.

