[#EmailService]
= EmailService

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:

The `EmailService` provides the ability to send HTML emails, with attachments, to one or more recipients.

Apache Isis provides a default implementation to send emails (as an HTML message) using an external SMTP provider.

== API

The API for the service is:

[source,java]
----
public interface EmailService {
    boolean send(                                                   // <.>
        List<String> to, List<String> cc, List<String> bcc,         // <.>
        String subject,
        String body,                                                // <.>
        DataSource... attachments);
    boolean isConfigured();                                         // <.>
}
----
<.> is the main API to send the email (and optional attachments).
Will return `false` if failed to send
<.> pass either `null` or `Collections.emptyList()` if not required
<.> should be HTML text
<.> indicates whether the implementation was configured and initialized correctly.
If this returns `false` then any attempt to call `send(...)` will fail.

== Implementation

As noted in the introduction, the core framework provides a default implementation, `EmailServiceDefault`.
This sends email as an HTML message, using an external SMTP provider.

=== Configuration Properties

The default implementation defines a number of xref:refguide:config:sections/isis.core.runtime-services.adoc[configuration properties], under the `isis.core.runtime-services.email` key.


=== Alternatives

If you wish to write an alternative implementation, be aware that it should process the message body as HTML (as opposed to plain text or any other format).


== Related Services

The email service is used by the xref:refguide:applib-svc:EmailNotificationService.adoc[`EmailNotificationService`] which is, in turn, used by xref:refguide:applib-svc:UserRegistrationService.adoc[`UserRegistrationService`].
