= `FactoryService`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:

WARNING: TODO: this content has not yet been reviewed/updated for v2.0


The `FactoryService` collects together methods for instantiating domain objects.

== API

The API of `FactoryService` is:

[source,java]
----
include::refguide:applib-svc:example$services/factory/FactoryService.java[tags="refguide"]
----
<.> General purpose factory method, to automatically get or create an instance of the required type.
Maps onto one of the specialized factory methods `#get(Class)` or `#create(Class)` based on the type's meta-data.
<.> Gets an instance (possibly shared or independent) of the specified type, with injection points resolved and any life-cycle callback processed.
<.> Creates a new detached (not yet persisted) entity instance, with injection points resolved and defaults applied.
The class must have a no-arg constructor (for xref:pjdo:ROOT:about.adoc[JDO/DataNucleus], the enhancer adds this automatically).
<.> Resolves injection points for given entity.
<.> Creates a new Mixin instance, with injection points resolved.
The class must have a 1-arg constructor of the appropriate type.
<.> Creates a new ViewModel instance, with injection points resolved, and initialized according to the given memento string.
<.> Creates a new ViewModel instance, with injection points resolved and defaults applied.
<.> Resolves injection points for given ViewModel instance.
<.> Creates a new instance of the specified class, with injection points resolved and defaults applied.



The object is created in memory, but (if an entity) is not persisted.
The benefits of using this method (instead of simply using the Java `new` keyword) are:

* any services will be injected into the object immediately (otherwise they will not be injected until the frameworkbecomes aware of the object, typically when it is persisted through the xref:refguide:applib-svc:RepositoryService.adoc[`RepositoryService`]

* the default value for any properties (usually as specified by `defaultXxx()` supporting methods) or from the value type itself will be set and the `created()` callback will be called.

An alternative idiom is to just `new` up the object and then use  xref:refguide:applib-svc:ServiceInjector.adoc[`ServiceInjector`] domain service can be used to inject services into the domain object.
Note though that no default values will be set on the created object.



== Usage

For example:

[source,java]
----
Customer cust = factoryService.detachedEntity(Customer.class);
cust.setFirstName("Freddie");
cust.setLastName("Mercury");
repositoryService.persist(cust);
----


== Implementation

The core framework provides a default implementation of this service (`o.a.i.core.metamodel.services.factory.FactoryServiceDefault`).




== Related Services

The xref:refguide:applib-svc:RepositoryService.adoc[`RepositoryService`] is often used in conjunction with the `FactoryService`, to persist domain objects after they have been instantiated and populated.

An alternative to using the factory service is to simply instantiate the object ("new is the new new") and then use the xref:refguide:applib-svc:ServiceRegistry.adoc[`ServiceRegistry`] service to inject other domain services into the instantiated object.
