= `GridLoaderService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:



The `GridLoaderService` provides the ability to load the XML layout (grid) for a domain class.

== SPI

The SPI defined by this service is:

[source,java]
----
public interface GridLoaderService {
    boolean supportsReloading();                // <1>
    void remove(Class<?> domainClass);          // <2>
    boolean existsFor(Class<?> domainClass);    // <3>
    Grid load(final Class<?> domainClass);      // <4>
}
----
<1> whether dynamic reloading of layouts is enabled.  The default implementation enables reloading for prototyping, disables in production
<2> support metamodel invalidation/rebuilding of spec, eg as called by this xref:refguide:applib-cm:rgcms.adoc#__rgcms_classes_mixins_Object_rebuildMetamodel[Object mixin] action.
<3> whether any persisted layout metadata (eg a `.layout.xml` file) exists for this domain class.
<4> returns a new instance of a xref:refguide:applib-cm:classes/layout.adoc#component[`Grid`] for the specified domain class, eg as loaded from a `layout.xml` file.  If none exists, will return null (and the calling xref:refguide:applib-svc:GridService.adoc[`GridService`] will use xref:refguide:applib-svc:GridSystemService.adoc[`GridSystemService`] to obtain a default grid for the domain class).



== Implementation

The framework provides a default implementation of this service, namely `GridLoaderServiceDefault`.  This implementation
loads the grid from its serialized representation as a `.layout.xml` file, loaded from the classpath.

For example, the layout for a domain class `com.mycompany.myapp.Customer` would be loaded from `com/mycompany/myapp/Customer.layout.xml`.



== Related Services

This service is used by xref:refguide:applib-svc:GridService.adoc[`GridService`].
