= `HealthCheckService`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


This service integrates with Spring Boot's link:https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/health/HealthIndicator.html[HealthIndicator] SPI, surfaced through the link:https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html[Spring Boot Actuator].

WARNING: TODO: v2: update - rest of this documentation is out of date.



This service, if implemented, is used to performs a health check to determine if the application is still available.
The results of this service are made available through a REST resource, typically mounted at `/restful/health`.

The service, when called, will be within the context of a special internal user `__health` with the internal role `__health-role`.

This service was introduced to allow deployment infrastructure to monitor the app and (potentially) restart it if required.
For example, if deploying to Docker then both Docker Swarm and Kubernetes are orchestrators that can perform this task.


== SPI & Implementation

The SPI defined by `HealthCheckService` is:

[source,java]
----
include::refguide:applib-svc:example$services/health/HealthCheckService.java[tags="refguide"]
----

There is no default implementation, but the xref:docs:starters:simpleapp.adoc[simpleapp] starter app provides a sample implementation:

[source,java]
----
@Service
@Named("domainapp.HealthCheckServiceImpl")
@Log4j2
public class HealthCheckServiceImpl implements HealthCheckService {

    private final SimpleObjects simpleObjects;

    @Inject
    public HealthCheckServiceImpl(SimpleObjects simpleObjects) {
        this.simpleObjects = simpleObjects;
    }

    @Override
    public Health check() {
        try {
            simpleObjects.ping();
            return Health.ok();
        } catch (Exception ex) {
            return Health.error(ex);
        }
    }
}
----


