[#InteractionContext]
= InteractionContext

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The `InteractionContext` is a request-scoped domain service that is used to obtain the current
`Interaction`.

An `Interaction` generally consists of a single top-level `Execution`, either to invoke an action or to edit a property.
If that top-level action or property uses xref:refguide:applib-svc:WrapperFactory.adoc[`WrapperFactory`] to invoke child actions/properties, then those sub-executions are captured as a call-graph.
The `Execution` is thus a graph structure.

If a bulk action is performed (as per an action annotated using xref:refguide:applib-ant:Action.adoc#invokeOn[`@Action#invokeOn`]), then this will result in multiple ``Interaction``s, one per selected object (not one `Interaction` with multiple top-level ``Execution``s).

It is possible for ``Interaction.Execution``s to be persisted; this is supported by the xref:mappings:outbox-publisher:about.adoc[Outbox Publisher] mapping module, for example.
Persistent``Interaction``s support several use cases:

* they enable profiling of the running application (which actions are invoked then most often, what is their response time)

* if auditing is configured (using xref:refguide:applib-svc:AuditerService.adoc[`AuditerService`]), they provide better audit information, since the
`Interaction.Execution` captures the 'cause' of an interaction and can be correlated to the audit records (the "effect" of the interaction) by way of the xref:applib-classes:roles-mixins-contributees/contributee.adoc#HasUniqueId[`transactionId`]

== API

The public API of the service consists of several related classes:

* `InteractionContext` domain service itself:
* `Interaction` class, obtainable from the `InteractionContext`
+
The `Interaction` can be used to obtain the `Command` object representing the top-level invocation action/property edit.
* `Execution` class, obtainable from the `Interaction`.

The `Execution` class itself is abstract; there are two subclasses, `ActionInvocation` and `PropertyEdit`.

== API

include::system:generated:page$index/applib/services/iactn/InteractionContext.adoc[leveloffset=+2]

TODO example migration

.Deprecated Docs
[WARNING]
================================

=== `InteractionContext`

The public API of the `InteractionContext` domain service itself consists of simply:

[source,java]
----
include::refguide:applib-svc:example$services/iactn/InteractionContext.java[tags="refguide"]
----
<.> Returns the currently active {@link Interaction} for this thread.

This class is concrete (that is, it is also the implementation).


================================

== API

include::system:generated:page$index/applib/services/iactn/Interaction.adoc[leveloffset=+2]

TODO example migration

.Deprecated Docs
[WARNING]
================================

=== `Interaction`

The public API of the `Interaction` class consists of:

[source,java]
----
include::refguide:applib-svc:example$services/iactn/Interaction.java[tags="refguide"]
----
<.> The unique identifier of this interaction.
<.> Returns a (list of) execution}s in the order that they were pushed.
Generally there will be just one entry in this list, but additional entries may arise from the use of mixins/contributions when re-rendering a modified object.
<.> The current execution.
<.> The member `Execution` (action invocation or property edit) that preceded the current one.
<.> Generates numbers in a named sequence.
Used by the framework both to number successive interaction ``Execution``s and for events published by the xref:refguide:applib-svc:ExecutionSubscriber.adoc[`PublisherService`].

This class is concrete (is also the implementation).


================================

=== `Interaction.Execution`

The `Interaction.Execution` (static nested) class represents an action invocation/property edit as a node in a call-stack execution graph.
Sub-executions can be performed using the
xref:refguide:applib-svc:WrapperFactory.adoc[`WrapperFactory`].

It has the following public API:

[source,java]
----
public abstract class Execution {
    public Interaction getInteraction();            // <.>
    public InteractionType getInteractionType();    // <.>
    public String getMemberIdentifier();            // <.>
    public Object getTarget();                      // <.>

    public String getTargetClass();                 // <.>
    public String getTargetMember();

    public Execution getParent();                   // <.>
    public List<Execution> getChildren();

    public AbstractDomainEvent getEvent();          // <.>

    public Timestamp getStartedAt();                // <.>
    public Timestamp getCompletedAt();

    public Object getReturned();                    // <.>
    public Exception getThrew();

    public T getDto();                              // <.>
}
----

<.> The owning `Interaction`.
<.> Whether this is an action invocation or a property edit.
<.> A string uniquely identifying the action or property (similar to Javadoc syntax).
<.> The object on which the action is being invoked or property edited.
In the case of a mixin this will be the mixin object itself (rather than the mixed-in object).
<.> A human-friendly description of the class of the target object, and of the name of the action invoked/property edited on the target object.
<.> The parent action/property that invoked this action/property edit (if any), and any actions/property edits made in turn via the xref:refguide:applib-svc:WrapperFactory.adoc[`WrapperFactory`].
<.> The domain event fired via the xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`] representing the execution of this action invocation/property edit.
<.> The date/time at which this execution started/completed.
<.> The object returned by the action invocation/property edit, or the exception thrown.
For `void` methods and for actions returning collections, the value will be `null`.
<.> A DTO (instance of the xref:refguide:schema:ixn.adoc["ixn" schema]) being a serializable representation of this action invocation/property edit.


There are two concrete subclasses of `Execution`.

The first is `ActionInvocation`, representing the execution of an action being invoked:

[source,java]
----
public class ActionInvocation extends Execution {
    public List<Object> getArgs();                  // <1>
}
----
<1> The objects passed in as the arguments to the action's parameters.
Any of these could be `null`.

The second is `PropertyEdit`, and naturally enough represents the execution of a property being edited:

[source,java]
----
public class PropertyEdit extends Execution {
    public Object getNewValue();                    // <1>
}
----
<1> The object used as the new value of the property.
Could be `null` if the property is being cleared.

== Implementation

This class (`o.a.i.applib.services.iactn.InteractionContext`) is also the default implementation.

== Interacting with the services

Typically domain objects will have little need to interact with the `InteractionContext` and `Interaction` directly.
The services are used within the framework however, primarily to support the
xref:refguide:applib-svc:ExecutionSubscriber.adoc[`PublisherService`] SPI, and to emit domain events over the
xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`].

