[#MenuBarsService]
= MenuBarsService

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


WARNING: TODO: this content has not yet been reviewed/updated for v2.0

The `MenuBarsService` is responsible for returning a xref:applib-classes:layout.adoc#menubars-layout[`MenuBars`] instance, a data structure representing the arrangement of domain service actions across multiple menu bars, menus and sections.
This is used by the Wicket viewer to build up the menu, and is also served as the "menuBars" resource by the xref:vro:ROOT:about.adoc[Restful Objects] viewer.

== API

include::system:generated:page$index/applib/services/menu/MenuBarsService.adoc[leveloffset=+2]

TODO example migration

.Deprecated Docs
[WARNING]
================================

== SPI

The SPI defined by this service is:

[source,java]
----
include::refguide:applib-svc:example$services/menu/MenuBarsService.java[tags="refguide"]
----
<.> Convenience API to return the default `MenuBars` instance
<.> Returns an instance of `MenuBars` according the specified type...

\... where `Type` is used to specify whether to return the "default" `MenuBars` instance - which may be obtained from anywhere, eg read from the classpath, or to "fallback"" and derive from the metamodel facet/annotations.

[source,java]
----
include::refguide:applib-svc:example$services/menu/MenuBarsService.java[tags="refguide-1"]
----


================================

== Implementation

The framework provides a default implementation of this service, namely `o.a.i.core.runtime.services.menu.MenuBarsServiceDefault`.
This uses the xref:refguide:applib-svc:MenuBarsLoaderService.adoc[MenuBarsLoaderService] to load a serialized form of `MenuBars` instance, called `menubars.layout.xml`, from the classpath.
