= `RepositoryService`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:

WARNING: TODO - to review for v2.

The `RepositoryService` collects together methods for creating, persisting and searching for entities from the underlying persistence store.
It acts as an abstraction over the JDO/DataNucleus objectstore.

You can use it during prototyping to write naive queries (find all rows, then filter using the Guava `Predicate` API, or you can use it to call JDO link:http://www.datanucleus.org/products/accessplatform_4_0/jdo/query.html#named[named queries] using JDOQL.



== API

The API of `RepositoryService` is:

[source,java]
----
include::refguide:applib-svc:example$services/repository/RepositoryService.java[tags="refguide"]
----
<.> determine the state of this domain entity:
+
[source,java]
----
include::refguide:applib-svc:example$services/repository/EntityState.java[tags="refguide"]
----

<.> create a new non-persisted domain entity.
This is identical to
xref:refguide:applib-svc:FactoryService.adoc[`FactoryService`]'s `detachedEntity(...)` method, but is provided in the
``RepositoryService``'s API too because instantiating and persisting objects are often done together.

<.> persist (ie save) an object to the persistent object store (or do nothing if it is already persistent).

<.> persist (ie save) and flush; same as `persist()`, but also flushes changes to database and updates managed properties and collections (i.e., 1-1, 1-n, m-n relationships automatically maintained by the DataNucleus persistence mechanism).

<.> remove (ie delete) an object from the persistent object store (or do nothing if it has already been deleted).

<.> remove (delete) and flush;  same as `remove()`, but also flushes changes to database and updates managed properties and collections (i.e., 1-1, 1-n, m-n relationships automatically maintained by the DataNucleus persistence mechanism).

<.> return all persisted instances of specified type.
Mostly for prototyping, though can be useful to obtain all instances of domain entities if the number is known to be small.

<.> as previous, with paging.

<.> all persisted instances matching the `Predicate`.
Client-side filtering so only really intended for prototyping.

<.> as previous, with paging.

<.> all persisted instances matching the (server-side) `Query`.
*This is the primary API used for querying*

<.> returns the one-and-only match of an instance matching the `Predicate`.
If there is more that one instances a run-time exception will be thrown.
Client-side filtering so only really intended for prototyping.

<.> returns the one-and-only match of an instance matching the (server-side) `Query`
Generally this method is preferred for looking up an object by its (primary or alternate) key.

<.> returns the first instance that matches the `Predicate`.
No exception is thrown if more than one matches, so this is less strict that `uniqueMatch(...)`.
Client-side filtering so only really intended for prototyping.

<.> returns the first instance that matches the (server-side) `Query`.
No exception is thrown if more than one matches, so this is less strict that `uniqueMatch(...)`.


The `uniqueMatch(...)` methods are the recommended way of querying for (precisely) one instance.
The `firstMatch(...)` methods are for less strict querying.


== Usage

This section briefly discusses how application code can use (some of) these APIs.


=== Persist

[source,java]
----
Customer cust = repositoryService.detachedEntity(Customer.class);
cust.setFirstName("Freddie");
cust.setLastName("Mercury");
repositoryService.persist(cust);
----

You should be aware that by default Apache Isis queues up calls to `#persist()` and `#remove()`.
These are then executed either when the request completes (and the transaction commits), or if the queue is flushed.
This can be done either implicitly by the framework, or as the result of a direct call to `#flush()`.

By default the framework itself will cause `#flush()` to be called whenever a query is executed by way of `#allMatches(Query)`.
However, this behaviour can be disabled using the  xref:refguide:config:configuring-core.adoc[configuration property] `isis.services.container.disableAutoFlush`.



=== `persistAndFlush(...)`, `removeAndFlush(...)`

In some cases, such as when using managed properties and collections for implementing 1-1, 1-n, or m-n relationships, the developer needs to invoke `flush()` to send the changes to the DataNucleus persistence mechanism.
These managed properties and collections and then updated.

The `persistAndFlush(...)` and `removeAndFlush(...)` methods save the developer from having to additionally call the `flush(...)` method after calling `persist()` or `remove()`.

For example, the following code requires a flush to occur, so uses these methods:

[source,java]
----
public abstract class Warehouse extends SalesVIPEntity<Marketplace> {

    @Persistent(mappedBy = "marketplace", dependentElement = "true")
    @Getter @Setter                                                             // <1>
    private SortedSet<MarketplaceExcludedProduct> excludedProducts =
                            new TreeSet<MarketplaceExcludedProduct>();

    @Action(semantics = SemanticsOf.IDEMPOTENT)
    public MarketplaceExcludedProduct addExcludedProduct(final Product product) {
        MarketplaceExcludedProduct marketplaceExcludedProduct = this.findExcludedProduct(product);
        if (marketplaceExcludedProduct == null) {
            marketplaceExcludedProduct =
                this.repositoryService.detachedEntity(MarketplaceExcludedProduct.class);
        }

        this.wrap(marketplaceExcludedProduct).setMarketplace(this);
        this.wrap(marketplaceExcludedProduct).setProduct(product);

        this.repositoryService.persistAndFlush(marketplaceExcludedProduct);     // <2>
        return marketplaceExcludedProduct;
    }

    @Action(semantics = SemanticsOf.IDEMPOTENT)
    public void deleteFromExcludedProducts(final Product product) {
        final MarketplaceExcludedProduct marketplaceExcludedProduct = findExcludedProduct(product);
        if (marketplaceExcludedProduct != null) {
            this.repositoryService.removeAndFlush(marketplaceExcludedProduct);
        }
    }
    ...                                                                         // <3>
}
----
<1> using lombok for brevity
<2> Needed for updating the managed properties and collections.
<3> injected services and other methods ommited

On the “addExcludedProduct()” action, if the user didn't flush, the following test would fail because the managed collection would not containing the given product:

[source,java]
----
@Test
public void addExcludedProduct() {

    // given
    final AmazonMarketplace amazonMarketplace = this.wrapSkipRules(
        this.marketplaceRepository).findOrCreateAmazonMarketplace(
            AmazonMarketplaceLocation.FRANCE);

    final Product product = this.wrap(this.productRepository)
        .createProduct(UUID.randomUUID().toString(), UUID.randomUUID().toString());

    // when
    this.wrap(amazonMarketplace).addExcludedProduct(product);

    // then
    Assertions.assertThat(
            this.wrapSkipRules(amazonMarketplace).findAllProductsExcluded()
        ).contains(product);                                                    // <1>
}
----
<1> this would fail.



=== Query and `xxxMatches(...)`

There are various implementations of the `Query` API, but these either duplicate functionality of the other overloads of `allMatches(...)` or they are not supported by the JDO/DataNucleus object store.
The only significant implementation of `Query` to be aware of is `QueryDefault`, which identifies a named query and a set of parameter/argument tuples.

For example, in the http://github.com/apache/isis-app-todoapp[TodoApp] the `ToDoItem` is annotated:

[source,java]
----
@javax.jdo.annotations.Queries( {
    @javax.jdo.annotations.Query(
            name = "findByAtPathAndComplete", language = "JDOQL",               // <1>
            value = "SELECT "
                    + "FROM todoapp.dom.module.todoitem.ToDoItem "
                    + "WHERE atPath.indexOf(:atPath) == 0 "                     // <2>
                    + "   && complete == :complete"),                           // <3>
    ...
})
public class ToDoItem ... {
    ...
}
----
<1> name of the query
<2> defines the `atPath` parameter
<3> defines the `complete` parameter

This JDO query definitions are used in the `ToDoItemRepositoryImplUsingJdoql` service:

[source,java]
----
import org.springframework.stereotype.Service;

@Service
public class ToDoItemRepositoryImplUsingJdoql implements ToDoItemRepositoryImpl {
    @Programmatic
    public List<ToDoItem> findByAtPathAndCategory(final String atPath, final Category category) {
        return repositoryService.allMatches(
                new QueryDefault<>(ToDoItem.class,
                        "findByAtPathAndCategory",                              // <1>
                        "atPath", atPath,                                       // <2>
                        "category", category));                                 // <3>
    }
    ...
    @javax.inject.Inject
    RepositoryService repositoryService;
}
----
<1> corresponds to the "findByAtPathAndCategory" JDO named query
<2> provide argument for the `atPath` parameter.
The pattern is parameter, argument, parameter, argument, ... and so on.
<3> provide argument for the `category` parameter.
The pattern is parameter, argument, parameter, argument, ... and so on.

Other JDOQL named queries (not shown) follow the exact same pattern.

With respect to the other query APIs, the varargs parameters are optional, but allow for (client-side and managed) paging.
The first parameter is the `start` (0-based, the second is the `count`.

[TIP]
====
If using JDO/DataNucleus, it is also possible to use the DataNucleus type-safe query API.
For more details, see xref:pjdo:ROOT:services/IsisJdoSupport.adoc[`IsisJdoSupport`].
====



== Implementation

The default implementation of this domain service is `o.a.i.core.metamodel.services.repository.RepositoryServiceDefault`.

WARNING: TODO: v2 - discuss `EntityState`.

=== Configuration Properties

The default implementation of this domain service supports the following configuration properties:

[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(default value)
|Description

|`isis.services.` +
`container.` +
`disableAutoFlush`
|`true`,`false` +
(`false`)
|Whether the `RepositoryService` should automatically flush pending changes prior to querying (via `allMatches()`, `firstMatch()` and so on).

|===


== Usage Notes

The xref:refguide:applib-svc:FactoryService.adoc[`FactoryService`] is often used in conjunction with the `RepositoryService`, to instantiate domain objects before persisting.

