[#TitleService]
= TitleService

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


WARNING: TODO: this content has not yet been reviewed/updated for v2.0

The `TitleService` provides methods to programmatically obtain the title and icon of a domain object.

== API

include::system:generated:page$index/applib/services/title/TitleService.adoc[leveloffset=+2]

TODO example migration

.Deprecated Docs
[WARNING]
================================

== API

The API of `TitleService` is:

[source,java]
----
include::refguide:applib-svc:example$services/title/TitleService.java[tags="refguide"]
----
<.> return the title of the object, as rendered in the UI by the Apache Isis viewers.

<.> return the icon name of the object, as rendered in the UI by the Apache Isis viewers.



================================

== Implementation

The core framework provides a default implementation of this service (`o.a.i.core.metamodel.services.title.TitleServiceDefault`).




== Usage

By way of example, here's some code based on a system for managing government benefits:

[source,java]
----
public class QualifiedAdult {

    private Customer qualifying;

    public String title() {
        return "QA for " + titleService.titleOf(qualifying);
    }

    ...
    @Inject
    TitleService titleService;
}
----

In this example, whatever the title of a `Customer`, it is reused within the title of that customer's ``QualifiedAdult`` object.




