= `TransactionService`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


WARNING: TODO: this content has not yet been reviewed/updated for v2.0
// TODO: Document `Transaction` and `TransactionId` and `TransactionState`.


The `TransactionService` (and its various supertypes) allows domain objects to influence user transactions.



== API

include::system:generated:page$index/applib/services/xactn/TransactionState.adoc[leveloffset=+2]

TODO example migration

.Deprecated Docs
[WARNING]
================================

== API

The API of `TransactionService` is:

[source,java]
----
include::refguide:applib-svc:example$services/xactn/TransactionService.java[tags="refguide"]
----

<.> obtains the identity of the current transaction.
(Note, although there is an internal `Transaction` object, this isn't exposed in the API).
+
[source,java]
----
include::refguide:applib-svc:example$services/xactn/TransactionId.java[tags="refguide"]
----
+
The `uniqueId` is in effect a session Id (eg new id per HTTP request).
The sequence is because there could be more than one transaction per request/session.

<.> obtains the state of the current transaction:
+
[source,java]
----
include::refguide:applib-svc:example$services/xactn/TransactionState.java[tags="refguide"]
----

<.> If the user interaction creates/persists an object or deletes an object (eg using the
xref:refguide:applib-svc:RepositoryService.adoc[`RepositoryService`]'s `persist()` or `delete()` methods), then the framework actually queues up the work and only performs the persistence command either at the end of the transaction or immediately prior to the next query.
Performing a flush will cause any pending calls to be performed immediately.

<.> The framework automatically start a transaction before each user interaction (action invocation or property edit), and will commit that transaction after the interaction has completed.
Under certain circumstances (eg actions used to perform data migration, say, or for large fixture scripts), it can be helpful to programmatically complete one transaction and start another one.

<.> Primarily for internal use, will execute the task within the current transaction if there is one, but if there is none then begin and then commit a new transaction for the task.

<.> Ditto, but retrieving the task to be performed from the supplier.



================================

== Implementation

The core framework provides a default implementation of this service, `o.a.i.core.runtimeservices.xactn.TransactionServiceSpring`.


