= `TranslationService`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:

WARNING: TODO: this content has not yet been reviewed/updated for v2.0

The `TranslationService` is the cornerstone of Apache Isis' i18n support.
Its role is to be able to provide translated versions of the various elements within the Apache Isis metamodel (service and object classes, properties, collections, actions, action parameters) and also to translate business rule (disable/valid) messages, and exceptions.
These translations provide for both singular and plural forms.


[NOTE]
====
For the "big picture" and further details on Apache Isis' i18n support, see xref:userguide:btb:i18n.adoc[here].
====



== SPI

The SPI defined by this service is:

[source,java]
----
include::refguide:applib-svc:example$services/i18n/TranslationService.java[tags="refguide"]
----
<.> translate the text, in the locale of the "current user".
<.> return a translation of either the singular or the plural text, dependent on the `num` parameter, in the locale of the "current user"
<.> whether this implementation is operating in read or in write mode:
+
[source,java]
----
include::refguide:applib-svc:example$services/i18n/TranslationService.java[tags="refguide-1"]
----
+
If in read mode, then the translations are expected to be present.
If in write mode, then the implementation is saving translation keys, and will always return the untranslated translation.



== Implementation

The Apache Isis framework provides a default implementation (`o.a.i.core.runtimeservices.i18n.po.TranslationServicePo`) that uses the GNU `.pot` and `.po` files for translations.



== Related Services

The default implementation (`TranslationServicePo`) relies on xref:refguide:applib-svc:LocaleProvider.adoc[`LocaleProvider`] service (to return the `Locale` of the current user), and xref:TranslationsResolver.adoc[`TranslationsResolver`] service (to read existing translations).

The framework also provides a supporting `TranslationServicePoMenu` provides menu items under the "Prototyping" secondary menu for controlling this service and downloading `.pot` files for translation.

If the menu items are not required then these can be suppressed either using security or by implementing a xref:userguide:btb:about.adoc#vetoing-visibility[vetoing subscriber].

For more details on the implementation, see xref:userguide:btb:i18n.adoc[i18n support].

If the menu items are not required then these can be suppressed either using security or by implementing a xref:userguide:btb:about.adoc#vetoing-visibility[vetoing subscriber].


