[#TranslationsResolver]
= TranslationsResolver

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


WARNING: TODO: this content has not yet been reviewed/updated for v2.0


include::system:generated:page$index/applib/services/i18n/TranslationsResolver.adoc[TranslationsResolver]

include::TranslationsResolver/hooks/implementation.adoc[]

include::TranslationsResolver/hooks/examples_and_usage.adoc[]


The `TranslationsResolver` domain service locates and return translations.

It is one of the supporting services that work together to implement Apache Isis' support for i18n, being used by Isis' default implementation of xref:refguide:applib-svc:TranslationService.adoc[`TranslationService`].

For the "big picture" and further details on Apache Isis' i18n support, see xref:userguide:btb:i18n.adoc[here].



== API

include::system:generated:page$index/applib/services/i18n/TranslationsResolver.adoc[leveloffset=+2]

TODO example migration

.Deprecated Docs
[WARNING]
================================

== SPI

The SPI defined by this service is:

[source,java]
----
include::refguide:applib-svc:example$services/i18n/TranslationsResolver.java[tags="refguide"]
----




================================

== Implementation

Isis' xref:vw:ROOT:about.adoc[Wicket viewer] provides an implementation of this service (`TranslationsResolverWicket`) which leverages Apache Wicket APIs.  This searches for translation files in the standard `WEB-INF/` directory.

There is no equivalent implementation for the xref:vro:ROOT:about.adoc[RestfulObjects viewer].




== Related Services


This service works in conjunction with xref:refguide:applib-svc:LocaleProvider.adoc[`LocaleProvider`] and xref:refguide:applib-svc:TranslationService.adoc[`TranslationService`] in order to provide i18n support.


