= `WrapperFactory`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:



The `WrapperFactory` provides the ability to enforce business rules for programmatic interactions between domain objects.
If there is a (lack of) trust boundary between the caller and callee -- eg if they reside in different modules -- then the wrapper factory is one mechanism to ensure that any business constraints defined by the callee are honoured.

For example, if the calling object attempts to modify an unmodifiable property on the target object, then an exception will be thrown.

Said another way: interactions are performed "as if" they are through the viewer.

[NOTE]
====
For a discussion of the use of the `WrapperFactory` within integration tests (the primary or at least original use case for this service) can be found xref:testing:integtestsupport:about.adoc#wrapper-factory[here].
====

This capability goes beyond enforcing the (imperative) constraints within the `hideXxx()`, `disableXxx()` and `validateXxx()` supporting methods; it also enforces (declarative) constraints such as those represented by annotations, eg `@Parameter(maxLength=...)` or `@Property(mustSatisfy=...)`.

This capability is frequently used within xref:testing:integtestsupport:about.adoc[integration tests], but can also be used in production code.

== API

The API breaks into four parts, along with a number of supporting control classes.

=== Synchronous API

The synchronous API provided by the service is:

[source,java]
----
include::refguide:applib-svc:example$services/wrapper/WrapperFactory.java[tags="refguide"]
----
<.> wraps the underlying domain object so it can invoked (through its wrapper) synchronously in the same thread.
+
The `SyncControl` modifies the way in which the wrapper interacts with the underlying domain object, discussed xref:#synccontrol[below].

<.> overload that wraps the underlying domain object with a wrapper that will validate all business rules and then execute if they pass.

<.> instantiates and wraps a mixin so that it can be invoked (through its wrapper) synchronously in the same thread.
Again `SyncControl` modifies the way in which the wrapper interacts with the underlying domain object, discussed xref:#synccontrol[below]..

<.> overload that instantiates and wraps a mixin with a wrapper that will validate all business rules and then execute the action if they pass.

The service works by returning a "wrapper" around a supplied domain object (using link:https://bytebuddy.net/[byte buddy]), and it is this wrapper that ensures that the hide/disable/validate rules implies by the Apache Isis programming model are enforced.

==== Domain Objects

For domain objects (not mixins), the wrapper can be interacted with as follows:

* a `get...()` method for properties or collections
* a `set...()` method for properties
* an `addTo...()` or `removeFrom...()` method for collections
* any action

Calling any of the above methods may result in a (subclass of) `InteractionException` if the object disallows it.
For example, if a property is annotated with xref:refguide:applib-ant:ActionLayout.adoc#hidden[`@ActionLayout#hidden`] then a `HiddenException` will be thrown.
Similarly if an action has a xref:refguide:applib-methods:prefixes.adoc#validate[`validateXxx()`] method and the supplied arguments are invalid then an `InvalidException` will be thrown.

In addition, the following methods may also be called:

* the xref:refguide:applib-methods:reserved.adoc#title[`title()`] and `toString()` methods
* any xref:refguide:applib-methods:prefixes.adoc#default[`default...()`], xref:refguide:applib-methods:prefixes.adoc#choices[`choices...()`] or xref:refguide:applib-methods:prefixes.adoc#autoComplete[`autoComplete...()`] methods

An exception will be thrown if any other methods are thrown.

If the interface is performed (action invoked or property set), then - irrespective of whether the business rules were checked or skipped - a xref:refguide:applib-ant:Action.adoc#command[command] will be created and pre- and post-execute xref:refguide:applib-ant:Action.adoc#domainEvent[domain event]s) will be fired.

==== Mixins

For mixins, the behaviour of the wrapper is similar but simpler.
Mixin wrappers only apply to actions, and so the wrapper will enforce the hidden/disable/validate rules before executing.
In addition, any xref:refguide:applib-methods:prefixes.adoc#default[`default...()`], xref:refguide:applib-methods:prefixes.adoc#choices[`choices...()`] or xref:refguide:applib-methods:prefixes.adoc#autoComplete[`autoComplete...()`] methods can be called.

[#synccontrol]
==== `SyncControl`

The `SyncControl` class controls the way that a (synchronous) wrapper works.
Its superclass `ControlAbstract` is:

[source,java]
.ControlAbstract.java
----
include::refguide:applib-svc:example$services/wrapper/control/ControlAbstract.java[tags="refguide"]
----
<.> whether to check business rules (hide/disable/validate) before executing the underlying property or action
<.> how to handle exceptions if they occur, using `ExceptionHandler`:
+
[source,java]
.SyncControl.java
----
include::refguide:applib-svc:example$services/wrapper/control/ExceptionHandler.java[tags="refguide"]
----
+
Exceptions can be rethrown or ignored.
If ignored, the handler can instead return a value; this must be compatible with the expected return value of the underlying action.


\... and the `SyncControl` class itself is:

[source,java]
----
include::refguide:applib-svc:example$services/wrapper/control/SyncControl.java[tags="refguide"]
----
<.> Default exception handler is to rethrow the exception.
<.> Don't actually execute the action (for example, just check the rules as in a "dry-run").



=== Asynchronous API

The `WrapperFactory` also allows domain objects to be interacted with in an asynchronous fashion, in other words executed in a separate thread:

[source,java]
----
include::refguide:applib-svc:example$services/wrapper/WrapperFactory.java[tags="refguide-async"]
----
<.> Wraps the underlying domain object so it can be invoked (through its wrapper) asynchronously in a separate thread.
The `AsyncControl` modifies the way in which the wrapper interacts with the underlying domain object, discussed xref:#asynccontrol[below].

<.> instantiates and wraps a mixin so that it can be invoked (through its wrapper) asynchronously in a separate thread.
Again `AsyncControl` modifies the way this is done.

Executing in a separate thread means that the target and arguments are used in a new session.
If any of these are entities, they are retrieved from the database afresh; it isn't possible to pass domain entity references from the foreground calling thread to the background threads.


[#asynccontrol]
==== `AsyncControl`

The `AsyncControl` class controls the way that an asynchronous wrapper -- as obtained by `asyncWrapXxx(...)` -- works.
The class inherits from `ControlAbstract` (see above), to allow the rules checking to be skipped and to configure the `ExceptionHandler`.
It extends with the following behaviour:

[source,java]
.AsyncControl.java
----
include::refguide:applib-svc:example$services/wrapper/control/AsyncControl.java[tags="refguide"]
----
<.> instantiate for a void action or property edit (where there is no need or intention to provide a return value through the `Future`, discussed below).
<.> instantiate for an action returning a value of `<R>` (where this value will be returned through the `Future`, discussed below).
<.> Default exception handler is just to log the exception, though this can be overridden.
<.> Default executor service is the common pool.
<.> Specify the user for the session used to execute the command asynchronously, in the background.
If not specified, then the user of the current foreground session is used.
<.> Specify the roles of the user for the session used to execute the command asynchronously, in the background.
If not specified, then the roles of the current user foreground user are used.
<.> Provides access to a `Future` representing the result of the background command.
This may or may not hold a value.

The `AsyncControl` can therefore be used to check business rules or to skip them.
If business rules are checked, note that they are performed in the context of the _foreground_ session.


=== Unwrap API

The unwrap API provided by the service is:
[source,java]
----
include::refguide:applib-svc:example$services/wrapper/WrapperFactory.java[tags="refguide-unwrap"]
----
<.> Obtains the underlying domain object or mixin, if wrapped.
+
If the object is not wrapped, returns back unchanged.

<.> whether the supplied object is a wrapper around a domain object or mixin.



=== Listener API

The listener API allows the interactions between the wrapper and the underlying domain object to be observed:

[source,java]
----
include::refguide:applib-svc:example$services/wrapper/WrapperFactory.java[tags="refguide-listeners"]
----
<.> all ``InteractionListener``s that have been registered.
<.> registers an `InteractionListener`, to be notified of interactions on all wrappers.
The listener will be notified of interactions even on wrappers created before the listener was installed.
(From an implementation perspective this is because the wrappers delegate back to the container to fire the events).
<.> remove an `InteractionListener`, to no longer be notified of interactions on wrappers.
<.> used by the framework itself

This API isn't (currently) used by the framework itself.

[TIP]
====
One possible use case would be to autogenerate documentation, for example a sequence diagram from tests.
Such a feature would probably also use xref:refguide:applib-svc:InteractionContext.adoc[`InteractionContext`], which builds up an execution call graph of interactions between (wrapped) objects.
====


== Typical Usage

The caller will typically obtain the target object (eg from some repository) and then use the injected `WrapperFactory` to wrap it before interacting with it.

For example:

[source,java]
----
public class CustomerAgent {
    @Action
    public void refundOrder(final Order order) {
        final Order wrappedOrder = wrapperFactory.wrap(order);
        try {
            wrappedOrder.refund();
        } catch(InteractionException ex) {          // <1>
            messageService.raiseError(ex.getMessage());  // <2>
            return;
        }
    }
    ...
    @Inject
    WrapperFactory wrapperFactory;
    @Inject
    MessageService messageService;
}
----
<1> if any constraints on the `Order`'s `refund()` action would be violated, then ...
<2> ... these will be trapped and raised to the user as a warning.

