= `XmlService`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The `XmlService` provides general purpose utilities for working with w3c DOM ``Document``s.
It is used by the framework's default implementation of xref:refguide:applib-svc:XmlSnapshotService.adoc[`XmlSnapshotService`].


== API

The API of `XmlService` is:

[source]
----
include::refguide:applib-svc:example$services/xmlsnapshot/XmlService.java[tags="refguide"]
----
<1> is a convenience method to convert xml string back into a W3C Document
<2> is a convenience method to extract the value of an XML element, based on its type.
<3> is a convenience method to walk XML document.
<4> is a convenience method to obtain value of child text node.



== Implementation

The framework provides a default implementation of this service, `o.a.i.core.runtimeservices.xml.XmlServiceDefault`.

