= ContentNegotiationServiceForRestfulObjectsV1_0
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Returns representations according to theRestful Objectsspec.

== API

[source,java]
.ContentNegotiationServiceForRestfulObjectsV1_0.java
----
class ContentNegotiationServiceForRestfulObjectsV1_0 {
  ContentNegotiationServiceForRestfulObjectsV1_0(CausewayConfiguration configuration, SpecificationLoader specificationLoader, ResponseFactory responseFactory)
  ResponseEntity<Object> buildResponse(IResourceContext resourceContext, ManagedObject objectAdapter)
  ResponseEntity<Object> buildResponseTo(IResourceContext resourceContext, ManagedObject objectAdapter, JsonRepresentation representationIfAnyRequired, JsonRepresentation rootRepresentation, MediaType mediaTypeOverride)     // <.>
  ResponseEntity<Object> buildResponse(IResourceContext resourceContext, ManagedProperty objectAndProperty)
  ResponseEntity<Object> buildResponse(IResourceContext resourceContext, ManagedCollection objectAndCollection)
  ResponseEntity<Object> buildResponseTo(IResourceContext resourceContext, ManagedCollection objectAndCollection, JsonRepresentation representation, JsonRepresentation rootRepresentation, MediaType mediaTypeOverride)     // <.>
  ResponseEntity<Object> buildResponse(IResourceContext resourceContext, ManagedAction objectAndAction)
  ResponseEntity<Object> buildResponse(IResourceContext resourceContext, ObjectAndActionInvocation objectAndActionInvocation)
  ResponseEntity<Object> buildResponseTo(IResourceContext resourceContext, ObjectAndActionInvocation objectAndActionInvocation, JsonRepresentation representation, JsonRepresentation rootRepresentation, MediaType mediaTypeOverride)     // <.>
}
----

<.> xref:#buildResponseTo_IResourceContext_ManagedObject_JsonRepresentation_JsonRepresentation_MediaType[buildResponseTo(IResourceContext, ManagedObject, JsonRepresentation, JsonRepresentation, MediaType)]
+
--
Not API
--
<.> xref:#buildResponseTo_IResourceContext_ManagedCollection_JsonRepresentation_JsonRepresentation_MediaType[buildResponseTo(IResourceContext, ManagedCollection, JsonRepresentation, JsonRepresentation, MediaType)]
+
--
Not API
--
<.> xref:#buildResponseTo_IResourceContext_ObjectAndActionInvocation_JsonRepresentation_JsonRepresentation_MediaType[buildResponseTo(IResourceContext, ObjectAndActionInvocation, JsonRepresentation, JsonRepresentation, MediaType)]
+
--
Not API
--

== Members

[#buildResponseTo_IResourceContext_ManagedObject_JsonRepresentation_JsonRepresentation_MediaType]
=== buildResponseTo(IResourceContext, ManagedObject, JsonRepresentation, JsonRepresentation, MediaType)

Not API

[#buildResponseTo_IResourceContext_ManagedCollection_JsonRepresentation_JsonRepresentation_MediaType]
=== buildResponseTo(IResourceContext, ManagedCollection, JsonRepresentation, JsonRepresentation, MediaType)

Not API

[#buildResponseTo_IResourceContext_ObjectAndActionInvocation_JsonRepresentation_JsonRepresentation_MediaType]
=== buildResponseTo(IResourceContext, ObjectAndActionInvocation, JsonRepresentation, JsonRepresentation, MediaType)

Not API

include::hooks/ContentNegotiationServiceForRestfulObjectsV1_0_usage-notes.adoc[]
