:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Usually a domain event is emitted by the framework to emit whenever the user interacts with a property.
Domain service subscribers can influence this interaction, either by:

* hiding the property
* disabling the property
* validating proposed values for the property
* performing arbitrary operations before the property has been modified (including modifying the proposed value of the property)
* performing arbitrary operations after the property has been modified

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/Property.html#domainevent[@Property#domainEvent] element specifies the class to be emitted; this must be a subclass of the abstract link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/events/domain/PropertyDomainEvent.html[PropertyDomainEvent] class.

If no `domainEvent` is specified on the property itself, then the domain event class can be specified at the class level using link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObject.html#propertydomainevent[@DomainObject#propertyDomainEvent].
And if not specified at the class level, then an instance of `o.a.c.applib.events.domain.PropertyDomainEvent.Default` is emitted as the fallback.

== How this demo works

This page object has two properties, `text` and `otherText`.
The first is annotated with a custom domain event, the second is not.

The annotated property can be controlled using the "change control strategy" action, influencing whether it is hidden, disabled, and so on.
This control does not apply to the non-annotated property.

In terms of code:

* this page object, with its properties:
+
[source,java]
.PropertyDomainEventPage.java
----
include::PropertyDomainEventPage.java[tags=class]
----
<.> Indicates that the object's properties are editable
<.> the event class to emit; genericised by the target type and the property type
It's common to define these as nested classes.
<.> indicates that the framework should emit domain events of this type
<.> not annotated and so will emit the default property domain event

* the subscriber that listens to the events:
+
[source,java]
.PropertyDomainEventControlSubscriber.java
----
include::PropertyDomainEventControlSubscriber.java[tags=class]
----
<.> currently selected strategy
<.> listens to the custom event
<.> dispatches to the currently selected control strategy (see below)

* the action that selects the strategy in effect:
+
[source,java]
.PropertyDomainEventPage_changeControlStrategy
----
include::PropertyDomainEventPage_changeControlStrategy.java[tags=class]
----
<.> Forces page to fully redraw

* the different strategies:

** do nothing
+
[source,java]
.PropertyDomainEventControlStrategy.java
----
include::PropertyDomainEventControlStrategy.java[tags=class]
----

** hide
+
[source,java,indent=0]
.PropertyDomainEventControlStrategy.java
----
include::PropertyDomainEventControlStrategy.java[tags=hide]
----

** disable
+
[source,java,indent=0]
.PropertyDomainEventControlStrategy.java
----
include::PropertyDomainEventControlStrategy.java[tags=disable]
----

** validate
+
[source,java,indent=0]
----
.PropertyDomainEventControlStrategy.java
include::PropertyDomainEventControlStrategy.java[tags=validate]
----

** executing
+
[source,java,indent=0]
----
.PropertyDomainEventControlStrategy.java
include::PropertyDomainEventControlStrategy.java[tags=executing]
----

** executed
+
[source,java,indent=0]
----
.PropertyDomainEventControlStrategy.java
include::PropertyDomainEventControlStrategy.java[tags=executed]
----

