[[_rgcms_classes_contributee_HasTransactionId]]
= `HasTransactionId`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/


The `HasTransactionId` interface is a mix-in for any domain objects that reference a transaction id, such as
auditing entries or commands, or for xref:../rgsvc/rgsvc.adoc#_rgsvc_application-layer-api_InteractionContext[``Interaction``]s persisted as published events.

[NOTE]
====
This identifier actually is for the request/interaction in which the object was created, so is actually now mis-named.
====

The interface is defined is:

[source,java]
----
public interface HasTransactionId {
    public UUID getTransactionId();                             // <1>
    public void setTransactionId(final UUID transactionId);
}
----
<1> unique identifier (a GUID) of this request/interaction.


Modules in the (non-ASF) link:http://platform.incode.org[Incode Platform^] that have domain entity/ies that implement this interface, and/or services that contribute this interface are:

* audit module: `AuditEntry` entity, `AuditingServiceContributions` service
* command module: `CommandJdo` entity, `CommandServiceJdoContributions` service
* publishmq module: `PublishedEvent` entity


