[[_rgcms_schema-aim]]
= Action Invocation Memento
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/



The "aim" schema defines the serialized form (or memento) of an action invocation.

[WARNING]
====
This schema has been removed in `1.13.0`, replaced with xref:../rgcms/rgcms.adoc#_rgcms_schema-ixn[ixn.xsd] (for action
invocations/property edits) and with xref:../rgcms/rgcms.adoc#_rgcms_schema-cmd[cmd.xsd] (commands, ie the __intention__ to
invoke an action/edit a property).

The remaining content on this page describes how `CommandContext` works up to v1.12.x.  However, as of `1.13.0` the `CommandContext` uses its own `cmd.xsd` schema).
====

Action invocations are captured (in memory rather than in serialized form) when the end-user invokes the action
"through" the UI, by way of the xref:../rgsvc/rgsvc.adoc#_rgsvc_application-layer-api_CommandContext[CommandContext] service. Using the
`ActionInvocationMementoDtoUtils` utility class, a service can instantiate `ActionInvocationMementoDto` which can then
be serialized to/from using the same `ActionInvocationMementoDtoUtils` class.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://isis.apache.org/schema/aim"                              <!--1-->
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://isis.apache.org/schema/aim"
           xmlns:common="http://isis.apache.org/schema/common">

    <xs:import namespace="http://isis.apache.org/schema/common"                             <!--2-->
               schemaLocation="http://isis.apache.org/schema/common/common-1.0.xsd"/>

    <xs:element name="actionInvocationMementoDto">                                          <!--3-->
        <xs:complexType>
            <xs:sequence>
                <xs:element name="metadata">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="transactionId" type="xs:string"/>             <!--4-->
                            <xs:element name="sequence" type="xs:int"/>                     <!--5-->
                            <xs:element name="timestamp" type="xs:dateTime"/>               <!--6-->
                            <xs:element name="target" type="common:oidDto"/>                <!--7-->
                            <xs:element name="targetClass" type="xs:string"/>               <!--8-->
                            <xs:element name="targetAction" type="xs:string"/>              <!--9-->
                            <xs:element name="actionIdentifier" type="xs:string"/>          <!--10-->
                            <xs:element name="user" type="xs:string"/>                      <!--11-->
                            <xs:element name="title" type="xs:string"/>                     <!--12-->
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="payload">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parameters">                                  <!--13-->
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded">
                                        <xs:element name="param" type="paramDto"/>
                                    </xs:sequence>
                                    <xs:attribute name="num" use="required" type="xs:int"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="return" type="common:valueDto"                <!--14-->
                                        minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="paramDto">                                                        <!--15-->
        <xs:sequence>
            <xs:element name="value" type="common:valueDto"/>                               <!--16-->
        </xs:sequence>
        <xs:attribute name="parameterName" use="required" type="xs:string"/>                <!--17-->
        <xs:attribute name="parameterType" use="required" type="common:valueType"/>
        <xs:attribute name="null" use="optional" type="xs:boolean"/>
    </xs:complexType>
</xs:schema>
----
<1> the aim schema has a namespace URI of "http://isis.apache.org/schema/aim".  Although URIs are not the same as URLs, you will find that the schemas are also downloadable from this location.
<2> reuses the xref:../rgcms/rgcms.adoc#_rgcms_schema-common[common] schema
<3> definition of the `actionInvocationMementoDto` complex type. This consists of metadata (the transaction identifier, the target object, the initiating user) and the payload (the action parameter/arguments, the return value if known).
<4> the unique transaction Id (a guid) allocated by the framework for each and every transaction
<5> a sequence number within the transaction.  It is possible for there to be more than one action invocation to be
<6> when the action was invoked
<7> target object, as an OID (using `oidDto` from the xref:../rgcms/rgcms.adoc#_rgcms_schema-common[common] schema)
<8> fully qualified class name of the target object, for information only
<9> name of the action, for information only
<10> Javadoc style unique identifier for the action.
<11> User that invoked the action
<12> title of the target object, for information only
<13> Collection of parameter/arguments, defined in terms of the `paramDto` complex type (discussed just below)
<14> The return value of the action, if known (and not void)
<15> The `paramDto` defines both an action parameter and its corresponding argument values
<16> The value of the parameter, in other words an argument value
<17> Metadata about the parameter itself: its name, type, optionality.

[NOTE]
====
As of `1.11.0` through `1.12.2` this schema is not used directly by the framework; in particular
`Command#setMemento(...)` sets a similar but less formal XML structure.  This may change in the future.
====
