= ManagedObject
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Represents an instance of some element of the meta-model managed by the framework, that is _Spring_ managed beans, persistence-stack provided entities, view-models or instances of value types.

== API

[source,java]
.ManagedObject.java
----
interface ManagedObject {
  Specialization getSpecialization()     // <.>
  ObjectSpecification getSpecification()     // <.>
  Object getPojo()     // <.>
  Optional<Bookmark> getBookmark()     // <.>
  Optional<Bookmark> getBookmarkRefreshed()     // <.>
  void refreshViewmodel(Supplier<Bookmark> bookmarkSupplier)     // <.>
  boolean isBookmarkMemoized()
  Supplier<ManagedObject> asSupplier()
  void assertSpecIsInSyncWithPojo()
  String titleString(UnaryOperator<TitleRenderRequest.TitleRenderRequestBuilder> onBuilder)
  String titleString()
  Optional<ObjectSpecification> getElementSpecification()     // <.>
  String getTitle()
  String getIconName()     // <.>
  ObjectIcon getIcon()
  ManagedObject unspecified()     // <.>
  ManagedObject empty(ObjectSpecification spec)     // <.>
  ManagedObject value(ObjectSpecification spec, Object pojo)     // <.>
  ManagedObject service(ObjectSpecification spec, Object pojo)     // <.>
  ManagedObject viewmodel(ObjectSpecification spec, Object pojo)     // <.>
  ManagedObject entity(ObjectSpecification spec, Object pojo)     // <.>
  ManagedObject mixin(ObjectSpecification spec, Object pojo)     // <.>
  ManagedObject other(ObjectSpecification spec, Object pojo)     // <.>
  PackedManagedObject packed(ObjectSpecification elementSpec, Can<ManagedObject> nonScalar)     // <.>
  ManagedObject wrapScalar(SpecificationLoader specLoader, Object pojo)     // <.>
  ManagedObject notBookmarked(ObjectSpecification spec, Object pojo)
  ManagedObject of(ObjectSpecification spec, Object pojo)     // <.>
  ManagedObject bookmarked(ObjectSpecification spec, Object pojo, Bookmark bookmark)     // <.>
}
----

<.> xref:#getSpecialization_[getSpecialization()]
+
--
Returns the specific _Specialization_ this xref:refguide:core:index/metamodel/object/ManagedObject.adoc[ManagedObject] implements, which governs this object's behavior.
--
<.> xref:#getSpecification_[getSpecification()]
+
--
Returns the specification that details the structure (meta-model) of this object.
--
<.> xref:#getPojo_[getPojo()]
+
--
Returns the adapted domain object, the 'plain old java' object this managed object represents with the framework.
--
<.> xref:#getBookmark_[getBookmark()]
+
--
Returns the object's bookmark as identified by the ObjectManager. Bookmarks are considered immutable, hence will be memoized once fetched.
--
<.> xref:#getBookmarkRefreshed_[getBookmarkRefreshed()]
+
--
Similar to _#getBookmark()_ , but invalidates any memoized xref:refguide:applib:index/services/bookmark/Bookmark.adoc[Bookmark] such that the xref:refguide:applib:index/services/bookmark/Bookmark.adoc[Bookmark] returned is recreated, reflecting the object's current state.
--
<.> xref:#refreshViewmodel_Supplier[refreshViewmodel(Supplier)]
+
--
If the underlying domain object is a viewmodel, refreshes any referenced entities. (Acts as a no-op otherwise.)
--
<.> xref:#getElementSpecification_[getElementSpecification()]
+
--
Used only for (standalone or parented) collections.
--
<.> xref:#getIconName_[getIconName()]
+
--
Returns the name of an icon to use if this object is to be displayed graphically.
--
<.> xref:#unspecified_[unspecified()]
+
--
Factory for Specialization#UNSPECIFIED.
--
<.> xref:#empty_ObjectSpecification[empty(ObjectSpecification)]
+
--
EMPTY
--
<.> xref:#value_ObjectSpecification_Object[value(ObjectSpecification, Object)]
+
--
VALUE
--
<.> xref:#service_ObjectSpecification_Object[service(ObjectSpecification, Object)]
+
--
SERVICE
--
<.> xref:#viewmodel_ObjectSpecification_Object[viewmodel(ObjectSpecification, Object)]
+
--
VIEWMODEL
--
<.> xref:#entity_ObjectSpecification_Object[entity(ObjectSpecification, Object)]
+
--
ENTITY
--
<.> xref:#mixin_ObjectSpecification_Object[mixin(ObjectSpecification, Object)]
+
--
MIXIN
--
<.> xref:#other_ObjectSpecification_Object[other(ObjectSpecification, Object)]
+
--
OTHER
--
<.> xref:#packed_ObjectSpecification_Can[packed(ObjectSpecification, Can)]
+
--
PACKED
--
<.> xref:#wrapScalar_SpecificationLoader_Object[wrapScalar(SpecificationLoader, Object)]
+
--
For cases, when the pojo's specification is not available and needs to be looked up.
--
<.> xref:#of_ObjectSpecification_Object[of(ObjectSpecification, Object)]
+
--
Optimized for cases, when the pojo's specification is already available. If _pojo_ is an entity, automatically memoizes its bookmark.
--
<.> xref:#bookmarked_ObjectSpecification_Object_Bookmark[bookmarked(ObjectSpecification, Object, Bookmark)]
+
--
Optimized for cases, when the pojo's specification and bookmark are already available.
--

== Members

[#getSpecialization_]
=== getSpecialization()

Returns the specific _Specialization_ this xref:refguide:core:index/metamodel/object/ManagedObject.adoc[ManagedObject] implements, which governs this object's behavior.

[#getSpecification_]
=== getSpecification()

Returns the specification that details the structure (meta-model) of this object.

[#getPojo_]
=== getPojo()

Returns the adapted domain object, the 'plain old java' object this managed object represents with the framework.

[#getBookmark_]
=== getBookmark()

Returns the object's bookmark as identified by the ObjectManager. Bookmarks are considered immutable, hence will be memoized once fetched.

[#getBookmarkRefreshed_]
=== getBookmarkRefreshed()

Similar to _#getBookmark()_ , but invalidates any memoized xref:refguide:applib:index/services/bookmark/Bookmark.adoc[Bookmark] such that the xref:refguide:applib:index/services/bookmark/Bookmark.adoc[Bookmark] returned is recreated, reflecting the object's current state.

[#refreshViewmodel_Supplier]
=== refreshViewmodel(Supplier)

If the underlying domain object is a viewmodel, refreshes any referenced entities. (Acts as a no-op otherwise.)

[#getElementSpecification_]
=== getElementSpecification()

Used only for (standalone or parented) collections.

[#getIconName_]
=== getIconName()

Returns the name of an icon to use if this object is to be displayed graphically.

May return `null` if no icon is specified.

[#unspecified_]
=== unspecified()

Factory for Specialization#UNSPECIFIED.

[#empty_ObjectSpecification]
=== empty(ObjectSpecification)

EMPTY

[#value_ObjectSpecification_Object]
=== value(ObjectSpecification, Object)

VALUE

[#service_ObjectSpecification_Object]
=== service(ObjectSpecification, Object)

SERVICE

[#viewmodel_ObjectSpecification_Object]
=== viewmodel(ObjectSpecification, Object)

VIEWMODEL

[#entity_ObjectSpecification_Object]
=== entity(ObjectSpecification, Object)

ENTITY

[#mixin_ObjectSpecification_Object]
=== mixin(ObjectSpecification, Object)

MIXIN

[#other_ObjectSpecification_Object]
=== other(ObjectSpecification, Object)

OTHER

[#packed_ObjectSpecification_Can]
=== packed(ObjectSpecification, Can)

PACKED

[#wrapScalar_SpecificationLoader_Object]
=== wrapScalar(SpecificationLoader, Object)

For cases, when the pojo's specification is not available and needs to be looked up.

Fails if the pojo is non-scalar.

[#of_ObjectSpecification_Object]
=== of(ObjectSpecification, Object)

Optimized for cases, when the pojo's specification is already available. If _pojo_ is an entity, automatically memoizes its bookmark.

[#bookmarked_ObjectSpecification_Object_Bookmark]
=== bookmarked(ObjectSpecification, Object, Bookmark)

Optimized for cases, when the pojo's specification and bookmark are already available.
