:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The "specification" design pattern is used to encapsulate a rule or constraint that an object must satisfy.
The framework allows this to be applied to candidate values for a property, and to action parameters:

* for properties, the constraint can be specified using the link:https://causeway.apache.org/refguwide/2.0.0-SNAPSHOT/applib/index/annotation/Property.html#mustsatisfy[@Property#mustSatisfy] attribute

* for action parameters, the constraint can be specified using the link:https://causeway.apache.org/refguwide/2.0.0-SNAPSHOT/applib/index/annotation/Parameter.html#mustsatisfy[@Parameter#mustSatisfy] attribute

The constraint itself is provided as a concrete class that implements the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/spec/Specification.html[Specification] interface.
This is usually done by subclassing link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/spec/AbstractSpecification.html[AbstractSpecification].
(There are also i18n versions of these classes, link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/spec/Specification2.html[Specification2] and link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/spec/AbstractSpecification2.html[AbstractSpecification2]).

TIP: See the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib-classes/spec.html[reference guide] for more background on the specification pattern.

== How this demo works

This page has a single `customerAge` property, which is of type `Integer`.
This can be edited directly, or can also be updated using an action.

We also have a rule that a customer must be aged between 18 and 65.
This is expressed using a `Specification`
This rule is enforced on both the property and on the action parameter.

In terms of code:

* the specification is defined as:
+
[source,java,indent=0]
----
include::OfWorkingAgeSpecification.java[tags=class]
----

* on the property, we use `@Property#mustSatisfy`:
+
[source,java,indent=0]
.PropertyMustSatisfyPage.java
----
include::PropertyMustSatisfyPage.java[tags=annotation]
----
<.> explicitly specifies that the property holds an integer in the range 18 to 65

* and on the action parameter, similarly we use `@Parameter#mustSatisfy`:
+
[source,java,indent=0]
.PropertyMustSatisfyPage_updateCustomerAge.java
----
include::PropertyMustSatisfyPage_updateCustomerAge.java[tags=annotation]
----
<.> explicitly specifies that the parameter holds an integer in the range 18 to 65

