= ApplicationUser _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.ApplicationUser.java
----
interface ApplicationUser {
  public static final int MAX_LENGTH_USERNAME;
  public static final int MAX_LENGTH_FAMILY_NAME;
  public static final int MAX_LENGTH_GIVEN_NAME;
  public static final int MAX_LENGTH_KNOWN_AS;
  public static final int MAX_LENGTH_EMAIL_ADDRESS;
  public static final int MAX_LENGTH_PHONE_NUMBER;
  String title()     // <.>
  String iconName()
  String getName()
  String getEncryptedPassword()
  AccountType getAccountType()
  void setAccountType(AccountType accountType)
  ApplicationPermissionValueSet getPermissionSet()
  SortedSet<? extends ApplicationRole> getRoles()
  ApplicationUserStatus getStatus()
  void setStatus(ApplicationUserStatus disabled)
  void setAtPath(String atPath)
  String getEmailAddress()
  void setEmailAddress(String emailAddress)
  String getFaxNumber()
  void setFaxNumber(String faxNumber)
  String getFamilyName()
  void setFamilyName(String familyName)
  String getGivenName()
  void setGivenName(String givenName)
  String getKnownAs()
  void setKnownAs(String knownAs)
  String getPhoneNumber()
  void setPhoneNumber(String phoneNumber)
  void setUsername(String username)
  void setEncryptedPassword(String encryptedPassword)
  boolean isForSelfOrRunAsAdministrator()
  boolean isHasPassword()
  boolean isLocalAccount()
}
----

<.> xref:#title__[title()]
+
--
having a title() method (rather than using @Title annotation) is necessary as a workaround to be able to use wrapperFactory#unwrap(...) method, which is otherwise broken in Isis 1.6.0
--

== Members

[#title__]
=== title()

having a title() method (rather than using @Title annotation) is necessary as a workaround to be able to use wrapperFactory#unwrap(...) method, which is otherwise broken in Isis 1.6.0
