= `SwaggerService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `SwaggerService` generates link:http://swagger.io/[Swagger] spec files to describe the public and/or private RESTful APIs exposed by the xref:ug:vro:ugvro.adoc#[RestfulObjects viewer].

These spec files can then be used with the link:http://swagger.io/swagger-ui/[Swagger UI] page to explore the REST API, or used to generate client-side stubs using the link:http://swagger.io/swagger-codegen/[Swagger codegen] tool, eg for use in a custom REST client app.

[NOTE]
====
Not all of the REST API exposed by the xref:ug:vro:ugvro.adoc#[Restful Objects viewer] is included in the Swagger schema definition files; the emphasis is those REST resources that are used to develop custom apps: domain objects, domain object collections and action invocations.  When combined with Apache Isis' own xref:ug:vro:ugvro.adoc#_ugvro_simplified-representations[simplified representations], these are pretty much all that is needed  for this use case.
====



== API

The API defined by `SwaggerService` is:

[source,java]
----
public interface SwaggerService {
    enum Visibility {
        PUBLIC,                     // <1>
        PRIVATE,                    // <2>
        PRIVATE_WITH_PROTOTYPING;   // <3>
    }
    enum Format {                   // <4>
        JSON,
        YAML
    }
    String generateSwaggerSpec(final Visibility visibility, final Format format);
}
----
<1> Generate a Swagger spec for use by third-party clients, ie public use.  This specification is restricted only to
xref:ug:fun:ugfun.adoc#_ugfun_building-blocks_types-of-domain-objects_view-models[view model]s and to domain services with a xref:rg:ant:DomainService/nature.adoc[nature] of `VIEW_REST_ONLY`.
<2> Generate a Swagger spec for use only by internally-managed clients, ie private internal use.  This specification includes domain entities and all menu domain services (as well as any view models).
<3> Generate a Swagger spec that is the same as private case (above), but also including any xref:rg:ant:Action/restrictTo.adoc[prototype] actions.
<4> Swagger specs can be written either in JSON or YAML format.



== Implementation

Apache Isis provides a default implementation of the service, `o.a.i.core.metamodel.services.swagger.SwaggerServiceDefault`.



== Usage within the framework

This service is provided as a convenience for applications, it is not (currently) used by the framework itself.




== Related Services

A `SwaggerServiceMenu` domain service provides a prototype action that enables the swagger spec to be downloaded from the Wicket viewer's UI.

Apache Isis' xref:rg:mvn:rgmvn.adoc#[Maven plugin] also provides a xref:rg:mvn:swagger.adoc[swagger goal] which allows the spec file(s) to be generated at build time.  this then allows client-side stubs can then be generated in turn as part of a build pipeline.


