:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.SecmanConfiguration.java
----
class SecmanConfiguration {
  @Getter
@Builder.Default
@NonNull
final String regularUserRoleName;
  @Getter
@Builder.Default
@NonNull
final String fixtureRoleName;
  @Getter
@Builder.Default
@NonNull
final String adminRoleName;
  @Getter
@Builder.Default
@NonNull
final String adminUserName;
  @Getter
@Builder.Default
@NonNull
final String adminPassword;
  @Getter
@Builder.Default
@NonNull
final String[] adminStickyNamespacePermissions;     // <.>
  @Getter
@Singular
final Set<String> adminAdditionalNamespacePermissions;
  @Getter
@Builder.Default
final boolean autoEnableIfDelegatedAndAuthenticated;     // <.>
  Stream<String> streamAdminNamespacePermissions()
  boolean isStickyAdminNamespace(String featureFqn)
}
----

<.> xref:#adminStickyNamespacePermissions[adminStickyNamespacePermissions]
+
--
cannot be removed via user interface
--
<.> xref:#autoEnableIfDelegatedAndAuthenticated[autoEnableIfDelegatedAndAuthenticated]
+
--
Delegated users, on first successful logon, are auto-created but disabled (by default).
--

== Members

[#adminStickyNamespacePermissions]
=== adminStickyNamespacePermissions

cannot be removed via user interface

[#autoEnableIfDelegatedAndAuthenticated]
=== autoEnableIfDelegatedAndAuthenticated

Delegated users, on first successful logon, are auto-created but disabled (by default).

This option allows to override this behavior, such that authenticated users are also auto-enabled.

default: false
