{
  gqltestdomain_GQLTestDomainMenu {
    findAllE2 {
       _gql_meta {
          id
          logicalTypeName
          version
          structure {
            properties
            collections
            safeActions
            idempotentActions
            nonIdempotentActions
            layoutXml
        }
      }
    }
  }
}
