{
  "data" : {
    "_gql_Query_lookup" : {
      "gqltestdomain_E2" : {
        "_gql_generic" : {
          "__typename" : "gqltestdomain_E2__DomainObject_generic",
          "id" : "10",
          "logicalTypeName" : "gqltestdomain.E2",
          "version" : "not yet implemented",
          "structure" : {
            "__typename" : "_gql__DomainObject_generic_structure",
            "properties" : [ "e1", "name", "logicalTypeName", "objectIdentifier" ],
            "collections" : [ "otherE2List", "stringList", "zintList" ],
            "actions" : [ "otherEntities", "changeE1", "changeName", "remove", "removeWithReason" ],
            "layoutXml" : "<xml>todo: implement .... </xml>"
          },
          "iconName" : "not yet implemented",
          "title" : "Untitled E2",
          "properties" : {
            "__typename" : "gqltestdomain_E2__DomainObject_generic_properties",
            "e1" : {
              "__typename" : "_gql__DomainObject_generic_property",
              "hide" : false,
              "disable" : "Disabled"
            },
            "logicalTypeName" : {
              "__typename" : "_gql__DomainObject_generic_property",
              "hide" : false,
              "disable" : "Contributed property"
            },
            "name" : {
              "__typename" : "_gql__DomainObject_generic_property",
              "hide" : false,
              "disable" : "Disabled"
            },
            "objectIdentifier" : {
              "__typename" : "_gql__DomainObject_generic_property",
              "hide" : false,
              "disable" : "Contributed property"
            }
          },
          "collections" : {
            "__typename" : "gqltestdomain_E2__DomainObject_generic_collections",
            "otherE2List" : {
              "__typename" : "_gql__DomainObject_generic_collection",
              "hide" : true,
              "disable" : null
            },
            "zintList" : {
              "__typename" : "_gql__DomainObject_generic_collection",
              "hide" : false,
              "disable" : null
            },
            "stringList" : {
              "__typename" : "_gql__DomainObject_generic_collection",
              "hide" : false,
              "disable" : null
            }
          },
          "actions" : {
            "__typename" : "gqltestdomain_E2__DomainObject_generic_actions",
            "otherEntities" : {
              "__typename" : "gqltestdomain_E2__otherEntities__ObjectAction_generic",
              "hide" : false,
              "disable" : null,
              "validate" : null,
              "semantics" : "SAFE",
              "params" : {
                "__typename" : "gqltestdomain_E2__otherEntities__ObjectAction_generic_params",
                "name" : {
                  "__typename" : "gqltestdomain_E2__otherEntities__name__ObjectActionParam_generic",
                  "optionality" : true,
                  "validate" : null,
                  "autocomplete" : null,
                  "default" : "e",
                  "choices" : null
                },
                "numberOfResults" : {
                  "__typename" : "gqltestdomain_E2__otherEntities__numberOfResults__ObjectActionParam_generic",
                  "optionality" : true,
                  "validate" : null,
                  "autocomplete" : null,
                  "default" : 10,
                  "choices" : null
                }
              }
            },
            "remove" : {
              "__typename" : "gqltestdomain_E2__remove__ObjectAction_generic",
              "hide" : false,
              "disable" : null,
              "validate" : null,
              "semantics" : "NON_IDEMPOTENT_ARE_YOU_SURE"
            },
            "removeWithReason" : {
              "__typename" : "gqltestdomain_E2__removeWithReason__ObjectAction_generic",
              "hide" : false,
              "disable" : null,
              "validate" : null,
              "semantics" : "NON_IDEMPOTENT_ARE_YOU_SURE",
              "params" : {
                "reason" : {
                  "__typename" : "gqltestdomain_E2__removeWithReason__reason__ObjectActionParam_generic",
                  "optionality" : false,
                  "validate" : null,
                  "autocomplete" : null,
                  "default" : null,
                  "choices" : null
                }
              }
            },
            "changeE1" : {
              "__typename" : "gqltestdomain_E2__changeE1__ObjectAction_generic",
              "hide" : false,
              "disable" : null,
              "validate" : "Already there",
              "semantics" : "IDEMPOTENT",
              "params" : {
                "e1" : {
                  "__typename" : "gqltestdomain_E2__changeE1__e1__ObjectActionParam_generic",
                  "optionality" : false,
                  "validate" : null,
                  "autocomplete" : null,
                  "default" : null,
                  "choices" : null
                }
              }
            },
            "changeName" : {
              "__typename" : "gqltestdomain_E2__changeName__ObjectAction_generic",
              "hide" : false,
              "disable" : null,
              "validate" : "The name of an object called e2 cannot be changed",
              "semantics" : "IDEMPOTENT",
              "params" : {
                "newName" : {
                  "__typename" : "gqltestdomain_E2__changeName__newName__ObjectActionParam_generic",
                  "optionality" : false,
                  "validate" : null,
                  "autocomplete" : null,
                  "default" : "e2",
                  "choices" : null
                }
              }
            }
          }
        },
        "e1" : null,
        "logicalTypeName" : "gqltestdomain.E2",
        "name" : "e2",
        "objectIdentifier" : "10"
      }
    }
  }
}