{
  "data" : {
    "_gql_Query_lookup" : {
      "gqltestdomain_E2" : {
        "_gql_generic" : {
          "__typename" : "gqltestdomain_E2__DomainObject_generic",
          "id" : "10",
          "logicalTypeName" : "gqltestdomain.E2",
          "version" : "not yet implemented",
          "structure" : {
            "__typename" : "_gql__DomainObject_generic_structure",
            "properties" : [ "e1", "name", "logicalTypeName", "objectIdentifier" ],
            "collections" : [ "otherE2List", "stringList", "zintList" ],
            "actions" : [ "otherEntities", "changeE1", "changeName", "remove", "removeWithReason" ],
            "layoutXml" : "<xml>todo: implement .... </xml>"
          },
          "iconName" : "not yet implemented",
          "title" : "Untitled E2",
          "properties" : {
            "__typename" : "gqltestdomain_E2__DomainObject_generic_properties",
            "e1" : {
              "__typename" : "_gql__DomainObject_generic_property",
              "hide" : false,
              "disable" : "Disabled"
            },
            "logicalTypeName" : {
              "__typename" : "_gql__DomainObject_generic_property",
              "hide" : false,
              "disable" : "Contributed property"
            },
            "name" : {
              "__typename" : "_gql__DomainObject_generic_property",
              "hide" : false,
              "disable" : "Disabled"
            },
            "objectIdentifier" : {
              "__typename" : "_gql__DomainObject_generic_property",
              "hide" : false,
              "disable" : "Contributed property"
            }
          },
          "collections" : {
            "__typename" : "gqltestdomain_E2__DomainObject_generic_collections",
            "otherE2List" : {
              "__typename" : "_gql__DomainObject_generic_collection",
              "hide" : true,
              "disable" : null
            },
            "zintList" : {
              "__typename" : "_gql__DomainObject_generic_collection",
              "hide" : false,
              "disable" : null
            },
            "stringList" : {
              "__typename" : "_gql__DomainObject_generic_collection",
              "hide" : false,
              "disable" : null
            }
          },
          "actions" : {
            "__typename" : "gqltestdomain_E2__DomainObject_generic_actions",
            "otherEntities" : {
              "__typename" : "gqltestdomain_E2__DomainObject_generic_actions_otherEntities",
              "hide" : false,
              "disable" : null,
              "validate" : "not yet implemented",
              "semantics" : "SAFE",
              "params" : null
            },
            "remove" : {
              "__typename" : "gqltestdomain_E2__DomainObject_generic_actions_remove",
              "hide" : false,
              "disable" : null,
              "validate" : "not yet implemented",
              "semantics" : "NON_IDEMPOTENT_ARE_YOU_SURE"
            },
            "removeWithReason" : {
              "__typename" : "gqltestdomain_E2__DomainObject_generic_actions_removeWithReason",
              "hide" : false,
              "disable" : null,
              "validate" : "not yet implemented",
              "semantics" : "NON_IDEMPOTENT_ARE_YOU_SURE",
              "params" : null
            },
            "changeE1" : {
              "__typename" : "gqltestdomain_E2__DomainObject_generic_actions_changeE1",
              "hide" : false,
              "disable" : null,
              "validate" : "not yet implemented",
              "semantics" : "IDEMPOTENT",
              "params" : null
            },
            "changeName" : {
              "__typename" : "gqltestdomain_E2__DomainObject_generic_actions_changeName",
              "hide" : false,
              "disable" : null,
              "validate" : "not yet implemented",
              "semantics" : "IDEMPOTENT",
              "params" : null
            }
          }
        },
        "e1" : null,
        "logicalTypeName" : "gqltestdomain.E2",
        "name" : "e2",
        "objectIdentifier" : "10",
        "otherE2List" : [ ],
        "otherEntities" : null,
        "stringList" : [ ],
        "zintList" : [ ]
      }
    }
  }
}