[[TableColumnOrderService]]
= `TableColumnOrderService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:



The `TableColumnOrderService` provides the ability to reorder (or suppress) columns in both parented- and standalone tables.


== SPI

The SPI defined by this service is:

[source,java]
----
public interface TableColumnOrderService {
    List<String> orderParented(                  // <1>
            Object parent,
            String collectionId,
            Class<?> collectionType,
            List<String> propertyIds);
    List<String> orderStandalone(                // <2>
            Class<?> collectionType,
            List<String> propertyIds);
}
----
<1> for the parent collection owned by the specified parent and collection Id, return the set of property ids in the same or other order.
<2> for the standalone collection of the specified type, return the set of property ids in the same or other order, else return `null` if provides no reordering.

There can be multiple implementations of `TableColumnOrderService` registered, ordered as per xref:applib:ant:DomainServiceLayout.adoc#menuOrder[`@DomainServiceLayout#menuOrder()`].
The ordering provided by the first such service that returns a non-`null` value will be used.
If all provided implementations return `null`, then the framework will fallback to a default implementation.



== Implementation

The framework provides a fallback implementation of this service, namely `TableColumnOrderService.Default`.

There can be multiple implementations of `TableColumnOrderService registered.
These are checked in turn (chain of responsibility pattern), ordered according to xref:applib:ant:DomainServiceLayout.adoc#menuOrder[`@DomainServiceLayout#menuOrder()`] (as explained in the xref:rg:svc:intro/overriding-the-services.adoc[introduction] to this guide).
The order from the first service that returns a non null value will be used.



