[[TranslationService]]
= `TranslationService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:



The `TranslationService` is the cornerstone of Apache Isis' i18n support.
Its role is to be able to provide translated versions of the various elements within the Apache Isis metamodel (service and object classes, properties, collections, actions, action parameters) and also to translate business rule (disable/valid) messages, and exceptions.
These translations provide for both singular and plural forms.


[NOTE]
====
For the "big picture" and further details on Apache Isis' i18n support, see xref:ug:btb:i18n.adoc[here].
====



== SPI

The SPI defined by this service is:

[source,java]
----
public interface TranslationService {
    @Programmatic
    String translate(String context, String text);      // <1>
    @Programmatic
    String translate(String context,                    // <2>
                     String singularText,
                     String pluralText, int num);

    enum Mode { READ, WRITE;}
    @Programmatic
    Mode getMode();                                     // <3>
}

----
<1> translate the text, in the locale of the "current user".
<2> return a translation of either the singular or the plural text, dependent on the `num` parameter, in the locale of the "current user"
<3> whether this implementation is operating in read or in write mode.

If in read mode, then the translations are expected to be present.

If in write mode, then the implementation is saving translation keys, and will always return the untranslated translation.




== Implementation

The Apache Isis framework provides a default implementation (`TranslationServicePo`) that uses the GNU `.pot` and `.po` files for translations.
It relies on the `LocaleProvider` service (to return the `Locale` of the current user) and also the `TranslationsResolver` service (to read existing translations).

The framework also provides a supporting `TranslationServicePoMenu` provides menu items under the "Prototyping" secondary menu for controlling this service and downloading `.pot` files for translation.

If the menu items are not required then these can be suppressed either using security or by implementing a xref:ug:btb:about.adoc#vetoing-visibility[vetoing subscriber].

For more details on the implementation, see xref:ug:btb:i18n.adoc[i18n support].


If the menu items are not required then these can be suppressed either using security or by implementing a xref:ug:btb:about.adoc#vetoing-visibility[vetoing subscriber].

=== Configuration Properties

The default implementation of this domain service recognises the following configuration properties:

[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(default value)
|Description

|`isis.services.` +
`translation.` +
`p`
| `read`,`write`,`disabled`
|Whether to force the `TranslationService` into either read or write mode.
It can also be disabled.
This can be useful for integration tests.

See xref:ug:btb:i18n.adoc[i18n support] to learn more about the translation service.

|===





== Related Menus

The `TranslationServicePoMenu` menu exposes the `TranslationServicePo` service's `toPot()` method so that all
translations can be downloaded as a single file.



== Related Services

This service works in conjunction with xref:rg:svc:presentation-layer-spi/LocaleProvider.adoc[`LocaleProvider`] and xref:rg:svc:presentation-layer-spi/TranslationsResolver.adoc[`TranslationsResolver`] in order to provide i18n support.

