{
  simple {
    university_dept_Departments {
      findAllDepartments {
        name
        staffMembers {
          name
          department {
            name
          }
        }
      }
    }
  }
}
