= Injecting services
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


Apache Isis autowires (automatically injects) domain services into each entity, as well as into the domain services themselves, using either method injection or field injection.
The framework defines many additional services (such as xref:rg:svc:rgsvc.adoc#_rgsvc_persistence-layer-api_RepositoryService[`RepositoryService`]); these are injected in exactly the same manner.

Sometimes there may be multiple services that implement a single type.
This is common for example for SPI service, whereby one module defines an SPI service, and other module(s) in the application implement that service.
To support this, the framework also allows lists of services to be injected.

When there are multiple service implementations of a given type, the framework will inject the service with highest priority, as defined through xref:rg:ant:rgant.adoc#_rgant-DomainService_menuOrder[`@DomainService#menuOrder()`] (even for domain services that are not menus), lowest first.
If a list of services is injected, then that list will be ordered according to `menuOrder`, again lowest first.



[NOTE]
====
Isis currently does _not_ support qualified injection of services; the domain service of each type must be distinct from any other.

If you find a requirement to inject two instances of type `SomeService`, say, then the work-around is to create trivial subclasses `SomeServiceA` and `SomeServiceB` and inject these instead.
====


== Field Injection

Field injection is recommended, using the `@javax.inject.Inject` annotation.
For example:

[source,java]
----
public class Customer {
    ...
    @javax.inject.Inject
    OrderRepository orderRepository;
}
----

To inject a list of services, use:

[source,java]
----
public class DocumentService {
    ...
    @javax.inject.Inject
    List<PaperclipFactory> paperclipFactories;
}
----

We recommend using default rather than `private` visibility so that the field can be mocked out within unit tests (placed in the same package as the code under test).




== Method Injection

The framework also supports two forms of method injection.
All that is required to inject a service into a entity/service is to provide an appropriate method or field.
The name of the method does not matter, only that it is prefixed either `set` or `inject`, is public, and has a single parameter of the correct type.

For example:

[source,java]
----
public class Customer {
    private OrderRepository orderRepository;
    public void setOrderRepository(OrderRepository orderRepository) {
        this.orderRepository = orderRepository;
    }
    ...
}
----

or alternatively, using 'inject' as the prefix:

[source,java]
----
public class Customer {
    private OrderRepository orderRepository;
    public void injectOrderRepository(OrderRepository orderRepository) {
        this.orderRepository = orderRepository;
    }
    ...
}
----

Lists of services can be injected in a similar manner.

Note that the method name can be anything; it doesn't need to be related to the type being injected.


== Constructor injection

Simply to note that constructor injection is _not_ supported by Apache Isis (and is unlikely to be, because the JDO specification for entities requires a no-arg constructor).






