:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Domain objects are identified to the user through a title and an icon.
The most common way to define the icon is with a `.png` image file with the same name as the class (eg `Customer.png` for a `Customer` class).

An alternative though is to use a fontawesome icon, specified using link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/DomainObjectLayout.html#cssclassfa[@DomainObjectLayout#cssClassFa].

== How this demo works

The collection on the left shows a list of entities where the `cssClass` attribute has been set to a value of "fa-user".

In terms of code:

* entity class definition:
+
[source,css]
.DomainObjectLayoutCssClassFaEntity.java
----
include::DomainObjectLayoutCssClassFaEntity.java[tags=class]
----
<.> specifies the "fa-user" fontawesome CSS class

