[[HsqlDbManagerMenu]]
= `HsqlDbManagerMenu`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:



The `HsqlDbManagerMenu` provides a single menu item to open up the HSQLDB manager.
This is only enabled for prototyping, and if HSQLDB is detected in the underlying JDBC URL.
The menu appears under the "Prototyping" menu.


== API & Implementation

The API of the service is:

[source,java]
----
public class HsqlDbManagerMenu {
    public void hsqlDbManager() { /* ... */ }
}
----

Note that this launches the manager on the same host that the webapp runs, and so is only appropriate to use when running on `localhost`.


== Disabling/hiding the menu

The menu can be hidden or disabled by subscribing to its domain event, eg:


[source,java]
----
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;

@Service
public class HideHsqlDbManagerMenu {

    @EventListener(HsqlDbManagerMenu.ActionDomainEvent.class)
    public void on(HsqlDbManagerMenu.ActionDomainEvent ev) {
        ev.hide();
    }
}
----
