= SimpleTicket
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Response from the xref:refguide:applib:index/services/error/ErrorReportingService.adoc[ErrorReportingService] , containing information to show to the end-user.

Implementation notes:

* a class has been used here so that additional fields might be added in the future.
* the class is _Serializable_

so that it can be stored by the Wicket viewer as a Wicket model.

== API

[source,java]
.SimpleTicket.java
----
class SimpleTicket {
  SimpleTicket(String reference, String userMessage, String details)
  SimpleTicket(String reference, String userMessage, String details, StackTracePolicy stackTracePolicy)
  SimpleTicket(String reference, String userMessage, String details, String kittenUrl)
  SimpleTicket(String reference, String userMessage, String details, StackTracePolicy stackTracePolicy, String kittenUrl)
  String getReference()
  String getUserMessage()
  String getDetails()
  StackTracePolicy getStackTracePolicy()
  String getKittenUrl()     // <.>
  String getMarkup()
}
----

<.> xref:#getKittenUrl__[getKittenUrl()]
+
--
If specified, is the external URL of an image to display to the end user.
--

== Members

[#getKittenUrl__]
=== getKittenUrl()

If specified, is the external URL of an image to display to the end user.

Not necessarily of a kitten, but something by way of an apology.
