[[HasUniqueId]]
= `HasUniqueId`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The `HasUniqueId` interface is a mix-in for any domain objects that reference a transaction id, such as
auditing entries or commands, or for xref:refguide:applib-svc:InteractionContext.adoc[``Interaction`]s persisted as published events.

[NOTE]
====
This identifier actually is for the request/interaction in which the object was created, so is actually now mis-named.
====

The interface is defined is:

[source,java]
----
public interface HasUniqueId {
    public UUID getTransactionId();                             // <1>
    public void setTransactionId(final UUID transactionId);
}
----
<1> unique identifier (a GUID) of this request/interaction.


Modules in the (non-ASF) link:https://platform.incode.org[Incode Platform^] that have domain entity/ies that implement this interface, and/or services that contribute this interface are:

* audit module: `AuditEntry` entity, `AuditingServiceContributions` service
* command module: `CommandJdo` entity, `CommandServiceJdoContributions` service
* publishmq module: `PublishedEvent` entity


== `RepresentsInteractionMemberExecution`

The `RepresentsInteractionMemberExecution` interface is a sub-interface of `HasUniqueId` that also includes a sequence property:

[source,java]
----
public interface RepresentsInteractionMemberExecution extends HasUniqueId {
    int getSequence();
}
----

Here the (inherited) `getTransactionId()` is intended to be interpreted as an interaction (cf xref:refguide:schema:ixn[`InteractionDto`]) that has at least one member execution (cf xref:refguide:schema:about.adoc#ixn/memberExecutionDto.adoc[`memberExecutionDto`]).

If the interaction (almost certainly an action) calls other actions by way of xref:refguide:applib-svc:WrapperFactory.adoc[`WrapperFactory`]), then there may be several member executions, each with a unique sequence number, within the same transaction Id.

The purpose of this interface is to allow mixins to be defined, though the framework itself defines none.

Currently the only implementation of this interface is that for `PublishedObjects` applib interface as defined by the xref:refguide:applib-svc:PublisherService.adoc[`PublisherService`].

