= Components

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


This page provides user/config guides for each of the main components of the frameworks (viewer, object store and security).

== Overview

xref:core:_overview:about.adoc[System Overview]

== Viewers

The framework provides two viewers that will automatically render the domain objects in your application into the presentation layer:

* xref:vw:ROOT:about.adoc[Web UI (Wicket)]
+
Provides a human-usable UI, implemented using https://wicket.apache.org[Apache Wicket], and styled using Bootstrap.

* xref:vro:ROOT:about.adoc[REST API (Restful Objects)]
+
Presents your domain objects in JSON representations, compliant either with link:http://restfulobjects.org[Restful Objects] specification or one of a number of other representations.



== Persistence

The framework allows xref:userguide:fun:overview.adoc#domain-entities[domain entities] to be persisted using either:

* the xref:pjpa:ROOT:about.adoc[JPA/Eclipselink] object store
+
for use with JPA and link:https://spring.io/projects/spring-data-jpa[Spring Data JPA].

* the xref:pjdo:ROOT:about.adoc[JDO/DataNucleus object store]
+
for use with the JDO API.

Alternatively, you can "roll your own" (by implementing the xref:refguide:applib:index/ViewModel.adoc[ViewModel] interface) and persist with any data persistence technology that is supported by Spring Boot.


== Security

The xref:security:ROOT:about.adoc[Security Guide] describes how to configure each of the various security implementations that integrate with Apache Isis.


== Extensions

The xref:extensions:ROOT:about.adoc[Extensions Catalog] describes a number of extensions for the various components of the framework itself.

For example, the "Excel Download" extension allows collections to be downloaded as an Excel `.xlsx` spreadsheet in the Wicket viewer.

As well as the current extensions,  the xref:incubator:ROOT:about.adoc[Incubator] has additional components and extensions that may end up graduating.


