= Libraries

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Included with the framework are several catalogues/libraries:

* xref:subdomains:ROOT:about.adoc[Subdomain Libraries]
+
Libraries and utilities to be called by the domain logic of the Apache Isis application itself.

* xref:valuetypes:ROOT:about.adoc[Value Type Catalog]
+
Implementations of various value types, eg Markdown.
Each will have an applib submodule (for use within the domain logic) as well as various extension modules to be made available to the framework itself (to teach it how to persist or render the value type).

* xref:mappings:ROOT:about.adoc[BC Mapping Libraries]
+
Libraries and utilities for bounded context (BC) mappings.
In other words, tools to help integrating system together.


There is also the xref:incubator:ROOT:about.adoc[Incubator], that includes functionality that is currently experimental or unstable, but which may end up graduating as a component or to one of the library catalogues listed above.



