#
# This script:
#
# - builds interim of isis
# - pushes to repo.incode.cloud
# - builds demo-app, simple-app, helloworld
# - pushes demo-app image to hub.docker.com
#
# It requires the following gitlab secret variables
#
# - GCPAPPENGINEREPO_USERNAME
# - GCPAPPENGINEREPO_PASSWORD
# - GCPAPPENGINEREPO_URL
#
# - DOCKER_REGISTRY_USERNAME    # eg "apacheisiscommitters"  (needs to be in the ORG_NAME)
# - DOCKER_REGISTRY_PASSWORD


build all:
  stage: build-package-push
  variables:
     SHARED_VARS_FILE: /builds/apache-isis-committers/apache-isis/ci-env.txt
     MVN_STAGES: deploy
     MVN_ADDITIONAL_OPTS: '-DaltDeploymentRepository=gcpappenginerepo-deploy.serverId::url=https://repo.incode.work'
  script:
    # parent and mixins are built first because core (which includes extensions) depend upon them.
    - echo "REVISION=$BASELINE.$(date +%Y%m%d)-$(date +%H%M)-$(echo $CI_COMMIT_SHA | cut -c1-8)" > $SHARED_VARS_FILE
    - sh $CI_SCRIPTS_PATH/build-core.sh
    - sh $CI_SCRIPTS_PATH/build-demo-app.sh springboot
    - sh $CI_SCRIPTS_PATH/build-starter-apps.sh
