The `navigable` hint allows the viewer to construct a breadcrumb trail.
It is commonly used with objects forming a hierarchy, and so often is used in conjunction with the `TreeNode` value type.

This app uses the filesystem of the host computer to illustrate the idea:

* The view model object you are viewing -- `FileNode` -- represents either a directory or a file within that filesystem.

* Every instance of `FileNode` shows the same `TreeNode` instance, on the left hand side.
This allows the user to drill into the tree and inspect the individual files, without "losing their place".

The mechanics of creating the tree are shown below.

For all ``FileNode``s except the root (see the `path` property), a breadcrumb trail is rendered.
The framework constructs this based on the `navigable` hint, associated with no more than one property of the object.
This points back to the logical parent of the domain object:

[source,java,indent=0]
----
include::FileNodeVm.java[tags=navigable]
----

TIP: for a domain entity, the implementation would be a lookup of the parent entity from a repository.
For a view model, we can simply instantiate the parent (view models have value semantics in this respect).


It's common for hierarchical objects to indicate their nature using an icon:

[source,java,indent=0]
----
include::FileNodeVm.java[tags=iconName]
----

where `FileNodeType` is:

[source,java,indent=0]
----
include::FileNodeType.java[tags=class]
----

Note that there are SVG files for each of the instances of this enum, namely `FileNodeVm-FileSystemRoot.svg`, `FileNodeVm-Folder.svg` and `FileNodeVm-File.svg`.


== Tree

As described above, every `FileNode` renders the same tree:

[source,java,indent=0]
----
include::FileNodeVm.java[tags=tree]
----

The tree instance itself is cached by a `FileTreeNodeService`, so that there is no need to track the state of the tree (which nodes are expanded etc).
The `FileTreeNodeService` in turn uses `HttpSession` as the actual in-memory cache:

[source,java,indent=0]
----
include::FileTreeNodeService.java[tags=sessionTree]
----

The `TreeNode` value type itself is created using:

[source,java,indent=0]
----
include::FileTreeNodeService.java[tags=newTree]
----

This requires an implementation of the `TreeAdapter<T>` SPI:

[source,java]
----
public interface TreeAdapter<T> {
    public Optional<T> parentOf(T value);
    public int childCountOf(T value);
    public Stream<T> childrenOf(T value);
}
----

In the case of the demo app, the implementation is `FileSystemTreeAdapter`, which navigate the host computer's filesystem:


[source,java,indent=0]
----
include::FileSystemTreeAdapter.java[tags=class]
----
