= Oid _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.Oid.java
----
interface Oid {
  static final String SEPARATOR;
  String getLogicalTypeName()     // <.>
  String getIdentifier()     // <.>
  String stringify()     // <.>
}
----

<.> xref:#getLogicalTypeName__[getLogicalTypeName()]
+
--
Logical-type-name of the domain object this Oid is representing. (aka. object-type)
--
<.> xref:#getIdentifier__[getIdentifier()]
+
--
Stringified version of the ID of the domain object instance this Oid is representing.
--
<.> xref:#stringify__[stringify()]
+
--
The canonical form of the xref:refguide:applib:index/services/bookmark/Bookmark.adoc[Bookmark] , that is _#getLogicalTypeName() logical-type-name_ _#SEPARATOR_ _#getIdentifier() identifier_ .
--

== Members

[#getLogicalTypeName__]
=== getLogicalTypeName()

Logical-type-name of the domain object this Oid is representing. (aka. object-type)

[#getIdentifier__]
=== getIdentifier()

Stringified version of the ID of the domain object instance this Oid is representing.

[#stringify__]
=== stringify()

The canonical form of the xref:refguide:applib:index/services/bookmark/Bookmark.adoc[Bookmark] , that is _#getLogicalTypeName() logical-type-name_ _#SEPARATOR_ _#getIdentifier() identifier_ .
