:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

In this demo app, property editing has been disabled by default.
This entity class re-enables editing using `@DomainObject#editing`, and then selectively _disables_ it again for one of the properties using `@Property#editing`.

[source,java,indent=0]
.DomainObjectEditingJpa.java
----
include::DomainObjectEditingEntityImpl.java[tags=class]
----
<.> indicates that the properties of this type may be edited, overriding the global default set by  configuration property.
<.> editable property because of the `@DomainObject#editing` annotation
<.> this property cannot, after all, be edited, with `@Property#editing` overriding `@DomainObject#editing`
<.> also a non-editable property, but this time because it is a derived property.
