/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package org.apache.isis.core.metamodel.specloader.specimpl;

import org.junit.Assert;
import org.junit.rules.ExpectedException;
import org.junit.Test;

import java.lang.reflect.Array;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import com.diffblue.deeptestutils.CompareWithFieldList;
import com.diffblue.deeptestutils.Reflector;

@org.junit.runner.RunWith(org.powermock.modules.junit4.PowerMockRunner.class)
public class ObjectActionContributeeaddElementToArray001Test {

  @org.junit.Rule
  public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: org/apache/isis/core/metamodel/specloader/specimpl/ObjectActionContributee.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   * conditional line 275 branch to line 275
   * conditional line 276 branch to line 276
   */
  @org.powermock.core.classloader.annotations.PrepareForTest( { com.google.common.collect.Lists.class } )
  @Test
  public void org_apache_isis_core_metamodel_specloader_specimpl_ObjectActionContributee_addElementToArray_001_ed958a494e46bcbc() throws Throwable {

    Object [] retval;
    {
      /* Setup mocks */
      java.util.ArrayList mock_instance = new java.util.ArrayList();
      org.powermock.api.mockito.PowerMockito.mockStatic(com.google.common.collect.Lists.class);
      final java.util.ArrayList com_google_common_collect_Lists_newArrayList_Iterable_answer_list = new java.util.ArrayList();
      final java.util.ArrayList<Object[]> com_google_common_collect_Lists_newArrayList_Iterable_expectation_list = new java.util.ArrayList<Object[]>();
      final com.diffblue.deeptestutils.IterAnswer com_google_common_collect_Lists_newArrayList_Iterable_answer_object = new com.diffblue.deeptestutils.IterAnswer("com.google.common.collect.Lists", "newArrayList", com_google_common_collect_Lists_newArrayList_Iterable_answer_list, com_google_common_collect_Lists_newArrayList_Iterable_expectation_list);
      com_google_common_collect_Lists_newArrayList_Iterable_answer_list.add(mock_instance);
      org.mockito.Mockito.when(com.google.common.collect.Lists.newArrayList(org.mockito.AdditionalMatchers.or(org.mockito.Matchers.isA(Iterable.class), org.mockito.Matchers.isNull(Iterable.class)))).thenAnswer(com_google_common_collect_Lists_newArrayList_Iterable_answer_object);

      /* Arrange */
      java.lang.Object[] array = { null };
      int n = -1073741824;
      Object element = null;
      Object [] type = null;

      /* Act */
      thrown.expect(IndexOutOfBoundsException.class);
      try {
        Class<?> c = Reflector.forName("org.apache.isis.core.metamodel.specloader.specimpl.ObjectActionContributee");
        Method m = c.getDeclaredMethod("addElementToArray", Reflector.forName("java.lang.Object []"), Reflector.forName("int"), Reflector.forName("java.lang.Object"), Reflector.forName("java.lang.Object []"));
        m.setAccessible(true);
        retval = (Object []) m.invoke(null, array, n, element, type);
      } catch(InvocationTargetException ex) {
        throw ex.getCause();
      }

    /* Method is not expected to return due to exception thrown */  }
  }
}
