{
  "data" : {
    "gqltestdomain_GQLTestDomainMenu" : {
      "findE2" : {
        "name" : "foo",
        "_gql_mutations" : {
          "changeName" : {
            "name" : "bar"
          }
        }
      }
    }
  }
}