{
  "data" : {
    "gqltestdomain_GQLTestDomainMenu" : {
      "findAllE1" : [ {
        "name" : "foo",
        "_gql_generic" : {
          "id" : "1",
          "logicalTypeName" : "gqltestdomain.E1",
          "version" : "not yet implemented"
        }
      } ]
    }
  }
}