[[clear]]
= `clear...()` (deprecated)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `clear...()` supporting method is called -- instead of the setter -- whenever an (optional) property is to be set to `null`.
Its purpose is to allow additional business logic to be performed.

[NOTE]
====
DataNucleus' smart handling of setters means that this supporting methods are in essence redundant, and so should be considered deprecated.
====

For example:

[source,java]
----
public class LibraryMember {
    public Title getFavoriteTitle() { /* ... */ }
    public void setFavoriteTitle(Title title) { /* ... */ }
    public void modifyFavoriteTitle(Title title) { /* ... */ }
    public void clearFavoriteTitle() {
        if(getTitle() == null) { return; }
        setFavoriteTitle(null);                         // <1>
        titleFavoritesService.decrement(title);         // <2>
    }
    ...
}
----
<1> update the property
<2> perform some additional business logic


See also xref:rg:cms:methods/prefixes.adoc#modify[`modify...()`]`
