:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

CAUTION: this feature is currently broken in the demo (though it will work in most apps); see link:https://issues.apache.org/jira/browse/CAUSEWAY-3418[CAUSEWAY-3418].

Actions parameters can be either value types or reference types (typically entities), and can be either for  single-valued (a scalar) or multi-valued (a list).
Scalar values can be entered directly, but other combinations require a supporting method or other mechanism to provide a list of candidates for the end-user to select:

.Parameter types and entry methods
[cols="1a,2a,2a", options="header"]
|===

>| Type \ +
Param Cardinality
^|
Value type
^|
Reference type


<| Single
| Direct entry
|
* `choicesNXxx()` supporting method
* `autoCompleteNXxx()` supporting method
* `@DomainObject#autoCompleteXxx`
* `@DomainObject#bounded`


| Multiple
|
`choicesNXxx` supporting method
|
* `choicesNXxx()` supporting method
* `autoCompleteNXxx()` supporting method
* link:https://causeway.apache.org/refguide/2.0.0-SNAPSHOT/applib/index/annotation/Action.html#choicesfrom[@Action#choicesFrom]

|===

The `choicesFrom` element specifies an action has a multi-value reference type parameter whose choices should be obtained from the specified collection.

The end-user can select the choices using checkboxes rendered with the collection.

TIP: Such actions are sometimes called "bulk" actions because they (can) act upon many objects at once.


== How this demo works

The collection on the left hand side shows a set of domain objects, along with a couple of actions that both accept a collection of said objects as one of their parameters.

You can check the checkbox against one or more objectsand then click the actions' button.
The selected objects will be defaulted, but all objects will be available to select in the drop-down list.

In terms of code:

* page object:
+
[source,java,indent=0]
.ActionChoicesFromPage.java
----
include::ActionChoicesFromPage.java[tags=class]
----

* (contributed) collection of objects:
+
[source,java,indent=0]
.ActionChoicesFromPage_objects.java
----
include::ActionChoicesFromPage_objects.java[tags=class]
----

* one of the actions
+
[source,java,indent=0]
.ActionChoicesFromPage_makeLowerCase.java
----
include::ActionChoicesFromPage_makeLowerCase.java[tags=class]
----
<.> The `choicesFrom` element causes checkboxes to be rendered for each of the objects in the "objects" collection.
+
It also means that no `choices0Act()` or `autoComplete0Act()` is required.

