{
  rich {
    university_admin_AdminMenu {
      actionWithHiddenParam {
        params {
          firstParam {
            hidden
          }
          secondParam {
            hidden
          }
        }
      }
    }
  }
}
