{
  rich {
    university_dept_Departments {
      createDepartment {
        params {
          name {
            disabled
          }
        }
        invokeNonIdempotent(name: "newbie") {
          results {
            name {
              get
            }
          }
        }
      }
    }
  }
}
