{
  rich {
    university_dept_Departments {
      createDepartment {
        hidden
        disabled
        invokeNonIdempotent(name: "newbie") {
          results {
            name {
              get
            }
          }
        }
      }
    }
  }
}
