{
  university_dept_Departments {
    findDepartmentByName {
      invoke(name: "Classics") {
        deptHead {
          autoComplete(search: "Ho") {
            name {
              get
            }
          }
        }
      }
    }
  }
}
