{
  university_dept_Departments {
    findDepartmentByName {
      invoke(name: "Classics") {
        addStaffMembers {
          params {
            staffMembers {
              choices {
                _gqlv_meta {
                  id
                }
                name {
                  get
                }
              }
            }
          }
        }
      }
    }
  }
}
