{
  rich {
    university_dept_Departments {
      findDepartmentByName {
        invoke(name: "Classics") {
          results {
            deptHead {
              autoComplete(search: "Ho") {
                name {
                  get
                }
              }
            }
          }
        }
      }
    }
  }
}
