{
  university_dept_Departments {
    findDepartmentByName {
      invoke(name: "Classics") {
        changeDeptHead {
          params {
            newDeptHead {
              default {
                name {
                  get
                }
              }
            }
          }
        }
      }
    }
  }
}
