{
  university_dept_Departments {
    findAllDepartments {
      invoke {
        name {
          get
          datatype
        }
        _meta {
          logicalTypeName
          version
        }
      }
    }
  }
}
