{
  university_dept_Departments {
    findDepartmentByName {
      invoke(name: "Classics") {
        staffMembers {
          get {
            name {
              get
            }
          }
        }
      }
    }
  }
}
