{
  rich {
    university_dept_Departments {
      findAllDepartments {
        invoke {
          results {
            name {
              get
              datatype
            }
            _meta {
              logicalTypeName
              version
            }
          }
        }
      }
    }
  }
}
