{
  rich {
    Scenario(name: "DeptHead is also a Person") {
      Name
      Given {
        university_dept_People {
          findNamed {
            invoke(name: "Dr. Helen Johansen") {
              args {
                name
              }
              results {
                name {
                  get
                }
                _meta {
                  saveAs(ref: "dept-head")
                }
              }
            }
          }
        }
      }
      When {
        university_dept_Person(object: {ref: "dept-head"}) {
          name {
            get
          }
        }
      }
    }
  }
}
