{
  rich {
    university_dept_Staff {
      findStaffMemberByName {
        invoke(name: "Gerry Jones") {
          results {
            name {
              validate(name: "Gerry!")
            }
          }
        }
      }
    }
  }
}
