{
  rich {
    university_dept_Staff {
      findAllStaffMembers {
        invoke {
          results {
            name {
              get
            }
            grade {
              get
            }
            photo {
              get {
                name
                mimeType
                bytes
              }
            }
          }
        }
      }
    }
  }
}
