{
  university_dept_Staff {
    findByName {
      invoke(name: "Gerry Jones") {
        name {
          set(name: "Gerald Johns") {
            name {
              get
            }
          }
        }
      }
    }
  }
}
