[[jdo-api]]
= Using the JDO API

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



As an alternative to relying on Apache Isis to call lifecycle callback methods, you could instead use the JDO link:http://www.datanucleus.org/products/datanucleus/jdo/lifecycle_callbacks.html[lifecycle listener] API directly.

[NOTE]
====
We may decide to deprecate the Apache Isis callbacks in the future because they merely duplicate this functionality already available in JDO.
====

You can gain access to the relevant JDO API using the xref:pjdo:ROOT:services/IsisJdoSupport.adoc[`IsisJdoSupport`] domain service.

For example:

[source,java]
----
import org.springframework.stereotype.Service;

@IsisSessionScope                                                // <.>
@Service
public class ObjectChangedListenerService
        implements javax.jdo.listener.StoreLifecycleListener {   // <.>
    @PostConstruct
    public void init() {
        getPmFactory().addInstanceLifecycleListener(this);
    }
    @PreDestroy
    public void tidyUp() {
        getPmFactory().removeInstanceLifecycleListener(this);
    }
    private PersistenceManager getPersistenceManager() {
        return jdoSupport.getPersistenceManager();               // <.>
    }
    public void preStore (InstanceLifecycleEvent event) { /* ... */ }
    public void postStore (InstanceLifecycleEvent event) { /* ... */ }
    @Inject
    IsisJdoSupport jdoSupport;
}
----
<.> must be `@IsisSessionScope` because we register on the `PersistenceManager`, which is different for each request.
<.> implement whichever callback lifecycle listeners are of interest
<.> use the injected xref:pjdo:ROOT:services/IsisJdoSupport.adoc[`IsisJdoSupport`] service to obtain the `PersistenceManager`.

Note that it isn't possible to register on the `PersistenceManagerFactory` because listeners cannot be attached once a persistence session has been created (which it will have been when the service's `@PostConstruct` method is called).


