[[_ugtst_integ-test-support_bootstrapping]]
= Bootstrapping
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


Integration tests instantiate an Apache Isis "runtime" (as a singleton) within a JUnit test.
Because (depending on the size of your app) it takes a little time to bootstrap Apache Isis, the framework caches the runtime on a thread-local from one test to the next.


The recommended way to bootstrapping of integration tests is done using a xref:rg:cms:rgcms.adoc#_rgcms_classes_AppManifest2-bootstrapping[`Module`] implementation, along with the `IntegrationTestAbstract3` superclass.

For example, the xref:ug:fun:ugfun.adoc#_ugfun_getting-started_simpleapp-archetype[SimpleApp archetype]'s integration tests all inherit from this class:

[source,java]
----
public abstract class DomainAppIntegTestAbstract extends IntegrationTestAbstract3 {

    public DomainAppIntegTestAbstract() {
        super(new DomainAppApplicationModule());
    }
}
----

where `DomainAppApplicationModule` in turn declares all the dependencies that make up the application.

If required, the `Module` can be customised first using the various `withXxx(...)` methods to specify addition modules, domain services and configuration properties.


== Faster Bootstrapping

The `IntegrationTestAbstract3` superclass also allows the introspection mode to be specified, which can reduce the time to bootstrap the test.

By default integration tests are run in "production" deployment mode, so with the `isis.reflector.introspection.mode` set to its default of "lazy_unless_production" this will actually result in full introspection of the Apache Isis metamodel.
The _does_ have the benefit that the metamodel will be validated, but - as mentioned - with the corresponding downside of taking longer to bootstrap.

To bootstrap lazily, override as follows:

[source,java]
----
public abstract class DomainAppIntegTestAbstract extends IntegrationTestAbstract3 {

    public DomainAppIntegTestAbstract() {
        super(new DomainAppApplicationModule(), IntrospectionMode.LAZY);
    }
}
----
