:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/Action.html#semantics[@Action#semantics] attribute specifies whether invoking the action will change the state of the system, and if so, how:

* `SAFE` (also called "query-only") means no side-effects, that is, no permanent change in state of the system

* `IDEMPOTENT` means that the state of the system will change, but invoking the action again (with the same arguments) will not change the state; in other words re-runnable

* `NON_IDEMPOTENT` means that the state will change, and subsequent invocations will change the state again.
+
If the action is not annotated, then non-idempotent is assumed.

The REST API interprets these semantics by mapping to different HTTP verbs: GET, PUT and POST, respectively.

Each of these three basic `semantics` attribute have a variant:

* `SAFE_AND_REQUEST_CACHEABLE` means that the framework will automatically cache the result of a first invocation and use the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/services/queryresultscache/QueryResultsCache.html[QueryResultsCache] to return the result subsequently.
+
Note this does require that the action is invoked "through" the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/services/wrapper/WrapperFactory.html#wrap(t,-synccontrol)[WrapperFactory].

* `IDEMPOTENT_ARE_YOU_SURE` will cause the viewer to display an "are you sure" prompt so that the end-user can choose to not invoke the action after all

* `NON_IDEMPOTENT_ARE_YOU_SURE` similarly displays an "are you sure" prompt, but for non-idempotent actions.

== How this demo works

This page provides actions with different semantics.

=== No annotations

If the `semantics` attribute is omitted completely, then the action is assumed to be non-idempotent:

[source,java,indent=0]
----
include::ActionSemanticsPage.java[tags=action-no-annotation]
----
<.> does not indicate any `semantic` attribute, and so non-idempotent is assumed

=== Annotated as Safe

An action with safe semantics means that there are bi side-effects; it does not change the state of the system.
This is also sometimes called _query-only_.

Safe actions are called using HTTP GET when invoked through the Restful Objects' REST API.

[source,java,indent=0]
----
include::ActionSemanticsPage.java[tags=action-semantics-safe]
----
<.> safe semantics, meaning invoking the action results in no permanent change of state

[IMPORTANT]
====
The framework does not verify or ensure that the action results in no side-effects; the annotation is taken "on trust".
====


==== Safe and Request Cacheable

Since invoking a safe query-only action will often return the same result (at least for some short period of time), the framework also provides a variant that will automatically cache the result for the duration of the interaction (HTTP request).

To leverage this, the action must be invoked "through" the framework, in other words using the `WrapperFactory` service.

To demonstrate this, the demo app declares the following action:

[source,java,indent=0]
----
include::ActionSemanticsPage.java[tags=action-semantics-safe-and-request-cacheable]
----
<.> the result of invoking this action will be cached for the duration of the interaction (HTTP request)
<.> the action need not be exposed in the end-user
<.> for the purpose of the demo, counts the number of times invoked

This action can then be invoked through the `WrapperFactory`:

[source,java,indent=0]
----
include::ActionSemanticsPage.java[tags=action-semantics-safe-and-request-cacheable-caller]
----
<.> invoke the action 5 times
<.> skips the check that the action is hidden
<.> reports on the number of times the action was actually executed

In this case the called action should indicate it was only executed once.

=== Annotated as Idempotent

Annotating an action as idempotent means that it will change the state of the system, but invoking more than once will not change the state of the system further.

Idempotent actions are called using HTTP PUT when invoked through the Restful Objects' REST API.

Both regular and mixin actions can be annotated:

* on regular actions; the `setToValuePropertyForIdempotent` action is annotated as having idempotent semantics:
+
[source,java,indent=0]
----
include::ActionSemanticsPage.java[tags=action-semantics-idempotent]
----
<.> idempotent semantics

==== Idempotent, are you sure?

Because an idempotent action will change the state of the system, the framework offers a variant that will cause the viewer to render an "are you sure?" pop-up.

[source,java,indent=0]
----
include::ActionSemanticsPage.java[tags=action-semantics-idempotent-are-you-sure]
----
<.> idempotent semantics, with "are you sure" prompt


=== Annotated as Not Idempotent

Annotating an action as non-idempotent means that it will change the state of the system, and invoking more than once will change the state of the system further.

Non-idempotent actions are called using HTTP POST when invoked through the Restful Objects' REST API.

[source,java,indent=0]
----
include::ActionSemanticsPage.java[tags=action-semantics-non-idempotent]
----
<.> non-idempotent semantics


==== Not idempotent, are you sure ?

Because a non-idempotent action will change the state of the system, the framework offers a variant that will cause the viewer to render an "are you sure?" pop-up.

There are two example actions, one of which takes no parameters, the other of which takes a parameter.
This demonstrates that the pop-up appears at different points:

* with no parameters.
+
The pop-up appears when the action's button is pressed.
+
[source,java,indent=0]
----
include::ActionSemanticsPage.java[tags=action-semantics-non-idempotent-are-you-sure-1]
----
<.> non-idempotent semantics, with "are you sure" prompt

* with a parameters
+
The pop-up appears when the OK button on the action's prompt is pressed.
+
[source,java,indent=0]
----
include::ActionSemanticsPage.java[tags=action-semantics-non-idempotent-are-you-sure-2]
----
<.> non-idempotent semantics, with "are you sure" prompt

