The framework has built-in support for all of the primitive data types, including `char`.

From here you can:

* navigate to an entity that uses the `char` datatype
* open a view model that uses the `char` datatype

Because `char` is a primitive value, the properties on these domain objects are mandatory.

== Common interface

These objects both implement a common interface, `PrimitiveCharHolder`:

[source,java]
----
include::holder/PrimitiveCharHolder.java[tags=class]
----

There is also an extension of this interface, `PrimitiveCharHolder2`, with default methods demonstrating the use of label positions:

[source,java]
----
include::holder/PrimitiveCharHolder2.java[tags=class]
----

<.> The default methods have annotations that are automatically inherited.
<.> Using `@MemberOrder` positions the properties into the appropriate `<field-set>` within the `Xxx.layout.xml` layout file.


== Mixin actions

A number of mixin actions contribute through this interface, demonstrate the use of `char` as a parameter and as a return type.
For example:

* the `updateReadOnlyProperty` action is:
+
[source,java]
----
include::holder/PrimitiveCharHolder_updateReadOnlyProperty.java[tags=class]
----

* the `actionReturning` action is:
+
[source,java]
----
include::holder/PrimitiveCharHolder_actionReturning.java[tags=class]
----

== Mixin properties

We also use the interface to contribute a mixin property:

* the `mixinProperty` property:
+
[source,java]
----
include::holder/PrimitiveCharHolder_mixinProperty.java[tags=class]
----

