= ThrowingRunnable
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Similar to a _Runnable_ , except that it can also throw a checked _Exception_ .

== API

[source,java]
.ThrowingRunnable.java
----
interface ThrowingRunnable {
  void run()
  void runUncatched()     // <.>
  Void callUncatched()     // <.>
  Runnable toRunnable()     // <.>
  Callable<Void> toCallable()     // <.>
}
----

<.> xref:#runUncatched_[runUncatched()]
+
--
Does *not* silently swallow, wrap into RuntimeException, or otherwise modify any exceptions of the wrapped _#run()_ method.
--
<.> xref:#callUncatched_[callUncatched()]
+
--
Does *not* silently swallow, wrap into RuntimeException, or otherwise modify any exceptions of the wrapped _#run()_ method.
--
<.> xref:#toRunnable_[toRunnable()]
+
--
The resulting _Runnable_ does *not* silently swallow, wrap into RuntimeException, or otherwise modify any exceptions of the wrapped _#run()_ method.
--
<.> xref:#toCallable_[toCallable()]
+
--
The resulting _Callable_ does *not* silently swallow, wrap into RuntimeException, or otherwise modify any exceptions of the wrapped _#run()_ method.
--

== Members

[#runUncatched_]
=== runUncatched()

Does *not* silently swallow, wrap into RuntimeException, or otherwise modify any exceptions of the wrapped _#run()_ method.

[#callUncatched_]
=== callUncatched()

Does *not* silently swallow, wrap into RuntimeException, or otherwise modify any exceptions of the wrapped _#run()_ method.

[#toRunnable_]
=== toRunnable()

The resulting _Runnable_ does *not* silently swallow, wrap into RuntimeException, or otherwise modify any exceptions of the wrapped _#run()_ method.

[#toCallable_]
=== toCallable()

The resulting _Callable_ does *not* silently swallow, wrap into RuntimeException, or otherwise modify any exceptions of the wrapped _#run()_ method.
