= Maven Configuration
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]




Apache Isis' BDD spec support is automatically configured if you use the xref:arch:simpleapp:about.adoc[SimpleApp archetype].
To set it up manually, update the `pom.xml` of your domain object model module:

[source,xml]
----
<dependency>
    <groupId>org.apache.isis.core</groupId>
    <artifactId>isis-core-specsupport</artifactId>
    <scope>test</scope> // <1>
</dependency>
----
<1> Normally `test`; usual Maven scoping rules apply.


The configuration is wrapped up as maven mixins:

[source,xml]
----
<plugins>
    <plugin>
        <groupId>com.github.odavid.maven.plugins</groupId>
        <artifactId>mixin-maven-plugin</artifactId>
        <version>0.1-alpha-39</version>
        <extensions>true</extensions>
        <configuration>
            <mixins>
                ...
                <mixin>
                    <groupId>com.danhaywood.mavenmixin</groupId>
                    <artifactId>surefire</artifactId>
                </mixin>
                <mixin>
                    <groupId>com.danhaywood.mavenmixin</groupId>
                    <artifactId>cucumberreporting</artifactId>
                </mixin>
            </mixins>
        </configuration>
    </plugin>
</plugins>

----

You may also find it more convenient to place the `.feature` files in `src/test/java`, rather than `src/test/resources`.
If you wish to do this, then your integtest module's `pom.xml` must contain:

[source,xml]
----
<build>
    <testResources>
        <testResource>
            <filtering>false</filtering>
            <directory>src/test/resources</directory>
        </testResource>
        <testResource>
            <filtering>false</filtering>
            <directory>src/test/java</directory>
            <includes>
                <include>**</include>
            </includes>
            <excludes>
                <exclude>**/*.java</exclude>
            </excludes>
        </testResource>
    </testResources>
</build>
----
