:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The framework has built-in support for rendering HTML written using Markdown, using the `Markdown` data type.

NOTE: This is an Apache Isis specific data type.

From here you can:

* navigate to an entity that uses the `Markdown` datatype
* open a view model that uses the `Markdown` datatype

Some properties on these domain objects are mandatory, some optional.

== Common interfaces

The entity and view model types both implement some common interfaces.

=== IsisMarkdownHolder

The `IsisMarkdownHolder` interface is used to contribute a number of mixins to both types:

[source,java]
----
include::holder/IsisMarkdownHolder.java[tags=class]
----

=== IsisMarkdownHolder2

The `IsisMarkdownHolder2` interface is used to demonstrate support for label positions using `@PropertyLayout(labelPosition=...)`.

Further details, along with the effect of this annotation, can be seen on the entity and view model object pages.