= BS3Menu
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Describes the collection of domain services into menubars, broadly corresponding to the aggregation of information of xref:refguide:applib:index/annotation/DomainServiceLayout.adoc[DomainServiceLayout] that have the same value of _DomainServiceLayout#named()_ .

== API

[source,java]
.BS3Menu.java
----
class BS3Menu {
  BS3Menu()
  BS3Menu(String named)
  String getNamed()
  void setNamed(String named)
  String getCssClassFa()
  void setCssClassFa(String cssClassFa)
  List<BS3MenuSection> getSections()
  Boolean isUnreferencedActions()     // <.>
  void setUnreferencedActions(Boolean unreferencedActions)
}
----

<.> xref:#isUnreferencedActions__[isUnreferencedActions()]
+
--
Whether this menu should be used to hold any unreferenced actions.
--

== Members

[#isUnreferencedActions__]
=== isUnreferencedActions()

Whether this menu should be used to hold any unreferenced actions.

Any menubars layout must have precisely one menu that has this attribute set.
