[[weekly-builds]]
= Weekly Builds

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:

CAUTION: weekly builds are currently disabled.

A weekly build of the framework is performed in the main link:https://github.com/apache/causeway[apache/causeway] repo, and are available as link:https://github.com/orgs/apache/packages?repo_name=causeway[packages] of this repo.


[WARNING]
====
*These weekly builds should not be used in production.*

Weekly builds are interim builds that are untested and unsupported.

These unreleased builds may have undocumented features, known and unknown defects, and any number of other issues.

They are intended for use by developers and others wishing to help with the development of the framework.
====


== Authentication Access

To use the weekly builds, you need authenticated access using your github credentials.

One way to do this is to add the following to your `~/.m2/settings.xml` file.

[source,xml]
.~/.m2/settings.xml
----
<settings>
  <servers>
    <server>
      <id>github-apache-causeway</id>
      <username>myusername</username>                               <!--.-->
      <password>ghp_TOKEN_WITH_PACKAGE_REPO_READ_ACCESS</password>  <!--.-->
    </server>
  </servers>
  <profiles>
    <profile>
      <id>github-apache-causeway</id>
      <activation>
        <property>
          <name>!skip.github-apache-causeway</name>
        </property>
      </activation>
      <repositories>
        <repository>
          <id>github-apache-causeway</id>
          <url>https://maven.pkg.github.com/apache/causeway</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
      </repositories>
    </profile>
  </profiles>
  <activeProfiles>
    <activeProfile>github-apache-causeway</activeProfile>
  </activeProfiles>
</settings>
----
<.> your github username.
<.> a corresponding personal token to provide access, as per link:https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages[these docs].

You can find the latest version by browsing the link:https://github.com/apache/causeway/packages/1304938[org.apache.causeway.core.causeway-applib] package.

