= MarshallerService
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Supports marshaling and unmarshaling of the generic type T for a set of mime types.

== API

[source,java]
.MarshallerService.java
----
interface MarshallerService<T> {
  Class<T> supportedClass()
  EnumSet<CommonMimeType> supportedFormats()     // <.>
  String marshal(T value, CommonMimeType format)     // <.>
  Try<T> unmarshal(String content, CommonMimeType format)     // <.>
}
----

<.> xref:#supportedFormats_[supportedFormats()]
+
--
Supported format(s) for _#unmarshal(String, CommonMimeType)_ and _#marshal(Object, CommonMimeType)_ .
--
<.> xref:#marshal_T_CommonMimeType[marshal(T, CommonMimeType)]
<.> xref:#unmarshal_String_CommonMimeType[unmarshal(String, CommonMimeType)]
+
--
Returns a new de-serialized instance wrapped in a xref:refguide:commons:index/functional/Try.adoc[Try] .
--

== Members

[#supportedFormats_]
=== supportedFormats()

Supported format(s) for _#unmarshal(String, CommonMimeType)_ and _#marshal(Object, CommonMimeType)_ .

[#marshal_T_CommonMimeType]
=== marshal(T, CommonMimeType)

[#unmarshal_String_CommonMimeType]
=== unmarshal(String, CommonMimeType)

Returns a new de-serialized instance wrapped in a xref:refguide:commons:index/functional/Try.adoc[Try] .
