= ExceptionRecognizerForType
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

A specific implementation of xref:refguide:applib:index/services/exceprecog/ExceptionRecognizer.adoc[ExceptionRecognizer] that looks for an exception of the type provided in the constructor and, if found anywhere in the causal chain, then returns a non-null message indicating that the exception has been recognized.

If a messaging-parsing _Function_ is provided through the constructor, then the message can be altered. Otherwise the exception's _Throwable#getMessage() message_ is returned as-is.

== API

[source,java]
.ExceptionRecognizerForType.java
----
class ExceptionRecognizerForType {
  ExceptionRecognizerForType(Category category, Class<? extends Exception> exceptionType, Function<Throwable, String> rootCauseMessageFormatter)
  ExceptionRecognizerForType(Category category, Predicate<Throwable> predicate, Function<Throwable, String> rootCauseMessageFormatter)
  ExceptionRecognizerForType(Category category, Class<? extends Exception> exceptionType)
  ExceptionRecognizerForType(Class<? extends Exception> exceptionType, Function<Throwable, String> rootCauseMessageFormatter)
  ExceptionRecognizerForType(Predicate<Throwable> predicate, Function<Throwable, String> rootCauseMessageFormatter)
  ExceptionRecognizerForType(Class<? extends Exception> exceptionType)
}
----

