:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

It's quite common for user interfaces to include an icon for each action or menu item as a visual clue as to the purpose of that action.
The link:https://causeway.apache.org/refguide/2.0.0-SNAPSHOT/applib/index/annotation/ActionLayout.html#cssclassfa[@ActionLayout#cssClassFa] element allows this to be done by specifying the _Font Awesome_ CSS class (or classes) with which to decorate an action.
This is used for whether the action is rendered as a button or as a menu item.

=== How this demo works

This page includes two actinos

[source,java,indent=0]
----
include::ActionLayoutCssClassFaPage.java[tags=actLeftAndRight]
----

<.> in effect uses the `bus` icon for this action

<.> the `cssClassFaPosition` attribute indicates the position of the _Font Awesome_ icon;
in effect the icon is rendered on the _right_ of the action button


==== Related configuration property

[source,yaml]
.application.yml
----
causeway:

  applib:
    annotation:
      action:
        execution-publishing: none
        command-publishing: none
      action-layout:
        css-class-fa:
          patterns:
            new.*:fa-plus,
            add.*:fa-plus-square,
            create.*:fa-plus,
            update.*:fa-edit,
            delete.*:fa-trash,
            find.*:fa-search,
            list.*:fa-list,
            all.*:fa-list,
            export.*:fa-file-export,
            import.*:fa-file-import
        css-class:
          patterns:
            delete.*:btn-danger
----
