:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

To help the end-user navigate a page, it can sometimes be helpful to decorate individual actions within icons so that their purpose is more obvious.

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/ActionLayout.html#cssclassfa[@ActionLayout#cssClassFa] attribute allows this to be done by specifying the _Font Awesome_ CSS class (or classes) with which to decorate an action.
This is used for whether the action is rendered as a button or as a menu item.

== How this demo works

This page has a `name` property and two actions, both of which can be used to update that property.
The two actions have different fa icons.

* the `updateNameWithFaIconOnTheLeft` action is defined as:
+
[source,java,indent=0]
----
include::ActionLayoutCssClassFaPage.java[tags=updateNameWithFaIconOnTheLeft]
----
<.> uses the `bus` icon for this action

* the `updateNameWithFaIconOnTheRight` action is defined as:
+
[source,java,indent=0]
----
include::ActionLayoutCssClassFaPage.java[tags=updateNameWithFaIconOnTheRight]
----
<.> use the `car` icon for this action
<.> and place the icon on the right (by default it is placed on the left)


in effect the icon is rendered on the _right_ of the action button


== Related configuration property

Rather than styling each action individually, it's possible to use a configuration property which defines styles globally.

It works by specifying a set of `regex:cssClassFa` pairs; if the action's identifier matches the regex, then the fa icon is applied.
This is a great way to ensure that actions with similar semantics have similar names; they will then pick up the same visual cues.

The following is taken from this demo app:


[source,yaml]
.application.yml
----
causeway:

  applib:
    annotation:
      action-layout:
        css-class-fa:
          patterns:
            new.*:fa-plus,
            add.*:fa-plus-square,
            create.*:fa-plus,
            update.*:fa-edit,
            delete.*:fa-trash,
            find.*:fa-search,
            list.*:fa-list,
            all.*:fa-list,
            export.*:fa-file-export,
            import.*:fa-file-import
----


== .layout.xml

Instead of using `@ActionLayout#cssClassFa`, it is also possible to specify the fa icon class using the `<action id="..." cssClass="...">` in the link:https://causeway.apache.org/userguide/2.0.0-RC1/fun/ui.html#by-example[.layout.xml] file.

One advantage of using the `.layout.xml` file is that changes can be picked up without having to restart the application.
