= `AuditingServiceInternal`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


The (internal) `AuditingServiceInternal` domain service acts as an internal facade to any registered xref:applib:svc:persistence-layer-spi/AuditerService.adoc[`AuditerService`] service(s).
It is responsible for obtaining the details of all changes to domain objects within an interaction, and then to call the configured ``AuditerService``(s) to actually create audit entries of those changes.




== SPI and Implementation

The SPI of the service is:

[source,java]
----
public class AuditingServiceInternal {
    public boolean canAudit();              // <1>
    public void audit();                    // <2>
}
----
<1> minor performance optimization as to whether any auditing services are actually enabled; checks to see if any xref:applib:svc:persistence-layer-spi/AuditerService.adoc[`AuditerService`] are enabled.
<2> uses the xref:runtime-services:ROOT:persistence-layer/ChangedObjectsServiceInternal.adoc[`ChangedObjectsServiceInternal`] to obtain details of the changed properties, then call the configured xref:applib:svc:persistence-layer-spi/AuditerService.adoc[`AuditerService`](s).

The service implementation is `o.a.i.c.r.s.auditing.AuditingServiceInternal`.



== Registering the Service

Apache Isis' default implementation of `AuditingServiceInternal` class is automatically registered (it is annotated with `@DomainService`) so no further configuration is required.


== Related Classes

The service delegates between the (internal) xref:runtime-services:ROOT:persistence-layer/ChangedObjectsServiceInternal.adoc[`ChangedObjectsServiceInternal`] domain service  to the configured xref:applib:svc:persistence-layer-spi/AuditerService.adoc[`AuditerService`](s).
If no such service(s) are configured, then _this_ service is in effect a no-op.

The (internal) xref:runtime-services:ROOT:persistence-layer/PublishingServiceInternal.adoc[`PublishingServiceInternal`] performs a similar function for the xref:applib:svc:persistence-layer-spi/PublisherService.adoc[`PublisherService`], also collating details of the changed objects from `ChangedObjectsServiceInternal`.
