{
  university_dept_Departments {
    findDepartmentByName {
      invoke(name: "Classics") {
        changeName {
          validate(newName: "A Funny Thing Happened on the Way to the Forum !")
        }
      }
    }
  }
}
