= `InteractionContext`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `InteractionContext` is a request-scoped domain service that is used to obtain the current
`Interaction`.

An `Interaction` generally consists of a single top-level `Execution`, either to invoke an action or to edit a
property.  If that top-level action or property uses xref:rg:svc:application-layer-api/WrapperFactory.adoc[`WrapperFactory`] to
invoke child actions/properties, then those sub-executions are captured as a call-graph.  The `Execution` is thus a
graph structure.

If a bulk action is performed (as per an action annotated using
xref:rg:ant:Action.adoc#invokeOn[`@Action#invokeOn()`]), then this will result in multiple ``Interaction``s, one
per selected object (not one `Interaction` with multiple top-level ``Execution``s).


It is possible for ``Interaction.Execution``s to be persisted; this is supported by the (non-ASF) link:https://platform.incode.org[Incode Platform^]'s publishmq module, for example.  Persistent
``Interaction``s support several use cases:

* they enable profiling of the running application (which actions are invoked then most often, what is their response
time)

* if auditing is configured (using xref:rg:svc:persistence-layer-spi/AuditerService.adoc[`AuditerService`]), they provide better audit information, since the
`Interaction.Execution` captures the 'cause' of an interaction and can be correlated to the audit records (the "effect"
of the interaction) by way of the xref:rg:cms:classes/mixins.adoc#HasTransactionId[`transactionId`]





== API & Implementation

The public API of the service consists of several related classes:

* `InteractionContext` domain service itself:
* `Interaction` class, obtainable from the `InteractionContext`
* `Execution` class, obtainable from the `Interaction`.

The `Execution` class itself is abstract; there are two subclasses, `ActionInvocation` and `PropertyEdit`.

=== `InteractionContext`

The public API of the `InteractionContext` domain service itself consists of simply:

[source,java]
----
@RequestScoped
public class InteractionContext {
    public Interaction getInteraction();            // <1>
}
----
<1> Returns the currently active {@link Interaction} for this thread.

This class is concrete (that is, it is also the implementation).


=== `Interaction`

The public API of the `Interaction` class consists of:

[source,java]
----
public class Interaction {
    public UUID getTransactionId();                 // <1>
    public Execution getPriorExecution();           // <2>
    public Execution getCurrentExecution();         // <3>
    public List<Execution> getExecutions();         // <4>
    public int next(final String sequenceId);       // <5>
}
----
<1> The unique identifier of this interaction.  This will be the same value as held in `Command` (obtainable from xref:rg:svc:application-layer-api/CommandContext.adoc[`CommandContext`]).
<2> The member `Execution` (action invocation or property edit) that preceded the current one.
<3> The current execution.
<4> * Returns a (list of) execution}s in the order that they were pushed.  Generally there will be just one entry in this list, but additional entries may arise from the use of mixins/contributions when re-rendering a modified object.
<5> Generates numbers in a named sequence.  Used by the framework both to number successive interaction ``Execution``s and for events published by the xref:rg:svc:persistence-layer-spi/PublisherService.adoc[`PublisherService`].

This class is concrete (is also the implementation).


=== `Interaction.Execution`

The `Interaction.Execution` (static nested) class represents an action invocation/property edit as a node in a
call-stack execution graph.  Sub-executions can be performed using the
xref:rg:svc:application-layer-api/WrapperFactory.adoc[`WrapperFactory`].

It has the following public API:

[source,java]
----
public abstract class Execution {
    public Interaction getInteraction();            // <1>
    public InteractionType getInteractionType();    // <2>
    public String getMemberIdentifier();            // <3>
    public Object getTarget();                      // <4>

    public String getTargetClass();                 // <5>
    public String getTargetMember();

    public Execution getParent();                   // <6>
    public List<Execution> getChildren();

    public AbstractDomainEvent getEvent();          // <7>

    public Timestamp getStartedAt();                // <8>
    public Timestamp getCompletedAt();

    public Object getReturned();                    // <9>
    public Exception getThrew();

    public T getDto();                              // <10>
}
----
<1> The owning `Interaction`.
<2> Whether this is an action invocation or a property edit.
<3> A string uniquely identifying the action or property (similar to Javadoc syntax).
<4> The object on which the action is being invoked or property edited.  In the case of a mixin this will be the mixin object itself (rather than the mixed-in object).
<5> A human-friendly description of the class of the target object, and of the name of the action invoked/property
edited on the target object.
<6> The parent action/property that invoked this action/property edit (if any), and any actions/property edits made in
turn via the xref:rg:svc:application-layer-api/WrapperFactory.adoc[`WrapperFactory`].
<7> The domain event fired via the xref:rg:svc:core-domain-api/EventBusService.adoc[`EventBusService`] representing the
execution of this action invocation/property edit.
<8> The date/time at which this execution started/completed.
<9> The object returned by the action invocation/property edit, or the exception thrown.  For `void` methods and for actions returning collections, the value will be `null`.
<10> A DTO (instance of the xref:rg:cms:schema.adoc#ixn["ixn" schema]) being a serializable representation of this action invocation/property edit.



[NOTE]
====

Unlike the similar xref:rg:svc:application-layer-api/CommandContext.adoc[`CommandContext`] domain service (discussed xref:rg:svc:application-layer-api/InteractionContext.adoc#Related-Classes[below]) there is no domain service to different implementations of `Interaction` to be used.
That said, the framework simply instantiates the `Interaction` using the
xref:rg:svc:core-domain-api/FactoryService.adoc[`FactoryService`].
If a different implementation of `Interaction` was required, then a custom implementation of
 xref:rg:svc:core-domain-api/FactoryService.adoc[`FactoryService`] could always be supplied.
====


There are two concrete subclasses of `Execution`.

The first is `ActionInvocation`, representing the execution of an action being invoked:

[source,java]
----
public class ActionInvocation extends Execution {
    public List<Object> getArgs();                  // <1>
}
----
<1> The objects passed in as the arguments to the action's parameters.  Any of these could be `null`.


The second is `PropertyEdit`, and naturally enough represents the execution of a property being edited:

[source,java]
----
public class PropertyEdit extends Execution {
    public Object getNewValue();                    // <1>
}
----
<1> The object used as the new value of the property.  Could be `null` if the property is being cleared.


=== Alternate Implementations

Apache Isis' default implementation of `InteractionContext` class is automatically registered (it is annotated with `@DomainService`).





== Interacting with the services

Typically domain objects will have little need to interact with the `InteractionContext` and `Interaction` directly.
The services are used within the framework however, primarily to support the
xref:rg:svc:persistence-layer-spi/PublisherService.adoc[`PublisherService`] SPI, and to emit domain events over the
xref:rg:svc:core-domain-api/EventBusService.adoc[`EventBusService`].






== Related Classes

This service is very similar in nature to xref:rg:svc:application-layer-api/CommandContext.adoc[`CommandContext`], in that the
`Interaction` object accessed through it is very similar to the `Command` object obtained from the `CommandContext`.
The principle distinction is that while `Command` represents the __intention__ to invoke an action or edit a property,
the `Interaction` (and contained ``Execution``s) represents the actual execution.

Most of the time a `Command` will be followed directly by its corresponding `Interaction`.  However, if the `Command`
is annotated to run in the background (using xref:rg:ant:Action.adoc#command[`@Action#commandExecuteIn()`], or
is explicitly created through the xref:rg:svc:application-layer-api/BackgroundService.adoc[`BackgroundService`], then the actual
interaction/execution is deferred until some other mechanism invokes the command (eg as described
xref:ug:btb:about.adoc#BackgroundCommandExecution[here]).


