[[quotes]]
= Quotes
:notice: licensed to the apache software foundation (asf) under one or more contributor license agreements. see the notice file distributed with this work for additional information regarding copyright ownership. the asf licenses this file to you under the apache license, version 2.0 (the "license"); you may not use this file except in compliance with the license. you may obtain a copy of the license at. http://www.apache.org/licenses/license-2.0 . unless required by applicable law or agreed to in writing, software distributed under the license is distributed on an "as is" basis, without warranties or  conditions of any kind, either express or implied. see the license for the specific language governing permissions and limitations under the license.
:_basedir: ./
:_imagesdir: images/




pass:[<br/><br/>]


pass:[<div class="extended-quote-first"><p>]
Apache Isis' philosophy is awesome - it drives you to focus on the domain model and encourages you to practice Behavior Driven Development.
In addition, it brings the team together, sets the common platform and provides the right set of tools (Wicket Viewer OOUI, REST APIs, Swagger UI, Cucumber Framework) to work collaboratively which is simply great for the software development.
It's a fabulously fantastic framework!
A big thank you to the Apache Isis team.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Mansingh Shitole, Senior Developer, PRIME Research, Germany - Frankfurt / Mainz
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
Apache Isis enabled us to concentrate on modelling the domain and getting the UI and REST Interface with nearly no effort so we could build a fast and reliable application. Now we've started using it for the second project and I'm still very impressed by the framework and the community behind it.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Timothy Simecsek, NTT DATA Osterreich GmbH
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
We'd been looking for a RAD-tool for building our app; after trying different tools, Apache Isis gave us the most confidence for getting the job done.  It's really remarkable how easy it is to use, while contributors and users on the Isis' active mailing list are ready to help on more advanced topics.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Erik de Hair, pocos.nl
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
A fantastic framework! With Apache Isis we can prototype a deployable application in minutes rather than days.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Jeremy Branham
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
With its automatic UI and REST web services generation, Apache Isis kept our developers amazed and happy. Having had strenuous experiences with architecture and infrastructure concerns differing from project to project, it's like having back the fun in software development
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Willie Loyd Tandingan
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
Apache Isis' focus on the business domain improves communication between our end-users, architects and developers.  Having a better application in a fraction of the time and cost is something we highly appreciate.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Cesar Lugo
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
I like the guidance Apache Isis gives me for structuring code along the lines of Domain Driven Design. My first web application in plain Java without writing a single line of DDL or HTML/*Script.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Joerg Rade
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
The Apache Isis team is very supportive. They even added new functionality for Summernote when I needed a WYSIWYG editor in my prototype project.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Marianne Hagaseth
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
What interests me most about Apache Isis is its goal of making both developers and users co-owners of their domain models.  Apache Isis will be of interest to businesses who see their custom software as a strategic investment. It's not trying to be all things to all people, but it has depth and also, I predict, a bright future.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Steve Cameron
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
As students most of us prefer sticking with business logic than spending much time with UX enhancements.  Apache Isis provides a great platform to create a perfectly working prototypes with loads of inbuilt UX concerns and customizations without worrying a single bit on the GUI perspective.
And I must say this: "Great Support from the development team"
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Vishma Dias, University of Moratuwa, Sri Lanka.
pass:[</p></div>]




pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
Apache Isis has allowed us to be focused on the Domain instead of infrastructure issues. The extensive metamodel let us further automate and enhance our custom viewer and integrate with external frameworks.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Nacho Canovas
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
Support from the Apache Isis community is excellent. I sense a love and dedication that is inspiring.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Johan Doornenbal
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
Apache Isis provided us with a great starting point for our app; we simply took the todoapp archetype and used it as a template to help set up our integration tests and BDD specs.  We were productive almost immediately
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Vladimir Nisevic, A1 Telekom Austria
pass:[</p></div>]




pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
Apache Isis enabled us to focus on the problem domain and data quality and - because the UI was generated for us by the framework - not get distracted by UI concerns. Identified security issues were quickly addressed by the Apache Isis committers.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Architect
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
We use Apache Isis because of its simple and fast user interface generation.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Andreas Lechner
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
Apache Isis is an easy to learn, efficient and productive RAD platform. Further I can say it is evolving to be
"the best RAD platform" without any exaggerations. The help from the community is simply wonderful.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Theekshana Dilshan, Computer Science and Engineering, University of Moratuwa, Sri Lanka.
pass:[</p></div>]



pass:[<br/><br/>]
pass:[<div class="extended-quote-first"><p>]
Apache Isis is one of the best tools for hackathons.  Given a 2 day hackathon challenge I have the perfect framework
to create my prototype helping me to focus on business logic.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- Sunand Padmanabhan
pass:[</p></div>]



pass:[<br/><br/>]
From a Sprint retrospective, the criticism of one lead developer sounded more like praise:
pass:[<div class="extended-quote-first"><p>]
The problem is that if we show this to the customer they will think that all the work is done.
pass:[</p></div>]

pass:[<div class="extended-quote-attribution"><p>]
-- provided by Ged Byrne
pass:[</p></div>]

