{
  Scenario(name: "Fizz and buzz are concatenated together"){
    Name
    Given {
      university_calc_Calculator {
        concat {
          invoke(prefix: "Fizz", suffix: "Buzz")
        }
      }
    }
  }
}
