{
  Scenario(name: "Find department and change its name"){
    Name
    Given {
      university_dept_Departments {
        findDepartmentByName {
          invoke(name: "Classics") {
            _gqlv_meta {
              saveAs(ref: "classics_dept")
            }
          }
        }
      }
    }
    When {
      university_dept_Departments {
        findDepartmentByName {
          invoke(name: "Classics") {
            changeName {
              invokeIdempotent(newName: "Ancient History") {
                name {
                  get
                }
              }
            }
          }
        }
      }
    }
    Then {
      university_dept_Departments {
        findDepartmentByName {
          invoke(name: "Ancient History") {
            name {
              get
            }
          }
        }
      }
    }
  }
}
