{
  Scenario(name: "Find department and change its name"){
    Name

    Given {
      university_dept_Departments {
        findDepartmentByName {
          invoke(name: "Classics") {
            _meta {
              saveAs(ref: "classics_dept")
            }
          }
        }
      }
    }

    When {
      university_dept_Department(object: {ref: "classics_dept"}) {
        changeName {
          invokeIdempotent(newName: "Ancient History") {
            name {
              get
            }
          }
        }
      }
    }
  }
}
