[[UserService]]
= `UserService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The `UserService` allows the domain object to obtain the identity of the user interacting with said object.

If xref:refguide:applib-svc:testing/SudoService.adoc[`SudoService`] has been used to temporarily override the user and/or roles, then this service will report the overridden values instead.




== API and Usage

The API of `UserService` is:

[source,java]
----
public interface UserService {
    UserMemento getUser();
}
----

where in turn (the essence of) `UserMemento` is:

[source,java]
----
public final class UserMemento {
    public String getName() { /* ... */ }
    public boolean isCurrentUser(final String userName) { /* ... */ }

    public List<RoleMemento> getRoles() { /* ... */ }
    public boolean hasRole(final RoleMemento role) { /* ... */ }
    public boolean hasRole(final String roleName) { /* ... */ }
    ...
}
----

and `RoleMemento` is simpler still:

[source,java]
----
public final class RoleMemento {
    public String getName() { /* ... */ }
    public String getDescription() { /* ... */ }
    ...
}
----

The roles associated with the `UserMemento` will be based on the configured xref:security:ROOT:about.adoc[security] (typically Shiro).

In addition, when using the xref:vw:ROOT:about.adoc[Wicket viewer] there will be an additional "org.apache.isis.viewer.wicket.roles.USER" role; this is used internally to restrict access to web pages without authenticating.





== Implementation

The core framework provides a default implementation of this service (`o.a.i.core.runtime.services.user.UserServiceDefault`).




