source 'https://rubygems.org'

# only compatible with ruby 2.0 
# http://stackoverflow.com/questions/29123339/error-installed-wdm-gem-on-windows-system
gem 'wdm', '>= 0.1.0' if Gem.win_platform?


#https://github.com/guard/listen
gem 'listen', '~> 2.7' # this prevents upgrading to 3.x
gem 'asciidoctor'

#gem 'asciidoctor-diagram', '~> 1.2.0.pre
gem 'asciidoctor-diagram', '~> 1.2.1'

gem 'tilt'
gem 'thread_safe'
gem 'coderay'

#gem 'pygments'
gem 'rouge'
gem 'webrick'

gem 'launchy', '~> 2.4.3'
gem 'slop', '~> 4.1.0'
