= Apache Isis

ifndef::env-github[]
Notice: Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at
 .
 http://www.apache.org/licenses/LICENSE-2.0[http://www.apache.org/licenses/LICENSE-2.0]
 .
 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
endif::env-github[]

This directory contains the source documentation that constitutes both the Apache Isis website (including the user guide and reference guide)  It is written using http://www.methods.co.nz/asciidoc/[Asciidoc].

The website is created by running build tools (documented below) which create the HTML version of the site and guides.  This HTML is then copied to a different git repository (link:https://git-wip-us.apache.org/repos/asf?p=isis-site.git[isis-site]) which is synced by ASF infrastructure over to link:http://isis.apache.org[isis.apache.org].

If you want to contribute documentation - either just to fix a typo, or to write a how-to, or to write a longer article - then fork this repo, write the `.adoc` source file, and raise a pull request.



== Naming Conventions

For documents with inclusions, use '_' to separate out the logical hierarchy:

[source]
----
xxx-xxx/xxx-xxx.adoc
        _xxx-xxx_ppp-ppp.adoc
        _xxx-xxx_qqq-qqq.adoc
        _xxx-xxx_qqq-qqq_mmm-mmm.adoc
        _xxx-xxx_qqq-qqq_nnn-nnn.adoc
----

Any referenced images should be in subdirectories of the `images` directory: 

[source]
----
xxx-xxx/images/.
              /ppp-ppp/.
              /qqq-qqq/.
                      /mmm-mmm
                      /nnn-nnn
----

And similarly any resources should be in the `resources` subdirectory:

[source]
----
xxx-xxx/resources/.
                  ppp-ppp/.
                  qqq-qqq/.
                         /mmm-mmm/
                         /nnn-nnn/
----



== Build and Review (using Maven)

To (re)build the documentation locally prior to release, use:

[source]
----
mvn clean compile
----

The site will be generated at `target/site/index.html`.

You could then use a web server such as Python's SimpleHTTPServer to preview (so that all Javascript works correctly). However, instead we recommend using instant preview, described next.


== Instant Rebuild (using Ruby)

The ruby script, `monitor.rb` emulates the `mvn site` command, regenerating any changed Asciidoctor files to the relevant `target/site` directory. If any included files are changed then it rebuilds the parent (per the above naming convention). 

To setup:

* download and install ruby 2.0.0, from link:rubyinstaller.org/downloads[http://rubyinstaller.org/downloads/]
* download devkit for the Ruby 2.0 installation, also from link:rubyinstaller.org/downloads[http://rubyinstaller.org/downloads/]. Then follow the link:https://github.com/oneclick/rubyinstaller/wiki/Development-Kit[installation instructions] on their wiki


[NOTE]
====
We use Ruby 2.0 rather than 2.1 because the wdm gem (required to monitor the filesystem if running on Windows) is not currently compatible with Ruby 2.1.
====

To install:

[source,bash]
----
gem install bundler
bundle install
----

To run, we typically just use:

[source,bash]
----
ruby monitor.rb
----

This will start monitoring all files under `src/main/asciidoc`, and start up a web server on port 4000 so you can review results.  If any `.adoc` changes, then the appropriate HTML will be regenerated.  And, if any new assets (CSS, images etc) are added, they will be copied across.

It often makes sense to combine this with `mvn`:

[source,bash]
----
mvn clean install && ruby monitor.rb
----

This directory contains a tiny script, `r.sh`, that executes exactly the above line.

The `monitor.rb` script has a couple of other options, use `-h` flag for usage:

[source,bash]
----
ruby monitor.rb -h
----

which should print:

[source]
----
usage: monitor.rb [options]
    -p, --port       port (default: 4000)
    -b, --browser    launch browser
    -h, --help       help
----




== Publish procedure

Only Apache Isis committers can publish to link:http://isis.apache.org[isis.apache.org].

=== One-time setup

The generated site is published by copying into the `content/` directory of the https://git-wip-us.apache.org/repos/asf/isis-site.git[isis-site git repo]. You therefore need to check this out this repo.

The procedure assumes that two git repos (for https://git-wip-us.apache.org/repos/asf/isis.git[isis] itself and for isis-site) are checked out into the same parent directory, eg:

[source]
----
/APACHE/
    isis/                       # checkout of isis.git
        adocs/
            documentation/
                README.adoc     # this file you are reading right now
                ...
    isis-site/                  # checkout of isis-site.git
        content/                # the published website
----

If this isn't the case, then it is possible to override the relative directory by passing in a system property to the mvn goal; see below.

You also need to know that ASF's publishing script work from the 'asf-site' branch, NOT from the 'master' branch. Therefore, in the `isis.git` repo site:

[source]
----
git checkout asf-site
----

=== Publishing

Back in the main `isis-git.repo`, to copy the generated documents to the `isis-site.git` repo , run:

[source]
----
mvn clean package
----

This deletes the entire content of `contents`, and replaces with the content under `target/site`.  It also fixes up line endings, standardizing on unix-style LFs.

[TIP]
====
If you have checked out the `isis-site.git` repo into some other directory (relative to `isis.site.git), then this can be overridden by specifying `-Disis-site.dir=...` when calling `mvn`.
====


To copy and to also commit the generated documents to the `isis-site.git` repo , run:

[source]
----
mvn clean install
----

This will use a standard commit message (in the `isis-site.git` repo).  If you want to specify a custom message, use:

[source]
----
mvn clean install -Dmessage="ISIS-nnnn: a custom commit message"
----

Pushing the commits (in the `isis-site.git` directory, of course) will publishing the changes:

[source]
----
git push
----

Double check at http://isis.apache.org[isis.apache.org].