= Apache Isis

ifndef::env-github[]
Notice: Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at
 .
 http://www.apache.org/licenses/LICENSE-2.0[http://www.apache.org/licenses/LICENSE-2.0]
 .
 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
endif::env-github[]

This directory contains the source documentation that constitutes both the Apache Isis' documentation (meaning the website and the users' guide, the reference guide and contributors' guide)   It is written using http://www.methods.co.nz/asciidoc/[Asciidoc], specifically the link:http://asciidoctor.org/[Asciidoctor] implementation.

The website is created by running build tools (documented below) which create the HTML version of the site and guides.
You can therefore easily check the documentation before raising a pull request

So, if you want to contribute documentation - either just to fix a typo, or to write a how-to or longer article - then fork the repo, write or modify the the `.adoc` source file, and raise a pull request.


== Naming Conventions

For documents with inclusions, use '_' to separate out the logical hierarchy:

[source]
----
xxx-xxx/xxx-xxx.adoc
        _xxx-xxx_ppp-ppp.adoc
        _xxx-xxx_qqq-qqq.adoc
        _xxx-xxx_qqq-qqq_mmm-mmm.adoc
        _xxx-xxx_qqq-qqq_nnn-nnn.adoc
----

Any referenced images should be in subdirectories of the `images` directory: 

[source]
----
xxx-xxx/images/.
              /ppp-ppp/.
              /qqq-qqq/.
                      /mmm-mmm
                      /nnn-nnn
----

And similarly any resources should be in the `resources` subdirectory:

[source]
----
xxx-xxx/resources/.
                  ppp-ppp/.
                  qqq-qqq/.
                         /mmm-mmm/
                         /nnn-nnn/
----



== Build and Review (using Maven)

To (re)build the documentation locally prior to release, use:

[source]
----
sh preview-html.sh
----

The site will be generated at `target/site/index.html`, and then uses Python to start a webserver and a browser pointing at the site.




== Publish procedure

Only Apache Isis committers can publish to link:http://isis.apache.org[isis.apache.org].
See the link:http://isis.apache.org/guides/cgcom.html#_cg_asciidoc[committers' guide] for details.

