[[_ugtst_fixture-scripts_clock-fixtures]]
= Clock Fixtures (`1.16.0-SNAPSHOT`)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/



The `ClockFixture` is a pre-build fixture script that simply sets the time returned by the xref:../rgsvc/rgsvc.adoc#_rgsvc_api_ClockService[`ClockService`] to a known value.

For example, to set the clock to return "3 Sept 2014", use:

[source,java]
----
executionContext.executeChild(this, ClockFixture.setTo("2014-09-03"));
----

A variety of format strings are supported; the format "YYYY-MM-DD" (as shown above) will work in every locale.

The fixture script requires that a `FixtureClock` is initialized.
This happens automatically in any non-production environment, and in particular when running integration tests.


The `TickingClockFixture` is another, slightly more sophisticated, fixture script.



It requires that a TickingFixtureClock