= EntityChangeTracker _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Responsible for collecting the details of all changes to domain objects within a transaction.

== API

[source,java]
.EntityChangeTracker.java
----
interface EntityChangeTracker {
  void enlistCreated(ManagedObject entity)     // <.>
  void enlistDeleting(ManagedObject entity)     // <.>
  void enlistUpdating(ManagedObject entity)     // <.>
  void recognizeLoaded(ManagedObject entity)     // <.>
  void recognizePersisting(ManagedObject entity)     // <.>
  void recognizeUpdating(ManagedObject entity)     // <.>
}
----

<.> xref:#enlistCreated__ManagedObject[enlistCreated(ManagedObject)]
+
--
Publishing support: for object stores to enlist an object that has just been created, capturing a dummy value `'[NEW]'` for the pre-modification value.
--
<.> xref:#enlistDeleting__ManagedObject[enlistDeleting(ManagedObject)]
+
--
Publishing support: for object stores to enlist an object that is about to be deleted, capturing the pre-deletion value of the properties of the _ManagedObject_ .
--
<.> xref:#enlistUpdating__ManagedObject[enlistUpdating(ManagedObject)]
+
--
Publishing support: for object stores to enlist an object that is about to be updated, capturing the pre-modification values of the properties of the _ManagedObject_ .
--
<.> xref:#recognizeLoaded__ManagedObject[recognizeLoaded(ManagedObject)]
+
--
Fires the appropriate event and lifecycle callback: _LOADED_
--
<.> xref:#recognizePersisting__ManagedObject[recognizePersisting(ManagedObject)]
+
--
Fires the appropriate event and lifecycle callback: _PERSISTING_
--
<.> xref:#recognizeUpdating__ManagedObject[recognizeUpdating(ManagedObject)]
+
--
Fires the appropriate event and lifecycle callback: _UPDATING_
--

== Members

[#enlistCreated__ManagedObject]
=== enlistCreated(ManagedObject)

Publishing support: for object stores to enlist an object that has just been created, capturing a dummy value `'[NEW]'` for the pre-modification value.

Fires the appropriate event and lifecycle callback: _PERSISTED_

The post-modification values are captured when the transaction commits.

[#enlistDeleting__ManagedObject]
=== enlistDeleting(ManagedObject)

Publishing support: for object stores to enlist an object that is about to be deleted, capturing the pre-deletion value of the properties of the _ManagedObject_ .

Fires the appropriate event and lifecycle callback: _REMOVING_

The post-modification values are captured when the transaction commits. In the case of deleted objects, a dummy value `'[DELETED]'` is used as the post-modification value.

[#enlistUpdating__ManagedObject]
=== enlistUpdating(ManagedObject)

Publishing support: for object stores to enlist an object that is about to be updated, capturing the pre-modification values of the properties of the _ManagedObject_ .

Fires the appropriate event and lifecycle callback: _UPDATING_

The post-modification values are captured when the transaction commits.

[#recognizeLoaded__ManagedObject]
=== recognizeLoaded(ManagedObject)

Fires the appropriate event and lifecycle callback: _LOADED_

[#recognizePersisting__ManagedObject]
=== recognizePersisting(ManagedObject)

Fires the appropriate event and lifecycle callback: _PERSISTING_

[#recognizeUpdating__ManagedObject]
=== recognizeUpdating(ManagedObject)

Fires the appropriate event and lifecycle callback: _UPDATING_
