= EntityChangesPublisher _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Notifies xref:refguide:applib:index/services/publishing/spi/EntityChangesSubscriber.adoc[EntityChangesSubscriber] s.

== API

[source,java]
.EntityChangesPublisher.java
----
interface EntityChangesPublisher {
  void publishChangingEntities(HasEnlistedEntityChanges hasEnlistedEntityChanges)     // <.>
}
----

<.> xref:#publishChangingEntities__HasEnlistedEntityChanges[publishChangingEntities(HasEnlistedEntityChanges)]
+
--
Notifies xref:refguide:applib:index/services/publishing/spi/EntityChangesSubscriber.adoc[EntityChangesSubscriber] s of the changed entities within an _org.apache.isis.applib.services.iactn.Interaction_ , calling the _EntityChangesSubscriber#onChanging(EntityChanges)_ callback.
--

== Members

[#publishChangingEntities__HasEnlistedEntityChanges]
=== publishChangingEntities(HasEnlistedEntityChanges)

Notifies xref:refguide:applib:index/services/publishing/spi/EntityChangesSubscriber.adoc[EntityChangesSubscriber] s of the changed entities within an _org.apache.isis.applib.services.iactn.Interaction_ , calling the _EntityChangesSubscriber#onChanging(EntityChanges)_ callback.
