= CollectionSearchService
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

EXPERIMENTAL/DRAFT

If at least one xref:refguide:applib:index/services/search/CollectionSearchService.adoc[CollectionSearchService] is registered with Spring's context that handles a given domainType, viewer implementations (like Wicket Viewer) should show a quick-search prompt, which is rendered on top of the UI table that presents the collection in question.

== API

[source,java]
.CollectionSearchService.java
----
interface CollectionSearchService {
  boolean handles(Class<?> domainType)     // <.>
  BiPredicate<T, String> searchPredicate(Class<T> domainType)     // <.>
  TranslatableString searchPromptPlaceholderText(Class<?> domainType)     // <.>
  TranslationContext translationContext(Class<?> domainType)     // <.>
}
----

<.> xref:#handles_Class[handles(Class)]
+
--
Whether this service handles given type.
--
<.> xref:#searchPredicate_Class[searchPredicate(Class)]
+
--
Returns a _BiPredicate_ that filters collections of given _domainType_ by a nullable searchString.
--
<.> xref:#searchPromptPlaceholderText_Class[searchPromptPlaceholderText(Class)]
+
--
Placeholder text for the quick-search prompt.
--
<.> xref:#translationContext_Class[translationContext(Class)]
+
--
Provides the xref:refguide:applib:index/services/i18n/TranslationContext.adoc[TranslationContext] for translating the _#searchPromptPlaceholderText(Class)_ .
--

== Members

[#handles_Class]
=== handles(Class)

Whether this service handles given type.

[#searchPredicate_Class]
=== searchPredicate(Class)

Returns a _BiPredicate_ that filters collections of given _domainType_ by a nullable searchString.

For example, the searchString could be parsed into tokens, and then matched against the domain object's title say.

[#searchPromptPlaceholderText_Class]
=== searchPromptPlaceholderText(Class)

Placeholder text for the quick-search prompt.

[#translationContext_Class]
=== translationContext(Class)

Provides the xref:refguide:applib:index/services/i18n/TranslationContext.adoc[TranslationContext] for translating the _#searchPromptPlaceholderText(Class)_ .
