/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

package org.apache.isis.runtimes.dflt.runtime.system.persistence;

import org.apache.isis.applib.annotation.Aggregated;
import org.apache.isis.core.commons.components.Injectable;
import org.apache.isis.core.commons.components.SessionScopedComponent;
import org.apache.isis.core.commons.debug.DebugBuilder;
import org.apache.isis.core.commons.debug.DebuggableWithTitle;
import org.apache.isis.core.metamodel.adapter.ObjectAdapter;
import org.apache.isis.core.metamodel.adapter.oid.AggregatedOid;
import org.apache.isis.core.metamodel.adapter.oid.Oid;
import org.apache.isis.core.metamodel.adapter.oid.RootOid;
import org.apache.isis.core.metamodel.adapter.oid.RootOidDefault;
import org.apache.isis.core.metamodel.adapter.oid.TypedOid;
import org.apache.isis.core.metamodel.adapter.oid.stringable.OidStringifier;
import org.apache.isis.core.metamodel.spec.ObjectSpecId;
import org.apache.isis.core.metamodel.spec.ObjectSpecification;
import org.apache.isis.core.metamodel.spec.SpecificationLookup;
import org.apache.isis.runtimes.dflt.runtime.system.context.IsisContext;

public class OidGenerator implements DebuggableWithTitle, SessionScopedComponent, Injectable {

    private final OidStringifier oidStringifier;
    private final IdentifierGenerator identifierGenerator;
    
    public OidGenerator() {
        this(new IdentifierGeneratorDefault());
    }
    
    public OidGenerator(final IdentifierGenerator identifierGenerator) {
        this.identifierGenerator = identifierGenerator;
        this.oidStringifier = new OidStringifier(RootOidDefault.class);
    }

    
    public IdentifierGenerator getIdentifierGenerator() {
        return identifierGenerator;
    }

    /**
     * An {@link OidStringifier} to use for stringifying instances of the
     * concrete {@link Oid} generated by this generator.
     */
    public final OidStringifier getOidStringifier() {
        return oidStringifier;
    }

    // //////////////////////////////////////////////////////////////
    // open, close (session scoped)
    // //////////////////////////////////////////////////////////////

    /**
     * Default implementation does nothing.
     */
    @Override
    public void open() {
    }

    /**
     * Default implementation does nothing.
     */
    @Override
    public void close() {
    }

    
    // //////////////////////////////////////////////////////////////
    // API and mandatory hooks
    // //////////////////////////////////////////////////////////////
    
    /**
     * Create a new {@link Oid#isTransient() transient} {@link Oid} for the
     * supplied pojo, uniquely distinguishable from any other {@link Oid}.
     */
    public final RootOid createTransientOid(final Object pojo) {
        final ObjectSpecId objectSpecId = objectSpecIdFor(pojo);
        final String transientIdentifier = identifierGenerator.createTransientIdentifierFor(objectSpecId, pojo);
        return createTransient(objectSpecId, transientIdentifier);
    }

    /**
     * Creates a new id, locally unique within an aggregate root, for the specified 
     * object for use in an {@link AggregatedOid} (as returned by {@link AggregatedOid#getLocalId()}).
     * 
     * <p>
     * This is used by {@link Aggregated} references (either referenced by properties or by
     * collections).
     */
    public AggregatedOid createAggregateOid(final Object pojo, final ObjectAdapter parentAdapter) {
        final ObjectSpecId objectSpecId = objectSpecIdFor(pojo);
        final String aggregateLocalId = identifierGenerator.createAggregateLocalId(objectSpecId, pojo, parentAdapter);
        return new AggregatedOid(objectSpecId, (TypedOid) parentAdapter.getOid(), aggregateLocalId);
    }

    /**
     * Return an equivalent {@link RootOid}, but being persistent.
     * 
     * <p>
     * It is the responsibility of the implementation to determine the new unique identifier.
     * For example, the generator may simply assign a new value from a sequence, or a GUID;
     * or, the generator may use the oid to look up the object and inspect the object in order
     * to obtain an application-defined value.  
     * 
     * @param pojo - being persisted
     * @param transientRootOid - the oid for the pojo when transient.
     */
    public final RootOid createPersistent(Object pojo, RootOid transientRootOid) {

        final ObjectSpecId objectSpecId = objectSpecIdFor(pojo);
        final String persistentIdentifier = identifierGenerator.createPersistentIdentifierFor(objectSpecId, pojo, transientRootOid);
        
        return RootOidDefault.create(objectSpecId, persistentIdentifier);
    }


    // //////////////////////////////////////////////////////////////
    // Helpers
    // //////////////////////////////////////////////////////////////

    private RootOid createTransient(final ObjectSpecId objectSpecId, final String transientIdentifier) {
        return RootOidDefault.createTransient(objectSpecId, transientIdentifier);
    }

    private ObjectSpecId objectSpecIdFor(final Object pojo) {
        final Class<? extends Object> cls = pojo.getClass();
        final ObjectSpecification objectSpec = getSpecificationLookup().loadSpecification(cls);
        return objectSpec.getSpecId();
    }



    // ////////////////////////////////////////////////////////////////////
    // injectInto
    // ////////////////////////////////////////////////////////////////////

    @Override
    public void injectInto(final Object candidate) {
        if (OidGeneratorAware.class.isAssignableFrom(candidate.getClass())) {
            final OidGeneratorAware cast = OidGeneratorAware.class.cast(candidate);
            cast.setOidGenerator(this);
        }
    }


    // //////////////////////////////////////////////////////////////
    // debug
    // //////////////////////////////////////////////////////////////


    @Override
    public void debugData(final DebugBuilder debug) {
        getIdentifierGenerator().debugData(debug);
    }


    @Override
    public String debugTitle() {
        return getIdentifierGenerator().debugTitle();
    }

    
    //////////////////////////////////////////////////////////////////
    // context
    //////////////////////////////////////////////////////////////////

    protected SpecificationLookup getSpecificationLookup() {
        return IsisContext.getSpecificationLoader();
    }

}
