== Mixin actions

A number of mixin actions contribute through the `PrimitiveDoubleHolder` interface, demonstrate the use of `double` as a parameter and as a return type.
For example:

* the `updateReadOnlyProperty` action is:
+
[source,java]
----
include::holder/PrimitiveDoubleHolder_updateReadOnlyProperty.java[tags=class]
----

* the `actionReturning` action is:
+
[source,java]
----
include::holder/PrimitiveDoubleHolder_actionReturning.java[tags=class]
----

== Mixin properties

We also use the interface to contribute a mixin property:

* the `mixinProperty` property:
+
[source,java]
----
include::holder/PrimitiveDoubleHolder_mixinProperty.java[tags=class]
----

== @PropertyLayout(labelPosition=...)

To demonstrate support for label positions using `@PropertyLayout(labelPosition=...)`, the entity and view model objects both implement the extended `PrimitiveDoubleHolder2` interface:

[source,java]
----
include::holder/PrimitiveDoubleHolder2.java[tags=class]
----

<.> The default methods have annotations that are automatically inherited.
<.> Position to the left
<.> Uses `@MemberOrder` positions the properties into the appropriate `<field-set>` within the `Xxx.layout.xml` layout file.
<.> Position label on top
<.> Position label to the right
+
CAUTION: currently not supported
<.> Hide the label compleely.
