{
  rich {
    university_dept_DeptHeads {
      findHeadByName {
        invoke(name: "Prof. Dicky Horwich") {
          results {
            changeName {
              validate(newName: "Prof. Dicky Horwich!")
            }
          }
        }
      }
    }
  }
}
