The framework has built-in support for all of the Wrapper data types, including `Character`.

From here you can:

* navigate to an entity that uses the `Character` datatype
* open a view model that uses the `Character` datatype

Some properties on these domain objects are mandatory, some optional.

== Common interface

These objects both implement a common interface, `IsisClobHolder`:

[source,java]
----
include::holder/IsisClobHolder.java[tags=class]
----

There is also an extension of this interface, `IsisClobHolder2`, with default methods demonstrating the use of label positions:

[source,java]
----
include::holder/IsisClobHolder2.java[tags=class]
----

<.> The default methods have annotations that are automatically inherited.
<.> Using `@MemberOrder` positions the properties into the appropriate `<field-set>` within the `Xxx.layout.xml` layout file.


== Mixin actions

A number of mixin actions contribute through this interface, demonstrate the use of `Character` as a parameter and as a return type.
For example:

* the `updateReadOnlyProperty` action is:
+
[source,java]
----
include::holder/IsisClobHolder_updateReadOnlyProperty.java[tags=class]
----

* the `updateReadOnlyOptionalProperty` action is:
+
[source,java]
----
include::holder/IsisClobHolder_updateReadOnlyOptionalProperty.java[tags=class]
----

* the `actionReturning` action is:
+
[source,java]
----
include::holder/IsisClobHolder_actionReturning.java[tags=class]
----


* the `actionReturningCollection` action is:
+
[source,java]
----
include::holder/IsisClobHolder_actionReturningCollection.java[tags=class]
----

== Mixin properties

We also use the interface to contribute a mixin property:

* the `mixinProperty` property:
+
[source,java]
----
include::holder/IsisClobHolder_mixinProperty.java[tags=class]
----


