[[programming-model]]
= @DomainObject

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


Domain entities are persistent domain objects, and will typically be annotated with xref:refguide:applib:index/annotation/DomainObject.adoc[@DomainObject(nature=ENTITY)].

Their persistence is handled by either xref:pjpa:ROOT:about.adoc[JPA/EclipseLink] or xref:pjdo:ROOT:about.adoc[JDO/DataNucleus] ORM, with the ORM taking care of both lazy loading and also the persisting of modified ("dirty") objects.

As such, they will also require ORM metadata.
Both ORMs allow the metadata to be specified using either annotations or XML.
The following sections show the basics for both ORMs, but see their respective guides for more detail.

