= Menu
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:


Menu services provide actions to be rendered on the menu.

For the Wicket viewer, each service's actions appear as a collection of menu items of a named menu, and this menu is on one of the three menu bars provided by the Wicket viewer.
Although these can be organised using annotations, it's usually easier to use a xref:vw:ROOT:menubars-layout.adoc#file-based[`menubars.layout.xml`] file.

For the Restful Objects viewer, all menu services are shown in the services representation.

We suggest naming such classes `XxxMenu`, eg:


[source,java]
----
@DomainService(                                                 // <1>
    nature = NatureOfService.VIEW
)
public class CustomerMenu {

    @Action(semantics = SemanticsOf.SAFE)
    @ActionLayout(bookmarking = BookmarkPolicy.AS_ROOT)
    public List<Customer> findByName(                           // <2>
            @ParameterLayout(named="Name")                      // <3>
            final String name
    ) {
        return customerRepository.findByName(name);             // <4>
    }

    @Action(
            semantics = SemanticsOf.NON_IDEMPOTENT
    )
    public Customer newCustomer(...) {
        return customerRepository.newCustomer(...);
    }

    @Action(
            semantics = SemanticsOf.SAFE,
            restrictTo = RestrictTo.PROTOTYPING                 // <5>
    )
    public List<Customer> listAll() {
        return customerRepository.listAll();
    }

    @Inject
    protected CustomerRepository customerRepository;            // <6>
}
----
<1> The (Apache Isis) xref:refguide:applib-ant:DomainService.adoc[`@DomainService`] annotation is used to identify the class as a domain service.
Apache Isis scans the classpath looking for classes with this annotation, so there very little configuration other than to tell the framework which packages to scan underneath.
The `VIEW` nature indicates that this service's actions should be exposed as menu items.
<2> The `findByName` method is annotated with various Apache Isis annotations (xref:refguide:applib-ant:Action.adoc[`@Action`], xref:refguide:applib-ant:ActionLayout.adoc[`@ActionLayout`] and xref:refguide:applib-ant:MemberOrder.adoc[`@MemberOrder`] and is itself rendered in the UI as a "Find By Name" menu item underneath the "Simple Objects" menu.
<3> The xref:refguide:applib-ant:ParameterLayout.adoc[`@ParameterLayout`] provides metadata for the parameter itself, in this case its name.
+
[TIP]
====
There's no need to name the action parameters if the code is compiled using the `-parameters` flag to the Java compiler (javac); the framework will then use the name of the parameter itself.
====

<4> the action implementation delegates to an injected repository.
The framework can inject into not just other domain services but will also automatically into domain entities and view models.
There is further discussion of service injection xref:userguide:fun:programming-model.adoc#inject-services[below].
<5> xref:refguide:applib-ant:Action.adoc#restrictTo[Prototype] actions are rendered only in prototyping mode.
A "list all" action such as this can be useful when exploring the domain with a small dataset.
<6> Menu services typically delegate to an underlying repository/ies specific to the domain (rather than use `RepositoryService` directly, for example).



Not every action on the repository need to be delegated to of course (the above example does but only because it is very simple).

