= `@Parameter`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


The `@Parameter` annotation applies to action parameters collecting together all domain semantics within a single annotation.

The table below summarizes the annotation's attributes.

.`@Paramter` attributes
[cols="2,2,4a", options="header"]
|===

| Attribute
| Values (default)
| Description


|xref:rg:ant:Parameter.adoc#fileAccept[`fileAccept()`]
|Media type or file extension
|Hints the file type to be uploaded for xref:rg:cms:classes/value-types/Blob.adoc[`Blob`]
 or xref:rg:cms:classes/value-types/Clob.adoc[`Clob`]. +
 +
 Note that this does not prevent the user from uploading some other file type; rather it merely defaults the file type in the file open dialog.



|xref:rg:ant:Parameter.adoc#maxLength[`maxLength()`]
|Positive integer
|maximum number of characters for string parameters; ignored otherwise



|xref:rg:ant:Parameter.adoc#mustSatisfy[`mustSatisfy()`]
|implementation of `o.a.i.applib.spec.Specification`
|allows arbitrary validation to be applied


|xref:rg:ant:Parameter.adoc#optionality[`optionality()`]
|`MANDATORY`, `OPTIONAL` (`MANDATORY`)
|specifies a parameter is optional rather than mandatory


|xref:rg:ant:Parameter.adoc#regexPattern[regexPattern()]
|regular expression
|validates the contents of a string parameter against the regular expression pattern


|`regexPatternFlags()`
|value of flags as normally passed to `java.util.regex.` +
`Pattern#compile(...)`
|modifies the compilation of the regular expression


|`regexPatternReplacement()`
|
|Unused.


|===




For example:

[source,java]
----
public class Customer {
    public static class EmailSpecification extends AbstractSpecification<String> {
        public String satisfiesSafely(String proposed) {
            return EmailUtil.ensureValidEmail(proposed);    // <1>
        }
    }
    @Action(semantics=SemanticsOf.IDEMPOTENT)
    public Customer updateEmail(
        @Parameter(
            maxLength=30,
            mustSatisfy=EmailSpecification.class,
            optionality=Optionality.OPTIONAL,
            regexPattern = "(\\w+\\.)*\\w+@(\\w+\\.)+[A-Za-z]+",
            regexPatternFlags=Pattern.CASE_INSENSITIVE
        )
        @ParameterLayout(named="New Email Address")
        final String newEmailAddress
        ...
    }
}
----
<1> the (fictitious) `EmailUtil.ensureValid(...)` (omitted for brevity) returns a string explaining if an email is invalid



include:Parameter/fileAccept.adoc[leveloffset=+1]
include:Parameter/maxLength.adoc[leveloffset=+1]
include:Parameter/mustSatisfy.adoc[leveloffset=+1]
include:Parameter/optionality.adoc[leveloffset=+1]
include:Parameter/regexPattern.adoc[leveloffset=+1]
