:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/services/xmlsnapshot/XmlSnapshotService.html[XmlSnapshotService] exploits the framework's metamodel to create arbitrary XML serializations of domain object graphs.
One use case is for document generation/mail merge functionality, where an XML document holds the arguments to be interpolated into some output document.
As well as generating the XML document, the `XmlSnapshotService` can also generate an XSD schema document to which the XML conforms.

By default the `XmlSnapshotService` will include all properties of the domain object, but exclude any collections.
The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/Property.html#snapshot[@Property#snapshot] attribute can be used to explicitly specify whether a property should be included or excluded from the XML snapshot.
Collections, meanwhile, are specified programmatically.


== How this demo works

This page defines four properties, and one contributed collection.
The four properties are variously annotated (or not) with the different options `@Property#snapshot`.
wThe `takeXmlSnapshot` action can be used to generate to download the generated XML as a file.

In terms of code, the following are all included in the snapshot:

* the `familyName` property is explicitly included:
+
[source,java,indent=0]
----
include::PropertySnapshotPage.java[tags=annotated-included]
----
<.> explicitly include in the snapshot

* the `givenName` property is annotated as "not specified"; the default in such cases is to include
+
[source,java,indent=0]
----
include::PropertySnapshotPage.java[tags=annotated-not_specified]
----
<.> expresses no opinion, meaning that it will be included

* the `notes` property is not annotated at all; the default in such cases is to include
+
[source,java,indent=0]
----
include::PropertySnapshotPage.java[tags=no-annotation]
----
<.> not annotated, meaning it will be included

However, the following is excluded:

* the `middleInitial` property is annotated as being explicitly excluded:
+
[source,java,indent=0]
----
include::PropertySnapshotPage.java[tags=annotated-excluded]
----
<.> explicitly excluded from snapshot

The "friends" collection is not annotated, but is included programmatically in the action - as explained in the next section.

== Taking a Snapshot

The `takeSnapshot` mixin action shows how the `XmlSnapshotService` service is used:

[source,java,indent=0]
.PropertySnapshotPage_takeXmlSnapshot.java
----
include::PropertySnapshotPage_takeXmlSnapshot.java[tags=class]
----
<.> results in the "friends" collection being included in the snapshot.



== Limitations

Only basic value types are recognised by the `XmlSnapshotService`.


