= ApplicationUserStatus _(enum)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Whether the user's account is locked or unlocked.

== API

[source,java]
.ApplicationUserStatus.java
----
enum ApplicationUserStatus {
  UNLOCKED
  LOCKED
  ApplicationUserStatus parse(Boolean unlocked)
  String toString()
  boolean isUnlocked(ApplicationUserStatus status)
  boolean isLockedOrUnspecified(ApplicationUserStatus status)
  boolean canLock(ApplicationUserStatus status)     // <.>
  boolean canUnlock(ApplicationUserStatus status)     // <.>
}
----

<.> xref:#canLock_ApplicationUserStatus[canLock(ApplicationUserStatus)]
+
--
Whether can transition to state LOCKED. That is, YES if not already at that state.
--
<.> xref:#canUnlock_ApplicationUserStatus[canUnlock(ApplicationUserStatus)]
+
--
Whether can transition to state UNLOCKED. That is, YES if not already at that state.
--

== Members

[#canLock_ApplicationUserStatus]
=== canLock(ApplicationUserStatus)

Whether can transition to state LOCKED. That is, YES if not already at that state.

[#canUnlock_ApplicationUserStatus]
=== canUnlock(ApplicationUserStatus)

Whether can transition to state UNLOCKED. That is, YES if not already at that state.
