= LayoutResourceLoader
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

A simpler SPI for xref:refguide:core:index/metamodel/services/grid/GridLoaderServiceDefault.adoc[GridLoaderServiceDefault] .

== API

[source,java]
.LayoutResourceLoader.java
----
interface LayoutResourceLoader {
  Try<LayoutResource> tryLoadLayoutResource(Class<?> type, String candidateResourceName)     // <.>
  Optional<LayoutResource> lookupLayoutResource(Class<?> type, String candidateResourceName)     // <.>
}
----

<.> xref:#tryLoadLayoutResource_Class_String[tryLoadLayoutResource(Class, String)]
+
--
Try to locate and load a _LayoutResource_ by type and name.
--
<.> xref:#lookupLayoutResource_Class_String[lookupLayoutResource(Class, String)]
+
--
Optionally returns a _LayoutResource_ based on whether it could be resolved by type and name and successfully read.
--

== Members

[#tryLoadLayoutResource_Class_String]
=== tryLoadLayoutResource(Class, String)

Try to locate and load a _LayoutResource_ by type and name.

[#lookupLayoutResource_Class_String]
=== lookupLayoutResource(Class, String)

Optionally returns a _LayoutResource_ based on whether it could be resolved by type and name and successfully read.

Silently ignores exceptions underneath, if any.
