:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Whether the permission _#ALLOW grants_ or _#VETO denies_ access to an _ApplicationFeature_ .

== API

[source,java]
.ApplicationPermissionRule.java
----
enum ApplicationPermissionRule {
  ALLOW     // <.>
  VETO     // <.>
  String toString()
}
----

<.> xref:#ALLOW[ALLOW]
+
--
The permission grants the ability to view/use the _ApplicationFeature_ .
--
<.> xref:#VETO[VETO]
+
--
The permission prevents the ability to view/use the _ApplicationFeature_ .
--

== Members

[#ALLOW]
=== ALLOW

The permission grants the ability to view/use the _ApplicationFeature_ .

The xref:system:generated:index/extensions/secman/api/permission/ApplicationPermissionMode.adoc[ApplicationPermissionMode] determines whether the permission is to only view or also to use the _ApplicationFeature_ .

[#VETO]
=== VETO

The permission prevents the ability to view/use the _ApplicationFeature_ .

The xref:system:generated:index/extensions/secman/api/permission/ApplicationPermissionMode.adoc[ApplicationPermissionMode] determines whether the permission is to only view or also to use the _ApplicationFeature_ .
