= Instantiating
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



Both domain entities and view models can be instantiated using the xref:rg:svc:core-domain-api/FactoryService.adoc[`FactoryService`] provided by the framework.
For example:

[source,java]
----
Customer customer = factoryService.instantiate(Customer.class);
----

or

[source,java]
----
Dashboard dashboardVM = factoryService.instantiate(Dashboard.class);
----

When the framework instantiates the object, all services are injected into the framework, and an `ObjectCreatedEvent` xref:ug:fun:building-blocks/events/lifecycle-events.adoc[lifecycle event] will also be emitted.


For this to work the target class _must_ have a no-arg constructor.

However, you may prefer for your domain objects to have regular constructor defining their minimum set of mandatory properties.

For example:

[source,java]
----
public class Customer {

    public Customer(String reference, String firstName, String lastName) { ... }

    ...
}
----

In such cases, the domain object cannot be instantiated using `FactoryService`.
Instead the xref:rg:svc:metadata-api/ServiceRegistry.adoc[`ServiceRegistry`] service can be used to inject services:

[source,java]
----
Customer customer = new Customer(reference, firstName, lastName);
serviceRegister.injectServicesInto(customer);
----

Note that this does _not_ raise any lifecycle event.


To instantiate a mixin, a different API of `FactoryService` is used:

[source,java]
----
Customer_placeOrder placeOrderMixin = factoryService.mixin(Customer_placeOrder.class, customer);
----

Alternatively and equivalently, the mixin can be manually instantiated, and then the services injected directly:

[source,java]
----
Customer_placeOrder placeOrderMixin = new Customer_placeOrder(customer);
serviceRegistry.injectServicesInto(placeOrderMixin);
----
