:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Embedded types are a feature of the JPA ORM that an entity to a field of a composite type which groups several data fields together.
The values of the composite type are then stored inline within the entity's table.
Such embedded types have no identity in and of themselves; they are identified only by the entity that references them.

Embedded types themselves can be mutable or immutable.
When immutable, they are very similar to value types.
However, they are not quite true value types as the ORM needs to update their fields directly.
To enable that, a mutator method is required, though it can be made `private`


== How this demo works

This page object has a collection `allConstants` that just returns a set of `NumberConstantJpa` entities.
The `NumberConstantJpa` entity defines a `name` property (of type `String`) and a `numberConstant` property (of type `ComplexNumberJpa`).
It is this second property that we are interested in.

In terms of code:

* the `NumberConstantJpa` entity is defined as:
+
[source,java]
.NumberConstantJpa.java
----
include::NumberConstantJpa.java[tags=class]
----
<.> JPA `@Embedded` annotation indicates that the constituent parts of the embedded type should be stored as columns of the owning entity

* the `ComplexNumberJpa` is the embedded type:
+
[source,java]
.ComplexNumberJpa.java
----
include::ComplexNumberJpa.java[tags=class]
----
<.> JPA `@Embeddable` annotation is the companion of `@Embedded` on the owning object
<.> Indicates to the framework that this is a value rather than an entity.
Accordingly, we will also need to provide a `ValueSemanticsProvider` implementation, discussed below.
<.> provides access the fields
<.> allows the ORM to initialize the fields
<.> these fields of the embedded type are persisted as columns of the owning entity

* the `ComplexNumberJpaValueSemantics` class instructs the framework how to render the `ComplexNumberJpa` as a value.
+
[source,java,indent=0]
.ComplexNumberJpaValueSemantics.java
----
include::ComplexNumberJpaValueSemantics.java[tags=class]
----
+
In this particular demo, the value is immutable.
See elsewhere for examples of value types that can be mutated.
+
** the `getRenderer()` method:
+
[source,java,indent=0]
.ComplexNumberJpaValueSemantics.java
----
include::ComplexNumberJpaValueSemantics.java[tags=getRenderer]
----
+
** the `compose()`/`decompose()` methods:
+
[source,java,indent=0]
.ComplexNumberJpaValueSemantics.java
----
include::ComplexNumberJpaValueSemantics.java[tags=compose]
----

** the `getParser()` method allows new values to be entered as strings:
+
[source,java,indent=0]
.ComplexNumberJpaValueSemantics.java
----
include::ComplexNumberJpaValueSemantics.java[tags=getParser]
----
+
WARNING: this feature is incomplete; being tracked by https://issues.apache.org/jira/browse/CAUSEWAY-3474[CAUSEWAY-3474].
The workaround is to omit defining a parser and instead use the in-built 'nested' editing of the component parts.
