[[_rgant-PreDestroy]]
= `@PreDestroy` (`javax`)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `@javax.annotation.PreDestroy` annotation, as defined in link:https://jcp.org/en/jsr/detail?id=250[JSR-250], recognized by Apache Isis as a callback method on domain services to be called just as they go out of scope.


For the default application-scoped (singleton) domain services, this means that the method, if present, is called just prior to the termination of the application.  For xref:rg:ant:rgant.adoc#_rgant-RequestScoped[`@RequestScoped`] domain services, the method is called at the end of the request.

The signature of the method is:

[source,java]
----
@PreDestroy                         <1>
public void deinit() { ... }    <2>
----
<1> It is not necessary to annotate the method with xref:rg:ant:rgant.adoc#_rgant-Programmatic[`@Programmatic`]; it will be automatically excluded from the Apache Isis metamodel.
<2> the method can have any name, but must have `public` visibility, and accept no arguments.

A common use case is for domain services that interact with the xref:rg:svc:rgsvc.adoc#_rgsvc_core-domain-api_EventBusService[`EventBusService`].  For example:

[source,java]
----
@DomainService(nature=NatureOfService.DOMAIN)
public class MySubscribingService {
    @PostConstruct
    public void init() {
        eventBusService.register(this);
    }
    @PreDestroy
    public void deinit() {
        eventBusService.unregister(this);
    }
    ...
    @javax.inject.Inject
    EventBusService eventBusService;
}
----

[TIP]
====
In this particular use case, it is generally simpler to just subclass from xref:rg:cms:rgcms.adoc#_rgcms_classes_super_AbstractSubscriber[`AbstractSubscriber`].
====

Other use cases include obtaining connections to external datasources, eg subscribing to an ActiveMQ router, say, or initializing/cleaning up a background scheduler such as Quartz.



See also xref:rg:ant:rgant.adoc#_rgant-PostConstruct[`@PostConstruct`]