[[_rgant-Collection_notPersisted]]
= `notPersisted()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The (somewhat misnamed) `notPersisted()` attribute indicates that the collection should be excluded from any snapshots generated by the xref:rg:svc:rgsvc.adoc#_rgsvc_integration-api_XmlSnapshotService[`XmlSnapshotService`].


[WARNING]
====
This annotation does _not_ specify that a collection is not persisted in the JDO/DataNucleus objectstore.  See below for details as to how to additionally annotate the collection for this.
====


For example:

[source,java]
----
public class Customer {
    @Collection(notPersisted=true)
    public SortedSet<Order> getPreviousOrders() {...}
    public void setPreviousOrder(SortedSet<Order> previousOrders) {...}
    ...
}
----

Historically this annotation also hinted as to whether the collection's contents should be persisted in the object store.  However, the JDO/DataNucleus objectstore does not recognize this annotation.  Thus, to ensure that a collection is actually not persisted, it should *also* be annotated with `@javax.jdo.annotations.NotPersistent`.

For example:

[source,java]
----
public class Customer {
    @Collection(notPersisted=true)             // <1>
    @javax.jdo.annotations.NotPersistent       // <2>
    public SortedSet<Order> getPreviousOrders() {...}
    public void setPreviousOrder(SortedSet<Order> previousOrders) {...}
    ...
}
----
<1> ignored by Apache Isis
<2> ignored by JDO/DataNucleus



Alternatively, if the collection is derived, then providing only a "getter" will also work:

[source,java]
----
public class Customer {
    public SortedSet<Order> getPreviousOrders() {...}
    ...
}
----


== See also

This attribute is also supported for xref:rg:ant:rgant.adoc#_rgant-Property_notPersisted[properties].

