= Non-persisted Objects

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The xref:refguide:applib:index/ViewModel.adoc[ViewModel] interface can be implemented by a view model domain object to provide full control over its serialization to and from a memento.

TIP: There is a more in-depth discussion on view models in the xref:userguide:fun:view-models.adoc[user guide] and the xref:userguide:fun:overview.adoc#view-models[user guide overview].

The very similar xref:refguide:applib:index/RecreatableDomainObject.adoc[RecreatableDomainObject] also provides the same capability; the distinction is simply that the latter makes more sense for domain objects that conceptually are entities but are not to be persisted by JDO or JPA.

