The framework has built-in support for all of the Wrapper data types, including `Boolean`.

From here you can:

* navigate to an entity that uses the `Boolean` datatype
* open a view model that uses the `Boolean` datatype

Some properties on these domain objects are mandatory, some optional.

== Common interface

These objects both implement a common interface, `WrapperBooleanHolder`:

[source,java]
----
include::holder/WrapperBooleanHolder.java[tags=class]
----

There is also an extension of this interface, `WrapperBooleanHolder2`, with default methods demonstrating the use of label positions:

[source,java]
----
include::holder/WrapperBooleanHolder2.java[tags=class]
----

<.> The default methods have annotations that are automatically inherited.
<.> Using `@MemberOrder` positions the properties into the appropriate `<field-set>` within the `Xxx.layout.xml` layout file.


== Mixin actions

A number of mixin actions contribute through this interface, demonstrate the use of `Boolean` as a parameter and as a return type.
For example:

* the `updateReadOnlyProperty` action is:
+
[source,java]
----
include::holder/WrapperBooleanHolder_updateReadOnlyOptionalProperty.java[tags=class]
----

* the `updateReadOnlyOptionalProperty` action is:
+
[source,java]
----
include::holder/WrapperBooleanHolder_updateReadOnlyOptionalProperty.java[tags=class]
----

* the `actionReturning` action is:
+
[source,java]
----
include::holder/WrapperBooleanHolder_actionReturning.java[tags=class]
----


* the `actionReturningCollection` action is:
+
[source,java]
----
include::holder/WrapperBooleanHolder_actionReturningCollection.java[tags=class]
----

== Mixin properties

We also use the interface to contribute a mixin property:

* the `mixinProperty` property:
+
[source,java]
----
include::holder/WrapperBooleanHolder_mixinProperty.java[tags=class]
----


