= `@Action`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


The `@Action` annotation groups together all domain-specific metadata for an invokable action on a domain object or domain service.

[source,java]
----
include::refguide:applib-ant:example$annotation/Action.java[tags="refguide"]
----
<.> xref:refguide:applib-ant:Action.adoc#associatewith[`associateWith()`]
+
associates an action with another property or collection of the action.

<.> `associateWithSequence()`
+
the ordering of multiple actions associated with another property/collection.

<.> xref:refguide:applib-ant:Action.adoc#command[`command()`]
whether the action invocation should be reified into a `Command` object using the xref:refguide:applib-svc:CommandContext.adoc[`CommandContext`] service:

<.> `commandExecuteIn()`
+
Whether to execute the command immediately, or to persist it (assuming that an appropriate implementation of xref:refguide:applib-svc:CommandService.adoc[`CommandService`] has been configured) such that a background scheduler can execute the command asynchronously

<.> `commandPersistence()`
+
Whether the reified `Command` (as provided by the `CommandContext` domain service) should actually be persisted (assuming an appropriate implementation of xref:refguide:applib-svc:CommandService.adoc[`CommandService`] has been configured).

<.> `commandDtoProcessor()`
+
If the `Command` also implements `CommandWithDto` (meaning that it can return a `CommandDto`, in other words be converted into an XML memento), then optionally specifies a processor that can refine this XML.

<.> xref:refguide:applib-ant:Action.adoc#domainevent[`domainEvent()`]
+
The event type to be posted to the xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`] to broadcast the action's business rule checking (hide, disable, validate) and its invocation (pre-execute and post-execute).

<.> xref:refguide:applib-ant:Action.adoc#hidden[`hidden()`]
+
Indicates where (in the UI) the action should be hidden from the user.

<.> xref:refguide:applib-ant:Action.adoc#publishing[`publishing()`]
+
Whether the action invocation should be published to the registered xref:refguide:applib-svc:PublisherService.adoc[`PublisherService`].

<.> xref:refguide:applib-ant:Action.adoc#restrictto[`restrictTo()`]
+
Whether the action is only available in prototyping mode, or whether it is available also in production mode.

<.> xref:refguide:applib-ant:Action.adoc#semantics[`semantics()`]
+
The action's semantics (ie whether objects are modified as the result of invoking this action, and if so whether reinvoking the action would result in no further change; if not whether the results can be cached for the remainder of the request).
+
The `...ARE_YOU_SURE` variants cause a confirmation dialog to be displayed in the xref:vw:ROOT:about.adoc[Wicket viewer].

<.> xref:refguide:applib-ant:Action.adoc#typeof[`typeOf()`]
+
If the action returns a collection, hints as to the run-time type of the objects within that collection (as a fallback)


For example:

[source,java]
----
public class ToDoItem {
    public static class CompletedEvent extends ActionDomainEvent<ToDoItem> { }
    @Action(
        command=CommandReification.ENABLED,
        commandExecuteIn=CommandExecuteIn.FOREGROUND,          // <1>
        commandPersistence=CommandPersistence.NOT_PERSISTED,   // <2>
        domainEvent=CompletedEvent.class,
        hidden = Where.NOWHERE,                                // <3>
        invokeOn = InvokeOn.OBJECT_ONLY,                       // <4>
        publishing = Publishing.ENABLED,
        semantics = SemanticsOf.IDEMPOTENT
    )
    public ToDoItem completed() { /* ... */ }
}
----
<1> default value, so could be omitted
<2> default value, so could be omitted
<3> default value, so could be omitted
<4> default value, so could be omitted









include::Action/associateWith.adoc[leveloffset=+1]
include::Action/command.adoc[leveloffset=+1]
include::Action/domainEvent.adoc[leveloffset=+1]
include::Action/hidden.adoc[leveloffset=+1]
include::Action/invokeOn.adoc[leveloffset=+1]
include::Action/publishing.adoc[leveloffset=+1]
include::Action/restrictTo.adoc[leveloffset=+1]
include::Action/semantics.adoc[leveloffset=+1]
include::Action/typeOf.adoc[leveloffset=+1]
