[#DomainObject]
= `@DomainObject`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



The `@DomainObject` annotation applies to domain objects, collecting together all domain semantics within a single annotation.

== Main API

[source,java]
----
include::refguide:applib-ant:example$annotation/DomainObject.java[tags="refguide"]
----
<.> xref:refguide:applib-ant:DomainObject.adoc#auditing[`auditing()`]
+
Indicates whether each of the changed properties of an object should be submitted to the registered
xref:refguide:applib-svc:AuditerService.adoc[`AuditerService`](s) (Does only apply to entity objects.)

<.> xref:refguide:applib-ant:DomainObject.adoc#autoCompleteRepository[`autoCompleteRepository()`]
+
Nominate a method on a domain service to be used for looking up instances of the domain object

<.> xref:refguide:applib-ant:DomainObject.adoc#autoCompleteAction[`autoCompleteAction()`]
+
Override the method name to use on the auto-complete repository

<.> xref:refguide:applib-ant:DomainObject.adoc#bounding[`bounding()`]
+
Whether the number of instances of this domain class is relatively small (a "bounded" set), such that instances could be selected from a drop-down list box or similar.

<.> xref:refguide:applib-ant:DomainObject.adoc#changingEntitiesDispatch[`changingEntitiesDispatch()`]
+
Whether entity changes, captured as `ChangingEntities` should be dispatched to xref:refguide:applib-svc:ChangingEntitiesListener.adoc[`ChangingEntitiesListener`](s). (Does only apply to entity objects.)

<.> xref:refguide:applib-ant:DomainObject.adoc#editing[`editing()`]
+
Whether the object's properties and collections can be edited or not (ie whether the instance should be considered to be immutable)

<.> `editingDisabledReason()`
+
The default reason why the object's properties and collections cannot be edited.

<.> xref:refguide:applib-ant:DomainObject.adoc#mixinMethod[`mixinMethod()`]
+
How to recognize the "reserved" method name, meaning that the mixin's own name will be inferred from the mixin type.
Typical examples are "exec", "execute", "invoke", "apply" and so on.
The default "reserved" method name is `$$`.

<.> xref:refguide:applib-ant:DomainObject.adoc#nature[`nature()`]
+
Whether the domain object logically is an entity (part of the domain layer) or is a view model (part of the application layer); or is a mixin.
If an entity, indicates how its persistence is managed.

<.> xref:refguide:applib-ant:DomainObject.adoc#objectType[`objectType()`]
+
Specify an alias for the domain class used to uniquely identify the object both within the Apache Isis runtime and externally



== Entity Lifecycle API

These attributes define the events to be fired throughout an the persistence lifecycle of a domain entity:

[source,java]
----
include::refguide:applib-ant:example$annotation/DomainObject.java[tags="refguide-lifecycle-events"]
----
<.> xref:refguide:applib-ant:DomainObject.adoc#createdLifecycleEvent[`createdLifecycleEvent()`]
+
The event type to be posted to the xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`] whenever an instance is created

<.> xref:refguide:applib-ant:DomainObject.adoc#persistingLifecycleEvent[`persistingLifecycleEvent()`]
+
The event type to be posted to whenever an instance is about to be persisted

<.> xref:refguide:applib-ant:DomainObject.adoc#persistedLifecycleEvent[`persistedLifecycleEvent()`]
+
The event type to be posted whenever an instance has just been persisted

<.> xref:refguide:applib-ant:DomainObject.adoc#loadedLifecycleEvent[`loadedLifecycleEvent()`]
+
The event type to be posted whenever an instance has just been loaded from the datastore

<.> xref:refguide:applib-ant:DomainObject.adoc#removingLifecycleEvent[`removingLifecycleEvent()`]
+
The event type to be posted whenever an instance is about to be deleted

<.> xref:refguide:applib-ant:DomainObject.adoc#updatedLifecycleEvent[`updatedLifecycleEvent()`]
+
The event type to be posted whenever an instance has just been updated

<.> xref:refguide:applib-ant:DomainObject.adoc#updatingLifecycleEvent[`updatingLifecycleEvent()`]
+
The event type to be posted whenever an instance is about to be updated

== Domain Events API

These attributes define the events to be fired when a domain object's members (its actions, properties and collections) are interacted with.

These attributes define the default event types; they can be overridden for each specific domain member.

[source,java]
----
include::refguide:applib-ant:example$annotation/DomainObject.java[tags="refguide-domain-events"]
----
<.> `actionDomainEvent()`
+
The event type to be posted to the xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`] whenever an action of the domain object is interacted with (if not overridden using xref:refguide:applib-ant:Action.adoc#domainEvent[`@Action#domainEvent()]`).

<.> `propertyDomainEvent()`
+
The event type to be posted to the xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`] whenever a property of the domain object is interacted with (if not overridden using xref:refguide:applib-ant:Property.adoc#domainEvent[`@Property#domainEvent()]`).

<.> `collectionDomainEvent()`
+
The event type to be posted to the xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`] whenever a collection of the domain object is interacted with (if not overridden using xref:refguide:applib-ant:Collection.adoc#domainEvent[`@Collection#domainEvent()]`).


// TODO: v2: currently missing subpages for these attributes.

For example:

[source,java]
----
@DomainObject(
    auditing=Auditing.ENABLED,
    autoCompleteRepository=CustomerRepository.class
    editing=Editing.ENABLED,                            // <.>
    updatedLifecycleEvent=Customer.UpdatedEvent.class

)
public class Customer {
    ...
}
----
<.> default value, so could be omitted




include::DomainObject/auditing.adoc[leveloffset=+1]
include::DomainObject/autoCompleteRepository.adoc[leveloffset=+1]
include::DomainObject/bounding.adoc[leveloffset=+1]
include::DomainObject/createdLifecycleEvent.adoc[leveloffset=+1]
include::DomainObject/editing.adoc[leveloffset=+1]
include::DomainObject/loadedLifecycleEvent.adoc[leveloffset=+1]
include::DomainObject/mixinMethod.adoc[leveloffset=+1]
include::DomainObject/nature.adoc[leveloffset=+1]
include::DomainObject/persistedLifecycleEvent.adoc[leveloffset=+1]
include::DomainObject/persistingLifecycleEvent.adoc[leveloffset=+1]
include::DomainObject/objectType.adoc[leveloffset=+1]
include::DomainObject/publishing.adoc[leveloffset=+1]
include::DomainObject/removingLifecycleEvent.adoc[leveloffset=+1]
include::DomainObject/updatingLifecycleEvent.adoc[leveloffset=+1]
include::DomainObject/updatedLifecycleEvent.adoc[leveloffset=+1]
