[#DomainServiceLayout]
= `@DomainServiceLayout`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



The `@DomainServiceLayout` annotation applies to domain services, collecting together all view layout semantics within a single annotation.

[TIP]
====
You will also find some additional material in the xref:userguide:fun:ui.adoc#menu-bars-layout[user guide].
====

The annotation is:

[source,java]
----
include::refguide:applib-ant:example$annotation/DomainServiceLayout.java[tags="refguide"]
----
<.> xref:refguide:applib-ant:DomainServiceLayout.adoc#menuBar[`menuBar()`]
+
The menubar in which the menu that holds this service's actions should reside:
+
[source,java]
----
include::refguide:applib-ant:example$annotation/DomainServiceLayout.java[tags="refguide-menu-bar",indent=0]
----

<.> xref:refguide:applib-ant:DomainServiceLayout.adoc#named[`named()`]
+
Name of this class (overriding the name derived from its name in code)


For example:

[source,java]
----
@DomainService
@DomainServiceLayout(
    menuBar=MenuBar.PRIMARY,
    named="ToDos"
)
public class ToDoItems {
    ...
}
----

include::DomainServiceLayout/menuBar.adoc[leveloffset=+1]
include::DomainServiceLayout/named.adoc[leveloffset=+1]
