= `@MemberOrder`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


// TODO: v2: replace @MemberOrder#name() with @PropertyLayout#group(); replace @MemberOrder#sequence() with @PropertyLayout#sequence().

The `@MemberOrder` annotation is used to specify the relative order of domain object members, that is: properties, collections and actions.

[source,java]
----
include::refguide:applib-ant:example$annotation/MemberOrder.java[tags="refguide"]
----

The annotation defines two attributes:

* xref:refguide:applib-ant:MemberOrder.adoc#name[`name()`]
* xref:refguide:applib-ant:MemberOrder.adoc#sequence[`sequence()`]

As this is an important topic, there is a xref:vw:ROOT:layout.adoc[separate chapter] that discussed object layout in full.


[TIP]
====
The annotation is one of a handful (others including xref:refguide:applib-ant:Collection.adoc[`@Collection`], xref:refguide:applib-ant:CollectionLayout.adoc[`@CollectionLayout`], xref:refguide:applib-ant:Property.adoc[`@Property`]) and xref:refguide:applib-ant:PropertyLayout.adoc[`@PropertyLayout`] that can also be applied to the field, rather than the getter method.
 This is specifically so that boilerplate-busting tools such as link:https://projectlombok.org/[Project Lombok] can be used.
====


