[#PropertyLayout]
= `@PropertyLayout`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


The `@PropertyLayout` annotation applies to properties collecting together all UI hints within a single annotation.

[source,java]
----
include::refguide:applib-ant:example$annotation/PropertyLayout.java[tags="refguide"]
----
<.> xref:refguide:applib-ant:PropertyLayout.adoc#cssClass[`cssClass()`]
+
The css class that a property should have, to allow more targetted styling in xref:refguide:config:application-specific/application-css.adoc[`application.css`]

<.> xref:refguide:applib-ant:PropertyLayout.adoc#describedAs[`describedAs()`]
+
Description of this property, eg to be rendered in a tooltip.

<.> xref:refguide:applib-ant:PropertyLayout.adoc#hidden[`hidden()`]
+
Indicates where (in the UI) the property should be hidden from the user.

<.> xref:refguide:applib-ant:PropertyLayout.adoc#labelPosition[`labelPosition()`]
+
In forms, the positioning of the label relative to the property value. +
+
Defaults is `LEFT`, unless xref:refguide:applib-ant:PropertyLayout.adoc#multiLine[`multiLine`] in which case `TOP`.
The value `RIGHT` is only supported for boolean properties.
+
It is also possible to change the default through a xref:refguide:config:configuring-core.adoc#isis-viewers-propertyLayout-labelPosition[configuration property]

<.> xref:refguide:applib-ant:PropertyLayout.adoc#multiLine[`multiLine()`]
+
For string properties, render as a text area over multiple lines.  +
+
If set > 1, then xref:refguide:applib-ant:PropertyLayout.adoc#labelPosition[`labelPosition`] defaults to TOP.

<.> xref:refguide:applib-ant:PropertyLayout.adoc#named[`named()`]
+
To override the name inferred from the collection's name in code. +
+
A typical use case is if the desired name is a reserved Java keyword, such as `default` or `package`.

<.> `namedEscaped()`
+
Whether to HTML escape the name of this property.

<.> xref:refguide:applib-ant:PropertyLayout.adoc#navigable[`navigable()`]
+
Whether a property should be used as the navigable parent (parent breadcrumb) of this object

<.> xref:refguide:applib-ant:PropertyLayout.adoc#promptStyle[`promptStyle()`]
+
How a property prompt should be displayed within the UI

<.> xref:refguide:applib-ant:PropertyLayout.adoc#renderDay[`renderDay()`]
+
For date properties only, render the date as one day prior to the actually stored date.

<.> xref:refguide:applib-ant:PropertyLayout.adoc#repainting[`repainting()`]
+
Indicates that the value held by the property never changes over time (even if other properties of the object do change).
+
Used as a hint to the viewer not to redraw the property if possible after an AJAX update.

<.> xref:refguide:applib-ant:PropertyLayout.adoc#typicalLength[`typicalLength()`]
+
The typical entry length of a field, use to determine the optimum width for display



For example:

[source,java]
----
public class ToDoItem {
    @PropertyLayout(
        cssClass="x-key",
        named="Description of this <i>item</i>",
        namedEscaped=false,
        describedAs="What needs to be done",
        labelPosition=LabelPosition.LEFT,
        typicalLength=80
    )
    public String getDescription() { /* ... */ }
    ...
}
----

It is also possible to apply the annotation to actions of domain services that are acting as contributed properties.



[TIP]
====
As an alternative to using the `@PropertyLayout` annotation, a xref:userguide:fun:ui.adoc#object-layout[file-based layout] can be used (and is generally to be preferred since it is more flexible/powerful).
====





[TIP]
====
The annotation is one of a handful (others including xref:refguide:applib-ant:Collection.adoc[`@Collection`], xref:refguide:applib-ant:CollectionLayout.adoc[`@CollectionLayout`] and xref:refguide:applib-ant:Property.adoc[`@Property`]) that can also be applied to the field, rather than the getter method.  This is specifically
so that boilerplate-busting tools such as link:https://projectlombok.org/[Project Lombok] can be used.
====









include::PropertyLayout/cssClass.adoc[leveloffset=+1]
include::PropertyLayout/describedAs.adoc[leveloffset=+1]
include::PropertyLayout/hidden.adoc[leveloffset=+1]
include::PropertyLayout/labelPosition.adoc[leveloffset=+1]
include::PropertyLayout/multiLine.adoc[leveloffset=+1]
include::PropertyLayout/named.adoc[leveloffset=+1]
include::PropertyLayout/navigable.adoc[leveloffset=+1]
include::PropertyLayout/promptStyle.adoc[leveloffset=+1]
include::PropertyLayout/renderDay.adoc[leveloffset=+1]
include::PropertyLayout/typicalLength.adoc[leveloffset=+1]
include::PropertyLayout/repainting.adoc[leveloffset=+1]
