= `@RequestScoped` (`javax`)

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.




The `@javax.enterprise.context.RequestScoped` link:https://jcp.org/en/jsr/detail?id=299[JSR-299] CDI annotation is used to specify that a xref:refguide:applib-ant:DomainService.adoc[domain service] should be request-scoped rather than a singleton.

Although Apache Isis does not (currently) leverage CDI, the semantics are the same as request-scoped service; a new instance is created for each HTTP request, reserved for the exclusive use of all objects interacted with during that request.

One of the built-in domain services that uses this annotation is xref:refguide:applib-svc:Scratchpad.adoc[`Scratchpad`], intended to allow the arbitrary sharing of data between objects.  Here is the full source code of this service is:


[source,java]
----
@DomainService(
        nature = NatureOfService.DOMAIN
)
@RequestScoped
public class Scratchpad {
    private final Map<Object, Object> userData = Maps.newHashMap();   // <1>
    @Programmatic
    public Object get(Object key) {
        return userData.get(key);                                     // <2>
    }
    @Programmatic
    public void put(Object key, Object value) {
        userData.put(key, value);                                     // <3>
    }
    @Programmatic
    public void clear() {
        userData.clear();                                             // <4>
    }
}
----
<1> Provides a mechanism for each object being acted upon to pass data to the next object.
<2> Obtain user-data, as set by a previous object being acted upon.
<3> Set user-data, for the use of a subsequent object being acted upon.
<4> Clear any user data.


The vast majority of domain services in Apache Isis tend to be singletons (which requires no special annotation); but as you can see setting up request-scoped services is very straightforward.

[NOTE]
====
Behind the covers Apache Isis creates a (singleton) wrapper for the domain service; the individual request-scoped instances are held in a thread-local of this wrapper.  One consequence of this implementation is that request-scoped methods should not be marked as `final`.
====
