= ApplicationFeatureDefault
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Canonical application feature, identified by xref:refguide:applib:index/services/appfeat/ApplicationFeatureId.adoc[ApplicationFeatureId] , and wired together with other application features and cached by xref:refguide:applib:index/services/appfeat/ApplicationFeatureRepository.adoc[ApplicationFeatureRepository] .

Note that this is NOT a view model; instead it can be converted to a string using methods of xref:refguide:applib:index/services/appfeat/ApplicationFeatureRepository.adoc[ApplicationFeatureRepository] .

== API

[source,java]
.ApplicationFeatureDefault.java
----
class ApplicationFeatureDefault {
  ApplicationFeatureDefault(ApplicationFeatureId featureId)
  void addToContents(ApplicationFeatureId contentId)
  void addToMembers(ApplicationFeatureId memberId, ApplicationMemberSort memberSort)
  int compareTo(ApplicationFeature other)
  boolean equals(Object obj)
  int hashCode()
  String toString()
}
----

