[[_rgsvc_presentation-layer-spi_ContentMappingService]]
= `ContentMappingService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/



The `ContentMappingService` supports the (default implementation of the) xref:../rgfis/rgfis.adoc#_rgfis_presentation-layer_ContentNegotiationService[`ContentNegotiationService`] enabling the xref:../ugvro/ugvro.adoc#[RestfulObjects viewer] to represent domain objects in some other format as specified by the HTTP `Accept` header.

See xref:../rgfis/rgfis.adoc#_rgfis_presentation-layer_ContentNegotiationService[`ContentNegotiationService`] for further discussion.


[NOTE]
====
Unlike most other domain services, the framework (that is, `ContentNegotiationService`) will check _all_ available
implementations of `ContentMappingService` to convert the domain object to the requested media type, rather than merely
the first implementation found; in other words it uses the chain-of-responsibility pattern.  Services are checked
in the ordering defined by xref:../rgant/rgant.adoc#_rgant-DomainServiceLayout_menuOrder[`@DomainServiceLayout#menuOrder()`]).
The mapped object used will be the first non-`null` result returned by an implementation.
====



== SPI

The SPI defined by this service is:

[source,java]
----
public interface ContentMappingService {
    Object map(Object object,                           // <1>
               List<MediaType> acceptableMediaTypes);   // <2>
}

----
<1> typically the input is a domain object (whose structure might change over time), and the output is a DTO (whose structure is guaranteed to be preserved over time)
<2> as per the caller's HTTP `Accept` header




[[_rgsvc_presentation-layer-spi_ContentMappingService_implementations]]
== Implementations

The framework provides two implementations of this service, both in support of the xref:../rgsvc/rgsvc.adoc#_rgsvc_application-layer-spi_CommandService[`CommandService`] SPI.

By way of background: implementations of the SPI `CommandService` work with custom implementations of the `Command` interface, typically being persisted to a datastore.
The `CommandWithDto` interface is a subtype of `Command` for implementations that can be reified into xref:../rgcms/rgcms.adoc#_rgcms_schema-cmd[`CommandDto`] XML instances.
One implementation that does this is the (non-ASF) link:http://platform.incode.org[Incode Platform^]'s command module.

For framework implementations of `ContentMappingService` allow domain service actions that return ``CommandDto``s (either singularly or in a list) to be converted into XML documents:

* `o.a.i.applib.services.conmap.ContentMappingServiceForCommandDto` will map any single instance of a `CommandWithDto` into a `CommandDto` XML document
* `o.a.i.applib.services.conmap.ContentMappingServiceForCommandsDto` will map list of ``CommandWithDto``s into a `CommandsDto` XML document, and will wrap any single instance of a `CommandWithDto` into a singleton list and thence into a `CommandsDto` XML document.

If the action invocation or property edit represent provides an implementation of a `CommandDtoProcessor` (by way of xref:../rgant/rgant.adoc#_rgant-Action_command[`@Action#commandDtoProcessor()`] or xref:../rgant/rgant.adoc#_rgant-Property_command[`@Property#commandDtoProcessor()`]) then this is also called to post-process the persisted `CommandDto` if required.
A typical use case for this is to dynamically add in serialized ``Blob``s or ``Clob``s, the values of which are not captured by default in `CommandDto`.

To support the writing of custom implementations of this interface, the framework also provides `ContentMappingService.Util` which includes a couple of convenience utilities:

[source,java]
----
public static class Util {
    public static String determineDomainType(
        final List<MediaType> acceptableMediaTypes) { ... }
    public static boolean isSupported(
            final Class<?> clazz,
            final List<MediaType> acceptableMediaTypes) { ... }
}
----




== Related Services

This service is a companion to the default implementation of the xref:../rgfis/rgfis.adoc#_rgfis_presentation-layer_ContentNegotiationService[`ContentNegotiationService`].

The framework implementations of `ContentMappingService` use the xref:rgsvc.adoc#_rgsvc_metadata-api_MetamodelService[`MetaModelService`] to lookup any custom implementations of `CommandDtoProcessor`.