The framework has built-in support for a number of temporal types, including `joda.time.LocalDateTime`.

From here you can:

* navigate to an entity that uses the `joda.time.LocalDateTime` datatype
* open a view model that uses the `joda.time.LocalDateTime` datatype

Some properties on these domain objects are mandatory, some optional.

== Common interface

These objects both implement a common interface, `JodaLocalDateTimeHolder`:

[source,java]
----
include::holder/JodaLocalDateTimeHolder.java[tags=class]
----

There is also an extension of this interface, `JodaLocalDateTimeHolder2`, with default methods demonstrating the use of label positions:

[source,java]
----
include::holder/JodaLocalDateTimeHolder2.java[tags=class]
----

<.> The default methods have annotations that are automatically inherited.
<.> Using `@MemberOrder` positions the properties into the appropriate `<field-set>` within the `Xxx.layout.xml` layout file.


== Mixin actions

A number of mixin actions contribute through this interface, demonstrate the use of `joda.time.LocalDateTime` as a parameter and as a return type.
For example:

* the `updateReadOnlyProperty` action is:
+
[source,java]
----
include::holder/JodaLocalDateTimeHolder_updateReadOnlyProperty.java[tags=class]
----

* the `updateReadOnlyOptionalProperty` action is:
+
[source,java]
----
include::holder/JodaLocalDateTimeHolder_updateReadOnlyOptionalProperty.java[tags=class]
----

* the `actionReturning` action is:
+
[source,java]
----
include::holder/JodaLocalDateTimeHolder_actionReturning.java[tags=class]
----


* the `actionReturningCollection` action is:
+
[source,java]
----
include::holder/JodaLocalDateTimeHolder_actionReturningCollection.java[tags=class]
----

== Mixin properties

We also use the interface to contribute a mixin property:

* the `mixinProperty` property:
+
[source,java]
----
include::holder/JodaLocalDateTimeHolder_mixinProperty.java[tags=class]
----


