= Downloads

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



Apache Causeway&trade; software is a framework for rapidly developing domain-driven apps in Java.
Write your business logic in entities, domain services and repositories, and the framework dynamically generates a representation of that domain model as a webapp or RESTful API.
Use for prototyping or production.




== Getting Started

If you just want to get going quickly, we suggest using our xref:docs:starters:helloworld.adoc[HelloWorld] or xref:docs:starters:simpleapp.adoc[SimpleApp] starter apps.



== Formal Releases

If you want to build Apache Causeway from formally released source tarballs, you can download from here:

* 3.x release:
+
link:https://dlcdn.apache.org/causeway/causeway-bom-{page-causewayreleaseversion}-source-release.zip[causeway-bom-{page-causewayreleaseversion}-source-release.zip] (link:https://downloads.apache.org/causeway/causeway-bom-{page-causewayreleaseversion}-source-release.zip.asc[asc], link:https://downloads.apache.org/causeway/causeway-bom-{page-causewayreleaseversion}-source-release.zip.sha512[sha512])

:page-causewayreleaseversion2: 2.1.0

* 2.x release (EOL):
+
link:https://dlcdn.apache.org/causeway/causeway-bom-{page-causewayreleaseversion2}-source-release.zip[causeway-bom-{page-causewayreleaseversion2}-source-release.zip] (link:https://downloads.apache.org/causeway/causeway-bom-{page-causewayreleaseversion2}-source-release.zip.asc[asc], link:https://downloads.apache.org/causeway/causeway-bom-{page-causewayreleaseversion2}-source-release.zip.sha512[sha512])





=== Verifying Releases

You can verify your download using link:https://www.apache.org/info/verification.html[these procedures] and using these link:https://downloads.apache.org/causeway/KEYS[KEYS].

For more information on signing artifacts and why we do it, check out the http://www.apache.org/dev/release-signing.html[Release Signing FAQ].



== Source Code

The Apache Causeway source is hosted on github.
You can download the Apache Causeway source code using:

[source,bash]
----
git clone https://github.com/apache/causeway.git
----

Contributors can fork this repo using github's tools and contribute patches/new features using pull requests.

Committers can push to this repo directly, once their ASF account and github account have been linked.
See link:https://gitbox.apache.org/setup/[gitbox setup] for more details on how to do this.



== DOAP RDF File

The http://projects.apache.org/doap.html[description of a project] RDF file for Apache Causeway can be downloaded link:https://causeway.apache.org/doap_causeway.rdf[here].



== Interim Builds

If you want to track the latest developments, there are also xref:comguide:ROOT:nightly-builds.adoc[nightly builds] and xref:comguide:ROOT:weekly-builds.adoc[weekly builds].

Although these are maintained by the framework’s committers, do be aware that *these are not official ASF releases*.
