= Bulk Load of Standalone Collections
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


The implementation of user interactions (meaning either an action invocations or a property edits) in the xref:ug:vw:ugvw.adoc#[Wicket viewer] is splits into two.
The first phase performs the actual interaction, with the results (dirtied objects) flushed to the database.
The second phase then renders the results of the interaction.

When the user interaction in question is an action invocation that returns a list of objects, the resultant list is not rendered in the first phase.
Instead, only the IDs of the objects in the list are captured.
When the list is then rendered, the framework re-loads each object.

The default implementation does this row-by-row, resulting in multiple queries against the database.
Setting the property:

[source,ini]
----
isis.persistor.datanucleus.standaloneCollection.bulkLoad=true
----

changes to a more efficient implementation that bulk loads all the objects using a single query.


[NOTE]
====
In the future the bulkLoad implementation may be made the default.
====

[NOTE]
====
The implementation of parented collections does not suffer from this issue; the rendering phase runs the query to obtain the matches.
====

