[[SudoService]]
= `SudoService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:



The `SudoService` allows the current user reported by the xref:applib:svc:core-domain-api/UserService.adoc[`UserService`]  to be temporarily changed to some other user.
This is useful both for xref:integ-test-support:ROOT:about.adoc[integration testing] (eg if testing a workflow system whereby objects are moved from one user to another) and while running xref:ext-fixtures:ROOT:about.adoc[fixture scripts] (eg setting up objects that would normally require several users to have acted upon the objects).


== API

The API provided by the service is:

[source,java]
----
public interface SudoService {
    @Programmatic
    void sudo(String username, final Runnable runnable);
    @Programmatic
    <T> T sudo(String username, final Callable<T> callable);
    @Programmatic
    void sudo(String username, List<String> roles, final Runnable runnable);
    @Programmatic
    <T> T sudo(String username, List<String> roles, final Callable<T> callable);
}
----

which will run the provided block of code (a `Runnable` or a `Callable`) in a way such that calls to
`UserService#getUser()` will return the specified user (and roles, if specified).
(If roles are not specified, then the roles of the current user are preserved).

The current user/role reported by the internal xref:runtime-services:ROOT:application-layer/AuthenticationSessionProvider.adoc[`AuthenticationSessionProvider`] will also return the specified user/roles.

[IMPORTANT]
====
Note however that this the "effective user" does not propagate through to the xref:security:ROOT:about.adoc[Shiro security mechanism], which will continue to be evaluated according to the permissions of the current user.
See the xref:applib:svc:testing/SudoService.adoc#ACCESS-ALL-ROLE[`ACCESS-ALL-ROLE`] below for details of how to circumvent this.
====


== Implementation

The core framework provides a default implementation of this service (`o.a.i.core.runtime.services.sudo.SudoServiceDefault`).



== Usage

A good example can be found in the (non-ASF) http://github.com/isisaddons/isis-app-todoapp[Isis addons' todoapp] which uses the `SudoService` in a fixture script to set up `ToDoItem` objects:

[source,java]
----
protected void execute(final ExecutionContext ec) {
    ...
    sudoService.sudo(getUsername(),
            new Runnable() {
                @Override
                public void run() {
                    wrap(toDoItem).completed();
                }
            });
    ...
}
----


=== ACCESS_ALL_ROLE

When `sudo(...)` is called the "effective user" is reported by both xref:applib:svc:core-domain-api/UserService.adoc[`UserService`] and by xref:runtime-services:ROOT:application-layer/AuthenticationSessionProvider.adoc[`AuthenticationSessionProvider`], but does not propagate through to the xref:security:ROOT:about.adoc[Shiro security mechanism].
These continue to be evaluated according to the permissions of the current user.

This can be a problem in certain use cases.
For example if running a fixture script (which uses the xref:applib:svc:application-layer-api/WrapperFactory.adoc[`WrapperFactory`]) from within an implementation of xref:applib:svc:persistence-layer-spi/UserRegistrationService.adoc[`UserRegistrationService`], this is likely to result in ``HiddenException``s being thrown because there is no effective user.

In such cases, permission checking can simply be disabled by specifying `SudoService.ACCESS_ALL_ROLE` as one of the roles.
For example:

[source,java]
----
protected void execute(final ExecutionContext ec) {
    ...
    sudoService.sudo(getUsername(), Arrays.asList(SudoService.ACCESS_ALL_ROLE),
            new Runnable() {
                @Override
                public void run() {
                    wrap(toDoItem).completed();
                }
            });
    ...
}
----

[NOTE]
====
In the future this service may be used more deeply, eg to propagate permissions through to the Shiro security mechanism also.
====




== SPI

The `SudoService.Spi` service allows implementations of `SudoService` to notify other services/components that the effective user and roles are different.
The default implementation of xref:applib:svc:core-domain-api/UserService.adoc[`UserService`] has been refactored to leverage this SPI.

[source,java]
----
public interface SudoService {
    ...
    interface Spi {
        void runAs(String username, List<String> roles);        // <1>
        void releaseRunAs();                                    // <2>
    }
}
----
<1> Called by `SudoService#sudo(...)`, prior to invoking its `Runnable` or `Callable`.
<2> Called by `SudoService#sudo(...)`, after its `Runnable` or `Callable` has been invoked.

The names of these methods were chosen based on link:https://shiro.apache.org/static/1.2.6/apidocs/org/apache/shiro/subject/Subject.html#runAs-org.apache.shiro.subject.PrincipalCollection-[similar names within Shiro].




