[SwitchUserService]
= `SwitchUserService` (deprecated)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:



The `SwitchUserService` domain service provides the ability to install fixtures changing the effective user half-way
through.  For example, this allows the setup of a test of a workflow system which checks that work is moved between
different users of the system.


[NOTE]
====
This service is deprecated; use xref:ext-fixtures:ROOT:about.adoc[fixture scripts] and the
xref:applib:svc:testing/SudoService.adoc[`SudoService`] instead.
====



== API

The API of this service:

[source,java]
----
public class SwitchUserService {
    void switchUser(String username, String... roles);      // <1>
    void switchUser(String username, List<String> roles);   // <1>
}
----
<1> Switches the current user with the list of specified roles.





== Implementation

The framework provides a default implementation of this service: `SwitchUserServiceImpl` in `isis-core-runtime`