= EntityChanges _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

As used by xref:refguide:applib:index/services/publishing/spi/EntityChangesSubscriber.adoc[EntityChangesSubscriber] , provides metrics on the "footprint" of an interaction, in other words the number of objects accessed or changed.

The numbers of objects loaded, created, updated or deleted and the number of object properties modified (in other words the "size" or "weight" of the transaction).

== API

[source,java]
.EntityChanges.java
----
interface EntityChanges {
  UUID getInteractionId()     // <.>
  int getSequence()     // <.>
  String getUsername()     // <.>
  Timestamp getCompletedAt()     // <.>
  int getNumberLoaded()     // <.>
  int getNumberCreated()     // <.>
  int getNumberUpdated()     // <.>
  int getNumberDeleted()     // <.>
  int getNumberPropertiesModified()     // <.>
  ChangesDto getDto()     // <.>
}
----

<.> xref:#getInteractionId__[getInteractionId()]
+
--
inherited from xref:refguide:applib:index/mixins/system/HasTransactionId.adoc[HasTransactionId] and transitively from xref:refguide:applib:index/mixins/system/HasInteractionId.adoc[HasInteractionId] , correlates back to the unique identifier of the _org.apache.isis.applib.services.iactn.Interaction_ in which these objects were changed.
--
<.> xref:#getSequence__[getSequence()]
+
--
inherited from xref:refguide:applib:index/mixins/system/HasTransactionId.adoc[HasTransactionId] , with _#getInteractionId()_ it identifies the transaction within the _org.apache.isis.applib.services.iactn.Interaction_ in which these objects were changed.
--
<.> xref:#getUsername__[getUsername()]
+
--
Inherited from xref:refguide:applib:index/mixins/security/HasUsername.adoc[HasUsername] , is the user that initiated the transaction causing these objects to change.
--
<.> xref:#getCompletedAt__[getCompletedAt()]
+
--
Time that the interaction execution completed
--
<.> xref:#getNumberLoaded__[getNumberLoaded()]
+
--
Number of domain objects loaded in this interaction
--
<.> xref:#getNumberCreated__[getNumberCreated()]
+
--
Number of domain objects created in this interaction
--
<.> xref:#getNumberUpdated__[getNumberUpdated()]
+
--
Number of domain objects updated in this interaction
--
<.> xref:#getNumberDeleted__[getNumberDeleted()]
+
--
Number of domain objects deleted in this interaction
--
<.> xref:#getNumberPropertiesModified__[getNumberPropertiesModified()]
+
--
Number of domain objects properties that were changed in this interaction
--
<.> xref:#getDto__[getDto()]
+
--
Same details, but as an an instance of _ChangesDto_ .
--

== Members

[#getInteractionId__]
=== getInteractionId()

inherited from xref:refguide:applib:index/mixins/system/HasTransactionId.adoc[HasTransactionId] and transitively from xref:refguide:applib:index/mixins/system/HasInteractionId.adoc[HasInteractionId] , correlates back to the unique identifier of the _org.apache.isis.applib.services.iactn.Interaction_ in which these objects were changed.

[#getSequence__]
=== getSequence()

inherited from xref:refguide:applib:index/mixins/system/HasTransactionId.adoc[HasTransactionId] , with _#getInteractionId()_ it identifies the transaction within the _org.apache.isis.applib.services.iactn.Interaction_ in which these objects were changed.

[#getUsername__]
=== getUsername()

Inherited from xref:refguide:applib:index/mixins/security/HasUsername.adoc[HasUsername] , is the user that initiated the transaction causing these objects to change.

[#getCompletedAt__]
=== getCompletedAt()

Time that the interaction execution completed

[#getNumberLoaded__]
=== getNumberLoaded()

Number of domain objects loaded in this interaction

[#getNumberCreated__]
=== getNumberCreated()

Number of domain objects created in this interaction

[#getNumberUpdated__]
=== getNumberUpdated()

Number of domain objects updated in this interaction

[#getNumberDeleted__]
=== getNumberDeleted()

Number of domain objects deleted in this interaction

[#getNumberPropertiesModified__]
=== getNumberPropertiesModified()

Number of domain objects properties that were changed in this interaction

[#getDto__]
=== getDto()

Same details, but as an an instance of _ChangesDto_ .

This can be converted into a serializable XML representation using the _org.apache.isis.applib.util.schema.ChangesDtoUtils_ utility class.
