= EntityPropertyChangeSubscriber
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

SPI called for each pre-post change to a property of a domain entity during a result of the transaction. The callback is therefore quite fine-grained and will be called many (many) times for within any given transaction.

Only those properties of entities that have publishing enabled (using * _DomainObject#entityChangePublishing()_ ) are included.

== API

[source,java]
.EntityPropertyChangeSubscriber.java
----
interface EntityPropertyChangeSubscriber {
  void onChanging(EntityPropertyChange entityPropertyChange)     // <.>
  void onChanging(Can<EntityPropertyChange> entityPropertyChanges)     // <.>
}
----

<.> xref:#onChanging_EntityPropertyChange[onChanging(EntityPropertyChange)]
+
--
Receives a single property change event for changing entities (with publishing enabled using _DomainObject#entityChangePublishing()_ ) as an instance of _EntityPropertyChange_ .
--
<.> xref:#onChanging_Can[onChanging(Can)]
+
--
Receives a collection of _EntityPropertyChange property change event_ s for the changing entities.
--

== Members

[#onChanging_EntityPropertyChange]
=== onChanging(EntityPropertyChange)

Receives a single property change event for changing entities (with publishing enabled using _DomainObject#entityChangePublishing()_ ) as an instance of _EntityPropertyChange_ .

The callback is called (multiple times) at the end of the transaction, during the pre-commit phase.

[#onChanging_Can]
=== onChanging(Can)

Receives a collection of _EntityPropertyChange property change event_ s for the changing entities.

The default implementation simply delegates to _#onChanging(EntityPropertyChange)_ for each, but subclasses could override in order to perform work in bulk.

include::hooks/EntityPropertyChangeSubscriber_010-implementation.adoc[]

include::hooks/EntityPropertyChangeSubscriber_020-examples-and-usage.adoc[]
