= DomainObjectRepresentation
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.DomainObjectRepresentation.java
----
class DomainObjectRepresentation {
  DomainObjectRepresentation(JsonNode jsonNode)
  String getTitle()
  String getDomainType()     // <.>
  String getInstanceId()     // <.>
  String getServiceId()     // <.>
  JsonRepresentation getMembers()
  DomainObjectMemberRepresentation getProperty(String id)
  JsonRepresentation getProperties()
  DomainObjectMemberRepresentation getCollection(String id)
  JsonRepresentation getCollections()
  DomainObjectMemberRepresentation getAction(String id)
  JsonRepresentation getActions()
  LinkRepresentation getPersistLink()     // <.>
  String getOid()     // <.>
}
----

<.> xref:#getDomainType__[getDomainType()]
+
--
Populated only for domain objects, not for domain services.
--
<.> xref:#getInstanceId__[getInstanceId()]
+
--
Populated only for domain objects, not for domain services.
--
<.> xref:#getServiceId__[getServiceId()]
+
--
Populated only for domain services, not for domain objects.
--
<.> xref:#getPersistLink__[getPersistLink()]
+
--
Only for transient, persistable, objects
--
<.> xref:#getOid__[getOid()]
+
--
Isis extension.
--

== Members

[#getDomainType__]
=== getDomainType()

Populated only for domain objects, not for domain services.

[#getInstanceId__]
=== getInstanceId()

Populated only for domain objects, not for domain services.

[#getServiceId__]
=== getServiceId()

Populated only for domain services, not for domain objects.

[#getPersistLink__]
=== getPersistLink()

Only for transient, persistable, objects

[#getOid__]
=== getOid()

Isis extension.
