= TypeIdentifier
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

A generalization of Java's class type to also hold a logical name, which can be supplied lazily.

== API

[source,java]
.TypeIdentifier.java
----
class TypeIdentifier {
  TypeIdentifier lazy(final Class<?> correspondingClass, final Supplier<String> logicalNameProvider)     // <.>
  TypeIdentifier eager(final Class<?> correspondingClass, final String logicalName)     // <.>
  TypeIdentifier fqcn(final Class<?> correspondingClass)     // <.>
  String getClassName()     // <.>
  String getLogicalTypeName()
  String getLogicalTypeNameFormatted(final String root, final String delimiter)     // <.>
  boolean equals(final Object obj)
  boolean isEqualTo(final TypeIdentifier other)
  int hashCode()
  int compareTo(final TypeIdentifier other)
}
----

<.> xref:#lazy__Class_Supplier[lazy(Class, Supplier)]
+
--
Returns a new TypeIdentifier based on the corresponding class and a _logicalNameProvider_ for lazy logical name lookup.
--
<.> xref:#eager__Class_String[eager(Class, String)]
+
--
Returns a new TypeIdentifier based on the corresponding class and (ahead of time) known _logicalName_ .
--
<.> xref:#fqcn__Class[fqcn(Class)]
+
--
Use the corresponding class's fully qualified name for the _logicalName_ . Most likely used in testing scenarios.
--
<.> xref:#getClassName__[getClassName()]
+
--
Canonical name of the corresponding class.
--
<.> xref:#getLogicalTypeNameFormatted__String_String[getLogicalTypeNameFormatted(String, String)]
+
--
The logical type name consists of 2 parts, the _namespace_ and the _logical simple name_ . Returns a concatenation of _namespace_ , _delimiter_ and the _logical simple name_ , whereas in the absence of a _namespace_ returns a concatenation of _root_ and the _logical simple name_ .
--

== Members

[#lazy__Class_Supplier]
=== lazy(Class, Supplier)

Returns a new TypeIdentifier based on the corresponding class and a _logicalNameProvider_ for lazy logical name lookup.

[#eager__Class_String]
=== eager(Class, String)

Returns a new TypeIdentifier based on the corresponding class and (ahead of time) known _logicalName_ .

[#fqcn__Class]
=== fqcn(Class)

Use the corresponding class's fully qualified name for the _logicalName_ . Most likely used in testing scenarios.

[#getClassName__]
=== getClassName()

Canonical name of the corresponding class.

[#getLogicalTypeNameFormatted__String_String]
=== getLogicalTypeNameFormatted(String, String)

The logical type name consists of 2 parts, the _namespace_ and the _logical simple name_ . Returns a concatenation of _namespace_ , _delimiter_ and the _logical simple name_ , whereas in the absence of a _namespace_ returns a concatenation of _root_ and the _logical simple name_ .
