= DocxService _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Merges input HTML against a provided _docx_ template, generating a _Word docx_ .

== API

[source,java]
.DocxService.java
----
interface DocxService {
  WordprocessingMLPackage loadPackage(InputStream docxTemplate)     // <.>
  void merge(MergeParams mergeDefn)     // <.>
}
----

<.> xref:#loadPackage__InputStream[loadPackage(InputStream)]
+
--
Load and return an in-memory representation of a docx.
--
<.> xref:#merge__MergeParams[merge(MergeParams)]
+
--
Merge the input arguments (as HTML) against the Docx template, writing out as a Word docx..
--

== Members

[#loadPackage__InputStream]
=== loadPackage(InputStream)

Load and return an in-memory representation of a docx.

This is public API because building the in-memory structure can be quite slow. Thus, clients can use this method to cache the in-memory structure, and pass it in the _MergeParams_ (through the _MergeParams.Builder#docxTemplateAsWpMlPackage(WordprocessingMLPackage) builder method_ )

[#merge__MergeParams]
=== merge(MergeParams)

Merge the input arguments (as HTML) against the Docx template, writing out as a Word docx..
