= CommandExecutorServiceDefault _(record)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Default implementation of xref:refguide:applib:index/services/command/CommandExecutorService.adoc[CommandExecutorService] .

== API

[source,java]
.CommandExecutorServiceDefault.java
----
record CommandExecutorServiceDefault {
  Try<Bookmark> executeCommand(Command command)
  Try<Bookmark> executeCommand(InteractionContextPolicy interactionContextPolicy, Command command)
  Try<Bookmark> executeCommand(CommandDto dto)
  Try<Bookmark> executeCommand(InteractionContextPolicy interactionContextPolicy, CommandDto dto)
  void applyActionAdvisorPolicy(InteractionAdvisorPolicy policy, ObjectAction action, ManagedObject target, InteractionHead interactionHead, Can<ManagedObject> arguments)
  void applyPropertyAdvisorPolicy(InteractionAdvisorPolicy policy, OneToOneAssociation property, ManagedObject target, ManagedObject proposedValue)
  Can<ManagedObject> argAdaptersForParentedCollectionNavigation(ActionDto actionDto, ObjectAction objectAction, SchemaValueMarshaller valueMarshaller)     // <.>
}
----

<.> xref:#argAdaptersForParentedCollectionNavigation_ActionDto_ObjectAction_SchemaValueMarshaller[argAdaptersForParentedCollectionNavigation(ActionDto, ObjectAction, SchemaValueMarshaller)]
+
--
Reconstructs replay arguments for a synthetic parented-collection selector action.
--

== Members

[#argAdaptersForParentedCollectionNavigation_ActionDto_ObjectAction_SchemaValueMarshaller]
=== argAdaptersForParentedCollectionNavigation(ActionDto, ObjectAction, SchemaValueMarshaller)

Reconstructs replay arguments for a synthetic parented-collection selector action.

Such an action's parameters are the collection's optional column filters, which can be added, removed, or reordered between the time a command is recorded and the time it is replayed. Rather than bind positionally (which would silently mis-align on any such change), each current action parameter is matched to the recorded DTO parameter with the same stable id (falling back to friendly name); any current parameter with no corresponding recorded parameter is padded with an empty/unselected value.

Package-private and static to allow focused testing.
