
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



== Usage

This domain service is useful both for xref:testing:integtestsupport:about.adoc[integration testing] and while running xref:fixtures:ROOT:about.adoc[fixture scripts].

For example, to integration test a workflow system, whereby objects are moved from one user to another, it is helpful to switch the effective user to verify that the task was assigned correctly.

Or, this fixture script uses the `SudoService` to set up `ToDoItem` objects:

[source,java]
----
protected void execute(final ExecutionContext ec) {
    ...
    sudoService.sudo(
        InteractionContext.switchUser(UserMemento.ofName("joe")),
        () -> wrap(toDoItem).completed()
    );
    ...
}
----


== Interaction with Shiro

When `sudo(...)` is called the "effective user" is reported by  xref:refguide:applib:index/services/user/UserService.adoc[UserService].
However, it does _not_ propagate through to the xref:security:ROOT:about.adoc[Shiro security mechanism], which continue to be evaluated according to the permissions of the current user.

This can be a problem in certain use cases.
For example if running a fixture script (which uses the xref:refguide:applib:index/services/wrapper/WrapperFactory.adoc[WrapperFactory]) from within an implementation of xref:refguide:applib:index/services/userreg/UserRegistrationService.adoc[UserRegistrationService], this is likely to result in ``HiddenException``s being thrown because there is no effective user.

In such cases, permission checking can simply be disabled by specifying `SudoService.ACCESS_ALL_ROLE` as one of the roles.
For example:

[source,java]
----
protected void execute(final ExecutionContext ec) {
    ...
    ExecutionContext ec =
        ExecutionContext.ofUserWithSystemDefaults(
            UserMemento.ofNameAndRoleNames("joe", SudoService.ACCESS_ALL_ROLE)));

    sudoService.sudo(ec, () -> wrap(toDoItem).completed());
    ...
}
----

[NOTE]
====
In the future this service may be used more deeply, eg to propagate permissions through to the Shiro security mechanism also.
====





== See also

* xref:refguide:applib:index/services/iactn/ExecutionContext.adoc[ExecutionContext]

* xref:refguide:applib:index/services/sudo/SudoServiceListener.adoc[SudoServiceListener]

* the `InteractionFactory` is a lower-level framework (non-API) service, that provides the ability to programmatically start a new "interaction"; these can be nested.


