/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package demoapp.dom.types.causewayval.markdowns.holder;

import javax.inject.Named;

/* This file was GENERATED by the showcase generator (tooling). Do NOT edit! */
@Named("demo.CausewayMarkdownHolder")
//tag::class[]
public interface CausewayMarkdownHolder {

    org.apache.causeway.valuetypes.markdown.applib.value.Markdown getReadOnlyProperty();
    void setReadOnlyProperty(org.apache.causeway.valuetypes.markdown.applib.value.Markdown c);

    org.apache.causeway.valuetypes.markdown.applib.value.Markdown getReadWriteProperty();
    void setReadWriteProperty(org.apache.causeway.valuetypes.markdown.applib.value.Markdown c);

    org.apache.causeway.valuetypes.markdown.applib.value.Markdown getReadOnlyOptionalProperty();
    void setReadOnlyOptionalProperty(org.apache.causeway.valuetypes.markdown.applib.value.Markdown c);

    org.apache.causeway.valuetypes.markdown.applib.value.Markdown getReadWriteOptionalProperty();
    void setReadWriteOptionalProperty(org.apache.causeway.valuetypes.markdown.applib.value.Markdown c);

}
//end::class[]
