:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/ActionLayout.html#hidden[@ActionLayout#hidden] attribute specifies whether an action should be visible in the UI or not, based on the context in which the object being rendered (within a form, i.e. on its own page, or within a collection).


== How this demo works

The collection on the left hand side shows a set of domain objects.
That domain object defines four actions, and depending upon context, they may be visible on an object form or when rendered in a collection.
From this page, you can inspect the visibility of the actions from the context of a parented collection.

Navigate into each domain object to inspect the visibility of the actions on an object form.

NOTE: Currently the Wicket viewer never renders actions for objects rendered as instances of collections; this is being tracked as enhancement request link:https://issues.apache.org/jira/browse/CAUSEWAY-3477[CAUSEWAY-3477].

The four actions are:

* `hidden` not specified:
+
[source,java]
.ActionLayoutHiddenEntity_changeName.java
----
include::ActionLayoutHiddenEntity_changeName.java[tags=class]
----
<.> action _should_ be visible for this entity when rendered both on an object form and within a collection.
+

* `hidden` on object forms (but not necessarily on collections):
+
[source,java]
.ActionLayoutHiddenEntity_changeNameHiddenObjectForms.java
----
include::ActionLayoutHiddenEntity_changeNameHiddenObjectForms.java[tags=class]
----
<.> action should be visible for this entity when rendered in a collection.

* `hidden` on collections (but not necessarily on object forms):
+
[source,java]
.ActionLayoutHiddenEntity_changeNameHiddenAllTables.java
----
include::ActionLayoutHiddenEntity_changeNameHiddenAllTables.java[tags=class]
----
<.> action should _NOT_ be visible for this entity within the collection.
+
However, if you navigate into these domain objects then some of these actions will be visible.

* `hidden` everywhere:
+
[source,java]
.ActionLayoutHiddenEntity_changeNameHiddenEverywhere.java
----
include::ActionLayoutHiddenEntity_changeNameHiddenEverywhere.java[tags=class]
----
<.> action should _NOT_ be visible for this entity, in any context.

The notion of an action that is _always_ hidden might seem nonsensical.
But although there is no difference in the UI, a hidden action _is_ part of the metadamodel while a link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/Programmatic.html#hidden[@Programmatic] action is not.

A rare (but valid) use case is to invoke such a hidden action using the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/services/wrapper/WrapperFactory.html#wrap(t,-synccontrol)[WrapperFactory] (skipping rules).
This can be for example to publish executions to any registered link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/services/publishing/spi/ExecutionSubscriber.html[ExecutionSubscriber]s.
