image:https://github.com/apache-isis-committers/isis-nightly/workflows/Nightly/badge.svg[link="https://github.com/apache-isis-committers/isis-nightly/actions?query=workflow%3A%22Nightly%22"]

= Demo App

The Demo App is an introduction to the features and components available in Apache Isis.

It allows you to learn the very basics and also to discover some of the more advanced features, the framework has to offer. See the Docker section below on how to get started. 

== Docker

NOTE: Further on *<tag>* is used as a placeholder for the docker image tag of your choice. When omitted the latest version is used. Actual tag names might be changed without notice. Currently we have tag *nightly*. See https://hub.docker.com/r/apacheisis/demo-springboot/tags/[apacheisis/isis-2-demo] (Docker-Hub)

=== Prereqs

Install https://www.docker.com/community-edition[Docker] on your computer.

=== Pulling the Docker Image

Pull the demo image using:

[source]
----
docker pull apacheisis/demo-springboot:<tag>
----

=== Running the Docker Image

Run the demo image using:

[source]
----
docker run --name demo --detach -p8080:8080 apacheisis/demo-springboot:<tag>
----

This will start a new Docker container named 'demo'.

The demo-app can then be accessed at http://localhost:8080/wicket/[].
Login with `sven:pass`.

To stop and remove the container named 'demo' use:

[source]
----
docker stop demo && docker rm demo
----

=== Customization

To run the _Demo App_ in _prototyping_ mode, add an environment variable `PROTOTYPING=true`.
The 'run' command above then becomes:

[source]
----
docker run --name demo --detach -p8080:8080 -ePROTOTYPING=true apacheisis/demo-springboot:<tag>
----

To run the container with your console attached, replace the '--detach' argument with '-it'. (Use CTRL-C to stop and detach.)

[source]
----
docker run --name demo -it -p8080:8080 apacheisis/demo-springboot:<tag>
----

== Contributing

If you like to get involved quickly, please feel free to open new pull requests (at github) or just join the discussion and provide feedback.

If you are interested in contributing to Apache Isis, see the https://isis.apache.org/guides/dg/dg.html[Developers' Guide] for details. 

== Credits

This Demo App uses icons made by http://www.freepik.com[Freepik] and
 https://www.flaticon.com/authors/smashicons[Smashicons] from https://www.flaticon.com/[www.flaticon.com] which are licensed by http://creativecommons.org/licenses/by/3.0/[CC 3.0 BY]. We use https://github.com/vsch/flexmark-java[flexmark] for markdown rendering.
