:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

=== Dependency

In the webapp module of your application, add the following dependency:

[source,xml,subs="attributes+"]
.pom.xml
----
<dependencies>
    <dependency>
        <groupId>org.apache.causeway.persistence</groupId>
        <artifactId>causeway-persistence-querydsl-{querydsl-implementation}</artifactId>
    </dependency>
</dependencies>
----

=== AppManifest

In your application's `AppManifest` (top-level Spring `@Configuration` used to bootstrap the app), import the appropriate module:

[source,java,subs="attributes+"]
.AppManifest.java
----
@Configuration
@Import({
        ...
        CausewayModulePersistenceQueryDsl{querydsl-implementation-capitalized}.class,
        ...
})
public class AppManifest {
}
----


=== Module with entities

In every module that contains entities, it's necessary to generate the "Q" classes that are used in turn to construct the queries.
This requires several changes to the module's `pom.xml` file.

* add the build plugin
+
[source,xml,subs="attributes+"]
.pom.xml
----
<build>
    <plugins>
        ...
        <plugin>
            <groupId>com.mysema.maven</groupId>
            <artifactId>apt-maven-plugin</artifactId>
            <version>{sema-plugin-version}</version>
            <executions>
                <execution>
                    <goals>
                        <goal>process</goal>
                    </goals>
                    <configuration>
                        <outputDirectory>
                            target/generated-sources/java
                        </outputDirectory>
                        <processor>
                            {querydsl-annotation-processor}
                        </processor>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        ...
    </plugins>
</build>
----

* add a dependency to the `querydsl-apt` annotation processor:
+
[source,xml,subs="attributes+"]
.pom.xml
----
<dependencies>
    ...
    <dependency>
        <groupId>com.querydsl</groupId>
        <artifactId>querydsl-apt</artifactId>
        <scope>provided</scope>
    </dependency>
    ...
</dependencies>
----


* (recommended, usually required) add a dependency to the querydsl-applib module:
+
[source,xml,subs="attributes+"]
.pom.xml
----
<dependencies>
    ...
    <dependency>
        <groupId>org.apache.causeway.persistence</groupId>
        <artifactId>causeway-persistence-querydsl-applib</artifactId>
    </dependency>
    ...
</dependencies>
----
