= `InteractionDtoServiceInternal`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `InteractionDtoServiceInternal` internal domain service is used by the framework to create and update DTOs representing member executions, ie the invocation of an action or the editing of a property.  The DTO is in all cases a subclass of `MemberExecutionDto`, from the xref:refguide:schema:ixn["ixn" schema], and subsequently accessible from the `Interaction` object (per the xref:refguide:applib-svc:application-layer-api/InteractionContext.adoc.adoc[`InteractionContext`] service).


== SPI & Implementation

The SPI of the service is:

[source,java]
----
public interface InteractionDtoServiceInternal {
    ActionInvocationDto asActionInvocationDto(          // <1>
            ObjectAction objectAction,
            ObjectAdapter targetAdapter,
            List<ObjectAdapter> argumentAdapters);
    PropertyEditDto asPropertyEditDto(                  // <2>
            OneToOneAssociation property,
            ObjectAdapter targetAdapter,
            ObjectAdapter newValueAdapterIfAny);
    ActionInvocationDto updateResult(                   // <3>
            ActionInvocationDto actionInvocationDto,
            ObjectAction objectAction,
            Object resultPojo);
}
----
<1> called by the framework when invoking an action, to create a DTO capturing the details of the action invocation (target, arguments etc).
<2> called by the framework when editing a property, to create a DTO (for the xref:refguide:schema:ixn.adoc["ixn" schema]) capturing the details of the property edit (target, new value etc).
<3> called by the framework to attach the result of an action invocation to the aforementioned DTO.

The service is implemented by `o.a.i.core.runtime.services.ixn.InteractionDtoServiceInternalDefault`.


== Related Services

The design of this service is similar to that of
xref:core:runtime-services:application-layer/CommandDtoServiceInternal.adoc[`CommandDtoServiceInternal`], used to create the `CommandDto`
(from the xref:refguide:schema:cmd.adoc["cmd" schema]).
