# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

service:
  extensions: [jaeger_storage, jaeger_query, remote_sampling, healthcheckv2, expvar, zpages]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: "${env:JAEGER_LISTEN_HOST:-localhost}"
                port: 8888
    logs:
      level: info

extensions:
  jaeger_query:
    storage:
      traces: some_storage
    ai:
      mcp: {}

  jaeger_storage:
    backends:
      some_storage:
        memory:
          max_traces: "${env:JAEGER_MAX_TRACES:-10000}"

  remote_sampling:
    file:
      path:
      default_sampling_probability: 1
      reload_interval: 1s
    http:
      endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:5778"
    grpc:
      endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:5779"

  healthcheckv2:
    use_v2: true
    http:
      endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:13133"
    grpc:

  expvar:
    endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:27777"

  zpages:
    endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:27778"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:4317"
      http:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:4318"

  jaeger:
    protocols:
      grpc:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:14250"
      thrift_http:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:14268"
      thrift_binary:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:6832"
      thrift_compact:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:6831"

  zipkin:
    endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:9411"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_storage
