= DomainChangeRecord
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Allows domain objects that represents some sort of recorded change to a domain object (commands, executions, audit entries) to act as a mixee in order that other modules can contribute behaviour.

== API

[source,java]
.DomainChangeRecord.java
----
interface DomainChangeRecord {
  ChangeType getType()     // <.>
  UUID getInteractionId()     // <.>
  String getUsername()     // <.>
  java.sql.Timestamp getTimestamp()     // <.>
  String getTargetLogicalTypeName()     // <.>
  Bookmark getTarget()     // <.>
  String getLogicalMemberIdentifier()
  boolean hideLogicalMemberIdentifier()
  String getPropertyId()
  boolean hidePropertyId()
  String getPreValue()     // <.>
  boolean hidePreValue()
  String getPostValue()     // <.>
  boolean hidePostValue()
}
----

<.> xref:#getType_[getType()]
+
--
Distinguishes commands from audit entries from published events/interactions (when these are shown mixed together in a (standalone) table).
--
<.> xref:#getInteractionId_[getInteractionId()]
+
--
The unique identifier of the _org.apache.causeway.applib.services.iactn.Interaction_ within which this change occurred.
--
<.> xref:#getUsername_[getUsername()]
+
--
The user that caused the change.
--
<.> xref:#getTimestamp_[getTimestamp()]
+
--
The time that the change occurred.
--
<.> xref:#getTargetLogicalTypeName_[getTargetLogicalTypeName()]
+
--
The logical type name of the domain object being changed.
--
<.> xref:#getTarget_[getTarget()]
+
--
The xref:refguide:applib:index/services/bookmark/Bookmark.adoc[Bookmark] identifying the domain object that has changed.
--
<.> xref:#getPreValue_[getPreValue()]
+
--
The value of the property prior to it being changed.
--
<.> xref:#getPostValue_[getPostValue()]
+
--
The value of the property after it has changed.
--

== Members

[#getType_]
=== getType()

Distinguishes commands from audit entries from published events/interactions (when these are shown mixed together in a (standalone) table).

[#getInteractionId_]
=== getInteractionId()

The unique identifier of the _org.apache.causeway.applib.services.iactn.Interaction_ within which this change occurred.

[#getUsername_]
=== getUsername()

The user that caused the change.

[#getTimestamp_]
=== getTimestamp()

The time that the change occurred.

[#getTargetLogicalTypeName_]
=== getTargetLogicalTypeName()

The logical type name of the domain object being changed.

[#getTarget_]
=== getTarget()

The xref:refguide:applib:index/services/bookmark/Bookmark.adoc[Bookmark] identifying the domain object that has changed.

[#getPreValue_]
=== getPreValue()

The value of the property prior to it being changed.

Populated only for audit entries.

[#getPostValue_]
=== getPostValue()

The value of the property after it has changed.

Populated only for audit entries.
