[#view-models]
= View Models

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


As described in the xref:userguide:fun:overview.adoc#view-models[overview], view models are domain objects that have behaviour and state, similar to domain entities.
However, unlike domain entities, their state is _not_ persisted to a database but is instead serialized into its identifier (in effect, its URL).
The framework unpacks this URL to infer/recreate the view model's state with each interaction.

The framework provides two main ways to implement a view model:

* The more powerful/flexible approach is to use JAXB annotations; this allows the state of the object's properties and also its collections.
+
The serialized form of these view models is therefore XML, which also enables these view models to act as DTO (useful for various integration scenarios).

* The other approach is to use Apache Isis specific annotations.
+
While (arguably) these explain the intent of the view model better, they are more restrictive: only the state of the object's properties is serialized -- collections are ignored -- and not every datatype is recognized.
+
On the other hand, they are more likely to perform better.

In the sections below we consider JAXB view models both as "regular" view models, and also when using them to act as DTOs.

[[jaxb]]
== JAXB View Models

Here's a typical example of a JAXB view model, to allow (certain properties of) two ``Customer``s to be compared:

[source,java]
----
@XmlRootElement(name = "compareCustomers")          // <.>
@XmlType(
        propOrder = {                               // <.>
            "customer1",
            "customer2"
        }
)
@XmlAccessorType(XmlAccessType.FIELD)               // <.>
public class CompareCustomers {

    @XmlElement(required = true)                    // <.>
    @Getter @Setter
    Customer customer1;

    @XmlElement(required = true)                    // <.>
    @Getter @Setter
    Customer customer2;

    @XmlTransient                                   // <.>
    public String getCustomer1Name() {
        return getCustomer1().getName();
    }

    @XmlTransient                                   // <.>
    public String getCustomer2Name() {
        return getCustomer2().getName();
    }

    ...
}
----

<.> The JAXB `@XmlRootElement` annotation indicates this is a view model to Apache Isis, which then uses JAXB to serialize the state of the view model between interactions

<.> Optionally, the properties of the view model can be listed using the `XmlType#propOrder` attribute. +
This is an all-or-nothing affair: either all properties must be listed, or else the annotation omitted.

<.> Specifying field accessor type allows the Lombok `@Getter` and `@Setter` annotations to be used.

<.> The `@XmlElement` indicates the property is part of the view model's state.
For collections, the `@XmlElementWrapper` would also typically be used.

<.> The `@XmlTransient` indicates that the property is derived and should be ignored by JAXB. +
The derived properties could also have been implemented using xref:userguide:fun:overview.adoc#mixins[mixins].

[IMPORTANT]
====
Be aware that all the state will ultimately converted into a URL-safe form (by way of the xref:refguide:applib-svc:UrlEncodingService.adoc[`UrlEncodingService`]).

There are limits to the lengths of URLs, however.
If the URL does exceed limits or contains invalid characters, then provide a custom implementation of xref:refguide:applib-svc:UrlEncodingService.adoc[`UrlEncodingService`] to handle the memento string in some other fashion (eg substituting it with a GUID, with the memento cached somehow on the server).
====

[#referencing-domain-entities]
=== Referencing Domain Entities

It's quite common for view models to be "backed by" (be projections of) some underlying domain entity.
For example, the `CompareCustomers` view model described xref:userguide:fun:view-models.adoc#jaxb[above] actually references two underlying ``Customer`` entities.

It wouldn't make sense to serialize out the state of a persistent entity.
However, the identity of the underlying entity is well defined; Apache Isis defines the xref:refguide:schema:common.adoc[common schema] which defines the `<oid-dto>` element (and corresponding `OidDto` class): the object's type and its identifier.
This is basically a formal XML equivalent to the `Bookmark` object obtained from the xref:refguide:applib-svc:BookmarkService.adoc[`BookmarkService`].

There is only one requirement to make this work: every referenced domain entity must be annotated with xref:refguide:applib-ant:XmlJavaTypeAdapter.adoc[`@XmlJavaTypeAdapter`], specifying the framework-provided `PersistentEntityAdapter`.
And this class is similar to the xref:refguide:applib-svc:BookmarkService.adoc[`BookmarkService`]: it knows how to create an `OidDto` from an object reference.

Thus, in our view model we can legitimately write:

[source,java]
----
public class CompareCustomers {

    @XmlElement(required = true)
    @Getter @Setter
    Customer customer1;
    ...
}
----

All we need to do is remember to add that `@XmlJavaTypeAdapter` annotation to the referenced entity:

[source,java]
----
@XmlJavaTypeAdapter(PersistentEntityAdapter.class)
public class Customer ...  {
    ...
}
----

It's also possible for a DTO view models to hold collections of objects.
These can be of any type, either simple properties, or references to other objects.
The only bit of boilerplate that is required is the `@XmlElementWrapper` annotation.
This instructs JAXB to create an XML element (based on the field name) to contain each of the elements.
(If this is omitted then the contents of the collection are at the same level as the properties; almost certainly not what is required).

For example, we could perhaps generalize the view model to hold a set of ``Customer``s to be compared:

[source,java]
----
public class CompareCustomers {
    ...
    @XmlElementWrapper
    @XmlElement(name = "customers")
    @Getter @Setter
    protected List<Customer> customersToCompare = Lists.newArrayList();
}
----

// This capability is particularly useful when the JAXB view model is being used as a xref:userguide:fun:view-models.adoc#dto[DTO].

[[joda-datatypes]]
=== JODA Time Datatypes

If your JAXB view model contains fields using the JODA datatypes (`LocalDate` and so on), then `@XmlJavaTypeAdapter` additional annotations in order to "teach" JAXB how to serialize out the state.

The Apache Isis applib provides a number of adapters to use out-of-the-box.
For example:

[source,java]
----
@XmlRootElement(name = "categorizeIncomingInvoice")
@XmlType(
        propOrder = {
                ...
                "dateReceived",
                ...
        }
)
@XmlAccessorType(XmlAccessType.FIELD)
public class IncomingInvoiceViewModel extends IncomingOrderAndInvoiceViewModel {

    @XmlJavaTypeAdapter(JodaLocalDateStringAdapter.ForJaxb.class)
    private LocalDate dateReceived;

    ...
}
----

The full list of adapter classes are:

.JAXB adapters
[cols="1a,2a",options="header"]
|===

| JODA datatype
| Adapter

.2+| `org.joda.time.DateTime`
| `JodaDateTimeStringAdapter.ForJaxb`
| `JodaDateTimeXMLGregorianCalendarAdapter.ForJaxb`

.2+| `org.joda.time.LocalDate`
| `JodaLocalDateStringAdapter.ForJaxb`
| `JodaLocalDateXMLGregorianCalendarAdapter.ForJaxb`

.2+| `org.joda.time.LocalDateTime`
| `JodaLocalDateTimeStringAdapter.ForJaxb`
| `JodaLocalDateTimeXMLGregorianCalendarAdapter.ForJaxb`


.2+| `org.joda.time.LocalTime`
| `JodaLocalTimeStringAdapter.ForJaxb`
| `JodaLocalTimeXMLGregorianCalendarAdapter.ForJaxb`

| `java.sql.Timestamp`
| `JavaSqlTimestampXmlGregorianCalendarAdapter.ForJaxb`


|===

[TIP]
====
If you want use other Joda data types, check out link:http://blog.bdoughan.com/2011/05/jaxb-and-joda-time-dates-and-times.html[this blog post].
====

[[non-jaxb]]
== Non-JAXB View Models

WARNING: TODO: this content has not yet been updated for v2.0

// TODO: v2: to simplify, think we should only support programmatic API (ViewModel), and JAXB.
// To support programmatic, reintroduce MementoService.
// Double check that view models are implicitly cloned even in this fashion.


Instead of using JAXB to specify a view model, it is also possible to use Apache Isis-specific annotations.

As was explained xref:userguide:fun:view-models.adoc[earlier], the approach is described here is neither as flexible nor as powerful as using the JAXB-style of view models.
It is however likely to be faster.

While the underlying technique is the same irrespective of use case, the programming model provides various ways of defining a view model so that the original intent is not lost.
They are:

.View model programming model
[cols="1a,4a,2a",options="header"]
|===

| Use case
| Code
| Description


| External entity
| WARNING: TODO EXTERNAL_ENTITY was removed, this use-case is still valid for consideration, what to do?
[source,java]
----
@DomainObject(nature=EXTERNAL_ENTITY)
public class CustomerRecordOnSAP {
    // ...
}
----
|Annotated with xref:refguide:applib-ant:DomainObject.adoc#nature[`@DomainObject#nature`] and a nature of `EXTERNAL_ENTITY`, with memento derived automatically from the properties of the domain object.
Collections are ignored, as are any properties annotated as xref:refguide:applib-ant:Property.adoc#snapshot[snapshot=EXCLUDED].

| In-memory entity
| WARNING: TODO INMEMORY_ENTITY was removed, this use-case is still valid for consideration, what to do?
[source,java]
----
@DomainObject(nature=INMEMORY_ENTITY)
public class Log4JAppender {
    // ...
}
----
|As preceding, but using a nature of `INMEMORY_ENTITY`.

|Application view model
|[source,java]
----
@DomainObject(nature=VIEW_MODEL)
public class Dashboard {
    // ...
}
----
|As preceding, but using a nature of `VIEW_MODEL`.

|Application view model
|
[source,java]
----
public class ExcelUploadManager implements ViewModel {
  public String viewModelMemento() {
    // ...
  }
  public void viewModelInit(String memento) {
    // ...
  }
}
----
|Implement xref:refguide:applib-cm:classes/super.adoc#AbstractViewModel[`ViewModel`] interface.
The memento is as defined by the interface's methods: the programmer has full control (but also full responsibility) for the string memento.

|===




[[view-model-interface]]
== `ViewModel` interface

WARNING: TODO: this content has not yet been updated for v2.0

