[#titleUiEvent]
= `titleUiEvent()`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


Whenever a domain object is to be rendered, the framework fires off a title UI event to obtain a title for the object.
This is as an alternative to implementing xref:refguide:applib-methods:reserved.adoc#title[`title()`] reserved method, or using the xref:system:generated:index/applib/annotation/Title.adoc[`@Title`] annotation, within the class itself.
(If either `title()` or `@Title` are present, then they will take precedence).

Subscribers subscribe through the xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`] and can use obtain a reference to the domain object from the event.
From this they can, if they wish, specify a title for the domain object using the event's API.

By default the event raised is `TitleUiEvent.Default`.
For example:

[source,java]
----
@DomainObjectLayout
public class ToDoItemDto {
    ...
}
----

The purpose of the `titleUiEvent` attribute is to allows a custom subclass to be emitted instead.
A similar attribute is available for icon names and CSS classes.

For example:

[source,java]
----
@DomainObjectLayout(
    titleUiEvent=ToDoItemDto.TitleUiEvent.class
)
public class ToDoItemDto {
    public static class TitleUiEvent
        extends org.apache.isis.applib.events.ui.TitleUiEvent<ToDoItemDto> { }
    ...
}
----

The benefit is that subscribers can be more targeted as to the events that they subscribe to.

== Subscribers

Subscribers (which must be domain services) subscribe to events posted through the xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`].

Subscribers can be either coarse-grained (if they subscribe to the top-level event type):

[source,java]
----
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;

@Service
public class SomeSubscriber {
    @EventListener(TitleUiEvent.class)
    public void on(TitleUiEvent ev) {
        if(ev.getSource() instanceof ToDoItemDto) {
            ...
        }
    }
}
----

or can be fine-grained (by subscribing to specific event subtypes):

[source,java]
----
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;

@Service
public class SomeSubscriber {
    @EventListener(ToDoItemDto.TitleUiEvent.class)
    public void on(ToDoItemDto.TitleUiEvent ev) {
        ...
    }
}
----

The subscriber should then use either `TitleUiEvent#setTranslatableTitle(...)` or `TitleUiEvent#setTitle(...)` to actually specify the title to be used.

== Default, Doop and Noop events

If the `titleUiEvent` attribute is not explicitly specified (is left as its default value, `TitleUiEvent.Default`), then the framework will, by default, post an event.

If this is not required, then the `isis.reflector.facet.domainObjectLayoutAnnotation.titleUiEvent.postForDefault` configuration property can be set to "false"; this will disable posting.

On the other hand, if the `titleUiEvent` has been explicitly specified to some subclass, then an event will be posted.
The framework provides `TitleUiEvent.Doop` as such a subclass, so setting the `titleUiEvent` attribute to this class will ensure that the event to be posted, irrespective of the configuration property setting.

And, conversely, the framework also provides `TitleUiEvent.Noop`; if `titleUiEvent` attribute is set to this class, thn no event will be posted.

== Raising events programmatically

Normally events are only raised for interactions through the UI.
However, events can be raised programmatically either by calling the xref:refguide:applib-svc:EventBusService.adoc[`EventBusService`] API directly, or as a result of calling the xref:refguide:applib-svc:TitleService.adoc[`TitleService`]'s `titleOf(...)` method.


