= DataNucleus Configuration
:page-role: -toc -narrow


:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

include::../section-hooks/isis.persistence.jdo-datanucleus.impl~pre.adoc[]

[cols="3a,2a,5a", options="header"]
|===
|Property
|Default
|Description
|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.ConnectionFactory2Name]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus. +
ConnectionFactory2Name

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.ConnectionFactoryName]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus. +
ConnectionFactoryName

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.ConnectionPasswordDecrypter]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus. +
ConnectionPasswordDecrypter

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.PersistenceUnitLoadClasses]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus. +
PersistenceUnitLoadClasses

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.cache.level2.mode]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.cache.level2.mode

| 
| Values of javax.persistence.SharedCacheMode, capitalized


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.cache.level2.type]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.cache.level2.type

|  none
| Name of the type of Level 2 Cache to use.

Can be used to interface with external caching products. Use "none" to turn off L2 caching.

See also Cache docs for JDO, and for JPA

NOTE: this config property isn't used by the framework, but is provided as a convenience for IDE autocomplete.


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.connection-factory-name]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus. +
connection-factory-name

| 
| The JNDI name for a connection factory for transactional connections.

For RBDMS, it must be a JNDI name that points to a javax.sql.DataSource object.

See also ``json`` (PascalCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but is provided as a convenience for IDE autocomplete.


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.connection-factory2-name]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus. +
connection-factory2-name

| 
| The JNDI name for a connection factory for non-transactional connections.

For RBDMS, it must be a JNDI name that points to a javax.sql.DataSource object.

See also ``json`` (PascalCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but is provided as a convenience for IDE autocomplete.


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.connection-password-decrypter]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus. +
connection-password-decrypter

| 
| Name of a class that implements ``DecryptionProvider`` and should only be specified if the password is encrypted in the persistence properties.

See also ``json`` (camelCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but is provided as a convenience for IDE autocomplete.


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.identifier.case]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.identifier.case

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.persistence-unit-load-classes]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus. +
persistence-unit-load-classes

|  true
| Used when we have specified the persistence-unit name for a PMF/EMF and where we want the datastore "tables" for all classes of that persistence-unit loading up into the StoreManager.

Defaults to true, which is the opposite of DataNucleus' own default. (The reason that DN defaults to false is because some databases are slow so such an operation would slow down the startup process).

See also ``json`` (camelCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but is provided as a convenience for IDE autocomplete.


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.persistenceByReachabilityAtCommit]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus. +
persistenceByReachabilityAtCommit

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.schema.auto-create-all]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.schema. +
auto-create-all

| 
| Whether DN should automatically create the database schema on bootstrapping.

This should be set to ``true`` when running against an in-memory database, but set to ``false`` when running against a persistent database (use something like flyway instead to manage schema evolution).

See also ``json`` (camelCasing instead of kebab-casing).

NOTE: this config property isn't used by the core framework, but is used by one the flyway extension.


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.schema.auto-create-database]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.schema. +
auto-create-database

| 
| Previously we defaulted this property to "true", but that could cause the target database to be modified

See also ``json`` (camelCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but is provided as a convenience for IDE autocomplete.


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.schema.autoCreateAll]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.schema. +
autoCreateAll

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.schema.autoCreateDatabase]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.schema. +
autoCreateDatabase

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.schema.validate-all]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.schema. +
validate-all

|  true
| See also ``json`` (camelCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but is provided as a convenience for IDE autocomplete.


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.schema.validateAll]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.schema. +
validateAll

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.schema.validateConstraints]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.schema. +
validateConstraints

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.schema.validateTables]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.schema. +
validateTables

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.datanucleus.transaction-type]]
isis.persistence.jdo-datanucleus. +
impl.datanucleus.transaction-type

| 
| Type of transaction to use.

If running under JavaSE the default is RESOURCE_LOCAL, and if running under JavaEE the default is JTA.

See also ``json`` (camelCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but is provided as a convenience for IDE autocomplete.


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.PersistenceManagerFactoryClass]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo. +
PersistenceManagerFactoryClass

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.option.ConnectionDriverName]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo.option. +
ConnectionDriverName

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.option.ConnectionPassword]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo.option. +
ConnectionPassword

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.option.ConnectionURL]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo.option. +
ConnectionURL

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.option.ConnectionUserName]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo.option. +
ConnectionUserName

| 
| null


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.option.connection-driver-name]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo.option. +
connection-driver-name

| 
| JDBC driver used by JDO/DataNucleus object store to connect.

See also ``json`` (PascalCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but provided as a convenience for IDE autocomplete (and is mandatory if using JDO Datanucleus).


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.option.connection-password]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo.option. +
connection-password

| 
| Password for the user account used by JDO/DataNucleus object store to connect.

See also ``json`` (PascalCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but provided as a convenience for IDE autocomplete. It is not necessarily mandatory, some databases accept an empty password.


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.option.connection-url]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo.option. +
connection-url

| 
| URL used by JDO/DataNucleus object store to connect.

See also ``json`` (PascalCasing instead of kebab-casing).

NOTE: some extensions (H2Console, MsqlDbManager) peek at this URL to determine if they should be enabled. Note that it is also mandatory if using JDO Datanucleus.


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.option.connection-user-name]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo.option. +
connection-user-name

| 
| User account used by JDO/DataNucleus object store to connect.

See also ``json`` (PascalCasing instead of kebab-casing).

NOTE: this config property isn't used by the framework, but provided as a convenience for IDE autocomplete (and is mandatory if using JDO Datanucleus).


|
[[isis.persistence.jdo-datanucleus.impl.javax.jdo.persistence-manager-factory-class]]
isis.persistence.jdo-datanucleus. +
impl.javax.jdo. +
persistence-manager-factory-class

|  org.datanucleus.api.jdo. +
JDOPersistenceManagerFactory
| See also ``json`` (camelCasing instead of kebab-casing).

NOTE: changing this property from its default is used to enable the flyway extension (in combination with ``Schema#isAutoCreateAll()``



|===

include::../section-hooks/isis.persistence.jdo-datanucleus.impl~post.adoc[]
