= Migrating from RC2 to RC3

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


== Programming Model

=== Removed

As previously marked deprecated for removal:

* `Action#hidden` ... use `ActionLayout#hidden` instead
* `Collection#hidden` ... use `CollectionLayout#hidden` instead
* `Property#hidden` ... use `PropertyLayout#hidden` instead
* `@LogicalTypeName(..)` ... use `@Named(..)` instead
* `DomainObjectLayoutData#plural` (XML)

== Utilities

=== YamlUtils

Expression of the global tag that contained the DTO class name was removed.
The yaml file will not start with `!!mypackage.Person` (or similar) anymore.

see https://medium.com/@snyksec/snakeyaml-2-0-solving-the-unsafe-deserialization-vulnerability-c29a0f08f152

== Artifacts

=== docgen

Package
`org.apache.causeway.extensions.docgen`
moved to
`org.apache.causeway.extensions.docgen.help`.

Module entry point
`org.apache.causeway.extensions.docgen.CausewayModuleExtDocgen`
moved to
`org.apache.causeway.extensions.docgen.help.CausewayModuleExtDocgenHelp`.

[source,xml]
.pom.xml
----
<!-- removed
<dependency>
	<groupId>org.apache.causeway.extensions</groupId>
	<artifactId>causeway-extensions-docgen</artifactId>
</dependency>
-->

<!-- instead use -->
<dependency>
	<groupId>org.apache.causeway.extensions</groupId>
	<artifactId>causeway-extensions-docgen-help</artifactId>
</dependency>
----

=== model4adoc

[source,xml]
.pom.xml
----
<!-- removed
<dependency>
	<groupId>org.apache.causeway.tooling</groupId>
	<artifactId>causeway-tooling-model4adoc</artifactId>
</dependency>
-->

<!-- instead use -->
<dependency>
	<groupId>org.apache.causeway.valuetypes</groupId>
	<artifactId>causeway-valuetypes-asciidoc-builder</artifactId>
</dependency>
----

== Extensions

=== CausewayModuleExtExcelDownloadWicketUi

Was relocated from
`org.apache.causeway.extensions.viewer.wicket.exceldownload.ui.CausewayModuleExtExcelDownloadWicketUi` to
`org.apache.causeway.extensions.exceldownload.wkt.ui.CausewayModuleExtExcelDownloadWicketUi`

