= ActionInvocationEvent
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

 _Supported only by xref:refguide:applib:index/services/wrapper/WrapperFactory.adoc[WrapperFactory] service,_ represents a check as to whether a particular argument for an action is valid or not.

If _#getReason()_ is not `null` then provides the reason why the set of arguments are invalid; otherwise the arguments are valid.

Called after each of the xref:refguide:applib:index/services/wrapper/events/ActionArgumentEvent.adoc[ActionArgumentEvent] s.

== API

[source,java]
.ActionInvocationEvent.java
----
class ActionInvocationEvent {
  ActionInvocationEvent(Object source, Identifier actionIdentifier, Object[] args)
  Object[] getArgs()
  void setArgs(Object[] args)
  Object getProposed()     // <.>
}
----

<.> xref:#getProposed__[getProposed()]
+
--
Does not apply
--

== Members

[#getProposed__]
=== getProposed()

Does not apply
