= IsisExtSecmanRegularUserRoleAndPermissions
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Role for regular users of the security module.

These permissions are intended to be sufficient for most regular users to have access to the 'safe' features provided by the core framework (in particular, everything under the _IsisModuleApplib#NAMESPACE isis.applib_ namespace.

That said, it does _not_ include the ability to impersonate other users (for this, grant the xref:refguide:extensions:index/secman/applib/role/seed/IsisSudoImpersonateRoleAndPermissions.adoc[IsisSudoImpersonateRoleAndPermissions] role), and also does _not_ include the ability to access the configuration properties (for this, grant the xref:refguide:extensions:index/secman/applib/role/seed/IsisSudoImpersonateRoleAndPermissions.adoc[IsisSudoImpersonateRoleAndPermissions] role).

The permissions also provide the ability to lookup their user account using the xref:refguide:extensions:index/secman/applib/user/menu/MeService.adoc[MeService] , and for viewing and maintaining their user details.

== API

[source,java]
.IsisExtSecmanRegularUserRoleAndPermissions.java
----
class IsisExtSecmanRegularUserRoleAndPermissions {
  IsisExtSecmanRegularUserRoleAndPermissions(SecmanConfiguration configBean)
}
----

