:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

[WARNING]
====
This feature is currently *not* supported by the _Wicket Viewer_; tracked by link:https://issues.apache.org/jira/browse/CAUSEWAY-1659[CAUSEWAY-1659]
====

If an action returns its target, then the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/ActionLayout.html#redirectpolicy[@ActionLayout#redirectPolicy] attribute determines
whether to update the page or instead to redirect (which redraws the enter page).
_This only has an effect on actions that return the object on which they are invoked, ie which return ``this``_.

The annotation is intended to be used in combination with link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/PropertyLayout.html#repainting[@PropertyLayout#repainting]`, which specifies that a property is immutable, expensive and should not be re-rendered if necessary.
The canonical use case is a blob property that holds a PDF, and which uses the link:https://causeway.apache.org/vw/2.0.0-RC1/pdfjs/about.html[pdf.js] viewer extension to render the PDF.
Such a PDF is immutable.
In such cases, not re-rendering that PDF provides a smoother UI experience.

== How this demo works

On the left hand side is a collection of entities, each of which has a counter and a PDF property.
The value of the PDF property is immutable and so is annotated with `@PropertyLayout#repainting` to disable repainting if possible.

The entity also has two actions that update a counter, and which both return `this`.
One of these is annotated with `@ActionLayout#redirectPolicy` to specify that the page should be updated; this should result in the PDF not being unnecessarily redrawn.

In terms of code:

* PDF blob
+
[source,java,indent=0]
----
include::ActionLayoutRedirectPolicyEntity.java[tags=class]
----
<.> render the blob as a PDF
<.> don't repaint the PDF if possible

* redirect even if the same
+
[source,java,indent=0]
----
include::ActionLayoutRedirectPolicyEntity_incrementRedirectOnlyIfDiffers.java[tags=class]
----
<.> suppress redirect if returning the same object
<.> return the same object

* redirect even if the same
+
[source,java,indent=0]
----
include::ActionLayoutRedirectPolicyEntity_incrementRedirectEvenIfSame.java[tags=class]
----
<.> redirect _even if_ returning the same object

