=== Default view

The xref:system:generated:index/applib/annotation/CollectionLayout.adoc#defaultView[`defaultView()] element is used to select which of views should be used by default for a given collection.
Without any hint the collection is shown collapsed (to save real estate and reduce load time).

For example:

[source,java]
----
import lombok.Getter;
import lombok.Setter;


public class BusRoute {

    @CollectionLayout( defaultView="table" )    // <.>
    @Getter @Setter
    private SortedSet<BusStop> stops = ...

}
----
<.> renders the collection as a table view.

The xref:vw:ROOT:about.adoc[Wicket viewer] allows additional views to be configured to render collections of objects, eg xref:vw:exceldownload:about.adoc[Excel Download] ("excel"), xref:vw:fullcalendar:about.adoc[Fullcalendar] ("fullcalendar") and xref:vw:gmap3:about.adoc[Gmap3] ("map") extensions.
This attribute can be used to select any of these alternative views instead.


As an alternative to using the annotation, the dynamic xref:userguide:fun:ui.adoc#object-layout[file-based layout] can be used instead.

