=== Hiding collections

The xref:refguide:applib:index/annotation/CollectionLayout.adoc#hidden[hidden()] element indicates where (in the UI) the collection should be hidden from the user.

[TIP]
====
It is also possible to use xref:refguide:applib:index/annotation/Collection.adoc#hidden[`@Collection#hidden`] to hide an action at the domain layer.
====

For example:

[source,java]
----
import lombok.Getter;
import lombok.Setter;

public class ToDoItem {

    @CollectionLayout(
        hidden=Where.EVERYWHERE
    )
    @Getter @Setter
    private SortedSet<ToDoItem> dependencies = ...
}
----

The acceptable values for the `where` parameter are:

* `Where.EVERYWHERE` or `Where.ANYWHERE`
+
The collection should be hidden everywhere.

* `Where.ANYWHERE`
+
Synonym for everywhere.

* `Where.OBJECT_FORMS`
+
The collection should be hidden when displayed within an object form.

* `Where.NOWHERE`
+
The collection should not be hidden.

The other values of the `Where` enum have no meaning for a collection.


As an alternative to using the annotation, the dynamic xref:userguide:fun:ui.adoc#object-layout[file-based layout] can be used instead.
