[[restful-image-property]]
= How parse images in RO viewer?

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


From this link:http://markmail.org/message/4kcu7sml4ufdsah3[thread] on the Apache Isis users mailing list:

* _I am trying to display an image in a JavaScript client app, the image comes from
   an Isis RO web service as a string, but it won't show.
Is there something I should do to change the message?_


The RO viewer returns the image as a string, in the form:

    "Tacos.jpg:image/jpeg:/9j//4AAQSkZJRgABAQEAlgCWAAD/  ...."

This is in the form:

    (filename):(mime type):(binary data in base64)

This is basically the xref:refguide:applib-cm:classes/value-types.adoc#Blob[`Blob`] value type, in string form.

To use, split the parts then format the mime type and base64 data correctly before using as source in an `<img>` tag.
