:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Apache Causeway implements the relevant JDO extension points to allow the link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/value/Blob.html[Clob] type to be persisted.
To do so correctly, it requires that the column names for the three constituent parts of a `Clob` are specified using `@Column`.
It's also necessary to specify the `jdbcType` to hold the characters.

== About this demo

On the left hand side of this page, four `Clob` properties are defined for a JDO entity, along with a variety of contributed properties and action.
The properties can variously be edited directly or through actions.

In terms of code:

* the entity class is:
+
[source,java]
----
include::CausewayClobJdo.java[tags=class]
----

* the `readOnlyProperty` (mandatory) property is mapped using:
+
[source,java,indent=0]
----
include::CausewayClobJdo.java[tags=property]
----

* while an optional property is mapped using:
+
[source,java,indent=0]
----
include::CausewayClobJdo.java[tags=optional-property]
----

while an optional property is mapped using:


include::../CausewayClobs-common.adoc[leveloffset=+1]
