= Mixins
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:


A xref:ug:fun:building-blocks.adoc#mixins[mixin] acts like a trait or extension method, allowing one module to contribute behaviour or derived state to another object.

Syntactically, a mixin is defined using either the xref:rg:ant:Mixin.adoc[`@Mixin`] annotation or using xref:rg:ant:DomainObject.adoc#nature[`@DomainObject#nature()`] attribute (specifying a nature of `Nature.MIXIN`).

// TODO: v2: perhaps we should get rid of @DomainObject#nature=MIXIN ?

[source,java]
----
@Mixin(method="coll")                                       // <1>
public class Customer_orders {                              // <2>

    private final Customer customer;
    public Customer_orders(final Customer customer) {       // <3>
        this.customer = customer;
    }

    @Action(semantics=SemanticsOf.SAFE)                     // <4>
    @ActionLayout(contributed=Contributed.AS_ASSOCIATION)   // <4>
    @CollectionLayout(defaultView="table")
    public List<Order> coll() {                             // <1>
        return repositoryService.findOrdersFor(customer);
    }

    @Inject
    RepositoryService repositoryService;
}
----
<1> indicates that this is a mixin, with "coll" as the name of the main method
<2> The contributed member is inferred from the name, after the "_"; in other words "orders"
<3> The mixee is `Customer`.
This could also be an interface.
<4> Indicates that the action should be interpreted as a collection.
This requires that the action has safe semantics, ie does not alter state/no side-effects.




