The "fileAccept" semantic specifies the file extension allowed when browsing for a file to upload:

* for properties, the semantic can be specified using either the `@Property` annotation, or a meta-annotation

* for parameters, the semantic can be specified using either the `@Parameter` annotation, or a meta-annotation.

This semantic applies only to ``Blob``s and ``Clob``s.


== Annotated

The fileAccept semantic can be specified explicitly using an annotation (on a `Blob` property):

* for properties, using `@Property#fileAccept()`:
+
[source,java,indent=0]
----
include::PropertyFileAcceptVm.java[tags=annotation]
----
<.> explicitly specifies that only PDFs can be accepted for the property

* for parameters, using `@Parameter#fileAccept()`:
+
[source,java,indent=0]
----
include::PropertyFileAcceptVm_updateWithParameterLayout.java[tags=annotation]
----
<.> explicitly specifies that only PDFs can be accepted for the parameter

This also works for ``Clob``s:

* for properties, using `@Property#fileAccept()`:
+
[source,java,indent=0]
----
include::PropertyFileAcceptVm.java[tags=annotation-clob]
----
<.> explicitly specifies that only PDFs can be accepted for the property

* for parameters, using `@Parameter#fileAccept()`:
+
[source,java,indent=0]
----
include::PropertyFileAcceptVm_updateClobWithParameterLayout.java[tags=annotation]
----
<.> explicitly specifies that only PDFs can be accepted for the parameter

The annotation could also be applied to a mixin, but would have little effect because mixin properties are always read-only.

== Meta-annotated

The fileAccept semantic can also be specified using a custom meta-annotation:

* the meta-annotation is defined as:
+
[source,java]
----
include::FileAcceptPdfMetaAnnotation.java[tags=class]
----
<.> annotated for property ...
<.> \... and also for parameter.
<.> annotation can be applied to a property (either its getter or the field directly)
<.> annotation can be applied to a parameter
<.> annotation can be applied to a type (ie, meta-meta annotations recursively)

* and can be applied to a property:
+
[source,java,indent=0]
----
include::PropertyFileAcceptVm.java[tags=meta-annotated]
----
<.> semantic is inherited from the meta-annotation

* or can be applied to a parameter:
+
[source,java,indent=0]
----
include::PropertyFileAcceptVm_updateWithMetaAnnotation.java[tags=meta-annotation]
----
<.> semantic is inherited from the meta-annotation


=== Meta-annotated Overridden

The meta-annotation can itself be overridden:

* in a property:
+
[source,java,indent=0]
----
include::PropertyFileAcceptVm.java[tags=meta-annotated-overridden]
----
<.> semantic from meta-annotation ...
<.> \... is overridden by the `@Property` annotation

* or a parameter:
+
[source,java,indent=0]
----
include::PropertyFileAcceptVm_updateWithMetaAnnotationOverridden.java[tags=meta-annotation-overridden]
----
<.> semantic from meta-annotation ...
<.> \... is overridden by the `@Parameter` annotation



