= `H2ManagerMenu`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `H2ManagerMenu` provides a single menu item to redirect to the H2 web console.
This is only enabled for prototyping, and only if H2 is detected in the underlying JDBC URL.
The menu appears under the "Prototyping" menu.


== API & Implementation

The API of the service is:

[source,java]
----
public class H2ManagerMenu {
    public void openH2Console() { ... }
}
----

Note that this launches the manager on the same host that the webapp runs, and so is only appropriate to use when running on `localhost`.

== Additional Configuration

The following additional configuration is also required (all of this is present in the helloworld and simpleapp archetypes):

* the h2 jdbc driver is required on the classpath of the webapp:
+
[source,xml]
.pom.xml
----
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
</dependency>
----

* the `jdbc:h2` URL configuration properties must be defined, eg in `isis.properties`:
+
[source,ini]
.isis.properties
----
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionDriverName=org.h2.Driver
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionURL=jdbc:h2:mem:test
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionUserName=sa
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionPassword=
----

* finally, and most importantly, the h2 console servlet must be configured in `web.xml`, and must be mapped to `/db`:
+
[source,xml]
.web.xml
----
<servlet>
    <servlet-name>H2Console</servlet-name>
    <servlet-class>org.h2.server.web.WebServlet</servlet-class>
    <init-param>
        <param-name>webAllowOthers</param-name>
        <param-value>true</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
</servlet>
<servlet-mapping>
    <servlet-name>H2Console</servlet-name>
    <url-pattern>/db/*</url-pattern>
</servlet-mapping>
----


== Disabling/hiding the menu

The menu can be hidden or disabled by subscribing to its domain event, eg:


[source,java]
----
import org.springframework.context.event.EventListener;

@DomainService(nature=DOMAIN)
public class HideH2ManagerMenu extends AbstractSubscriber {

    @EventListener(H2ManagerMenu.ActionDomainEvent.class)
    public void on(H2ManagerMenu.ActionDomainEvent ev) {
        ev.hide();
    }
}
----
