[[_ugfun_programming-model_domain-services_contributions]]
= Contributions (deprecated)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/



Services can contribute either actions, properties or collections, based on the type of their parameters.

[WARNING]
====
Contributed services should be considered a deprecated feature.
Instead, contribute the behaviour using xref:../ugfun/ugfun.adoc#_ugfun_building-blocks_mixins[mixins].
====

We suggest naming such classes `XxxContributions`, eg:

[source,java]
----
@DomainService(
    nature=NatureOfService.VIEW_CONTRIBUTIONS_ONLY              // <1>
)
@DomainServiceLayout(
    menuOrder="10",
    name="...",
}
public class OrderContributions {
    @Action(semantics=SemanticsOf.SAFE)
    @ActionLayout(contributed=Contributed.AS_ASSOCIATION)       // <2>
    @CollectionLayout(defaultView="table")
    public List<Order> orders(Customer customer) {              // <3>
        return container.allMatches(...);
    }

    @Inject
    CustomerRepository customerRepository;
}
----
<1> the service's actions should be contributed to the entities of the parameters of those actions
<2> contributed as an association, in particular as a collection because returns a `List<T>`.
<3> Only actions with a single argument can be contributed as associations

More information about contributions can be found xref:../ugfun/ugfun.adoc#_ugfun_how-tos_contributed-members[here].  More information
about using contributions and mixins to keep your domain application decoupled can be found xref:../ugfun/ugfun.adoc#_ugfun_building-blocks_types-of-domain-objects_mixins[here] and xref:../ugfun/ugfun.adoc#_ugfun_programming-model_domain-services_contributions[contributed services]).



