[[_ugfun_programming-model_mixins_inferred-name]]
= Inferred Name

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/




Where the mixin follows the naming convention `SomeType_mixinName` then the method name can be abbreviated, and the name of the member being contributed is inferred from the name of the class itself, beingeverything after the last '_'.

The default abbreviation to "$$".

For example:

[source,java]
----
@Mixin(method="act")
public class DocumentHolder_documents {

    private final DocumentHolder holder;
    public DocumentHolder_documents(DocumentHolder holder) { this.holder = holder; }

    @Action(semantics=SemanticsOf.SAFE)
    @ActionLayout(contributed = Contributed.AS_ASSOCIATION)
    @CollectionLayout(defaultView="table")
    public List<Document> act() {
        ...
    }
    public boolean hideAct() { ... }
}
----


Alternatively, if the xref:../rgant/rgant.adoc#_rgant-Mixin_method[`@Mixin#method()`] attribute is specified, then this can nominate a different abbreviation.

The examples above (for xref:../ugfun/ugfun.adoc#_ugfun_programming-model_mixins_contributed-property[property], xref:../ugfun/ugfun.adoc#_ugfun_programming-model_mixins_contributed-collection[collection] and xref:../ugfun/ugfun.adoc#_ugfun_programming-model_mixins_contributed-action[action]) demonstrate this.


The character "$" is also recognized as a separator between the mixin type and mixin name.
This is useful for mixins implemented as nested static types, discussed xref:../ugfun/ugfun.adoc#_ugfun_programming-model_mixins_nested-static-classes[below].

