[[_ugfun_programming-model_mixins]]
= Mixins

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../../
:_imagesdir: images/




Syntactically, a mixin is defined using either the xref:../rgant/rgant.adoc#_rgant_Mixin[`@Mixin`] annotation or using xref:../rgant/rgant.adoc#_rgant_DomainObject_nature[`@DomainObject#nature()`] attribute (specifying a nature of `Nature.MIXIN`).



[source,java]
----
@Mixin(method="coll")                                       // <1>
public class Customer_orders {                              // <2>

    private final Customer customer;
    public Customer_orders(final Customer customer) {       // <3>
        this.customer = customer;
    }

    @Action(semantics=SemanticsOf.SAFE)                     // <4>
    @ActionLayout(contributed=Contributed.AS_ASSOCIATION)   // <4>
    @CollectionLayout(render=RenderType.EAGERLY)
    public List<Order> coll() {                             // <1>
        return repositoryService.findOrdersFor(customer);
    }

    @Inject
    RepositoryService repositoryService;
}
----
<1> indicates that this is a mixin, with "coll" as the name of the main method
<2> The contributed member is inferred from the name, after the "_"; in other words "orders"
<3> The mixee is `Customer`.
This could also be an interface.
<4> Indicates that the action should be interpreted as a collection.
This requires that the action has safe semantics, ie does not alter state/no side-effects.







''''
''''

== Contributed services

Contributed services provide many of the same benefits as xref:../ugbtb/ugbtb.adoc#_ugbtb_decoupling_mixins[mixins];
indeed mixins are an evolution and refinement of the contributions concept.

[WARNING]
====
It's possible that contributions may be deprecated and eventually removed in a future version of the framework, to be replaced entirely by mixins.
====

The main difference between contributed services and mixins is that the actions of a contributed service will
contribute to _all_ the parameters of its actions, whereas a mixin only contributes to the type accepted in its
constructor.  Also, contributed services are long-lived
singletons, whereas mixins are instantiated as required (by the framework) and then discarded almost immediately.

[NOTE]
====
There's further useful information on contributed services in the reference guide, discussing the xref:../rgant/rgant.adoc#_rgant-DomainService_nature[@DomainService#nature()] attribute, for the `NatureOfService.VIEW_CONTRIBUTIONS_ONLY` nature.
====


=== Syntax

Any n-parameter action provided by a service will automatically be contributed to the list of actions for each of its (entity) parameters. From the viewpoint of the entity the action is called a contributed action.

For example, given a service:

[source,java]
----
public interface Library {
    public Loan borrow(Loanable l, Borrower b);
}
----

and the entities:

[source,java]
----
public class Book implements Loanable { ... }
----

and

[source,java]
----
public class LibraryMember implements Borrower { ... }
----

then the `borrow(...)` action will be contributed to both `Book` and to `LibraryMember`.

This is an important capability because it helps to decouple the concrete classes from the services.

If necessary, though, this behaviour can be suppressed by annotating the service action with `@org.apache.isis.applib.annotations.NotContributed`.

For example:

[source,java]
----
public interface Library {
    @NotContributed
    public Loan borrow(Loanable l, Borrower b);
}
----

If annotated at the interface level, then the annotation will be inherited by every concrete class. Alternatively the annotation can be applied at the implementation class level and only apply to that particular implementation.

Note that an action annotated as being `@NotContributed` will still appear in the service menu for the service. If an action should neither be contributed nor appear in service menu items, then simply annotate it as `@Hidden`.


## Contributed Action

NOTE: FIXME

## Contributed Property

NOTE: FIXME

## Contributed Collection

NOTE: FIXME





== Contributed Collection

The example below shows how to contribute a collection:

[source,java]
----
@Mixin
public class DocumentHolderDocuments {

    private final DocumentHolder holder;
    public DocumentHolderDocuments(DocumentHolder holder) { this.holder = holder; }

    @Action(semantics=SemanticsOf.SAFE)                         // <1>
    @ActionLayout(contributed = Contributed.AS_ASSOCIATION)     // <2>
    @CollectionLayout(render = RenderType.EAGERLY)
    public List<Document> documents() {                         // <3>
        ...
    }
    public boolean hideDocuments() { ... }                      // <4>
}
----
<1> required; actions that have side-effects cannot be contributed as collections
<2> required; otherwise the mixin will default to being rendered as an action
<3> must accept no arguments.
    The mixin is a collection rather than a property because the return type is a collection, not a scalar.
<4> supporting methods follow the usual naming conventions.
    (That said, in the case of collections, because the collection is derived/read-only, the only supporting method that is relevant is `hideXxx()`).

The above will result in a contributed collection for all types that implement/extend from `DocumentHolder` (so is probably for a mixin across modules).



== Contributed Property

Contributed properties are defined similarly, for example:

[source,java]
----
@Mixin
public class DocumentHolderMostRecentDocument {

    private final DocumentHolder holder;
    public DocumentHolderDocuments(DocumentHolder holder) { this.holder = holder; }

    @Action(semantics=SemanticsOf.SAFE)                         // <1>
    @ActionLayout(contributed = Contributed.AS_ASSOCIATION)     // <2>
    public Document> mostRecentDocument() {                     // <3>
        ...
    }
    public boolean hideMostRecentDocument() { ... }             // <4>
}
----
<1> required; actions that have side-effects cannot be contributed as collections
<2> required; otherwise the mixin will default to being rendered as an action
<3> must accept no arguments.
    The mixin is a property rather than a collection because the return type is a scalar.
<4> supporting methods follow the usual naming conventions.
    (That said, in the case of properties, because the property is derived/read-only, the only supporting method that is relevant is `hideXxx()`).


== Contributed Action

Contributed properties are defined similarly, for example:

[source,java]
----
@Mixin
public class DocumentHolderAddDocument {

    private final DocumentHolder holder;
    public DocumentHolderDocuments(DocumentHolder holder) { this.holder = holder; }

    @Action()
    @ActionLayout(contributed = Contributed.AS_ACTION)          // <1>
    public Document> addDocument(Document doc) {
        ...
    }
    public boolean hideAddDocument() { ... }                    // <2>
}
----
<1> recommended
<2> supporting methods follow the usual naming conventions.


== Inferred Name

Where the mixin follows the naming convention `SomeType_mixinName` then the method name can be abbreviated to "$$".
The mixin name is everything after the last '_'.

For example:

[source,java]
----
@Mixin
public class DocumentHolder_documents {

    private final DocumentHolder holder;
    public DocumentHolder_documents(DocumentHolder holder) { this.holder = holder; }

    @Action(semantics=SemanticsOf.SAFE)
    @ActionLayout(contributed = Contributed.AS_ASSOCIATION)
    @CollectionLayout(render = RenderType.EAGERLY)
    public List<Document> $$() {                                    // <1>
        ...
    }
    public boolean hide$$() { ... }                                 // <2>
}
----
<1> using "$$" as the reserved method name
<2> supporting methods as usual

The character "$" is also recognized as a separator between the mixin type and mixin name.
This is useful for mixins implemented as nested static types, discussed below.


== As Nested Static Classes

As noted in the introduction, while mixins were originally introduced as a means of allowing contributions from one module to the types of another module, they are also a convenient mechanism for grouping functionality/behaviour against a concrete type.
All the methods and supporting methods end up in a single construct, and the dependency between that functionality and the rest of the object is made more explicit.

When using mixins in this fashion, it is idiomatic to write the mixin as a nested static class, using the naming convention described above to reduce duplication.

For example:

[source,java]
----
public class Customer {

    @Mixin
    public static class placeOrder {                                            // <1>

        private final Customer customer;
        public documents(Customer customer) { this.customer = customer; }       // <2>

        @Action
        @ActionLayout(contributed = Contributed.AS_ACTION)
        public List<Order> $$(Product p, int quantity) {                        // <3>
            ...
        }
        public boolean hide$$() { ... }                                         // <4>
        public String validate0$$(Product p) { ...  }
    }
}
----
<1> Prior to `1.13.2`, had to be prefixed by an "_"; this is no longer required because "$" is also recognized as a way of parsing the class name in order to infer the mixin's name (eg `Customer$placeOrder`).
<2> typically contributed to concrete class
<3> using the "$$" reserved name
<4> supporting methods as usual


Moreover, the mixin class can be capitalized if desired.
Thus:

[source,java]
----
public class Customer {

    @Mixin
    public static class PlaceOrder {                                            // <1>

        private final Customer customer;
        public documents(Customer customer) { this.customer = customer; }       // <2>

        @Action
        @ActionLayout(contributed = Contributed.AS_ACTION)
        public List<Order> $$(Product p, int quantity) {                        // <3>
            ...
        }
        public boolean hide$$() { ... }                                         // <4>
        public String validate0$$(Product p) { ...  }
    }
}
----


In other words, all of the following are allowed:

* `public static class Documents { ... }`
* `public static class documents { ... }`
* `public static class _Documents { ... }`
* `public static class _documents { ... }`

The reserved method name "$$" can also be changed using xref:../rgant/rgant.adoc#_rgant_Mixin_method[`@Mixin#method()`] or xref:../rgant/rgant.adoc#_rgant_DomainObject_mixinMethod[`@DomainObject#mixinMethod()`].








== Programmatic usage

When a domain object is rendered, the framework will automatically instantiate all required mixins and delegate to them
dynamically.  If writing integration tests or fixtures, or (sometimes) just regular domain logic, then you may need to
instantiate mixins directly.

For this you can use the
xref:../rgsvc/rgsvc.adoc#_rgsvc_api_DomainObjectContainer_object-creation-api[`DomainObjectContainer#mixin(...)`
method.  For example:

[source,java]
----
DocumentHolder_documents mixin = container.mixin(DocumentHolder_documents.class, customer);
----

The xref:../ugtst/ugtst.adoc#__ugtst_integ-test-support_bootstrapping_IntegrationTestAbstract[`IntegrationTestAbstract`] and
xref:../rgcms/rgcms.adoc#_rgcms_classes_super_FixtureScript[`FixtureScript`] classes both provide a `mixin(...)` convenience
method.

