The framework has built-in support for all of the primitive data types, including `boolean`.

From here you can:

* navigate to an entity that uses the `boolean` datatype
* open a view model that uses the `boolean` datatype

Because `boolean` is a primitive value, the properties on these domain objects are mandatory.

== Common interface

The two domain objects both implement a common interface, `PrimitiveBooleanHolder`:

[source,java]
----
include::holder/PrimitiveBooleanHolder.java[tags=class]
----

== Mixin actions

A number of mixin actions contribute through this interface, demonstrate the use of `boolean` as a parameter and as a return type.
For example:

* the `updateReadOnlyProperty` action is:
+
[source,java]
----
include::holder/PrimitiveBooleanHolder_updateReadOnlyProperty.java[tags=class]
----

* the `actionReturning` action is:
+
[source,java]
----
include::holder/PrimitiveBooleanHolder_actionReturning.java[tags=class]
----

== Mixin properties

We also use the interface to contribute a mixin property:

* the `mixinProperty` property:
+
[source,java]
----
include::holder/PrimitiveBooleanHolder_mixinProperty.java[tags=class]
----

== @PropertyLayout(labelPosition=...)

To demonstrate support for label positions using `@PropertyLayout(labelPosition=...)`, the entity and view model objects both implement the extended `PrimitiveBooleanHolder2` interface:

[source,java]
----
include::holder/PrimitiveBooleanHolder2.java[tags=class]
----

<.> The default methods have annotations that are automatically inherited.
<.> Position to the left
<.> Uses `@MemberOrder` positions the properties into the appropriate `<field-set>` within the `Xxx.layout.xml` layout file.
<.> Position label on top
<.> Position label to the right
<.> Hide the label compleely.
