= DomainObjectLayoutData
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Describes the layout of the title and icon of a domain object, broadly corresponding to _org.apache.isis.applib.annotation.DomainObjectLayout_ .

== API

[source,java]
.DomainObjectLayoutData.java
----
class DomainObjectLayoutData {
  DomainObjectLayoutData()
  BookmarkPolicy getBookmarking()
  void setBookmarking(BookmarkPolicy bookmarking)
  String getCssClass()
  void setCssClass(String cssClass)
  String getCssClassFa()
  void setCssClassFa(String cssClassFa)
  CssClassFaPosition getCssClassFaPosition()
  void setCssClassFaPosition(CssClassFaPosition cssClassFaPosition)
  String getDescribedAs()
  void setDescribedAs(String describedAs)
  String getNamed()
  void setNamed(String named)
  String getPlural()
  void setPlural(String plural)
  String getMetadataError()     // <.>
  void setMetadataError(String metadataError)
  DomainObjectLayoutDataOwner getOwner()     // <.>
  void setOwner(DomainObjectLayoutDataOwner owner)
  Link getLink()     // <.>
  void setLink(Link link)
}
----

<.> xref:#getMetadataError__[getMetadataError()]
+
--
For diagnostics; populated by the framework if and only if a metadata error.
--
<.> xref:#getOwner__[getOwner()]
+
--
Owner.
--
<.> xref:#getLink__[getLink()]
+
--
The link to access this resource from the REST API (Restful Objects viewer).
--

== Members

[#getMetadataError__]
=== getMetadataError()

For diagnostics; populated by the framework if and only if a metadata error.

[#getOwner__]
=== getOwner()

Owner.

Set programmatically by framework after reading in from XML.

[#getLink__]
=== getLink()

The link to access this resource from the REST API (Restful Objects viewer).

Populated by the framework automatically.
