= FieldSet
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

A xref:refguide:applib:index/layout/component/MemberRegion.adoc[MemberRegion] of the page containing a set of related xref:refguide:applib:index/layout/component/PropertyLayoutData.adoc[PropertyLayoutData] and associated xref:refguide:applib:index/layout/component/ActionLayoutData.adoc[ActionLayoutData] .

== API

[source,java]
.FieldSet.java
----
class FieldSet {
  FieldSet()
  FieldSet(String name)
  String getId()     // <.>
  void setId(String id)
  Boolean isUnreferencedActions()     // <.>
  void setUnreferencedActions(Boolean unreferencedActions)
  Boolean isUnreferencedProperties()     // <.>
  void setUnreferencedProperties(Boolean unreferencedProperties)
  String getName()     // <.>
  void setName(String name)
  List<ActionLayoutData> getActions()
  void setActions(List<ActionLayoutData> actionLayoutDatas)
  List<PropertyLayoutData> getProperties()
  void setProperties(List<PropertyLayoutData> properties)
  FieldSetOwner getOwner()     // <.>
  void setOwner(FieldSetOwner owner)
  String getMetadataError()     // <.>
  void setMetadataError(String metadataError)
  String toString()
}
----

<.> xref:#getId__[getId()]
+
--
As per <div id="...">...</div> : must be unique across entire page.
--
<.> xref:#isUnreferencedActions__[isUnreferencedActions()]
+
--
Whether this fieldset should be used to hold any unreferenced actions (contributed or "native").
--
<.> xref:#isUnreferencedProperties__[isUnreferencedProperties()]
+
--
Whether this fieldset should be used to hold any unreferenced properties (contributed or "native").
--
<.> xref:#getName__[getName()]
+
--
Corresponds to the _PropertyLayout#fieldSetName()_ (when applied to properties).
--
<.> xref:#getOwner__[getOwner()]
+
--
Owner.
--
<.> xref:#getMetadataError__[getMetadataError()]
+
--
For diagnostics; populated by the framework if and only if a metadata error.
--

== Members

[#getId__]
=== getId()

As per <div id="...">...</div> : must be unique across entire page.

[#isUnreferencedActions__]
=== isUnreferencedActions()

Whether this fieldset should be used to hold any unreferenced actions (contributed or "native").

Any layout must have precisely one fieldset or xref:refguide:applib:index/layout/grid/bootstrap3/BS3Col.adoc[BS3Col] that has this attribute set.

[#isUnreferencedProperties__]
=== isUnreferencedProperties()

Whether this fieldset should be used to hold any unreferenced properties (contributed or "native").

Any grid layout must have precisely one fieldset that has this attribute set.

[#getName__]
=== getName()

Corresponds to the _PropertyLayout#fieldSetName()_ (when applied to properties).

[#getOwner__]
=== getOwner()

Owner.

Set programmatically by framework after reading in from XML.

[#getMetadataError__]
=== getMetadataError()

For diagnostics; populated by the framework if and only if a metadata error.
