= PropertyLayoutData
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Describes the layout of a single property, broadly corresponds to the _org.apache.isis.applib.annotation.PropertyLayout_ annotation.

== API

[source,java]
.PropertyLayoutData.java
----
class PropertyLayoutData {
  PropertyLayoutData()
  PropertyLayoutData(String id)
  String getId()     // <.>
  void setId(String id)
  String getCssClass()
  void setCssClass(String cssClass)
  String getDescribedAs()
  void setDescribedAs(String describedAs)
  Where getHidden()
  void setHidden(Where hidden)
  LabelPosition getLabelPosition()
  void setLabelPosition(LabelPosition labelPosition)
  Integer getMultiLine()
  void setMultiLine(Integer multiLine)
  String getNamed()
  void setNamed(String named)
  PromptStyle getPromptStyle()
  void setPromptStyle(PromptStyle promptStyle)
  RenderDay getRenderDay()
  void setRenderDay(RenderDay renderDay)
  Integer getTypicalLength()
  void setTypicalLength(Integer typicalLength)
  Repainting getRepainting()
  void setRepainting(Repainting repainting)
  List<ActionLayoutData> getActions()
  void setActions(List<ActionLayoutData> actionLayoutDatas)
  FieldSet getOwner()     // <.>
  void setOwner(FieldSet owner)
  String getMetadataError()     // <.>
  void setMetadataError(String metadataError)
  Link getLink()     // <.>
  void setLink(Link link)
  String toString()
}
----

<.> xref:#getId__[getId()]
+
--
Property identifier, being the getter method without 'get' or 'is' prefix, first letter lower cased.
--
<.> xref:#getOwner__[getOwner()]
+
--
Owner.
--
<.> xref:#getMetadataError__[getMetadataError()]
+
--
For diagnostics; populated by the framework if and only if a metadata error.
--
<.> xref:#getLink__[getLink()]
+
--
The link to access this resource from the REST API (Restful Objects viewer).
--

== Members

[#getId__]
=== getId()

Property identifier, being the getter method without 'get' or 'is' prefix, first letter lower cased.

[#getOwner__]
=== getOwner()

Owner.

Set programmatically by framework after reading in from XML.

[#getMetadataError__]
=== getMetadataError()

For diagnostics; populated by the framework if and only if a metadata error.

[#getLink__]
=== getLink()

The link to access this resource from the REST API (Restful Objects viewer).

Populated by the framework automatically.
