= ServiceActionLayoutData
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Describes the layout of a single action, broadly corresponding to _org.apache.isis.applib.annotation.ActionLayout_ .

== API

[source,java]
.ServiceActionLayoutData.java
----
class ServiceActionLayoutData {
  ServiceActionLayoutData()
  ServiceActionLayoutData(String logicalTypeName, String id)
  String getObjectType()
  void setObjectType(String objectType)
  String getId()     // <.>
  void setId(String id)
  BookmarkPolicy getBookmarking()
  void setBookmarking(BookmarkPolicy bookmarking)
  String getCssClass()
  void setCssClass(String cssClass)
  String getCssClassFa()
  void setCssClassFa(String cssClassFa)
  String getDescribedAs()
  void setDescribedAs(String describedAs)
  String getNamed()
  void setNamed(String named)
  Boolean getNamedEscaped()
  void setNamedEscaped(Boolean namedEscaped)
  ServiceActionLayoutDataOwner getOwner()     // <.>
  void setOwner(ServiceActionLayoutDataOwner owner)
  String getMetadataError()     // <.>
  void setMetadataError(String metadataError)
  Link getLink()     // <.>
  void setLink(Link link)
  String getLogicalTypeNameAndId()
  String toString()
}
----

<.> xref:#getId__[getId()]
+
--
Method name.
--
<.> xref:#getOwner__[getOwner()]
+
--
Owner.
--
<.> xref:#getMetadataError__[getMetadataError()]
+
--
For diagnostics; populated by the framework if and only if a metadata error.
--
<.> xref:#getLink__[getLink()]
+
--
The link to access this resource from the REST API (Restful Objects viewer).
--

== Members

[#getId__]
=== getId()

Method name.

Overloaded methods are not supported.

[#getOwner__]
=== getOwner()

Owner.

Set programmatically by framework after reading in from XML.

[#getMetadataError__]
=== getMetadataError()

For diagnostics; populated by the framework if and only if a metadata error.

[#getLink__]
=== getLink()

The link to access this resource from the REST API (Restful Objects viewer).

Populated by the framework automatically.
