= FakeDataService
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The main entry point for the fake data library, a domain service that provides the ability to obtain a random value for multiple different types.

Also provides _#javaFaker() access_ to the _Faker_ class which provides many more random instances, some relating to movies and tv shows.

== API

[source,java]
.FakeDataService.java
----
class FakeDataService {
  FakeDataService(ClockService clockService, RepositoryService repositoryService)
  void init()
  Faker javaFaker()     // <.>
  Names name()
  Comms comms()
  Lorem lorem()
  Addresses addresses()
  CreditCards creditCards()
  Books books()
  Bytes bytes()
  Shorts shorts()
  Integers ints()
  Longs longs()
  Floats floats()
  Doubles doubles()
  Chars chars()
  Booleans booleans()
  Strings strings()
  Collections collections()
  Enums enums()
  JavaUtilDates javaUtilDates()
  JavaSqlDates javaSqlDates()
  JavaSqlTimestamps javaSqlTimestamps()
  JavaTimeLocalDates javaTimeLocalDates()
  JavaTimeDateTimes javaTimeDateTimes()
  JavaTimePeriods javaTimePeriods()
  JodaLocalDates jodaLocalDates()
  JodaDateTimes jodaDateTimes()
  JodaPeriods jodaPeriods()
  BigDecimals bigDecimals()
  BigIntegers bigIntegers()
  Urls urls()
  Uuids uuids()
  IsisPasswords isisPasswords()
  IsisBlobs isisBlobs()
  IsisClobs isisClobs()
}
----

<.> xref:#javaFaker__[javaFaker()]
+
--
Access to the full API of the underlying javafaker library.
--

== Members

[#javaFaker__]
=== javaFaker()

Access to the full API of the underlying javafaker library.
