= JavaUtilDates
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Returns a random _java.util.Date_ , optionally based on the current time but constrained by a _Period_ .

The current time ('now') is obtained from the _org.apache.isis.applib.services.clock.ClockService_ .

== API

[source,java]
.JavaUtilDates.java
----
class JavaUtilDates {
  JavaUtilDates(FakeDataService fakeDataService)
  Date around(Period period)     // <.>
  Date before(Period period)     // <.>
  Date after(Period period)     // <.>
  java.util.Date any()     // <.>
}
----

<.> xref:#around__Period[around(Period)]
+
--
Returns a random date either before or after 'now', within the specified _Period_ .
--
<.> xref:#before__Period[before(Period)]
+
--
Returns a random date some time before 'now', within the specified _Period_ .
--
<.> xref:#after__Period[after(Period)]
+
--
Returns a random date some time after 'now', within the specified _Period_ .
--
<.> xref:#any__[any()]
+
--
Returns a random date 5 years around 'now'.
--

== Members

[#around__Period]
=== around(Period)

Returns a random date either before or after 'now', within the specified _Period_ .

[#before__Period]
=== before(Period)

Returns a random date some time before 'now', within the specified _Period_ .

[#after__Period]
=== after(Period)

Returns a random date some time after 'now', within the specified _Period_ .

[#any__]
=== any()

Returns a random date 5 years around 'now'.
