[[LayoutService]]
= `LayoutService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]
:page-partial:



The `LayoutService` provides the ability to obtain the XML layout for a single domain object or for all domain
objects.  This functionality is surfaced through the user interface through a related xref:applib:svc:metadata-api/LayoutService.adoc#related-mixins-and-menus[mixin and menu action].



== API & Implementation

The API defined by `LayoutService` is:

[source,java]
----
public interface LayoutService {
    String toXml(Class<?> domainClass, Style style);        // <1>
    byte[] toZip(Style style);                              // <2>
}
----
<1> Returns the serialized XML form of the layout (grid) for the specified domain class, in specified style (discussed below).
<2> Returns (a byte array) of a zip of the serialized XML of the layouts (grids), for all domain entities and view models.

The `Style` enum is defined as:

[source,java]
----
enum Style {
    CURRENT,
    COMPLETE,
    NORMALIZED,
    MINIMAL
}
----

The `CURRENT` style corresponds to the layout already loaded for the domain class, typically from an already persisted `layout.xml` file.
The other three styles allow the developer to choose how much metadata is to be specified in the XML, and how much (if any) will be obtained elsewhere, typically from annotations in the metamodel.
The table below summarises the choices:

.Table caption
[cols="<.>,^.>,^.>,^.>", options="header"]
|===

| Style
|xref:applib:ant:MemberGroupLayout.adoc[`@MemberGroupLayout`]
| xref:applib:ant:MemberOrder.adoc[`@MemberOrder`]
| xref:applib:ant:ActionLayout.adoc[`@ActionLayout`], xref:applib:ant:PropertyLayout.adoc[`@PropertyLayout`], xref:applib:ant:CollectionLayout.adoc[`@CollectionLayout`]


|`COMPLETE`
|serialized as XML
|serialized as XML
|serialized as XML


|`NORMALIZED`
|serialized as XML
|serialized as XML
|not in the XML


|`MINIMAL`
|serialized as XML
|not in the XML
|not in the XML

|===

As a developer, you therefore have a choice as to how you provide the metadata required for customised layouts:

* if you want all layout metadata to be read from the `.layout.xml` file, then download the "complete" version, and copy the file alongside the domain class.  You can then remove all `@MemberGroupLayout`, `@MemberOrder`, `@ActionLayout`, `@PropertyLayout` and `@CollectionLayout` annotations from the source code of the domain class.

* if you want to use layout XML file to describe the grid (columns, tabs etc) and specify which object members are associated with those regions of the grid, then download the "normalized" version.  You can then remove the `@MemberGroupLayout` and `@MemberOrder` annotations from the source code of the domain class, but retain the `@ActionLayout`, `@PropertyLayout` and `@CollectionLayout` annotations.

* if you want to use layout XML file ONLY to describe the grid, then download the "minimal" version.  The grid regions will be empty in this version, and the framework will use the `@MemberOrder` annotation to bind object members to those regions.  The only annotation that can be safely removed from the source code with this style is the `@MemberGroupLayout` annotation.




== Related Mixins and Menus

The service's functionality is exposed in the UI through a mixin (per object) and a menu action (for all objects):

* the xref:applib:cms:classes/mixins.adoc#Object[`Object` mixin] provides the ability to download the XML layout for
any domain object (entity or view model).

* the `LayoutServiceMenu` provides the ability to download all XML layouts as a single ZIP file (in any of the
three styles).

The XML can then be copied into the codebase of the application, and annotations in the domain classes removed as
desired.



== Related Domain Services

The xref:applib:svc:presentation-layer-spi/GridService.adoc[`GridService`] is responsible for loading and normalizing layout XML for
a domain class.  It in turn uses the xref:applib:svc:presentation-layer-spi/GridLoaderService.adoc[`GridLoaderService`] and  xref:applib:svc:presentation-layer-spi/GridSystemService.adoc[`GridSystemService`]
services.