=== Hiding actions

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:

The xref:refguide:applib:index/annotation/ActionLayout.adoc#hidden[hidden()] attribute indicates where (in the UI) the action should be hidden from the user.

[TIP]
====
It is also possible to use xref:refguide:applib:index/annotation/Action.adoc#hidden[`@Action#hidden`] to hide an action at the domain layer.
====

For example:

[source,java]
----
public class Customer {

    @ActionLayout(hidden=Where.EVERYWHERE)
    public void updateStatus() {
        // ...
    }
    ...
}
----

The acceptable values for the `where` parameter are:

* `Where.EVERYWHERE` or `Where.ANYWHERE`
+
The action should be hidden at all times.

* `Where.NOWHERE`
+
The action should not be hidden.

The other values of the `Where` enum have no meaning for a collection.


