=== Auditing

The xref:refguide:applib:index/annotation/DomainObject.adoc#entityChangePublishing[entityChangePublishing()] element indicates that if the object is modified, then each of its changed properties should be submitted to the registered xref:refguide:applib:index/services/publishing/spi/EntityPropertyChangeSubscriber.adoc[`EntityPropertyChangeSubscriber`](s).

The default value for the element is `AS_CONFIGURED`, meaning that the xref:refguide:config:sections/isis.applib.adoc#isis.applib.annotation.domain-object.entity-change-publishing[`isis.applib.annotation.domain-object.entity-change-publishing`] configuration property is used to determine the whether the action is audited:

* `all` +
+
all changed properties of objects are audited

* `none` +
+
no changed properties of objects are audited

If there is no configuration property in `application.properties` then auditing is automatically enabled for domain objects.

This default can be overridden on an object-by-object basis; if `entityChangePublishing()` is set to `ENABLED` then changed properties of instances of the domain class are audited irrespective of the configured value; if set to `DISABLED` then the changed properties of instances are _not_ audited, again irrespective of the configured value.

For example:

[source,java]
----
@DomainObject(
    entityChangePublishing=Publishing.ENABLED  // <.>
)
public class Customer {
    ...
}
----
<.> because set to enabled, will be audited irrespective of the configured value.



