:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

A number of the built-in domain services uses this annotation, including xref:refguide:applib:index/services/scratchpad/Scratchpad.adoc[Scratchpad] and xref:refguide:applib:index/services/queryresultscache/QueryResultsCache.adoc[QueryResultsCache].

You may find that these services must be injected using the `Provider` idiom, not directly.
For example:

[source,java]
----
@DomainService
public class SomeRepository {
   // ...
   @Inject Provider<QueryResultsCache> queryResultsCacheProvider;
}
----

If you forget to do this, then the framework will fail-fast with a suitable error message.

