:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/Property.html#maxlength[@Property#maxLength] attribute specifies the maximum length of the value that can be held by the property.
This corresponds to the number of characters that can be entered through the text field:

* for properties, the attribute can be specified using the `@Property` annotation

* for parameters, the attribute can be specified using the `@Parameter` annotation

This attribute applies only to strings.

[IMPORTANT]
====
For domain entities this semantic should be accompanied with `@Column(maxLength=...)` so that the persistence layer implements the same constraint.
====

== How this demo works

This page object has a single `name` property.
This can be edited directly, or can also be updated using an action.
Either way, a maximum length for the string is enforced.

In terms of code:

* to edit the property directly:
+
[source,java,indent=0]
.PropertyMaxLengthPage.java
----
include::PropertyMaxLengthPage.java[tags=name]
----
<.> explicitly specifies the maximum length that can be entered for the property


* to update using an action:
+
[source,java,indent=0]
.PropertyMaxLengthPage_updateName.java
----
include::PropertyMaxLengthPage_updateName.java[tags=annotation]
----
<.> explicitly specifies the maximum length that can be entered for the property


== See also

The link:https://causeway.apache.org/refguide/2.0.0-RC1/applib/index/annotation/PropertyLayout.html#typicallength[@PropertyLayout#typicalLength()] also pertains to string properties and parameters, and is a layout hint relating to the size of the textfield.
One would expect `typicalLength() \<= maxLength()`, but otherwise the two annotation attributes are not related.

