= Specifying components
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


TODO: v2: this is out of date; the way in which components are found is being reworked in v2.0.


Bootstrapping an Apache Isis application involves identifying both:

* the major components (authentication, persistence mechanisms, viewers) of Apache Isis, and also
* specifying the domain services and persistent entities that make up the application itself.

This is done using an xref:rg:cms:rgcms.adoc#_rgcms_classes_super_AppManifest[`AppManifest`], specified either programmatically or through the configuration properties.
This allows the components, services and entities to be specified from a single class.

To specify the `AppManifest` as a configuration property, use:

.Core Configuration Properties (ignored if `isis.appManifest` is present)
[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(_default value_)
|Implements

|`isis.appManifest`
|`FQCN`
|`o.a.i.applib.AppManifest` +

By convention this implementation resides in an `myapp-app` Maven module (as opposed to `myapp-dom` or `myapp-fixture`).
See the xref:ug:fun:getting-started/simpleapp-archetype.adoc[SimpleApp archetype] for details.

|===

From this the framework can determine the domain services, persistent entities and security (authentication and authorization) mechanisms to use.
Other configuration (including fixtures) can also be specified this way.

In the `AppManifest` itself, there are two methods which specify how authentication and authorisation are configured:

[source,java]
----
public interface AppManifest {
    ...
    String getAuthenticationMechanism();
    String getAuthorizationMechanism();
    ...
}
----

These can return either:

    * "shiro" - enable integration with Apache Shiro, as described in the xref:ug:sec:ugsec.adoc#[security] user guide
    * "bypass" - bypass security (in effect, configure a no-op implementation that allows everything).

Note that these are actually aliases for concrete implementations.
It is also possible to specify a fully qualified class name to replace either of the two security components, implementing the appropriate interface.






== Viewer Configuration

Viewers are specified by way of the filters and servlets in the xref:ug:btb:ugbtb.adoc#_ugbtb_web-xml[`web.xml`] file; these are not bootstrapped by the framework, rather it is the other way around.


