= Overview

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

In this section we run through the main building blocks that make up an Apache Causeway application.

The "big idea" of Apache Causeway is that you write only the domain logic, while the application takes care of the user interface.
There's a bit more to it than that, of course, and lots of interesting consequences, but that's the main gist.


[#type-of-domain-objects]
== Type of Domain Objects

From the end-user's perspective the UI displays a single domain object instance that has state.
These will be either a xref:domain-entities.adoc[domain entity] (persisted state) or a xref:view-models.adoc[view model] (user-specific temporary state).
To access them, a menu xref:domain-services.adoc[domain service] will be used to find from the database (a repository service) or occasionally to create a new instance (a factory service).

The state managed by entities and view models is expressed in terms of xref:object-members.adoc[properties and collections], with properties either referring to other domain objects or alternatively to values.
These values will have xref:value-types.adoc[value types] that are either built-in (such as primitives, strings or dates_, 3rd party or custom.

Actions allow the end-user to invoke business logic.
These are either defined as a regular method on a domain object (entity, view model or service), or can be "contributed" as a xref:mixins.adoc[mixin]: an important capability to help keep large applications decoupled.


== Annotations

Domain classes are generally recognized using annotations.
Apache Causeway defines its own set of annotations, and
you can generally recognize an Apache Causeway domain class because it will be probably be annotated using xref:refguide:applib:index/annotation/DomainObject.adoc[@DomainObject] and xref:refguide:applib:index/annotation/DomainService.adoc[@DomainService].
There are though configuration options that allow you to control to what extent (some) annotations can be inferred implicitly rather than  specified explicitly.

The framework also recognises some annotations from the ORM layer (ie JPA/EclipseLink or JDO/DataNucleus) and infers domain semantics from these annotations.
Similarly, JAXB annotations are often used for view models.

The framework also defines supplementary annotations, notably xref:refguide:applib:index/annotation/DomainObjectLayout.adoc[@DomainObjectLayout] and xref:refguide:applib:index/annotation/DomainServiceLayout.adoc[@DomainServiceLayout].
These provide hints relating to the layout of the domain object in the user interface.
Alternatively, these UI hints might be defined in a supplementary xref:userguide:ROOT:ui.adoc#object-layout[.layout.xml] file.


== Object Members

Every domain object in Apache Causeway consists of three types of members:

* properties, such as a ``Customer``'s `firstName`
* collections, such as a ``Customer``'s `orders` collection of ``Order``s
* actions, such as a ``Customer'``s `placeOrder(...)` method.

In addition, xref:mixins.adoc[mixins] can contribute both actions (ie behaviour) and derived (read-only) state to an underlying domain object.



include::partial$overview/business-rules.adoc[leveloffset=+1]
include::partial$overview/events.adoc[leveloffset=+1]
include::partial$overview/modules.adoc[leveloffset=+1]
include::partial$overview/programming-model.adoc[leveloffset=+1]


