= `regexPattern()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



There are three attributes related to enforcing regular expressions:

* The `regexPattern()` attribute validates the contents of any string property with respect to a regular expression pattern.
It is ignored if applied to properties of any other type.

* The `regexPatternFlags()` attribute specifies flags that modify the handling of the pattern.
The values are those that would normally be passed to `java.util.regex.Pattern#compile(String,int)`.

* The related `regexPatternReplacement()` attribute specifies the error message to show if the provided argument does not match the regex pattern.

For example:

[source,java]
----
public class Customer {
    @Property(
        regexPattern = "(\\w+\\.)*\\w+@(\\w+\\.)+[A-Za-z]+",
        regexPatternFlags=Pattern.CASE_INSENSITIVE,
        regexPatternReplacement = "Must be valid email address (containing a '@') symbol"   // <1>
    )
    public String getEmail() { /* ... */ }
}
----
<1> Note that there is currently no i18n support for this phrase.



== See also

This attribute can also be specified for xref:rg:ant:Parameter/regexPattern.adoc[parameters].

