= CollectionDomainEvent
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Fired whenever the framework interacts with a domain object's collection.

This is the specialization of xref:refguide:applib:index/events/domain/AbstractDomainEvent.adoc[AbstractDomainEvent] , for collections, * which should then be further subclassed by domain application. .

The class itself is instantiated automatically by the framework using a no-arg constructor; fields are set reflectively.

== API

[source,java]
.CollectionDomainEvent.java
----
class CollectionDomainEvent<S, T> {
  CollectionDomainEvent()     // <.>
  CollectionDomainEvent(S source)     // <.>
  String toString()
}
----

<.> xref:#CollectionDomainEvent__[CollectionDomainEvent()]
+
--
Subtypes can define a no-arg constructor; the framework sets state via (non-API) setters.
--
<.> xref:#CollectionDomainEvent__S[CollectionDomainEvent(S)]
+
--
Subtypes can define a one-arg constructor (for nested non-static classes of nested non-static mixins); the framework sets state via (non-API) setters.
--

== Members

[#CollectionDomainEvent__]
=== CollectionDomainEvent()

Subtypes can define a no-arg constructor; the framework sets state via (non-API) setters.

[#CollectionDomainEvent__S]
=== CollectionDomainEvent(S)

Subtypes can define a one-arg constructor (for nested non-static classes of nested non-static mixins); the framework sets state via (non-API) setters.
