= Editing _(enum)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The available policies for editing properties and collections.

== API

[source,java]
.Editing.java
----
enum Editing {
  AS_CONFIGURED     // <.>
  ENABLED     // <.>
  DISABLED     // <.>
  NOT_SPECIFIED     // <.>
}
----

<.> xref:#AS_CONFIGURED[AS_CONFIGURED]
+
--
The editing of the object should be as per the default editing policy configured in `application.properties` .
--
<.> xref:#ENABLED[ENABLED]
+
--
Audit changes to this object.
--
<.> xref:#DISABLED[DISABLED]
+
--
Do not allow the properties to be edited, or the collections to be added to/removed from.
--
<.> xref:#NOT_SPECIFIED[NOT_SPECIFIED]
+
--
Ignore the value provided by this annotation (meaning that the framework will keep searching, in meta annotations or superclasses/interfaces).
--

== Members

[#AS_CONFIGURED]
=== AS_CONFIGURED

The editing of the object should be as per the default editing policy configured in `application.properties` .

If no editing policy is configured, then the editing is enabled.

[#ENABLED]
=== ENABLED

Audit changes to this object.

[#DISABLED]
=== DISABLED

Do not allow the properties to be edited, or the collections to be added to/removed from.

[#NOT_SPECIFIED]
=== NOT_SPECIFIED

Ignore the value provided by this annotation (meaning that the framework will keep searching, in meta annotations or superclasses/interfaces).
