:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Intended to be annotated on the root marker class of a (Maven) module which contains a single coherent set of functionality, possibly including domain services.

A xref:refguide:applib:index/annotation/Module.adoc[Module] (because it's a meta-annotation) is also a Spring _Configuration @Configuration_ , which means that the functionality can be depended upon transitively using Spring's _Import @Import_ annotation. Normally the import graph mirrors the dependencies in Maven.

Also, a xref:refguide:applib:index/annotation/Module.adoc[Module] also declares the Spring _ComponentScan @ComponentScan_ (with no parameters), which means that any domain services in the same package or subpackages are automatically found and registered.

== API

[source,java]
.Module.java
----
@interface Module {
}
----

