/**
 * These files were (almost completely) GENERATED by org.apache.causeway.tooling.metaprog.demoshowcases.value.ValueTypeGenTemplateTest.
 *
 * The exception is for some datatypes that have custom `jdo` or `jpa` packages; a packages-info.java file indicates this.
 *
 * <p>
 * Do NOT edit!
 * </p>
 */
package demoapp.dom.types;