/**
 * Many of these files were GENERATED by org.apache.causeway.tooling.metaprog.demoshowcases.value.ValueTypeGenTemplateTest.
 *
 * The exception is for some datatypes that have custom `jdo` or `jpa` packages; a packages-info.java file indicates this.
 *
 * Oh, and where bugs have been raised, the generated .adoc files have been edited there also.
 *
 * <p>
 * Do NOT edit!
 * </p>
 */
package demoapp.dom.types;