[[ObjectContracts]]
= `ObjectContracts`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:


The `ObjectContracts` utility class provides a series of methods to make it easy for your domain objects to:

* implement `Comparable` (eg so can be stored in ``java.util.SortedSet``s)
* implement `toString()`
* implement `equals()`
* implement `hashCode()`

HOWEVER, be aware the class uses reflection heavily.

CAUTION: This class is only intended for use while prototyping.
It uses reflection heavily and is not performant.

For example:

[source,java]
----
import lombok.Getter;
import lombok.Setter;

public class ToDoItem implements Comparable<ToDoItem> {

    @Getter @Setter
    private boolean complete;

    @Getter @Setter
    private LocalDate dueBy;

    @Getter @Setter
    private String description;

    @Getter @Setter
    private String ownedBy;

    public int compareTo(final ToDoItem other) {
        return ObjectContracts.compare(this, other,
                    "complete","dueBy","description");
    }

    public String toString() {
        return ObjectContracts.toString(this,
                    "description","complete","dueBy","ownedBy");
    }
}
----

== Be aware of ORM loading issues

`ObjectContracts` implementation can cause DataNucleus to recursively rehydrate a larger number of associated entities (More detail below).

We therefore recommend that you disable
xref:refguide:config:sections/isis.persistence.jdo-datanucleus.impl.adoc#isis.persistence.jdo-datanucleus.impl.datanucleus.persistenceByReachabilityAtCommit[persistence-by-reachability] by adding:

[source,ini]
.persistor_datanucleus.properties
----
isis.persistence.jdo-datanucleus.impl.datanucleus.persistenceByReachabilityAtCommit=false
----

[plantuml]
----
hide empty members

class Party
class AgreementRole
class Agreement

Party <-r-> "0.*" AgreementRole
AgreementRole "0..*" <-r-> Agreement
----

In the course of a transaction, the `Agreement` entity is loaded into memory (not necessarily modified), and then new ``AgreementRole``s are associated to it.

All these entities implement `Comparable` using `ObjectContracts`, so that the implementation of ``AgreementRole``'s (simplified) is:

[source,java]
----
public class AgreementRole {
    ...
    public int compareTo(AgreementRole other) {
        return ObjectContracts.compareTo(this, other, "agreement","startDate","party");
    }
    ...
}
----

while ``Agreement``'s is implemented as:

[source,java]
----
    public class Agreement {
        ...
        public int compareTo(Agreement other) {
            return ObjectContracts.compareTo(this, other, "reference");
        }
        ...
    }
----

and ``Party``'s is similarly implemented as:

[source,java]
----
public class Party {
    ...
    public int compareTo(Party other) {
        return ObjectContracts.compareTo(this, other, "reference");
    }
    ...
}
----

DataNucleus's persistence-by-reachability algorithm adds the ``AgreementRole``s into a `SortedSet`, which causes `AgreementRole#compareTo()` to fire:

* the evaluation of the "agreement" property delegates back to the `Agreement`, whose own `Agreement#compareTo()` uses the scalar `reference` property.
As the `Agreement` is already in-memory, this does not trigger any further database queries

* the evaluation of the "startDate" property is just a scalar property of the `AgreementRole`, so will already in-memory

* the evaluation of the "party" property delegates back to the `Party`, whose own `Party#compareTo()` requires the uses the scalar `reference` property.
However, since the `Party` is not yet in-memory, using the `reference` property triggers a database query to "rehydrate" the `Party` instance.

In other words, figuring out whether `AgreementRole` is comparable requires the persistence-by-reachability algorithm to run, causing the adjacent associated entity `Party` to also be retrieved.
