[[_ugsec_api-for-applications]]
= API for Applications
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



Generally speaking your domain objects (or more generally your application) should be agnostic of the user/roles that are interacting with them; applying security permissions is the responsibility of the framework.

Still, on very rare occasion you may have a need, in which case you can either use Apache Isis' `UserService` API or you can reach further down the stack and use the JEE Servlet API.


== `UserService` API

The xref:../rgsvc/rgsvc.adoc#_rgsvc_core-domain-api_UserService[`UserService`] service exposes the following API:

[source,java]
----
final UserMemento user = userService.getUser();
final List<RoleMemento> roles = user.getRoles();
for (RoleMemento role : roles) {
    String roleName = role.getName();
    ...
}
----

Each role's `name` property encodes both the realm that provided the role, and the role identity itself.

For example, in the simpleapp, if logging in as `dick` with the following entries for `realm1`:

[source,ini]
----
dick = pass, user_role, analysis_role, self-install_role
----

then this corresponds to the roles "realm1:user_role", "realm1:self-install_role" and "realm1:analysis_role".

If using the Wicket viewer, then note there will also be another role which is used internally (namely "org.apache.isis.viewer.wicket.roles.USER").





== Servlet API

On occasion you may find it necessary to reach below Apache Isis and to the underlying servlet API.
For example, the (non-ASF) link:http://platform.incode.org[Incode Platform^]'s togglz module (non-ASF) has a requirement to do this in order to expose its embedded togglz web console.  (

[TIP]
====
If you do need to access the servlet API and are running within the context of Wicket viewer, the (non-ASF) link:http://platform.incode.org[Incode Platform^]'s servletapi module can provide access to the `HttpServletRequest`, `HttpServletResponse` and `ServletContext`.
====

In this situation, you can still obtain some information about the user and its roles:

[source,java]
----
Principal principal = httpServletRequest.getPrincipal();
String username = principal.getName();
boolean analyst = httpServletRequest.isUserInRole("analysis_role");
----

However, it isn't possible to obtain any role permissions for the user.
