[[_cgcom_verifying-releases]]
= Verifying a Release
:notice: licensed to the apache software foundation (asf) under one or more contributor license agreements. see the notice file distributed with this work for additional information regarding copyright ownership. the asf licenses this file to you under the apache license, version 2.0 (the "license"); you may not use this file except in compliance with the license. you may obtain a copy of the license at. http://www.apache.org/licenses/license-2.0 . unless required by applicable law or agreed to in writing, software distributed under the license is distributed on an "as is" basis, without warranties or  conditions of any kind, either express or implied. see the license for the specific language governing permissions and limitations under the license.
:_basedir: ../../
:_imagesdir: images/
:toc: right
include::__versions.adoc[]


The release process consists of:

* the release manager xref:../cgcom/cgcom.adoc#_cgcom_cutting-a-release[cutting the release]
* members of the Apache Isis PMC verifying and voting on the release (documented below)
* the release manager performing post-release tasks, for either a xref:../cgcom/cgcom.adoc#_cgcom_post-release-successful[successful] or an xref:../cgcom/cgcom.adoc#_cgcom_post-release-unsuccessful[unsuccessful] vote.

This section describes some guidance on what a voter (members of the Apache Isis PMC and anyone else who wishes) is expected to do before casting their vote in order to verify a release.



[[__cgcom_verifying-releases_background]]
== Background

Whenever a release manager announces a vote on a release (as per the xref:../cgcom/cgcom.adoc#_cgcom_release-process[release process]) on the xref:../../support.adoc#[dev mailing list], it is the responsibility of the project's PMC to cast their vote on the release.
Anyone else can also vote, but only members of the Apache Isis PMC's vote are binding.

Per this http://www.apache.org/dev/release.html[ASF documentation], the legal requirements for an ASF release are:

* a source zip file + corresponding signature (signed by the release manager, which is in the ASF web of trust and in our KEYS file)
* all source files have the Apache license (this is ensured by the running of the rat plugin prior to release; you could run it on the unzipped source)
* all dependencies are appropriately licensed; see the `DEPENDENCIES` file which is automatically generated from the POMs plus the supplemental-models.xml file

Note that the binaries are _not_ an ASF release, they merely exist on the Maven central repo as a convenience.
That said, you might also want to verify the release by pulling the binaries from the Maven staging repository.
Details of how to do this are also documented below.



[[__cgcom_verifying-releases_prerequisites]]
== Prerequisites

To verify the source ZIP files, you will need to have imported the public keys used for signing Apache Isis releases.
These can be downloaded from the root of the Apache Isis source tree.

Since the Apache Isis source is mirrored on github.com, you can just use:

[source,bash]
----
curl http://www.apache.org/dist/isis/KEYS > /tmp/KEYS
gpg --import /tmp/KEYS
----


Also, we will be rebuilding Isis from source.
Therefore delete all Isis artifacts from your local Maven repo:

[source,bash]
----
rm -rf ~/.m2/repository/org/apache/isis
----


[[__cgcom_verifying-releases_verifying-source-artifacts]]
== Verifying source artifacts

You can either verify the source artifacts xref:../cgcom/cgcom.adoc#\__cgcom_verifying-releases_manual-procedure[manually], or use a script that xref:../cgcom/cgcom.adoc#__cgcom_verifying-releases_automated-procedure[automates] the steps.


[[__cgcom_verifying-releases_manual-procedure]]
=== Manual procedure

The following section describes the steps to perform to manually verify a release.

==== Download the artifacts

Download both the ZIP and .ASC files from the location specified in the voting email.
To verify that the signature is correct, use:

[source,bash]
----
gpg --verify isis-x.y.z.zip.asc isis-x.y.z.zip
----

==== Building source artifacts

Assuming the ZIP file verifies, it should be unpacked, and then the artifact built from source.

To build Apache Isis core, first clean out the local repository cache:

[source]
----
rm -rf ~/.m2/repository/org/apache/isis
----

and then build using:

[source]
----
mvn clean install -Dskip.git
----

[IMPORTANT]
====
The `-Dskip.git` is required in order to temporarily disable the `git-commit-id-plugin` (which expects to be run within a git repository).
====


Optionally, confirm that the versions of the Isis artifacts now cached in your local repository are correct.


==== Verifying binary artifacts

You can verify the binary releases by configuring your local Maven install to point to the Maven staging repository (or repositories) and then using them, eg to run the xref:../ugfun/ugfun.adoc#_ugfun_getting-started_helloworld-archetype[HelloWorld archetype] or the xref:../ugfun/ugfun.adoc#_ugfun_getting-started_simpleapp-archetype[SimpleApp archetype] and running the resultant app.

Configuring your local Maven install amounts to updating the `~/.m2/settings.xml` file:

[source,xml]
----
<profiles>
    <profile>
        <id>verify-isis</id>
        <repositories>
            <repository>
                <id>isis-core-staging</id>
                <name>Isis Core Staging</name>
                <releases>
                    <enabled>true</enabled>
                    <updatePolicy>always</updatePolicy>
                    <checksumPolicy>warn</checksumPolicy>
                </releases>
                <url>http://repository.apache.org/content/repositories/orgapacheisis-10xx</url>
                <layout>default</layout>
            </repository>
            ...
        </repositories>
    </profile>
    ...
</profiles>
<activeProfiles>
    <activeProfile>verify-isis</activeProfile>
    ...
</activeProfiles>
----

where the repository URL is as provided in the VOTE email.
If there is more than one repository (as is sometimes the case if multiple components have been released), then repeat the <repository> section for each.

Once the vote has completed, the staging repositories will be removed and so you should deactive the profile (comment out the `&lt;activeProfile&gt;` element).
If you forget to deactive the profile, there should be no adverse effects; Maven will just spend unnecessary cycles attempting to hit a non-existent repo.




[[__cgcom_verifying-releases_automated-procedure]]
=== Automated procedure

To save some time in verifying an Apache Isis release we've assembled a script to automate the process.
The script is tested on Mac OSX and Linux. Windows users can use Cygwin or http://msysgit.github.io/[msysgit].

It's _recommended_ that you start this process in an empty directory:

[source,bash]
----
mkdir ~/verify-isis-release
cd ~/verify-isis-release
----


==== Copy script to local machine

Download this link:https://gist.github.com/danhaywood/9b052f68ef56cfdbeb3eb1603c5f772a[gist], save to `verify-isis-release.sh`.


==== Create an input file

The input file is a plain `urls.txt` file containing all urls to the packages to be verified.
Here's a sample of the release from Apache Isis 1.12.0:

[source]
----
http://repository.apache.org/content/repositories/orgapacheisis-1058/org/apache/isis/core/isis/1.12.0/isis-1.12.0-source-release.zip
http://repository.apache.org/content/repositories/orgapacheisis-1059/org/apache/isis/archetype/helloworld-archetype/1.12.0/helloworld-archetype-1.12.0-source-release.zip
http://repository.apache.org/content/repositories/orgapacheisis-1059/org/apache/isis/archetype/simpleapp-archetype/1.12.0/simpleapp-archetype-1.12.0-source-release.zip
----

You will find the actual list of URLs to be verified in the vote mail on the dev mailing list.



==== Execute the script

Execute...

[source,bash]
----
sh verify-isis-release.sh
----

\... and get yourself a cup of coffee.




[[__cgcom_verifying-releases_creadur]]
== (Optional) Creadur Tools

The http://creadur.apache.org[Apache Creadur] project exists to provide a set of tools to ensure compliance with Apache's licensing standards.

The main release auditing tool, http://creadur.apache.org/rat[Apache RAT] is used in the xref:../cgcom/cgcom.adoc#_cgcom_cutting-a-release[release process].

Creadur's remaining tools - link:http://creadur.apache.org/tentacles/[Tentacles] and link:http://creadur.apache.org/whisker/[Whisker] - are to support the verification process.

For example, Tentacles generates a report called `archives.html`.
This lists all of the top-level binaires, their `LICENSE` and `NOTICE` files and any `LICENSE` and `NOTICE` files of any binaries they may contain.

Validation of the output at this point is all still manual.
Things to check include:

* any binaries that contain no LICENSE and NOTICE files
* any binaries that contain more than one LICENSE or NOTICE file

In this report, each binary will have three links listed after its name '(licenses, notices, contents)'





== Test the archetypes

Assuming that everything builds ok, then test the archetypes (adjust version as necessary):

* First the `helloworld` archetype: +
+
[source,bash,subs="attributes+"]
----
mvn archetype:generate  \
    -D archetypeCatalog=local \
    -D archetypeGroupId=org.apache.isis.archetype \
    -D archetypeArtifactId=helloworld-archetype \
    -D archetypeVersion={isisrel} \
    -D groupId=com.mycompany \
    -D artifactId=myhelloworld \
    -D version=1.0-SNAPSHOT \
    -B \
    -o

cd myhelloworld
mvn clean install jetty:run -o
----
+
Adjust the version as necessary.

* Next, the `simpleapp` archetype: +
+
[source,bash,subs="attributes+"]
----
cd ..

mvn archetype:generate  \
    -D archetypeCatalog=local \
    -D archetypeGroupId=org.apache.isis.archetype \
    -D archetypeArtifactId=simpleapp-archetype \
    -D archetypeVersion={isisrel} \
    -D groupId=com.mycompany \
    -D artifactId=mysimpleapp \
    -D version=1.0-SNAPSHOT \
    -B \
    -o

cd mysimpleapp
mvn clean install -o && mvn -pl webapp jetty:run -o
----
+
Adjust the version as necessary.

If the archetypes run up ok, then it's time to xref:../cgcom/cgcom.adoc#_cgcom_verifying-releases[vote]!




== Casting a Vote

When you have made the above checks (and any other checks you think may be relevant), cast your vote by replying to the email thread on the mailing list.

If you are casting `-1`, please provide details of the problem(s) you have found.
