[[_cgcom_post-release-unsuccessful]]
= Post Release (Unsuccessful)
:notice: licensed to the apache software foundation (asf) under one or more contributor license agreements. see the notice file distributed with this work for additional information regarding copyright ownership. the asf licenses this file to you under the apache license, version 2.0 (the "license"); you may not use this file except in compliance with the license. you may obtain a copy of the license at. http://www.apache.org/licenses/license-2.0 . unless required by applicable law or agreed to in writing, software distributed under the license is distributed on an "as is" basis, without warranties or  conditions of any kind, either express or implied. see the license for the specific language governing permissions and limitations under the license.
:_basedir: ../../
:_imagesdir: images/
:toc: right
include::__versions.adoc[]


The release process consists of:

* the release manager xref:../cgcom/cgcom.adoc#_cgcom_cutting-a-release[cutting the release]
* members of the Apache Isis PMC xref:../cgcom/cgcom.adoc#_cgcom_verifying-releases[verifying] and voting on the release
* the release manager performing post-release tasks, for either a xref:../cgcom/cgcom.adoc#_cgcom_post-release-successful[successful] or an unsuccessful vote (latter documented below).

If the vote did not succeed (did not achieve +3 votes after 72 hours and/or is unlikely to do so), then the vote should be closed and the following steps performed.

Note that a release manager may also decide to cancel a vote before 72 hours has elapsed (for example if an error is quickly discovered).


== Inform dev ML

Post the results to the `dev@isis.a.o` mailing list.

For example, use the following subject for a vote on Apache Isis Core:

[source,bash]
----
[RESULT] [VOTE] Apache Isis Core release 2.0.0-M1
----

using the body (alter last line as appropriate):

[source,bash]
----
The vote has completed with the following result :

  +1 (binding): _list of names_
  +1 (non binding): _list of names_

  -1 (binding): _list of names_
  -1 (non binding): _list of names_

The vote is UNSUCCESSFUL.
----


== Tidy up branches

Tidy up remote branches in the git repo:

* delete the remote branch, for example: +
+
[source,bash]
----
git push --delete origin release-2.0.0-M1-RC1
----


* delete the remote origin server's tags, for example: +
+
[source,bash]
----
git push --delete origin isis-2.0.0-M1-RC1
git push --delete origin helloworld-archetype-2.0.0-M1-RC1
git push --delete origin simpleapp-archetype-2.0.0-M1-RC1
----


* delete the tags that were created locally, for example: +
+
[source,bash]
----
git tag -d isis-2.0.0-M1
git tag -d helloworld-archetype-2.0.0-M1
git tag -d simpleapp-archetype-2.0.0-M1
----


== Tidy up the Nexus repo

Drop staging repositories:

* drop the staging repository in http://repository.apache.org[Nexus]




== Reset

Finally, rewind the release branch to prior to the previous release candidate, and continue from there.




