= HasInteractionId_commandLogEntry
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Contributes a `commandLogEntry` property to any object implementing xref:refguide:applib:index/mixins/system/HasInteractionId.adoc[HasInteractionId] , in other words the command giving rise or related to the implementing object.

For example, the `AuditTrailEntry` entity (in the _audit trail_ extension), or the `ExecutionLogEntry` entity (in the _execution log_ extension) both implement xref:refguide:applib:index/mixins/system/HasInteractionId.adoc[HasInteractionId] .

== API

[source,java]
.HasInteractionId_commandLogEntry.java
----
class HasInteractionId_commandLogEntry {
  CommandLogEntry prop()
  boolean hideProp()     // <.>
}
----

<.> xref:#hideProp_[hideProp()]
+
--
Hide if the contributee is a xref:refguide:extensions:index/commandlog/applib/dom/CommandLogEntry.adoc[CommandLogEntry] , because we don't want to navigate to ourselves, and there are other ways to navigate to the parent or child commands.
--

== Members

[#hideProp_]
=== hideProp()

Hide if the contributee is a xref:refguide:extensions:index/commandlog/applib/dom/CommandLogEntry.adoc[CommandLogEntry] , because we don't want to navigate to ourselves, and there are other ways to navigate to the parent or child commands.
