[[i18n-label-in-wicket-viewer]]
= How i18n the Wicket viewer?

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.



From link:http://isis.markmail.org/thread/ctppmtcbsf4iskzi[this thread] on the Apache Isis users mailing list:

* _I am trying to internationalize the label descriptions of form actions, eg those in `ActionParametersFormPanel`.
Referencing those via their message id inside a .po file didn't work either.
Can this be done?_


Yes, it _is_ possible to internationalize both the Wicket viewer's labels as well as the regular translations of the domain object metadata using the `.po` translation files as supported by the xref:system:generated:index/applib/services/i18n/TranslationService.adoc[`TranslationService`].

Full details of the ``msgId``s that must be added to the `translations.po` file can be found in xref:userguide:btb:i18n.adoc#wicket-viewer[i18n] section of the xref:userguide:btb:about.adoc[beyond the basics] guide.

