[[_ug_restfulobjects-viewer_configuration-properties_suppressing-elements]]
= Suppressing elements of the representation
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



The representations specified by the http://restfulobjects.org[Restful Object spec] are very rich in hypermedia controls and metadata, intended to support a wide variety of possible REST clients. However, if an application is providing its REST API only for a small well-defined set of REST clients, then it is possible to suppress (remove) various elements of these representations.

This is done by globally using the following properties (typically added to `WEB-INF/viewer_restfulobjects.properties`):

[source,ini]
----
isis.viewer.restfulobjects.suppressDescribedByLinks=true      # <1>
isis.viewer.restfulobjects.suppressUpdateLink=true            # <2>
isis.viewer.restfulobjects.suppressMemberId=true              # <3>
isis.viewer.restfulobjects.suppressMemberLinks=true           # <4>
isis.viewer.restfulobjects.suppressMemberExtensions=true      # <5>
isis.viewer.restfulobjects.suppressMemberDisabledReason=true  # <6>
----
<1> suppresses the "describedby" links (on all representations)
<2> suppresses the  "update" link (on object representation)
<3> suppresses the  "id" json-prop for object members (on object representation and member detail representations)
<4> suppresses the  "links" json-prop for object members (on the object representation and member detail representations)
<5> suppresses the  "extensions" json-prop for object members (on the object representation and member detail representations)
<6> suppresses the  "disabledReason" json-prop for object members (on the object representation and member detail representations)

The defaults for all of these is false, meaning that the hypermedia/metadata is NOT suppressed.

[NOTE]
====
In the future we might extend this per-request.  Raise/vote on a JIRA ticket if you require this feature.
====

If an even simpler representations (of objects) are required, see xref:_simplified_object_representation[simplified object representation], immediately below.  And if the above isn't flexible and you need complete control over all representations see the section on xref:_extending_the_restful_viewer[Extending the Restful viewer] in the <<Extending>> chapter.



