= anchor:deployment[]Neo4J
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

As of 1.8.0 Apache Isis has experimental support for Neo4J, courtesy of DataNucleus' http://www.datanucleus.org/products/datanucleus/datastores/neo4j.html[Neo4J Datastore] implementation.

The xref:__a_id_getting_started_a_simpleapp_archetype[SimpleApp archetype] has been updated so that they can be optionally run under Neo4J.

[TIP]
====
In addition, the http://github.com/isisaddons/isis-app-neoapp}[Isis addons' neoapp] (non-ASF) is configured to run with an embedded Neo4J server running alongside the Isis webapp.
====

The steps below describe the configuration steps required to update an existing app.

== ConnectionURL

In `persistor.properties`, update the JDO `ConnectionURL` property, eg:

[source,ini]
----
isis.persistor.datanucleus.impl.javax.jdo.option.ConnectionURL=neo4j:neo4j_DB
----

The other connection properties (`ConnectionDriverName`, `ConnectionUserName` and `ConnectionPassword`) should be commented out.

== Update pom.xml

Add the following dependency to the `webapp` project's `pom.xml`:

[source,xml]
----
<dependencies>
    ...
    <dependency>
        <groupId>org.datanucleus</groupId>
        <artifactId>datanucleus-neo4j</artifactId>
        <version>3.2.3</version> <!--1-->
    </dependency>
    ...
</dependencies>
----
<1> for 1.8.0, use the value shown.  for 1.9.0-SNAPSHOT, use 4.0.5.

In the xref:__a_id_getting_started_a_simpleapp_archetype[SimpleApp archetype] this is defined under the "neo4j" profile so can be activated using `-P neo4j`.

== Try it out!

If you want to quickly try out neo4j for yourself:

* run the xref:__a_id_getting_started_a_simpleapp_archetype[SimpleApp archetype] (v1.8.0)

* build the app:

* run the app:

If you visit the about page you should see the neo4j JAR files are linked in, and a `neo4j_DB` subdirectory within the `webapp` directory.
