[[_ug_reference-services-spi_manpage-BackgroundCommandService]]
= `BackgroundCommandService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

IMPORTANT: TODO


== Isis Addons Implementation

For 1.7.0+, see the http://github.com/isisaddons/isis-module-command[Isis addons' Command module] (non-ASF).



The `BackgroundCommandService` supports the xref:_ug_reference-services-api_manpage-BackgroundService[`BackgroundService`], persisting action invocations as commands such that they can subsequently be invoked in the background.

The `BackgroundService` is responsible for capturing a memento representing the action invocation, and then hands off to the xref:_ug_reference-services-spi_manpage-BackgroundCommandService[`BackgroundCommandService`] `BackgroundCommandService` to actually persist it. The (non-ASF) http://github.com/isisaddons/isis-module-command[Isis addons' command] module provides an implementation of `BackgroundCommandService` that persists to an RBMS entities.

The persisting of commands is only half the story; there needs to be a separate process to read the commands and execute them. The abstract xref:_ug_reference-services-api_manpage-BackgroundService_BackgroundCommandExecution[`BackgroundCommandExecution`] provides a mechanism to do this.  The (non-ASF) http://github.com/isisaddons/isis-module-command[Isis addons' command] module provides a concrete subclass (`BackgroundCommandExecutionFromBackgroundCommandServiceJdo`) that knows how to query for persisted (background) `Command`s such that they can be executed by a scheduler.



== BackgroundCommandService

The `BackgroundCommandService` typically isn't called from domain classes, but it exists as a domain service so that it is pluggable into `BackgroundService`.

=== API

The API of the `BackgroundCommandService` is:

[source,java]
----
public interface BackgroundCommandService {

    public void schedule(
            final ActionInvocationMemento aim,
            final Command command,
            final String targetClassName, final String targetActionName, final String targetArgs);

}
----

where `ActionInvocationMemento` is a wrapper around a xref:_ug_reference-services-api_manpage-MementoService[`MementoService`]'s `Memento`, capturing the details of an action invocation (for execution later on).

For the record, the API of `ActionInvocationMemento` is:

[source,java]
----
public class ActionInvocationMemento {

    public String getActionId() { ... }
    public String getTargetClassName() { ... }
    public String getTargetActionName() { ... }
    public Bookmark getTarget() { ... }
    public int getNumArgs() { ... }
    public Class<?> getArgType(final int num) throws ClassNotFoundException { ... }
    public <T> T getArg(final int num, final Class<T> type) { ... }

    public String asMementoString() { ... }
}
----

The `asMementoString()` method therefore lets the `BackgroundCommandService` implementation convert the action invocation into a simple string.

=== Implementation

The (non-ASF) http://github.com/isisaddons/isis-module-command[Isis addons' command] module provides the  `BackgroundCommandServiceJdo` implementation that persists `Command`s to an RDBMS.

There is also a supporting repository to query persisted background `Command`s:

* `org.apache.isis.objectstore.jdo.applib.service.background.BackgroundCommandServiceJdoRepository`

In addition, there is a supporting contributions service that contributes actions for searching for persisted child and sibling `Command`s:

* `org.apache.isis.objectstore.jdo.applib.service.background.BackgroundCommandServiceJdoContributions`

=== Usage

As noted above, this service isn't intended to be called from domain classes; rather it acts as a plug-in point to the default `BackgroundServiceDefault` service.

== Related Services

As discussed above, this service supports the xref:_ug_reference-services-api_manpage-BackgroundService[`BackgroundService`] , persisting `Command`s such that they can be executed in the background.

There is also a tie-up with the xref:_ug_reference-services-api_manpage-CommandContext[`CommandContext`] and its supporting xref:_ug_reference-services-spi_manpage-CommandService[`CommandService`] domain service. The `CommandContext` service is responsible for providing a parent `Command` with which the background `Command`s can then be associated as children, while the `CommandService` is responsible for persisting those parent `Command`s (analogous to the way in which the `BackgroundCommandService` persists the child background `Command`s). The `BackgroundCommandService` ensures that these background `Command`s are associated with the parent "foreground" `Command`.

What that means is that the implementations of `CommandService` and `BackgroundCommandService` go together, hence both implemented in the (non-ASF) http://github.com/isisaddons/isis-module-command[Isis addons' command] module.).

== BackgroundCommandExecution concrete implementation

The `BackgroundCommandExecution` (in isis-core) is an abstract template class provided by isis-core that defines an abstract hook method to obtain background `Command`s to be executed:

[source,java]
----
public abstract class BackgroundCommandExecution
                         extends AbstractIsisSessionTemplate {
    ...
    protected abstract List<? extends Command> findBackgroundCommandsToExecute();
    ...
}
----

The developer is required to implement this hook method in a subclass.

The `isis-module-command-jdo` module provides a concrete subclass that queries for commands persisted by its `BackgroundCommandServiceJdo`, namely:

* `org.apache.isis.objectstore.jdo.service.BackgroundCommandExecutionFromBackgroundCommandServiceJdo`

== Quartz Scheduler Configuration

Details are provided on the xref:_ug_reference-services-api_manpage-BackgroundService[`BackgroundService`] page.

== Registering the Services

Assuming that the `configuration-and-annotation` services installer is configured:

[source,ini]
----
isis.services-installer=configuration-and-annotation
----

then the `BackgroundCommandServiceJdo` and `BackgroundCommandJdoRepository` services are automatically registered if the `isis-module-command-jdo` module is on the classpath. The `BackgroundCommandServiceJdoContributions` service (because it influences the user interface) must be explicitly registered:

[source,ini]
----
isis.services=...,\
              org.apache.isis.objectstore.jdo.applib.service.background.BackgroundCommandServiceJdoContributions,\
              ...
----