= anchor:reference-annotations_manpage-[]`@ViewModelLayout`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `@ViewModelLayout` annotation is identical to the link:./DomainObjectLayout.html[@DomainObjectLayout], but is provided
for symmetry with domain objects that have been annotated using xref:__a_id_reference_annotations_manpage_a_code_viewmodel_code[`@ViewModel`] (rather than xref:__a_id_reference_annotations_manpage_a_code_domainobject_code[`@DomainObject(nature=VIEW_MODEL)`]).


The table below summarizes the annotation's attributes.

.`@Action` attributes
[cols="2,2,4", options="header"]
|===

| Attribute
| Values (default)
| Description


|xref:__a_id_reference_annotations_manpage_viewmodellayout_a_code_cssclass_code[`cssClass()`]
|
|


|xref:__a_id_reference_annotations_manpage_viewmodellayout_a_cssclassfa[`cssClassFa()`]
|
|


|`cssClassFaPosition()`
|
|


|xref:__a_id_reference_annotations_manpage_viewmodellayout_a_code_describedas_code[`describedAs()`]
|
|


|xref:__a_id_reference_annotations_manpage_viewmodellayout_a_code_named_code[`named()`]
|
|


|xref:__a_id_reference_annotations_manpage_viewmodellayout_a_code_paged_code[`paged()`]
|
|


|xref:__a_id_reference_annotations_manpage_viewmodellayout_a_code_plural_code[`plural()`]
|
|

|===





[source,java]
----
@ViewModel(...)
@ViewModelLayout(...)
public class MyViewModel { ... }
----





== anchor:reference-annotations_manpage-ViewModelLayout[]`cssClass()`

IMPORTANT: WIP ... this section

The `CssClass` annotation applies to object and also to any object member (property, collection or action). It is used by the Wicket viewer as a UI hint to render specified CSS classes around the representation of the element.

Application-specific CSS can then be used to target and adjust the UI representation of that particular element.

For example:

[source,java]
----
@CssClass("x-main")
public class ToDoItem { ... }
----


=== Alternatives (`.layout.json`)

As an alternative to using the `@CssClass` annotation, the `.layout.json`
link:../../components/viewers/wicket/dynamic-layouts.html[dynamic layout file]
can be specified, eg:

[source,javascript]
----
{
    "span": 6,
    "memberGroups": {
        "Priority": {
            "members": {
                ...
                "dueBy": {
                    "cssClass": { "value": "x-key" }
                }
                ....
            }
        },
        ...
    }
}
----

Note that this (currently) only supports class members, not classes



[NOTE]
====
The similar link:./CssClassFa-deprecated.html[CssClassFa] annotation is also used as a hint to apply CSS, but in particular to allow http://fortawesome.github.io/Font-Awesome/icons/[Font Awesome icons] to be rendered on action butotns or as the icon for classes.
====










== anchor:reference-annotations_manpage-ViewModelLayout[]`cssClassFa()`



=== `cssClassFa()

IMPORTANT: WIP ... this section


The `CssClassFa` annotation applies to objects and also to object actions,
and is used by the Wicket viewer as a UI hint.

For object actions, the viewer will render the specified
http://fortawesome.github.io/Font-Awesome/icons/[Font Awesome icon]
on the action's button (or menu item).

For objects, it will be used as an icon. Note that this is only used if
the object does not have a `getIconName()` method.

For example:

[source,java]
----
@CssClassFa("fa-check-circle")
public class ToDoItem { ... }
----

or

[source,java]
----
public class ToDoItem {

    @CssClass("fa-step-backward")
    public ToDoItem previous() { ... }

    @CssClass("fa-step-forward")
    public ToDoItem next() { ... }

}
----

There can be multiple "fa-" classes, eg to mirror or rotate the icon. There
is no need to include the "fa" class; it will be automatically appended.

=== Alternatives (`.layout.json`)

As an alternative to using the `@CssClass` annotation, the `.layout.json`
link:../../components/viewers/wicket/dynamic-layouts.html[dynamic layout file]
can be specified, eg:

[source,javascript]
----
{
    "span": 6,
    "memberGroups": {
        "Priority": {
            "members": {
                ...
                 "relativePriority": {
                    "actions": {
                        "previous": {
                            "cssClassFa": { "value": "fa-step-backward" }
                        },
                        "next": {
                            "cssClassFa": { "value": "fa-step-forward" }
                        }
                    }
                },
                ....
            }
        },
        ...
    }
}
----

Note that this (currently) only supports class members, not classes.



[NOTE]
====
The similar link:./CssClass-deprecated.html[CssClass] annotation is also used as a hint to apply CSS, but for wrapping the representation of an object or object member so that it can be styled in an application-specific way.

====


=== `cssClassFaPosition()

IMPORTANT: WIP ... this section







== anchor:reference-annotations_manpage-ViewModelLayout[]`describedAs()`

IMPORTANT: WIP ... this section


The `@DescribedAs` annotation is used to provide a short description of something that features on the user interface. How this description is used will depend upon the viewing mechanism - but it may be thought of as being like a 'tool tip'.

Descriptions may be provided for objects, members (properties, collections and actions), and for individual parameters within an action method. `@DescribedAs` therefore works in a very similar manner to `@Named` <!--(see ?)-->.


For example:

[source,java]
----
public class Customer {
    @DescribedAs("The name that the customer has indicated that they wish to be " +
                 "addressed as (e.g. Johnny rather than Jonathan)")
    public String getFirstName() { ... }
}
----







== anchor:reference-annotations_manpage-ViewModelLayout[]`named()`

IMPORTANT: WIP ... this section

The `@Named` annotation is used when you want to specify the way something is named on the user interface i.e. when you do not want to use the name generated automatically by the system. It can be applied to objects, members (properties, collections, and actions) and to parameters within an action method.

[WARNING]
====
Generally speaking it is better to rename the property, collection or
action. The only common case where `@Named` is common is to rename
parameters for built-in value types. Even here though a custom value
type can be defined using `@Value` so that the value type is used as the
parameter name. `@Named` may also be used if the name needs punctuation
or other symbols in the name presented to the user.
====



By default the name of an object is derived, reflectively from the class
name. To specify a different name for an object, use the `@Named`
annotation in front of the class declaration.

For example:

[source,java]
----
@Named("Customer")
public class CustomerImpl implements Customer{
   ...
}
----





== `paged()`

Title: @Paged


This annotation is used to indicate that parented and/or standalone collections should be paginated.

When annotated on a collection, `@Paged` indicates the page size of a parented collection. When annotated on a type, `@Paged` indicates the page size of a standalone collection.

For example:

[source,java]
----
@ViewModel(paged=30)
public class Order {

}
----

This indicates a page size of 15 for parented collections, and a page
size of 30 for standalone collections.

When omitting a parameter value or omitting the annotation completely,
the configured defaults in `isis.properties` will be used.

For example:

[source,ini]
----
isis.viewers.paged.standalone=20
isis.viewers.paged.parented=5
----

This indicates a page size of 5 for parented collections and a page size
of 20 for standalone collections.






== `plural()`


When the framework displays a collection of several objects it may use the plural form of the object type in the title. By default the plural name will be created by adding an 's' to the end of the singular name (whether that is the class name or another name specified using `@Named`). Where the single name ends in 'y' then the default plural name will end in 'ies' - for example a collection of `Country` objects will be titled 'Countries'. Where these conventions do not work, the programmer may specify the plural form of the name using `@Plural`.

For example:

[source,java]
----
@Plural("Children")
public class Child {
    // members and actions here
}
----





