[[_ug_reference-services-api_manpage-BookmarkService]]
= `BookmarkService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

IMPORTANT: TODO


Title: Bookmark Service

The `BookmarkService` provides the ability to obtain a serializable `org.apache.isis.applib.bookmarks.Bookmark` for any (persisted) domain object, and to lookup domain objects given a `Bookmark`.

This is a good way of storing a reference to an arbitrary object (a polymorphic relationship). The downside is that there is no way for the objectstore (eg JDO objectstore) to enforce any kind of referental integrity.

== API

The API defined by `BookmarkService` is:

[source]
----
public interface BookmarkService {

    @NotInServiceMenu
    Object lookup(BookmarkHolder bookmarkHolder);

    @Programmatic
    Object lookup(Bookmark bookmark);

    @Programmatic
    <T> T lookup(Bookmark bookmark, Class<T> requiredType);

    @Programmatic
    Bookmark bookmarkFor(Object domainObject);

    @Programmatic
    Bookmark bookmarkFor(Class<?> cls, String identifier);
}
----

If a domain class implements the `org.apache.isis.applib.bookmarks.BookmarkHolder` interface then the `BookmarkService` will appear as a contributed action. Otherwise the service is hidden from view, intended to be injected into domain objects as a supporting domain service.

== Usage within the framework

Bookmarks are used by the xref:_ug_reference-services-api_manpage-BackgroundCommandService[`BackgroundCommandService`], which uses a bookmark to capture the target object on which an action will be invoked subsequently.

Bookmarks are also used by the xref:_ug_reference-services-spi_manpage-PublishingService[`PublishingService`] and the xref:_ug_reference-services-spi_manpage-AuditingService[`AuditingService`].

== Implementations

The core framework provides a default implementation of this API:

* `org.apache.isis.core.metamodel.services.bookmarks.BookmarkServiceDefault`

== Register the Service

The `BookmarkServiceDefault` is automatically registered with the framework (it is annotated with `@DomainService`) so there is no need to explicitly register the service.