[[_ug_reference-annotations_manpage-DomainObject_autoComplete]]
= `autoComplete()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


IMPORTANT: WIP ... this section


This annotation is to support an auto-complete capability for reference
properties and action parameters, the idea being that the user enters a
few characters to locate a reference, and these are shown - for example
- in a drop-down list box.

The annotation is specified on the type, and specifies an action on a
repository; this action should take a single string and should return a
list of the type.

For example:

[source,java]
----
@AutoComplete(repository=Customers.class, action="autoComplete")
public class Customer extends AbstractDomainObject {
   ....
}
----

where:

[source,java]
----
public interface Customers {

    @Hidden
    List<Customer> autoComplete(String search);
    ...
}
----


[NOTE]
====
In many cases you may require additional control. For this, you can use the `autoComplete` method prefix, associated either with link:../../how-tos/how-to-03-025-How-to-specify-an-autocomplete-for-an-action-parameter.html[action parameter] or with the link:../../how-tos/how-to-03-015-How-to-specify-an-autocomplete-for-a-property.html[property].
====



