[[_ug_reference-annotations_manpage-Collection_domainEvent]]
= `domainEvent()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


Whenever a domain object (or list of domain objects) is to be rendered, the framework fires off multiple domain events for every property, collection and action of the domain object.  In the cases of the domain object's collections, the events that are fired are:

* hide phase: to check that the collection is visible (has not been hidden)
* disable phase: to check that the collection is usable (has not been disabled)
* validate phase: to check that the collection's arguments are valid (to add or remove an element)
* pre-execute phase: before the modification of the collection
* post-execute: after the modification of the collection

Subscribers subscribe through the xref:_ug_reference-services-api_manpage-EventBusService[`EventBusService`] using either link:https://github.com/google/guava[Guava] or link:http://www.axonframework.org/[Axon Framework] annotations and can influence each of these phases.


[WARNING]
====
The xref:_ug_wicket-viewer[Wicket viewer] does NOT currently support the modification of collections; they are rendered read-only.  However, domain events are still relevant to determine if such collections should be hidden.
====

By default the event raised is `CollectionDomainEvent.Default`. For example:

[source,java]
----
public class ToDoItem {
    @Collection()
    public SortedSet<ToDoItem> getDependencies() { ... }
    ...
}
----

The purpose of the `domainEvent()` attribute is to allows a custom subclass to be emitted instead.

For example:

[source,java]
----
public class ToDoItem {
    public static class DependenciesChangedEvent extends CollectionInteractionEvent<ToDoItem, ToDoItem> {
        private static final long serialVersionUID = 1L;
        public DependenciesChangedEvent(
                ToDoItem source, 
                Identifier identifier, 
                Of of,                                      // <1> 
                ToDoItem value) {
            super(source, identifier, of, value);
        }
    }
}
----
<1> indicates if the collection is being accessed, added to or removed from.


The benefit is that subscribers can be more targetted as to the events that they subscribe to.

[NOTE]
====
As you might expect, it is also possible to influence the domain event type raised for xref:_ug_reference-annotations_manpage-Action_domainEvent[actions] and xref:_ug_reference-annotations_manpage-Property_domainEvent[properties].
====



== Subscribers

Subscribers (which must be domain services) subscribe using either the link:https://github.com/google/guava[Guava] API or (if the xref:_ug_reference-services-api_manpage-EventBusService[`EventBusService`] has been appropriately configured) using the link:http://www.axonframework.org/[Axon Framework] API.  The examples below use the Guava API.

Subscribers can be either coarse-grained (if they subscribe to the top-level event type):

[source,java]
----
@DomainService
public class SomeSubscriber {
    @Programmatic
    @com.google.common.eventbus.Subscribe
    public void on(CollectionInteractionEvent ev) {
        ...
    }
}
----

or can be fine-grained (by subscribing to specific event subtypes):

[source,java]
----
@DomainService
public class SomeSubscriber {
    @Programmatic
    @com.google.common.eventbus.Subscribe
    public void on(ToDoItem.DependenciesChangedEvent ev) {
        ...
    }
}
----

[TIP]
====
If the AxonFramework is being used, replace `@com.google.common.eventbus.Subscribe` for `@org.axonframework.eventhandling.annotation.EventHandler`.
====

The subscriber's method is called (up to) 5 times:

* whether to veto visibility (hide)
* whether to veto usability (disable)
* whether to veto execution (validate) the element being added to/removed from the collection
* steps to perform prior to the collection being added to/removed from
* steps to perform after the collection has been added to/removed from.

The subscriber can distinguish these by calling `ev.getPhase()`. Thus the general form is:

[source,java]
----
@Programmatic
@com.google.common.eventbus.Subscribe
public void on(CollectionDomainEvent ev) {
    switch(ev.getPhase()) {
        case HIDE:
            break;
        case DISABLE:
            break;
        case VALIDATE:
            break;
        case EXECUTING:
            break;
        case EXECUTED:
            break;
    }
}
----

Vetoing is performed by calling the appropriate method on the event:

* To hide: +
+
`ev.hide()` or `ev.veto("")`

* To disable: +
+
`ev.disable("...")` or `ev.veto("...")`

* To invalidate: +

`ev.invalidate("...")` or `ev.veto("...")`

It is also possible to abort the transaction during the executing or executed phases by throwing an exception. If the exception is a subtype of `RecoverableException` then the exception will be rendered as a user-friendly warning (eg Growl/toast) rather than an error.




== Raising events programmatically

Normally events are only raised for interactions through the UI. However, events can be raised programmatically either by calling the xref:_ug_reference-services-api_manpage-EventBusService[`EventBusService`] API directly, or by emulating the UI by
wrapping the target object using the xref:_ug_reference-services-api_manpage-WrapperFactory[`WrapperFactory`] domain service.




