= anchor:reference-annotations_manpage-[]`@DomainService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

IMPORTANT: TODO


Title: @DomainService

Indicates that the (concrete) class should be automatically instantiated as a domain service.

Domain services with this annotation do NOT need to be registered explicitly in `isis.properties`; they will be
discovered automatically on the CLASSPATH.

The following attributes can be specified:

*

`nature` - the nature of this service: providing actions for menus, contributed actions, or neither (1.8.0)

*

`repositoryFor` - if this domain service acts as a repository for an entity type, specify that entity type. (This is currently informational only)

*

`menuOrder` - the order of the service's menu with respect to other service's (deprecated in 1.8.0)

For example:

[source]
----
@DomainService(menuOrder = "10", repositoryFor = ToDoItem.class)
public class ToDoItems {
    ...
}
----

or:

[source]
----
@DomainService(menuBar = DomainService.MenuBar.SECONDARY, menuOrder = "1")
public class ToDoItemsFixturesService extends FixtureScripts {
    ...
}
----

It is not (currently) possible to specify the UI hints through any other means (specifically: is _not_ supported through a `.layout.json` file).

== Source code

See <a href="https://issues.apache.org/jira/browse/ISIS-970">ISIS-970</a> and <a href="https://github.com/apache/isis/blob/master/core/applib/src/main/java/org/apache/isis/applib/annotation/DomainObject.java">@DomainObject</a> source code.

== See also

Other domain semantics:

* link:./Property.html[@Property]
* link:./Collection.html[@Collection]
* link:./Action.html[@Action]
* link:./Parameter.html[@Parameter]
* link:./DomainObject.html[@DomainObject]
* link:./DomainService.html[@DomainService]
* link:./ViewModel.html[@ViewModel]

Corresponding view layer ("Layout") annotation:

* link:./PropertyLayout.html[@PropertyLayout]
* link:./CollectionLayout.html[@CollectionLayout]
* link:./ActionLayout.html[@ActionLayout]
* link:./DomainObjectLayout.html[@DomainObjectLayout]
* link:./DomainServiceLayout.html[@DomainServiceLayout]
* link:./ViewModelLayout.html[@ViewModelLayout]





== `natureOfService()`

now also VIEW_REST_ONLY


Title: @NotContributed

____

Deprecated, use instead link:./DomainService.html[@DomainService#nature()] to specify whether a service's actions are contributed, and use link:./ActionLayout.html[@ActionLayout#contributed()] to specify how they are contributed.

____

The `@NotContributed` annotation applies only to action methods, and
specifically to the actions of services. If present, it indicates that
the action should not be contributed to any of its domain object
arguments.

For example:

[source]
----
public class OrderServices {
    @NotContributed
    public void cancel(Order order);
    ...
}
----

If the action should neither be contributed nor appear in the service's
service menu, then you could instead simply mark it as `@Hidden`.

== Contributing of one-arg actions

Actions that accept a single argument will, by default, also be contributed as an association:

*

if the action returns a single object (value or entity) then the action will be contributed as a property

*

if the action returns a list then the action will be contributed as a collection

This behaviour can be influenced by specifying the "As." attribute:

* use `@NotContributed(As.ACTION)` to contribute the action as an association
* use `@NotContributed(As.ASSOCIATION)` to contribute the action as an action
* use `@NotContributed` to not contribute the action at all.





Title: @NotInServiceMenu

____

Deprecated, use instead link:./DomainService.html[@DomainService#nature()] to specify whether a service's actions are visible on the menu bar.

____

The `@NotInServiceMenu` annotation applies only to action methods, and
specifically to the actions of services. If present, it indicates that
the action should not appear in the service menu for the service. It
may, however, still be contributed to any of its domain object
arguments.

For example:

[source]
----
public class OrderServices {
    @NotInServiceMenu
    public void cancel(Order order);
    ...
}
----




If the action should neither be contributed (see ?) nor appear in the
service's service menu, then you could instead simply mark it as `@Hidden`
<!--(see ?)-->.





