[[_ug_reference-annotations_manpage-PropertyLayout]]
= `@PropertyLayout`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `@PropertyLayout` annotation applies to properties collecting together all UI hints within a single annotation.


The table below summarizes the annotation's attributes.

.`@PropertyLayout` attributes
[cols="2,2,4a", options="header"]
|===

| Attribute
| Values (default)
| Description


|xref:_ug_reference-annotations_manpage-PropertyLayout_cssClass[`cssClass()`]
|Any string valid as a CSS class
|the css class that a property should have, to allow more targetted styling in xref:_ug_runtime_application-specific_application-css[`application.css`]


|xref:_ug_reference-annotations_manpage-PropertyLayout_describedAs[`describedAs()`]
|String
|description of this property, eg to be rendered in a tooltip.


|xref:_ug_reference-annotations_manpage-PropertyLayout_hidden[`hidden()`]
|`EVERYWHERE`, `OBJECT_FORMS`, `PARENTED_TABLES`, `STANDALONE_TABLES`, `ALL_TABLES`, `NOWHERE` +
(`NOWHERE`)
|indicates where (in the UI) the property should be hidden from the user.


|xref:_ug_reference-annotations_manpage-PropertyLayout_labelPosition[`labelPosition()`]
|`LEFT`, `TOP`, `RIGHT`, `NONE` +
(`LEFT`)
|in forms, the positioning of the label relative to the property value. +

Defaults is `LEFT`, unless xref:_ug_reference-annotations_manpage-PropertyLayout_multiLine[`multiLine`] in which case `TOP`.  The value `RIGHT` is only supported for boolean properties. +

It is also possible to change the default through a xref:_ug_runtime_configuring-core_isis-viewers-propertyLayout-labelPosition[configuration property]


|xref:_ug_reference-annotations_manpage-PropertyLayout_multiLine[`multiLine()`]
|Positive integer
|for string properties, render as a text area over multiple lines.  +

If set > 1, then xref:_ug_reference-annotations_manpage-PropertyLayout_labelPosition[`labelPosition`] defaults to TOP.


|xref:_ug_reference-annotations_manpage-PropertyLayout_named[`named()`]
|String
|to override the name inferred from the collection's name in code. +

A typical use case is if the desired name is a reserved Java keyword, such as `default` or `package`.


|`namedEscaped()`
|`true`, `false` +
(`true`)
|whether to HTML escape the name of this property.


|xref:_ug_reference-annotations_manpage-PropertyLayout_renderedAsDayBefore[`renderedAsDayBefore()`]
|`true`, `false` +
(`false`)
|for date propertys only, render the date as one day prior to the actually stored date. +

Useful for persisting an open interval, eg: +

`[1-Apr-2015, 1-Jun-2015)` +

but presenting the data as if a closed interval +

`[1-Apr-2015, 31-May-2015]`.


|xref:_ug_reference-annotations_manpage-PropertyLayout_typicalLength[`typicalLength()`]
|Positive integer.
|the typical entry length of a field, use to determine the optimum width for display

|===




For example:

[source,java]
----
public class ToDoItem {
    @PropertyLayout(
        cssClass="x-key",
        named="Description of this <i>item</i>",
        namedEscaped=false,
        describedAs="What needs to be done",
        labelPosition=LabelPosition.LEFT,
        typicalLength=80
    )
    public String getDescription() { ... }
    ...
}
----

It is also possible to apply the annotation to actions of domain services that are acting as link:../../more-advanced-topics/how-to-01-062-How-to-decouple-dependencies-using-contributions.html[contributed properties].



As an alternative to using the `@PropertyLayout` annotation, a dynamic layout using  xref:_ug_wicket-viewer_layout_dynamic-object-layout[`.layout.json`] file can be specified; for example:

[source,javascript]
----
{
    "span": 6,
    "memberGroups": {
        "Other": {
            "members": {
                ...
                "description": {
                    "propertyLayout": {
                        "cssClass": "x-key",
                        "describedAs": "What needs to be done",
                        "labelPosition": "LEFT",
                        "typicalLength": 80
                    }
                },
                "notes": {
                    "propertyLayout": {
                        "describedAs": "Additional notes"
                        "labelPosition": "TOP",
                        multiLine=8
                    }
                },
                ....
            }
        },
        ...
    }
}
----





include::_ug_reference-annotations_manpage-PropertyLayout_cssClass.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_describedAs.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_labelPosition.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_multiLine.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_named.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_renderedAsDayBefore.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_typicalLength.adoc[leveloffset=+1]






