[[_ug_reference-annotations_manpage-PropertyLayout_labelPosition]]
= `labelPosition()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



IMPORTANT: WIP ... this section


As an alternative to using the annotation, the dynamic xref:_ug_wicket-viewer_layout_dynamic-object-layout[`.layout.json`]
can be used instead, eg:

[source,javascript]
----
----



[TIP]
.Specifying a default setting for label positions
====
If you want a consistent look-n-feel throughout the app, eg all property labels to the top, then it'd be rather frustrating to have to annotate every property.

Instead, a default can be specified in `isis.properties`:

[source,ini]
----
isis.viewers.propertyLayout.labelPosition=TOP
----

or

[source,ini]
----
isis.viewers.propertyLayout.labelPosition=LEFT
----

If these are not present then Isis will render according to internal defaults. At the time of writing, this means labels are to the left for all datatypes except multiline strings.
====

