[[_ug_reference-annotations_manpage-ViewModel]]
= `@ViewModel`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



The `@ViewModel` annotation, applied to a class, is the simplest way to indicate that the class is a view model.
View models are not persisted to the database, instead their state is encoded within their identity (ultimately
represented in the URL). As such, view models are immutable.

For example:

[source,java]
----
@ViewModel
public class MyViewModel {

    public MyViewModel() {}

    ...

}
----

View models must have a no-arg constructor, but there are few other constraints.

* if the view model has dependencies on domain services, then either:
* instantiate using `DomainObjectContainer#newTransientInstance()` or
* instantiate directly and then inject explicitly using `DomainObjectContainer#injectServicesInto(.)`
* if the view model has no dependencies on domain services, then just instantiate directly


[TIP]
====
Note that there is a `DomainObjectContainer#newViewModelInstance(.)`; this is for view models that implement `ViewModel` interface and can be safely ignored.
====


The view model's memento will be derived from the value of the view model object's properties. Any xref:_ug_reference-annotations_manpage-Property_notPersisted[`@Property#notPersisted()`] properties will be excluded from the memento, as will any http://isis.apache.org/reference/recognized-annotations/Programmatic.html[@Programmatic] properties. Properties that are merely http://isis.apache.org/reference/recognized-annotations/Hidden-deprecated.html[@Hidden] are included in the memento.

Only properties supported by the configured xref:_ug_reference-services-api_manpage-MementoService[`MementoService`] can be used. The default implementation supports all the value types and persisted entities.

(As of 1.8.0) there are some limitations:
* view models cannot hold collections other view models (simple properties _are_ supported, though)
* collections (of either view models or entities) are ignored.


