[[_ug_reference-annotations_manpage-Action_hidden]]
= `hidden()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/




Actions can be hidden at the domain-level, indicating that they are not visible to the end-user.

For example:

[source,java]
----
public class Customer {
    @Action(hidden=EVERYWHERE)
    public void updateStatus() { ... }
    ...
}
----

The only value that currently makes sense is `EVERYWHERE` (or its synonym `ANYWHERE`).



[TIP]
====
It is also possible to use `@ActionLayout` or xref:_ug_wicket-viewer_layout_dynamic-object-layout[dynamic layouts] such that the action can be hidden at the view layer. Both options are provided with a view that in the future the view-layer semantics may be under the control of (expert) users, whereas domain-layer semantics should never be overridden or modified by the user.
====

[NOTE]
====
For actions of domain services the visibility is dependent upon its xref:_ug_reference-annotations_manpage-DomainService_nature[`@DomainService#nature()`] and also on whether it is contributed (as per `ActionLayout#contributed()`).
====



