[[_ug_reference-annotations_manpage-Property]]
= `@Property`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

IMPORTANT: TODO


The `@Property` annotation applies to properties collecting together all domain semantics within a single annotation.

It is also possible to apply the annotation to actions of domain services that are acting as link:../../more-advanced-topics/how-to-01-062-How-to-decouple-dependencies-using-contributions.html[contributed properties].



.`@Action` attributes
[cols="2,2,4", options="header"]
|===

| Attribute
| Values (default)
| Description


|xref:__a_id_reference_annotations_manpage_property_a_code_domainevent_code[`domainEvent()`]
|
|


|xref:__a_id_reference_annotations_manpage_property_a_code_editing_code[`editing()`]
|
|


|xref:__a_id_reference_annotations_manpage_property_a_code_hidden_code[`hidden()`]
|
|


|xref:__a_id_reference_annotations_manpage_property_a_code_maxlength_code[`maxLength()`]
|
|


|xref:__a_id_reference_annotations_manpage_property_a_code_mustsatisfy_code[`mustSatisfy()`]
|
|


|xref:__a_id_reference_annotations_manpage_property_a_code_notpersisted_code[`notPersisted()`]
|
|


|xref:__a_id_reference_annotations_manpage_property_a_code_optionality_code[`optionality()`]
|
|


|xref:__a_id_reference_annotations_manpage_property_a_regex[`regex()`]
|
|


|`regexPatternFlags()`
|
|


|`regexPatternReplacement()`
|
|

|===






== anchor:reference-annotations_manpage-Property[]`domainEvent()`

IMPORTANT: WIP ... this section


The `@PropertyInteraction` annotation applies to domain entity properties, allowing
subscribers to optionally veto, validate or otherwise perform tasks before
or after the property has been modified/cleared.

Subscribers subscribe through the xref:__a_id_reference_services_api_manpage_a_code_eventbusservice_code[`EventBusService`] using either link:https://github.com/google/guava[Guava] or link:http://www.axonframework.org/[Axon Framework] annotations.

By default the event raised is `PropertyInteractionEvent.Default`. For example:

[source,java]
----
public class ToDoItem {
    ...
    @PropertyInteraction
    public LocalDate getDueBy() { ... }
}
----

Optionally a subclass can be declared:

[source,java]
----
public class ToDoItem {

    public static class DueByChangedEvent extends PropertyInteractionEvent<ToDoItem, LocalDate> {
        private static final long serialVersionUID = 1L;
        public DueByChangedEvent(ToDoItem source, Identifier identifier, LocalDate oldValue, LocalDate newValue) {
            super(source, identifier, oldValue, newValue);
        }
    }

    @PropertyInteraction(ToDoItem.DueByChangedEvent)
    public LocalDate getDueBy() { ... }

}
----


=== Subscribers

Subscribers (which must be domain services) subscribe using the Guava API.
Subscribers can be either coarse-grained (if they subscribe to the top-level event type):

[source,java]
----
@DomainService
public class SomeSubscriber {

    @Programmatic
    @com.google.common.eventbus.Subscribe
    public void on(PropertyInteractionEvent ev) {

        ...
    }

}
----

or can be fine-grained by subscribing to specific event subtypes:

[source,java]
----
@DomainService
public class SomeSubscriber {

    @Programmatic
    @com.google.common.eventbus.Subscribe
    public void on(ToDoItem.DueByChangedEvent ev) {

        ...
    }

}
----

The subscriber's method is called (up to) 5 times:

* whether to veto visibility (hide)
* whether to veto usability (disable)
* whether to veto execution (validate)
* steps to perform prior to the property being modified
* steps to perform after the property has been modified.

The subscriber can distinguish these by calling `ev.getPhase()`. Thus the general form is:

[source,java]
----
@Programmatic
@com.google.common.eventbus.Subscribe
public void on(PropertyInteractionEvent ev) {

    switch(ev.getPhase()) {
        case HIDE:
            ...
            break;
        case DISABLE:
            ...
            break;
        case VALIDATE:
            ...
            break;
        case EXECUTING:
            ...
            break;
        case EXECUTED:
            ...
            break;
    }
}
----

Vetoing is performed by calling the appropriate method on the event:

*

To hide:

ev.hide()

*

To disable:

ev.disable("…");

*

To invalidate:

ev.invalidate("…");

It is also possible to abort the transaction during the executing or executed
phases by throwing an exception. If the exception is a subtype of `RecoverableException`
then the exception will be rendered as a user-friendly warning (eg Growl/toast)
rather than an error.

=== Raising events programmatically.

Normally events are only raised for interactions through the UI. However, events can be raised programmatically by
wrapping the target object using the link:../services/wrapper-factory.html[Wrapper Factory] service.


[NOTE]
====
Interaction events can also be raised for link:./ActionInteraction.html[actions] and link:./CollectionInteraction.html[collections].
====









== anchor:reference-annotations_manpage-Property[]`editing()`

IMPORTANT: WIP ... this section

[NOTE]
====
Fully supported by: Wicket viewer; other viewers do not yet support the `where` attribute.
====

The `@Disabled` annotation means that the member cannot be used in any instance of the class. When applied to the property it means that the user may not modify the value of that property (though it may still be modified programmatically). When applied to an action method, it means that the user cannot invoke that method.

For example:

[source,java]
----
public class Customer {
    @Disabled
    public void assessCreditWorthiness() { ... }

    @Disabled
    public int getInitialCreditRating(){ ... }
    public void setInitialCreditRating(int initialCreditRating) { ... }
}
----

Note that if an action is marked as `@Disabled`, it will be shown on the
user interface but cannot ever be invoked. The only possible reason we
can think to do this is during prototyping, to indicate an action that
is still to be developed. If a method is intended for programmatic use,
but not intended ever to be invoked directly by a user, then it should
be marked as `@Hidden` instead.

This annotation can also take two parameter indicating where (in the UI)
it is to be disabled, and when (in the object's lifecycle) it is to be
disabled. For example:

[source,java]
----
public class Customer {
    (when=When.UNTIL_PERSISTED)
    public void assessCreditWorthiness() { ... }
}
----

would disable the action until the object has been saved. And:

[source,java]
----
public class Customer {
    (where=Where.PARENTED_TABLES)
    public void getFirstName() { ... }
}
----

would disable the property in parented tables but not in regular object
forms (though note: this would only be used by viewers that provide
in-table editing capability).

The acceptable values for the `where` parameter are:

* `Where.ANYWHERE` +
+
The member should be disabled everywhere.

* `Where.OBJECT_FORMS` +
+
The member should be disabled when displayed within an object form.
For most viewers, this applies to property and collection members,
not actions.

* `Where.PARENTED_TABLES` +
+
The member should be disabled when displayed as a column of a table
within a parent object's collection. For most (all?) viewers, this
will have meaning only if applied to a property member.

* `Where.STANDALONE_TABLES` +
+
The member should be disabled when displayed as a column of a table
showing a standalone list of objects, for example as returned by a
repository query. For most (all?) viewers, this will have meaning
only if applied to a property member.

* `Where.ALL_TABLES` +
+
The member should be disabled when displayed as a column of a table,
either an object's * collection or a standalone list. This combines
`PARENTED_TABLES` and `STANDALONE_TABLES`

* `Where.NOWHERE` +
+
Has no meaning for the `@Disabled` annotation (though is used by the
`@Hidden` annotation which also uses the `Where` enum<!--, see ?-->).

The acceptable values for the `when` parameter are:

* `When.ALWAYS` +
+
The member should be disabled at all times.

* `When.NEVER` +
+
The member should never be disabled (unless disabled through some
other mechanism, for example an imperative disableXxx() supporting
method)..

* `When.ONCE_PERSISTED` +
+
The member should be enabled for transient objects, but disabled for
persisted objects.

* `When.UNTIL_PERSISTED` +
+
The member should be disabled for transient objects, but enabled for
persisted objects.

By default the annotated property or action is always disabled (ie
defaults to `Where.ANYWHERE`, `When.ALWAYS`).





== anchor:reference-annotations_manpage-Property[]`hidden()`

IMPORTANT: WIP ... this section

The `@Hidden` annotation indicates that the member (property, collection or action) to which it is applied should never be visible to the user. It can also be applied to service types (it has no effect if applied to entities or values).

For example:

[source,java]
----
public class Customer {
    @Hidden
    public int getInternalId() { ... }

    @Hidden
    public void updateStatus() { ... }
    ...
}
----

Or, applied to a service:

[source,java]
----
@Hidden
public class EmailService {
    public void sendEmail(...) { ... }
    ...
}
----

This annotation can also take a parameters indicating where and when it
is to be hidden. For example:

[source,java]
----
public class Customer {
    @Hidden(when=When.ONCE_PERSISTED)
    public int getInternalId() { ... }
    ...
}
----

would show the `Id` until the object has been saved, and then would hide
it. And:

[source,java]
----
public class Customer {
    @Hidden(where=Where.ALL_TABLES)
    public int getDateOfBirth() { ... }
    ...
}
----

would suppress the `dateOfBirth` property of a Customer from all tables.

The acceptable values for the `where` parameter are:

* `Where.ANYWHERE` +
+
The member should be hidden everywhere.

* `Where.OBJECT_FORMS` +
+
The member should be hidden when displayed within an object form.
For most viewers, this applies to property and collection members,
not actions.

* `Where.PARENTED_TABLES` +
+
The member should be hidden when displayed as a column of a table
within a parent object's collection. For most (all?) viewers, this
will have meaning only if applied to a property member.

* `Where.STANDALONE_TABLES` +
+
The member should be hidden when displayed as a column of a table
showing a standalone list of objects, for example as returned by a
repository query. For most (all?) viewers, this will have meaning
only if applied to a property member.

* `Where.ALL_TABLES` +
+
The member should be /hidden when displayed as a column of a table,
either an object's * collection or a standalone list. This combines
`PARENTED_TABLES` and `STANDALONE_TABLES`.

* `Where.NOWHERE` +
+
Acts as an override if a member would normally be hidden as a result
of some other convention. For example, if a property is annotated
with `@Title` <!--(see ?)-->, then normally this should be hidden from all
tables. Additionally annotating with `@Hidden(where=Where.NOWHERE)`
overrides this.

The acceptable values for the `when` parameter are:

* `When.ALWAYS` +
+
The member should be hidden at all times.

* `When.NEVER` +
+
The member should never be hidden (unless disabled through some
other mechanism, for example an imperative disableXxx() supporting
method)..

* `When.ONCE_PERSISTED` +
+
The member should be visible for transient objects, but hidden for
persisted objects.

* `When.UNTIL_PERSISTED` +
+
The member should be hidden for transient objects, but visible for
persisted objects.

By default the annotated property or action is always hidden (ie
defaults to `Where.ANYWHERE`, `When.ALWAYS`).








== anchor:reference-annotations_manpage-Property[]`maxLength()`

IMPORTANT: WIP ... this section

The `@MaxLength` annotation indicates the maximum number of characters that the user may enter into a `String` property, or a `String` parameter in an action, or for a string-based value type. It is ignored if applied to any other type.

For example:

[source,java]
----
public class Customer {
    @MaxLength(30)
    public String getFirstName() { ... }
    public void setFirstName(String firstName) { ... }
    ...
}
----





== anchor:reference-annotations_manpage-Property[]`mustSatisfy()`

IMPORTANT: WIP ... this section


The `@MustSatisfy` annotation allows validation to be applied to
properties and parameters using an (implementation of a)
`org.apache.isis.applib.spec.Specification` object.

For example:

[source,java]
----
public class Customer {
    @MustSatisfy(StartWithCapitalLetterSpecification.class)
    public String getFirstName() { ... }
    ...
}
----


The `Specification` is consulted during validation, being passed the proposed value.


[TIP]
====
Can also specify on property, so the specification class can be reused.
====







== anchor:reference-annotations_manpage-Property[]`notPersisted()`

IMPORTANT: WIP ... this section

The `@NotPersisted` annotation indicates that the property is not to be
persisted.


[NOTE]
====
In many cases the same thing can be achieved simply by providing the property with a 'getter' but no 'setter'.
====


For example:

[source,java]
----
public class Order {

    @NotPersisted
    public Order getPreviousOrder() {...}
    public void setPreviousOrder(Order previousOrder) {...}

    ...
}
----







== anchor:reference-annotations_manpage-Property[]`optionality()`


By default, the system assumes that all properties of an object are required, and therefore will not let the user save a new object unless a value has been specified for each property. Similarly, by default, the system assumes that all parameters in an action are required and will not let the user execute that action unless values have been specified for each parameter.

To indicate that either a property, or an action parameter, is optional, use the `@Optional` annotation.


[TIP]
====
The `@Optional`annotation has no meaning for a primitive property (or parameter) such as `int` - because primitives will always return a default value (e.g. zero). If optionality is required, then use the corresponding wrapper class (e.g. `java.lang.Integer`).
====


=== Making a property optional

Annotate the getter to indicate that a property is `@Optional`. For
example:

[source,java]
----
public class Order {
    public Product getProduct() { ... }

    public java.util.Date getShipDate() { ... }
    public void setShipDate(Date java.util.shipDate) { ... }

    @Optional
    public String getComments() { ... }
    public void setComments(String comments) { ... }
}
----

Here the `product` and `shipDate` properties are both required, but the
`comments` property is optional.

=== Making an action parameter optional

To indicate that an action may be invoked without having to specify a
value for a particular parameter, annotate with `@Optional`. For
example:

[source,java]
----
public class Customer {
    public Order placeOrder(
            Product product
           ,@Named("Quantity") int quantity
           ,@Optional @Named("Special Instructions") String instr) {
        ...
    }
    ...
}
----




== anchor:reference-annotations_manpage-Property[]Regex

IMPORTANT: WIP ... this section


=== `regexPattern()`

=== `regexPatternFlags()`

=== `regexPatternReplacement()`



The `@RegEx` annotation may be applied to any string property, or to any
parameter within an action method. It can also be applied to any
string-based value type. It serves both to validate and potentially to
normalise the format of the input. `@Regex` is therefore similar in use
to `@Mask` <!--(see ?)--> but provides more flexibility.

The syntax is:

`@RegEx(validation = &quot;regEx string&quot;,
        format = &quot;regEx string&quot;, caseSensitive =
        &lt;true|false&gt;)`

Only the first parameter is required; the `format` defaults to "no
formatting", and `caseSensitive` defaults to false.

For example:

[source,java]
----
public class Customer {
    @RegEx(validation = "(\\w+\\.)*\\w+@(\\w+\\.)+[A-Za-z]+")
    public String getEmail() {}
    ...
}
----

