[[_ug_reference-annotations_manpage-ViewModelLayout_paged]]
= `paged()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/





This annotation is used to indicate that parented and/or standalone collections should be paginated.

When annotated on a collection, `@Paged` indicates the page size of a parented collection. When annotated on a type, `@Paged` indicates the page size of a standalone collection.

For example:

[source,java]
----
@ViewModel(paged=30)
public class Order {

}
----

This indicates a page size of 15 for parented collections, and a page
size of 30 for standalone collections.

When omitting a parameter value or omitting the annotation completely,
the configured defaults in `isis.properties` will be used.

For example:

[source,ini]
----
isis.viewers.paged.standalone=20
isis.viewers.paged.parented=5
----

This indicates a page size of 5 for parented collections and a page size
of 20 for standalone collections.




