[[_ug_reference-annotations_manpage-Action_restrictTo]]
= `restrictTo()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `restrictTo` attribute specifies whether the action is restricted to prototyping, or is generally available.

[NOTE]
====
This attribute replaces the deprecated `@Exploration` and `@Prototype` annotations.
====

By default there are no restrictions, with the action being available in all environments.

For example:

[source,java]
----
public class Customer {
    public Order placeNewOrder() { ... }
    public List<Order> listRecentOrders() { ... }
    @Action(restrictTo=RestrictTo.PROTOTYPING)
    public List<Order> listAllOrders() { ... }
    ...
}
----

In this case listing all orders probably doesn't make sense for production (there could be thousands or millions), but would be fine in a test or demo system where there are only a handful.




