[[_ug_reference-services-spi_manpage-AuditingService]]
= `AuditingService3`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/





The auditing service provides a simple mechanism to capture changes to data. It is called for each property that has changed on any domain object, as a set of pre- and post-values.

== API

The API for the service is:

[source,java]
----
public interface AuditingService3 {

    @Programmatic
    public void audit(
            final UUID transactionId, String targetClassName, final Bookmark target,
            String memberIdentifier, final String propertyName,
            final String preValue, final String postValue,
            final String user, final java.sql.Timestamp timestamp);
  }
----



== Implementations

For 1.7.0+, see the http://github.com/isisaddons/isis-module-audit[Isis addons' Audit module] (non-ASF).

If you just want to debug (writing to stderr), you can instead configure `org.apache.isis.applib.services.audit.AuditingService3$Stderr`



== Usage

=== Explicitly marking an object as audited

The typical way to indicate that an object should be audited is to annotate it with the xref:_ug_reference-annotations_manpage_DomainObject_auditing[`@DomainObject#auditing()`] annotation, for example:

[source,java]
----
@DomainObject(auditing=Auditing.ENABLED)
public class ToDoItem ... {
    ...
}
----

=== Making auditing the default

As an alternative to annotating every object with `@Audited`, alternatively this can be configured as the default. Add the following to `isis.properties`:

[source]
----
isis.services.audit.objects=all
----

To prevent an object from being audited (even if globally enabled), use the `@Audited` annotation with the `disabled` attribute:

[source]
----
@Audited(disabled=true)
public class NotAuditedObject { ... }
----

To disable globally, use:

[source]
----
isis.services.audit.objects=none
----

If the key is not present in `isis.properties`, then objects are not audited by default.


=== Related Services

A similar service that you may want to use alongside or instead of the auditing service is the xref:_ug_reference-services-spi_manpage-PublishingService[`PublishingService`].
