[[_ug_reference-annotations_manpage-PostConstruct]]
= `@PostConstruct` (`javax`)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `@javax.annotation.PostConstruct` annotation, as defined in link:https://jcp.org/en/jsr/detail?id=250[JSR-250],  is recognized by Apache Isis as a callback method on domain services to be called just after they have been constructed, in order that they initialize themselves.

For the default application-scoped (singleton) domain services, this means that the method, if present, is called during the bootstrapping of the application.  For xref:_ug_reference-annotations_manpage-RequestScoped[`@RequestScoped`] domain services, the method is called at the beginning of the request.

The signature of the method is:

[source,java]
----
@PostConstruct
@Programmatic                          <1>
public void postConstruct() { ... }    <2>
----
<1> The method should be annotated using xref:_ug_reference-annotations_manpage-Programmatic[`@Programmatic`] so that it is not interpreted as an action.
<2> the method can have any name, but must have `public` visibility.

In the form shown above the method can either accept no arguments.  Alternatively, the method can accept a parameter of type `Map<String,String>`:

[source,java]
----
@PostConstruct
@Programmatic
public void postConstruct(Map<String,String> properties) { ... }
----
Isis uses argument to pass in the configuration properties read from all xref:_ug_runtime_configuration-files[configuration files]:

[TIP]
====
Alternatively, you could inject xref:_ug_reference-services-api_manpage-DomainObjectContainer[`DomainObjectContainer`] into the service and read configuration properties using `DomainObjectContainer#getProperty(...)` and related methods.
====

A common use case is for domain services that interact with the xref:_ug_reference-services-api_manpage-EventBusService[`EventBusService`].  For example:

[source,java]
----
@DomainService(nature=NatureOfService.DOMAIN)
public class MySubscribingService {
    @Programmatic
    @PostConstruct
    public void postConstruct() {
        eventBusService.register(this);
    }
    @Programmatic
    @PreDestroy
    public void preDestroy() {
        eventBusService.unregister(this);
    }
    ...
    @javax.inject.Inject
    EventBusService eventBusService;
}
----

Other use cases include obtaining connections to external datasources, eg subscribing to an ActiveMQ router, say, or initializing/cleaning up a background scheduler such as Quartz.





See also xref:_ug_reference-annotations_manpage-PreDestroy[`@PreDestroy`]