[[_ug_reference-annotations_manpage-PropertyLayout]]
= `@PropertyLayout`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `@PropertyLayout` annotation applies to properties collecting together all UI hints within a single annotation.


The table below summarizes the annotation's attributes.

.`@Action` attributes
[cols="2,2,4", options="header"]
|===

| Attribute
| Values (default)
| Description


|xref:__a_id_reference_annotations_manpage_propertylayout_a_code_cssclass_code[`cssClass()`]
|
|the css class that a property should have, to allow more targetted styling in `application.css`


|xref:__a_id_reference_annotations_manpage_propertylayout_a_code_describedas_code[`describedAs()`]
|
|description of this property, eg to be rendered in a tooltip.


|xref:__a_id_reference_annotations_manpage_propertylayout_a_code_labelposition_code[`labelPosition()`]
|
|in forms, the positioning of the label (LEFT, TOP or NONE) relative to the property value. For boolean properties it is also possible to specify RIGHT. Defaults to LEFT unless `multiLine` also specified (see below)


|xref:__a_id_reference_annotations_manpage_propertylayout_a_code_multiline_code[`multiLine()`]
|
|for string propertys, render as a text area over multiple lines. If set &gt;1, then `labelPosition` defaults to TOP unless otherwise specified.


|xref:__a_id_reference_annotations_manpage_propertylayout_a_named[`named()`]
|
|the name of this property. For Java 7 this is generally required. For Java 8, the name can be inferred from the code so this attribute allows the name to be overridden.


|`namedEscaped()`
|
|whether to HTML escape the name of this property. Defaults to true.


|xref:__a_id_reference_annotations_manpage_propertylayout_a_code_renderedasdaybefore_code[`renderedAsDayBefore()`]
|
|for date propertys only, render the date as one day prior to the actually stored date (eg the end date of an open interval into a closed interval)


|xref:__a_id_reference_annotations_manpage_propertylayout_a_code_typicallength_code[`typicalLength()`]
|
|the typical entry length of a field, use to determine the optimum width for display

|===




For example:

[source,java]
----
public class ToDoItem {

    @PropertyLayout(
        cssClass="x-key",
        named="Description of this <i>item</i>",
        namedEscaped=false,
        describedAs="What needs to be done",
        labelPosition=LabelPosition.LEFT,
        typicalLength=80)
    public String getDescription() { ... }

    @PropertyLayout(
        describedAs="Additional notes",
        labelPosition=LabelPosition.TOP,
        multiLine=8)
    public String getNotes() { ... }

    ...
}
----

It is also possible to apply the annotation to actions of domain services that are acting as link:../../more-advanced-topics/how-to-01-062-How-to-decouple-dependencies-using-contributions.html[contributed properties].



As an alternative to using the `@PropertyLayout` annotation, the xref:__a_id_wicket_viewer_layout_a_dynamic_object_layout[]
  can be specified, eg:

[source,javascript]
----
{
    "span": 6,
    "memberGroups": {
        "Other": {
            "members": {
                ...
                "description": {
                    "propertyLayout": {
                        "cssClass": "x-key",
                        "describedAs": "What needs to be done",
                        "labelPosition": "LEFT",
                        "typicalLength": 80
                    }
                },
                "notes": {
                    "propertyLayout": {
                        "describedAs": "Additional notes"
                        "labelPosition": "TOP",
                        multiLine=8
                    }
                },
                ....
            }
        },
        ...
    }
}
----

[TIP]
.Specifying a default setting for label positions
====
If you want a consistent look-n-feel throughout the app, eg all property labels to the top, then it'd be rather
frustrating to have to annotate every property.

Instead, a default can be specified in `isis.properties`:

[source,ini]
----
isis.viewers.propertyLayout.labelPosition=TOP
----

or

[source,ini]
----
isis.viewers.propertyLayout.labelPosition=LEFT
----

If these are not present then Isis will render according to internal defaults. At the time of writing, this means labels are to the left for all datatypes except multiline strings.
====


IMPORTANT: TODO - ensure these properties are in the runtime config chapter





== anchor:reference-annotations_manpage-PropertyLayout[]`cssClass()`

IMPORTANT: WIP ... this section


The `CssClass` annotation applies to object and also to any object member (property, collection or action). It is used by the Wicket viewer as a UI hint to render specified CSS classes around the representation of the element.

Application-specific CSS can then be used to target and adjust the UI representation of that particular element.

For example:

[source,java]
----
public class ToDoItem {

    @CssClass("x-key")
    public LocalDate getDueBy() { ... }

}
----

=== Alternatives (`.layout.json`)

As an alternative to using the `@CssClass` annotation, the `.layout.json` link:../../components/viewers/wicket/dynamic-layouts.html[dynamic layout file] can be specified, eg:

[source,javascript]
----
{
    "span": 6,
    "memberGroups": {
        "Priority": {
            "members": {
                ...
                "dueBy": {
                    "cssClass": { "value": "x-key" }
                }
                ....
            }
        },
        ...
    }
}
----

Note that this (currently) only supports class members, not classes


[NOTE]
====
The similar link:./CssClassFa-deprecated.html[CssClassFa] annotation is also used as a hint to apply CSS, but in particular to allow http://fortawesome.github.io/Font-Awesome/icons/[Font Awesome icons] to be rendered on action butotns or as the icon for classes.
====







== anchor:reference-annotations_manpage-PropertyLayout[]`cssClassFa()`

IMPORTANT: WIP ... this section

The `CssClassFa` annotation applies to objects and also to object actions, and is used by the Wicket viewer as a UI hint.

For object actions, the viewer will render the specified http://fortawesome.github.io/Font-Awesome/icons/[Font Awesome icon] on the action's button (or menu item).

For objects, it will be used as an icon. Note that this is only used if the object does not have a `getIconName()` method.

For example:

[source,java]
----
public class ToDoItem {

    @CssClass("fa-step-backward")
    public ToDoItem previous() { ... }

    @CssClass("fa-step-forward")
    public ToDoItem next() { ... }

}
----

There can be multiple "fa-" classes, eg to mirror or rotate the icon. There is no need to include the "fa" class; it will be automatically appended.

=== Alternatives (`.layout.json`)

As an alternative to using the `@CssClass` annotation, the `.layout.json` link:../../components/viewers/wicket/dynamic-layouts.html[dynamic layout file] can be specified, eg:

[source,javascript]
----
{
    "span": 6,
    "memberGroups": {
        "Priority": {
            "members": {
                ...
                 "relativePriority": {
                    "actions": {
                        "previous": {
                            "cssClassFa": { "value": "fa-step-backward" }
                        },
                        "next": {
                            "cssClassFa": { "value": "fa-step-forward" }
                        }
                    }
                },
                ....
            }
        },
        ...
    }
}
----

Note that this (currently) only supports class members, not classes.


[NOTE]
====
The similar link:./CssClass-deprecated.html[CssClass] annotation is also used as a hint to apply CSS, but for wrapping the representation of an object or object member so that it can be styled in an application-specific way.
====






== anchor:reference-annotations_manpage-PropertyLayout[]`describedAs()`

IMPORTANT: WIP ... this section

The `@DescribedAs` annotation is used to provide a short description of something that features on the user interface. How this description is used will depend upon the viewing mechanism - but it may be thought of as being like a 'tool tip'.

Descriptions may be provided for objects, members (properties, collections and actions), and for individual parameters within an action method. `@DescribedAs` therefore works in a very similar manner to `@Named`.

For example:

[source,java]
----
public class Customer {
    @DescribedAs("The name that the customer has indicated that they wish to be " +
                 "addressed as (e.g. Johnny rather than Jonathan)")
    public String getFirstName() { ... }
}
----







== anchor:reference-annotations_manpage-PropertyLayout[]`hidden()`

IMPORTANT: WIP ... this section

The `@Hidden` annotation indicates that the member (property, collection
or action) to which it is applied should never be visible to the user.
It can also be applied to service types (it has no effect if applied to
entities or values).

For example:

[source,java]
----
public class Customer {
    @Hidden
    public int getInternalId() { ... }

    @Hidden
    public void updateStatus() { ... }
    ...
}
----

This annotation can also take a parameters indicating where and when it
is to be hidden. For example:

[source,java]
----
public class Customer {
    @Hidden(when=When.ONCE_PERSISTED)
    public int getInternalId() { ... }
    ...
}
----

would show the `Id` until the object has been saved, and then would hide
it. And:

[source,java]
----
public class Customer {
    @Hidden(where=Where.ALL_TABLES)
    public int getDateOfBirth() { ... }
    ...
}
----

would suppress the `dateOfBirth` property of a Customer from all tables.

The acceptable values for the `where` parameter are:

* `Where.ANYWHERE` +
+
The member should be hidden everywhere.

* `Where.OBJECT_FORMS` +
+
The member should be hidden when displayed within an object form.
For most viewers, this applies to property and collection members,
not actions.

* `Where.PARENTED_TABLES` +
+
The member should be hidden when displayed as a column of a table
within a parent object's collection. For most (all?) viewers, this
will have meaning only if applied to a property member.

* `Where.STANDALONE_TABLES` +
+
The member should be hidden when displayed as a column of a table
showing a standalone list of objects, for example as returned by a
repository query. For most (all?) viewers, this will have meaning
only if applied to a property member.

* `Where.ALL_TABLES` +
+
The member should be /hidden when displayed as a column of a table,
either an object's * collection or a standalone list. This combines
`PARENTED_TABLES` and `STANDALONE_TABLES`.

* `Where.NOWHERE` +
+
Acts as an override if a member would normally be hidden as a result
of some other convention. For example, if a property is annotated
with `@Title` <!--(see ?)-->, then normally this should be hidden from all
tables. Additionally annotating with `@Hidden(where=Where.NOWHERE)`
overrides this.

The acceptable values for the `when` parameter are:

* `When.ALWAYS` +
+
The member should be hidden at all times.

* `When.NEVER` +
+
The member should never be hidden (unless disabled through some
other mechanism, for example an imperative disableXxx() supporting
method)..

* `When.ONCE_PERSISTED` +
+
The member should be visible for transient objects, but hidden for
persisted objects.

* `When.UNTIL_PERSISTED` +
+
The member should be hidden for transient objects, but visible for
persisted objects.

By default the annotated property or action is always hidden (ie
defaults to `Where.ANYWHERE`, `When.ALWAYS`).




== anchor:reference-annotations_manpage-ParameterLayout[]`labelPosition()`

IMPORTANT: WIP ... this section







== anchor:reference-annotations_manpage-PropertyLayout[]`multiLine()`

IMPORTANT: WIP ... this section


The `@MultiLine` annotation provides information about the carriage
returns in a `String` property or action parameter, or for a
string-based value type. It also implies a hint to the viewer that the
widget to be used should be over multiple lines (eg a text area rather
than a text field), with appropriate wrapping and/or scrollbars.

More formally, the annotation indicates that:

* the `String` property or parameter may contain carriage returns, and

* (optionally) the typical number of such carriage returns (meaning
the number of rows in the text area), and

* (optionally) that the text should be wrapped (the default is that
text is not wrapped).

The syntax is:

`@MultiLine([numberOfLines=&lt;typicalNumberOfCRs&gt;]
        [,preventWrapping=&lt;false|true&gt;])`

For example:

[source,java]
----
public class BugReport {
    @MultiLine(numberOfLines=10)
    public String getStepsToReproduce() { ... }
    public void setStepsToReproduce(String stepsToReproduce) { ... }
    ...
}
----

Here the `stepsToReproduce` may be displayed in a text area of 10 rows,
with no wrapping. A horizontal scrollbar may appear if the number of
characters on any given row exceeds the width.

Another example:

[source,java]
----
public class Email {
    @MultiLine(numberOfLines=20, preventWrapping=false)
    public String getBody() { ... }
    public void setBody(String body) { ... }
    ...
}
----

Here the body should be displayed in a text area of 20 rows, with
wrapping.

If the annotation is combined with the `@TypicalLength`, then the
expected width of the text area in the user interface will be determined
by the value of the typical length divided by the number of specified
lines. For example:

[source,java]
----
public class Email {
    @MultiLine(numberOfLines=20, preventWrapping=false)
    @TypicalLength(800)
    public String getBody() { ... }
    public void setBody(String body) { ... }
    ...
}
----

Here the body will (likely be) displayed in a text area of 20 rows, with
40 columns.










== anchor:reference-annotations_manpage-PropertyLayout[]`named()`

IMPORTANT: WIP ... this section

The `@Named` annotation is used when you want to specify the way something is named on the user interface i.e. when you do not want to use the name generated automatically by the system. It can be applied to objects, members (properties, collections, and actions) and to parameters within an action method.


[WARNING]
====
Generally speaking it is better to rename the property, collection or action. The only common case where `@Named` is common is to rename parameters for built-in value types. Even here though a custom value type can be defined using `@Value` so that the value type is used as the parameter name. `@Named` may also be used if the name needs punctuation or other symbols in the name presented to the user.
====


By default, the name of a class member (a property, collection or action) presented to the user is derived, reflectively, from the name of the member defined in the program code. To specify a different name use the `@Named
`annotation immediately before the member declaration.

For example:

[source,java]
----
public class Customer {

    public String getFirstName() { ... }

    public String getSurname() { ... }

    public CreditRating getCreditRating() { ... }
}
----

Note that the framework provides a separate and more powerful mechanism
for internationalisation.





== anchor:reference-annotations_manpage-PropertyLayout[]`renderedAsDayBefore()`

IMPORTANT: WIP ... this section

A rendering hint, instructing the viewer that the date should as one day prior to the actually stored date.

This is intended to be used so that an exclusive end date of an interval can be rendered as 1 day before the actual value stored.

For example:

[source,java]
----
public LocalDate getStartDate() { ... }

@RenderedAsDayBefore
public LocalDate getEndDate() { ... }
----

Here, the interval of the [1-may-2013,1-jun-2013) would be rendered as the dates 1-may-2013 for the start date but using 31-may-2013 (the day before) for the end date.

What is stored in the domain object, itself, however, the value stored is 1-jun-2013.







== anchor:reference-annotations_manpage-PropertyLayout[]`typicalLength()`

IMPORTANT: WIP ... this section


The `@TypicalLength` annotation indicates the typical length of a `String` property or `String` parameter in an action. It can also be specified for string-based value types.

The information is generally used by the viewing mechanism to determine the space that should be given to that property or parameter in the appropriate view. If the typical length is the same as the `@MaxLength` <!--(see ?)--> then there is no need to specify `@TypicalLength` as well. If the value specified is zero or negative then it will be ignored.

For example:

[source,java]
----
public class Customer {
    @MaxLength(30)
    @TypicalLength(20)
    public String getFirstName() { ... }
    public void setFirstName(String firstName) { ... }
}
----

