[[_ug_reference-annotations_manpage-Action_domainEvent]]
= domainEvent()
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



Every interaction with a domain object action causes multiple events to be fired, in the following phases:

* hide phase: to check that the action is visible (has not been hidden)
* disable phase: to check that the action is usable (has not been disabled)
* validate phase: to check that the action's arguments are valid
* pre-execute phase: before the invocation of the action
* post-execute: after the invocation of the action


Subscribers subscribe through the xref:_ug_reference-services-api_manpage-EventBusService[`EventBusService`] using either link:https://github.com/google/guava[Guava] or link:http://www.axonframework.org/[Axon Framework] annotations and can influence each of these phases.

By default the event raised is `ActionDomainEvent.Default`. For example:

[source,java]
----
public class ToDoItem {
    ...
    @Action()
    public ToDoItem completed() { ... }
}
----


This attribute allows a custom subclass to be declared.

[NOTE]
====
This attribute replaces the deprecated `@ActionInteraction` annotation.
====

For example:

[source,java]
----
public class ToDoItem {
    public static class CompletedEvent extends AbstractActionDomainEvent {
        private static final long serialVersionUID = 1L;
        public CompletedEvent(
                final ToDoItem source,
                final Identifier identifier,
                final Object... arguments) {
            super("completed", source, identifier, arguments);
        }
    }
    @Action(domainEvent=CompletedEvent.class)
    public ToDoItem completed() { ... }
}
----

The benefit is that subscribers can be more targetted as to the events that they subscribe to.




== Subscribers

Subscribers (which must be domain services) subscribe using either the Guava API or (if the xref:_ug_reference-services-api_manpage-EventBusService[`EventBusService`] has been appropriately configured) using the AxonFramework API.

Subscribers can be either coarse-grained (if they subscribe to the top-level event type):

[source,java]
----
@DomainService
public class SomeSubscriber {
    @Programmatic
    @com.google.common.eventbus.Subscribe
    public void on(ActionInteractionEvent ev) {
        ...
    }
}
----

or can be fine-grained by subscribing to specific event subtypes:

[source,java]
----
@DomainService
public class SomeSubscriber {
    @Programmatic
    @com.google.common.eventbus.Subscribe
    public void on(ToDoItem.CompletedEvent ev) {
        ...
    }
}
----

[NOTE]
====
If the AxonFramework is being used, replace `@com.google.common.eventbus.Subscribe` for `@org.axonframework.eventhandling.annotation.EventHandler`.
====


The subscriber's method is called (up to) 5 times:

* whether to veto visibility (hide)
* whether to veto usability (disable)
* whether to veto execution (validate)
* steps to perform prior to the action being invoked.
* steps to perform after the action has been invoked.

The subscriber can distinguish these by calling `ev.getEventPhase()`. Thus the general form is:

[source,java]
----
@Programmatic
@com.google.common.eventbus.Subscribe
public void on(ActionInteractionEvent ev) {
    switch(ev.getPhase()) {
        case HIDE:
            ...
            break;
        case DISABLE:
            ...
            break;
        case VALIDATE:
            ...
            break;
        case EXECUTING:
            ...
            break;
        case EXECUTED:
            ...
            break;
    }
}
----

Vetoing is performed by calling the appropriate method on the event:

* To hide: +
+
`ev.hide()` or `ev.veto("")`

* To disable: +
+
`ev.disable("...")` or `ev.veto("...")`

* To invalidate: +

`ev.invalidate("...")` or `ev.veto("...")`

It is also possible to abort the transaction during the executing or executed
phases by throwing an exception. If the exception is a subtype of `RecoverableException`
then the exception will be rendered as a user-friendly warning (eg Growl/toast)
rather than an error.




== Raising events programmatically.

Normally events are only raised for interactions through the UI. However, events can be raised programmatically by
wrapping the target object using the xref:_ug_reference-services-api_manpage-WrapperFactory[`WrapperFactory`] domain service.





