[[_ug_reference-methods_lifecycle_jdo-api]]
= Using the JDO API
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



As an alternative to relying on Isis to call lifecycle callback methods, you could instead use the JDO link:http://www.datanucleus.org/products/datanucleus/jdo/lifecycle_callbacks.html[lifecycle listener] API directly.

[NOTE]
====
We may decide to deprecate the Isis callbacks in the future because they merely duplicate this functionality already available in JDO.
====

You can gain access to the relevant JDO API using the xref:_ug_reference-services-api_manpage-IsisJdoSupport[`IsisJdoSupport`] domain service.

For example:

[source,java]
----
@DomainService(nature=NatureOfService.DOMAIN)
public class ObjectChangedListenerService
        implements javax.jdo.listener.StoreLifecycleListener {   // <1>
    @Programmatic
    @PostConstruct
    public void init() {
        getPmFactory().addInstanceLifecycleListener(this);
    }
    @Programmatic
    @PreDestroy
    public void tidyUp() {
        getPmFactory().removeInstanceLifecycleListener(this);
    }
    private PersistenceManagerFactory getPmFactory() {
        return jdoSupport.getPersistenceManager()
               .getPersistenceManagerFactory();                 // <2>
    }
    @Programmatic
    public void preStore (InstanceLifecycleEvent event) { ... }
    @Programmatic
    public void postStore (InstanceLifecycleEvent event) { ... }
    @Inject
    IsisJdoSupport jdoSupport;
}
----
<1> implement whichever callback lifecycle listeners are of interest
<2> register on the factory so set up for every subsequent session.


