[[_ug_runtime_configuration-files]]
= Configuration Files
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


When running an Isis webapp, configuration properties are read from configuration files held in the `WEB-INF` directory.

The `WEBINF/isis.properties` file is always read and must exist.

In addition, the following other properties are searched for and if present also read:

* `viewer_wicket.properties` - if the xref:_ug_wicket-viewer[Wicket UI (viewer)] is in use

* `viewer_restfulobjects.properties` - if the xref:_ug_restfulobjects-viewer[Restful Objects REST API (viewer)] is in use

* `viewer.properties` - for any shared UI configuration

* `persistor_datanucleus.properties` - assuming the JDO/DataNucleus objectstore is in use

* `persistor.properties` - for any other objectstore configuration.  This typically is used to hold `JDBC` ``URL``s

* `authentication_shiro.properties`, `authorization_shiro.properties`
+
assuming the Shiro Security is in use (but there are no security-related config properties currently; use shiro.ini for Shiro config)

* `authentication.properties`, `authorization.properties` +
+
for any other security-related config properties (but there are none currently).

You can if you wish simply store all properties in the `isis.properties` file; but we think that breaking properties out into sections is preferable.


== Specifying other components

The `isis.properties` file has three configuration properties in particular that specify the major components of Isis to use.  They are:

.Core Configuration Properties
[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(_default value_)
|Implements

|`isis.persistor`
|`_datanucleus_`
|`org.apache.isis.core.runtime.installerregistry.installerapi.` `PersistenceMechanismInstaller`

|`isis.authentication`
|`_shiro_` +
`bypass`
|`org.apache.isis.core.runtime.authentication.` `AuthenticationManagerInstaller`

|`isis.authorization`
|`_shiro_` +
`bypass`
|`org.apache.isis.core.runtime.authorization.` `AuthorizationManagerInstaller`

|===

[TIP]
====
The values "datanucleus", "shiro" etc are actually aliases for concrete implementations listed in Isis' `installer-registry.properties` file (in `isis-core-runtime.jar`).  It is -- at least in theory -- possible to specify a fully qualified class name to replace any of these components.  In practice only the two security APIs are actually simple enough for this to be viable.
====

As for the viewers, these are specified indirectly by way of the filters and servlets in the `web.xml` file (discussed xref:_ug_runtime_web-xml[below]).  However, the configuration of which viewers to initialize is declared through a context parameter:


[source,xml]
----
<context-param>
    <param-name>isis.viewers</param-name>
    <param-value>wicket,restfulobjects</param-value>
</context-param>
----

The net effect of this configuration is simply to ensure that the `viewer_wicket.properties` and/or the `viewer_restfulobjects.properties` files are read.





include::_ug_runtime_configuration-files_deployment-types.adoc[leveloffset=+1]
