[[reference-annotations_manpage-@Programmatic]]
= `@Programmatic`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `@Programmatic` annotation causes the method to be excluded completely from the Apache Isis metamodel. This means it won't appear in any UI, and it won't appear in any xref:__a_id_reference_services_api_manpage_a_code_mementoservice_code[memento]s or xref:__a_id_reference_services_api_manpage_a_code_xmlsnapshotservice_code[snapshot]s.

A common use-case is to ignore implementation-level artifacts. For example:

[source,java]
----
public class Customer implements Comparable<Customer> {
    ...
    @Programmatic
    public int compareTo(Customer c) {
        return getSalary() - c.getSalary();
    }
    ...
}
----


Note that `@Programmatic` does not simply imply `@Hidden`; it actually means that the class member will not be part of the Isis metamodel.




`@Ignore` (deprecated) is equivalent to using `@Programmatic`.

[TIP]
====
The `@Programmatic` annotation was introduced because `@Ignore` can easily clash with `@org.junit.Ignore`.
====


