[[_ug_reference-services-api_manpage-SudoService]]
= `SudoService`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

IMPORTANT: TODO



= SudoService (1.9.0-SNAPSHOT)

The `SudoService` allows the current user reported by the `DomainObjectContainer` to be temporarily changed to some
other user. This is valuable during both integration testing (eg if testing a workflow system whereby objects are
moved from one user to another) and during fixture scripts (eg setting up objects that would normally require several
users to have acted upon the objects).

The API provided by the service is:

[source,java]
----
public interface SudoService {

    void sudo(String username, final Runnable runnable);
    <T> T sudo(String username, final Callable<T> callable);
    void sudo(String username, List<String> roles, final Runnable runnable);
    <T> T sudo(String username, List<String> roles, final Callable<T> callable);
}
----

which will run the provided block of code (a `Runnable` or a `Callable`) as if the specified username and optionally
roles being returned by `DomainObjectContainer#getUser()`.

For example, in the https://github.com/isisaddons/isis-app-todoapp[todoapp] (non ASF) the `SudoService` is used to
set up todo item objects:

[source,java]
----
protected void execute(final ExecutionContext ec) {
    ...
    sudoService.sudo(getUsername(),
            new Runnable() {
                @Override
                public void run() {
                    wrap(toDoItem).completed();
                }
            });
    ...
}
----



== Registering the Service

Assuming that the `configuration-and-annotation` services installer is configured:

[source,ini]
----
isis.services-installer=configuration-and-annotation
----

then Isis core' implementation of `SudoService` service is automatically registered and injected (it is annotated with `@DomainService`) so no further configuration is required.
