[[_ug_reference-annotations_manpage-DomainServiceLayout_named]]
= `named()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `named()` attribute explicitly specifies the domain service's name, overriding the name that would normally be inferred from the Java source code.

[TIP]
====
Following the link:http://en.wikipedia.org/wiki/Don%27t_repeat_yourself[don't repeat yourself] principle, we recommend that you only use this attribute when the desired name cannot be used in Java source code.  Examples of that include a name that would be a reserved Java keyword (eg "package"), or a name that has punctuation, eg apostrophes.
====

[NOTE]
====
This attribute can also be specified for xref:_ug_reference-annotations_manpage-ActionLayout_named[actions], xref:_ug_reference-annotations_manpage-CollectionLayout_named[collections], xref:_ug_reference-annotations_manpage-PropertyLayout_named[properties], xref:_ug_reference-annotations_manpage-ParameterLayout_named[parameters], xref:_ug_reference-annotations_manpage-DomainObjectLayout_named[domain objects] and xref:_ug_reference-annotations_manpage-ViewModelLayout_named[view models].
====



For example:

[source,java]
----
@DomainService
@DomainServiceLayout(
    named="Customers")
public class CustomerRepository {
   ...
}
----


[TIP]
====
The framework also provides a separate, powerful mechanism for xref:_ug_more-advanced_i18n[internationalization].
====


