[[_ug_reference-annotations_manpage-PropertyLayout]]
= `@PropertyLayout`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The `@PropertyLayout` annotation applies to properties collecting together all UI hints within a single annotation.


The table below summarizes the annotation's attributes.

.`@Action` attributes
[cols="2,2,4", options="header"]
|===

| Attribute
| Values (default)
| Description


|xref:_ug_reference-annotations_manpage-PropertyLayout_cssClass[`cssClass()`]
|
|the css class that a property should have, to allow more targetted styling in `application.css`


|xref:_ug_reference-annotations_manpage-PropertyLayout_describedAs[`describedAs()`]
|
|description of this property, eg to be rendered in a tooltip.


|xref:_ug_reference-annotations_manpage-PropertyLayout_labelPosition[`labelPosition()`]
|
|in forms, the positioning of the label (LEFT, TOP or NONE) relative to the property value. For boolean properties it is also possible to specify RIGHT. Defaults to LEFT unless `multiLine` also specified (see below)


|xref:_ug_reference-annotations_manpage-PropertyLayout_multiLine[`multiLine()`]
|
|for string propertys, render as a text area over multiple lines. If set &gt;1, then `labelPosition` defaults to TOP unless otherwise specified.


|xref:_ug_reference-annotations_manpage-PropertyLayout_named[`named()`]
|
|the name of this property. For Java 7 this is generally required. For Java 8, the name can be inferred from the code so this attribute allows the name to be overridden.


|`namedEscaped()`
|
|whether to HTML escape the name of this property. Defaults to true.


|xref:_ug_reference-annotations_manpage-PropertyLayout_renderedAsDayBefore[`renderedAsDayBefore()`]
|
|for date propertys only, render the date as one day prior to the actually stored date (eg the end date of an open interval into a closed interval)


|xref:_ug_reference-annotations_manpage-PropertyLayout_typicalLength[`typicalLength()`]
|
|the typical entry length of a field, use to determine the optimum width for display

|===




For example:

[source,java]
----
public class ToDoItem {

    @PropertyLayout(
        cssClass="x-key",
        named="Description of this <i>item</i>",
        namedEscaped=false,
        describedAs="What needs to be done",
        labelPosition=LabelPosition.LEFT,
        typicalLength=80)
    public String getDescription() { ... }

    @PropertyLayout(
        describedAs="Additional notes",
        labelPosition=LabelPosition.TOP,
        multiLine=8)
    public String getNotes() { ... }

    ...
}
----

It is also possible to apply the annotation to actions of domain services that are acting as link:../../more-advanced-topics/how-to-01-062-How-to-decouple-dependencies-using-contributions.html[contributed properties].



As an alternative to using the `@PropertyLayout` annotation, a dynamic layout using  xref:_ug_wicket-viewer_layout_dynamic-object-layout[`.layout.json`] file can be specified; for example:

[source,javascript]
----
{
    "span": 6,
    "memberGroups": {
        "Other": {
            "members": {
                ...
                "description": {
                    "propertyLayout": {
                        "cssClass": "x-key",
                        "describedAs": "What needs to be done",
                        "labelPosition": "LEFT",
                        "typicalLength": 80
                    }
                },
                "notes": {
                    "propertyLayout": {
                        "describedAs": "Additional notes"
                        "labelPosition": "TOP",
                        multiLine=8
                    }
                },
                ....
            }
        },
        ...
    }
}
----

[TIP]
.Specifying a default setting for label positions
====
If you want a consistent look-n-feel throughout the app, eg all property labels to the top, then it'd be rather
frustrating to have to annotate every property.

Instead, a default can be specified in `isis.properties`:

[source,ini]
----
isis.viewers.propertyLayout.labelPosition=TOP
----

or

[source,ini]
----
isis.viewers.propertyLayout.labelPosition=LEFT
----

If these are not present then Isis will render according to internal defaults. At the time of writing, this means labels are to the left for all datatypes except multiline strings.
====


IMPORTANT: TODO - ensure these properties are in the runtime config chapter





include::_ug_reference-annotations_manpage-PropertyLayout_cssClass.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_describedAs.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_labelPosition.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_multiLine.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_named.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_renderedAsDayBefore.adoc[leveloffset=+1]
include::_ug_reference-annotations_manpage-PropertyLayout_typicalLength.adoc[leveloffset=+1]






