= JDO/Datanucleus Objectstore
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

IMPORTANT: WIP...

These configuration properties are typically stored in `WEB-INF/persistor_datanucleus.properties`.  However, you can place all configuration properties into `WEB-INF/isis.properties` if you wish (the configuration properties from all config files are merged together).

.JDO/DataNucleus Objectstore Configuration Properties
[cols="2a,1,3a", options="header"]
|===
|Property
|Value +
(_default value_)
|Description

|`isis.persistor.datanucleus.` +
`impl.*`
|
| Passed through directly to Datanucleus (with `isis.persistor.datanucleus.impl` prefix stripped)


        // run-in memory
        addDataNucleusProperty("javax.jdo.option.ConnectionURL", "jdbc:hsqldb:mem:test");
        addDataNucleusProperty("javax.jdo.option.ConnectionDriverName", "org.hsqldb.jdbcDriver");
        addDataNucleusProperty("javax.jdo.option.ConnectionUserName", "sa");
        addDataNucleusProperty("javax.jdo.option.ConnectionPassword", "");

        // Don't do validations that consume setup time.
        addDataNucleusProperty(PropertyNames.PROPERTY_SCHEMA_AUTOCREATE_ALL, "true");
        addDataNucleusProperty(PropertyNames.PROPERTY_SCHEMA_VALIDATE_ALL, "false");

        // other properties as per WEB-INF/persistor_datanucleus.properties
        addDataNucleusProperty("datanucleus.persistenceByReachabilityAtCommit", "false");
        addDataNucleusProperty("datanucleus.identifier.case", "MixedCase");
        addDataNucleusProperty("datanucleus.cache.level2.type","none");
        addDataNucleusProperty("datanucleus.cache.level2.mode","ENABLE_SELECTIVE");

        // automatically install any fixtures that might have been registered
        add(DataNucleusObjectStore.INSTALL_FIXTURES_KEY , "true");

        add(PersistenceConstants.ENFORCE_SAFE_SEMANTICS, ""+PersistenceConstants.ENFORCE_SAFE_SEMANTICS_DEFAULT);

        add("isis.deploymentType", "server_prototype");



|`isis.persistor.datanucleus.impl` +
`.datanucleus.persistenceByReachabilityAtCommit
|false
|We recommend this setting is disabled.  +
Further <<_disabling_persistence_by_reachability, discussion below>>.

|`isis.persistor.datanucleus.` +
`RegisterEntities.packagePrefix`
| fully qualified package names (CSV)
| of class names; specifies the entities early rather than allow DataNucleus to find the entities lazily.  Strongly recommended (subtle issues can sometimes arise if lazy discovery is used).
Further <<_registering_entity_types, discussion below>>.

|`isis.persistor.datanucleus.` +
`PublishingService.serializedForm`
| zipped
|

|===

include::_user-guide_reference_configuration-properties_datanucleus-objectstore_disabling-persistence-by-reachability.adoc[leveloffset=+1]

include::_user-guide_reference_configuration-properties_datanucleus-objectstore_eagerly-registering-entities.adoc[leveloffset=+1]
