= Settings Service
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

[NOTE]
====
This service (both its API and implementation) are entirely independent of Apache Isis, being part of the http://github.com/isisaddons/isis-module-settings}[Isis addons' Settings module] (non-ASF).  The service is documented here for your convenience.
====

== Application Settings

=== API

IMPORTANT: TODO

=== Implementation

In the case of `ApplicationSettingsService`, the service is implemented by `ApplicationSettingsServiceJdo`, with the `ApplicationSetting` interface implemented by a `ApplicationSettingsJdo` entity.

The service also provides the ability to create list all existing settings, create new settings (of whichever datatype), update settings, and to delete settings.

These actions can be hidden using security if need be.

== User Settings

=== API

IMPORTANT: TODO

=== Implementation

In the case of `UserSettingsService`, the service is implemented by `UserSettingsServiceJdo`, with the `UserSetting` interface implemented by a `UserSettingsJdo` entity.

As for application settings, the user settings service also provides the ability to create list all existing settings, create new settings (of whichever datatype), update settings, and to delete settings.

These actions can be hidden using security if need be.


== Registration and Configuration

The `ApplicationSettingsServiceJdo` class and `UserSettingsServiceJdo` are annotated with `@DomainService` and so are automatically registered with the framework, with actions appearing on the secondary menu bar.

IMPORTANT: TODO - screenshot of settings menu

All actions from the services emit domain events.  If you wish to hide/disable these default actions in your application, we recommend using up a subscriber on the actions' domain events to veto their visibility/usability.


