= Properties and Files
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/

IMPORTANT: TODO

Isis' own configuration properties are simple key-value pairs, typically held in the `WEBINF/isis.properties` file.  This section explains which other config files are read, and identifies the most important configuration properties.

A full list of all configuration properties can be found in the <<_configuration_properties,reference>> section of this manual.

== Configuration Properties


== Files

When running an Isis webapp, configuration properties are read from configuration files held in the `WEB-INF` directory.

The `WEBINF/isis.properties` file is always read and must exist.

In addition, the following other properties are searched for and if present also read:

* `viewer_wicket.properties` - if the Wicket UI (viewer) is in use
* `viewer_restfulobjects.properties` - if the Restful Objects REST API (viewer) is in use
* `viewer.properties` - for any shared UI configuration
* `persistor_datanucleus.properties` - assuming the JDO/DataNucleus objectstore is in use
* `persistor.properties` - for any shared objectstore configuration.  This typically is used to hold `JDBC` ``URL``s

You can if you wish simply store all properties in the `isis.properties` file; but we think that breaking properties out into sections is preferable.

== Deployment Types


=== Configuring Isis to use Shiro

For more on some specific use cases, see <<Configuring Shiro>>




== Configuring the Integration Tests

Integration tests are configured programmatically, with a default set of properties to bootstrap the JDO/DataNucleus objectstore using an HSQLDB in-memory database.

These can be overridden by subclassing `IsisConfigurationForJdoIntegTests`.



