= Extending the Wicket viewer
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/


The Wicket viewer allows you to customize the GUI in several (progressively more sophisticated) ways:

* by <<_tweak_the_ui_with_css, tweaking the UI using CSS>>
* by <<_tweak_the_ui_with_javascript, tweaking the UI using Javascript>>
* by writing a <<_writing_a_custom_theme, custom bootstrap theme>>
* by <<_replacing_page_elements, replacing elements of the page>> using the `ComponentFactory` interface
* by implementing <<_custom_pages, replacement page implementations>> for the standard page types

The first two of these options are discussed in the <<Wicket Viewer>> chapter.  This chapter describes the remaining "heavier-weight/more powerful" options.




== Custom Bootstrap theme

The Isis Wicket viewer uses http://getbootstrap.com/[Bootstrap] styles and components (courtesy of the https://github.com/l0rdn1kk0n/wicket-bootstrap[Wicket Bootstrap] integration).

By default the viewer uses the default bootstrap theme. It is possible to configure the Wicket viewer to allow the user to <<_showing_a_theme_chooser, select other themes>> provided by http://bootswatch.com[bootswatch.com], and if required one of these can be <<_specifying_a_default_theme, set as the default>>.

However, you may instead want to write your own custom theme, for example to fit your company's look-n-feel/interface guidelines. This is done by implementing https://github.com/l0rdn1kk0n/wicket-bootstrap[Wicket Bootstrap]’s `de.agilecoders.wicket.core.settings.ITheme` class. This defines:

* the name of the theme
* the resources it needs (the CSS and optional JS and/or fonts), and
* optional urls to load them from a Content Delivery Network (CDN).

To make use of the custom `ITheme` the application should register it by adding the following snippet in
(your application's subclass of) `IsisWicketApplication`:

[source,java]
----
public void init() {
    ...
    IBootstrapSettings settings = new BootstrapSettings();
    ThemeProvider themeProvider = new SingleThemeProvider(new MyTheme());
    settings.setThemeProvider(themeProvider);
    Bootstrap.install(getClass(), settings);
}
----



== Replacing page elements

Replacing elements of the page is the most powerful general-purpose way to customize the look-n-feel of the viewer.  Examples at http://www.isisaddons.org[Isis Add-ons] include the link:isisaddons/isis-wicket-gmap3.html[gmap3], link:isisaddons/isis-wicket-fullcalendar2.html[calendar], link:isisaddons/isis-wicket-excel.html[excel download] and link:isisaddons/isis-wicket-wickedcharts.html[charting] integrations.

The pages generated by Isis' Wicket viewer are built up of numerous elements, from fine-grained widgets for property/parameter fields, to much larger components that take responsibility for rendering an entire entity entity, or a collection of entities. Under the covers these are all implementations of the the Apache Wicket `Component` API. The larger components delegate to the smaller, of course.

=== How the Wicket viewer selects components

Components are created using Isis' `ComponentFactory` interface, which are registered in turn through the `ComponentFactoryRegistrar` interface. Every component is categorizes by type (the `ComponentType` enum), and Isis uses this to determine which `ComponentFactory` to use. For example, the `ComponentType.BOOKMARKED_PAGES` is used to locate the `ComponentFactory` that will build the bookmarked pages panel.

Each factory is also handed a model (an implementation of `org.apache.wicket.IModel`) appropriate to its `ComponentType`; this holds the data to be rendered. For example, `ComponentType.BOOKMARKED_PAGES` is given a `BookmarkedPagesModel`, while `ComponentType.SCALAR_NAME_AND_VALUE` factories are provided a model of type of type `ScalarModel` .

In some cases there are several factories for a given `ComponentType`; this is most notably the case for `ComponentType.SCALAR_NAME_AND_VALUE`. After doing a first pass selection of candidate factories by `ComponentType`, each factory is then asked if it `appliesTo(Model)`. This is an opportunity for the factory to check the model itself to see if the data within it is of the appropriate type.

Thus, the `BooleanPanelFactory` checks that the `ScalarModel` holds a boolean, while the `JodaLocalDatePanelFactory` checks to see if it holds `org.joda.time.LocalDate`.

There will typically be only one `ComponentFactory` capable of rendering a particular `ComponentType`/`ScalarModel` combination; at any rate, the framework stops as soon as one is found.

[NOTE]
====
There is one refinement to the above algorithm where multiple component factories might be used to render an object; this is discussed in <<Additional Views of Collections>>, below.
====


=== How to replace a component

This design (the http://en.wikipedia.org/wiki/Chain-of-responsibility_pattern[chain of responsibility] design pattern) makes it quite straightforward to change the rendering of any element of the page. For example, you might switch out Isis' sliding bookmark panel and replace it with one that presents the bookmarks in some different fashion.

First, you need to write a `ComponentFactory` and corresponding `Component`. The recommended approach is to start with the source of the `Component` you want to switch out. For example:

[source,java]
----
public class MyBookmarkedPagesPanelFactory extends ComponentFactoryAbstract {
    public MyBookmarkedPagesPanelFactory() {
        super(ComponentType.BOOKMARKED_PAGES);
    }
    @Override
    public ApplicationAdvice appliesTo(final IModel<?> model) {
        return appliesIf(model instanceof BookmarkedPagesModel);
    }
    @Override
    public Component createComponent(final String id, final IModel<?> model) {
        final BookmarkedPagesModel bookmarkedPagesModel = (BookmarkedPagesModel) model;
        return new MyBookmarkedPagesPanel(id, bookmarkedPagesModel);
    }
}
----

and

[source,java]
----
public class MyBookmarkedPagesPanel
    extends PanelAbstract<BookmarkedPagesModel> {
   ...
}
----

Here `PanelAbstract` ultimately inherits from `org.apache.wicket.Component`.
Your new `Component` uses the information in the provided model (eg `BookmarkedPagesModel`) to know what to render.

Next, you will require a custom implementation of the `ComponentFactoryRegistrar` that registers your custom `ComponentFactory` as a replacement:

[source,java]
----
@Singleton
public class MyComponentFactoryRegistrar extends ComponentFactoryRegistrarDefault {
    @Override
    public void addComponentFactories(ComponentFactoryList componentFactories) {
        super.addComponentFactories(componentFactories);
        componentFactories.add(new MyBookmarkedPagesPanelFactory());
    }
}
----

This will result in the new component being used instead of (that is, discovered prior to) Isis' default implementation.

[WARNING]
====
Previously we suggested using "replace" rather than "add"; however this has unclear semantics for some component types; see https://issues.apache.org/jira/browse/ISIS-996[ISIS-996].
====


Finally (as for other customizations), you need to adjust the Guice bindings in your custom subclass of `IsisWicketApplication`:

[source,java]
----
public class MyAppApplication extends IsisWicketApplication {
    @Override
    protected Module newIsisWicketModule() {
        final Module isisDefaults = super.newIsisWicketModule();
        final Module myAppOverrides = new AbstractModule() {
            @Override
            protected void configure() {
                ...
                bind(ComponentFactoryRegistrar.class)
                    .to(MyComponentFactoryRegistrar.class);
                ...
            }
        };

        return Modules.override(isisDefaults).with(myAppOverrides);
    }
}
----

=== Additional Views of Collections

As explained above, in most cases Isis' Wicket viewer will search for the first `ComponentFactory` that can render an element, and use it. In the case of (either standalone or parented) collections, though, Isis will show all available views.

For example, out-of-the-box Isis provides a table view, a summary view (totals/sums/averages of any data), and a collapsed view (for `@Render(LAZILY)` collections). These are selected by clicking on the toolbar by each collection.

Additional views though could render the objects in the collection as a variety of ways. Indeed, some third-party implementations already exist:

* https://github.com/isisaddons/isis-wicket-excel[excel integration] (collection as a downloadable excel spreadsheet)
* https://github.com/isisaddons/isis-wicket-gmap3[google maps v3 integration] (render any objects with a location on a map)
* https://github.com/isisaddons/isis-wicket-wickedcharts[wicked charts integration] (barchart of any data)
* https://github.com/isisaddons/isis-wicket-fullcalendar2[full calendar integration] (render any objects with date properties on a calendar)

Registering these custom views is just a matter of adding the appropriate Maven module to the classpath. Isis uses the JDK `ServiceLoader` API to automatically discover and register the `ComponentFactory` of each such component.

If you want to write your own alternative component and auto-register, then include a file `META-INF/services/org.apache.isis.viewer.wicket.ui.ComponentFactory` whose contents is the fully-qualified class name of the custom `ComponentFactory` that you have written.

Wicket itself has lots of components available at its http://wicketstuff.org[wicketstuff.org] companion website; you might find some of these useful for your own customizations.

=== Adding a Custom Object View (eg a Dashboard)

One further use case in particular is worth highlighting; the rendering of an entire entity. Normally entities this is done using `EntityCombinedPanelFactory`, this being the first `ComponentFactory` for the `ComponentType.ENTITY` that is registered in Isis default `ComponentFactoryRegistrarDefault`.

You could, though, register your own `ComponentFactory` for entities that is targeted at a particular class of entity - some sort of object representing a dashboard, for example. It can use the `EntityModel` provided to it to determine the class of the entity, checking if it is of the appropriate type. Your custom factory should also be registered before the `EntityCombinedPanelFactory` so that it is checked prior to the default `EntityCombinedPanelFactory`:

[source,java]
----
@Singleton
public class MyComponentFactoryRegistrar extends ComponentFactoryRegistrarDefault {
    @Override
    public void addComponentFactories(ComponentFactoryList componentFactories) {
        componentFactories.add(new DashboardEntityFactory());
        ...
        super.addComponentFactories(componentFactories);
        ...
    }
}
----



== Custom pages

In the vast majority of cases customization should be sufficient by link:./customizing-the-viewer.html[replacing elements of a page]. However, it is also possible to define an entirely new page for a given page type.

Isis defines eight page types (see the `org.apache.isis.viewer.wicket.model.models.PageType` enum):

.PageType enum
[cols="1,4", options="header"]
|===
| Page type
| Renders

| SIGN_IN
| The initial sign-in page

| HOME
| The home page, displaying either the welcome message or dashboard

| ABOUT
| The about page, accessible from link top-right

| ENTITY
| Renders a single entity or view model

| STANDALONE_COLLECTION
| Page rendered after invoking an action that returns a collection of entites

| VALUE
| After invoking an action that returns a value type (though not URLs or Blob/Clobs, as these are handled appropriately automatically).

| VOID_RETURN
| After invoking an action that is `void`

| ACTION_PROMPT
| (No longer used).

|===


The `PageClassList` interface declares which class (subclass of `org.apache.wicket.Page` is used to render for each of these types.  For example, Isis' `WicketSignInPage` renders the signin page.

To specify a different page class, create a custom subclass of `PageClassList`:

[source,java]
----
@Singleton
public class MyPageClassList extends PageClassListDefault {
    protected Class<? extends Page> getSignInPageClass() {
        return MySignInPage.class;
    }
}
----


You then need to register your custom `PageClassList`.  This is done by adjusting the Guice bindings (part of Isis' bootstrapping) in your custom subclass of `IsisWicketApplication`:

[source,java]
----
public class MyAppApplication extends IsisWicketApplication {
    @Override
    protected Module newIsisWicketModule() {
        final Module isisDefaults = super.newIsisWicketModule();
        final Module myAppOverrides = new AbstractModule() {
            @Override
            protected void configure() {
                ...
                bind(PageClassList.class).to(MyPageClassList.class);
                ...
            }
        };
        return Modules.override(isisDefaults).with(myAppOverrides);
    }
}
----




== Isis Addons Extensions

IMPORTANT: TODO

[WARNING]
====
Note that Isis addons, while maintained by Isis committers, are not part of the ASF.
====



