{
  __type(name: "BlobInput") {
    kind
    name
    description
    inputFields {
      name
      description
      type {
        kind
        name
        ofType {
          kind
          name
        }
      }
    }
  }
}
