= `default...()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `default...()` supporting method is called for action parameters to return the initial argument value.
This may be some sensible default (eg today's date, or 0 or 1), or -- for an action that is modifying the state of an object -- might default to the current value of a corresponding property.

The method is _also_ called for properties in the case when an object is newly instantiated using xref:rg:svc:rgsvc.adoc#_rgsvc_core-domain-api_RepositoryService[`RepositoryService#instantiate(...)`] or xref:rg:svc:rgsvc.adoc#_rgsvc_core-domain-api_FactoryService[`FactoryService#instantiate(...)`].
This is a much less common use case.
If a default is not specified then properties are initialized to a default based on their type (eg 0 or `false`).

The signature of the supporting method depends on whether it is for an action parameter or a property.


== Parameters

For an action parameter in (0-based position n), and of type `T`, the signature is:

[source,java]
----
public T defaultNXxx() { ... }
----


For example:

[source,java]
----
public class ShoppingCartItem {
    @Property(editing=Editing.DISABLED)
    public Product getProduct() { ... }
    public void setProduct(Product product) { ... }

    @Property(editing=Editing.DISABLED)
    public int getQuantity() { ... }
    public void setQuantity(int quantity) { ... }

    @Action(semantics=SemanticsOf.IDEMPOTENT)
    public ShoppingCartItem updateProduct(
        Product product,
        @ParameterLayout(named="Quantity")
        final Integer quantity) {
        setProduct(product);
        setQuantity(quantity);
    }
    public Product default0UpdateProduct() {    // <1>
        return getProduct();
    }
    public int default1UpdateProduct() {        // <2>
        return getQuantity();
    }
    ...
}
----
<1> default the 0-th parameter using the current value of the `product` property
<2> default the 1-th parameter using the current value of the `quantity` property



Defaults are also supported (of course) for xref:ug:fun:how-tos/contributed-members.adoc[contributed actions].
For example, here is a contributed action for updating category/subcategory of the (non-ASF) http://github.com/isisaddons/isis-app-todoapp[Isis addons' todoapp]:

[source,java]
----
@DomainService(nature = NatureOfService.VIEW_CONTRIBUTIONS_ONLY)
public class UpdateCategoryContributions ... {
    @ActionLayout(
            describedAs = "Update category and subcategory"
    )
    @Action(semantics = SemanticsOf.IDEMPOTENT)
    public Categorized updateCategory(
            final Categorized item,                              // <1>
            final Category category,
            @Nullable final Subcategory subcategory) {
        item.setCategory(category);
        item.setSubcategory(subcategory);
        return item;
    }
    public Category default1UpdateCategory(                     // <2>
            final Categorized item) {
        return item != null? item.getCategory(): null;
    }
    public Subcategory default2UpdateCategory(                  // <3>
            final Categorized item) {
        return item != null? item.getSubcategory(): null;
    }
}
----
<1> `ToDoItem` implements `Categorized`
<2> defaults the 1-th parameter using the item's `category` property
<3> defaults the 2-th parameter using the item's `subcategory` property


=== Dependent Defaults

Action parameters also support the notion of dependent defaults, whereby the value of a default is dependent upon the value of some other previous argument.

In this example we can default the `gross` argument based on the previous `net` and `vat` arguments:

[source,java]
----
public int add(final Integer net, final Integer vat, final Integer gross) {
    return net + vat;
}

public Integer default2Add(final Integer net, final Integer val) {
    if(net == null || val == null) { return null; }
    return net + val;
}
----

As a more complex example (taken from the (non-ASF) http://github.com/isisaddons/isis-app-kitchensink[Isis addons' kitchensink] app), we can default the NFL region from the NFL league, and then the NFL team based on the region:

[source,java]
----
public NflPlayer updateUsingEntity(
        final NflLeague league,
        @Nullable final NflRegion region,
        @Nullable final NflTeamEntity nflTeamEntity) {

    setLeague(league);
    setRegion(region);
    setTeamEnum(NflTeamEnum.lookup(nflTeamEntity));
    setTeamEntity(nflTeamEntity);

    return this;
}

public List<NflRegion> choices1UpdateUsingEntity(final NflLeague league) {
    return NflRegion.thoseFor(league);
}
public List<NflTeamEntity> choices2UpdateUsingEntity(final NflLeague league, final NflRegion region) {
    return nflTeams.thoseFor(region);
}
public NflLeague default0UpdateUsingEntity() {
    return getLeague();
}
public NflRegion default1UpdateUsingEntity(final NflLeague nflLeague) {
    return choices1UpdateUsingEntity(nflLeague).stream()
            .findFirst().orElse(null);
}
public NflTeamEntity default2UpdateUsingEntity(
                                final NflLeague league, final NflRegion region) {
    return choices2UpdateUsingEntity(league, region).stream()
            .findFirst().orElse(null);
}
----

In fact, in the example above the two `defaultNxxx` methods are not required; if a choices exists then the Wicket viewer will (now) ensure that the selected argument is compatible with the choices, and reset the argument to an empty value otherwise.


== Properties

For a property of type `T`, the signature is:

[source,java]
----
public T defaultXxx() { ... }
----


For example:

[source,java]
----
public class ShoppingCartItem {
    public int getQuantity() { ... }
    public void setQuantity(int quantity) { ... }

    public int defaultProduct() {
        return 1;
    }
----


=== Alternatives

There are, in fact, two other ways to set properties of a newly instantiated object to default values.

The first is to use the xref:rg:cms:methods/lifecycle/created.adoc[`created()`] callback, called by the framework when xref:rg:svc:rgsvc.adoc#_rgsvc_core-domain-api_RepositoryService[`RepositoryService#instantiate(...)`] or xref:rg:svc:rgsvc.adoc#_rgsvc_core-domain-api_FactoryService[`FactoryService#instantiate(...)`] is called.
This method is called after any services have been injected into the domain object.

The second is more straightforward: simply initialize properties in the constructor.
However, this cannot use any injected services as they will not have been initialized.

