= `validateAddTo...()` (deprecated)
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `validateAddTo...()` supporting method is called whenever an object is to be added to a collection. Its purpose is to validate the proposed object and possibly veto the change.


[NOTE]
====
Directly mutable collections are not currently supported by the xref:ug:vw:about.adoc[Wicket viewer].
The suggested workaround is to simply define an action.
====


The signature of the supporting method for a collection with element type `E` is:

[source,java]
----
public String validateAddToXxx(E element) { /* ... */ }
----

where the returned string is the reason the collection modification invocation is vetoed (or `null` if not vetoed).  Apache Isis' xref:ug:btb:i18n.adoc[i18n support] extends this so that reasons can be internationalized if required.


For example:

[source,java]
----
public class LibraryMember {
    public SortedSet<Book> getBorrowed() { /* ... */ }
    public void setBorrowed(SortedSet<Book> borrowed) { /* ... */ }
    public String validateAddToBorrowed(Book book) {
        return book.isReference()? "Reference books cannot be borrowed": null;
    }
    public void validateRemoveFromBorrowed(Book book) { /* ... */ }
    ...
}
----


See also xref:rg:cms:methods/prefixes/addTo.adoc[`addTo...()`] and  xref:rg:cms:methods/prefixes/validateRemoveFrom.adoc[`validateRemoveFrom...()`]`

