[[headless-access]]
= Headless access

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:

This section tackles the topic of enabling access to an Apache Isis application directly, or at least, not through either the xref:vw:ROOT:about.adoc[Wicket] or xref:vro:ROOT:about.adoc[Restful] viewers.

There are a number of use-cases:

* integration from other systems, eg for a subscriber on a pub/sub mechanism such as Camel, pushing changes through an Apache Isis domain model.

* leveraging an Apache Isis application within a batch process

Note that the calling thread runs in the same process space as the Apache Isis domain object model (must be physically linked to the JAR files containing the domain classes).
For use cases where the calling thread runs in some other process space (eg migrating data from a legacy system), then the xref:vro:ROOT:about.adoc[Restful Objects viewer] is usually the way to go.

The key to headless access is the `IsisInteractionFactory` service, a singleton managed by Spring.
Use it as follows:

[source,java]
----
@Service
@lombok.RequiredArgsConstructor(onConstructor_ = { @Inject })
private static class HeadlessAccess {

    final IsisInteractionFactory isisInteractionFactory;
    final TransactionService transactionService;

    @Override
    public R call(AuthenticationSession session, Supplier<R> supplier) {
        return isisInteractionFactory.callAuthenticated(session, () -> {
            return transactionService.executeWithinTransaction(() -> {
                    return supplier.get();
                });
        });
    }
}
----

The API described here is reasonably low-level, allowing code to interact very directly with the Apache Isis metamodel and runtime.
Such callers should be considered trusted: they do not (by default) honour any business rules eg implicit in the Isis annotations or hide/disable/validate methods.

