/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package org.apache.isis.applib.util;

import org.junit.Assert;
import org.junit.rules.ExpectedException;
import org.junit.Test;

import java.lang.reflect.Array;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import com.diffblue.deeptestutils.CompareWithFieldList;
import com.diffblue.deeptestutils.Reflector;

public class TitleBuffertruncate001Test {

  @org.junit.Rule
  public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: org/apache/isis/applib/util/TitleBuffer.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 1 (line 447)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 6 (line 450)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 7 (line 451)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 8 (line 453)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 9 (line 453)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 11 (line 453)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 12 (line 454)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 13 (line 454)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 15 (line 455)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 16 (line 457)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 17 (line 459)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 18 (line 459)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 20 (line 460)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 21 (line 462)
   * This test covers `org.apache.isis.applib.util.TitleBuffer truncate(int)' block 22 (line 464)

   */

  @Test
  public void org_apache_isis_applib_util_TitleBuffer_truncate_001_6089b85b64e1c3a5() throws Throwable {

    org.apache.isis.applib.util.TitleBuffer retval;
    {
      /* Arrange */
      org.apache.isis.applib.util.TitleBuffer param_1 = (org.apache.isis.applib.util.TitleBuffer) Reflector.getInstance("org.apache.isis.applib.util.TitleBuffer");
      Reflector.setField(param_1, "title", new StringBuilder(" %$$$$$$$"));
      int noWords = 1;

      /* Act */
      retval = param_1.truncate(noWords);
    }
    {
      /* Assert result */
      Assert.assertNotNull(retval);
      Assert.assertNotNull(((StringBuilder) Reflector.getInstanceField(retval, "title")));
      Assert.assertNotNull(((StringBuilder) Reflector.getInstanceField(retval, "title")));
      Assert.assertEquals("...", ((StringBuilder) Reflector.getInstanceField(retval, "title")).toString());
    }
  }
}
