= AutoCompleteGeneratedQueryService
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Programmatic access to the autocomplete functionality defined declaratively by _Property#queryDslAutoComplete()_ and can be fine-tuned using the `queryDslAutoCompleteXxx...()` attributes in xref:refguide:applib:index/annotation/DomainObject.adoc[DomainObject] .

== API

[source,java]
.AutoCompleteGeneratedQueryService.java
----
interface AutoCompleteGeneratedQueryService {
  List<T> autoComplete(Class<T> cls, String searchPhrase)     // <.>
  List<T> autoComplete(Class<T> cls, String searchPhrase, Function<PathBuilder<T>, Predicate> additionalExpression)     // <.>
  List<T> executeQuery(Class<T> cls, String searchPhrase)     // <.>
  List<T> executeQuery(Class<T> cls, String searchPhrase, Function<PathBuilder<T>, Predicate> additionalExpression)     // <.>
}
----

<.> xref:#autoComplete_Class_String[autoComplete(Class, String)]
+
--
Convenience method for programmatically delegate to the generated facet query
--
<.> xref:#autoComplete_Class_String_Function[autoComplete(Class, String, Function)]
+
--
Convenience method for programmatically delegate to the generated facet query
--
<.> xref:#executeQuery_Class_String[executeQuery(Class, String)]
+
--
Convenience method for programmatically delegate to the generated facet query
--
<.> xref:#executeQuery_Class_String_Function[executeQuery(Class, String, Function)]
+
--
Convenience method for programmatically delegate to the generated facet query
--

== Members

[#autoComplete_Class_String]
=== autoComplete(Class, String)

Convenience method for programmatically delegate to the generated facet query

[#autoComplete_Class_String_Function]
=== autoComplete(Class, String, Function)

Convenience method for programmatically delegate to the generated facet query

[#executeQuery_Class_String]
=== executeQuery(Class, String)

Convenience method for programmatically delegate to the generated facet query

[#executeQuery_Class_String_Function]
=== executeQuery(Class, String, Function)

Convenience method for programmatically delegate to the generated facet query
