:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.AbstractDomainEvent.java
----
class AbstractDomainEvent<S> {
  AbstractDomainEvent()     // <.>
  AbstractDomainEvent(final S source, final Identifier identifier)
  void setMixedIn(final Object mixedIn)     // <.>
  Object getSubject()     // <.>
  void setEventPhase(Phase phase)     // <.>
  void setIdentifier(final Identifier identifier)     // <.>
  void hide()     // <.>
  boolean isDisabled()
  void disable(final String reason)     // <.>
  void disable(final TranslatableString reason)     // <.>
  boolean isInvalid()
  void invalidate(final String reason)     // <.>
  void invalidate(final TranslatableString reason)     // <.>
  void veto(final String reason, final Object... args)     // <.>
  void veto(final TranslatableString translatableReason)     // <.>
  Object get(Object key)     // <.>
  void put(Object key, Object value)     // <.>
  String toString()
}
----

<.> xref:#AbstractDomainEvent[AbstractDomainEvent]
+
--
If used then the framework will set state via (non-API) setters.
--
<.> xref:#setMixedIn__Object[setMixedIn(Object)]
+
--
Not API - set by the framework.
--
<.> xref:#getSubject__[getSubject()]
+
--
The subject of the event, which will be either the _#getSource() source_ for a regular action, or the _#getMixedIn() mixed-in_ domain object for a mixin.
--
<.> xref:#setEventPhase__Phase[setEventPhase(Phase)]
+
--
Not API, set by the framework.
--
<.> xref:#setIdentifier__Identifier[setIdentifier(Identifier)]
+
--
Not API, set by the framework if the no-arg constructor is used.
--
<.> xref:#hide__[hide()]
<.> xref:#disable__String[disable(String)]
<.> xref:#disable__TranslatableString[disable(TranslatableString)]
<.> xref:#invalidate__String[invalidate(String)]
<.> xref:#invalidate__TranslatableString[invalidate(TranslatableString)]
<.> xref:#veto__String_Object[veto(String, Object)]
+
--
Use instead of _#hide()_ , _#disable(String)_ and _#invalidate(String)_ ; just delegates to appropriate vetoing method based upon the _#getEventPhase() phase_ .
--
<.> xref:#veto__TranslatableString[veto(TranslatableString)]
+
--
Use instead of _#hide()_ , _#disable(org.apache.isis.applib.services.i18n.TranslatableString)_ and _#invalidate(org.apache.isis.applib.services.i18n.TranslatableString)_ ; just delegates to appropriate vetoing method based upon the _#getEventPhase() phase_ .
--
<.> xref:#get__Object[get(Object)]
+
--
Obtain user-data, as set by a previous _#getEventPhase() phase_ .
--
<.> xref:#put__Object_Object[put(Object, Object)]
+
--
Set user-data, for the use of a subsequent _#getEventPhase() phase_ .
--

== Members

[#AbstractDomainEvent]
=== AbstractDomainEvent

If used then the framework will set state via (non-API) setters.

Because the xref:refguide:applib:index/events/EventObjectBase.adoc[EventObjectBase] superclass prohibits a null source, a dummy value is temporarily used.

[#setMixedIn__Object]
=== setMixedIn(Object)

Not API - set by the framework.

[#getSubject__]
=== getSubject()

The subject of the event, which will be either the _#getSource() source_ for a regular action, or the _#getMixedIn() mixed-in_ domain object for a mixin.

[#setEventPhase__Phase]
=== setEventPhase(Phase)

Not API, set by the framework.

[#setIdentifier__Identifier]
=== setIdentifier(Identifier)

Not API, set by the framework if the no-arg constructor is used.

[#hide__]
=== hide()

[#disable__String]
=== disable(String)

[#disable__TranslatableString]
=== disable(TranslatableString)

[#invalidate__String]
=== invalidate(String)

[#invalidate__TranslatableString]
=== invalidate(TranslatableString)

[#veto__String_Object]
=== veto(String, Object)

Use instead of _#hide()_ , _#disable(String)_ and _#invalidate(String)_ ; just delegates to appropriate vetoing method based upon the _#getEventPhase() phase_ .

If hiding, just pass `null` for the parameter.

[#veto__TranslatableString]
=== veto(TranslatableString)

Use instead of _#hide()_ , _#disable(org.apache.isis.applib.services.i18n.TranslatableString)_ and _#invalidate(org.apache.isis.applib.services.i18n.TranslatableString)_ ; just delegates to appropriate vetoing method based upon the _#getEventPhase() phase_ .

If hiding, just pass `null` for the parameter.

[#get__Object]
=== get(Object)

Obtain user-data, as set by a previous _#getEventPhase() phase_ .

[#put__Object_Object]
=== put(Object, Object)

Set user-data, for the use of a subsequent _#getEventPhase() phase_ .
