= `PropertyDomainEvent`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


Subclass of xref:rg:cms:rgcms.adoc#_rgcms_classes_domainevent_AbstractDomainEvent[`AbstractDomainEvent`] for properties.

The class has a couple of responsibilities (in addition to those it inherits):

* capture the target object being interacted with

* capture the old and new values of the property


The class itself is instantiated automatically by the framework whenever interacting with a rendered object's property.


== API

The API of the class is:

[source,java]
----
public abstract class PropertyDomainEvent<S,T> extends AbstractDomainEvent<S> {

    public static class Default                                 // <1>
        extends PropertyDomainEvent<Object, Object> { ... }
    public static class Noop                                    // <2>
        extends PropertyDomainEvent<Object, Object> { ... }
    public static class Doop                                    // <3>
        extends PropertyDomainEvent<Object, Object> { ... }

    public T getOldValue();                                     // <4>
    public T getNewValue();                                     // <5>
}
----
<1> The `Default` nested static class is the default for the xref:rg:ant:Property/domainEvent.adoc[`@Property#domainEvent()`] annotation attribute.
Whether this raises an event or not depends upon the
`isis.reflector.facet.propertyAnnotation.domainEvent.postForDefault` configuration property.
<2> The `Noop` class is provided as a convenience to indicate that an event should _not_ be posted (irrespective of the configuration property setting).
<3> Similarly, the `Doop` class is provided as a convenience to indicate that an event _should_ be raised (irrespective of the configuration property setting).
<4> The pre-modification value of the property; populated at validate and subsequent phases.
<5> The proposed (post-modification) value of the property; populated at validate and subsequent phases
