= Documentation

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


Apache Isis uses link:https://antora.org/[Antora] and link:https://asciidoctor.org/[Asciidoc(tor)]:

* Antora is the static website generator

* _Asciidoc_ is a markup syntax and _Asciidoctor_ the tools to convert the markup into different formats.
+
HTML is the format generated by Antora, but other outputs such as PDF are also supported.

Both are open source, have an active community, and are maintained by the same company, link:https://opendevise.com/services/[OpenDevise].


== Building Docs and Website

Prerequisites:

* Node LTS
* Antora

See the link:https://docs.antora.org/antora/2.2/install/install-antora/[Antora docs] for details.

We also generate some Asciidoc files dynamically from other source code.
This requires:

* link:https://groovy.apache.org/download.html[Groovy 2.x]

* link:https://pandoc.org/installing.html[pandoc]


Also strongly recommended:

* IntelliJ link:https://plugins.jetbrains.com/plugin/7391-asciidoc[Asciidoc plugin]
+
TIP: even if you don't use IntelliJ as your primary IDE, it's worth using it for writing documentation - there's currently nothing as good as this plugin on any other editor platform, especially when it comes to Antora.

To build the website:

* use `build-site.sh`; or even better ...
* use `preview.sh`, to build and then preview in a web browser

Both scripts can be found at the root of this git repo.


