= BookmarkPolicy _(enum)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.BookmarkPolicy.java
----
enum BookmarkPolicy {
  AS_ROOT     // <.>
  AS_CHILD     // <.>
  NEVER     // <.>
  NOT_SPECIFIED     // <.>
}
----

<.> xref:#AS_ROOT[AS_ROOT]
+
--
Can be bookmarked, and is a top-level 'root' (or parent) bookmark.
--
<.> xref:#AS_CHILD[AS_CHILD]
+
--
Can be bookmarked, but only as a child or some other parent/root bookmark
--
<.> xref:#NEVER[NEVER]
+
--
An unimportant entity that should never be bookmarked.
--
<.> xref:#NOT_SPECIFIED[NOT_SPECIFIED]
+
--
Ignore the value provided by this annotation (meaning that the framework will keep searching, in meta annotations or superclasses/interfaces).
--

== Members

[#AS_ROOT]
=== AS_ROOT

Can be bookmarked, and is a top-level 'root' (or parent) bookmark.

[#AS_CHILD]
=== AS_CHILD

Can be bookmarked, but only as a child or some other parent/root bookmark

[#NEVER]
=== NEVER

An unimportant entity that should never be bookmarked.

[#NOT_SPECIFIED]
=== NOT_SPECIFIED

Ignore the value provided by this annotation (meaning that the framework will keep searching, in meta annotations or superclasses/interfaces).
