= @DomainService
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Indicates that the class should be automatically recognized as a domain service.

Also indicates whether the domain service acts as a repository for an entity, and menu ordering UI hints.

== API

[source,java]
.DomainService.java
----
@interface DomainService {
  String[] aliased() default {};     // <.>
  @Deprecated(forRemoval = true, since = "2.0.0-RC4")
NatureOfService nature() default NatureOfService.VIEW;     // <.>
}
----

<.> xref:#aliased[aliased]
+
--
Alternative logical type name(s) for the annotated type.
--
<.> xref:#nature[nature]
+
--
[WARNING]
====
[red]#_deprecated:_#

has no scope limiting effect any longer, see [CAUSEWAY-3697]
====

The nature of this service, either in the UI or REST only
--

== Members

[#aliased]
=== aliased

Alternative logical type name(s) for the annotated type.

[#nature]
=== nature

[WARNING]
====
[red]#_deprecated:_#

has no scope limiting effect any longer, see [CAUSEWAY-3697]
====

The nature of this service, either in the UI or REST only

include::hooks/DomainService_010-examples-and-usage.adoc[]

include::hooks/DomainService_021-objectType.adoc[]

include::hooks/DomainService_022-nature.adoc[]
