= Introspection _(enum)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The available policies as to how class introspection should process members, supporting methods and callback methods.

Particularly whether to consider or ignore non-public members as contributors to the meta-model (encapsulation). And also whether or not to enforce presence of the _Domain.Include_ annotation on those members.

== API

[source,java]
.Introspection.java
----
enum Introspection {
  NOT_SPECIFIED     // <.>
  AS_CONFIGURED     // <.>
  ENCAPSULATION_ENABLED     // <.>
  ANNOTATION_REQUIRED     // <.>
  ANNOTATION_OPTIONAL     // <.>
  boolean isNotSpecified()
  boolean isAsConfigured()
}
----

<.> xref:#NOT_SPECIFIED[NOT_SPECIFIED]
+
--
Ignore the value provided by this annotation (meaning that the framework will keep searching, in meta annotations or super-classes/interfaces).
--
<.> xref:#AS_CONFIGURED[AS_CONFIGURED]
+
--
Introspection should be handled as per the default introspection policy configured in `application.properties` .
--
<.> xref:#ENCAPSULATION_ENABLED[ENCAPSULATION_ENABLED]
+
--
Introspect public and non-public members, while presence of at least one appropriate domain annotation is enforced.
--
<.> xref:#ANNOTATION_REQUIRED[ANNOTATION_REQUIRED]
+
--
Introspect public members only, while presence of at least one appropriate domain annotation is enforced.
--
<.> xref:#ANNOTATION_OPTIONAL[ANNOTATION_OPTIONAL]
+
--
Introspect public members only, while presence of domain annotations is optional.
--

== Members

[#NOT_SPECIFIED]
=== NOT_SPECIFIED

Ignore the value provided by this annotation (meaning that the framework will keep searching, in meta annotations or super-classes/interfaces).

[#AS_CONFIGURED]
=== AS_CONFIGURED

Introspection should be handled as per the default introspection policy configured in `application.properties` .

If not configured, then encapsulation is disabled and presence of the _Domain.Include_ annotation is not enforced.

[#ENCAPSULATION_ENABLED]
=== ENCAPSULATION_ENABLED

Introspect public and non-public members, while presence of at least one appropriate domain annotation is enforced.

[#ANNOTATION_REQUIRED]
=== ANNOTATION_REQUIRED

Introspect public members only, while presence of at least one appropriate domain annotation is enforced.

[#ANNOTATION_OPTIONAL]
=== ANNOTATION_OPTIONAL

Introspect public members only, while presence of domain annotations is optional.
