= @MultivariateParameterSupport
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

[WARNING]
====
[red]#_deprecated:_#

likely to be phased out with later releases, while there is yet no definitive schedule
====

Indicates that a method is supporting an _Action_ parameter, while allowing for one or more than one arguments to be passed in.

Following method templates are supported to receive a xref:refguide:applib:index/annotation/MultivariateParameterSupport.adoc[MultivariateParameterSupport] annotation:

* hideNXxx
* disableNXxx
* choicesNXxx
* autoCompleteNXxx
* validateNXxx

By placing the xref:refguide:applib:index/annotation/MultivariateParameterSupport.adoc[MultivariateParameterSupport] annotation on a method, a contract with the meta-model is enforced, such that this method must be recognized by the meta-model and cannot be ignored.

It was introduced to allow compatibility with the _Apache Isis v1_ programming model and is likely going to be phased out with later releases.

== API

[source,java]
.MultivariateParameterSupport.java
----
@interface MultivariateParameterSupport {
}
----

