= NatureOfService _(enum)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

The different sorts of domain services recognized by Causeway, as specified in _DomainService#nature()_

== API

[source,java]
.NatureOfService.java
----
enum NatureOfService {
  WEB_UI
  WEB_API
  BOTH
  VIEW     // <.>
  REST     // <.>
  boolean isEnabledEverywhere()     // <.>
  boolean isEnabledForUi()     // <.>
  boolean isEnabledForWebApi()     // <.>
}
----

<.> xref:#VIEW[VIEW]
+
--
[WARNING]
====
[red]#_deprecated:_#

use _#BOTH_ instead
====
--
<.> xref:#REST[REST]
+
--
[WARNING]
====
[red]#_deprecated:_#

use _#WEB_API_ instead
====
--
<.> xref:#isEnabledEverywhere_[isEnabledEverywhere()]
+
--
Whether a service contributes its actions to both human-usable UIs and the Web APIs.
--
<.> xref:#isEnabledForUi_[isEnabledForUi()]
+
--
Whether a service contributes its actions to human-usable UIs.
--
<.> xref:#isEnabledForWebApi_[isEnabledForWebApi()]
+
--
Whether a service contributes its actions to Web APIs (REST and GraphQL)
--

== Members

[#VIEW]
=== VIEW

[WARNING]
====
[red]#_deprecated:_#

use _#BOTH_ instead
====

[#REST]
=== REST

[WARNING]
====
[red]#_deprecated:_#

use _#WEB_API_ instead
====

[#isEnabledEverywhere_]
=== isEnabledEverywhere()

Whether a service contributes its actions to both human-usable UIs and the Web APIs.

[#isEnabledForUi_]
=== isEnabledForUi()

Whether a service contributes its actions to human-usable UIs.

[#isEnabledForWebApi_]
=== isEnabledForWebApi()

Whether a service contributes its actions to Web APIs (REST and GraphQL)
