= @Title
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Used to indicate which property or properties make up the object title.

If more than one property is used, the order can be specified (using the same Dewey-decimal notation as used by `@MemberOrder`) and the string to use between the components can also be specified.

== API

[source,java]
.Title.java
----
@interface Title {
  String sequence() default "1.0";     // <.>
  String prepend() default " ";     // <.>
  String append() default "";     // <.>
  int abbreviatedTo() default Integer.MAX_VALUE;     // <.>
}
----

<.> xref:#sequence[sequence]
+
--
The order (in Dewey decimal notation) that the property annotated with xref:refguide:applib:index/annotation/Title.adoc[Title] appears with respect to other properties also annotated with xref:refguide:applib:index/annotation/Title.adoc[Title] .
--
<.> xref:#prepend[prepend]
+
--
The string to use to separate this property from any preceding properties in the title.
--
<.> xref:#append[append]
+
--
The string to append to this property if non-empty.
--
<.> xref:#abbreviatedTo[abbreviatedTo]
+
--
The length to abbreviate this title element to.
--

== Members

[#sequence]
=== sequence

The order (in Dewey decimal notation) that the property annotated with xref:refguide:applib:index/annotation/Title.adoc[Title] appears with respect to other properties also annotated with xref:refguide:applib:index/annotation/Title.adoc[Title] .

[#prepend]
=== prepend

The string to use to separate this property from any preceding properties in the title.

[#append]
=== append

The string to append to this property if non-empty.

[#abbreviatedTo]
=== abbreviatedTo

The length to abbreviate this title element to.

include::hooks/Title_010-examples-and-usage.adoc[]
