= VirtualClock _(interface)_
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

Works in connection with xref:refguide:applib:index/services/iactnlayer/InteractionService.adoc[InteractionService] , such that it allows an xref:refguide:applib:index/services/iactn/Interaction.adoc[Interaction] to run with its own simulated (or actual) time.

== API

[source,java]
.VirtualClock.java
----
interface VirtualClock {
  Instant nowAsInstant()     // <.>
  VirtualClock system()     // <.>
  VirtualClock nowAt(Instant virtualNow)     // <.>
  VirtualClock nowAt(java.time.LocalDate virtualNow)     // <.>
  VirtualClock nowAt(java.time.LocalDateTime virtualNow)
  VirtualClock nowAt(java.time.OffsetDateTime virtualNow)
  VirtualClock nowAt(java.time.ZonedDateTime virtualNow)
  VirtualClock nowAt(java.util.Date virtualNow)
  VirtualClock nowAt(org.joda.time.LocalDate virtualNow)     // <.>
  VirtualClock nowAt(org.joda.time.LocalDateTime virtualNow)     // <.>
  VirtualClock nowAt(org.joda.time.DateTime virtualNow)     // <.>
  VirtualClock frozenAt(Instant frozenAt)     // <.>
  VirtualClock frozenAt(java.time.LocalDate frozenAt)
  VirtualClock frozenAt(java.time.LocalDateTime frozenAt)
  VirtualClock frozenAt(java.time.OffsetDateTime frozenAt)
  VirtualClock frozenAt(java.time.ZonedDateTime frozenAt)
  VirtualClock frozenAt(java.util.Date frozenAt)
  VirtualClock frozenAt(org.joda.time.LocalDate frozenAt)     // <.>
  VirtualClock frozenAt(org.joda.time.LocalDateTime frozenAt)     // <.>
  VirtualClock frozenAt(org.joda.time.DateTime frozenAt)     // <.>
  VirtualClock frozenTestClock()     // <.>
  long nowAsEpochMilli()     // <.>
  LocalDate nowAsLocalDate(ZoneId zoneId)     // <.>
  LocalDate nowAsLocalDate()     // <.>
  LocalDateTime nowAsLocalDateTime(ZoneId zoneId)     // <.>
  LocalDateTime nowAsLocalDateTime()     // <.>
  OffsetDateTime nowAsOffsetDateTime(ZoneId zoneId)     // <.>
  OffsetDateTime nowAsOffsetDateTime()     // <.>
  java.util.Date nowAsJavaUtilDate()     // <.>
  java.sql.Timestamp nowAsJavaSqlTimestamp()     // <.>
  XMLGregorianCalendar nowAsXmlGregorianCalendar()     // <.>
  org.joda.time.DateTime nowAsJodaDateTime(ZoneId zoneId)     // <.>
  org.joda.time.DateTime nowAsJodaDateTime()     // <.>
  org.joda.time.LocalDateTime nowAsJodaLocalDateTime(ZoneId zoneId)     // <.>
  org.joda.time.LocalDateTime nowAsJodaLocalDateTime()     // <.>
  org.joda.time.LocalDate nowAsJodaLocalDate(ZoneId zoneId)     // <.>
  org.joda.time.LocalDate nowAsJodaLocalDate()     // <.>
}
----

<.> xref:#nowAsInstant__[nowAsInstant()]
+
--
Returns the (virtual) time as an _Instant_ .
--
<.> xref:#system__[system()]
+
--
Returns the system's default ticking clock.
--
<.> xref:#nowAt__Instant[nowAt(Instant)]
+
--
Returns a ticking clock set to virtual time _Instant_ _virtualNow_
--
<.> xref:#nowAt__java.time.LocalDate[nowAt(java.time.LocalDate)]
+
--
Returns a ticking clock set to virtual time.
--
<.> xref:#nowAt__org.joda.time.LocalDate[nowAt(org.joda.time.LocalDate)]
+
--
[WARNING]
====
[red]#_deprecated:_#

convert use java.time variant instead (Joda Time is deprecated)
====
--
<.> xref:#nowAt__org.joda.time.LocalDateTime[nowAt(org.joda.time.LocalDateTime)]
+
--
[WARNING]
====
[red]#_deprecated:_#

convert use java.time variant instead (Joda Time is deprecated)
====
--
<.> xref:#nowAt__org.joda.time.DateTime[nowAt(org.joda.time.DateTime)]
+
--
[WARNING]
====
[red]#_deprecated:_#

convert use java.time variant instead (Joda Time is deprecated)
====
--
<.> xref:#frozenAt__Instant[frozenAt(Instant)]
+
--
Always returns the time _Instant_ as given by _frozenAt_
--
<.> xref:#frozenAt__org.joda.time.LocalDate[frozenAt(org.joda.time.LocalDate)]
+
--
[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====
--
<.> xref:#frozenAt__org.joda.time.LocalDateTime[frozenAt(org.joda.time.LocalDateTime)]
+
--
[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====
--
<.> xref:#frozenAt__org.joda.time.DateTime[frozenAt(org.joda.time.DateTime)]
+
--
[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====
--
<.> xref:#frozenTestClock__[frozenTestClock()]
+
--
Always returns the time _Instant_ 2003/8/17 21:30:25 (UTC)
--
<.> xref:#nowAsEpochMilli__[nowAsEpochMilli()]
+
--
Returns the (virtual) time as the number of milliseconds since the epoch start.
--
<.> xref:#nowAsLocalDate__ZoneId[nowAsLocalDate(ZoneId)]
+
--
Returns the (virtual) time as _LocalDate_ , using the _ZoneId_ timezone.
--
<.> xref:#nowAsLocalDate__[nowAsLocalDate()]
+
--
Returns the (virtual) time as _LocalDate_ , using the _ZoneId#systemDefault() system default_ timezone.
--
<.> xref:#nowAsLocalDateTime__ZoneId[nowAsLocalDateTime(ZoneId)]
+
--
Returns the (virtual) time as _LocalDateTime_ , using the _ZoneId_ timezone.
--
<.> xref:#nowAsLocalDateTime__[nowAsLocalDateTime()]
+
--
Returns the (virtual) time as _LocalDateTime_ , using the _ZoneId#systemDefault() system default_ timezone.
--
<.> xref:#nowAsOffsetDateTime__ZoneId[nowAsOffsetDateTime(ZoneId)]
+
--
Returns the (virtual) time as _OffsetDateTime_ , using the _ZoneId_ timezone.
--
<.> xref:#nowAsOffsetDateTime__[nowAsOffsetDateTime()]
+
--
Returns the (virtual) time as _OffsetDateTime_ , using the _ZoneId#systemDefault() system default_ timezone.
--
<.> xref:#nowAsJavaUtilDate__[nowAsJavaUtilDate()]
+
--
Returns the (virtual)time as _java.util.Date_ .
--
<.> xref:#nowAsJavaSqlTimestamp__[nowAsJavaSqlTimestamp()]
+
--
Returns the (virtual) time as _java.sql.Timestamp_ .
--
<.> xref:#nowAsXmlGregorianCalendar__[nowAsXmlGregorianCalendar()]
+
--
Returns the (virtual) time as _XMLGregorianCalendar_ .
--
<.> xref:#nowAsJodaDateTime__ZoneId[nowAsJodaDateTime(ZoneId)]
+
--
[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _org.joda.time.DateTime_ , using the specified _ZoneId_ timezone.
--
<.> xref:#nowAsJodaDateTime__[nowAsJodaDateTime()]
+
--
[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _org.joda.time.DateTime_ , using the _ZoneId#systemDefault() system default_ timezone.
--
<.> xref:#nowAsJodaLocalDateTime__ZoneId[nowAsJodaLocalDateTime(ZoneId)]
+
--
[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====
--
<.> xref:#nowAsJodaLocalDateTime__[nowAsJodaLocalDateTime()]
+
--
[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _org.joda.time.LocalDateTime_ , using the _ZoneId#systemDefault() system default_ timezone.
--
<.> xref:#nowAsJodaLocalDate__ZoneId[nowAsJodaLocalDate(ZoneId)]
+
--
[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _DateTime_ , using the specified _ZoneId_ timezone.
--
<.> xref:#nowAsJodaLocalDate__[nowAsJodaLocalDate()]
+
--
[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _DateTime_ , using the _ZoneId#systemDefault() system default_ timezone.
--

== Members

[#nowAsInstant__]
=== nowAsInstant()

Returns the (virtual) time as an _Instant_ .

[#system__]
=== system()

Returns the system's default ticking clock.

[#nowAt__Instant]
=== nowAt(Instant)

Returns a ticking clock set to virtual time _Instant_ _virtualNow_

[#nowAt__java.time.LocalDate]
=== nowAt(java.time.LocalDate)

Returns a ticking clock set to virtual time.

[#nowAt__org.joda.time.LocalDate]
=== nowAt(org.joda.time.LocalDate)

[WARNING]
====
[red]#_deprecated:_#

convert use java.time variant instead (Joda Time is deprecated)
====

[#nowAt__org.joda.time.LocalDateTime]
=== nowAt(org.joda.time.LocalDateTime)

[WARNING]
====
[red]#_deprecated:_#

convert use java.time variant instead (Joda Time is deprecated)
====

[#nowAt__org.joda.time.DateTime]
=== nowAt(org.joda.time.DateTime)

[WARNING]
====
[red]#_deprecated:_#

convert use java.time variant instead (Joda Time is deprecated)
====

[#frozenAt__Instant]
=== frozenAt(Instant)

Always returns the time _Instant_ as given by _frozenAt_

[#frozenAt__org.joda.time.LocalDate]
=== frozenAt(org.joda.time.LocalDate)

[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

[#frozenAt__org.joda.time.LocalDateTime]
=== frozenAt(org.joda.time.LocalDateTime)

[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

[#frozenAt__org.joda.time.DateTime]
=== frozenAt(org.joda.time.DateTime)

[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

[#frozenTestClock__]
=== frozenTestClock()

Always returns the time _Instant_ 2003/8/17 21:30:25 (UTC)

[#nowAsEpochMilli__]
=== nowAsEpochMilli()

Returns the (virtual) time as the number of milliseconds since the epoch start.

[#nowAsLocalDate__ZoneId]
=== nowAsLocalDate(ZoneId)

Returns the (virtual) time as _LocalDate_ , using the _ZoneId_ timezone.

[#nowAsLocalDate__]
=== nowAsLocalDate()

Returns the (virtual) time as _LocalDate_ , using the _ZoneId#systemDefault() system default_ timezone.

[#nowAsLocalDateTime__ZoneId]
=== nowAsLocalDateTime(ZoneId)

Returns the (virtual) time as _LocalDateTime_ , using the _ZoneId_ timezone.

[#nowAsLocalDateTime__]
=== nowAsLocalDateTime()

Returns the (virtual) time as _LocalDateTime_ , using the _ZoneId#systemDefault() system default_ timezone.

[#nowAsOffsetDateTime__ZoneId]
=== nowAsOffsetDateTime(ZoneId)

Returns the (virtual) time as _OffsetDateTime_ , using the _ZoneId_ timezone.

[#nowAsOffsetDateTime__]
=== nowAsOffsetDateTime()

Returns the (virtual) time as _OffsetDateTime_ , using the _ZoneId#systemDefault() system default_ timezone.

[#nowAsJavaUtilDate__]
=== nowAsJavaUtilDate()

Returns the (virtual)time as _java.util.Date_ .

[#nowAsJavaSqlTimestamp__]
=== nowAsJavaSqlTimestamp()

Returns the (virtual) time as _java.sql.Timestamp_ .

[#nowAsXmlGregorianCalendar__]
=== nowAsXmlGregorianCalendar()

Returns the (virtual) time as _XMLGregorianCalendar_ .

[#nowAsJodaDateTime__ZoneId]
=== nowAsJodaDateTime(ZoneId)

[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _org.joda.time.DateTime_ , using the specified _ZoneId_ timezone.

[#nowAsJodaDateTime__]
=== nowAsJodaDateTime()

[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _org.joda.time.DateTime_ , using the _ZoneId#systemDefault() system default_ timezone.

[#nowAsJodaLocalDateTime__ZoneId]
=== nowAsJodaLocalDateTime(ZoneId)

[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

[#nowAsJodaLocalDateTime__]
=== nowAsJodaLocalDateTime()

[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _org.joda.time.LocalDateTime_ , using the _ZoneId#systemDefault() system default_ timezone.

[#nowAsJodaLocalDate__ZoneId]
=== nowAsJodaLocalDate(ZoneId)

[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _DateTime_ , using the specified _ZoneId_ timezone.

[#nowAsJodaLocalDate__]
=== nowAsJodaLocalDate()

[WARNING]
====
[red]#_deprecated:_#

use java.time variant instead (Joda Time is deprecated)
====

Returns the time as a Joda _DateTime_ , using the _ZoneId#systemDefault() system default_ timezone.
