= Annotations
include::_attributes.adoc[]


This guide describes the various annotations used by Apache Isis to provide additional metadata about the domain objects.
Most of these are defined by Isis itself, but some are from other libraries.
It also identifies a number of annotations that are now deprecated, and indicates their replacement.




== Examples

To give just a few examples of annotations supported by Apache Isis:

* if a property is read-only, then this can be annotated with `@Property(editing=EditingDISABLED)`.
* if a class has a small fixed set of instances (eg a picklist), then it can be annotated using `@DomainObject(bounded=true)`
* if a class is a domain service and should be automatically instantiated as a singleton, then it can be annotated using `@DomainService`
* if an action is idempotent, then it can be annotated using `@Action(semantics=SemanticsOf.IDEMPOTENT)`.
* if an action parameter is optional, it can be annotated using `@Parameter(optionality=Optionality.OPTIONAL)`

Some annotations act as UI hints, for example:

* if a collection should be rendered "open" rather than collapsed, it can be annotated using `@CollectionLayout(defaultView="table")`
* if an action has a tooltip, it can be annotated using `@ActionLayout(describedAs=...)`
* if a domain object is bookmarkable, it can be annotated using `@DomainObjectLayout(bookmarking=BookmarkPolicy.AS_ROOT`).


