= View Models
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


As described in the xref:ug:fun:ugfun.adoc#\_ugfun_building-blocks_types-of-domain-objects_view-models[introduction], view models are domain objects like domain entities, with behaviour and state.
However, unlike domain entities, their state is _not_ persisted to a database but is instead serialized into its identifier (in effect, its URL).

The framework provides two main ways to implement a view model:

* The more powerful/flexible approach is to use JAXB annotations; this allows the state of the object's properties and also its collections.

* The other approach is to use Apache Isis specific annotations.
While (arguably) these explain the intent of the view model better, they are more restrictive: only the state of the object's properties is serialized -- collections are ignored -- and not every datatype is recognized.

The serialized form of these view models is therefore XML, which also enables these view models to act as DTO (useful for various integration scenarios).

For these reasons we recommend that you use JAXB-style view models wherever possible.
Indeed, the legacy approach for view models may be deprecated in the future.

In the sections below we consider JAXB view models both as "regular" view models, and also when using them to act as DTOs.


include::partial$_ugfun_programming-model_view-models_jaxb.adoc[leveloffset=+1]
include::partial$_ugfun_programming-model_view-models_dto.adoc[leveloffset=+1]
include::partial$_ugfun_programming-model_view-models_non-jaxb.adoc[leveloffset=+1]
