[[_ugfun_programming-model_view-models_dto]]
= DTOs

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]


JAXB view models can also be used as DTOs.
The examples in this section uses the DTO for `ToDoItem`, taken from the (non-ASF) http://github.com/isisaddons/isis-app-todoapp[Isis addons' todoapp].

This DTO is defined as follows:

[source,java]
----
package todoapp.app.viewmodels.todoitem.v1;                         // <1>
@XmlRootElement(name = "toDoItemDto")                               // <2>
@XmlType(
        propOrder = {                                               // <3>
            "majorVersion", "minorVersion",
            "description", "category", ...
            "toDoItem", "similarItems"
        }
)
@DomainObjectLayout(
        titleUiEvent = TitleUiEvent.Doop.class                      // <4>
)
public class ToDoItemV1_1 implements Dto {                          // <5>
    @XmlElement(required = true, defaultValue = "1")                // <6>
    public final String getMajorVersion() { return "1"; }
    @XmlElement(required = true, defaultValue = "1")                // <7>
    public String getMinorVersion() { return "1"; }

    @XmlElement(required = true)                                    // <8>
    @Getter @Setter
    protected String description;
    @XmlElement(required = true)
    @Getter @Setter
    protected String category;
    ...

    @Getter @Setter                                                 // <9>
    protected ToDoItem toDoItem;
    @XmlElementWrapper                                              // <10>
    @XmlElement(name = "todoItem")
    @Getter @Setter
    protected List<ToDoItem> similarItems = Lists.newArrayList();
}
----
<1> package name encodes major version; see discussion on xref:ug:fun:ugfun.adoc#_ugfun_programming-model_view-models_dto_versioning[versioning]
<2> identifies this class as a view model and defines the root element for JAXB serialization
<3> all properties in the class must be listed; (they can be ignored using `@XmlTransient`)
<4> demonstrating use of UI events for a subscriber to provide the DTO's title; see xref:rg:ant:rgant.adoc#_rgant-DomainObjectLayout_titleUiEvent[`@DomainObjectLayout#titleUiEvent()`].
<5> class name encodes (major and) minor version; see discussion on xref:ug:fun:ugfun.adoc#_ugfun_programming-model_view-models_dto_versioning[versioning]
<6> again, see discussion on xref:ug:fun:ugfun.adoc#_ugfun_programming-model_view-models_dto_versioning[versioning]
<7> again, see discussion on xref:ug:fun:ugfun.adoc#_ugfun_programming-model_view-models_dto_versioning[versioning]
<8> simple scalar properties
<9> reference to a persistent entity; discussed xref:ug:fun:ugfun.adoc#_ugfun_programming-model_view-models_jaxb_referencing-domain-entities[here]
<10> reference to a collection of persistent entities; again discussed xref:ug:fun:ugfun.adoc#_ugfun_programming-model_view-models_jaxb_referencing-domain-entities[here]





include::_ugfun_programming-model_view-models_dto_versioning.adoc[leveloffset=+1]

include::_ugfun_programming-model_view-models_dto_generating-xsds.adoc[leveloffset=+1]

include::_ugfun_programming-model_view-models_dto_dto-consumers.adoc[leveloffset=+1]
