= `cssClass()`
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
include::_attributes.adoc[]



The `cssClass()` attribute can be used to render additional CSS classes in the HTML (a wrapping `<div>`) that represents the action.   xref:rg:cfg:application-specific/application-css.adoc[Application-specific CSS] can then be used to target and adjust the UI representation of that particular element.


For example:

[source,java]
----
public class ToDoItem {
    @ActionLayout(cssClass="x-key")
    public ToDoItem postpone(LocalDate until) { /* ... */ }
    ...
}
----

[NOTE]
====
The similar xref:rg:ant:ActionLayout/cssClassFa.adoc[`@ActionLayout#cssClassFa()`] annotation attribute is also used as a hint
to apply CSS, specifically to add http://fortawesome.github.io/Font-Awesome/icons/[Font Awesome icons] on action menu items or buttons.
====



== Alternatives

As an alternative to using the annotation, the dynamic xref:vw:ROOT:layout/file-based.adoc[file-based layout] can be used instead.

== See also

This attribute can also be applied to:

* xref:rg:ant:DomainObjectLayout/cssClass.adoc[domain objects]
* xref:rg:ant:ViewModelLayout/cssClass.adoc[view models]
* xref:rg:ant:PropertyLayout/cssClass.adoc[properties]
* xref:rg:ant:CollectionLayout/cssClass.adoc[collections]
* xref:rg:ant:ParameterLayout/cssClass.adoc[parameters].

