= ContentMappingService
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.ContentMappingService.java
----
interface ContentMappingService {
  Object map(Object object, List<MediaType> acceptableMediaTypes)     // <.>
  boolean isSupported(Class<?> clazz, List<MediaType> acceptableMediaTypes)     // <.>
  String determineDomainType(List<MediaType> acceptableMediaTypes)
}
----

<.> xref:#map_Object_List[map(Object, List)]
+
--
Typically for mapping from a domain object to a DTO.
--
<.> xref:#isSupported_Class_List[isSupported(Class, List)]
+
--
Convenience utilities for implementations of xref:refguide:applib:index/services/conmap/ContentMappingService.adoc[ContentMappingService] .
--

== Members

[#map_Object_List]
=== map(Object, List)

Typically for mapping from a domain object to a DTO.

[#isSupported_Class_List]
=== isSupported(Class, List)

Convenience utilities for implementations of xref:refguide:applib:index/services/conmap/ContentMappingService.adoc[ContentMappingService] .

include::hooks/ContentMappingService_010-implementation.adoc[]

include::hooks/ContentMappingService_020-examples-and-usage.adoc[]
