[[auto-refresh]]
= Auto-refresh page
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.


This requirement from the users mailing list:

"Suppose you want to build a monitoring application, eg for an electricity grid. Data is updated in the background (eg via the Restful Objects REST API).
What is needed is the ability to show an entity that includes a map, and have it auto-refresh every 5 seconds or so."

Here's one (somewhat crude, but workable) way to accomplish this.

* First, update the domain object to return custom CSS: +
+
[source,java]
----
public class MyDomainObject {
    ...
    public String cssClass() { return "my-special-auto-updating-entity"; }
    ...
}
----

* Then, use javascript in `scripts/application.js` (under `src/main/webapp/`) to reload:
+
[source,javascript]
----
$(function() {
    if ($(".my-special-auto-updating-entity").length) {
        setTimeout(function() {document.location.reload();}, 5000); // 1000 is 5 sec
    }
});
----
