[[_migration-notes_1.11.0-to-1.12.0]]
= From v1.12.0 to 1.13.0
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



Existing projects written against v1.12.x should run against v1.13.0 with few if any changes.  If you *do* encounter
any difficulties then let us know via the link:support.html[users mailing list], so we can support you and document
issues here.

[NOTE]
====
`1.13.0-SNAPSHOT` is currently still in development.
====



== Faster startup times

Several new configuration settings influence application startup times:

* `isis.services.applicationFeatures.init` +
+
This setting can be used to control whether the
xref:rgsvc.adoc#_rgsvc_api_ApplicationFeatureRepository[`ApplicationFeatureRepository`] domain service lazily or
eagerly initializes itself based on the framework's internal metamodel. +
+
Prior to `1.13.0` this service eagerly initialized itself, causing the framework to have to traverse the domain object
model graph for all types.  This could add noticeable overhead.  For `1.13.0` this service now initializes itself
lazily.  The previous behaviour (of eager initialization) can be re-enabled by setting this property to `eager`.

* `isis.services.injector.injectPrefix` and `isis.services.injector.setPrefix` +
+
These settings can be used to control the styles of injection of domain services that the framework supports. +
+
Prior to `1.13.0` the framework supported the injection of fields using xref:rgant.adoc#_rgant-Inject[`@Inject`], and
also injection to `set...()` setter methods and also `inject...()` methods.  In `1.13.0` the injection through `@Inject`
remains, and injection through setters is enabled by default.  Injection through `inject...()` is disabled however.
For faster start-up times still, consider disabling injection through `set...()`.
