[[_migration-notes_1.8.0-to-1.9.0_specify-all-dom-packages]]
= Specify all `dom` packages
:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:_basedir: ../
:_imagesdir: images/



Apache Isis automatically scans for certain classes on the classpath in order to configure itself.  Specifically these are:

* searching for classes annotated with xref:rg.adoc#_rg_annotations_manpage-DomainService[`@DomainService`].

* searching for classes extending xref:rg.adoc#_rg_classes_super_manpage-FixtureScript[`FixtureScript`]

* searching for classes annotated with xref:rg.adoc#_rg_annotations_manpage-PersistenceCapable[`@PersistenceCapable`].

Prior to 1.9.0 we used the link:https://github.com/ronmamo/reflections[Reflections] library to do this, which under the covers uses link:http://www.javassist.org/[Javassist].  This is a relatively heavyweight approach.

In 1.9.0 we have changed to using the link:https://github.com/lukehutch/fast-classpath-scanner[Fast-Classpath-Scanner] library, which is altogether more lightweight and has no dependencies.

Generally this change should be transparent, however you should ensure that all domain classes are correctly registered using the `isis.persistor.datanucleus.RegisterEntities.packagePrefix` key.  This should include any domain classes for addon modules.

For example, the (non-ASF) http://github.com/isisaddons/isis-app-todoapp[Isis addons' todoapp]'s configuration now reads:

[source,ini]
----
isis.persistor.datanucleus.RegisterEntities.packagePrefix=\
                todoapp.dom.module,\
                org.isisaddons.module.security.dom,\
                org.isisaddons.module.settings.dom,\
                org.isisaddons.module.sessionlogger.dom,\
                org.isisaddons.module.command.dom,\
                org.isisaddons.module.audit.dom,\
                org.isisaddons.module.publishing.dom
----
