:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

== API

[source,java]
.ExcelServiceImpl.java
----
class ExcelServiceImpl {
  @javax.inject.Inject
BookmarkService bookmarkService;
  @javax.inject.Inject
SpecificationLoader specificationLoader;
  @javax.inject.Inject
ServiceInjector serviceInjector;
  @javax.inject.Inject
ObjectManager objectManager;
  Blob toExcel(final List<T> domainObjects, final Class<T> cls, final String sheetName, final String fileName)     // <.>
  Blob toExcel(final List<T> domainObjects, final Class<T> cls, final String sheetName, final String fileName, final InputStream in)     // <.>
  Blob toExcel(WorksheetContent worksheetContent, final String fileName)     // <.>
  Blob toExcel(WorksheetContent worksheetContent, final String fileName, final InputStream in)     // <.>
  Blob toExcel(final List<WorksheetContent> worksheetContents, final String fileName)     // <.>
  Blob toExcel(final List<WorksheetContent> worksheetContents, final String fileName, final InputStream in)     // <.>
  Blob toExcelPivot(final List<T> domainObjects, final Class<T> cls, final String fileName)     // <.>
  Blob toExcelPivot(final List<T> domainObjects, final Class<T> cls, final String sheetName, final String fileName)
  Blob toExcelPivot(WorksheetContent worksheetContent, final String fileName)
  Blob toExcelPivot(final List<WorksheetContent> worksheetContents, final String fileName)
  List<T> fromExcel(final Blob excelBlob, final Class<T> cls, final String sheetName)     // <.>
  List<T> fromExcel(final Blob excelBlob, final WorksheetSpec worksheetSpec)     // <.>
  List<List<?>> fromExcel(final Blob excelBlob, final List<WorksheetSpec> worksheetSpecs)     // <.>
}
----

<.> xref:#toExcel__List_Class_String_String[toExcel(List, Class, String, String)]
+
--
Creates a Blob holding a single-sheet spreadsheet of the domain objects.
--
<.> xref:#toExcel__List_Class_String_String_InputStream[toExcel(List, Class, String, String, InputStream)]
+
--
As _#toExcel(List, Class, String, String)_ , but appends a single-sheet spreadsheet of the domain objects to an existing workbook instead of creating one.
--
<.> xref:#toExcel__WorksheetContent_String[toExcel(WorksheetContent, String)]
+
--
As _#toExcel(List, Class, String, String)_ , but with the domain objects, class and sheet name provided using a xref:refguide:subdomains:index/excel/applib/dom/WorksheetContent.adoc[WorksheetContent] .
--
<.> xref:#toExcel__WorksheetContent_String_InputStream[toExcel(WorksheetContent, String, InputStream)]
+
--
As _#toExcel(List, Class, String, String)_ , but with the domain objects, class and sheet name provided using a xref:refguide:subdomains:index/excel/applib/dom/WorksheetContent.adoc[WorksheetContent] and with an input stream.
--
<.> xref:#toExcel__List_String[toExcel(List, String)]
+
--
As _#toExcel(WorksheetContent, String)_ , but with multiple sheets.
--
<.> xref:#toExcel__List_String_InputStream[toExcel(List, String, InputStream)]
+
--
As _#toExcel(WorksheetContent, String)_ , but with multiple sheets and an input stream.
--
<.> xref:#toExcelPivot__List_Class_String[toExcelPivot(List, Class, String)]
+
--
Creates a Blob holding a single-sheet spreadsheet with a pivot of the domain objects. The sheet name is derived from the class name.
--
<.> xref:#fromExcel__Blob_Class_String[fromExcel(Blob, Class, String)]
+
--
Returns a list of objects for each line in the spreadsheet, of the specified type. The objects are read from a sheet taken as the simple name of the class.
--
<.> xref:#fromExcel__Blob_WorksheetSpec[fromExcel(Blob, WorksheetSpec)]
+
--
As _#fromExcel(Blob, Class, String)_ , but specifying the class name and sheet name by way of a xref:refguide:subdomains:index/excel/applib/dom/WorksheetSpec.adoc[WorksheetSpec] .
--
<.> xref:#fromExcel__Blob_List[fromExcel(Blob, List)]
+
--
As _#fromExcel(Blob, WorksheetSpec)_ , but reading multiple sheets (and returning a list of lists of domain objects).
--

== Members

[#toExcel__List_Class_String_String]
=== toExcel(List, Class, String, String)

Creates a Blob holding a single-sheet spreadsheet of the domain objects.

There are no specific restrictions on the domain objects; they can be either persistable entities or view models. Do be aware though that if imported back using _#fromExcel(Blob, Class, String)_ , then new instances are always created. It is generally better therefore to work with view models than to work with entities. This also makes it easier to maintain backward compatibility in the future if the persistence model changes; using view models represents a stable API for import/export.

[#toExcel__List_Class_String_String_InputStream]
=== toExcel(List, Class, String, String, InputStream)

As _#toExcel(List, Class, String, String)_ , but appends a single-sheet spreadsheet of the domain objects to an existing workbook instead of creating one.

[#toExcel__WorksheetContent_String]
=== toExcel(WorksheetContent, String)

As _#toExcel(List, Class, String, String)_ , but with the domain objects, class and sheet name provided using a xref:refguide:subdomains:index/excel/applib/dom/WorksheetContent.adoc[WorksheetContent] .

[#toExcel__WorksheetContent_String_InputStream]
=== toExcel(WorksheetContent, String, InputStream)

As _#toExcel(List, Class, String, String)_ , but with the domain objects, class and sheet name provided using a xref:refguide:subdomains:index/excel/applib/dom/WorksheetContent.adoc[WorksheetContent] and with an input stream.

[#toExcel__List_String]
=== toExcel(List, String)

As _#toExcel(WorksheetContent, String)_ , but with multiple sheets.

[#toExcel__List_String_InputStream]
=== toExcel(List, String, InputStream)

As _#toExcel(WorksheetContent, String)_ , but with multiple sheets and an input stream.

[#toExcelPivot__List_Class_String]
=== toExcelPivot(List, Class, String)

Creates a Blob holding a single-sheet spreadsheet with a pivot of the domain objects. The sheet name is derived from the class name.

Minimal requirements for the domain object are:

* One property has annotation xref:refguide:subdomains:index/excel/applib/dom/PivotRow.adoc[PivotRow] and will be used as row identifier in left column of pivot. Empty values are supported.
* At least one property has annotation xref:refguide:subdomains:index/excel/applib/dom/PivotColumn.adoc[PivotColumn] . Its values will be used in columns of pivot. Empty values are supported.
* At least one property has annotation xref:refguide:subdomains:index/excel/applib/dom/PivotValue.adoc[PivotValue] . Its values will be distributed in the pivot.

[#fromExcel__Blob_Class_String]
=== fromExcel(Blob, Class, String)

Returns a list of objects for each line in the spreadsheet, of the specified type. The objects are read from a sheet taken as the simple name of the class.

If the class is a view model then the objects will be properly instantiated, with the correct view model memento; otherwise the objects will be simple transient objects.

[#fromExcel__Blob_WorksheetSpec]
=== fromExcel(Blob, WorksheetSpec)

As _#fromExcel(Blob, Class, String)_ , but specifying the class name and sheet name by way of a xref:refguide:subdomains:index/excel/applib/dom/WorksheetSpec.adoc[WorksheetSpec] .

[#fromExcel__Blob_List]
=== fromExcel(Blob, List)

As _#fromExcel(Blob, WorksheetSpec)_ , but reading multiple sheets (and returning a list of lists of domain objects).
