[[CollectionDomainEvent]]
= `CollectionDomainEvent`

:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
:page-partial:



== API

The API of the class is:

// TODO: v2: use include::[]

[source,java]
----
public abstract class CollectionDomainEvent<S,T> extends AbstractDomainEvent<S> {

    public static class Default                                 // <.>
        extends CollectionDomainEvent<Object, Object> { }
    public static class Noop                                    // <.>
        extends CollectionDomainEvent<Object, Object> { }
    public static class Doop                                    // <.>
        extends CollectionDomainEvent<Object, Object> { }

    public T getValue();                                        // <.>
    public Of getOf();                                          // <.>
}
----
<1> The `Default` nested static class is the default for the xref:refguide:applib:index/annotation/Collection.adoc#domainEvent[@Collection#domainEvent()] annotation attribute.
Whether this raises an event or not depends upon the
`isis.reflector.facet.collectionAnnotation.domainEvent.postForDefault` configuration property.
<2> The `Noop` class is provided as a convenience to indicate that an event should _not_ be posted (irrespective of the configuration property setting).
<3> Similarly, the `Doop` class is provided as a convenience to indicate that an event _should_ be raised (irrespective of the configuration property setting).
<4> the object being added or removed
<5> whether this is to add or to remove

where the `Of` enum indicates in turn how the collection is being interacted with:

[source,java]
----
public static enum Of {
    ACCESS,         // <1>
    ADD_TO,         // <2>
    REMOVE_FROM     // <3>
}
----
<1> collection is being rendered; set during for hide and disable phases
<2> collection is being added to; set for validate, executing and executed phases
<3> or, collection is being removed from; set for validate, executing and executed phases
