:Notice: Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at. http://www.apache.org/licenses/LICENSE-2.0 . Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR  CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

This domain class is used in the demo of `@Property#executionPublishing`.

== How this demo works

This entity has two editable properties, `name` and `notes`.
One `name` property has execution publishing enabled, while the `notes` property does not.

Editing the `name` property will result in an execution representing the property edit being persisted as an `ExecutionLogEntry`; these are listed in the collection at the bottom of the page.

In terms of code:

* property with execution publishing enabled:
+
[source,java,indent=0]
.PropertyExecutionPublishingEntity.java
----
include::PropertyExecutionPublishingEntity.java[tags=published]
----
<.> makes the property editable...
<.> \... and enables execution publishing

* property with execution publishing disabled:
+
[source,java,indent=0]
..PropertyExecutionPublishingEntity.java
----
include::PropertyExecutionPublishingEntity.java[tags=not-published]
----
<.> makes the property editable...
<.> \... but execution publishing is disabled

* contributed collection showing persisted ``ExecutionLogEntry``s:
+
[source,java,indent=0]
.PropertyExecutionPublishingEntity_publishedExecutions.java
----
include::PropertyExecutionPublishingEntity_publishedExecutions.java[tags=class]
----
<.> repository provided by the _executionLog_ extension.
